;WITH CTE_WO 
AS
(
SELECT
      WO.TYPE,
       WO.BASE_ID, 
      WO.LOT_ID, 
      WO.SPLIT_ID,
      WO.SUB_ID, 
      dbo.sfnWONUMFormat(wo.BASE_ID, wo.LOT_ID, wo.SPLIT_ID, wo.SUB_ID) AS WONUM,
      WO.STATUS,
      WO.DESIRED_QTY, 
      WO.PART_ID,
      ISNULL(WO.DESIRED_RLS_DATE, 
           (SELECT WO1.DESIRED_RLS_DATE 
              FROM WORK_ORDER WO1
              WHERE wo.BASE_ID    = WO1.BASE_ID
              AND wo.LOT_ID    = WO1.LOT_ID
              AND wo.SPLIT_ID    = WO1.SPLIT_ID
              AND WO1.SUB_ID = '0'
              AND WO.TYPE        = WO1.TYPE)
            ) AS DESIRED_RLS_DATE, 
      ISNULL(WO.DESIRED_WANT_DATE, 
           (SELECT WO1.DESIRED_WANT_DATE 
              FROM WORK_ORDER WO1
              WHERE wo.BASE_ID    = WO1.BASE_ID
              AND wo.LOT_ID    = WO1.LOT_ID
              AND wo.SPLIT_ID    = WO1.SPLIT_ID
              AND WO1.SUB_ID = '0'
              AND WO.TYPE        = WO1.TYPE)
            ) AS DESIRED_WANT_DATE
  FROM WORK_ORDER WO
 WHERE WO.TYPE = N'W'
   AND WO.STATUS IN (N'R', N'F')
      --and WO.SUB_ID = '1'
)

--select * from CTE_WO
--VISUAL ENTERPRISE REPORTS-->INVENTORY REPORTS-->CMP SHOP STOCK DEMAND 

--CMP RAW MATERIAL AVAILABILITY 
--CMP SHOP STOCK DEMAND 

--DECLARE @COMMODITY_CODE AS NVARCHAR(15)
--SET @COMMODITY_CODE = 'CFM-Raw Matl'

SELECT RESOURCE_ID, 
      RQ_PART_ID, 
      RQP_DESCRIPTION, 
      COMMODITY_CODE, 
      CALC_QTY, 
      RTOTAL, 
      CASE WHEN QTY_AVAILABLE_ISS >= RTOTAL
         THEN 'YES'
         ELSE 'NO'
      END AS AVAIL, 
      WO_PART_ID USED_ON, 
      DESIRED_RLS_DATE AS RELEASE, 
      DESIRED_WANT_DATE AS DUE_DATE, 
      QTY_AVAILABLE_ISS, 
      BASE_ID, 
                    WONUM,
      CUST_ORDER_ID, 
      WP_DESCRIPTION AS USED_ON_DESCRIPTION, 
      OP_PIECE, 
      LOCTYPE, 
      QTY_PER, 
      USAGE_UM, 
      ISSUED_QTY, 
      DESIRED_QTY, 
      ALLOY, 
      STATUS
  FROM (
SELECT O.RESOURCE_ID, 
      RQ.PART_ID            AS    RQ_PART_ID, 
      P.DESCRIPTION         AS    RQP_DESCRIPTION, 
      P.COMMODITY_CODE, 
      RQ.CALC_QTY, 
      SUM(RQ.CALC_QTY) OVER(PARTITION BY RQ.PART_ID  ORDER BY RQ.PART_ID, WO.DESIRED_WANT_DATE) AS RTOTAL, 
      WO.PART_ID            AS WO_PART_ID, 
      WO.WONUM,
      WO.DESIRED_RLS_DATE, 
      WO.DESIRED_WANT_DATE, 
      P.QTY_AVAILABLE_ISS, 
      WO.BASE_ID, 
      DSL.DEMAND_BASE_ID    AS CUST_ORDER_ID, 
      WP.DESCRIPTION        AS WP_DESCRIPTION, 
      CONVERT(NVARCHAR(3), RQ.OPERATION_SEQ_NO) + '_' + CONVERT(NVARCHAR(4), RQ.PIECE_NO) AS OP_PIECE, 
      CASE WHEN O.OPERATION_TYPE = 'CHKMATL'
           THEN 'RM'
          ELSE 'FG'
      END AS LOCTYPE, 
      RQ.QTY_PER, 
      RQ.USAGE_UM, 
      RQ.ISSUED_QTY, 
      WO.DESIRED_QTY, 
      UDF.ALLOY, 
      WO.STATUS
  FROM CTE_WO WO
  LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
    ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
   AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
   AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
   AND DSL.SUPPLY_SUB_ID = WO.SUB_ID
  LEFT OUTER JOIN OPERATION O
    ON WO.BASE_ID = O.WORKORDER_BASE_ID
   AND WO.LOT_ID = O.WORKORDER_LOT_ID
   AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
   AND WO.SUB_ID = O.WORKORDER_SUB_ID
   AND WO.TYPE = O.WORKORDER_TYPE
  LEFT OUTER JOIN PART WP
    ON WO.PART_ID = WP.ID
  LEFT OUTER JOIN REQUIREMENT RQ
    ON O.WORKORDER_TYPE = RQ.WORKORDER_TYPE
   AND O.WORKORDER_BASE_ID = RQ.WORKORDER_BASE_ID
   AND O.WORKORDER_LOT_ID = RQ.WORKORDER_LOT_ID
   AND O.WORKORDER_SPLIT_ID = RQ.WORKORDER_SPLIT_ID
   AND O.WORKORDER_SUB_ID = RQ.WORKORDER_SUB_ID
   AND O.SEQUENCE_NO = RQ.OPERATION_SEQ_NO
  LEFT OUTER JOIN PART P
    ON RQ.PART_ID = P.ID
  LEFT OUTER JOIN SKILLS_PART_UDF UDF
    ON RQ.PART_ID = UDF.PART_ID
 WHERE O.RESOURCE_ID IN(N'P2M2-RLSMTL-CMP')
   AND RQ.ISSUED_QTY = 0
   ) AS A
ORDER BY LOCTYPE, 
        RQ_PART_ID, 
        STATUS DESC, 
        DESIRED_WANT_DATE;
