SELECT     EMPLOYEE.ID, EMPLOYEE.LAST_NAME, EMPLOYEE.FIRST_NAME, EMPLOYEE.ACTIVE, EMPLOYEE.DEPARTMENT_ID, 
                      DEPARTMENT.DESCRIPTION
FROM         EMPLOYEE INNER JOIN
                      DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.ID
WHERE     (EMPLOYEE.ACTIVE = 'Y')  and (EMPLOYEE.LAST_NAME = @LastName)
