/*************************************************************************************************
Visual Enterprise Reports > CERT Reports > Skills Cert MFG_unlinked_no_specs


**************************************************************************************************/
--DECLARE @PACKLIST AS NVARCHAR(15) = '1449240'

declare @PACKLIST nvarchar(250) = '1486364'

SELECT DISTINCT W.BASE_ID, W.LOT_ID, W.SPLIT_ID
    , dbo.sfnWONUMFormat(W.BASE_ID ,W.LOT_ID , W.SPLIT_ID, W.SUB_ID) as WO_NUM
    , dbo.sfnWONUMFormat_OLD(W.BASE_ID ,W.LOT_ID , W.SPLIT_ID, W.SUB_ID) as WO_NUMOld
    , TRT.TRACE_ID, O.WORKORDER_SUB_ID, CL.PART_ID, P.description as part_description
    , ABS(TRT.QTY) AS SHIPPED_QTY, SOB.SEQUENCE_NO, O.RESOURCE_ID, O.OPERATION_TYPE
    , S.PACKLIST_ID, CL.CUSTOMER_PART_ID
    , ISNULL(CS.ADDR_1, '') +  CHAR(10) + CHAR(13) + ISNULL(CS.CITY, '') + ', ' +  ISNULL(CS.STATE, '') + ' ' + ISNULL(CS.ZIPCODE, '') + ' ' + ISNULL(CS.COUNTRY, '') + CHAR(10) + CHAR(13) + CHAR(10) + CHAR(13) + ISNULL(CS.CONTACT_PHONE, '') + '  FAX ' +  ISNULL(CS.CONTACT_FAX, '') AS SHIPFROM
    , C.NAME, C.ADDR_1, C.ADDR_2, C.CITY, C.STATE, C.ZIPCODE
    , ISNULL(C.NAME,'') + CHAR(10) + CHAR(13) + ISNULL(C.ADDR_1,'') + CHAR(10) + CHAR(13)  + ISNULL(C.ADDR_2,'') + CHAR(10) + CHAR(13) + ISNULL(C.CITY, '') + ' ' +  ISNULL(C.STATE, '') + ' ' + ISNULL(C.ZIPCODE, '') AS SOLDTO
    , ISNULL(CA1.NAME, CA.NAME) AS ShipName, ISNULL(CA1.ADDR_1, CA.ADDR_1) AS ShipAddr1
    , ISNULL(CA1.ADDR_2, CA.ADDR_2) AS ShipAddr2, ISNULL(CA1.CITY, CA.CITY) AS ShipCity
    , ISNULL(CA1.STATE, CA.STATE) AS ShipState, ISNULL(CA1.ZIPCODE, CA.ZIPCODE) AS ShipZip
    , ISNULL(CA1.COUNTRY, CA.COUNTRY) AS COUNTRY
    , ISNULL(CA1.NAME,ISNULL(CA.NAME,'')) + CHAR(10) + CHAR(13) + ISNULL(CA1.ADDR_1, ISNULL(CA.ADDR_1,'')) + CHAR(10) + CHAR(13) + ISNULL(CA1.ADDR_2, ISNULL(CA.ADDR_2,'')) + CHAR(10) + CHAR(13) + ISNULL(CA1.CITY, ISNULL(CA.CITY, '')) + ' ' +  ISNULL(CA1.STATE, ISNULL(CA.STATE, '')) + ' ' + ISNULL(CA1.ZIPCODE, ISNULL(CA.ZIPCODE, '')) + CHAR(10) + CHAR(13) + ISNULL(CA1.COUNTRY, ISNULL(CA.COUNTRY, '')) AS SHIPTO
    , CASE WHEN CL.USER_2 IS NOT NULL THEN CL.USER_2 ELSE NULL END AS CUST_PO_LN
    , CASE WHEN CL.USER_2 IS NOT NULL THEN 'Y' ELSE 'N' END AS CUST_POLN_PRINT
    , CO.CUSTOMER_ID, CO.CUSTOMER_PO_REF, CO.ID as CUST_ID
    , DBO.fnFormatDate(S.SHIPPED_DATE,'M/D/YYYY') AS SHIPPED_DATE
    , CL.LINE_NO, ISNULL(CD.CUST_FILTER_APPLIED, 'N') AS OP_FILTER
    , ISNULL(C.USER_7, 'N') AS CUST_FILTER, W.PART_ID AS Expr1
    , SWD.WO_LINK_NO_LOC --Document Reference
    --controls what is show in the specs
    , ( SELECT SUM(ABS(TRT.QTY)) 
        FROM SHIPPER_LINE sl
        INNER JOIN TRACE_INV_TRANS AS TRT
        INNER JOIN WORK_ORDER AS W ON dbo.sfnGetBaseFromTraceID(TRT.TRACE_ID) = W.BASE_ID
            AND ISNULL(dbo.sfnGetLOTIDFromTraceID(TRT.TRACE_ID), '1') = W.LOT_ID
            AND ISNULL(dbo.sfnGetSplitIDFromTraceID(TRT.TRACE_ID),'0') = W.SPLIT_ID
            AND W.SUB_ID = 0
            ON SL.TRANSACTION_ID = TRT.TRANSACTION_ID
            and sl.PACKLIST_ID =  @PACKLIST
    ) AS totqty
    , ( SELECT w.name + CHAR(10)+CHAR(13) + w.ADDR_1 +  CHAR(10)+CHAR(13) + w.city + ', ' +  w.STATE + ' ' 
            + w.zipcode + ' ' + 'USA' + CHAR(10)+CHAR(13) + CHAR(10)+CHAR(13) + w.ADDR_3 
        FROM SHIPPER_LINE SL
        INNER JOIN  INVENTORY_TRANS it on SL.TRANSACTION_ID = it.TRANSACTION_ID
        INNER join WAREHOUSE W ON IT.WAREHOUSE_ID = W.ID
        WHERE PACKLIST_ID = @PACKLIST
    ) AS SHIPFROM_aub

FROM CUSTOMER AS C
    INNER JOIN CUSTOMER_ORDER AS CO ON C.ID = CO.CUSTOMER_ID
    INNER JOIN CUST_ORDER_LINE AS CL ON CO.ID = CL.CUST_ORDER_ID
        AND ( NOT(CL.PART_ID = 'E' OR CL.PART_ID = 'EX' OR CL.PART_ID = 'EXP' OR CL.PART_ID = 'L') )
    LEFT OUTER JOIN PART P ON P.ID = CL.PART_ID
    LEFT OUTER JOIN CUST_ADDRESS AS CA ON CO.CUSTOMER_ID = CA.CUSTOMER_ID
        AND CO.SHIP_TO_ADDR_NO = CA.ADDR_NO
    LEFT OUTER JOIN CUST_ADDRESS AS CA1 ON CO.CUSTOMER_ID = CA1.CUSTOMER_ID
        AND CL.SHIPTO_ID = CA1.ADDR_NO
    INNER JOIN SHIPPER AS S ON CO.ID = S.CUST_ORDER_ID
    INNER JOIN SHIPPER_LINE AS SL ON S.PACKLIST_ID = SL.PACKLIST_ID
        AND CL.CUST_ORDER_ID = SL.CUST_ORDER_ID AND CL.LINE_NO = SL.CUST_ORDER_LINE_NO
    INNER JOIN TRACE_INV_TRANS AS TRT
    INNER JOIN WORK_ORDER AS W ON dbo.sfnGetBaseFromTraceID(TRT.TRACE_ID) = W.BASE_ID
            AND ISNULL(dbo.sfnGetLOTIDFromTraceID(TRT.TRACE_ID), '1') = W.LOT_ID
            AND ISNULL(dbo.sfnGetSplitIDFromTraceID(TRT.TRACE_ID), '0') = W.SPLIT_ID
            AND W.SUB_ID = '0' ON SL.TRANSACTION_ID = TRT.TRANSACTION_ID
    INNER JOIN OPERATION AS O ON W.TYPE = O.WORKORDER_TYPE
        AND W.BASE_ID = O.WORKORDER_BASE_ID AND W.LOT_ID = O.WORKORDER_LOT_ID
        AND W.SPLIT_ID = O.WORKORDER_SPLIT_ID AND W.SUB_ID = O.WORKORDER_SUB_ID
    INNER JOIN SKILLS_WO_OPS_first_last_loc CLO ON CLO.TYPE = W.TYPE
        AND CLO.BASE_ID = W.BASE_ID AND CLO.LOT_ID = W.LOT_ID
        AND CLO.SPLIT_ID = W.SPLIT_ID AND CLO.SUB_ID = W.SUB_ID 
    INNER JOIN CUSTOMER CS ON CS.ID = CLO.CERTENDLOC 
    INNER JOIN SKILLS_WO_DOC SWD ON W.BASE_ID = SWD.BASE_ID
        AND W.LOT_ID = SWD.LOT_ID AND W.SPLIT_ID = SWD.SPLIT_ID
    INNER JOIN SKILL_OPERATION_BINARY AS SOB ON O.WORKORDER_TYPE = SOB.WORKORDER_TYPE
        AND O.WORKORDER_BASE_ID = SOB.WORKORDER_BASE_ID AND O.WORKORDER_LOT_ID = SOB.WORKORDER_LOT_ID
        AND O.WORKORDER_SPLIT_ID = SOB.WORKORDER_SPLIT_ID AND O.WORKORDER_SUB_ID = SOB.WORKORDER_SUB_ID
        AND O.SEQUENCE_NO = SOB.SEQUENCE_NO
    LEFT OUTER JOIN SKILLS_CERT_DESC AS CD ON O.OPERATION_TYPE = CD.OP_TYPE

WHERE (SL.SHIPPED_QTY > 0) AND (S.PACKLIST_ID = @PACKLIST)
--ORDER BY CL.LINE_NO, SOB.SEQUENCE_NO

/********************************************************************************************************/
/************************************    UNION WITH [SQL-Lab-2].[LIVEARC].dbo.   ***********************/
/******************************************************************************************************/
UNION
SELECT DISTINCT W.BASE_ID, W.LOT_ID, W.SPLIT_ID
    , dbo.sfnWONUMFormat(W.BASE_ID ,W.LOT_ID , W.SPLIT_ID, W.SUB_ID) as WO_NUM
    , dbo.sfnWONUMFormat_OLD(W.BASE_ID ,W.LOT_ID , W.SPLIT_ID, W.SUB_ID) as WO_NUMOld
    , TRT.TRACE_ID, O.WORKORDER_SUB_ID, CL.PART_ID, P.description as part_description
    , ABS(TRT.QTY) AS SHIPPED_QTY, SOB.SEQUENCE_NO, O.RESOURCE_ID, O.OPERATION_TYPE
    , S.PACKLIST_ID, CL.CUSTOMER_PART_ID
    , ISNULL(CS.ADDR_1, '') +  CHAR(10) + CHAR(13) + ISNULL(CS.CITY, '') + ', ' +  ISNULL(CS.STATE, '') + ' ' + ISNULL(CS.ZIPCODE, '') + ' ' + ISNULL(CS.COUNTRY, '') + CHAR(10) + CHAR(13) + CHAR(10) + CHAR(13) + ISNULL(CS.CONTACT_PHONE, '') + '  FAX ' +  ISNULL(CS.CONTACT_FAX, '') AS SHIPFROM
    , C.NAME, C.ADDR_1, C.ADDR_2, C.CITY, C.STATE, C.ZIPCODE
    , ISNULL(C.NAME,'') + CHAR(10) + CHAR(13) + ISNULL(C.ADDR_1,'') + CHAR(10) + CHAR(13)  + ISNULL(C.ADDR_2,'') + CHAR(10) + CHAR(13) + ISNULL(C.CITY, '') + ' ' +  ISNULL(C.STATE, '') + ' ' + ISNULL(C.ZIPCODE, '') AS SOLDTO
    , ISNULL(CA1.NAME, CA.NAME) AS ShipName, ISNULL(CA1.ADDR_1, CA.ADDR_1) AS ShipAddr1
    , ISNULL(CA1.ADDR_2, CA.ADDR_2) AS ShipAddr2, ISNULL(CA1.CITY, CA.CITY) AS ShipCity
    , ISNULL(CA1.STATE, CA.STATE) AS ShipState, ISNULL(CA1.ZIPCODE, CA.ZIPCODE) AS ShipZip
    , ISNULL(CA1.COUNTRY, CA.COUNTRY) AS COUNTRY
    , ISNULL(CA1.NAME,ISNULL(CA.NAME,'')) + CHAR(10) + CHAR(13) + ISNULL(CA1.ADDR_1, ISNULL(CA.ADDR_1,'')) + CHAR(10) + CHAR(13) + ISNULL(CA1.ADDR_2, ISNULL(CA.ADDR_2,'')) + CHAR(10) + CHAR(13) + ISNULL(CA1.CITY, ISNULL(CA.CITY, '')) + ' ' +  ISNULL(CA1.STATE, ISNULL(CA.STATE, '')) + ' ' + ISNULL(CA1.ZIPCODE, ISNULL(CA.ZIPCODE, '')) + CHAR(10) + CHAR(13) + ISNULL(CA1.COUNTRY, ISNULL(CA.COUNTRY, '')) AS SHIPTO
    , CASE WHEN CL.USER_2 IS NOT NULL THEN CL.USER_2 ELSE NULL END AS CUST_PO_LN
    , CASE WHEN CL.USER_2 IS NOT NULL THEN 'Y' ELSE 'N' END AS CUST_POLN_PRINT
    , CO.CUSTOMER_ID, CO.CUSTOMER_PO_REF, CO.ID as CUST_ID
    , DBO.fnFormatDate(S.SHIPPED_DATE,'M/D/YYYY') AS SHIPPED_DATE
    , CL.LINE_NO, ISNULL(CD.CUST_FILTER_APPLIED, 'N') AS OP_FILTER
    , ISNULL(C.USER_7, 'N') AS CUST_FILTER, W.PART_ID AS Expr1
    , SWD.WO_LINK_NO_LOC --Document Reference
    --controls what is show in the specs
    , ( SELECT SUM(ABS(TRT.QTY)) 
        FROM SHIPPER_LINE sl
        INNER JOIN TRACE_INV_TRANS AS TRT
        INNER JOIN [SQL-Lab-2].[LIVEARC].[dbo].WORK_ORDER AS W
            ON dbo.sfnGetBaseFromTraceID(TRT.TRACE_ID) = W.BASE_ID
            AND ISNULL(dbo.sfnGetLOTIDFromTraceID(TRT.TRACE_ID), '1') = W.LOT_ID
            AND ISNULL(dbo.sfnGetSplitIDFromTraceID(TRT.TRACE_ID),'0') = W.SPLIT_ID
            AND W.SUB_ID = 0
            ON SL.TRANSACTION_ID = TRT.TRANSACTION_ID
            and sl.PACKLIST_ID =  @PACKLIST
    ) AS totqty
    , ( SELECT w.name + CHAR(10)+CHAR(13) + w.ADDR_1 +  CHAR(10)+CHAR(13) + w.city + ', ' +  w.STATE + ' ' 
            + w.zipcode + ' ' + 'USA' + CHAR(10)+CHAR(13) + CHAR(10)+CHAR(13) + w.ADDR_3 
        FROM SHIPPER_LINE SL
        INNER JOIN  INVENTORY_TRANS it on SL.TRANSACTION_ID = it.TRANSACTION_ID
        INNER join WAREHOUSE W ON IT.WAREHOUSE_ID = W.ID
        WHERE PACKLIST_ID = @PACKLIST
    ) AS SHIPFROM_aub

FROM CUSTOMER AS C
    INNER JOIN CUSTOMER_ORDER AS CO ON C.ID = CO.CUSTOMER_ID
    INNER JOIN CUST_ORDER_LINE AS CL ON CO.ID = CL.CUST_ORDER_ID
        AND ( NOT(CL.PART_ID = 'E' OR CL.PART_ID = 'EX' OR CL.PART_ID = 'EXP' OR CL.PART_ID = 'L') )
    LEFT OUTER JOIN PART P ON P.ID = CL.PART_ID
    LEFT OUTER JOIN CUST_ADDRESS AS CA ON CO.CUSTOMER_ID = CA.CUSTOMER_ID
        AND CO.SHIP_TO_ADDR_NO = CA.ADDR_NO
    LEFT OUTER JOIN CUST_ADDRESS AS CA1 ON CO.CUSTOMER_ID = CA1.CUSTOMER_ID
        AND CL.SHIPTO_ID = CA1.ADDR_NO
    INNER JOIN SHIPPER AS S ON CO.ID = S.CUST_ORDER_ID
    INNER JOIN SHIPPER_LINE AS SL ON S.PACKLIST_ID = SL.PACKLIST_ID
        AND CL.CUST_ORDER_ID = SL.CUST_ORDER_ID AND CL.LINE_NO = SL.CUST_ORDER_LINE_NO
    INNER JOIN TRACE_INV_TRANS AS TRT
    INNER JOIN [SQL-Lab-2].[LIVEARC].[dbo].WORK_ORDER AS W ON dbo.sfnGetBaseFromTraceID(TRT.TRACE_ID) = W.BASE_ID
        AND ISNULL(dbo.sfnGetLOTIDFromTraceID(TRT.TRACE_ID), '1') = W.LOT_ID
        AND ISNULL(dbo.sfnGetSplitIDFromTraceID(TRT.TRACE_ID), '0') = W.SPLIT_ID
        AND W.SUB_ID = '0' ON SL.TRANSACTION_ID = TRT.TRANSACTION_ID
    INNER JOIN [SQL-Lab-2].[LIVEARC].[dbo].OPERATION AS O ON W.TYPE = O.WORKORDER_TYPE
        AND W.BASE_ID = O.WORKORDER_BASE_ID AND W.LOT_ID = O.WORKORDER_LOT_ID
        AND W.SPLIT_ID = O.WORKORDER_SPLIT_ID AND W.SUB_ID = O.WORKORDER_SUB_ID
    INNER JOIN SKILLS_WO_OPS_first_last_loc_ARC CLO ON CLO.TYPE = W.TYPE
        AND CLO.BASE_ID = W.BASE_ID AND CLO.LOT_ID = W.LOT_ID
        AND CLO.SPLIT_ID = W.SPLIT_ID AND CLO.SUB_ID = W.SUB_ID 
        --select * from SKILLS_WO_OPS_first_last_loc_ARC where base_id = '1771342'
    LEFT JOIN CUSTOMER CS ON CS.ID = CLO.CERTENDLOC 
    INNER JOIN SKILLS_WO_DOC_ARC SWD ON W.BASE_ID = SWD.BASE_ID
        AND W.LOT_ID = SWD.LOT_ID AND W.SPLIT_ID = SWD.SPLIT_ID
        --select * from SKILLS_WO_DOC_ARC where base_id = '1771342'
    INNER JOIN [SQL-Lab-2].[LIVEARC].[dbo].SKILL_OPERATION_BINARY AS SOB ON O.WORKORDER_TYPE = SOB.WORKORDER_TYPE
        AND O.WORKORDER_BASE_ID = SOB.WORKORDER_BASE_ID AND O.WORKORDER_LOT_ID = SOB.WORKORDER_LOT_ID
        AND O.WORKORDER_SPLIT_ID = SOB.WORKORDER_SPLIT_ID AND O.WORKORDER_SUB_ID = SOB.WORKORDER_SUB_ID
        AND O.SEQUENCE_NO = SOB.SEQUENCE_NO
    LEFT OUTER JOIN [SQL-Lab-2].[LIVEARC].[dbo].SKILLS_CERT_DESC AS CD ON O.OPERATION_TYPE = CD.OP_TYPE

WHERE (SL.SHIPPED_QTY > 0) AND (S.PACKLIST_ID = @PACKLIST)
ORDER BY CL.LINE_NO, SOB.SEQUENCE_NO
