# BOE Receivable Input File Diagnostic Script
# Run this to check the current state of the BOE processing folders

Write-Host "=== BOE Receivable File System Diagnostic ===" -ForegroundColor Green
Write-Host "Date: $(Get-Date)" -ForegroundColor Green
Write-Host ""

# Define paths
$InputPath = "\\skillsinc.local\public\IS\DataTransfer\BOE Receivable\Input"
$ProcessPath = "\\skillsinc.local\public\IS\DataTransfer\BOE Receivable\Process"
$ProcessCompletePath = "\\skillsinc.local\public\IS\DataTransfer\BOE Receivable\ProcessComplete"

Write-Host "Checking BOE Receivable folder structure..." -ForegroundColor Yellow

# Check Input folder
Write-Host "`n1. INPUT FOLDER: $InputPath" -ForegroundColor Cyan
if (Test-Path $InputPath) {
    Write-Host "   ✓ Folder exists" -ForegroundColor Green
    $inputFiles = Get-ChildItem $InputPath -ErrorAction SilentlyContinue
    if ($inputFiles) {
        Write-Host "   Files found:" -ForegroundColor Green
        $inputFiles | ForEach-Object {
            $size = if ($_.Length) { [math]::Round($_.Length / 1KB, 2) } else { "0" }
            Write-Host "     - $($_.Name) (${size} KB, Modified: $($_.LastWriteTime))" -ForegroundColor White
        }
    } else {
        Write-Host "   ⚠ EMPTY - No files found in Input folder" -ForegroundColor Yellow
        Write-Host "   Expected: BOE.xls" -ForegroundColor Yellow
    }
} else {
    Write-Host "   ✗ Folder does not exist!" -ForegroundColor Red
}

# Check Process folder
Write-Host "`n2. PROCESS FOLDER: $ProcessPath" -ForegroundColor Cyan
if (Test-Path $ProcessPath) {
    Write-Host "   ✓ Folder exists" -ForegroundColor Green
    $processFiles = Get-ChildItem $ProcessPath -ErrorAction SilentlyContinue
    if ($processFiles) {
        Write-Host "   Files found:" -ForegroundColor Green
        $processFiles | ForEach-Object {
            $size = if ($_.Length) { [math]::Round($_.Length / 1KB, 2) } else { "0" }
            $status = if ($_.Name -like "*LOCKED*") { " (LOCKED BACKUP)" } else { "" }
            Write-Host "     - $($_.Name) (${size} KB, Modified: $($_.LastWriteTime))$status" -ForegroundColor White
        }
    } else {
        Write-Host "   ⚠ EMPTY - No files found in Process folder" -ForegroundColor Yellow
    }
} else {
    Write-Host "   ✗ Folder does not exist!" -ForegroundColor Red
}

# Check ProcessComplete folder
Write-Host "`n3. PROCESS COMPLETE FOLDER: $ProcessCompletePath" -ForegroundColor Cyan
if (Test-Path $ProcessCompletePath) {
    Write-Host "   ✓ Folder exists" -ForegroundColor Green
    $completeFiles = Get-ChildItem $ProcessCompletePath -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending
    if ($completeFiles) {
        Write-Host "   Recent files (last 5):" -ForegroundColor Green
        $completeFiles | Select-Object -First 5 | ForEach-Object {
            $size = if ($_.Length) { [math]::Round($_.Length / 1KB, 2) } else { "0" }
            Write-Host "     - $($_.Name) (${size} KB, Modified: $($_.LastWriteTime))" -ForegroundColor White
        }
        if ($completeFiles.Count -gt 5) {
            Write-Host "     ... and $($completeFiles.Count - 5) more files" -ForegroundColor Gray
        }
    } else {
        Write-Host "   ⚠ EMPTY - No completed files found" -ForegroundColor Yellow
    }
} else {
    Write-Host "   ✗ Folder does not exist!" -ForegroundColor Red
}

# Check for template files
Write-Host "`n4. TEMPLATE FILES CHECK" -ForegroundColor Cyan
$templateFiles = @(
    "TEMPLATE_BOE_Receivable.xlsx",
    "TEMPLATE_BOE_Header.csv"
)

foreach ($template in $templateFiles) {
    $templatePath = Join-Path $ProcessPath $template
    if (Test-Path $templatePath) {
        $fileInfo = Get-Item $templatePath
        $size = [math]::Round($fileInfo.Length / 1KB, 2)
        Write-Host "   ✓ $template (${size} KB, Modified: $($fileInfo.LastWriteTime))" -ForegroundColor Green
    } else {
        Write-Host "   ✗ $template - MISSING!" -ForegroundColor Red
    }
}

# Provide recommendations
Write-Host "`n=== RECOMMENDATIONS ===" -ForegroundColor Yellow
Write-Host ""

$inputFileExists = Test-Path (Join-Path $InputPath "BOE.xls")
if (-not $inputFileExists) {
    Write-Host "🔍 MISSING INPUT FILE SOLUTIONS:" -ForegroundColor Yellow
    Write-Host "   1. Check if BOE.xls file is being generated by the source system" -ForegroundColor White
    Write-Host "   2. Verify the file wasn't already processed (check ProcessComplete folder)" -ForegroundColor White
    Write-Host "   3. Check if the file has a different name or extension" -ForegroundColor White
    Write-Host "   4. Confirm the scheduled job timing aligns with file delivery" -ForegroundColor White
    Write-Host ""
    
    # Look for similar files
    Write-Host "🔎 SEARCHING FOR SIMILAR FILES:" -ForegroundColor Cyan
    $searchPaths = @($InputPath, $ProcessPath, $ProcessCompletePath)
    $foundSimilar = $false
    
    foreach ($searchPath in $searchPaths) {
        if (Test-Path $searchPath) {
            $similarFiles = Get-ChildItem $searchPath -Filter "*BOE*" -ErrorAction SilentlyContinue
            $xlsFiles = Get-ChildItem $searchPath -Filter "*.xls*" -ErrorAction SilentlyContinue
            
            $allFiles = @($similarFiles + $xlsFiles) | Sort-Object Name -Unique
            
            if ($allFiles) {
                $folderName = Split-Path $searchPath -Leaf
                Write-Host "   Found in $folderName folder:" -ForegroundColor Green
                $allFiles | ForEach-Object {
                    $size = if ($_.Length) { [math]::Round($_.Length / 1KB, 2) } else { "0" }
                    Write-Host "     - $($_.Name) (${size} KB, Modified: $($_.LastWriteTime))" -ForegroundColor White
                }
                $foundSimilar = $true
            }
        }
    }
    
    if (-not $foundSimilar) {
        Write-Host "   No BOE or Excel files found in any folder" -ForegroundColor Gray
    }
}

Write-Host "`n📋 NEXT STEPS:" -ForegroundColor Green
Write-Host "   1. Locate the missing BOE.xls input file" -ForegroundColor White
Write-Host "   2. Place it in: $InputPath" -ForegroundColor White
Write-Host "   3. Re-run the BOE processing script" -ForegroundColor White
Write-Host "   4. Monitor the ProcessComplete folder for results" -ForegroundColor White

Write-Host "`n=== DIAGNOSTIC COMPLETE ===" -ForegroundColor Green