SELECT ID AS EC_ID
, REASON
, REQUEST_DATE
, TYPE
FROM EC 
WHERE ISNULL(EC.REASON, '_Blank') IN (@REASON)
AND ISNULL(EC.TYPE, '_Blank') IN (@TYPE)
AND REQUEST_DATE >= @STARTDATE
AND REQUEST_DATE <= @ENDDATE
