SELECT EE.ID AS VISUAL_ID
    , EE.[LAST_NAME] AS VISUAL_LNAME
    , EE.[FIRST_NAME] AS VISUAL_FNAME
    , EE.[ACTIVE] AS VISUAL_STATUS
    , EE.DEPARTMENT_ID AS VISUAL_DEPT
    , EE.SHIFT_ID AS VISUAL_SHIFT
    , EE.EMAIL_ADDR
FROM DataWarehouse.[dbo].[EMPLOYEE] EE
WHERE EE.[ACTIVE] = 'Y'
    AND LEFT(EE.ID, 3) IN ('INT', 'AIP')

