-- Visual Enterprise Reports/Administrative Reports/Part Inventory Value

SELECT 
    P.ID, 
    P.QTY_ON_HAND, 
    P.COMMODITY_CODE, 
    IT.ACT_MATERIAL_COST,
    IT.ACT_LABOR_COST,
    IT.ACT_BURDEN_COST,
    IT.ACT_SERVICE_COST,
    IT.ACT_MATERIAL_COST + IT.ACT_LABOR_COST + IT.ACT_BURDEN_COST + IT.ACT_SERVICE_COST as [last transaction value],
    IT.QTY,
    ((IT.ACT_MATERIAL_COST + IT.ACT_LABOR_COST + IT.ACT_BURDEN_COST + IT.ACT_SERVICE_COST)/ IT.QTY) * P.QTY_ON_HAND  as [Total Value],
    cast(IT.TRANSACTION_DATE as date) as TransDate
FROM   
    PART P 
INNER JOIN 
    INVENTORY_TRANS IT
    on P.ID = IT.PART_ID
INNER JOIN 
    (select PART_ID, MAX(TRANSACTION_ID) AS TRANSACTION_ID
    FROM INVENTORY_TRANS IT2
    WHERE IT2.TRANSACTION_DATE <= @AsOfDate
        AND IT2.QTY <> 0 
        AND IT2.TYPE IN ('I', 'O') 
        AND IT2.CLASS <> 'A'
    GROUP BY IT2.PART_ID
    ) IT2
    on IT.TRANSACTION_ID = IT2.TRANSACTION_ID
    AND IT.PART_ID = IT2.PART_ID
WHERE  
    P.QTY_ON_HAND > 0 
    and P.COMMODITY_CODE IN (@CommCode)

ORDER BY 
    IT.PART_ID, 
    IT.TRANSACTION_DATE DESC
