WITH CTE_SLCT AS
(SELECT U.[USER_ID]
    , EE.FIRST_NAME
    , EE.LAST_NAME
    , ADP.[Job Title Description]
    , ADP.[Reports To Name]
    , A.PROGRAM_ID
    , CASE
        WHEN PERMISSION IN ('N', 'R', 'Y') THEN ISNULL(PROFILE_STRING, PERMISSION)
        ELSE ''
    END AS [PERMISSION]
FROM APPLICATION A
LEFT OUTER JOIN [USER_PGM_AUTHORITY] U
    ON A.PROGRAM_ID = U.PROGRAM_ID
    AND U.PROGRAM_COMPONENT = 'PROGRAM'
LEFT JOIN EMPLOYEE EE
    ON U.[USER_ID] = EE.[USER_ID]
LEFT JOIN LIVESupplemental.dbo.ADP_EMP ADP
    ON CONVERT(NVARCHAR(15), RIGHT('0000' + EE.ID, 6)) = ADP.[File Number]
WHERE U.[USER_ID] NOT IN ('AIP', 'AUBNOBRAKEFORM', 'BARCODE', 'BLANK', 'BRAKEM1', 'BRAKEM2', 'BRAKEM3', 'CNC', 'Config/Plan ECN', 'DOOSAN1', 'DOOSAN2', 'ECN ADMIN', 'ECN Entry', 'EXPEDITE', 'Gen Sec', 'Gen Security', 'HAAS1', 'HAAS10', 'HAAS11', 'HAAS12', 'HAAS13', 'HAAS14', 'HAAS15', 'HAAS16', 'HAAS17', 'HAAS18', 'HAAS19', 'HAAS2', 'HAAS20', 'HAAS21', 'HAAS3', 'HAAS4', 'HAAS5', 'HAAS6', 'HAAS7', 'HAAS8', 'HAAS9', 'HANSG', 'MACRO', 'MacrosGeneral', 'MENUUSER', 'OKUMA', 'PAINTER', 'PAINTERBATCH', 'PREDATOR', 'PURCHASE', 'ROMFG', 'ROUTER1', 'ROUTER2', 'ROUTER3', 'ROUTER4', 'SKILLS\barcode', 'TANKLINE', 'TANKLINEBATCH', 'testing2', 'TM1', 'TM2', 'TRAINER', 'UMC1', 'UMC2')
    AND ADP.[Location Code] IN (@FACILITY)
    AND ADP.[Home Department Code] IN (@DEPARTMENT)
    AND ADP.[Reports To Name] IN (@SUPERVISOR)
    AND EE.ACTIVE = 'Y'
)

SELECT * FROM CTE_SLCT
PIVOT(MAX(PERMISSION)
    FOR PROGRAM_ID IN (LMC_VEXP, VFAPCENT, VFAPIENT, VFAPSCHD, VFAPVINQ, VFARCENT, VFARCINQ, VFARCLCT, VFARIENT, VFBNKMNT, VFCASHBK, VFCONSOL, VFCSHWIN, VFGLAWIN, VFGLBMNT, VFGLTENT, VFMFGJRN, VFREVALU, VMALCUTL, VMBOMRPT, VMCBKRPT, VMCBORPT, VMCSJRPT, VMCSTBOM, VMCUSINQ, VMCUSMNT, VMDOCMNT, VMECNENT, VMECNHST, VMEMPMNT, VMENGRPT, VMIBTENT, VMIBTRCV, VMIBTSHP, VMINVENT, VMINVGEN, VMLABENT, VMMFGWIN, VMORDENT, VMORDWIN, VMPBCENT, VMPFTRPT, VMPHYINV, VMPIVRPT, VMPLNWIN, VMPRTMNT, VMPURENT, VMPURWIN, VMRCVENT, VMRCVINS, VMRCVRPT, VMREQENT, VMRESMNT, VMREVRPT, VMRFQENT, VMSCHRPT, VMSCHWIN, VMSDSRPT, VMSHPENT, VMSRVDIS, VMSRVENT, VMSRVMNT, VMSRVPLN, VMSUPPFM, VMTHRWIN, VMUMTMNT, VMVNDINQ, VMVNDMNT, VMWHSMNT, VMWIPRPT, VMWRKCST, VMWRQRPT, VTMATTRC, VTTRCMNT, VTTRPMNT)
) AS [PIVOTTABLE]
