-- VISUAL ENTERPRISE > CUSTOMER SERVICE REPORTS > BOEING REPORTS > Mfg Planning Queue slides Repeats
SELECT TOP 10 CASE
--        WHEN P.PLANNER_USER_ID = 'MRP' 
        WHEN EXISTS        
            (SELECT 1    
            FROM LIVESUPPLEMENTAL.DBO.PLANNER_USER_ID_ReportSettings EX    
            WHERE P.PLANNER_USER_ID = EX.PLANNER_USER_ID    
            AND REPORT_NAME = 'Mfg Planning Queue slides Repeats'
            AND REPORT_SECTION = 'MRP'
            )    
        AND O.OPERATION_TYPE = 'REVIEW' THEN 'REPEAT PLAN'
    END AS WAITINGFOR
    , WO.[STATUS]
    , WO.PART_ID
    , [dbo].[sfnWONUMFormat](WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID) AS BASE_ID
    , P.PLANNER_USER_ID
    , P.BUYER_USER_ID
    , WO.DESIRED_RLS_DATE
    , WO.DESIRED_WANT_DATE
    , WO.DESIRED_QTY
    , CONVERT( VARCHAR(3),DBO.SFN_CURRENT_OPERATION(WO.TYPE,WO.BASE_ID,WO.LOT_ID,WO.SUB_ID,WO.SPLIT_ID)) AS CURRENT_OP
    , O.RESOURCE_ID
    , WO.ENGINEERED_BY
    , REPLACE(REPLACE(CONVERT(VARCHAR, A.CREATE_DATE, 100)+ ' ' +CAST(CAST(A.NOTE AS VARBINARY(MAX)) AS NVARCHAR(MAX)), CHAR(10), ' '), CHAR(13), ' ') AS WONOTEALL
FROM WORK_ORDER WO
    INNER JOIN OPERATION O
    ON WO.TYPE = O.WORKORDER_TYPE
    AND WO.BASE_ID = O.WORKORDER_BASE_ID
    AND WO.LOT_ID = O.WORKORDER_LOT_ID
    AND WO.SUB_ID = O.WORKORDER_SUB_ID
    AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
    AND CONVERT(VARCHAR(3), dbo.sfn_current_operation(WO.TYPE, WO.BASE_ID, WO.LOT_ID, WO.SUB_ID, WO.SPLIT_ID)) = O.SEQUENCE_NO
    AND O.OPERATION_TYPE NOT IN ('QP-NI', 'QP-REVIEW')
INNER JOIN PART P
    ON WO.PART_ID = P.ID
LEFT OUTER JOIN
    (SELECT N.*
    FROM NOTATION N
    JOIN
        (SELECT N.OWNER_ID
            , MAX(CREATE_DATE) AS MAXDATE
        FROM   NOTATION N
        WHERE  [TYPE] = 'E'
        GROUP BY N.OWNER_ID
        ) NMAX
        ON NMAX.OWNER_ID = N.OWNER_ID
        AND NMAX.MAXDATE = N.CREATE_DATE
    ) AS A
    ON A.OWNER_ID = WO.BASE_ID + '/' + WO.LOT_ID
WHERE WO.[TYPE] = 'W'
    AND WO.[STATUS] = 'F'
    AND EXISTS
        (SELECT 1 
        FROM LIVESupplemental.dbo.ResourceID_ReportSettings s
        WHERE s.Report_Name = 'Mfg Planning Queue Slides'
            AND s.Report_Section = 'REVIEW Resources'
        )
    --     AND O.RESOURCE_ID = 'REVIEW'
--    AND P.PLANNER_USER_ID = 'MRP'
    AND EXISTS        
        (SELECT 1    
        FROM LIVESUPPLEMENTAL.DBO.PLANNER_USER_ID_ReportSettings EX    
        WHERE P.PLANNER_USER_ID = EX.PLANNER_USER_ID    
        AND REPORT_NAME = 'Mfg Planning Queue slides Repeats'
        AND REPORT_SECTION = 'MRP'
        )    
    AND O.OPERATION_TYPE = 'REVIEW'
ORDER BY WO.DESIRED_WANT_DATE
