SELECT * FROM 
    (SELECT SR.USER_1 AS SKILLS_TYPE
        , CASE 
            WHEN ID.DEMAND_SUPPLY_ID IS NULL THEN 'UNLINKED'
            WHEN ID.DEMAND_SUPPLY_ID IS NOT NULL THEN 'LINKED'
            ELSE 'BOTH'
        END AS [ORDER]
        , 'BURDEN' AS MSG
        , C.USER_9
        --, ( (O.ACT_ATL_BUR_COST + ISNULL(RQ.Req_Burd_Cost, 0))/S.RECEIVED_QTY) * ID.DIST_QTY AS BUR_COST
        , ( (O.ACT_ATL_BUR_COST/S.RECEIVED_QTY) * ID.DIST_QTY) + ISNULL(RQ.Req_Burd_Cost, 0) AS BUR_COST
    FROM LIVE.dbo.INVENTORY_TRANS IT 
    INNER JOIN LIVE.dbo.INV_TRANS_DIST ID ON IT.TRANSACTION_ID = ID.OUT_TRANS_ID
    INNER JOIN LIVE.dbo.CUSTOMER_ORDER CO ON IT.CUST_ORDER_ID = CO.ID
    INNER JOIN LIVE.dbo.CUSTOMER C ON CO.CUSTOMER_ID = C.ID
    INNER JOIN LIVE.dbo.INVENTORY_TRANS I1 ON ID.IN_TRANS_ID = I1.TRANSACTION_ID
    LEFT OUTER JOIN LIVE.dbo.OPERATION O ON I1.WORKORDER_TYPE = O.WORKORDER_TYPE
        AND I1.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
        AND I1.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
        AND I1.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
    LEFT OUTER JOIN ( Select WORKORDER_BASE_ID as 'WO', WORKORDER_LOT_ID as 'LotID', 
        WORKORDER_SPLIT_ID as 'SplitID', WORKORDER_SUB_ID as 'SubID', OPERATION_SEQ_NO as 'SeqNo', 
        SUM(ACT_BURDEN_COST) as 'Req_Burd_Cost', SUM(ACT_LABOR_COST) as 'Req_Lab_Cost'
        from REQUIREMENT with (nolock) Group by WORKORDER_BASE_ID, WORKORDER_BASE_ID, 
        WORKORDER_LOT_ID, WORKORDER_SPLIT_ID, WORKORDER_SUB_ID, OPERATION_SEQ_NO
    ) RQ ON RQ.WO = O.WORKORDER_BASE_ID AND RQ.LotID = O.WORKORDER_LOT_ID AND RQ.SplitID = O.WORKORDER_SPLIT_ID
            AND RQ.SubID = O.WORKORDER_SUB_ID AND RQ.SeqNo = O.SEQUENCE_NO
    LEFT OUTER JOIN LIVE.dbo.SHOP_RESOURCE SR ON O.RESOURCE_ID = SR.ID
    LEFT OUTER JOIN LIVE.dbo.WORK_ORDER WO ON O.WORKORDER_TYPE = WO.[TYPE]
        AND O.WORKORDER_BASE_ID = WO.BASE_ID AND O.WORKORDER_LOT_ID = WO.LOT_ID
        AND O.WORKORDER_SPLIT_ID = WO.SPLIT_ID AND O.WORKORDER_SUB_ID = WO.SUB_ID
    LEFT OUTER JOIN LIVE.dbo.SKILLS_WO_REC_QTY S ON O.WORKORDER_BASE_ID = S.BASE_ID
        AND O.WORKORDER_LOT_ID = S.LOT_ID AND O.WORKORDER_SPLIT_ID = S.SPLIT_ID
    WHERE IT.CUST_ORDER_ID IS NOT NULL 
--> FILTERED UPON REQUEST AS OO AND OR ARE ASSOCIATED TO BUSINESS SOLUTIONS
        AND C.USER_9 IN ('1', '2', '3', '4')
        AND (IT.TRANSACTION_DATE >= @STARTDATE
            AND IT.TRANSACTION_DATE <= @ENDDATE)
        AND S.RECEIVED_QTY > 0
        AND IT.CLASS = N'I'
        AND IT.[TYPE] = N'O'
        AND @REPORT != 'LABOR' 
        AND CASE 
            WHEN @TYPE = 'UNLINKED' AND ID.DEMAND_SUPPLY_ID IS NULL THEN 'OK'
            WHEN @TYPE = 'LINKED' AND ID.DEMAND_SUPPLY_ID IS NOT NULL THEN 'OK'
            WHEN @TYPE = 'BOTH' THEN 'OK'
            ELSE 'NOPE'
        END = 'OK'
    ) X
PIVOT (SUM(BUR_COST)
    FOR USER_9 IN (
        [1]
        , [2]
        , [3]
        , [4]
    )
) AS PIVOT_TABLE
UNION ALL
SELECT * FROM 
    (SELECT SR.USER_1 AS SKILLS_TYPE
        , CASE 
            WHEN ID.DEMAND_SUPPLY_ID IS NULL THEN 'UNLINKED'
            WHEN ID.DEMAND_SUPPLY_ID IS NOT NULL THEN 'LINKED'
            ELSE 'BOTH'
        END AS [ORDER]
        , 'LABOR' AS MSG
        , C.USER_9
        --, ( (O.ACT_ATL_LAB_COST+ISNULL(RQ.Req_Lab_Cost, 0))/S.RECEIVED_QTY) * ID.DIST_QTY AS LAB_COST
        , ( (O.ACT_ATL_LAB_COST/S.RECEIVED_QTY) * ID.DIST_QTY) + ISNULL(RQ.Req_Lab_Cost, 0) AS LAB_COST
    FROM LIVE.dbo.INVENTORY_TRANS IT 
    INNER JOIN LIVE.dbo.INV_TRANS_DIST ID ON IT.TRANSACTION_ID = ID.OUT_TRANS_ID
    INNER JOIN LIVE.dbo.CUSTOMER_ORDER CO ON IT.CUST_ORDER_ID = CO.ID
    INNER JOIN LIVE.dbo.CUSTOMER C ON CO.CUSTOMER_ID = C.ID
    INNER JOIN LIVE.dbo.INVENTORY_TRANS I1 ON ID.IN_TRANS_ID = I1.TRANSACTION_ID
    LEFT OUTER JOIN LIVE.dbo.OPERATION O ON I1.WORKORDER_TYPE = O.WORKORDER_TYPE
        AND I1.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
        AND I1.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
        AND I1.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
    LEFT OUTER JOIN ( Select WORKORDER_BASE_ID as 'WO', WORKORDER_LOT_ID as 'LotID', 
        WORKORDER_SPLIT_ID as 'SplitID', WORKORDER_SUB_ID as 'SubID', OPERATION_SEQ_NO as 'SeqNo', 
        SUM(ACT_BURDEN_COST) as 'Req_Burd_Cost', SUM(ACT_LABOR_COST) as 'Req_Lab_Cost'
        from REQUIREMENT with (nolock) Group by WORKORDER_BASE_ID, WORKORDER_BASE_ID, 
        WORKORDER_LOT_ID, WORKORDER_SPLIT_ID, WORKORDER_SUB_ID, OPERATION_SEQ_NO
    ) RQ ON RQ.WO = O.WORKORDER_BASE_ID AND RQ.LotID = O.WORKORDER_LOT_ID AND RQ.SplitID = O.WORKORDER_SPLIT_ID
        AND RQ.SubID = O.WORKORDER_SUB_ID AND RQ.SeqNo = O.SEQUENCE_NO
    LEFT OUTER JOIN LIVE.dbo.SHOP_RESOURCE SR ON O.RESOURCE_ID = SR.ID
    LEFT OUTER JOIN LIVE.dbo.WORK_ORDER WO ON O.WORKORDER_TYPE = WO.[TYPE]
        AND O.WORKORDER_BASE_ID = WO.BASE_ID AND O.WORKORDER_LOT_ID = WO.LOT_ID
        AND O.WORKORDER_SPLIT_ID = WO.SPLIT_ID AND O.WORKORDER_SUB_ID = WO.SUB_ID
    LEFT OUTER JOIN LIVE.dbo.SKILLS_WO_REC_QTY S ON O.WORKORDER_BASE_ID = S.BASE_ID
        AND O.WORKORDER_LOT_ID = S.LOT_ID AND O.WORKORDER_SPLIT_ID = S.SPLIT_ID
    WHERE IT.CUST_ORDER_ID IS NOT NULL 
    --> FILTERED UPON REQUEST AS OO AND OR ARE ASSOCIATED TO BUSINESS SOLUTIONS
            AND C.USER_9 IN ('1', '2', '3', '4')
            AND (IT.TRANSACTION_DATE >= @STARTDATE
                AND IT.TRANSACTION_DATE <= @ENDDATE)
            AND S.RECEIVED_QTY > 0
            AND IT.CLASS = N'I'
            AND IT.[TYPE] = N'O'
            AND @REPORT != 'BURDEN' 
            AND CASE 
                WHEN @TYPE = 'UNLINKED' AND ID.DEMAND_SUPPLY_ID IS NULL THEN 'OK'
                WHEN @TYPE = 'LINKED' AND ID.DEMAND_SUPPLY_ID IS NOT NULL THEN 'OK'
                WHEN @TYPE = 'BOTH' THEN 'OK'
                ELSE 'NOPE'
            END = 'OK'
    ) X
PIVOT (SUM(LAB_COST)
    FOR USER_9 IN (
        [1]
        , [2]
        , [3]
        , [4]
    )
) AS PIVOT_TABLE
