SELECT        BASE_ID, LOT_ID, SPLIT_ID, SUB_ID, SEQ_NO, EMPLOYEE_ID, RECORDED_DATE, AMM_TYPE, RESOURCE_ID, TRANSACTION_DATE, COMMENTS, RECORDED_BY
FROM            AMM_ERRORS
WHERE        (AMM_TYPE IN (@ErrorType)) AND (TRANSACTION_DATE >= @StartDate) AND (TRANSACTION_DATE <= @EndDate)
ORDER BY BASE_ID
