SELECT da.DOCUMENT_AUDIT_ID, da.AUDITED_BY
    , CASE 
        WHEN da.RESULT = 'N' THEN 'Pending' 
        WHEN da.RESULT = 'P' THEN 'Passed'
        WHEN da.RESULT = 'F' THEN 'Failed'
        ELSE 'NA'
        END AS RESULT
    , da.REVISION_LEVEL, da.ISSUE_DATE, da.NEXT_AUDIT_DATE, da.DUE_DATE, da.COMPLETION_DATE, da.BUSINESS_UNIT_ID, da.COMMENTS, da.CreatedBy, da.CreateDate
     , e.NAME_1 InternalAuditorName
     , e.EMPLOYEE_ID InternalAuditorEMPID
     , d.DOCUMENT, d.DOCUMENT_ID, d.NAME AS DOC_NAME, d.STATUS, d.STATUS_EFFECTIVE_DATE, d.REVISION_LEVEL DOC_REVISION_LEVEL
     , af.FINDING_ID, af.FINDING_TEXT, af.FINDING_TYPE, af.FOLLOWUP_TEXT, af.CLOSED_DATE
     --, d.*
FROM VQ_DOCUMENT_AUDIT da
    JOIN VQ_AUDIT_MANAGER am
        ON da.SITE_ID = am.SITE_ID
            AND da.SK_AUDIT_MANAGER_ID = am.AUDIT_MANAGER_ID
    LEFT JOIN VQ_EMPLOYEE e
        ON da.EMPLOYEE_REC_ID = e.RECORD_ID
    LEFT JOIN VQ_DOCUMENT_SITE ds    
        ON ds.RECORD_ID = da.DOCUMENT_SITE_REC_ID
            AND ds.SITE_ID = da.SITE_ID
    LEFT JOIN VQ_DOCUMENT d 
        ON ds.DOCUMENT_REC_ID = d.RECORD_ID
    LEFT JOIN VQ_AUDIT_FINDINGS af
        ON af.SK_DOC_AUDIT_ID = da.DOCUMENT_AUDIT_ID
WHERE am.AUDIT_MANAGER_ID = @AUDIT_MANAGER_ID
    AND am.SITE_ID = @SITE_ID
