SELECT am.SITE_ID
    , am.AUDIT_MANAGER_ID
    , am.AUDIT_ID
    , am.STANDARD
    , am.SUBJECT
    , am.SCHEDULED_DATE
    , am.SK_DUE_DATE
    , laE.EMPLOYEE_ID AS LeadAuditorEMPID
    , laE.NAME_1 AS LeadAuditorName
    , aaE1.EMPLOYEE_ID AS AsstAuditor1EMPID
    , aaE1.NAME_1 AS AsstAuditor1Name
    , CL.CHECKLIST_ID
    , CL.REFERENCE
    , CL.QUESTION
FROM VQ_AUDIT_MANAGER am
LEFT OUTER JOIN VQ_AUDIT_CHECKLIST CL
    ON CL.AUDIT_REC_ID = am.RECORD_ID
LEFT JOIN VQ_EMPLOYEE laE
    ON laE.RECORD_ID = am.LEAD_AUDITOR_REC_ID
LEFT JOIN VQ_EMPLOYEE aaE1
    ON aaE1.RECORD_ID = am.ASST_AUDITOR1_REC_ID
WHERE am.SITE_ID = @SITE_ID
    AND am.AUDIT_MANAGER_ID IN (@AUDIT_ID)
