SELECT pa.AUDIT_ID, pa.AUDIT_DATE, pa.AUDITED_BY, pa.BUSINESS_UNIT_ID, pa.COMMENTS, pa.COMPLETION_DATE, pa.DOC_ISSUE_DATE, pa.DOC_NEXT_AUD_DATE
    --, pa.RESULT
    , CASE WHEN pa.RESULT = 'PE' THEN 'Pending'
        WHEN pa.RESULT = 'PA' THEN 'Passed'
        WHEN pa.RESULT = 'F' THEN 'Failed'
        ELSE 'NA'
        END AS RESULT
    , e.NAME_1 AuditedByEMPName, e.EMPLOYEE_ID, e.WORK_EMAIL_ADDRESS
    , af.FINDING_ID, af.FINDING_TEXT, af.FINDING_TYPE, af.FOLLOWUP_TEXT, af.CLOSED_DATE
    , p.PRODUCT_ID, p.REFERENCE, p.REVISION_LEVEL, p.COMMODITY_TYPE, p.BUSINESS_UNIT_ID ProductBizUnit, p.DRAWING_NUMBER, p.ISSUE_DATE, p.LID, p.MAJOR_LOCATION, p.MINOR_LOCATION, p.NAME ProductName
FROM VQ_PRODUCT_AUDIT pa
    JOIN VQ_AUDIT_MANAGER am
        ON pa.SITE_ID = am.SITE_ID
            AND pa.SK_AUDIT_MANAGER_ID = am.AUDIT_MANAGER_ID
    LEFT JOIN VQ_EMPLOYEE e
        ON pa.EMPLOYEE_REC_ID = e.RECORD_ID
    LEFT JOIN VQ_AUDIT_FINDINGS af
        ON af.SK_PROD_AUDIT_ID = pa.AUDIT_ID
    LEFT JOIN VQ_PRODUCT_SITE ps
        ON pa.PRODUCT_SITE_REC_ID = ps.RECORD_ID
    LEFT JOIN VQ_PRODUCT p
        ON p.RECORD_ID = ps.PRODUCT_REC_ID
WHERE am.AUDIT_MANAGER_ID = @AUDIT_MANAGER_ID
    AND am.SITE_ID = @SITE_ID
