SELECT t.EC_ID as 'ECN_ID', e.CREATE_DATE as 'ECN_CREATE_DATE', 
CASE
    WHEN t.STATUS = 'I' THEN 'In Process'
    WHEN t.STATUS = 'H' THEN 'On Hold'
    WHEN t.STATUS = 'P' THEN 'Pending'
    WHEN t.STATUS = 'U' THEN 'Undefined'
    ELSE 'NOT IDENDIFIED'
END AS   EC_STATUS_DEFINED, 
t.USER_ID, 
CASE WHEN T.SUB_TYPE = 'AT' THEN 'Assigned To'
    WHEN T.SUB_TYPE = 'A'  THEN 'Authorization'
    WHEN T.SUB_TYPE = 'I'  THEN 'Implementation'
    WHEN T.SUB_TYPE = 'AP'  THEN 'Approval'
    WHEN T.SUB_TYPE = 'H'  THEN 'On Hold'
    ELSE 'NOT IDENTIFIED'
END AS SUB_TYPE_DEFINED, t.CREATE_DATE as 'TASK_CREATE_DATE', 
ECL.LINE_NO, ECL.TYPE, COALESCE(ECL.WO_BASE_ID, ECL.PART_ID, ECL.DOC_ID) AS 'ID'
, PSV.PLANNER_USER_ID -- MAY BE NULL IF BASE_ID IS A CLOSED WORK ORDER
FROM TASK t with (nolock)
INNER JOIN EC e with (nolock) on t.EC_ID = e.ID
LEFT OUTER JOIN EC_LINE ECL on t.EC_ID = ECL.EC_ID
LEFT OUTER JOIN WORK_ORDER WO ON ECL.WO_TYPE = WO.TYPE
    AND ECL.WO_BASE_ID = WO.BASE_ID
    AND ECL.WO_LOT_ID = WO.LOT_ID
    AND ECL.WO_SPLIT_ID = WO.SPLIT_ID
    and WO.STATUS NOT IN ('C', 'X')
LEFT OUTER JOIN PART_SITE_VIEW PSV ON WO.PART_ID = PSV.PART_ID
WHERE t.EC_ID  like 'DC%' and t.STATUS NOT IN ('C', 'X')
