--61 catchup w NCM PRODUCT JOIN.sql

SELECT 
      NCM.NCM_ID
    , P.PRODUCT_ID -- 
    , CO.CUSTOMER_ID
    , PO.DISPLAY_ID AS PRODUCTION_ORDER_ID
    , NCM.LOT_SIZE
    , NCM.ACCEPTED
    , NCM.REJECTED
    , NCM.NCM_DATE
    -- aliased fields can remain
    , NCM.REFERENCE_1 AS [SPEC_SECT]
    , NCM.SK_AS_IS AS [ASIS_DIM]
    , NCM.SK_SHOULD_BE AS [SHOULD_BE_DIM]
    , COALESCE(NCM.SK_FIN_NCM_PROCESS, NCM.SK_MFG_NCM_PROCESS, '') AS [PROCESS]
    , COALESCE(NCM.SK_FIN_NCM_SUBPROCESS, NCM.SK_MFG_NCM_SUBPROCESS, '') AS [SUBPROCESS]
    , ISNULL(NCM.USER_DEFINED_3, '') AS [FEATURE]
    , COALESCE(NCM.USER_DEFINED_7, NCM.USER_DEFINED_4, '') AS [DEFECT]
    -- changes for null
    , ISNULL(NCM.DISPOSITION_TYPE, '') AS DISPOSITION_TYPE
    , NCM.DISPOSITION
    , DISP_EE.[FIRST_NAME] + ' ' + DISP_EE.[LAST_NAME] AS [DISP_BY]
    , ISNULL(NCM.[STATUS], '') AS [NCM_STATUS]
    , ISNULL(NCM.BUSINESS_UNIT_ID, '') AS BUSINESS_UNIT
    -- changes for null
    , ISNULL(NCM.NCM_TYPE, '') AS NCM_TYPE
    , NCM.SK_ROOT_CAUSE
    , NCM.SK_ROOT_CAUSE_ANALYSIS
    , PS.PLANNER_USER_ID
-- ------------------------------------------------
--- combo report ends -----------------------------
-- ------------------------------------------------
    ,NCM.[RECORD_ID]

      ,NCM.[ENTITY_ID]
      ,NCM.[SITE_ID]
     -- ,NCM.[NCM_ID]
     -- ,NCM.[NCM_TYPE]
     -- ,NCM.[NCM_DATE]
      ,NCM.[CAUSE_CODE]
      ,NCM.[STATUS]
      ,NCM.[STATUS_EFFECTIVE_DATE]
      ,NCM.[CLOSED_DATE]
      ,NCM.[REPORTED_BY]
      ,NCM.[REPORTED_BY_EMP_REC_ID]
      ,NCM.[REPORTED_BY_CUST_REC_ID]
      ,NCM.[REPORTED_BY_SUPP_REC_ID]
      ,NCM.[CUST_CONT_NO]
      ,NCM.[SUPP_CONT_NO]
      ,NCM.[ASSIGNED_TO_REC_ID]
      ,NCM.[SUBJECT]
      ,NCM.[LOCATION_GENERATED]
      ,NCM.[LOCATION_FOUND]
      ,NCM.[DUE_DATE]
      ,NCM.[REFERENCE_1]
      ,NCM.[REFERENCE_2]
      ,NCM.[REFERENCE_3]
      ,NCM.[REFERENCE_4]
      ,NCM.[REFERENCE_5]
      ,NCM.[REFERENCE_6]
      ,NCM.[REFERENCE_7]
      ,NCM.[REFERENCE_8]
      ,NCM.[REFERENCE_9]
      ,NCM.[REFERENCE_10]
      ,NCM.[REFERENCE_11]
      ,NCM.[REFERENCE_12]
      ,NCM.[REFERENCE_13]
      ,NCM.[REFERENCE_14]
      ,NCM.[REFERENCE_15]
      ,NCM.[USER_DEFINED_1]
      ,NCM.[USER_DEFINED_2]
      ,NCM.[USER_DEFINED_3]
      ,NCM.[USER_DEFINED_4]
      ,NCM.[USER_DEFINED_5]
      ,NCM.[USER_DEFINED_6]
      ,NCM.[USER_DEFINED_7]
      ,NCM.[PRD_INSP_PLN_REC_ID]
      ,NCM.[PRODUCT_REC_ID]
      ,NCM.[OPERATION_NO]
      ,NCM.[LOT_REC_ID]
      ,NCM.[PO_NUMBER]
      ,NCM.[LOT_NUMBER]
      --,NCM.[LOT_SIZE]
      --,NCM.[ACCEPTED]
      --,NCM.[REJECTED]
      ,NCM.[MADE_BY]
      ,NCM.[MADE_BY_EMP_REC_ID]
      ,NCM.[MADE_BY_CUST_REC_ID]
      ,NCM.[MADE_BY_SUPP_REC_ID]
      ,NCM.[EQUIPMENT_REC_ID]
      ,NCM.[TOOL_REC_ID]
      ,NCM.[DEVICE_REC_ID]
      ,NCM.[CHECKED_BY]
      ,NCM.[CHECKED_BY_EMP_REC_ID]
      ,NCM.[CHECKED_BY_CUST_REC_ID]
      ,NCM.[CHECKED_BY_SUPP_REC_ID]
      ,NCM.[COLL_USER_DEF_1]
      ,NCM.[PROCESS_REC_ID]
      ,NCM.[PROCESS_MODEL_REC_ID]
      ,NCM.[TRPC_OPERATION_NO]
      ,NCM.[DISP_DATE]
     -- ,NCM.[DISPOSITION_TYPE]
      ,NCM.[DISP_ASSG_TO_REC_ID]
      ,NCM.[DISP_DUE_DATE]
   --   ,NCM.[DISP_BY]
      ,NCM.[DISP_EMP_REC_ID]
      ,NCM.[DISP_CUST_REC_ID]
      ,NCM.[DISP_SUPP_REC_ID]
      ,NCM.[DISP_CUST_CONT]
      ,NCM.[DISP_SUPP_CONT]
      ,NCM.[DISP_STATUS]
      ,NCM.[DISP_STATUS_EFFECTIVE_DATE]
      ,NCM.[DISP_CLOSED_DATE]
      ,NCM.[VERIFY_DATE]
      ,NCM.[VERIFY_ASSG_TO_REC_ID]
      ,NCM.[VERIFY_DUE_DATE]
      ,NCM.[VERIFY_BY_REC_ID]
      ,NCM.[VERIFY_STATUS]
      ,NCM.[VERIFY_STATUS_EFFECTIVE_DATE]
      ,NCM.[VERIFY_CLOSED_DATE]
      ,NCM.[SERIAL_NUMBER]
      ,NCM.[MEETING_ID]
      ,NCM.[PROD_ORDER_REC_ID]
      ,NCM.[OPERATION_REC_ID]
      ,NCM.[ERP_ID1]
      ,NCM.[ERP_ID2]
      ,NCM.[ERP_ID3]
      ,NCM.[ERP_ID4]
      ,NCM.[ERP_ID5]
      ,NCM.[ERP_ID6]
      ,NCM.[ERP_ID7]
      ,NCM.[ERP_ID8]
      ,NCM.[ERP_ID9]
      ,NCM.[BUSINESS_UNIT_ID]
      ,NCM.[LID]
      ,NCM.[VARIATION_ID]
      ,NCM.[SOR_STATUS]
      ,NCM.[DESCRIPTION]
     -- ,NCM.[DISPOSITION]
      ,NCM.[SERIAL_NUMBERS]
      ,NCM.[VERIFICATION]
      ,NCM.[CreatedBy]
      ,NCM.[UpdatedBy]
      ,NCM.[CreateDate]
      ,NCM.[RecordDate]
      ,NCM.[RowPointer]
      ,NCM.[NoteExistsFlag]
      ,NCM.[InWorkflow]
      ,NCM.[SK_DRAWING_NOTREQUIRED]
      ,NCM.[SK_FIN_CATEGORY]
      ,NCM.[SK_FIN_NCM_PROCESS]
      ,NCM.[SK_FIN_NCM_SUBPROCESS]
      ,NCM.[SK_MFG_NCM_PROCESS]
      ,NCM.[SK_MFG_NCM_SUBPROCESS]
   --   ,NCM.[SK_ROOT_CAUSE_ANALYSIS]
      ,NCM.[SK_AS_IS]
      ,NCM.[SK_SHOULD_BE]
      ,NCM.[SK_SUPPLIER_NOTICE_SENT]
      ,NCM.[SK_DRAWINGREV]
   --   ,NCM.[SK_ROOT_CAUSE]
FROM dbo.VQ_NONCONFORMANCE NCM (NOLOCK)
LEFT OUTER JOIN dbo.VQ_PRODUCT P
    ON P.RECORD_ID = NCM.PRODUCT_REC_ID
LEFT OUTER JOIN dbo.VQ_PRODUCTION_ORDER PO
    ON PO.RECORD_ID = NCM.PROD_ORDER_REC_ID
LEFT OUTER JOIN [SQL-LAB-2].[LIVE].dbo.PART PS
    ON PS.ID = P.PRODUCT_ID
LEFT OUTER JOIN VQ_EMPLOYEE DISP_EE
    ON DISP_EE.RECORD_ID = NCM.[DISP_EMP_REC_ID]
LEFT OUTER JOIN [SQL-LAB-2].[LIVE].dbo.DEMAND_SUPPLY_LINK DSL
    ON PO.DISPLAY_ID = DSL.SUPPLY_BASE_ID + '/' + DSL.SUPPLY_LOT_ID
LEFT OUTER JOIN [SQL-LAB-2].[LIVE].dbo.CUSTOMER_ORDER CO
    ON CO.ID = DSL.DEMAND_BASE_ID
    AND DSL.[DEMAND_TYPE] = 'CO'
WHERE 1=1
and ncm.RecordDate >= '2025-09-10'
--and
--ISNULL(NCM.NCM_TYPE,NCM. '_Blank') IN (@NCMTYPE)
--    AND ISNULL(NCM.[STATUS],NCM. '_Blank') IN (@NCMSTATUS)
--    AND ISNULL(NCM.DISPOSITION_TYPE,NCM. '_Blank') IN (@DISPTYPE)
--    AND COALESCE(NCM.SK_FIN_NCM_PROCESS,NCM. NCM.SK_MFG_NCM_PROCESS,NCM. '_BLANK') IN (@PROCESS)
--    AND COALESCE(NCM.SK_FIN_NCM_SUBPROCESS,NCM. NCM.SK_MFG_NCM_SUBPROCESS,NCM. '_BLANK') IN (@SUBPROCESS)
--    AND ISNULL(NCM.BUSINESS_UNIT_ID,NCM. '_Blank') IN (@BUSUNIT)
--    AND ISNULL(NCM.USER_DEFINED_3,NCM. '_Blank') IN (@FEATURE)
--    AND COALESCE(NCM.USER_DEFINED_7,NCM. NCM.USER_DEFINED_4,NCM. '_Blank') IN (@DEFECT)
--    AND NCM.NCM_DATE >= @STARTDATE
--    AND NCM.NCM_DATE <= @ENDDATE
--    AND PS.PLANNER_USER_ID IN (@PLANNER)
--    AND ISNULL(CO.CUSTOMER_ID,NCM. '_Blank') IN (@CUSTID)
