SELECT pa.AUDIT_ID, pa.BUSINESS_UNIT_ID, pa.AUDITED_BY, e.NAME_1 AS AuditedByEMPNAME
    , pa.COMMENTS, pa.COMPLETION_DATE, pa.DUE_DATE, pa.ISSUE_DATE, pa.NEXT_AUDIT_DATE, pa.SK_AUDIT_MANAGER_ID
    --, pa.RESULT
    , CASE WHEN pa.RESULT = 'PE' THEN 'Pending'
        WHEN pa.RESULT = 'F' THEN 'Failed'
        WHEN pa.RESULT = 'P' THEN 'Passed'
    END AS RESULT
    , pa.REVISION_LEVEL
    , p.BUSINESS_UNIT_ID as ProcessBizUnit, p.PROCESS_ID, p.PROCESS_NAME, p.STATUS_EFFECTIVE_DATE ProcessStatusEffDate, p.CONTROL_FUN_CODE, p.CONTROL_JOB_CODE, p.LOCATION, p.MISSION, p.SOR_STATUS, p.VARIATION_ID
    , pm.ACTIVITY_NO, pm.AREA_NUMBER, pm.DESCRIPTION, pm.ELEMENT_NO, pm.FUNCTION_CODE, pm.JOB_CODE, pm.NAME AS PROCESSMODEL_NAME, pm.PROCESS_LEVEL
    --, af.FINDING_ID, af.FINDING_TEXT, af.FINDING_TYPE, af.FOLLOWUP_TEXT, af.CLOSED_DATE FindingClosedDate
    --, fe.EMPLOYEE_ID FindingEMPID, fe.NAME_1 FindingEMPName, fe.WORK_EMAIL_ADDRESS FindingEMPEmail
    --, p.*
    --, pa.*
    --, pm.*
    --, af.*
FROM VQ_PROCESS_AUDIT pa
    --JOIN VQ_AUDIT_MANAGER am
    --    ON pa.SITE_ID = am.SITE_ID
    --        AND pa.SK_AUDIT_MANAGER_ID = am.AUDIT_MANAGER_ID
    LEFT JOIN VQ_EMPLOYEE e
        ON pa.EMPLOYEE_REC_ID = e.RECORD_ID

    JOIN VQ_PROCESS p
        ON p.RECORD_ID = pa.PROCESS_REC_ID
    JOIN VQ_PROCESS_MODEL pm
        ON pm.RECORD_ID = pa.PROCESS_MODEL_REC_ID    
    --LEFT JOIN VQ_AUDIT_FINDINGS af
    --    ON af.SK_PROC_AUDIT_ID = pa.AUDIT_ID
    --LEFT JOIN VQ_EMPLOYEE fe
    --    ON af.FOLLOWUP_BY_REC_ID = fe.RECORD_ID
WHERE pa.AUDIT_ID = @AUDIT_ID
    AND pa.SITE_ID = @SITE_ID
