--IQM Report > Tags not Closed
SELECT NCM_ID
    , PO.DISPLAY_ID AS PRODUCTION_ORDER_ID
    , NCM.PO_NUMBER AS VENDOR_PO_NUM
    , O.DISPLAY_ID AS OPERATION_ID
    , MADE_EE.EMPLOYEE_ID AS MADE_BY_EEID
    , MADE_EE.FIRST_NAME AS MADE_BY_EE_FNAME
    , MADE_EE.LAST_NAME AS MADE_BY_EE_LNAME
    , NCM.LOT_SIZE
    , NCM.ACCEPTED
    , NCM.REJECTED
    , NCM.NCM_TYPE
    , NCM.NCM_DATE
    , ISNULL(NCM.[STATUS], '_BLANK') AS [STATUS]
    , NCM.CLOSED_DATE
    , NCM.DUE_DATE
    , P.PRODUCT_ID
    , ISNULL(NCM.USER_DEFINED_1, NCM.USER_DEFINED_5) AS [PROCESS]
    , ISNULL(NCM.USER_DEFINED_2, NCM.USER_DEFINED_6) AS [SUBPROCESS]
    , NCM.USER_DEFINED_3 AS [CATEGORY]
    , ISNULL(NCM.USER_DEFINED_4, NCM.USER_DEFINED_7) AS [DEFECT]
    , NCM.DISPOSITION_TYPE
    , DT.[DESCRIPTION] AS DISP_DESC
    , NCM.DISP_DATE
    , NCM.REFERENCE_6 AS [REWORK_QTY]
    , NCM.REFERENCE_7 AS [SCRAP_QTY]
    , NCM.REFERENCE_8 AS [OVERAGE_QTY]
    , NCM.REFERENCE_9 AS [RETURN_QTY]
    , NCM.REFERENCE_10 AS [ASIS_QTY]
    , ISNULL(NCM.SK_FIN_NCM_PROCESS, NCM.SK_MFG_NCM_PROCESS) AS SK_NCM_PROCESS
    , ISNULL(NCM.SK_FIN_NCM_SUBPROCESS, NCM.SK_MFG_NCM_SUBPROCESS) AS SK_NCM_SUBPROCESS
    , SR.USER_1
    , CASE
        WHEN SR.USER_1 = 'A' THEN 'FIN'
        WHEN SR.USER_1 = 'M' THEN 'MFG'
        WHEN SR.USER_1 = 'O' THEN 'OUTREACH'
        WHEN SR.USER_1 = 'B' THEN 'BALLARD'
        WHEN SR.USER_1 = 'C' THEN 'CLOSED'
        ELSE '_Blank'
    END AS BUSINESS_UNIT
FROM DATAWAREHOUSE.DBO.VQ_NONCONFORMANCE NCM
LEFT OUTER JOIN DATAWAREHOUSE.DBO.VQ_PRODUCT P
    ON P.RECORD_ID = NCM.PRODUCT_REC_ID
LEFT OUTER JOIN DATAWAREHOUSE.DBO.VQ_PRODUCTION_ORDER PO
    ON PO.RECORD_ID = NCM.PROD_ORDER_REC_ID
LEFT OUTER JOIN DATAWAREHOUSE.DBO.VQ_OPERATION O
    ON O.RECORD_ID = NCM.OPERATION_REC_ID
LEFT OUTER JOIN DATAWAREHOUSE.DBO.VQ_DISPOSITION_TYPE DT
    ON DT.[DISPOSITION_TYPE] = NCM.[DISPOSITION_TYPE]
LEFT OUTER JOIN DATAWAREHOUSE.DBO.VQ_EMPLOYEE MADE_EE
    ON MADE_EE.RECORD_ID = NCM.MADE_BY_EMP_REC_ID
LEFT OUTER JOIN DATAWAREHOUSE.DBO.OPERATION OP
    ON PO.[ALT_ID_2] = OP.WORKORDER_BASE_ID
    AND PO.[ALT_ID_3] = OP.WORKORDER_LOT_ID
    AND PO.[ALT_ID_4] = OP.WORKORDER_SPLIT_ID
    AND PO.[ALT_ID_5] = OP.WORKORDER_SUB_ID
    AND PO.[ALT_ID_1] = OP.WORKORDER_TYPE
LEFT OUTER JOIN DATAWAREHOUSE.DBO.SHOP_RESOURCE_SITE SR
    ON SR.RESOURCE_ID = OP.RESOURCE_ID
WHERE NCM.NCM_DATE >= @StartDate
    AND NCM.NCM_DATE <= @EndDate
    AND NCM.[STATUS] IN (@Status)
    AND CASE
        WHEN SR.USER_1 = 'A' THEN 'FIN'
        WHEN SR.USER_1 = 'M' THEN 'MFG'
        WHEN SR.USER_1 = 'O' THEN 'OUTREACH'
        WHEN SR.USER_1 = 'B' THEN 'BALLARD'
        WHEN SR.USER_1 = 'C' THEN 'CLOSED'
        ELSE '_Blank'
    END IN (@BUSUNIT)
