SELECT 
      R.INVOICE_ID,
      R.CUSTOMER_ID,
      C.NAME,
      C.ADDR_1,
      C.ADDR_2,
      C.ADDR_3,
      C.CITY,
      C.STATE,
      C.ZIPCODE,
      RL.REFERENCE,
      'Due on Payment Terms' AS TERMS,
      R.INVOICE_DATE,
      RL.LINE_NO,
      RL.QTY AS QUANTITY,
      RL.AMOUNT,
      CONVERT( DECIMAL(8,2),RL.AMOUNT / RL.QTY) AS UNIT_PRICE,
      CAST(CAST(BITS AS    VARBINARY(MAX)) AS NVARCHAR(MAX)) AS INVOICE_LONG_DESCRIPTION
FROM   RECEIVABLE R
      INNER JOIN RECEIVABLE_LINE RL
        ON R.INVOICE_ID = RL.INVOICE_ID
      INNER JOIN CUSTOMER C
        ON C.ID = R.CUSTOMER_ID
      LEFT OUTER JOIN RECEIVABLE_BINARY RB
        ON R.INVOICE_ID = RB.INVOICE_ID
WHERE  R.INVOICE_ID = @invoice_id;
