SELECT ISNULL(NCM.USER_DEFINED_4, NCM.USER_DEFINED_7) AS DEFECT
    , COUNT(*) AS [DEFECT_COUNT]
FROM OPERATION O
INNER JOIN SHOP_RESOURCE SR
    ON SR.ID = O.RESOURCE_ID
INNER JOIN VQ_PRODUCTION_ORDER PO
    ON PO.[ALT_ID_2] = O.WORKORDER_BASE_ID
    AND PO.[ALT_ID_3] = O.WORKORDER_LOT_ID
    AND PO.[ALT_ID_4] = O.WORKORDER_SPLIT_ID
    AND PO.[ALT_ID_5] = O.WORKORDER_SUB_ID
    AND PO.[ALT_ID_1] = O.WORKORDER_TYPE
INNER JOIN VQ_OPERATION OI
    ON OI.[ID] = CAST(O.WORKORDER_TYPE AS NVARCHAR(1)) + '~' + CAST(O.WORKORDER_BASE_ID AS NVARCHAR(7)) + '~' 
        + CAST(O.WORKORDER_LOT_ID AS NVARCHAR(1)) + '~' + CAST(O.WORKORDER_SPLIT_ID AS NVARCHAR(1)) + '~' 
        + CAST(O.WORKORDER_SUB_ID AS NVARCHAR(1)) + '~' + CAST(O.SEQUENCE_NO AS NVARCHAR(5))
INNER JOIN VQ_NONCONFORMANCE NCM
    ON PO.RECORD_ID = NCM.PROD_ORDER_REC_ID
    AND OI.RECORD_ID = NCM.OPERATION_REC_ID
INNER JOIN VQ_PRODUCT P
    ON P.RECORD_ID = NCM.PRODUCT_REC_ID
WHERE O.CLOSE_DATE >= @STARTDATE
    AND O.CLOSE_DATE <= @ENDDATE
    AND (NCM.SITE_ID = 'SK01' OR NCM.SITE_ID IS NULL)
    AND NCM.NCM_ID IS NOT NULL
    AND NCM.NCM_TYPE NOT IN ('OVERAGE')
    AND NCM.DISPOSITION_TYPE NOT IN ('NON-DISCREPANT', 'OVERAGE')
    AND SR.USER_6 != 'PENETRANT'
    AND SR.USER_8 IN (@DEPARTMENT)
    AND SR.USER_5 IN (@FACILITY)
    AND O.[STATUS] != 'X'
GROUP BY SR.USER_8
    , SR.USER_5
    , ISNULL(NCM.USER_DEFINED_4, NCM.USER_DEFINED_7)
