--> VISUAL ENTERPRISE > WORK ORDER REPORTS > CommBoard Ops Bar Chart

SET DATEFIRST 1;

SELECT SR.USER_5 AS [FACILITY]
	, SR.USER_7 AS [PROCESS]
	, SR.USER_8 AS [DEPARTMENT]
	, CASE
		WHEN @TIMEFRAME IN ('LAST WEEK', 'CURRENT WEEK') THEN DATENAME(WEEKDAY, O.CLOSE_DATE)
		WHEN @TIMEFRAME IN ('LAST MONTH', 'CURRENT MONTH', 'OTHER') THEN CONVERT(VARCHAR(15), DATEADD(WEEK, DATEDIFF(WEEK, 0, O.CLOSE_DATE), -1), 101)
		ELSE DATENAME(MONTH, O.CLOSE_DATE)
	END AS [TIMEFRAME]
	, CASE
		WHEN @TIMEFRAME IN ('LAST WEEK', 'CURRENT WEEK') THEN CONVERT(NVARCHAR(15), O.CLOSE_DATE, 101)
		WHEN @TIMEFRAME IN ('LAST MONTH', 'CURRENT MONTH', 'OTHER') THEN ''
		ELSE CONVERT(NVARCHAR(15), YEAR(O.CLOSE_DATE))
	END AS [LABEL]
	, O.CLOSE_DATE

	, CAST(CAST(YEAR(O.CLOSE_DATE) AS VARCHAR(4)) + ' ' + RIGHT('00' + CAST(DATEPART(WW, DATEADD(WEEK, DATEDIFF(WEEK, 0, O.CLOSE_DATE), -1)) AS VARCHAR(2)), 2) AS NVARCHAR(7))

	, CASE
		WHEN @TIMEFRAME IN ('LAST MONTH', 'CURRENT MONTH', 'OTHER') THEN CAST(CAST(YEAR(O.CLOSE_DATE) AS VARCHAR(4)) + ' ' + RIGHT('00' + CAST(DATEPART(WW, DATEADD(WEEK, DATEDIFF(WEEK, 0, O.CLOSE_DATE), -1)) AS VARCHAR(2)), 2) AS NVARCHAR(10))
--		WHEN @TIMEFRAME IN ('LAST MONTH', 'CURRENT MONTH', 'OTHER') THEN YEAR(O.CLOSE_DATE) + '-' + DATEPART(WW, DATEADD(WEEK, DATEDIFF(WEEK, 0, O.CLOSE_DATE), -1))
		WHEN @TIMEFRAME IN ('LAST WEEK', 'CURRENT WEEK') THEN CAST(CAST(O.CLOSE_DATE AS VARCHAR(10)) AS NVARCHAR(10))
		ELSE CAST(CAST(DATEPART(MM, O.CLOSE_DATE) AS VARCHAR(10)) AS NVARCHAR(10))
	END [CHARTSORT]
	, CASE
		WHEN @TIMEFRAME = 'LAST WEEK' THEN CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 7, GETDATE()), 0))
		WHEN @TIMEFRAME = 'CURRENT WEEK' THEN CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0))
		WHEN @TIMEFRAME = 'LAST MONTH' THEN CONVERT(DATE, DATEADD(MM, DATEDIFF(MM, 0, GETDATE()) - 1, 0))
		WHEN @TIMEFRAME = 'CURRENT MONTH' THEN CONVERT(DATE, DATEADD(D, -(DAY(GETDATE()-1)), GETDATE()))
		WHEN @TIMEFRAME = 'LAST YEAR' THEN CONVERT(DATE, DATEADD(YEAR, DATEDIFF(YEAR, 0, GETDATE()) - 1, 0))
		WHEN @TIMEFRAME = 'CURRENT YEAR' THEN CONVERT(DATE, DATEADD(YY, DATEDIFF(YY, 0, GETDATE()), 0)) 
		WHEN @TIMEFRAME = 'LAST QUARTER' THEN CONVERT(DATE, DATEADD(QUARTER, DATEDIFF(QUARTER, 0 , GETDATE()) - 1, 0))
		WHEN @TIMEFRAME = 'CURRENT QUARTER' THEN CONVERT(DATE, DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()), 0))
		WHEN @TIMEFRAME = 'OTHER' THEN @STARTDATE
		ELSE 'ERROR'
	END AS [STARTDATE]
	, CASE
		WHEN @TIMEFRAME = 'LAST WEEK' THEN CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 7, GETDATE()), 6))
		WHEN @TIMEFRAME = 'CURRENT WEEK' THEN CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 6))
		WHEN @TIMEFRAME = 'LAST MONTH' THEN CONVERT(DATE, DATEADD(D, -(DAY(GETDATE())), GETDATE()))
		WHEN @TIMEFRAME = 'CURRENT MONTH' THEN CONVERT(DATE, EOMONTH(GETDATE()))
		WHEN @TIMEFRAME = 'LAST YEAR' THEN CONVERT(DATE, DATEADD(YEAR, DATEDIFF(YEAR, 0, GETDATE()), -1))
		WHEN @TIMEFRAME = 'CURRENT YEAR' THEN CONVERT(DATE, DATEADD(YY, DATEDIFF(YY, 0, GETDATE()) + 1, -1))
		WHEN @TIMEFRAME = 'LAST QUARTER' THEN CONVERT(DATE, DATEADD(DD, -1, DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()), 0)))
		WHEN @TIMEFRAME = 'CURRENT QUARTER' THEN CONVERT(DATE, DATEADD(DD, -1, DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()) + 1, 0)))
		WHEN @TIMEFRAME = 'OTHER' THEN @ENDDATE
		ELSE 'ERROR'
	END AS [ENDDATE]
FROM DATAWAREHOUSE.DBO.OPERATION O
LEFT OUTER JOIN DATAWAREHOUSE.DBO.SHOP_RESOURCE_SITE SR
	ON SR.RESOURCE_ID = O.RESOURCE_ID
WHERE (
		(@TIMEFRAME = 'LAST WEEK' 
			AND O.CLOSE_DATE >= CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 7, GETDATE()), 0))
			AND O.CLOSE_DATE <= CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 7, GETDATE()), 7))
		)
		OR (@TIMEFRAME = 'CURRENT WEEK' 
			AND O.CLOSE_DATE >= CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0))
			AND O.CLOSE_DATE <= CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 7))
		)
		OR (@TIMEFRAME = 'LAST MONTH' 
			AND O.CLOSE_DATE >= CONVERT(DATE, DATEADD(MM, DATEDIFF(MM, 0, GETDATE()) - 1, 0))
			AND O.CLOSE_DATE <= CONVERT(DATE, DATEADD(D, -(DAY(GETDATE())), GETDATE()))
		)
		OR (@TIMEFRAME = 'CURRENT MONTH' 
			AND O.CLOSE_DATE >= CONVERT(DATE, DATEADD(D, -(DAY(GETDATE()-1)), GETDATE()))
			AND O.CLOSE_DATE <= CONVERT(DATE, EOMONTH(GETDATE()))
		)
		OR (@TIMEFRAME = 'LAST YEAR' 
			AND O.CLOSE_DATE >= CONVERT(DATE, DATEADD(YEAR, DATEDIFF(YEAR, 0, GETDATE()) - 1, 0))
			AND O.CLOSE_DATE <= CONVERT(DATE, DATEADD(YEAR, DATEDIFF(YEAR, 0, GETDATE()), -1))
		)
		OR (@TIMEFRAME = 'CURRENT YEAR' 
			AND O.CLOSE_DATE >= CONVERT(DATE, DATEADD(YY, DATEDIFF(YY, 0, GETDATE()), 0)) 
			AND O.CLOSE_DATE <= CONVERT(DATE, DATEADD(YY, DATEDIFF(YY, 0, GETDATE()) + 1, -1))
		)
		OR (@TIMEFRAME = 'LAST QUARTER' 
			AND O.CLOSE_DATE >= CONVERT(DATE, DATEADD(QUARTER, DATEDIFF(QUARTER, 0 , GETDATE()) - 1, 0))
			AND O.CLOSE_DATE <= CONVERT(DATE, DATEADD(DD, -1, DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()), 0)))
		)
		OR (@TIMEFRAME = 'CURRENT QUARTER' 
			AND O.CLOSE_DATE >= CONVERT(DATE, DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()), 0))
			AND O.CLOSE_DATE <= CONVERT(DATE, DATEADD (DD, -1, DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()) + 1, 0)))
		)
	)
	AND ISNULL(SR.USER_5, '_BLANK') IN (@FACILITY)
	AND ISNULL(SR.USER_7, '_BLANK') IN (@PROCESS)
	AND ISNULL(SR.USER_8, '_BLANK') IN (@DEPARTMENT)
	AND O.[STATUS] != 'X'