--DECLARE @PART_ID NVARCHAR(30) -- = '411T3484-66B'
--    SELECT @PART_ID = PART_ID 
--    FROM WORK_ORDER wo
--    WHERE wo.BASE_ID = @BASE_ID
--        AND wo.LOT_ID = @LOT_ID
--        AND wo.SUB_ID = '0'
--        AND wo.SPLIT_ID = @SPLIT_ID

--DECLARE @B_TYPE NVARCHAR(1) = 'W'
--DECLARE @BASE_ID NVARCHAR(30) = '1517994'
--DECLARE @LOT_ID NVARCHAR(3) = '1'
--DECLARE @SPLIT_ID NVARCHAR(3)= '0'
--DECLARE @SUB_ID NVARCHAR(3) = '0'
--DECLARE @SEQ_NO SMALLINT = 10

;WITH cte_OPERATION AS
(
    SELECT O.WORKORDER_TYPE, 
           O.WORKORDER_BASE_ID, 
           O.WORKORDER_LOT_ID, 
          O.WORKORDER_SPLIT_ID,
          O.WORKORDER_SUB_ID, 
          O.OPERATION_TYPE, 
          O.SEQUENCE_NO
     FROM OPERATION O
    WHERE O.WORKORDER_TYPE = @B_TYPE 
         AND O.WORKORDER_BASE_ID = @BASE_ID
        AND  O.WORKORDER_LOT_ID = @LOT_ID
        AND  O.WORKORDER_SPLIT_ID = @SPLIT_ID
        AND  O.WORKORDER_SUB_ID = @SUB_ID
      --  AND O.SEQUENCE_NO = @SEQ_NO
)

 --SELECT * FROM CTE_OPERATION

,cte_custspecs
AS
(
    SELECT 
     UDF.DOCUMENT_ID
    ,STRING_VAL AS CUST_SPECIFIC_SPEC
    ,RIGHT(UDF.DOCUMENT_ID,(REVERSE(CHARINDEX('~', UDF.DOCUMENT_ID)))) AS SEQUENCE_NO
    ,SUBSTRING(UDF.DOCUMENT_ID, CHARINDEX(N'~',UDF.DOCUMENT_ID, CHARINDEX(N'~',UDF.DOCUMENT_ID)+1)+1,1) AS SUB_ID
    , ROW_NUMBER() OVER(PARTITION BY UDF.DOCUMENT_ID ORDER BY  UDF.ID) as num
    FROM USER_DEF_FIELDS UDF
    INNER JOIN cte_OPERATION O
       ON  O.WORKORDER_TYPE + '~'+ O.WORKORDER_BASE_ID + '~' + O.WORKORDER_SUB_ID + '~'+ O.WORKORDER_LOT_ID + '~'
       + O.WORKORDER_SPLIT_ID + '~'+ CAST(O.SEQUENCE_NO AS NVARCHAR(3))= UDF.DOCUMENT_ID
    WHERE UDF.ID IN ('UDF-0000074', 
    'UDF-0000075',
    'UDF-0000077',
    'UDF-0000078',
    'UDF-0000079',
    'UDF-0000080',
    'UDF-0000081',
    'UDF-0000076')
    AND UDF.PROGRAM_ID = 'VMMFGWIN_OP'
    AND UDF.LABEL IS NULL

       )
SELECT * FROM cte_custspecs
