-- Visual Enterprise Reports -> Work Order Reports ->

SELECT PN.ABBR2 AS plant_id, 
WO.CREATE_DATE, 
      O.WORKORDER_TYPE, 
      O.WORKORDER_BASE_ID, 
      O.WORKORDER_LOT_ID, 
      O.WORKORDER_SPLIT_ID, 
      O.WORKORDER_SUB_ID, 
      O.SEQUENCE_NO, 
      O.RESOURCE_ID, 
      O.SERVICE_ID, 
      O.OPERATION_TYPE, 
      PSV.PLANNER_USER_ID, 
      PSV.BUYER_USER_ID, 
      WO.ENGINEERED_BY
FROM WORK_ORDER WO
     INNER JOIN PART_SITE_VIEW PSV
        ON PSV.PART_ID = WO.PART_ID
    INNER JOIN OPERATION O
       ON O.WORKORDER_BASE_ID = WO.BASE_ID
         AND O.WORKORDER_LOT_ID = WO.LOT_ID
         AND O.WORKORDER_SPLIT_ID = WO.SPLIT_ID
         AND O.WORKORDER_SUB_ID = WO.SUB_ID
         AND O.WORKORDER_TYPE = 'M'
    INNER JOIN SHOP_RESOURCE SR
       ON O.RESOURCE_ID = SR.ID
    INNER JOIN LIVESUPPLEMENTAL.DBO.PLANT_NAMES PN
       ON PN.ID = SR.USER_5
WHERE O.RESOURCE_ID IN(@resource_id)
  AND PN.ABBR2 IN(@plant_id)
ORDER BY CREATE_DATE DESC;
