SELECT O.WORKORDER_TYPE AS [TYPE]
    , O.WORKORDER_BASE_ID AS [BASE_ID]
    , O.WORKORDER_LOT_ID AS [LOT]
    , O.WORKORDER_SPLIT_ID AS [SPLIT]
    , O.WORKORDER_SUB_ID AS [SUB]
    , O.SEQUENCE_NO AS [SEQ_NO]
    , O.OPERATION_TYPE AS [OPTYPE]
    , O.RESOURCE_ID
    , OB.[SPECS]
    , ISNULL(P.[STATUS], 'A') AS PART_STATUS
FROM OPERATION AS O
INNER JOIN SHOP_RESOURCE AS SR
    ON O.RESOURCE_ID = SR.ID
INNER JOIN [Datamart].dbo.[SKILL_OPERATION_BINARY] OB
    ON OB.WORKORDER_TYPE = O.WORKORDER_TYPE
    AND OB.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
    AND OB.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
    AND OB.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
    AND OB.WORKORDER_SUB_ID = O.WORKORDER_SUB_ID
    AND OB.SEQUENCE_NO = O.SEQUENCE_NO
INNER JOIN WORK_ORDER WO
    ON WO.[TYPE] = O.WORKORDER_TYPE
    AND WO.BASE_ID = O.WORKORDER_BASE_ID
    AND WO.LOT_ID = O.WORKORDER_LOT_ID
    AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
    AND WO.SUB_ID = O.WORKORDER_SUB_ID
LEFT OUTER JOIN PART P
    ON WO.PART_ID = P.ID
WHERE O.[WORKORDER_TYPE] = 'M'
    AND (
        (@SEARCH = 'Both'
        AND ISNULL(O.OPERATION_TYPE, '_Blank') IN (@OPTYPE)
        AND O.RESOURCE_ID IN (@RESOURCE_ID)
        )
        OR
        (@SEARCH = 'OpType'
        AND ISNULL(O.OPERATION_TYPE, '_Blank') IN (@OPTYPE)
        )
        OR
        (@SEARCH = 'ResourceID'
        AND O.RESOURCE_ID IN (@RESOURCE_ID)
        )
    )
