SELECT CO.ID 
    , COL.LINE_NO
    , CASE
        WHEN CO.[STATUS] = 'C' THEN 'COMPLETE'
        WHEN CO.[STATUS] = 'R' THEN 'RELEASED'
        WHEN CO.[STATUS] = 'H' THEN 'HOLD'
        WHEN CO.[STATUS] = 'X' THEN 'CANCELLED'
        ELSE 'OTHER'
    END AS CO_STATUS
    , CASE
        WHEN COL.LINE_STATUS = 'C' THEN 'SHIP SHORT'
        ELSE ''
    END AS LINE_STATUS
    , CO.CUSTOMER_ID 
    , UDF.STRING_VAL AS BUSUNIT
    , CO.ORDER_DATE
    , COL.PART_ID
    , COL.SERVICE_CHARGE_ID
    , COL.ORDER_QTY
    , COL.UNIT_PRICE
    , COL.USER_5
FROM CUSTOMER_ORDER CO
INNER JOIN CUST_ORDER_LINE COL
    ON COL.CUST_ORDER_ID = CO.ID
LEFT OUTER JOIN USER_DEF_FIELDS UDF
    ON UDF.DOCUMENT_ID = CO.CUSTOMER_ID
    AND PROGRAM_ID = 'VMCUSMNT'
    AND UDF.ID = 'UDF-0000072'
WHERE CO.ORDER_DATE >= @STARTDATE
    AND UDF.STRING_VAL IN (@BUSUNIT)
