-- VISUAL ENTERPRISE > WORK_ORDER REPORTS > UNPRINTED WORK ORDERS2
SELECT WO.BASE_ID
    , WO.LOT_ID
    , WO.SPLIT_ID
    , WO.SUB_ID
    , WO.PART_ID
    , P.[DESCRIPTION]
    , P.COMMODITY_CODE
    , WO.CREATE_DATE
    , WO.DESIRED_RLS_DATE
    , WO.DESIRED_WANT_DATE
    , WO.[STATUS]
    , WO.PRINTED_DATE
    , WO.[TYPE]
    , WO.ACT_MATERIAL_COST
    , WO.ACT_LABOR_COST
    , WO.ACT_SERVICE_COST
    , P.PLANNER_USER_ID
    , WO.DESIRED_QTY
FROM WORK_ORDER WO
LEFT OUTER JOIN PART_SITE_VIEW P
    ON WO.PART_ID = P.PART_ID
WHERE WO.[TYPE] = 'W'
    AND WO.[STATUS] IN ('F', 'R', 'U') 
    AND WO.ACT_MATERIAL_COST = 0 
    AND WO.ACT_SERVICE_COST = 0 
    AND P.PLANNER_USER_ID IN (@PLANNER)
    AND WO.PRINTED_DATE IS NULL
