-- VISUAL ENTERPRISE > SHIPPING REPORTS > WO MRP STATUS
/**********************************************************************
-- Author: traci treffert
-- Create date: 20211027
**********************************************************************/
SELECT WO.BASE_ID
    , WO.LOT_ID
    , WO.SPLIT_ID
    , WO.SUB_ID
    , WO.PART_ID
    , WO.[STATUS]
    , WO.RECEIVED_QTY
    , WO.DESIRED_QTY
    , WO.DESIRED_RLS_DATE
    , WO.DESIRED_WANT_DATE
    , P.PLANNER_USER_ID
    , P.BUYER_USER_ID
    , P.COMMODITY_CODE
    , P.PLANNING_LEADTIME
    , P.ORDER_POLICY
    , P.SAFETY_STOCK_QTY
    , P.MINIMUM_ORDER_QTY
    , P.QTY_AVAILABLE_ISS
    , P.QTY_ON_HAND    
    , P.QTY_ON_HAND - P.QTY_AVAILABLE_ISS AS QTY_ON_HOLD    
    , P.QTY_ON_ORDER
    , P.ENGINEERING_MSTR
    , WCA.EXPR1 AS CURRENT_OPS
    , REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(WCA.REMAINING_OPS,
        'AUB-', ''),'BAL-', ''),'AMP;', ''),'(CONTRACTOR)','(O/S)'), 'PRECISION', ''), 'ASSEMBLY, ASSEMBLY', 'ASSEMBLY')
        , 'CNCMILL, CNCMILL', 'CNCMILL'), 'CNCMILL-4, CNCMILL-4', 'CNCMILL-4'), 'TITANIUM', 'TI'), 'OKUMA, OKUMA', 'OKUMA')
        , 'HONING, HONING', 'HONING'), 'BRAKEFORM, BRAKEFORM', 'BRAKEFORM') AS REMAINING_OPS
    , CASE 
        WHEN WO.RECEIVED_QTY > 0 AND P.QTY_AVAILABLE_ISS > 0 THEN '(' + CAST(CAST(P.QTY_AVAILABLE_ISS AS INT) AS NVARCHAR) + ')' + ' IN STOCK, ' + WO.BASE_ID + ' INTERNAL SPLIT'
        WHEN WO.RECEIVED_QTY > 0 AND P.QTY_AVAILABLE_ISS = 0 THEN WO.BASE_ID + ' (' + CAST(CAST((WO.DESIRED_QTY - WO.RECEIVED_QTY) AS INT) AS NVARCHAR) + ')  INTERNAL SPLIT'
        WHEN WO.[STATUS] = 'F' THEN WO.BASE_ID + ' (' + CAST(CAST(WO.DESIRED_QTY AS INT) AS NVARCHAR) + ')  FIRMED'
        WHEN WO.[STATUS] = 'U' THEN WO.BASE_ID + ' (' + CAST(CAST(WO.DESIRED_QTY AS INT) AS NVARCHAR) + ')  ON HOLD'
        WHEN WCA.EXPR1 IS NULL THEN  WO.BASE_ID + ' (' + CAST(CAST(WO.DESIRED_QTY AS INT) AS NVARCHAR) + ')  COMPLETE'
        WHEN REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(WCA.REMAINING_OPS,
            'AUB-', ''),'BAL-', ''),'AMP;', ''),'(CONTRACTOR)','(O/S)'), 'PRECISION', ''), 'ASSEMBLY, ASSEMBLY', 'ASSEMBLY'), 'CNCMILL, CNCMILL', 'CNCMILL')
            , 'CNCMILL-4, CNCMILL-4', 'CNCMILL-4'), 'TITANIUM', 'TI'), 'OKUMA, OKUMA', 'OKUMA'), 'HONING, HONING', 'HONING'), 'BRAKEFORM, BRAKEFORM', 'BRAKEFORM') IS NULL 
                THEN WO.BASE_ID + ' (' + CAST(CAST(WO.DESIRED_QTY AS INT) AS NVARCHAR) + ') ' + WCA.EXPR1
        WHEN WO.SPLIT_ID <> '0' THEN WO.BASE_ID + '/' + WO.LOT_ID + '.' + WO.SPLIT_ID + ' (' + CAST(CAST(WO.DESIRED_QTY AS INT) AS NVARCHAR) + WCA.EXPR1
        ELSE WO.BASE_ID + ' (' + CAST(CAST(WO.DESIRED_QTY AS INT) AS NVARCHAR) + ') ' + WCA.EXPR1 + ', ' + REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(WCA.REMAINING_OPS,
            'AUB-', ''),'BAL-', ''),'AMP;', ''),'(CONTRACTOR)','(O/S)'), 'PRECISION', ''), 'ASSEMBLY, ASSEMBLY', 'ASSEMBLY'), 'CNCMILL, CNCMILL', 'CNCMILL'), 'CNCMILL-4, CNCMILL-4', 'CNCMILL-4')
            , 'TITANIUM', 'TI'), 'OKUMA, OKUMA', 'OKUMA'), 'HONING, HONING', 'HONING'), 'BRAKEFORM, BRAKEFORM', 'BRAKEFORM')
    END AS PRODUCTIONSTATUS
    , dbo.sfnWONUMFormat(WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID) AS WONUM
    , STUFF((SELECT CHAR(032) + NOTE + '; '
        FROM (SELECT OWNER_ID
            , REPLACE(REPLACE(CONVERT(NVARCHAR, CREATE_DATE, 101) + N': ' + CAST(CAST(NOTE AS VARBINARY(MAX)) AS NVARCHAR(MAX))
                , CHAR(10), ' '), CHAR(13),' ') AS NOTE
            FROM NOTATION
        ) T
        WHERE T.OWNER_ID = dbo.sfnWONUMFormat(WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID)
        FOR XML PATH('')), 1, 1, '') AS WO_NOTATIONS
FROM WORK_ORDER WO
LEFT OUTER JOIN WO_CURRENTLY_AT WCA
    ON WO.[TYPE] = WCA.WORKORDER_TYPE
    AND WO.BASE_ID = WCA.WORKORDER_BASE_ID
    AND WO.LOT_ID = WCA.WORKORDER_LOT_ID
    AND WO.SPLIT_ID = WCA.WORKORDER_SPLIT_ID
    AND WO.PART_ID = WCA.PART_ID
LEFT OUTER JOIN PART_SITE_VIEW P 
    ON WO.PART_ID = P.PART_ID
WHERE WO.SUB_ID = '0' 
    AND WO.[STATUS] IN ('F', 'R' ,'U')
    AND WO.[TYPE] = 'W' 
    AND P.PLANNER_USER_ID IN (@PLANNER)
    AND P.COMMODITY_CODE IN (@COMMCODE)
    AND WO.[STATUS] IN (@WOSTATUS)
    AND WO.DESIRED_RLS_DATE >= ISNULL(@STARTDATE, '1/1/2020')

