SELECT WO.PART_ID
    , P.[DESCRIPTION]
    , P.USER_7
    , P.[STATUS] AS PART_STATUS
    , WO.CREATE_DATE
    , WO.CLOSE_DATE
    , WO.[STATUS] AS WO_STATUS
    , WO.BASE_ID
    , WO.LOT_ID
    , WO.SPLIT_ID
    , WO.SUB_ID
    , O.SEQUENCE_NO
    , O.RESOURCE_ID
    , O.OPERATION_TYPE
    , CAST(CAST(OB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS OP_BINARY
    , CAST(CAST(OTB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS OT_BINARY
FROM DataWarehouse.dbo.WORK_ORDER WO
INNER JOIN DataWarehouse.dbo.OPERATION O
    ON WO.BASE_ID = O.WORKORDER_BASE_ID
    AND WO.LOT_ID = O.WORKORDER_LOT_ID
    AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
    AND WO.SUB_ID = O.WORKORDER_SUB_ID
    AND WO.[TYPE] = O.WORKORDER_TYPE
INNER JOIN DataWarehouse.dbo.PART P
    ON WO.PART_ID = P.ID
    AND P.USER_7 IN (@MODEL)
    AND P.ID LIKE @PARTID
LEFT OUTER JOIN DataWarehouse.dbo.OPERATION_BINARY OB
    ON O.WORKORDER_TYPE = OB.WORKORDER_TYPE
    AND O.WORKORDER_BASE_ID = OB.WORKORDER_BASE_ID
    AND O.WORKORDER_LOT_ID = OB.WORKORDER_LOT_ID
    AND O.WORKORDER_SPLIT_ID = OB.WORKORDER_SPLIT_ID
    AND O.WORKORDER_SUB_ID = OB.WORKORDER_SUB_ID
    AND O.SEQUENCE_NO = OB.SEQUENCE_NO
LEFT OUTER JOIN DataWarehouse.dbo.OPER_TYPE_BINARY OTB
    ON OTB.OPERATION_TYPE_ID = O.OPERATION_TYPE
WHERE WO.[TYPE] = 'W'
    AND WO.CLOSE_DATE >= @CLOSEDATE
    AND (
        CAST(CAST(OB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) LIKE @BINSEARCH -- '%BMS%10-20%'
        OR CAST(CAST(OTB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) LIKE @BINSEARCH -- '%BMS%10-20%'
        )
