USE LIVE
GO

SELECT WO.BASE_ID
, WO.LOT_ID
, WO.SPLIT_ID
, WO.SUB_ID
, WO.PART_ID
, WO.DESIRED_QTY
, WO.CREATE_DATE
, WO.DESIRED_RLS_DATE
, WO.DESIRED_WANT_DATE
, WO.CLOSE_DATE
, WO.[STATUS]
, dbo.sfn_current_operation(wo.[TYPE], wo.BASE_ID, wo.LOT_ID, wo.SPLIT_ID, wo.SUB_ID) AS CURRENT_OPS
FROM WORK_ORDER WO
WHERE WO.PART_ID = '251T1112-7'
AND WO.CREATE_DATE >= '1/1/2019'