select I.TRANSACTION_ID
, I.WORKORDER_BASE_ID
, I.WORKORDER_LOT_ID
, I.WORKORDER_SPLIT_ID
, I.WORKORDER_SUB_ID
, I.CUST_ORDER_ID
, I.CUST_ORDER_LINE_NO
, I.PURC_ORDER_ID
, I.PURC_ORDER_LINE_NO
, I.PART_ID
, I.[TYPE]
, I.CLASS
, I.QTY
, I.TRANSACTION_DATE
, I.WAREHOUSE_ID
, I.LOCATION_ID
, I.[USER_ID]
, I.ACT_LABOR_COST
, I.ACT_BURDEN_COST
, I.CREATE_DATE
, SL.PACKLIST_ID
, S.SHIPPED_DATE
from inventory_trans i
LEFT OUTER JOIN SHIPPER_LINE SL
ON I.TRANSACTION_ID = SL.TRANSACTION_ID
LEFT OUTER JOIN SHIPPER S
ON S.PACKLIST_ID = SL.PACKLIST_ID
where i.part_id = '303T3051-105'
order by transaction_id