USE LIVE
GO

SELECT WO.[TYPE]
, WO.BASE_ID
, WO.LOT_ID
, WO.SPLIT_ID
, WO.SUB_ID
, WO.PART_ID
, P.ID AS PART_ID
, P.[STATUS]
, O.SEQUENCE_NO
, O.RESOURCE_ID
, O.OPERATION_TYPE
FROM WORK_ORDER WO
INNER JOIN OPERATION O
ON WO.[TYPE] = O.WORKORDER_TYPE
AND WO.BASE_ID = O.WORKORDER_BASE_ID
AND WO.LOT_ID = O.WORKORDER_LOT_ID
AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
AND WO.SUB_ID = O.WORKORDER_SUB_ID
LEFT OUTER JOIN PART P
ON P.ID = WO.PART_ID
WHERE WO.[TYPE] = 'M'
AND O.OPERATION_TYPE = '5423 LEVEL 2'