USE DataWarehouse
GO

-- VISUAL ENTERPRISE > CUSTOMER SERVICE REPORTS > BOEING REPORTS > 605-609 MFG weekly summary chart
SELECT DISTINCT COL.CUST_ORDER_ID
	, CO.ORDER_DATE
	, CONVERT(DATE,DATEADD(DD,(DATEDIFF(DD,'17530101',CO.ORDER_DATE)/7)*7,'17530101')) AS [START_OF_WEEK_STARTING_MON_DATE]
	, CONVERT(DATE, DATEADD(DD,((DATEDIFF(DD,'17530101',CO.ORDER_DATE)/7)*7)+6,'17530101')) AS [END_OF_WEEK_STARTING_MON_DATE]
	, DATEPART(YEAR,CO.ORDER_DATE) AS YEAR
	, DATEPART(WEEK,CO.ORDER_DATE) WEEKNUM
	, O.WORKORDER_BASE_ID
	, CO.CUSTOMER_ID
FROM CUST_ORDER_LINE COL
INNER JOIN CUSTOMER_ORDER CO 
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL 
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID 
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
	AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
INNER JOIN OPERATION O
	ON WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID 
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID 
	AND WO.SUB_ID = O.WORKORDER_SUB_ID 
INNER JOIN SHOP_RESOURCE SR 
	ON O.RESOURCE_ID = SR.ID
	AND SR.ID NOT IN (
		SELECT RESOURCE_ID
		FROM LIVESupplemental..ResourceID_ReportSettings S
		WHERE S.REPORT_NAME = '605-609 MFG weekly summary chart'
			AND S.REPORT_SECTION = 'Main Report'
		)
WHERE SR.USER_1 IN ('D', 'M') 
	AND co.SHIP_TO_ADDR_NO = 1 
	AND CO.CUSTOMER_ID IN ('BOE609', 'BOEMFG', 'BOE605')
	AND CO.ORDER_DATE >= GETDATE() - 177
	AND CO.ORDER_DATE <= GETDATE() - 1
