USE LIVE
GO

; WITH CTE_PARTS AS
(SELECT ID AS PART_ID
, [STATUS]
, USER_7 AS MODEL
FROM PART WHERE USER_7 = '747'
)

SELECT PS.PARTID
, P.[STATUS] AS PART_STATUS
, P.USER_7 AS MODEL
, WAREHOUSE_ID
, LOCATION_ID
, PL.[STATUS] AS LOCATION_STATUS
, QTY
FROM PART_LOCATION PL
INNER JOIN LIVESUPPLEMENTAL.[dbo].[747_Parts] PS
ON PS.PARTID = PL.PART_ID
INNER JOIN PART P
ON P.ID = PL.PART_ID
--INNER JOIN CTE_PARTS CTE
--ON CTE.PART_ID = PL.PART_ID
WHERE QTY != 0