USE LIVE
GO

SELECT AB.ACCOUNT_ID
, A.[DESCRIPTION]
, A.[TYPE]
, A.PARENT_ACCT_ID
, AB.ACCT_YEAR
, AB.ACCT_PERIOD
, AB.DEBIT_AMOUNT
, AB.CREDIT_AMOUNT
, AB.CURR_BALANCE
FROM ACCOUNT A
LEFT OUTER JOIN ACCOUNT_BALANCE AB
ON A.ID = AB.ACCOUNT_ID
WHERE AB.ACCT_YEAR = 2019

SELECT AB.ACCOUNT_ID
, A.[DESCRIPTION]
, A.[TYPE]
, A.PARENT_ACCT_ID
, AB.ACCT_YEAR
, AB.ACCT_PERIOD
, AB.DEBIT_AMOUNT
, AB.CREDIT_AMOUNT
, AB.CURR_BALANCE
FROM ACCOUNT A
LEFT OUTER JOIN ACCOUNT_BALANCE AB
ON A.ID = AB.ACCOUNT_ID
WHERE AB.ACCT_YEAR = 2018
AND ACCOUNT_ID = '88'

SELECT * FROM GJ 
LEFT OUTER JOIN GJ_LINE GJL
ON GJL.GJ_ID = GJ.ID
WHERE GJ_DATE >= '12/1/2018' ORDER BY GJ_DATE