SELECT PO.ID AS PO_ID
	, P.VOUCHER_ID
	, R.RECEIVED_DATE
	, PO.VENDOR_ID
	, POL.LINE_NO AS 'PO_LINE_NO'
	, POL.ORDER_QTY
	, RL.RECEIVED_QTY
	, POL.TOTAL_AMT_ORDERED AS 'PO_AMOUNT'
	, POL.TOTAL_AMT_RECVD AS 'RECEIVED_AMOUNT'
	, PL.AMOUNT AS 'INVOICE_AMOUNT'
	, P.INVOICE_ID 
	, R.ID AS 'RECEIVER_ID'
	, RL.LINE_NO
	, PO.BUYER
	, IIF(POL.ORDER_QTY = RL.RECEIVED_QTY, 'NO','YES') AS [QTY ISSUE]
	, CASE
		WHEN (POL.TOTAL_AMT_ORDERED = PL.AMOUNT) THEN 'NO'
		ELSE 'YES'
	END AS [PRICE ISSUE]
FROM PAYABLE P
LEFT OUTER JOIN PAYABLE_LINE PL
	ON PL.VOUCHER_ID = P.VOUCHER_ID
LEFT OUTER JOIN PURC_ORDER_LINE POL
	ON POL.PURC_ORDER_ID = PL.PURC_ORDER_ID
	AND POL.LINE_NO = PL.PURC_ORDER_LINE_NO
LEFT OUTER JOIN RECEIVER_LINE RL
	ON RL.PURC_ORDER_ID = POL.PURC_ORDER_ID
	AND RL.PURC_ORDER_LINE_NO = POL.LINE_NO
LEFT OUTER JOIN PURCHASE_ORDER PO
	ON PO.ID = POL.PURC_ORDER_ID
LEFT OUTER JOIN RECEIVER R
	ON R.ID = RL.RECEIVER_ID
WHERE P.PAY_STATUS = 'L'
	AND PO.CREATE_DATE >= '1/1/2020'