DECLARE @STARTDATE DATE = '5/26/2021'
, @ENDDATE DATE = '8/1/2021'
, @LIST NVARCHAR(50) = 'ACTION ITEMS'
--, @LIST NVARCHAR(50) = 'ALL'

/**********************************************************************************************
Description:	Approved Supplier List
Date        Modified By         Change Description
----------  ------------------  ------------------------------------------------------------
8/28/2020						Existing - Part I
8/28/2020	William Thompson	Added part2 to ASL
9/14/2020	William Thompson	Created ASL - Action Items report based on ASL
9/16/2020	William Thompson	Added year filter on 11 expiration columns
20210526	tt	                Cleaned up the garbage; merged 2 reports into a single
**********************************************************************************************/

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DEADLOCK_PRIORITY LOW

IF OBJECT_ID('tempdb..#USER_DEF_FIELDS') IS NOT NULL DROP TABLE #USER_DEF_FIELDS
IF OBJECT_ID('tempdb..#VND_CERTS_DATA_FLAT') IS NOT NULL DROP TABLE #VND_CERTS_DATA_FLAT

SELECT *
INTO #USER_DEF_FIELDS
FROM USER_DEF_FIELDS (NOLOCK)
WHERE PROGRAM_ID IN (N'VMVNDMNT')
AND DOCUMENT_ID IS NOT NULL
AND ID IN ('UDF-0000093', 'UDF-0000094', 'UDF-0000095', 'UDF-0000096', 'UDF-0000097', 'UDF-0000098');

SELECT * 
INTO #VND_CERTS_DATA_FLAT
FROM (SELECT KV1.DOCUMENT_ID
	, KV1.STRING_VAL
	, KV2.DATE_VAL
FROM #USER_DEF_FIELDS KV1
JOIN #USER_DEF_FIELDS KV2
	ON KV1.PROGRAM_ID = KV2.PROGRAM_ID
	AND KV1.DOCUMENT_ID = KV2.DOCUMENT_ID
	AND KV1.ID = 'UDF-0000093'
	AND KV2.ID = 'UDF-0000094'
UNION ALL
SELECT KV1.DOCUMENT_ID
	, KV1.STRING_VAL 
	, KV2.DATE_VAL 
FROM #USER_DEF_FIELDS KV1
JOIN #USER_DEF_FIELDS KV2
	ON KV1.PROGRAM_ID = KV2.PROGRAM_ID
	AND KV1.DOCUMENT_ID = KV2.DOCUMENT_ID
	AND KV1.ID = 'UDF-0000095'
	AND KV2.ID = 'UDF-0000096'
UNION ALL
SELECT KV1.DOCUMENT_ID
	, KV1.STRING_VAL
	, KV2.DATE_VAL
FROM #USER_DEF_FIELDS KV1
JOIN #USER_DEF_FIELDS KV2
	ON KV1.PROGRAM_ID = KV2.PROGRAM_ID
	AND KV1.DOCUMENT_ID = KV2.DOCUMENT_ID
	AND KV1.ID = 'UDF-0000097'
	AND KV2.ID = 'UDF-0000098'
) VENDORS
PIVOT(MAX(DATE_VAL)
	FOR STRING_VAL IN ([COMP EXP], [CP EXP], [HT EXP], [MTL EXP], [NDT EXP], [SE EXP], [SLT EXP], [WLD EXP])
) PVT

SELECT V.ID AS VENDOR_ID
	, V.NAME AS VENDOR_NAME
	, V.OPEN_DATE AS ACCOUNT_OPENED
	, V.LAST_ORDER_DATE AS LAST_PO_DATE
	, V.USER_1 AS CONTROLLED_PRODUCT
	, V.USER_2 AS APPROVAL_STATUS
	, CAST(V.USER_3 AS DATE) AS APPROVAL_EXPIRATION_ON
	, ISDATE(V.USER_3) AS USER_3_IS_DATE
	, CAST(V.USER_4 AS DATE) AS ITAR_EXPIRATION_ON
	, CAST(V.USER_5 AS DATE) AS DPD_EXPIRATION_ON
	, V.USER_6 AS SUPPLIER_TYPE
	, V.USER_7 AS PRODUCT_TYPE
	, V.USER_8 AS LIMITATIONS
	, CAST(CAST(VB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS SPECIFICATIONS
	, UDF.STRING_VAL AS QCNOTES
	, V.CONTACT_FIRST_NAME + ' ' + V.CONTACT_LAST_NAME  AS CONTACT_NAME
	, V.CONTACT_EMAIL AS EMAIL
	, V.CONTACT_PHONE AS DESK_PHONE
	, V.CONTACT_MOBILE AS CELL
	, V.ADDR_1 AS ADDRESS1
	, V.ADDR_2 AS ADDRESS2
	, V.CITY AS CITY
	, V.STATE AS STATE
	, V.ZIPCODE AS ZIP
	, V.BUYER
	, V.CONTACT_FIRST_NAME
	, V.CONTACT_LAST_NAME
	, V.ACTIVE_FLAG
	, APPROVAL_EXPIRATION_ONX = CASE ISDATE(V.USER_3) WHEN 1 THEN YEAR(V.USER_3) ELSE CONVERT(INT,NULL) END
	, APPROVAL_EXPIRATION_ONZ = CASE ISDATE(V.USER_3) WHEN 1 THEN 1 ELSE 0 END
	, ITAR_EXPIRATION_ONX = CASE ISDATE(V.USER_4) WHEN 1 THEN YEAR(V.USER_4) ELSE CONVERT(INT,NULL) END
	, ITAR_EXPIRATION_ONZ = CASE ISDATE(V.USER_4) WHEN 1 THEN 1 ELSE 0 END
	, DPD_EXPIRATION_ONX = CASE ISDATE(V.USER_5) WHEN 1 THEN YEAR(V.USER_5) ELSE CONVERT(INT,NULL) END
	, DPD_EXPIRATION_ONZ = CASE ISDATE(V.USER_5) WHEN 1 THEN 1 ELSE 0 END
	, T.[COMP EXP] 
	, [COMP EXPX] = CASE ISDATE(T.[COMP EXP]) WHEN 1 THEN YEAR(T.[COMP EXP]) ELSE CONVERT(INT,NULL) END
	, T.[CP EXP]
	, [CP EXPX] = CASE ISDATE(T.[CP EXP]) WHEN 1 THEN YEAR(T.[CP EXP]) ELSE CONVERT(INT,NULL) END
	, T.[HT EXP]
	, [HT EXPX] = CASE ISDATE(T.[HT EXP]) WHEN 1 THEN YEAR(T.[HT EXP]) ELSE CONVERT(INT,NULL) END
	, T.[MTL EXP]
	, [MTL EXPX] = CASE ISDATE(T.[MTL EXP]) WHEN 1 THEN YEAR(T.[MTL EXP]) ELSE CONVERT(INT,NULL) END
	, T.[NDT EXP]
	, [NDT EXPX] = CASE ISDATE(T.[NDT EXP]) WHEN 1 THEN YEAR(T.[NDT EXP]) ELSE CONVERT(INT,NULL) END
	, T.[SE EXP]
	, [SE EXPX] = CASE ISDATE(T.[SE EXP]) WHEN 1 THEN YEAR(T.[SE EXP]) ELSE CONVERT(INT,NULL) END
	, T.[SLT EXP]
	, [SLT EXPX] = CASE ISDATE(T.[SLT EXP]) WHEN 1 THEN YEAR(T.[SLT EXP]) ELSE CONVERT(INT,NULL) END
	, T.[WLD EXP]
	, [WLD EXPX] = CASE ISDATE(T.[WLD EXP]) WHEN 1 THEN YEAR(T.[WLD EXP]) ELSE CONVERT(INT,NULL) END
FROM VENDOR V
LEFT OUTER JOIN VENDOR_BINARY VB
  ON V.ID = VB.VENDOR_ID
LEFT JOIN #VND_CERTS_DATA_FLAT T
	ON V.ID = T.DOCUMENT_ID
LEFT OUTER JOIN USER_DEF_FIELDS UDF
	ON UDF.PROGRAM_ID IN (N'VMVNDMNT')
	AND UDF.DOCUMENT_ID = V.ID
	AND UDF.ID IN ('UDF-0000102')
WHERE V.ACTIVE_FLAG = 'Y'
	AND V.USER_1 = 'Y'
	AND (@LIST != 'ALL' AND (
			(CAST(V.USER_3 AS DATE) >= @STARTDATE AND CAST(V.USER_3 AS DATE) <= @ENDDATE)
			OR (ISNULL(V.USER_4, CAST('12/31/2050' AS DATE)) >= @STARTDATE AND ISNULL(V.USER_4, CAST('12/31/2050' AS DATE)) <= @ENDDATE)
			OR (ISNULL(V.USER_5, CAST('12/31/2050' AS DATE)) >= @STARTDATE AND ISNULL(V.USER_5, CAST('12/31/2050' AS DATE)) <= @ENDDATE)
			OR (ISNULL([COMP EXP], CAST('12/31/2050' AS DATE)) >= @STARTDATE AND ISNULL([COMP EXP], CAST('12/31/2050' AS DATE)) <= @ENDDATE)
			OR (ISNULL([CP EXP], CAST('12/31/2050' AS DATE)) >= @STARTDATE AND ISNULL([CP EXP], CAST('12/31/2050' AS DATE)) <= @ENDDATE)
			OR (ISNULL([HT EXP], CAST('12/31/2050' AS DATE)) >= @STARTDATE AND ISNULL([HT EXP], CAST('12/31/2050' AS DATE)) <= @ENDDATE)
			OR (ISNULL([MTL EXP], CAST('12/31/2050' AS DATE)) >= @STARTDATE AND ISNULL([MTL EXP], CAST('12/31/2050' AS DATE)) <= @ENDDATE)
			OR (ISNULL([NDT EXP], CAST('12/31/2050' AS DATE)) >= @STARTDATE AND ISNULL([NDT EXP], CAST('12/31/2050' AS DATE)) <= @ENDDATE)
			OR (ISNULL([SE EXP], CAST('12/31/2050' AS DATE)) >= @STARTDATE AND ISNULL([SE EXP], CAST('12/31/2050' AS DATE)) <= @ENDDATE)
			OR (ISNULL([SLT EXP], CAST('12/31/2050' AS DATE)) >= @STARTDATE AND ISNULL([SLT EXP], CAST('12/31/2050' AS DATE)) <= @ENDDATE)
			OR (ISNULL([WLD EXP], CAST('12/31/2050' AS DATE)) >= @STARTDATE AND ISNULL([WLD EXP], CAST('12/31/2050' AS DATE)) <= @ENDDATE)
		)
		OR @LIST = 'ALL'
	)
	


