USE LIVE
GO

WITH CTE_CO AS 
(SELECT CO.CUSTOMER_ID
, IT.CUST_ORDER_ID
, IT.CUST_ORDER_LINE_NO
, IT.PART_ID
, SUM(ITD.DIST_QTY) AS QTY
-- ISSUED TO JOB
FROM INVENTORY_TRANS IT
LEFT OUTER JOIN INV_TRANS_DIST ITD
ON IT.TRANSACTION_ID = ITD.OUT_TRANS_ID
-- PUT INTO INVENTORY
LEFT OUTER JOIN INVENTORY_TRANS IT2
ON ITD.IN_TRANS_ID = IT2.TRANSACTION_ID
LEFT OUTER JOIN CUSTOMER_ORDER CO
ON CO.ID = IT.CUST_ORDER_ID
WHERE IT2.TRANSACTION_DATE < '1/1/2020'
AND IT.TRANSACTION_DATE >= '1/1/2020'
AND IT.TRANSACTION_DATE < '2/1/2020'
AND IT.CUST_ORDER_ID IS NOT NULL
GROUP BY CO.CUSTOMER_ID
, IT.CUST_ORDER_ID
, IT.CUST_ORDER_LINE_NO
, IT.PART_ID
)

, CTE_INV_QTY AS
(SELECT PART_ID
	, SUM(CASE
		WHEN TYPE = 'I' AND CLASS = 'R' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'I' THEN -1
		WHEN TYPE = 'O' AND CLASS = 'A' THEN -1
		WHEN TYPE = 'I' AND CLASS = 'A' THEN 1
		WHEN TYPE = 'I' AND CLASS = 'I' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'R' THEN -1
		ELSE 0
	END * QTY) AS INV_QTY
FROM INVENTORY_TRANS
WHERE TRANSACTION_DATE <= '1/1/2020'
GROUP BY PART_ID
HAVING SUM(CASE
		WHEN TYPE = 'I' AND CLASS = 'R' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'I' THEN -1
		WHEN TYPE = 'O' AND CLASS = 'A' THEN -1
		WHEN TYPE = 'I' AND CLASS = 'A' THEN 1
		WHEN TYPE = 'I' AND CLASS = 'I' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'R' THEN -1
		ELSE 0
	END * QTY) > 0
)

SELECT RL.INVOICE_ID
, RL.LINE_NO
, CTE.CUSTOMER_ID
, CTE.PART_ID
, RL.AMOUNT
, RL.QTY AS ISSUED_QTY
, INV.INV_QTY AS B4_INV_QTY
FROM CTE_CO CTE
LEFT OUTER JOIN RECEIVABLE_LINE RL
ON RL.CUST_ORDER_ID = CTE.CUST_ORDER_ID
AND RL.CUST_ORDER_LINE_NO = CTE.CUST_ORDER_LINE_NO
LEFT OUTER JOIN CTE_INV_QTY INV
ON INV.PART_ID = CTE.PART_ID
WHERE RL.INVOICE_ID NOT LIKE '%DM'
AND RL.INVOICE_ID NOT LIKE '%CM'

