USE DataWarehouse
GO

/*
Is there a report to pull the average number of wait days per area over the last month?  
I am trying to get a baseline for a project and pulling today’s numbers isn’t going to give me a good snapshot.  
*/

; WITH CTE_OPS AS
(SELECT O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.WORKORDER_TYPE
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, LAG(CLOSE_DATE, 1, CLOSE_DATE) OVER (PARTITION BY O.WORKORDER_TYPE, O.WORKORDER_BASE_ID, O.WORKORDER_LOT_ID, O.WORKORDER_SPLIT_ID, O.WORKORDER_SUB_ID
		ORDER BY O.WORKORDER_TYPE, O.WORKORDER_BASE_ID, O.WORKORDER_LOT_ID, O.WORKORDER_SPLIT_ID, O.WORKORDER_SUB_ID, O.SEQUENCE_NO
	) AS PRIOR_CLOSE
	, LT.FIRST_CLOCK
	, O.CLOSE_DATE
	, SR.USER_5 AS FACILITY
	, SR.USER_6 AS PROCESS
	, SR.USER_7 AS SUBPROCESS
	, SR.USER_8 AS REPT_DEPT
FROM OPERATION O
LEFT OUTER JOIN SHOP_RESOURCE SR
ON O.RESOURCE_ID = SR.ID
LEFT OUTER JOIN (SELECT LT.WORKORDER_BASE_ID
		, LT.WORKORDER_LOT_ID
		, LT.WORKORDER_SPLIT_ID
		, LT.WORKORDER_SUB_ID
		, LT.WORKORDER_TYPE
		, LT.OPERATION_SEQ_NO
		, LT.RESOURCE_ID
		, MIN(LT.CLOCK_IN) AS FIRST_CLOCK
	FROM LABOR_TICKET LT
	WHERE TRANSACTION_DATE >= '8/1/2021'
	GROUP BY LT.WORKORDER_BASE_ID
		, LT.WORKORDER_LOT_ID
		, LT.WORKORDER_SPLIT_ID
		, LT.WORKORDER_SUB_ID
		, LT.WORKORDER_TYPE
		, LT.OPERATION_SEQ_NO
		, LT.RESOURCE_ID
	) LT 
	ON LT.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
	AND LT.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
	AND LT.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND LT.WORKORDER_SUB_ID = O.WORKORDER_SUB_ID
	AND LT.WORKORDER_TYPE = O.WORKORDER_TYPE
	AND LT.OPERATION_SEQ_NO = O.SEQUENCE_NO
	AND LT.RESOURCE_ID = O.RESOURCE_ID
WHERE O.CLOSE_DATE >= '8/1/2021'
AND O.WORKORDER_TYPE = 'W'
AND O.[STATUS] = 'C'
--AND O.WORKORDER_BASE_ID = '1597969'
)

, CTE_DELTA AS
(SELECT *
	, DATEDIFF(HH, PRIOR_CLOSE, CLOSE_DATE) AS CLOSE_HOURS_DELTA
	, DATEDIFF(HH, PRIOR_CLOSE, FIRST_CLOCK) AS [1ST_CLOCK_DELTA]
FROM CTE_OPS
)
--SELECT * FROM CTE_DELTA

SELECT FACILITY
	, PROCESS
	, SUBPROCESS
	, REPT_DEPT
	, AVG(CLOSE_HOURS_DELTA) AS AVG_CLOSE_HOURS
	, AVG([1ST_CLOCK_DELTA]) AS AVG_1ST_CLOCK_HOURS
FROM CTE_DELTA
GROUP BY FACILITY
	, PROCESS
	, SUBPROCESS
	, REPT_DEPT
ORDER BY FACILITY
	, PROCESS
	, SUBPROCESS
	, REPT_DEPT