USE LIVE
GO

--SELECT * FROM TRACE WHERE PART_ID LIKE 'BACS20N1C%'
--SELECT * FROM TRACE_PROFILE WHERE PART_ID LIKE 'BACS20N1C%'

SELECT * FROM REQUIREMENT 
WHERE WORKORDER_TYPE = 'W'
AND PART_ID LIKE 'BACS20N1C%'

SELECT 
'FROM INVENTORY_TRANS IT' AS MSG01
, IT.*
, 'INNER JOIN REQUIREMENT R' AS MSG02
, R.*
, 'LEFT OUTER JOIN TRACE_INV_TRANS TI' AS MSG03
, TI.*

FROM INVENTORY_TRANS IT
INNER JOIN REQUIREMENT R
ON IT.WORKORDER_TYPE = R.WORKORDER_TYPE
AND IT.WORKORDER_BASE_ID = R.WORKORDER_BASE_ID
AND IT.WORKORDER_LOT_ID = R.WORKORDER_LOT_ID
AND IT.WORKORDER_SPLIT_ID = R.WORKORDER_SPLIT_ID
AND IT.WORKORDER_SUB_ID = R.WORKORDER_SUB_ID
AND R.PART_ID = 'BACS20N1C'
LEFT OUTER JOIN TRACE_INV_TRANS TI
ON IT.TRANSACTION_ID = TI.TRANSACTION_ID
ORDER BY IT.WORKORDER_BASE_ID
, IT.TRANSACTION_ID
