USE DataWarehouse
GO
;

SET DATEFIRST 1;

--> VISUAL HOURS
SELECT LT.[EMPLOYEE_ID]
	, RIGHT('0000' + [EMPLOYEE_ID], 6) AS [File Number]
	, YEAR(SHIFT_DATE) AS [YEAR]
	, DATEPART(WW, DATEADD(WEEK, DATEDIFF(WEEK, 0, SHIFT_DATE), -1)) AS [WEEK]
	, DATEADD(DAY, 8 - DATEPART(WEEKDAY, SHIFT_DATE), CAST(SHIFT_DATE AS DATE)) [WEEKEND]
	, SHIFT_DATE
	, SUM(CASE
		WHEN [TYPE] = 'I' THEN HOURS_WORKED
		ELSE 0
	END) AS [VIS_INDIRECT]
	, SUM(CASE
		WHEN [TYPE] = 'R' THEN HOURS_WORKED
		ELSE 0
	END) AS [VIS_DIRECT]
	, SUM(HOURS_WORKED) AS [VIS_TOTAL_HOURS]
FROM DataWarehouse.dbo.LABOR_TICKET LT
WHERE TRANSACTION_DATE >= '1/1/2019'
GROUP BY EMPLOYEE_ID
	, SHIFT_DATE

--> ADP HOURS FROM DAILY IMPORT
SELECT [File Number]
	, YEAR([Pay Date]) AS [YEAR]
	, DATEPART(WW, DATEADD(WEEK, DATEDIFF(WEEK, 0, [Pay Date]), -1)) AS [WEEK]
	, DATEADD(DAY, 8 - DATEPART(WEEKDAY, [Pay Date]), CAST([Pay Date] AS DATE)) [WEEKEND]
	, [Pay Date]
	, SUM(CASE
		WHEN [Earnings Code] = '' THEN [Hours]
		ELSE 0
	END) AS [ADP_WORK_TIME]
	, SUM(CASE
		WHEN [Earnings Code] = 'SICK' THEN [Hours]
		ELSE 0
	END) AS [ADP_SICK_TIME]
	, SUM(CASE
		WHEN [Earnings Code] = 'VACATION' THEN [Hours]
		ELSE 0
	END) AS [ADP_VAC_TIME]
	, SUM(CASE
		WHEN [Earnings Code] = 'HOLIDAY' THEN [Hours]
		ELSE 0
	END) AS [ADP_HOL_TIME]
	, SUM(CASE
		WHEN [Earnings Code] = 'JURY' THEN [Hours]
		ELSE 0
	END) AS [ADP_JURY_TIME]
	, SUM(CASE
		WHEN [Earnings Code] = 'BEREAV' THEN [Hours]
		ELSE 0
	END) AS [ADP_BEREAV_TIME]
	, SUM(CASE
		WHEN [Earnings Code] = 'WORKERSCOMP' THEN [Hours]
		ELSE 0
	END) AS [ADP_WC_TIME]
	, SUM([Hours]) AS [ADP_TOTAL_HOURS]
FROM DataWarehouse.SimpleWarehouse.ADP_LABOR 
GROUP BY [File Number]
	, [Pay Date]

SELECT * FROM [SQL-LAB-2].LIVESupplemental.dbo.ADP_EMP WHERE [FILE NUMBER] = '002694'
SELECT * FROM [SQL-LAB-2].LIVESupplemental.dbo.ADP_LABOR WHERE [FILE NUMBER] = '002694' AND [PAY DATE] >= '7/20/2019' AND [PAY DATE] <= '8/5/2019'
SELECT * FROM DataWarehouse.dbo.LABOR_TICKET WHERE EMPLOYEE_ID = '2694' AND [SHIFT_DATE] >= '7/25/2019' AND [SHIFT_DATE] <= '8/5/2019' ORDER BY [SHIFT_DATE]