USE DataWarehouse
GO

SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DEADLOCK_PRIORITY LOW

DECLARE @CHARGE FLOAT
DECLARE @STARTDATE DATE, @ENDDATE DATE
SET @STARTDATE = '1/1/2020' 
SET @ENDDATE = '1/9/2020'
SET @CHARGE = (SELECT CHARGE FROM [SQL-BI-1].LIVESupplemental.dbo.[BOE_Billing_Charges] WHERE [REPORT] = 'usp_BOE_BILLING_FINISH')
;

WITH CTE_INCLUDE AS
--> PULLS BORIC AND ETCH OPERATIONS FOR SPECIAL HANDLING, ONLY FOR PART FAMILY 437W8500%
(SELECT * 
FROM [SQL-BI-1].LIVESupplemental.dbo.ResourceID_ReportSettings EX
WHERE REPORT_NAME = 'usp_BOE_BILLING_FINISH'
AND [INCLUDE] = 1
)
--SELECT * FROM CTE_INCLUDE  

--SELECT 'FINISH' AS SPROC 
--	, 0 AS [COST ITEM]
--	, '1' AS [POS]
--	, PART_ID AS [PART NUMBER]
--	, ID AS [RAMAC]
--	, TOTAL_SHIPPED_QTY AS [BILLED QTY]
--	, CASE
--		WHEN [Finish_Unit Run Hours] IS NOT NULL THEN [Finish_Unit Run Hours] * @CHARGE
--		ELSE (((SUM(SORT_SETUP) + SUM(SORT_RUN)) * @CHARGE) / TOTAL_SHIPPED_QTY) 
--	END AS [UNIT PRICE]
--	, CASE
--		WHEN [Finish_Unit Run Hours] IS NOT NULL THEN [Finish_Unit Run Hours] * TOTAL_SHIPPED_QTY * @CHARGE
--		ELSE (SUM(SORT_SETUP) + SUM(SORT_RUN)) * @CHARGE
--	END AS [EXTENDED DOLLARS]
--	, 0 AS [EXPEDITE DOLLARS]
--	, CASE
--		WHEN TOTAL_SHIPPED_QTY < [Batch Qty] THEN 175
--		ELSE 0
--	END AS [SPECIAL FEES]
--	, CASE 
--		WHEN [Finish_Unit Run Hours] IS NOT NULL THEN 0
--		ELSE SUM(SORT_SETUP)
--	END AS [SETUP HOURS]
--	, CASE 
--		WHEN [Finish_Unit Run Hours] IS NOT NULL THEN [Finish_Unit Run Hours] * TOTAL_SHIPPED_QTY
--		ELSE SUM(SORT_RUN) 
--	END AS [RUN HOURS]
--	, 0 AS [EXPEDITE HOURS]
--	, PACKLIST_ID + ',' + STUFF(REPLACE('/' + CONVERT(NVARCHAR(15), INVOICED_DATE, 101), '/0', '/'), 1, 1, '') + ',FIN,WRAP' AS [PACK SLIPS / DATE]  
--	, COMMENTS
----	, INVOICE_ID AS [INVOICE ID]
--	, CASE
--		WHEN TOTAL_SHIPPED_QTY < [Batch Qty] THEN 1
--		ELSE 9 
--	END AS SORTATION

--FROM 
--	(
	SELECT CO.ID
		, LT.WORKORDER_BASE_ID
		, LT.HOURS_WORKED
		, COL.PART_ID
		, COL.TOTAL_SHIPPED_QTY
		, LT.[TYPE]
		, LT.TRANSACTION_ID
		, CO.CUSTOMER_ID
		, SR.USER_1
		, SL.SHIPPED_QTY
		, S.INVOICE_ID
		, S.INVOICED_DATE
		, S.PACKLIST_ID
		, SR.RESOURCE_ID
		
		, LT.[TYPE] 
		, LT.HOURS_WORKED
		
		, CASE
			WHEN LT.[TYPE] = 'S' THEN LT.HOURS_WORKED
			ELSE 0
		END AS SORT_SETUP

		, CB.[FINISH_UNIT RUN HOURS]
		, CTE.REASONING 

		, COALESCE(CB.[FINISH_UNIT RUN HOURS], CTE.REASONING, 
			CASE
				WHEN LT.[TYPE] = 'R' THEN LT.HOURS_WORKED
				ELSE 0
			END
			, 0) AS SORT_RUN
		, CASE
			WHEN CB.[PART NUMBER] IS NULL THEN ''
--			WHEN CB.[Batch Qty] > COL.TOTAL_SHIPPED_QTY THEN CAST(TOTAL_SHIPPED_QTY AS NVARCHAR) + ', FIXED HOURS, MIN LOT'
			ELSE 'FIXED HOURS' 
		END AS [COMMENTS]
		, CB.[Finish_Unit Run Hours]
		, CB.[Batch Qty]
	FROM DataWarehouse.dbo.SHIPPER S
	INNER JOIN DataWarehouse.dbo.SHIPPER_LINE SL
		ON S.PACKLIST_ID = SL.PACKLIST_ID
	INNER JOIN DataWarehouse.dbo.CUST_ORDER_LINE COL
		ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
		AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	INNER JOIN DataWarehouse.dbo.CUSTOMER_ORDER CO
		ON COL.CUST_ORDER_ID = CO.ID
	INNER JOIN DataWarehouse.dbo.DEMAND_SUPPLY_LINK DSL
		ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
		AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
	INNER JOIN DataWarehouse.dbo.LABOR_TICKET LT
		ON DSL.SUPPLY_BASE_ID = LT.WORKORDER_BASE_ID
		AND DSL.SUPPLY_LOT_ID = LT.WORKORDER_LOT_ID
	INNER JOIN DataWarehouse.dbo.SHOP_RESOURCE_SITE SR
		ON LT.RESOURCE_ID = SR.RESOURCE_ID
	LEFT OUTER JOIN CTE_INCLUDE CTE
		ON CTE.RESOURCE_ID = SR.RESOURCE_ID
		AND COL.PART_ID LIKE '437W8500%'
	LEFT OUTER JOIN [SQL-BI-1].LIVESupplemental.dbo.[BOE_Stanchion_Cargo_Bay] CB
		ON CB.[PART NUMBER] = COL.PART_ID
	WHERE SL.SHIPPED_QTY > 0
		AND SR.USER_1 <> N'M'
		AND CO.CUSTOMER_ID = N'BOE609'
		AND NOT EXISTS (SELECT 1 FROM [SQL-BI-1].LIVESupplemental.dbo.ResourceID_ReportSettings EX
			WHERE LT.RESOURCE_ID = EX.RESOURCE_ID
				AND REPORT_NAME = 'usp_BOE_BILLING_FINISH'
				AND REPORT_SECTION = 'MAIN EXCLUSION'
				)
--> REMOVE REWORKS EXCEPT FOR PARTID 411N2001-1
		AND CASE
			WHEN COL.PART_ID = '411N2001-1' THEN 'OK'
			WHEN LT.WORKORDER_BASE_ID LIKE '%R%' THEN 'NOT OK'
			ELSE 'OK'
		END = 'OK'
		AND (S.INVOICED_DATE >= @STARTDATE AND S.INVOICED_DATE <= @ENDDATE)

--		AND CO.ID = @COID
		


/*
SELECT * FROM SHIPPER_LINE WHERE CUST_ORDER_ID = '001688994'
SELECT * FROM RECEIVABLE_LINE WHERE CUST_ORDER_ID = '001688994'
SELECT * FROM RECEIVABLE WHERE INVOICE_ID = '1265319'

SELECT * FROM [SQL-BI-1].LIVESupplemental.dbo.[BOE_Stanchion_Cargo_Bay] CB
SELECT * FROM [SQL-BI-1].LIVESupplemental.dbo.ResourceID_ReportSettings EX WHERE REPORT_NAME = 'usp_BOE_BILLING_FINISH'
--> ADD P1F2-ANO-BORIC; P1F2-CH-ETCH


SELECT CASE
WHEN SR.ID IN ('ANM-FINALinsp', 'ARL-cert', 'AUB-cert', 'AUB-FINALinsp', 'AUB-panel', 'BAL-cert', 'BAL-FINALinsp', 'BAL-panel', 'P1F1-IN-CERT', 'P1F1-IN-FNL', 'P1F1-REC-PANELS', 'P1F2-IN-FNL-CMP', 'P1M1-CP-FINAL', 'P2M1-IN-FNL', 'P2M1-PANEL', 'P3M1-IN-FNL', 'P3M1-IN-FNL-CMP', 'panel', 'SouthAUB-cert', 'SouthAUB-Final')
	THEN 'HIT'
ELSE ''
END AS EXCLUDED
, ID
, [DESCRIPTION]
, [STATUS]
, USER_1
, USER_2
, USER_3
, USER_4
, USER_5
, USER_6
, USER_7
, USER_8
FROM SHOP_RESOURCE SR 
WHERE [STATUS] IS NULL OR [STATUS] != 'O'
*/