use DataWarehouse
go

DECLARE @STARTDATE DATE = '8/23/2019',
	@ENDDATE DATE = '8/31/2019'

--BOE001                 G:\ACCTG\AR\2019\Crystal Reports\BOE605revF – (Hours + Setup Hrs) * 75
WITH BOE001 AS 
(SELECT 0 AS COST_ITEM
	, CASE 
		WHEN BASE_ID LIKE '%R%' THEN 'RWK'
		ELSE '1'
	END AS POS
	, CUST_ORDER_ID
	, BASE_ID
	, PART_NUMBER
	, BILLED_QTY
	, SHIPPED_QTY
	, INVOICE_ID
	, INVOICED_DATE
	, PACK_SLIPS
	, CUSTOMER_PO_REF
	, CASE
		WHEN CUSTOMER_PO_REF LIKE '%SB%' THEN 250
		ELSE 0
	END AS EXPEDITE_DOLLARS	
	, SUM(EXTENDED_DOLLARS)/BILLED_QTY AS UNIT_PRICE
	, SUM(SPECIAL_FEES) AS SPECIAL_FEES
	, SUM(SORT_SETUP) AS SORT_SETUP
	, SUM(SORT_RUN) AS SORT_RUN
	, 0 AS EXPEDITE_HOURS
	, CASE 
		WHEN BASE_ID LIKE '%R%' THEN 0
		WHEN SUM(EXTENDED_DOLLARS) <= 250 THEN 250
		ELSE SUM(EXTENDED_DOLLARS)
	END AS EXTENDED_DOLLARS
	, CASE
		WHEN SUM(EXTENDED_DOLLARS) <= 250 THEN CONVERT(NVARCHAR(MAX), INVOICED_DATE, 101) + ', MIN LOT'
		ELSE CONVERT(NVARCHAR(MAX), INVOICED_DATE, 101) + ', WRAP'
	END AS COMMENTS
FROM
(SELECT CO.ID AS CUST_ORDER_ID
	, WO.BASE_ID
	, LT.HOURS_WORKED
	, COL.PART_ID AS PART_NUMBER
	, COL.TOTAL_SHIPPED_QTY AS BILLED_QTY
	, LT.[TYPE]
	, LT.TRANSACTION_ID
	, CO.CUSTOMER_ID
	, LT.TRANSACTION_DATE
	, SL.SHIPPED_QTY
	, S.INVOICE_ID
	, S.INVOICED_DATE
	, S.PACKLIST_ID AS PACK_SLIPS
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.SETUP_COMPLETED
	, CO.CUSTOMER_PO_REF
	, CASE 
		WHEN WO.BASE_ID LIKE 'R' THEN 0
		ELSE HOURS_WORKED * 75
	END AS EXTENDED_DOLLARS
	, CASE
		WHEN O.RESOURCE_ID = 'CONTRACTOR' THEN 150
		ELSE 0
	END AS SPECIAL_FEES
	, CASE
		WHEN LT.[TYPE] = 'S' THEN LT.HOURS_WORKED
		ELSE 0
	END AS SORT_SETUP
	, CASE
		WHEN LT.[TYPE] = 'R' THEN LT.HOURS_WORKED
		ELSE 0
	END AS SORT_RUN
	, 0 AS EXPEDITE_HOURS
FROM DATAWAREHOUSE.dbo.SHIPPER S
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO 
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
INNER JOIN DATAWAREHOUSE.dbo.OPERATION O
	ON WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O.WORKORDER_SUB_ID
	AND WO.[TYPE] = O.WORKORDER_TYPE
INNER JOIN DATAWAREHOUSE.dbo.LABOR_TICKET LT
	ON O.SEQUENCE_NO = LT.OPERATION_SEQ_NO
	AND O.WORKORDER_BASE_ID = LT.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = LT.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
WHERE SL.SHIPPED_QTY > 0
--	AND CO.CUSTOMER_ID = N'BOE602' OR CO.CUSTOMER_ID = N'BOE605')
	AND CO.CUSTOMER_ID IN (N'BOE602', N'BOE605', N'BOEEME')
	AND WO.BASE_ID NOT LIKE N'%R%'
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.ResourceID_ReportSettings EX
		WHERE O.RESOURCE_ID = EX.RESOURCE_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE605revF'
		)
	AND (S.INVOICED_DATE >= @STARTDATE AND S.INVOICED_DATE <= @ENDDATE)
--	AND CO.ID = @CUST_ORDER_ID
) A
GROUP BY CUST_ORDER_ID
	, BASE_ID
	, PART_NUMBER
	, BILLED_QTY
	, SHIPPED_QTY
	, INVOICE_ID
	, INVOICED_DATE
	, PACK_SLIPS
	, CUSTOMER_PO_REF
ORDER BY INVOICED_DATE
)

--BOE002 - Finish - G:\ACCTG\AR\2019\Crystal Reports\Finish 609v1 – (Hours + Setup Hrs) * 70
, BOE002 AS
(SELECT 0 AS COST_ITEM
	, CASE 
		WHEN BASE_ID LIKE '%R%' THEN 'RWK'
		ELSE '1'
	END AS POS
	, CUST_ORDER_ID
	, BASE_ID
	, PART_NUMBER
	, BILLED_QTY
	, SHIPPED_QTY
	, INVOICE_ID
	, INVOICED_DATE
	, PACK_SLIPS
	, CUSTOMER_PO_REF
	, 0 AS EXPEDITE_DOLLARS	
	, SUM(EXTENDED_DOLLARS)/BILLED_QTY AS UNIT_PRICE
	, SUM(SPECIAL_FEES) AS SPECIAL_FEES
	, SUM(SORT_SETUP) AS SORT_SETUP
	, SUM(SORT_RUN) AS SORT_RUN
	, 0 AS EXPEDITE_HOURS
	, SUM(EXTENDED_DOLLARS) AS EXTENDED_DOLLARS
	, INVOICED_DATE AS COMMENTS
FROM
(SELECT CO.ID AS CUST_ORDER_ID
	, WO.BASE_ID
	, LT.HOURS_WORKED
	, COL.PART_ID AS PART_NUMBER
	, COL.TOTAL_SHIPPED_QTY AS BILLED_QTY
	, LT.[TYPE]
	, LT.TRANSACTION_ID
	, CO.CUSTOMER_ID
	, LT.TRANSACTION_DATE
	, SL.SHIPPED_QTY
	, S.INVOICE_ID
	, S.INVOICED_DATE
	, S.PACKLIST_ID AS PACK_SLIPS
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.SETUP_COMPLETED
	, CO.CUSTOMER_PO_REF
	, CASE 
		WHEN COL.PART_ID = '411N2001-1' THEN HOURS_WORKED * 70
		WHEN WO.BASE_ID LIKE 'R' THEN 0
		ELSE HOURS_WORKED * 70
	END AS EXTENDED_DOLLARS
	, 0 AS SPECIAL_FEES
	, CASE
		WHEN LT.[TYPE] = 'S' THEN LT.HOURS_WORKED
		ELSE 0
	END AS SORT_SETUP
	, CASE
		WHEN COL.PART_ID LIKE '437W8500%' AND O.RESOURCE_ID LIKE '%BORIC%' THEN 1.73
		WHEN COL.PART_ID LIKE '437W8500%' AND O.RESOURCE_ID LIKE '%ETCH%' THEN 1.73
		WHEN LT.[TYPE] = 'R' THEN LT.HOURS_WORKED
		ELSE 0
	END AS SORT_RUN
	, 0 AS EXPEDITE_HOURS
FROM DATAWAREHOUSE.dbo.SHIPPER S
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO 
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
INNER JOIN DATAWAREHOUSE.dbo.OPERATION O
	ON WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O.WORKORDER_SUB_ID
	AND WO.[TYPE] = O.WORKORDER_TYPE
INNER JOIN DATAWAREHOUSE.dbo.LABOR_TICKET LT
	ON O.SEQUENCE_NO = LT.OPERATION_SEQ_NO
	AND O.WORKORDER_BASE_ID = LT.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = LT.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
INNER JOIN DATAWAREHOUSE.dbo.SHOP_RESOURCE SR
	ON LT.RESOURCE_ID = SR.ID
WHERE SL.SHIPPED_QTY > 0
	AND SR.SKILLS_TYPE <> N'M'
	AND CO.CUSTOMER_ID = N'BOE609'
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.ResourceID_ReportSettings EX
		WHERE LT.RESOURCE_ID = EX.RESOURCE_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 - Finish 609v1'
	AND (S.INVOICED_DATE >= @STARTDATE AND S.INVOICED_DATE <= @ENDDATE)
--	AND CO.ID = @CUST_ORDER_ID
	)
) A
GROUP BY CUST_ORDER_ID
	, BASE_ID
	, PART_NUMBER
	, BILLED_QTY
	, SHIPPED_QTY
	, INVOICE_ID
	, INVOICED_DATE
	, PACK_SLIPS
	, CUSTOMER_PO_REF
ORDER BY INVOICED_DATE
)

, BOE003 AS 
--BOE609 - MFG - G:\ACCTG\AR\2019\Crystal Reports\Mfg 609 V7 no 5 axis1 – (Hours + Setup Hrs) * 68.40
(SELECT 0 AS COST_ITEM
	, CASE 
		WHEN BASE_ID LIKE '%R%' THEN 'RWK'
		ELSE '1'
	END AS POS
	, CUST_ORDER_ID
	, BASE_ID
	, PART_NUMBER
	, BILLED_QTY
	, SHIPPED_QTY
	, INVOICE_ID
	, INVOICED_DATE
	, PACK_SLIPS
	, CUSTOMER_PO_REF
	, 0 AS EXPEDITE_DOLLARS	
	, SUM(EXTENDED_DOLLARS)/BILLED_QTY AS UNIT_PRICE
	, SUM(SPECIAL_FEES) AS SPECIAL_FEES
	, SUM(SORT_SETUP) AS SORT_SETUP
	, SUM(SORT_RUN) AS SORT_RUN
	, 0 AS EXPEDITE_HOURS
	, SUM(EXTENDED_DOLLARS) AS EXTENDED_DOLLARS
	, INVOICED_DATE AS COMMENTS
FROM
(SELECT CO.ID AS CUST_ORDER_ID
	, WO.BASE_ID
	, LT.HOURS_WORKED
	, COL.PART_ID AS PART_NUMBER
	, COL.TOTAL_SHIPPED_QTY AS BILLED_QTY
	, LT.[TYPE]
	, LT.TRANSACTION_ID
	, CO.CUSTOMER_ID
	, LT.TRANSACTION_DATE
	, SL.SHIPPED_QTY
	, S.INVOICE_ID
	, S.INVOICED_DATE
	, S.PACKLIST_ID AS PACK_SLIPS
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.SETUP_COMPLETED
	, CO.CUSTOMER_PO_REF
	, CASE 
		--WHEN COL.PART_ID = '411N2001-1' THEN HOURS_WORKED * 70
		WHEN WO.BASE_ID LIKE 'R' THEN 0
		ELSE HOURS_WORKED * 70
	END AS EXTENDED_DOLLARS
	, 0 AS SPECIAL_FEES
	, CASE
		WHEN LT.[TYPE] = 'S' THEN LT.HOURS_WORKED
		ELSE 0
	END AS SORT_SETUP
	, CASE
		--WHEN COL.PART_ID LIKE '437W8500%' AND O.RESOURCE_ID LIKE '%BORIC%' THEN 1.73
		--WHEN COL.PART_ID LIKE '437W8500%' AND O.RESOURCE_ID LIKE '%ETCH%' THEN 1.73
		WHEN LT.[TYPE] = 'R' THEN LT.HOURS_WORKED
		ELSE 0
	END AS SORT_RUN
	, 0 AS EXPEDITE_HOURS
FROM DATAWAREHOUSE.dbo.SHIPPER S
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
INNER JOIN DATAWAREHOUSE.dbo.LABOR_TICKET LT
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
INNER JOIN DATAWAREHOUSE.dbo.SHOP_RESOURCE SR
	ON LT.RESOURCE_ID = SR.ID
WHERE  SL.SHIPPED_QTY > 0
	AND SR.SKILLS_TYPE IN (N'D', N'E', N'M')
	AND CO.CUSTOMER_ID = N'BOE609'
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.PartID_ReportSettings EX
		WHERE COL.PART_ID = EX.PART_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Mfg 609 V7 no 5 axis1'
	)
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.ResourceID_ReportSettings EX
		WHERE LT.RESOURCE_ID = EX.RESOURCE_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Mfg 609 V7 no 5 axis1'
	)
	AND (S.INVOICED_DATE >= @STARTDATE AND S.INVOICED_DATE <= @ENDDATE)
--	AND CO.ID = @CUST_ORDER_ID
) A
GROUP BY ID
	, BASE_ID
	, ORDER_QTY
)

, BOE_04 AS
--BOE609 - ASSY - G:\ACCTG\AR\2019\Crystal Reports\Assy 609 V7a – (Hours + Setup Hrs) * 55.10
(SELECT 'BOE_04' AS [ORDER_TYPE]
	, CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
	, SUM(LT.HOURS_WORKED) AS TOTAL_HOURS_WORKED
	, ((SUM(LT.HOURS_WORKED) * 55.10) / COL.ORDER_QTY) AS UNIT_PRICE
	, SUM(LT.HOURS_WORKED) * 55.10 AS REC_AMOUNT
FROM DATAWAREHOUSE.dbo.SHIPPER S
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
INNER JOIN DATAWAREHOUSE.dbo.LABOR_TICKET LT
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
INNER JOIN DATAWAREHOUSE.dbo.SHOP_RESOURCE SR
	ON LT.RESOURCE_ID = SR.ID
WHERE SL.SHIPPED_QTY > 0
	AND SR.SKILLS_TYPE IN (N'D', N'E', N'M')
	AND CO.CUSTOMER_ID = N'BOE609'
	AND EXISTS (SELECT 1 FROM LIVESupplemental.dbo.PartID_ReportSettings EX
		WHERE COL.PART_ID = EX.PART_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Assy 609 V7a'
	)
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.ResourceID_ReportSettings EX
		WHERE LT.RESOURCE_ID = EX.RESOURCE_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Assy 609 V7a'
	)
	AND (S.INVOICED_DATE >= @STARTDATE AND S.INVOICED_DATE <= @ENDDATE)
--	AND CO.ID = @CUST_ORDER_ID
GROUP BY CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
)

, BOE_05 AS
--BOE609 - 5AXIS - G:\ACCTG\AR\2019\Crystal Reports\Mfg 609 5 Axis – (Hours + Setup Hrs) * 80
(SELECT 'BOE_05' AS [ORDER_TYPE]
	, CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
	, SUM(LT.HOURS_WORKED) AS TOTAL_HOURS_WORKED5
	, ((SUM(LT.HOURS_WORKED) * 80) / COL.ORDER_QTY) AS UNIT_PRICE
	, SUM(LT.HOURS_WORKED) * 80 AS REC_AMOUNT
FROM DATAWAREHOUSE.dbo.SHIPPER S
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
INNER JOIN DATAWAREHOUSE.dbo.LABOR_TICKET LT
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
INNER JOIN DATAWAREHOUSE.dbo.SHOP_RESOURCE SR
	ON LT.RESOURCE_ID = SR.ID
WHERE SL.SHIPPED_QTY > 0
	AND SR.SKILLS_TYPE IN (N'D', N'E', N'M')
	AND CO.CUSTOMER_ID = N'BOE609'
	AND EXISTS (SELECT 1 FROM LIVESupplemental.dbo.PartID_ReportSettings EX
		WHERE COL.PART_ID = EX.PART_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Mfg 609 5 Axis'
	)
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.ResourceID_ReportSettings EX
		WHERE LT.RESOURCE_ID = EX.RESOURCE_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Mfg 609 5 Axis'
	)
	AND (S.INVOICED_DATE >= @STARTDATE AND S.INVOICED_DATE <= @ENDDATE)
--	AND CO.ID = @CUST_ORDER_ID
GROUP BY CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
)

, BOE_06 AS
--BOE614 - G:\ACCTG\AR\2019\Crystal Reports\boe614 boltboards 2 – (Hours + Setup Hrs) * 60
(SELECT 'BOE_06' AS [ORDER_TYPE]
	, CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
	, SUM(LT.HOURS_WORKED) AS TOTAL_HOURS_WORKED
	, ((SUM(LT.HOURS_WORKED) * 60) / COL.ORDER_QTY) AS UNIT_PRICE
	, SUM(LT.HOURS_WORKED) * 60 AS REC_AMOUNT
FROM DATAWAREHOUSE.dbo.RECEIVABLE_LINE RL
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN DATAWAREHOUSE.dbo.RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
	AND DSL.SUPPLY_SUB_ID = WO.SUB_ID
INNER JOIN DATAWAREHOUSE.dbo.LABOR_TICKET LT
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
WHERE RL.QTY > 0
	AND CO.CUSTOMER_ID = N'BOE614'
	AND (R.INVOICE_DATE >= @STARTDATE AND R.INVOICE_DATE <= @ENDDATE)
--	AND CO.ID = @CUST_ORDER_ID
GROUP BY CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
)
