--VISUAL ENTERPRISE REPORTS-->INVENTORY REPORTS-->BILL OF MATERIAL AVAILABILITY

/**********************************************************************************************
DESCRIPTION:     MATERIALS AVAILABILITY REPORT
DEPENDENCY:		 REPORT DEPENDS ON DATASET IN WORKORDER FOLDER FOR CUSTOMER DROP DOWN.	

DATE        MODIFIED BY         CHANGE DESCRIPTION
----------  ------------------  ------------------------------------------------------------
3/7/2020	VIVIAN ELIA		    VIVIAN HAD CREATED, AND BEGAN TESTING, PRE-COVID19
10/23/2020	WILLIAM THOMPSON	ASSIGNED MYSELF TO THE PROJECT.
10/23/2020	WILLIAM THOMPSON	REMAINING OPS

**********************************************************************************************/

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DEADLOCK_PRIORITY LOW

; WITH CTE_WO AS
(SELECT WO.[TYPE]
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, DBO.SFNWONUMFORMAT(WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID) AS WONUM
	, WO.[STATUS]
	, WO.DESIRED_QTY
	, WO.PART_ID
	, ISNULL(WO.DESIRED_RLS_DATE, 
		(SELECT WO1.DESIRED_RLS_DATE 
		FROM WORK_ORDER WO1
		WHERE WO.BASE_ID = WO1.BASE_ID
			AND WO.LOT_ID = WO1.LOT_ID
			AND WO.SPLIT_ID	= WO1.SPLIT_ID
			AND WO1.SUB_ID = '0'
			AND WO.[TYPE] = WO1.[TYPE])
	) AS DESIRED_RLS_DATE
	, ISNULL(WO.DESIRED_WANT_DATE, 
		(SELECT WO1.DESIRED_WANT_DATE 
		FROM WORK_ORDER WO1
		WHERE WO.BASE_ID = WO1.BASE_ID
			AND WO.LOT_ID = WO1.LOT_ID
			AND WO.SPLIT_ID = WO1.SPLIT_ID
			AND WO1.SUB_ID = '0'
			AND WO.[TYPE] = WO1.[TYPE])
	) AS DESIRED_WANT_DATE
	, ISNULL(DBO.SFN_REMAINING_OPERATIONS(WO.[TYPE], WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID), N'NO REMAINING OPERATIONS') REMAINING_OPERATIONS
	, [DBO].[SFN_CURRENT_OPERATION] (WO.[TYPE],WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID) AS CURRENTOPERATION
FROM WORK_ORDER WO
WHERE WO.[TYPE] = N'W'
AND WO.[STATUS] IN ('F', 'R', 'U')
)

SELECT ZEROX10 = '00000' + '00000' 
	, ZEROX15 = '00000' + '00000' + '00000'   
	, ZEROX20 = '00000' + '00000' + '00000' + '00000' 
	, DESIRED_RLS_DATE AS WO_RELEASE_DATE 
	, DESIRED_WANT_DATE AS WO_DUE_DATE
	, DESIRED_QTY AS WO_QTY
	, WO_PART_ID  AS WO_PART_ID
	, A.ENDITEM_PART_ID
	, ISNULL(CUSTOMER_VIA_BUYER, '_BLANK') AS CUST_VIA_BUYER
	, WP_DESCRIPTION AS WO_DESCRIPTION
	, BUYER_USER_ID AS WO_BUYER_ID 
	, WONUM AS WO_NUM
	, SEQUENCE_NO AS WO_OP_NUM 
	, PIECE_NO
	, RQ_PART_ID AS BOM_PART_ID
	, RQP_DESCRIPTION AS BOM_ITEM_DESCRIPTION
	, RTOTAL AS QTY_REQD
	, QTY_AVAILABLE_ISS AS QTY_AVAILABLE
	, USAGE_UM  
	, CASE 
		WHEN QTY_AVAILABLE_ISS >= RTOTAL THEN 'YES'
		ELSE 'NO'
	END AS IN_STOCK 
	,  CUST_ORDER_ID 
	, LEFT(RESOURCE_ID,2) AS PLANT
	, PRIMARY_LOC_ID AS PRIMARY_LOC
	, WO_STATUS
	, A.RESOURCE_ID
	, A.SEQUENCE_NO
	, A.REMAINING_OPERATIONS
	, ISSERVICE -- IF REMAINING OPERATIONS CONTAIN SERVICE
	, A.WONUM
	, A.CURRENTOPERATION
	, A.CUSTOMER_ID_X
	, A.DSLTYPE
	, A.BUYER_USER_ID
	, CUSTOMER_ID
	, ENDITEM_PART_BUYER_USER_ID
--INTO #RESULTS
FROM 
	(SELECT O.RESOURCE_ID
		, O.SEQUENCE_NO
		, RQ.PART_ID AS RQ_PART_ID
		, P.[DESCRIPTION] AS RQP_DESCRIPTION
		, P.COMMODITY_CODE
		, P.PLANNER_USER_ID
		, P.BUYER_USER_ID
		, CASE 
			WHEN ISNUMERIC(SUBSTRING(P.BUYER_USER_ID, 4, 3)) = 1 THEN 'BOEPOP'
			ELSE SUBSTRING(P.BUYER_USER_ID, 4,6) 
		END AS CUSTOMER_VIA_BUYER
		, ISNULL(P.PRIMARY_LOC_ID, '') AS PRIMARY_LOC_ID
		, RQ.CALC_QTY
		, SUM(RQ.CALC_QTY) OVER(PARTITION BY RQ.PART_ID  ORDER BY RQ.PART_ID, WO.DESIRED_RLS_DATE) AS RTOTAL
		, WO.PART_ID AS WO_PART_ID
		, WO.WONUM
		, WO.DESIRED_RLS_DATE
		, WO.DESIRED_WANT_DATE
		, WO.DESIRED_QTY
		, P.QTY_AVAILABLE_ISS
		, WO.BASE_ID
		, WP.[DESCRIPTION] AS WP_DESCRIPTION
		, RQ.PIECE_NO
		, RQ.QTY_PER 
		, RQ.USAGE_UM
		, RQ.ISSUED_QTY
		, WO.[STATUS] AS WO_STATUS
		, ISSERVICE = IIF((CHARINDEX ('CONTRACTOR' , WO.REMAINING_OPERATIONS)) > 0, 1,0)
		, WO.REMAINING_OPERATIONS
		, WO.CURRENTOPERATION
		, DSLTYPE = CASE 
			WHEN (DSL.DEMAND_BASE_ID IS NULL AND DSL.DEMAND_SEQ_NO IS NULL AND DSL.DEMAND_TYPE IS NULL) THEN 'UNLINKED'
			WHEN (DSL.DEMAND_BASE_ID IS NOT NULL AND DSL.DEMAND_SEQ_NO IS NOT NULL AND DSL.DEMAND_TYPE IS NOT NULL) THEN 'LINKED'
		END

--?????????????????
		, CUSTOMER_ID_X = IIF((CASE 
				WHEN (DSL.DEMAND_BASE_ID IS NULL AND DSL.DEMAND_SEQ_NO IS NULL AND DSL.DEMAND_TYPE IS NULL) THEN 'UNLINKED'
			END) = 'UNLINKED' 
			AND NULLIF(LTRIM(RTRIM(CO.CUSTOMER_ID)), '') IS NULL  -- VERSION 2
			, IIF(ISNUMERIC(SUBSTRING(ENDITEMPART.BUYER_USER_ID, 4, 1)) = 1,'BOEPOP', SUBSTRING(ENDITEMPART.BUYER_USER_ID, 4, 6)), CO.CUSTOMER_ID) 

		, CO.CUSTOMER_ID CO_CUSTOMR_ID
		, ENDITEMPART.PART_ID ENDITEM_PART_ID
		, COL.CUST_ORDER_ID
		, CO.CUSTOMER_ID
		, ENDITEMPART.BUYER_USER_ID ENDITEM_PART_BUYER_USER_ID
	FROM CTE_WO WO
	LEFT JOIN WORK_ORDER ENDITEM
		ON ENDITEM.[TYPE] = WO.[TYPE]
		AND ENDITEM.[BASE_ID] = WO.[BASE_ID]
		AND ENDITEM.[LOT_ID] = WO.[LOT_ID]
		AND ENDITEM.[SPLIT_ID] = WO.[SPLIT_ID]
		AND ENDITEM.[SUB_ID] = '0'
	LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
		ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
		AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
		AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
	LEFT OUTER JOIN OPERATION O
		ON WO.BASE_ID = O.WORKORDER_BASE_ID
		AND WO.LOT_ID = O.WORKORDER_LOT_ID
		AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
		AND WO.SUB_ID = O.WORKORDER_SUB_ID
		AND WO.[TYPE] = O.WORKORDER_TYPE
		AND WO.CURRENTOPERATION = O.SEQUENCE_NO
	LEFT OUTER JOIN PART WP
		ON WO.PART_ID = WP.ID
	LEFT OUTER JOIN REQUIREMENT RQ
		ON O.WORKORDER_TYPE = RQ.WORKORDER_TYPE
		AND O.WORKORDER_BASE_ID = RQ.WORKORDER_BASE_ID
		AND O.WORKORDER_LOT_ID = RQ.WORKORDER_LOT_ID
		AND O.WORKORDER_SPLIT_ID = RQ.WORKORDER_SPLIT_ID
		AND O.WORKORDER_SUB_ID = RQ.WORKORDER_SUB_ID
		AND O.SEQUENCE_NO = RQ.OPERATION_SEQ_NO
	LEFT OUTER JOIN PART_SITE_VIEW P
		ON RQ.PART_ID = P.PART_ID
		AND P.SITE_ID = 'SK01'
	OUTER APPLY (SELECT TOP 1 COL2.CUST_ORDER_ID
		FROM CUST_ORDER_LINE COL2
		WHERE COL2.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
			AND COL2.LINE_NO = DSL.DEMAND_SEQ_NO
			AND DSL.DEMAND_TYPE = N'CO'
		) COL
	LEFT JOIN CUSTOMER_ORDER CO
		ON CO.ID = COL.CUST_ORDER_ID
	LEFT JOIN PART_SITE_VIEW ENDITEMPART
		ON ENDITEMPART.PART_ID = ENDITEM.PART_ID
		AND ENDITEMPART.SITE_ID = N'SK01'
		AND ISNULL(ENDITEMPART.PART_ID, '') != 'REWORK MFG'
	WHERE O.RESOURCE_ID IN (N'P2M2-RLSMTL-CMP', N'P2M1-RLSMTL', N'P2M1-KIT-FG', N'P2M2-KIT-CMP', N'P3M1-KIT', N'P3M1-KIT-CMP')
	) AS A
WHERE (1=1)
	AND LEFT(RESOURCE_ID,2) IN (@PLANT)
	AND A.RESOURCE_ID IN (@RESOURCE_ID)
	
/*

RESOURCEIDS CALLED:
P2M2-RLSMTL-CMP
P2M1-RLSMTL
P2M1-KIT-FG
P2M2-KIT-CMP
P3M1-KIT
P3M1-KIT-CMP

TOTAL RESOURCEIDS:
P1M1-CP-KIT
P2M1-KIT-FG
P2M1-RLSMTL
--> P2M1-STAGNG-CMP
P2M2-KIT-CMP
P2M2-RLSMTL-CMP
*/