USE CRUNCH0521
GO

DROP TABLE #T1

SELECT ID
	, [STATUS]
	, BUYER_USER_ID
	, CASE
		WHEN LEFT(BUYER_USER_ID, 4) IN ('01-5', '01-6') THEN REPLACE(BUYER_USER_ID, '01-', '02-') 
		ELSE REPLACE(BUYER_USER_ID, '01-', '06-') 
	END AS NEW_BUI
INTO #T1
FROM PART P
WHERE ([STATUS] IS NULL OR [STATUS] != 'O')
	AND LEFT(BUYER_USER_ID, 2) IN ('01')

SELECT * FROM #T1

/*
BEGIN TRANSACTION
UPDATE PART
SET BUYER_USER_ID = NEW_BUI
FROM PART P
INNER JOIN #T1 T
ON P.ID = T.ID
--> 2110 RECORDS

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

SELECT ID 
, [STATUS]
, BUYER_USER_ID
FROM PART
WHERE ([STATUS] IS NULL OR [STATUS] != 'O')
	AND LEFT(BUYER_USER_ID, 2) IN ('01')

/*
BEGIN TRANSACTION
UPDATE PART_SITE
SET BUYER_USER_ID = NEW_BUI
FROM PART_SITE P
INNER JOIN #T1 T
ON P.PART_ID = T.ID
--> 2069 RECORDS

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

SELECT PART_ID 
, [STATUS]
, BUYER_USER_ID
FROM PART_SITE
WHERE ([STATUS] IS NULL OR [STATUS] != 'O')
	AND LEFT(BUYER_USER_ID, 2) IN ('01')

