/*
--> SQL-LAB-1
UPDATE LIVESupplemental.dbo.buyer_assn
SET SALESPERSON_ID = '',
	[USER_ID] = NULL
WHERE Account_ID = '53'

UPDATE CUSTOMER
SET SALESREP_ID = B.SALESPERSON_ID,
	USER_4 = C.SALESREP_ID
--SELECT *
FROM LIVESupplemental.dbo.Cust_Reps C
LEFT OUTER JOIN LIVESupplemental.dbo.buyer_assn b
	ON c.SALESREP_ID = b.Account_ID
LEFT OUTER JOIN CUSTOMER CO
	ON C.CUST_ID = CO.ID
WHERE C.SALESREP_ID IS NOT NULL
	AND CO.ACTIVE_FLAG = 'Y'

--> SQL-BI-1
UPDATE LIVESupplemental.dbo.buyer_assn
SET SALESPERSON_ID = '',
	[USER_ID] = NULL
WHERE Account_ID = '53'

*/