/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [SKILLS_TYPE]
      ,[BUSINESS_ENTITY]
      ,[SETUP_COST_PER_HR]
      ,[RUN_COST_PER_HR]
      ,[BUR_PERCENT_RUN]
      ,[BUR_PERCENT_SETUP]
      ,[AFC_GL_ACCT_ID]
      ,[AFB_GL_ACCT_ID]
      ,[STARTDATEOFRATE]
      ,[ENDDATEOFRATE]
  FROM [LIVESupplemental].[dbo].[RATES]
  
 /*
BEGIN TRANSACTION;
UPDATE [dbo].[RATES]
SET [BUR_PERCENT_RUN] = '132.0'
,[BUR_PERCENT_SETUP] = '132.0'
WHERE BUSINESS_ENTITY = 'Finish'

UPDATE [dbo].[RATES]
SET [BUR_PERCENT_RUN] = '73.0'
,[BUR_PERCENT_SETUP] = '73.0'
WHERE BUSINESS_ENTITY = 'Manufacturing'

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

SELECT * FROM SHOP_RESOURCE_SITE WHERE USER_1 IN ('C', 'O', 'X')

SELECT * FROM SHOP_RESOURCE_SITE WHERE USER_1 IN ('M', 'X') AND (STATUS IS NULL OR STATUS != 'O')
SELECT * FROM SHOP_RESOURCE_SITE WHERE USER_1 IN ('A', 'B', 'O') AND (STATUS IS NULL OR STATUS != 'O')

/*
BEGIN TRANSACTION;
UPDATE SHOP_RESOURCE_SITE 
SET BUR_PERCENT_SETUP = 73
, BUR_PERCENT_RUN = 73
WHERE USER_1 IN ('M', 'X')
AND RESOURCE_ID != 'contractor'
--> 217 ROWS AFFECTED
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

BEGIN TRANSACTION;
UPDATE SHOP_RESOURCE_SITE 
SET BUR_PERCENT_SETUP = 132
, BUR_PERCENT_RUN = 132
WHERE USER_1 IN ('A', 'B', 'O')
--> 200 ROWS AFFECTED
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

SELECT TOP 100 * FROM OPERATION WHERE WORKORDER_TYPE = 'M'

SELECT RESOURCE_ID, SR.STATUS, COUNT(*) FROM OPERATION O
INNER JOIN SHOP_RESOURCE SR
ON SR.ID = O.RESOURCE_ID
WHERE WORKORDER_TYPE = 'M' 
GROUP BY RESOURCE_ID, SR.STATUS 
ORDER BY RESOURCE_ID, SR.STATUS
