USE DATAWAREHOUSE
GO

DECLARE @STARTDATE DATE = '8/23/2020'
, @ENDDATE DATE = '8/31/2020'
, @EEID NVARCHAR(6) = '003356'

SELECT SUM(HOURS) FROM SIMPLEWAREHOUSE.ADP_LABOR WHERE [FILE NUMBER] = @EEID
AND [PAY DATE] >= @STARTDATE
AND [PAY DATE] <= @ENDDATE

SELECT 30 - SUM(HOURS) FROM SIMPLEWAREHOUSE.ADP_LABOR WHERE [FILE NUMBER] = @EEID
AND [PAY DATE] >= @STARTDATE
AND [PAY DATE] <= @ENDDATE

SELECT 33.65 * SUM(HOURS) FROM SIMPLEWAREHOUSE.ADP_LABOR WHERE [FILE NUMBER] = @EEID 
AND [PAY DATE] >= @STARTDATE
AND [PAY DATE] <= @ENDDATE

SELECT * FROM SIMPLEWAREHOUSE.ADP_LABOR WHERE [FILE NUMBER] = @EEID
AND [PAY DATE] >= @STARTDATE
AND [PAY DATE] <= @ENDDATE
ORDER BY [PAY DATE] DESC
