use live
go

/*
ResourceID		Dept
--------------------------------
AUB-clean		AUB-clean
AUB-pen			AUB-Penetrant
AUB-PENetch		AUB-Penetrant
AUB-1000		AUB-Tankline
AUB-600			AUB-Tankline
AUB-alo			AUB-Tankline
AUB-ano			AUB-Tankline
AUB-boric		AUB-Tankline
AUB-chemstrip	AUB-Tankline
AUB-emu			AUB-Tankline
AUB-etch		AUB-Tankline
AUB-solgel		AUB-Tankline
AUB-tube		AUB-Tankline
AUB-TurcoClean	AUB-Tankline
BAL-pen			BAL-Penetrant
BAL-PENetch		BAL-Penetrant
BAL-1000		BAL-Tankline
BAL-600			BAL-Tankline
BAL-alo			BAL-Tankline
BAL-ano			BAL-Tankline
BAL-boric		BAL-Tankline
BAL-chemstrip	BAL-Tankline
BAL-emu			BAL-Tankline
BAL-etch		BAL-Tankline
BAL-sulf		BAL-Tankline
sulf			BAL-Tankline
Clean			Clean (Ballard)
--Remove:
--BAL-rack		BAL-Tankline
--BAL-takedown	BAL-Tankline
--BAL-unrack	BAL-Tankline

*/


DECLARE @StartDate DATE = '01/01/2015'
DECLARE @EndDate DATE = '12/31/2016'

SELECT 
	'Main' AS Msg,
	W.BASE_ID,
	W.LOT_ID,
	W.SPLIT_ID,
	W.SUB_ID,
	W.[STATUS],
	CASE
		WHEN W.PART_ID LIKE '%REWORK%' THEN W2.PART_ID
		WHEN W.PART_ID LIKE '%TOOLING%' THEN W2.PART_ID
		WHEN W.PART_ID IS NULL THEN W2.PART_ID
		ELSE W.PART_ID
	END AS PartID,
	W.PART_ID AS ChildPart,
	CASE
		WHEN O2.WORKORDER_BASE_ID IS NULL  THEN 'No'
		ELSE 'Yes'
	END AS SHOTPEEN,
	CASE
		WHEN O3.WORKORDER_BASE_ID IS NULL  THEN 'No'
		ELSE 'Yes'
	END AS Penetrant,
	O.SEQUENCE_NO, 
	O.RESOURCE_ID, 
	O.OPERATION_TYPE, 
	TransDate,
	PSA.ALLOY,
	PSA.THICKNESS_VAL,
	PSA.LENGTH_VAL,
	PSA.WIDTH_VAL,
	PSA.SURFACE_AREA AS Each_Surf_Area,
	W.[DESIRED_QTY],
	W.DESIRED_QTY * ISNULL(PSA.SURFACE_AREA, 0) AS Total_Surf_Area
from	   
	WORK_ORDER W
inner JOIN 
	WORK_ORDER W2
	ON  W.TYPE = W2.TYPE
	AND W.BASE_ID = W2.BASE_ID
	AND W.LOT_ID = W2.LOT_ID
	AND W.SPLIT_ID = W2.SPLIT_ID
	AND W2.SUB_ID = '0'
INNER JOIN 
	OPERATION O
	ON  W.TYPE = O.WORKORDER_TYPE
	AND W.BASE_ID = O.WORKORDER_BASE_ID
	AND W.LOT_ID = O.WORKORDER_LOT_ID
	AND W.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND W.SUB_ID = O.WORKORDER_SUB_ID
LEFT OUTER JOIN 
	(SELECT 
		O2.WORKORDER_TYPE,
		O2.WORKORDER_BASE_ID,
		O2.WORKORDER_LOT_ID,
		O2.WORKORDER_SPLIT_ID, 
		O2.WORKORDER_SUB_ID,
		MIN(O2.SEQUENCE_NO) AS SP_Seq_No
	FROM 
		OPERATION O2
	WHERE 
		O2.RESOURCE_ID IN ('AUB-MSP', 'AUB-SP', 'BAL-SP', 'MSP', 'SP')
	GROUP BY 
		O2.WORKORDER_TYPE,
		O2.WORKORDER_BASE_ID,
		O2.WORKORDER_LOT_ID,
		O2.WORKORDER_SPLIT_ID, 
		O2.WORKORDER_SUB_ID
	) AS O2
		ON  W.TYPE = O2.WORKORDER_TYPE
		AND W.BASE_ID  = O2.WORKORDER_BASE_ID
		AND W.LOT_ID = O2.WORKORDER_LOT_ID
		AND W.SPLIT_ID = O2.WORKORDER_SPLIT_ID
		AND W.SUB_ID = O2.WORKORDER_SUB_ID
LEFT OUTER JOIN 
	(SELECT 
		O3.WORKORDER_TYPE,
		O3.WORKORDER_BASE_ID,
		O3.WORKORDER_LOT_ID,
		O3.WORKORDER_SPLIT_ID, 
		O3.WORKORDER_SUB_ID,
		MIN(O3.SEQUENCE_NO) AS Pen_Seq_No
	FROM 
		OPERATION O3
	WHERE
		O3.RESOURCE_ID IN ('AUB-PEN', 'BAL-PEN', 'AUB-PENETCH', 'BAL-PENETCH')
	GROUP BY 
		O3.WORKORDER_TYPE,
		O3.WORKORDER_BASE_ID,
		O3.WORKORDER_LOT_ID,
		O3.WORKORDER_SPLIT_ID, 
		O3.WORKORDER_SUB_ID
	) AS O3
		ON  W.TYPE = O3.WORKORDER_TYPE
		AND W.BASE_ID = O3.WORKORDER_BASE_ID
		AND W.LOT_ID = O3.WORKORDER_LOT_ID
		AND W.SPLIT_ID = O3.WORKORDER_SPLIT_ID
		AND W.SUB_ID = O3.WORKORDER_SUB_ID
LEFT OUTER JOIN
	(SELECT
		LT.WORKORDER_TYPE,
		LT.WORKORDER_BASE_ID,
		LT.WORKORDER_LOT_ID,
		LT.WORKORDER_SPLIT_ID,
		LT.WORKORDER_SUB_ID,
		LT.OPERATION_SEQ_NO,
		MIN(LT.TRANSACTION_DATE) AS TransDate
	FROM	  
		LABOR_TICKET LT
	INNER JOIN 
		OPERATION O
		ON LT.WORKORDER_TYPE = O.WORKORDER_TYPE
		AND LT.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
		AND LT.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
		AND LT.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
		AND LT.WORKORDER_SUB_ID = O.WORKORDER_SUB_ID
		AND LT.OPERATION_SEQ_NO = O.SEQUENCE_NO
	GROUP BY 	   
		LT.WORKORDER_TYPE,
		LT.WORKORDER_BASE_ID,
		LT.WORKORDER_LOT_ID,
		LT.WORKORDER_SPLIT_ID,
		LT.WORKORDER_SUB_ID,
		LT.OPERATION_SEQ_NO
	) AS LT
	ON  O.WORKORDER_TYPE = LT.WORKORDER_TYPE
	AND O.WORKORDER_BASE_ID = LT.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = LT.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = LT.WORKORDER_SUB_ID
	AND O.SEQUENCE_NO = LT.OPERATION_SEQ_NO
INNER JOIN 
	LIVESUPPLEMENTAL.DBO.RESOURCEID_ASSIGNMENTS RA
	ON  RA.RESOURCE_ID = O.RESOURCE_ID
	AND RA.DEPT IN ('AUB-Tankline', 'BAL-Tankline', 'AUB-Penetrant', 'Bal-Penetrant', 'Clean', 'AUB-clean')
	AND RA.RESOURCE_ID NOT IN ('BAL-rack', 'BAL-takedown', 'BAL-unrack')
LEFT OUTER JOIN 
	SKILLS_PART_SURFACE_AREA AS PSA
	ON W2.PART_ID = PSA.PART_ID
WHERE
	W.TYPE = 'W'
	AND TransDate >= @StartDate
	AND TransDate <= @EndDate
	AND (W.STATUS = 'C' OR (W.STATUS IN ('R', 'X') AND LT.TRANSDATE IS NOT NULL))

union

SELECT 
	'Co-Product' AS Msg,
	W.BASE_ID,
	W.LOT_ID,
	W.SPLIT_ID,
	W.SUB_ID,
	W.[STATUS],
	CP.PART_ID as PartID, 
	'Co-Product' as ChildPart,
	CASE
		WHEN O2.WORKORDER_BASE_ID IS NULL  THEN 'No'
		ELSE 'Yes'
	END AS SHOTPEEN,
	CASE
		WHEN O3.WORKORDER_BASE_ID IS NULL  THEN 'No'
		ELSE 'Yes'
	END AS Penetrant,
	O.SEQUENCE_NO, 
	O.RESOURCE_ID, 
	O.OPERATION_TYPE, 
	TransDate,
	PSA.ALLOY,
	PSA.THICKNESS_VAL,
	PSA.LENGTH_VAL,
	PSA.WIDTH_VAL,
	PSA.SURFACE_AREA AS Each_Surf_Area,
	CP.[DESIRED_QTY],
	CP.DESIRED_QTY * ISNULL(PSA.SURFACE_AREA, 0) AS Total_Surf_Area
FROM	   
	CO_PRODUCT AS CP
INNER JOIN
	WORK_ORDER AS W
	ON  (CP.WORKORDER_TYPE = 'W')
	AND (CP.WORKORDER_BASE_ID = W.BASE_ID)
	AND (CP.WORKORDER_LOT_ID = W.LOT_ID)
	AND (CP.WORKORDER_SPLIT_ID = W.SPLIT_ID)
INNER JOIN 
	OPERATION O
	ON  W.TYPE = O.WORKORDER_TYPE
	AND W.BASE_ID = O.WORKORDER_BASE_ID
	AND W.LOT_ID = O.WORKORDER_LOT_ID
	AND W.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND W.SUB_ID = O.WORKORDER_SUB_ID
LEFT OUTER JOIN 
	(SELECT 
		O2.WORKORDER_TYPE,
		O2.WORKORDER_BASE_ID,
		O2.WORKORDER_LOT_ID,
		O2.WORKORDER_SPLIT_ID, 
		O2.WORKORDER_SUB_ID,
		MIN(O2.SEQUENCE_NO) AS SP_Seq_No
	FROM 
		OPERATION O2
	WHERE 
		O2.RESOURCE_ID IN ('AUB-MSP', 'AUB-SP', 'BAL-SP', 'MSP', 'SP')
	GROUP BY 
		O2.WORKORDER_TYPE,
		O2.WORKORDER_BASE_ID,
		O2.WORKORDER_LOT_ID,
		O2.WORKORDER_SPLIT_ID, 
		O2.WORKORDER_SUB_ID
	) AS O2
		ON  W.TYPE = O2.WORKORDER_TYPE
		AND W.BASE_ID  = O2.WORKORDER_BASE_ID
		AND W.LOT_ID = O2.WORKORDER_LOT_ID
		AND W.SPLIT_ID = O2.WORKORDER_SPLIT_ID
		AND W.SUB_ID = O2.WORKORDER_SUB_ID
LEFT OUTER JOIN 
	(SELECT 
		O3.WORKORDER_TYPE,
		O3.WORKORDER_BASE_ID,
		O3.WORKORDER_LOT_ID,
		O3.WORKORDER_SPLIT_ID, 
		O3.WORKORDER_SUB_ID,
		MIN(O3.SEQUENCE_NO) AS Pen_Seq_No
	FROM 
		OPERATION O3
	WHERE
		O3.RESOURCE_ID IN ('AUB-PEN', 'BAL-PEN', 'AUB-PENETCH', 'BAL-PENETCH')
	GROUP BY 
		O3.WORKORDER_TYPE,
		O3.WORKORDER_BASE_ID,
		O3.WORKORDER_LOT_ID,
		O3.WORKORDER_SPLIT_ID, 
		O3.WORKORDER_SUB_ID
	) AS O3
		ON  W.TYPE = O3.WORKORDER_TYPE
		AND W.BASE_ID = O3.WORKORDER_BASE_ID
		AND W.LOT_ID = O3.WORKORDER_LOT_ID
		AND W.SPLIT_ID = O3.WORKORDER_SPLIT_ID
		AND W.SUB_ID = O3.WORKORDER_SUB_ID
LEFT OUTER JOIN
	(SELECT
		LT.WORKORDER_TYPE,
		LT.WORKORDER_BASE_ID,
		LT.WORKORDER_LOT_ID,
		LT.WORKORDER_SPLIT_ID,
		LT.WORKORDER_SUB_ID,
		LT.OPERATION_SEQ_NO,
		MIN(LT.TRANSACTION_DATE) AS TransDate
	FROM	  
		LABOR_TICKET LT
	INNER JOIN 
		OPERATION O
		ON LT.WORKORDER_TYPE = O.WORKORDER_TYPE
		AND LT.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
		AND LT.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
		AND LT.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
		AND LT.WORKORDER_SUB_ID = O.WORKORDER_SUB_ID
		AND LT.OPERATION_SEQ_NO = O.SEQUENCE_NO
	GROUP BY 	   
		LT.WORKORDER_TYPE,
		LT.WORKORDER_BASE_ID,
		LT.WORKORDER_LOT_ID,
		LT.WORKORDER_SPLIT_ID,
		LT.WORKORDER_SUB_ID,
		LT.OPERATION_SEQ_NO
	) AS LT
	ON  O.WORKORDER_TYPE = LT.WORKORDER_TYPE
	AND O.WORKORDER_BASE_ID = LT.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = LT.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = LT.WORKORDER_SUB_ID
	AND O.SEQUENCE_NO = LT.OPERATION_SEQ_NO
INNER JOIN 
	LIVESUPPLEMENTAL.DBO.RESOURCEID_ASSIGNMENTS RA
	ON  RA.RESOURCE_ID = O.RESOURCE_ID
	AND RA.DEPT IN ('AUB-Tankline', 'BAL-Tankline', 'AUB-Penetrant', 'Bal-Penetrant', 'Clean', 'AUB-clean')
	AND RA.RESOURCE_ID NOT IN ('BAL-rack', 'BAL-takedown', 'BAL-unrack')
LEFT OUTER JOIN 
	SKILLS_PART_SURFACE_AREA AS PSA
	ON CP.PART_ID = PSA.PART_ID
WHERE
	W.TYPE = 'W'
	AND TransDate >= @StartDate
	AND TransDate <= @EndDate
	AND (W.STATUS = 'C' OR (W.STATUS IN ('R', 'X') AND LT.TRANSDATE IS NOT NULL))
ORDER BY 
	W.BASE_ID, 
	W.LOT_ID, 
	W.SPLIT_ID, 
	W.SUB_ID, 
	O.SEQUENCE_NO 


