USE LIVE
GO

SELECT CO.CUSTOMER_ID 
	, WO.PART_ID
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, MONTH(WO.CREATE_DATE) AS 'CREATE_MONTH'
	, YEAR(WO.CREATE_DATE) AS 'CREATE_YEAR'
	--,WO.CLOSE_DATE
	, SUM(LT.HOURS_WORKED) AS 'TOTAL HOURS CLOCKED'
FROM WORK_ORDER WO
INNER JOIN LABOR_TICKET LT
	ON LT.WORKORDER_BASE_ID = WO.BASE_ID
	AND LT.WORKORDER_LOT_ID = WO.LOT_ID
	AND LT.WORKORDER_SPLIT_ID = WO.SPLIT_ID
	AND LT.WORKORDER_SUB_ID = WO.SUB_ID
	AND LT.WORKORDER_TYPE = WO.[TYPE]
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
	AND DSL.SUPPLY_SUB_ID = WO.SUB_ID
LEFT OUTER JOIN CUST_ORDER_LINE COL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	--AND COL.LINE_NO = DSL.DEMAND_LOT_ID
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON CO.ID = COL.CUST_ORDER_ID
WHERE WO.CREATE_DATE >= '1/1/2020'
	AND CO.CUSTOMER_ID = 'BOE609'
GROUP BY CO.CUSTOMER_ID 
	, WO.PART_ID
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, MONTH(WO.CREATE_DATE)
	, YEAR(WO.CREATE_DATE)
ORDER BY WO.BASE_ID 
	, WO.LOT_ID 
	, YEAR(WO.CREATE_DATE)
	, MONTH(WO.CREATE_DATE)