USE DataWarehouse
GO

SELECT 'NEW ' AS COMPARECOL
	, EX.Reasoning AS BUS_STREAM
	, CO.ID
	, COL.PART_ID
	, P.PLANNER_USER_ID
	, P.BUYER_USER_ID
	, CO.ORDER_DATE AS DAYDATE
	, RIGHT('00' + CAST(MONTH(CO.ORDER_DATE) AS NVARCHAR(2)), 2) + '/' + RIGHT('00' + CAST(DAY(CO.ORDER_DATE) AS NVARCHAR(2)), 2) AS MMDD
FROM CUST_ORDER_LINE COL
INNER JOIN CUSTOMER_ORDER CO
ON CO.ID = COL.CUST_ORDER_ID
LEFT OUTER JOIN PART P
ON P.ID = COL.PART_ID
LEFT OUTER JOIN LIVESUPPLEMENTAL.DBO.PLANNER_USER_ID_ReportSettings EX	
ON P.PLANNER_USER_ID = EX.PLANNER_USER_ID	
AND REPORT_NAME = 'CMP Incoming V Outgoing Charts'
WHERE CO.CUSTOMER_ID = 'BOE609'
	AND CO.ORDER_DATE >= GETDATE()-28

UNION ALL

SELECT 'SHIP' AS COMPARECOL
	, EX.Reasoning AS BUS_STREAM
	, CO.ID
	, COL.PART_ID
	, P.PLANNER_USER_ID
	, P.BUYER_USER_ID
	, S.SHIPPED_DATE AS DAYDATE
	, RIGHT('00' + CAST(MONTH(S.SHIPPED_DATE) AS NVARCHAR(2)), 2) + '/' + RIGHT('00' + CAST(DAY(S.SHIPPED_DATE) AS NVARCHAR(2)), 2) AS MMDD
FROM CUST_ORDER_LINE COL
INNER JOIN CUSTOMER_ORDER CO
ON CO.ID = COL.CUST_ORDER_ID
INNER JOIN SHIPPER_LINE SL 
ON  COL.CUST_ORDER_ID = SL.CUST_ORDER_ID
AND COL.LINE_NO = SL.CUST_ORDER_LINE_NO 
AND SL.SHIPPED_QTY <> 0 
INNER JOIN SHIPPER S
ON S.PACKLIST_ID = SL.PACKLIST_ID 
LEFT OUTER JOIN PART P
ON P.ID = COL.PART_ID
LEFT OUTER JOIN LIVESUPPLEMENTAL.DBO.PLANNER_USER_ID_ReportSettings EX	
ON P.PLANNER_USER_ID = EX.PLANNER_USER_ID	
AND REPORT_NAME = 'CMP Incoming V Outgoing Charts'
WHERE CO.CUSTOMER_ID = 'BOE609'
AND S.SHIPPED_DATE >= GETDATE()- 28

