USE LIVE
GO

/*
We are needing a report for Finish Only CMP (Skills did not manufacture) part numbers from the last year with the following:
-	Part Number
-	Work Order
-	Order Date
-	Complete Date
-	Quantity
-	Time & Cost for the following:
o	Total (time & cost to process)
o	Penetrant
o	Shot Peen
o	Chemical Processing
o	Masking
o	Primer
o	Topcoat
o	Takedown
o	Quality
o	Packaging
*/

WITH CTE_BASE AS
(SELECT CO.CUSTOMER_ID
, CO.ID
, COL.LINE_NO AS COL_LINE
, COL.PART_ID
, CO.ORDER_DATE
, WO.CLOSE_DATE
, WO.BASE_ID
, WO.LOT_ID
, WO.SPLIT_ID
, WO.SUB_ID
, WO.DESIRED_QTY
FROM LIVE.dbo.CUSTOMER_ORDER CO
INNER JOIN LIVE.dbo.CUST_ORDER_LINE COL
	ON CO.ID = COL.CUST_ORDER_ID
LEFT OUTER JOIN LIVE.dbo.PART P
	ON COL.PART_ID = P.ID
	AND P.PLANNER_USER_ID IN ('FIN', 'FIN-HOURLY')
LEFT OUTER JOIN LIVE.dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
LEFT OUTER JOIN LIVE.dbo.WORK_ORDER WO
    ON DSL.SUPPLY_TYPE = 'WO' 
    AND DSL.SUPPLY_BASE_ID = WO.BASE_ID
    AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
    AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
    AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
	AND WO.[TYPE] = 'W'
WHERE CO.CUSTOMER_ID = 'BOE609'
AND WO.CLOSE_DATE >= GETDATE() - 365
AND WO.[STATUS] = 'C'
)
SELECT * FROM CTE_BASE

, CTE_BASE2 AS 
(SELECT CUSTOMER_ID
, CO_ID
, COL_LINE
, PART_ID
, ORDER_DATE
, CLOSE_DATE
, BASE_ID
, LOT_ID
, SPLIT_ID
, SUB_ID
, DESIRED_QTY
, DEPARTMENT
, SUM(TOTAL_HOURS) AS TOTAL_HOURS
, SUM(TOTAL_COST) AS TOTAL_COST
FROM
(SELECT CUSTOMER_ID
, CTE.ID AS CO_ID
, COL_LINE
, PART_ID
, ORDER_DATE
, CTE.CLOSE_DATE
, BASE_ID
, LOT_ID
, SPLIT_ID
, SUB_ID
, DESIRED_QTY
, O.SEQUENCE_NO
, O.RESOURCE_ID
, SR.USER_6 AS DEPT
, SR.USER_7 AS PROCESS
, CASE
	WHEN SR.USER_6 IN ('CHEMICAL PROCESSING', 'PENETRANT', 'SHOT PEEN', 'MASKING', 'TAKEDOWN', 'PACKAGING') THEN SR.USER_6
	WHEN SR.USER_6 = 'INSPECTION' THEN 'QUALITY'
	WHEN SR.USER_6 = 'PAINT' AND SR.USER_7 = 'PRIMER' THEN 'PRIMER' 
	WHEN SR.USER_6 = 'PAINT' AND SR.USER_7 = 'TOPCOAT' THEN 'TOPCOAT'
	ELSE ''
END AS DEPARTMENT
, O.[ACT_SETUP_HRS] + O.[ACT_RUN_HRS] AS TOTAL_HOURS
, O.[ACT_ATL_LAB_COST] + O.[ACT_ATL_BUR_COST] + O.[ACT_ATL_SER_COST] AS TOTAL_COST
FROM CTE_BASE CTE
LEFT OUTER JOIN OPERATION O
ON O.WORKORDER_TYPE = 'W'
AND O.WORKORDER_BASE_ID = CTE.BASE_ID
AND O.WORKORDER_LOT_ID = CTE.LOT_ID
AND O.WORKORDER_SPLIT_ID = CTE.SPLIT_ID
AND O.WORKORDER_SUB_ID = CTE.SUB_ID 
LEFT OUTER JOIN SHOP_RESOURCE SR
ON SR.ID = O.RESOURCE_ID
WHERE 
(SR.USER_6 IN ('CHEMICAL PROCESSING', 'INSPECTION', 'MASKING', 'PACKAGING', 'PAINT', 'PENETRANT', 'SHOT PEEN', 'TAKEDOWN')
	OR SR.USER_7 IN ('MASKING', 'PACKAGING', 'PENETRANT', 'PRIMER', 'TAKEDOWN', 'TOPCOAT')
)
AND SR.USER_6 != 'CARGO'
) X
WHERE DEPARTMENT != ''
GROUP BY CUSTOMER_ID
, CO_ID
, COL_LINE
, PART_ID
, ORDER_DATE
, CLOSE_DATE
, BASE_ID
, LOT_ID
, SPLIT_ID
, SUB_ID
, DESIRED_QTY
, DEPARTMENT
)
SELECT * FROM CTE_BASE2

SELECT BASE_ID
, PART_ID
, [CHEMICAL PROCESSING], [MASKING], [PACKAGING], [PENETRANT], [PRIMER], [QUALITY], [SHOT PEEN], [TAKEDOWN], [TOPCOAT]
FROM CTE_BASE2
PIVOT
(
SUM(TOTAL_HOURS)
FOR DEPARTMENT IN ([CHEMICAL PROCESSING], [MASKING], [PACKAGING], [PENETRANT], [PRIMER], [QUALITY], [SHOT PEEN], [TAKEDOWN], [TOPCOAT])
) AS PIVOTED

/*
CARGO-MASKING
CHEMICAL PROCESSING-BORIC
CHEMICAL PROCESSING-CHEMICAL CONVERSION
CHEMICAL PROCESSING-CHROMIC
CHEMICAL PROCESSING-CLEAN
CHEMICAL PROCESSING-POLISH
CHEMICAL PROCESSING-RACK
CHEMICAL PROCESSING-SOL GEL
CHEMICAL PROCESSING-STRIP
CHEMICAL PROCESSING-SULFURIC
CHEMICAL PROCESSING-UNRACK
CMP-PACKAGING
CMP-TAKEDOWN
MASKING-MASKING
PACKAGING-BOEING
PACKAGING-PACKAGING
PACKAGING-SHIPPING
PAINT-OVEN
PAINT-PRIMER
PAINT-SANDING
PAINT-SETUP
PAINT-TOPCOAT
PENETRANT-CLEAN
PENETRANT-MASKING
PENETRANT-PENETRANT
SHOT PEEN-AUTO SHOT
SHOT PEEN-BLASTING
SHOT PEEN-MANUAL SHOT
TAKEDOWN-TAKEDOWN

*/