USE DataWarehouse
GO

SET DATEFIRST 1

SELECT SHIPWEEK
, BUS_UNIT
--, COUNT(*)
, AVG([FLOW DAYS])
FROM (
SELECT CO.CUSTOMER_ID
	, CO.ID AS COID
	, WO.BASE_ID AS WO
	, COL.ORDER_QTY
	, WO.PART_ID 
	, P.[DESCRIPTION]
	, CO.ORDER_DATE
	, WO.DESIRED_WANT_DATE
	, DATEDIFF(DAY, CO.ORDER_DATE, WO.DESIRED_WANT_DATE) AS [ACT LT]
	, S.SHIPPED_DATE
	, DATEDIFF(DAY, CO.ORDER_DATE, S.SHIPPED_DATE) - 1  AS [FLOW DAYS]
	, CASE
		WHEN LEFT(P.BUYER_USER_ID, 2) = '09' THEN 'MFG'
--		WHEN LEFT(P.BUYER_USER_ID, 2) = '59' THEN 'FIN'
		ELSE 'FIN'
	END AS [BUS_UNIT]
	, P.BUYER_USER_ID
	, DATEADD(DAY, 7 - DATEPART(WEEKDAY, S.SHIPPED_DATE), S.SHIPPED_DATE) AS [SHIPWEEK]
FROM SHIPPER S
INNER JOIN SHIPPER_LINE SL
	ON SL.PACKLIST_ID = S.PACKLIST_ID
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN [DEMAND_SUPPLY_LINK] DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
LEFT OUTER JOIN WORK_ORDER WO
	ON DSL.[SUPPLY_TYPE] = 'WO'
	AND DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
	AND DSL.SUPPLY_SUB_ID = WO.SUB_ID
	AND WO.[TYPE] = 'W'
LEFT OUTER JOIN PART P
	ON P.ID = WO.PART_ID
WHERE S.SHIPPED_DATE >= '1/1/2020'
	AND CO.CUSTOMER_ID = 'BOE609'
) X
GROUP BY SHIPWEEK
, BUS_UNIT
ORDER BY SHIPWEEK
, BUS_UNIT