USE LIVE
GO

DECLARE @STARTDATE DATE = '1/25/2021'

; WITH CTE_START AS
(SELECT CO.ID AS COID
, CO.CUSTOMER_ID
, CO.CREATE_DATE
, WO.BASE_ID
, WO.LOT_ID
, WO.SPLIT_ID
, WO.SUB_ID
, CASE 
	WHEN CB.[USER_ID] = 'IMELDAE#' THEN 'P1' 
	WHEN CB.[USER_ID] = 'JOEM#' THEN 'P1' 
	WHEN LEFT(EE.DEPARTMENT_ID, 3) = '300' THEN 'P1' 
	WHEN LEFT(EE.DEPARTMENT_ID, 3) = '100' THEN 'P2' 
	WHEN LEFT(EE.DEPARTMENT_ID, 3) = '700' THEN 'P3' 
	WHEN LEFT(EE.DEPARTMENT_ID, 3) = '400' THEN 'P3' 
	WHEN LEFT(EE.DEPARTMENT_ID, 3) = '960' THEN 'P1' 
	ELSE 'OTHER'
END AS FACILITY
, (SELECT MIN(CLOCK_IN) 
	FROM LABOR_TICKET LT
	WHERE LT.WORKORDER_TYPE = WO.[TYPE]
	AND LT.WORKORDER_BASE_ID = WO.BASE_ID
	AND LT.WORKORDER_LOT_ID = WO.LOT_ID
	AND LT.WORKORDER_SPLIT_ID = WO.SPLIT_ID
	AND LT.WORKORDER_SUB_ID = WO.SUB_ID
) AS [1ST_LT]
, (SELECT MAX(CLOSE_DATE) 
	FROM OPERATION REV
	WHERE REV.WORKORDER_TYPE = WO.[TYPE]
	AND REV.WORKORDER_BASE_ID = WO.BASE_ID
	AND REV.WORKORDER_LOT_ID = WO.LOT_ID
	AND REV.WORKORDER_SPLIT_ID = WO.SPLIT_ID
	AND REV.WORKORDER_SUB_ID = WO.SUB_ID
	AND REV.RESOURCE_ID IN ('B1F1-REVIEW', 'P1F1-REVIEW', 'P1F1-REVIEWCM', 'P1F2-REVIEWCM', 'P1M1-CP-REVIEW', 'P2M1-REVIEW', 'P2M1-REVIEWCM', 'P2M1-REVIEW-CMP', 'P2M2-REVIEWCM', 'P3M1-BS-REVIEW', 'review')
) AS REV_OP_CLOSE_DATE
FROM CUSTOMER_ORDER CO
LEFT OUTER JOIN CUSTOMER_BOOKINGS CB
	ON CO.ID = CB.CUST_ORDER_ID
LEFT OUTER JOIN EMPLOYEE EE
	ON CB.[USER_ID] = EE.[USER_ID] + '#'
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.[DEMAND_TYPE] = 'CO'
	AND DSL.DEMAND_BASE_ID = CO.ID
LEFT OUTER JOIN WORK_ORDER WO
	ON DSL.[SUPPLY_TYPE] = 'WO'
	AND WO.[TYPE] = 'W'
	AND DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
	AND DSL.SUPPLY_SUB_ID = WO.SUB_ID
WHERE CO.CREATE_DATE >= @STARTDATE 
)

, CTE_CALC AS
(SELECT * 
, CAST(CREATE_DATE AS DATE) AS CO_DATE
, CASE
	WHEN CUSTOMER_ID = 'BOE609' THEN 'CMP'
	ELSE 'OTHER'
END AS CUSTOMER
, DATEDIFF(MINUTE, CREATE_DATE, [1ST_LT]) AS [FIRST STARTED]
, DATEDIFF(HOUR, CREATE_DATE, REV_OP_CLOSE_DATE) AS [REVIEW_CLOSE_HOURS]
, DATEDIFF(DAY, CREATE_DATE, REV_OP_CLOSE_DATE) AS [REVIEW_CLOSE_DAYS]
FROM CTE_START
)
SELECT * FROM CTE_CALC

SELECT FACILITY
, CUSTOMER
, CO_DATE
, COUNT(COID) AS COID_COUNT
, AVG([FIRST STARTED]) AS AVG_STARTED_MINS
, AVG([REVIEW_CLOSE_HOURS]) AS AVG_REVIEW_HOURS
, AVG([REVIEW_CLOSE_DAYS]) AS AVG_REVIEW_DAYS
FROM CTE_CALC
GROUP BY FACILITY
, CUSTOMER
, CO_DATE
ORDER BY CO_DATE
, FACILITY
, CUSTOMER

