USE LIVE
GO

DECLARE @TIMEFRAME NVARCHAR(15) = 'LAST MONTH'
, @STARTDATE DATE = '1/1/2021'
, @ENDDATE DATE = '2/1/2021'
, @LISTTYPE NVARCHAR(15) = ''
, @BUSUNIT NVARCHAR(50) = ''
, @FACILITY NVARCHAR(50) = ''
, @PROCESS NVARCHAR(50) = ''
, @DEPARTMENT NVARCHAR(50) = ''
, @RESOURCEID NVARCHAR(50) = ''
, @SUPERVISOR NVARCHAR(50) = 'Keith Wooldridge'
;

SET DATEFIRST 1;

WITH CTE_COS AS
(SELECT CO.CUSTOMER_ID
, CO.ID AS COID
, CO.ORDER_DATE
, CO.CREATE_DATE
, CB.BOOK_DATE
, CB.[USER_ID]
, CASE 
	WHEN CB.[USER_ID] = 'IMELDAE#' THEN 'P1' 
	WHEN CB.[USER_ID] = 'JOEM#' THEN 'P1' 
	WHEN LEFT(EE.DEPARTMENT_ID, 3) = '300' THEN 'P1' 
	WHEN LEFT(EE.DEPARTMENT_ID, 3) = '100' THEN 'P2' 
	WHEN LEFT(EE.DEPARTMENT_ID, 3) = '700' THEN 'P3' 
	WHEN LEFT(EE.DEPARTMENT_ID, 3) = '400' THEN 'P3' 
	WHEN LEFT(EE.DEPARTMENT_ID, 3) = '960' THEN 'P1' 
	ELSE 'OTHER'
END AS FACILITY
FROM CUSTOMER_ORDER CO
LEFT OUTER JOIN CUSTOMER_BOOKINGS CB
ON CO.ID = CB.CUST_ORDER_ID
LEFT OUTER JOIN EMPLOYEE EE
ON CB.[USER_ID] = EE.[USER_ID] + '#'
WHERE CO.ORDER_DATE >= @STARTDATE
AND CO.ORDER_DATE < @ENDDATE
--AND CUSTOMER_ID = 'BOE609'
)
--SELECT * FROM CTE_COS

SELECT * FROM 
(SELECT FACILITY, COID, CUSTOMER_ID, ORDER_DATE
FROM CTE_COS
) T
PIVOT (
	COUNT(COID)
	FOR FACILITY IN ([P1],[P2],[P3],[OTHER])
) AS PIVOT_TABLE
ORDER BY CUSTOMER_ID, ORDER_DATE