use DataWarehouse
go

--> VISUAL ENTERPRISE > SHIPPING REPORTS > CUST_ORDER_TO_WO DATASET
DECLARE @StartDate DATE = '1/1/'+CAST(YEAR(GETDATE())-1 AS NVARCHAR(4)); 

SELECT *
FROM OPERATION O
LEFT OUTER JOIN LABOR_TICKET LT
	ON LT.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
	AND LT.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
	AND LT.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND LT.WORKORDER_SUB_ID = O.WORKORDER_SUB_ID
	AND LT.WORKORDER_TYPE = O.WORKORDER_TYPE
	AND LT.OPERATION_SEQ_NO = O.SEQUENCE_NO
LEFT OUTER JOIN WORK_ORDER WO
	ON WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O.WORKORDER_SUB_ID
	AND WO.[TYPE] = O.WORKORDER_TYPE
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.SUPPLY_TYPE = 'WO' 
	AND DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
	AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
LEFT OUTER JOIN CUST_ORDER_LINE COL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID 
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON CO.ID = COL.CUST_ORDER_ID
LEFT OUTER JOIN PART P
	ON WO.PART_ID = P.ID
WHERE ISNULL(COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) >= '6/1/2018'
--WHERE ISNULL(COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) >= @StartDate
	AND CO.[STATUS] IN ('H', 'R', 'C')


/*

WO - [ROWID], [TYPE], [BASE_ID], [LOT_ID], [SPLIT_ID], [SUB_ID], [PART_ID], [GLOBAL_RANK], [DESIRED_QTY], [RECEIVED_QTY], [CREATE_DATE], [DESIRED_RLS_DATE], [DESIRED_WANT_DATE], [CLOSE_DATE], [COSTED_DATE], [STATUS], [COPY_FROM_SPLIT_ID], [ENGINEERED_BY], [ENGINEERED_DATE], [DRAWING_ID], [DRAWING_REV_NO], [PRODUCT_CODE], [COMMODITY_CODE], [FORWARD_SCHEDULE], [POSTING_CANDIDATE], [MAT_GL_ACCT_ID], [LAB_GL_ACCT_ID], [BUR_GL_ACCT_ID], [SER_GL_ACCT_ID], [VARIABLE_TABLE], [SCHEDULE_GROUP_ID], [SCHED_START_DATE], [SCHED_FINISH_DATE], [COULD_FINISH_DATE], [EST_MATERIAL_COST], [EST_LABOR_COST], [EST_BURDEN_COST], [EST_SERVICE_COST], [ACT_MATERIAL_COST], [ACT_LABOR_COST], [ACT_BURDEN_COST], [ACT_SERVICE_COST], [REM_MATERIAL_COST], [REM_LABOR_COST], [REM_BURDEN_COST], [REM_SERVICE_COST], [MARKED_FOR_PURGE], [PRINTED_DATE], [DRAWING_FILE], [WAREHOUSE_ID], [WIP_VAS_REQUIRED], [ALLOCATED_QTY], [FULFILLED_QTY], [DEF_LBL_FORMAT_ID], [HARD_RELEASE_DATE], [USER_1], [USER_2], [USER_3], [USER_4], [USER_5], [USER_6], [USER_7], [USER_8], [USER_9], [USER_10], [UDF_LAYOUT_ID], [DBR_TYPE], [DBR_PRIORITY], [DBR_CODE], [WBS_CODE], [WBS_PROJECT], [WBS_CUST_ORDER_ID], [MILESTONE_SEQ_NO], [MILESTONE_SUB_ID], [ECN_REVISION], [EDI_BLANKET_FLAG], [DISPATCHED], [ORIG_STAGE_REVISION_ID], [STATUS_EFF_DATE], [ALLOW_ALT_PARTS], [ALLOW_UPD_FROM_MST], [ALLOW_UPD_FROM_LEG], [UPDATE_FROM_REF], [UPDATE_USER_ID], [UPDATE_ENG_MASTER], [UPDATE_DATE], [SITE_ID], [PROD_ORDER_TYPE], [PLANNER_ID], [INACTIVE]
LT - [ROWID], [TRANSACTION_ID], [WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [OPERATION_SEQ_NO], [TYPE], [SETUP_COMPLETED], [EMPLOYEE_ID], [DEPARTMENT_ID], [RESOURCE_ID], [HOURLY_COST], [CLOCK_IN], [CLOCK_OUT], [HOURS_WORKED], [HOURS_BREAK], [MULTIPLIER_1], [MULTIPLIER_2], [GOOD_QTY], [BAD_QTY], [TRANSACTION_DATE], [DESCRIPTION], [USER_ID], [BURDEN_PER_HR], [BURDEN_PERCENT], [BUR_PER_OPERATION], [POSTING_CANDIDATE], [HOURS_OVERALL], [HOURS_PREVIOUS], [INDIRECT_CODE], [INDIRECT_ID], [SHIFT_DATE], [BREAK_CLOCKIN], [HOURS_BREAK_IND], [ACT_LABOR_COST], [ACT_BURDEN_COST], [CREATE_DATE], [ACT_CLOCK_IN], [ACT_CLOCK_OUT], [STARTING_TRANS], [BURDEN_PER_UNIT], [UNIT_COST], [GL_ACCT_ID], [EARNING_CODE_ID], [BUDGET_ACCT_YEAR], [BUDGET_ACCT_PERIOD], [MILESTONE_TXN_ID], [MILESTONE_UPDATED], [COST_CATEGORY_ID], [AUTOGEN_TXN_ID], [UNADJ_CLOCK_IN], [UNADJ_CLOCK_OUT], [DEVIATION_ID], [DATA_COLL_COMP], [PRD_INSP_PLAN_ID], [ACT_RATE_ID], [ACT_PERIOD_ID], [RETRO_RATE_ID], [RETRO_PERIOD_ID], [RETRO_RATE_CODE], [SITE_ID]
O - [ROWID], [WORKORDER_TYPE], [WORKORDER_BASE_ID], [WORKORDER_LOT_ID], [WORKORDER_SPLIT_ID], [WORKORDER_SUB_ID], [SEQUENCE_NO], [RESOURCE_ID], [SETUP_HRS], [RUN], [RUN_TYPE], [LOAD_SIZE_QTY], [RUN_HRS], [MOVE_HRS], [TRANSIT_DAYS], [SERVICE_ID], [SCRAP_YIELD_PCT], [SCRAP_YIELD_TYPE], [FIXED_SCRAP_UNITS], [MINIMUM_MOVE_QTY], [CALC_START_QTY], [CALC_END_QTY], [COMPLETED_QTY], [DEVIATED_QTY], [ACT_SETUP_HRS], [ACT_RUN_HRS], [STATUS], [SETUP_COMPLETED], [SERVICE_BEGIN_DATE], [CLOSE_DATE], [OPERATION_TYPE], [DRAWING_ID], [DRAWING_REV_NO], [OVERRIDE_QTYS], [BEGIN_TRACEABILITY], [CAPACITY_USAGE_MAX], [CAPACITY_USAGE_MIN], [TEST_ID], [SPC_QTY], [SCHED_START_DATE], [SCHED_FINISH_DATE], [COULD_FINISH_DATE], [ISDETERMINANT], [SETUP_COST_PER_HR], [RUN_COST_PER_HR], [RUN_COST_PER_UNIT], [BUR_PER_HR_SETUP], [BUR_PER_HR_RUN], [BUR_PER_UNIT_RUN], [SERVICE_BASE_CHG], [BUR_PERCENT_SETUP], [BUR_PERCENT_RUN], [BUR_PER_OPERATION], [EST_ATL_LAB_COST], [EST_ATL_BUR_COST], [EST_ATL_SER_COST], [REM_ATL_LAB_COST], [REM_ATL_BUR_COST], [REM_ATL_SER_COST], [ACT_ATL_LAB_COST], [ACT_ATL_BUR_COST], [ACT_ATL_SER_COST], [EST_TTL_MAT_COST], [EST_TTL_LAB_COST], [EST_TTL_BUR_COST], [EST_TTL_SER_COST], [REM_TTL_MAT_COST], [REM_TTL_LAB_COST], [REM_TTL_BUR_COST], [REM_TTL_SER_COST], [ACT_TTL_MAT_COST], [ACT_TTL_LAB_COST], [ACT_TTL_BUR_COST], [ACT_TTL_SER_COST], [SPLIT_ADJUSTMENT], [MILESTONE_ID], [SCHEDULE_TYPE], [MIN_SEGMENT_SIZE], [PROTECT_COST], [DRAWING_FILE], [DISPATCHED_QTY], [SERVICE_MIN_CHG], [VENDOR_ID], [VENDOR_SERVICE_ID], [SERVICE_PART_ID], [LAST_DISP_DATE], [LAST_RECV_DATE], [WAREHOUSE_ID], [ALLOCATED_QTY], [FULFILLED_QTY], [LEAST_MIN_MOVE_QTY], [MAX_GAP_PREV_OP], [APPLY_CALENDAR], [MAX_DOWNTIME], [ACCUM_DOWNTIME], [RUN_QTY_PER_CYCLE], [USER_1], [USER_2], [USER_3], [USER_4], [USER_5], [USER_6], [USER_7], [USER_8], [USER_9], [USER_10], [UDF_LAYOUT_ID], [NUM_MEM_TO_SCHED], [SERVICE_BUFFER], [MILESTONE_SUB_ID], [POST_MILESTONE], [PROJ_MILESTONE_OP], [WBS_CODE], [WBS_START_DATE], [WBS_END_DATE], [WBS_DURATION], [MILESTONE_SEQ_NO], [PRD_INSP_PLAN_ID], [SETUP_INSPECT_REQ], [RUN_INSPECT_REQ], [STATUS_EFF_DATE], [PRED_SUB_ID], [PRED_SEQ_NO], [SITE_ID], [SCHED_CAPACITY_USAGE], [BID_RATE_CATEGORY_ID]
OT - [ROWID], [ID], [DESCRIPTION], [RESOURCE_ID], [SETUP_HRS], [RUN], [RUN_TYPE], [LOAD_SIZE_QTY], [MOVE_HRS], [SERVICE_ID], [TRANSIT_DAYS], [SCRAP_YIELD_PCT], [SCRAP_YIELD_TYPE], [FIXED_SCRAP_UNITS], [MINIMUM_MOVE_QTY], [CALC_START_QTY], [CALC_END_QTY], [OVERRIDE_QTYS], [BEGIN_TRACEABILITY], [TEST_ID], [SETUP_COST_PER_HR], [RUN_COST_PER_HR], [BUR_PER_HR_SETUP], [BUR_PER_HR_RUN], [SERVICE_BASE_CHG], [BUR_PERCENT_SETUP], [BUR_PERCENT_RUN], [BUR_PER_OPERATION], [CAPACITY_USAGE_MAX], [CAPACITY_USAGE_MIN], [SCHEDULE_TYPE], [MIN_SEGMENT_SIZE], [SERVICE_MIN_CHG], [VENDOR_ID], [VENDOR_SERVICE_ID], [SERVICE_PART_ID], [BUR_PER_UNIT_RUN], [RUN_COST_PER_UNIT], [SITE_ID]
DSL - 

*/