USE LIVE
GO 

--SELECT COMMODITY_CODE, COUNT(*) FROM PART GROUP BY COMMODITY_CODE ORDER BY COMMODITY_CODE

SELECT P.ID AS PART_ID
, P.DESCRIPTION
, P.COMMODITY_CODE
, P.STATUS
, UNIT_LABOR_COST
, UNIT_MATERIAL_COST
, UNIT_SERVICE_COST
, UNIT_BURDEN_COST   
INTO #T1
FROM PART P
INNER JOIN PART_SITE PS
ON P.ID = PS.PART_ID
WHERE COMMODITY_CODE IN ('Adhesives', 'Gen-Controlled', 'CFM-Details', 'CFM-Standards', 'CFM-Raw Matl')
AND (P.STATUS IS NULL OR P.STATUS != 'O')
AND UNIT_LABOR_COST + UNIT_MATERIAL_COST + UNIT_SERVICE_COST + UNIT_BURDEN_COST != 0

--> PER MONICAD 12/16/2021
BEGIN TRANSACTION;
UPDATE PART_SITE 
SET UNIT_LABOR_COST = 0
, UNIT_MATERIAL_COST = 0
, UNIT_SERVICE_COST = 0
, UNIT_BURDEN_COST = 0 
FROM PART_SITE PS
INNER JOIN PART P
ON P.ID = PS.PART_ID
WHERE P.COMMODITY_CODE IN ('Adhesives', 'Gen-Controlled', 'CFM-Details', 'CFM-Standards', 'CFM-Raw Matl')
	AND (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
	AND PS.UNIT_LABOR_COST + PS.UNIT_MATERIAL_COST + PS.UNIT_SERVICE_COST + PS.UNIT_BURDEN_COST != 0
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;