USE DataWarehouse
GO

DROP TABLE #T1

DECLARE @STARTDATE DATE = '1/1/2020'
, @ENDDATE DATE = GETDATE()
--> VISUAL ENTERPRISE > WORK ORDER REPORTS > COMMBOARD CORE
SET DATEFIRST 1;

SELECT O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.OPERATION_TYPE
	, O.CLOSE_DATE AS OP_CLOSE_DATE
	, O.[STATUS] AS OP_STATUS
	, O.ACT_SETUP_HRS
	, O.ACT_RUN_HRS
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.DESIRED_RLS_DATE AS WO_DESIRED_RLS_DATE
	, WO.DESIRED_WANT_DATE AS WO_DESIRED_WANT_DATE
	, WO.PRINTED_DATE AS WO_PRINTED_DATE
	, WO.CLOSE_DATE AS WO_CLOSE_DATE
	, WO.ENGINEERED_BY
	, WO.DESIRED_QTY AS WO_DESIRED_QTY
 	, SR.USER_1 AS BUSUNIT
	, CASE
		WHEN SR.USER_1 = 'A' THEN 'FIN'
		WHEN SR.USER_1 = 'M' THEN 'MFG'
		WHEN SR.USER_1 = 'O' THEN 'OUTREACH'
		WHEN SR.USER_1 = 'B' THEN 'BALLARD'
		WHEN SR.USER_1 = 'C' THEN 'CLOSED'
		ELSE '_Blank'
	END AS BUSINESS_UNIT
	, SR.USER_2 AS [PRIMARY]
	, SR.USER_3 AS [SECONDARY]
	, SR.USER_4 AS [SUPERVISOR]
	, SR.USER_5 AS [FACILITY]
	, SR.USER_7 AS [PROCESS]
	, SR.USER_8 AS [DEPARTMENT]
	, NCM.NCM_ID
	, NCM.NCM_DATE
	, IIF(ISNULL(NCM.NCM_ID, '_BLANK') = '_BLANK', NULL, COALESCE(NCM.SK_FIN_NCM_PROCESS, NCM.SK_MFG_NCM_PROCESS, '_BLANK')) AS [IQM_PROCESS]
	, IIF(ISNULL(NCM.NCM_ID, '_BLANK') = '_BLANK', NULL, COALESCE(NCM.SK_FIN_NCM_SUBPROCESS, NCM.SK_MFG_NCM_SUBPROCESS, '_BLANK')) AS [IQM_SUBPROCESS]
	, IIF(ISNULL(NCM.NCM_ID, '_BLANK') = '_BLANK', NULL, COALESCE(NCM.USER_DEFINED_4, NCM.USER_DEFINED_7, '_BLANK')) AS [IQM_DEFECT]
	, NCM.DISPOSITION_TYPE
	, NCM.NCM_TYPE
	, WO.PART_ID
	, P.PLANNER_USER_ID
	, P.COMMODITY_CODE
	, P.BUYER_USER_ID
	, P.FABRICATED
	, P.PURCHASED
	, P.STOCKED
	, P.TOOL_OR_FIXTURE
	, P.[STATUS] AS PART_STATUS
	, CO.ID AS CO_ID
	, COL.LINE_NO AS CO_LINE_NO
	, CO.CUSTOMER_ID
	, CO.ORDER_DATE AS CO_ORDER_DATE
	, CO.[STATUS] AS CO_STATUS
	, CO.CUSTOMER_PO_REF
	, ISNULL(COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) AS CO_DESIRED_SHIP_DATE
	, COL.ORDER_QTY
INTO #T1
FROM DATAWAREHOUSE.DBO.OPERATION O
LEFT OUTER JOIN DATAWAREHOUSE.DBO.SHOP_RESOURCE_SITE SR
	ON SR.RESOURCE_ID = O.RESOURCE_ID
LEFT OUTER JOIN WORK_ORDER WO
	ON WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O.WORKORDER_SUB_ID
	AND WO.[TYPE] = O.WORKORDER_TYPE
LEFT OUTER JOIN PART P
	ON WO.PART_ID = P.ID
LEFT OUTER JOIN DATAWAREHOUSE.DBO.VQ_PRODUCTION_ORDER PO
	ON PO.[ALT_ID_2] = O.WORKORDER_BASE_ID
	AND PO.[ALT_ID_3] = O.WORKORDER_LOT_ID
	AND PO.[ALT_ID_4] = O.WORKORDER_SPLIT_ID
	AND PO.[ALT_ID_5] = O.WORKORDER_SUB_ID
	AND PO.[ALT_ID_1] = O.WORKORDER_TYPE
LEFT OUTER JOIN DATAWAREHOUSE.DBO.VQ_OPERATION IO
	ON IO.[ID] = CAST(O.WORKORDER_TYPE AS NVARCHAR(1)) + '~' + CAST(O.WORKORDER_BASE_ID AS NVARCHAR(7)) + '~' 
		+ CAST(O.WORKORDER_LOT_ID AS NVARCHAR(1)) + '~' + CAST(O.WORKORDER_SPLIT_ID AS NVARCHAR(1)) + '~' 
		+ CAST(O.WORKORDER_SUB_ID AS NVARCHAR(1)) + '~' + CAST(O.SEQUENCE_NO AS NVARCHAR(5))
LEFT OUTER JOIN DATAWAREHOUSE.DBO.VQ_NONCONFORMANCE NCM
	ON PO.RECORD_ID = NCM.PROD_ORDER_REC_ID
	AND IO.RECORD_ID = NCM.OPERATION_REC_ID
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON WO.BASE_ID = DSL.SUPPLY_BASE_ID
	AND WO.LOT_ID = DSL.SUPPLY_LOT_ID
	AND WO.SPLIT_ID = DSL.SUPPLY_SPLIT_ID
	AND WO.SUB_ID = DSL.SUPPLY_SUB_ID
	AND WO.[TYPE] = 'W'
	AND DSL.SUPPLY_TYPE = 'WO'
LEFT OUTER JOIN CUST_ORDER_LINE COL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
	AND DSL.DEMAND_TYPE = 'CO'
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON CO.ID = COL.CUST_ORDER_ID
WHERE (O.CLOSE_DATE >= @STARTDATE AND O.CLOSE_DATE <= @ENDDATE)

