use datamart
go

DECLARE @Facility NVARCHAR(5) = ''
, @Process NVARCHAR(20) = ''
, @Department NVARCHAR(20) = ''
, @BusinessUnit NVARCHAR(10) = ''
, @Primary NVARCHAR(20) = ''
, @Secondary NVARCHAR(20) = ''
, @Supervisor NVARCHAR(30) = ''
, @ResourceID NVARCHAR(30) = ''
, @StartDate Date = '11/4/2019'
, @EndDate Date = '11/10/2019'

--Visual Enterprise Reports>Work Order Reports>Completed Operations

SELECT O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.WORKORDER_TYPE
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.OPERATION_TYPE
	, O.CLOSE_DATE
	, SR.USER_2 AS [PRIMARY]
	, SR.USER_3 AS [SECONDARY]
	, SR.USER_4 AS [SUPERVISOR]
	, SR.USER_5 AS [FACILITY]
	, SR.USER_7 AS [PROCESS]
	, SR.USER_8 AS [REPTGROUP]
	, CASE
		WHEN SR.USER_1 = 'A' THEN 'FIN'
		WHEN SR.USER_1 = 'M' THEN 'MFG'
		WHEN SR.USER_1 = 'O' THEN 'OUTREACH'
		WHEN SR.USER_1 = 'B' THEN 'BALLARD'
		WHEN SR.USER_1 = 'C' THEN 'CLOSED'
	END AS [BUSINESS_UNIT]
FROM DataWarehouse.dbo.OPERATION O
LEFT OUTER JOIN DataWarehouse.dbo.SHOP_RESOURCE_SITE SR
	ON O.RESOURCE_ID = SR.RESOURCE_ID
WHERE O.CLOSE_DATE >= @StartDate
	AND O.CLOSE_DATE <= @EndDate
	AND CASE
		WHEN SR.USER_1 = 'A' THEN 'FIN'
		WHEN SR.USER_1 = 'M' THEN 'MFG'
		WHEN SR.USER_1 = 'O' THEN 'OUTREACH'
		WHEN SR.USER_1 = 'B' THEN 'BALLARD'
		WHEN SR.USER_1 = 'C' THEN 'CLOSED'
	END IN (@BusinessUnit)
	AND SR.USER_2 IN (@Primary)
	AND SR.USER_3 IN (@Secondary)
	AND SR.USER_4 IN (@Supervisor)
	AND SR.USER_5 IN (@Facility)
	AND SR.USER_7 IN (@Process)
	AND SR.USER_8 IN (@Department)
	AND O.RESOURCE_ID IN (@ResourceID)
