USE DataWarehouse
GO

DECLARE @STARTDATE DATE = '2/1/2021'
, @ENDDATE DATE = '2/28/2021'
, @FACILITY NVARCHAR(5) = 'AP1'
, @SUPERVISOR NVARCHAR(50) = 'Keith Wooldridge'
, @SR_CFG NVARCHAR(50) = 'P1F1-REVIEW'
, @OT_CFG NVARCHAR(50) = 'AREVIEW2'
		--WHEN O.RESOURCE_ID = 'P1F1-REVIEW' AND O.OPERATION_TYPE = 'AREVIEW2' AND LT1.EMPLOYEE_ID IN (@P1_EEID) THEN 'P1 CONFIG'
, @SR_PLN NVARCHAR(50) = 'P1F1-REVIEW'
, @OT_PLN NVARCHAR(50) = 'AREVIEW2'
		--WHEN O.OPERATION_TYPE IN ('AREVIEW2') THEN 'PLANNING'
		--WHEN O.RESOURCE_ID IN ('P1F1-REVIEW') THEN 'PLANNING'
, @SR_REC NVARCHAR(50) = 'P1F1-REC'
, @OT_REC NVARCHAR(50) = ''
		--WHEN O.OPERATION_TYPE IN ('REC-P1', 'REC-P1-APP', 'REC-P1-GLOVES') THEN 'RECEIVING'
		--WHEN O.RESOURCE_ID IN ('P1F1-REC') THEN 'RECEIVING'
, @EEID NVARCHAR(50) = '4109'

; SET DATEFIRST 1

; WITH CTE_COS AS
(SELECT CASE
		WHEN CO.CUSTOMER_ID = 'BOE609' THEN 'CMP'
		ELSE 'OTHER'
	END AS CUSTOMER_ID 
	, CO.CUSTOMER_ID AS CUST_ID
	, CO.ID AS COID
	, CAST(CO.ORDER_DATE AS DATE) AS ORDER_DATE
	, CO.CREATE_DATE
	, CB.BOOK_DATE
	, CB.[USER_ID]
	, CASE 
		WHEN CB.[USER_ID] = 'IMELDAE#' THEN 'P1' 
		WHEN CB.[USER_ID] = 'JOEM#' THEN 'P1' 
		WHEN LEFT(EE.DEPARTMENT_ID, 3) = '300' THEN 'P1' 
		WHEN LEFT(EE.DEPARTMENT_ID, 3) = '100' THEN 'P2' 
		WHEN LEFT(EE.DEPARTMENT_ID, 3) = '700' THEN 'P3' 
		WHEN LEFT(EE.DEPARTMENT_ID, 3) = '400' THEN 'P3' 
		WHEN LEFT(EE.DEPARTMENT_ID, 3) = '960' THEN 'P1' 
		ELSE 'OTHER'
	END AS FACILITY
FROM CUSTOMER_ORDER CO
LEFT OUTER JOIN CUSTOMER_BOOKINGS CB
	ON CO.ID = CB.CUST_ORDER_ID
LEFT OUTER JOIN EMPLOYEE EE
	ON CB.[USER_ID] = EE.[USER_ID] + '#'
WHERE CO.ORDER_DATE >= @STARTDATE
	AND CO.ORDER_DATE < @ENDDATE
)
--SELECT * FROM CTE_COS

, CTE_CO_COUNTS AS
(SELECT * 
FROM 
	(SELECT FACILITY, COID, CUSTOMER_ID, ORDER_DATE
	FROM CTE_COS
	) T
	PIVOT (
		COUNT(COID)
		FOR FACILITY IN ([P1],[P2],[P3],[OTHER])
	) AS PIVOT_TABLE
)
--SELECT * FROM CTE_CO_COUNTS

, CTE_LT AS
(SELECT LT.WORKORDER_TYPE 
	, LT.WORKORDER_BASE_ID
	, LT.WORKORDER_LOT_ID
	, LT.WORKORDER_SPLIT_ID
	, LT.WORKORDER_SUB_ID
	, LT.OPERATION_SEQ_NO
	, LT.RESOURCE_ID
	, LT.EMPLOYEE_ID
	, MAX(LT.TRANSACTION_DATE) AS TRANS_DATE
	, SUM(LT.HOURS_WORKED) AS HRS_WORKED
	, COUNT(LT.TRANSACTION_ID) AS XCT_COUNT
FROM LABOR_TICKET LT
WHERE LT.TRANSACTION_DATE >= @STARTDATE
	AND LT.TRANSACTION_DATE < @ENDDATE
GROUP BY LT.WORKORDER_TYPE 
	, LT.WORKORDER_BASE_ID
	, LT.WORKORDER_LOT_ID
	, LT.WORKORDER_SPLIT_ID
	, LT.WORKORDER_SUB_ID
	, LT.OPERATION_SEQ_NO
	, LT.RESOURCE_ID
	, LT.EMPLOYEE_ID
)
--SELECT * FROM CTE_LT

, CTE_MERGE AS
(SELECT CASE
		WHEN ISNULL(CO.CUSTOMER_ID, '_BLANK') = 'BOE609' THEN 'CMP'
		ELSE 'OTHER'
	END AS CUSTOMER_ID
	, ISNULL(CO.CUSTOMER_ID, '_BLANK') AS CUSTID
	, DSL.DEMAND_BASE_ID AS COID
	, DSL.DEMAND_SEQ_NO AS CO_LINE_NO
	, O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.OPERATION_TYPE
	, CAST(O.CLOSE_DATE AS DATE) AS CLOSE_DATE
 --	, SR.USER_1 AS BUSUNIT
	--, CASE
	--	WHEN SR.USER_1 = 'A' THEN 'FIN'
	--	WHEN SR.USER_1 = 'M' THEN 'MFG'
	--	WHEN SR.USER_1 = 'O' THEN 'OUTREACH'
	--	WHEN SR.USER_1 = 'B' THEN 'BALLARD'
	--	WHEN SR.USER_1 = 'C' THEN 'CLOSED'
	--	ELSE '_Blank'
	--END AS BUSINESS_UNIT
--	, SR.USER_4 AS [SUPERVISOR]
	, SR.USER_5 AS [FACILITY]
	--, SR.USER_7 AS [PROCESS]
	--, SR.USER_8 AS [DEPARTMENT]
	--, LT.EMPLOYEE_ID
	--, EE.FIRST_NAME + ' ' + EE.LAST_NAME AS EE_NAME
	--, LT.TRANS_DATE
	--, LT.HRS_WORKED
	--, LT.XCT_COUNT
	, CASE
		WHEN O.OPERATION_TYPE IN (@OT_REC) THEN 'RECEIVING'
		WHEN O.RESOURCE_ID IN (@SR_REC) THEN 'RECEIVING'
		ELSE ''
	END AS RECEIVING
	, CASE
		WHEN O.RESOURCE_ID IN (@SR_CFG) AND O.OPERATION_TYPE IN (@OT_CFG) AND LT1.EMPLOYEE_ID IN (@EEID) THEN 'CONFIG'
		ELSE ''
	END AS CONFIG
	, CASE
		WHEN O.OPERATION_TYPE IN (@OT_PLN) THEN 'PLANNING'
		WHEN O.RESOURCE_ID IN (@SR_PLN) THEN 'PLANNING'
		ELSE ''
	END AS PLANNING
FROM OPERATION O
LEFT OUTER JOIN CTE_LT LT1
	ON O.WORKORDER_BASE_ID = LT1.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = LT1.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = LT1.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = LT1.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = LT1.WORKORDER_TYPE
	AND O.SEQUENCE_NO = LT1.OPERATION_SEQ_NO
	AND LT1.EMPLOYEE_ID IN (@EEID)
LEFT OUTER JOIN CTE_LT LT2
	ON O.WORKORDER_BASE_ID = LT2.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = LT2.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = LT2.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = LT2.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = LT2.WORKORDER_TYPE
	AND O.SEQUENCE_NO = LT2.OPERATION_SEQ_NO
LEFT OUTER JOIN SHOP_RESOURCE_SITE SR
	ON SR.RESOURCE_ID = O.RESOURCE_ID
LEFT OUTER JOIN EMPLOYEE EE
	ON LT1.EMPLOYEE_ID = EE.ID
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.[SUPPLY_TYPE] = 'WO'
	AND DSL.SUPPLY_BASE_ID = O.WORKORDER_BASE_ID
	AND DSL.SUPPLY_LOT_ID = O.WORKORDER_LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND DSL.SUPPLY_SUB_ID = O.WORKORDER_SUB_ID
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON DSL.DEMAND_BASE_ID = CO.ID
--	AND CO.ORDER_DATE >= '1/1/2021'
WHERE O.[STATUS] = 'C'
	AND O.CLOSE_DATE >= @STARTDATE 
	AND O.CLOSE_DATE < @ENDDATE
	AND (O.RESOURCE_ID NOT IN ('P1F1-REC-PANELS', 'P1F1-PLAN')
		OR O.OPERATION_TYPE NOT IN ('PANEL')
	)
GROUP BY ISNULL(CO.CUSTOMER_ID, '_BLANK')
	, DSL.DEMAND_BASE_ID
	, DSL.DEMAND_SEQ_NO
	, O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.OPERATION_TYPE
	, O.CLOSE_DATE
	--, SR.USER_1
	--, SR.USER_4
	, SR.USER_5
	, CASE
		WHEN O.RESOURCE_ID IN (@SR_CFG) AND O.OPERATION_TYPE IN (@OT_CFG) AND LT1.EMPLOYEE_ID IN (@EEID) THEN 'CONFIG'
		ELSE ''
	END
)
--SELECT * FROM CTE_MERGE

, CTE_REC AS
(SELECT CUSTOMER_ID
--	, BUSINESS_UNIT
	, [FACILITY]
	, CLOSE_DATE
	, COUNT(*) AS REC_COUNT
FROM CTE_MERGE M
WHERE RECEIVING = 'RECEIVING'
GROUP BY CUSTOMER_ID, [FACILITY], CLOSE_DATE
) 

, CTE_CONFIG AS
(SELECT CUSTOMER_ID
--	, BUSINESS_UNIT
	, [FACILITY]
	, CLOSE_DATE
	, COUNT(*) AS CONFIG_COUNT
FROM CTE_MERGE M
WHERE CONFIG = 'CONFIG'
GROUP BY CUSTOMER_ID, [FACILITY], CLOSE_DATE
) 

, CTE_PLAN AS
(SELECT CUSTOMER_ID
--	, BUSINESS_UNIT
	, [FACILITY]
	, CLOSE_DATE
	, COUNT(*) AS PLAN_COUNT
FROM CTE_MERGE M
WHERE PLANNING = 'PLANNING'
GROUP BY CUSTOMER_ID, [FACILITY], CLOSE_DATE
)
--SELECT * FROM CTE_PLAN

, CTE_UNIQUE AS
(SELECT CUSTOMER_ID
--	, BUSINESS_UNIT
	, [FACILITY]
	, CLOSE_DATE
FROM CTE_MERGE M
GROUP BY CUSTOMER_ID, [FACILITY], CLOSE_DATE
)
--SELECT * FROM CTE_UNIQUE 


SELECT U.CUSTOMER_ID
	, U.FACILITY
	, U.CLOSE_DATE
	, DATEPART(WK, U.CLOSE_DATE) AS WEEKNUM
	, CASE
		WHEN U.FACILITY = 'AP1' THEN O.P1
		WHEN U.FACILITY = 'AP2' THEN O.P2
		WHEN U.FACILITY = 'AP3' THEN O.P3
		ELSE O.OTHER
	END AS CO_COUNT
	, REC_COUNT
	, CONFIG_COUNT
	, PLAN_COUNT
FROM CTE_UNIQUE U
LEFT OUTER JOIN CTE_CO_COUNTS O
	ON O.CUSTOMER_ID = U.CUSTOMER_ID
	AND O.ORDER_DATE = U.CLOSE_DATE
LEFT OUTER JOIN CTE_REC R
	ON R.CUSTOMER_ID = U.CUSTOMER_ID
	AND R.CLOSE_DATE = U.CLOSE_DATE
	AND R.[FACILITY] = U.[FACILITY]
LEFT OUTER JOIN CTE_PLAN P
	ON P.CUSTOMER_ID = U.CUSTOMER_ID
	AND P.CLOSE_DATE = U.CLOSE_DATE
	AND P.[FACILITY] = U.[FACILITY]
LEFT OUTER JOIN CTE_CONFIG C
	ON C.CUSTOMER_ID = U.CUSTOMER_ID
	AND C.CLOSE_DATE = U.CLOSE_DATE
	AND C.[FACILITY] = U.[FACILITY]
WHERE U.[FACILITY] IN (@FACILITY)
ORDER BY U.CLOSE_DATE
	, U.FACILITY
	, U.CUSTOMER_ID

