USE LIVE
GO

/*
-- FOR WHEN COSTED_QTY > QTY
-- SUPPLY LINK DOESN'T DISTRIBUTE EQUALLY


BEGIN TRAN
SELECT * FROM INV_TRANS_DIST WHERE OUT_TRANS_ID = '1269453'
DELETE INV_TRANS_DIST WHERE OUT_TRANS_ID = '1269453'
SELECT * FROM INVENTORY_TRANS WHERE PART_ID = '146T0807-4'
ROLLBACK TRAN


BEGIN TRAN
SELECT * FROM INV_TRANS_DIST WHERE OUT_TRANS_ID = '356681'
DELETE INV_TRANS_DIST WHERE OUT_TRANS_ID = '356681'
SELECT * FROM INVENTORY_TRANS WHERE PART_ID = 'Texture Key Chain'
ROLLBACK TRAN
*/
