/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ROWID]
      ,[CUSTOMER_ID]
      ,[PART_ID]
      ,[SELLING_UM]
      ,[CREATE_DATE]
      ,[EFFECTIVE_DATE]
      ,[DISCONTINUE_DATE]
      ,[CUSTOMER_PART_ID]
      ,[QTY_BREAK_1]
      ,[QTY_BREAK_2]
      ,[QTY_BREAK_3]
      ,[QTY_BREAK_4]
      ,[QTY_BREAK_5]
      ,[QTY_BREAK_6]
      ,[QTY_BREAK_7]
      ,[QTY_BREAK_8]
      ,[QTY_BREAK_9]
      ,[QTY_BREAK_10]
      ,[UNIT_PRICE_1]
      ,[UNIT_PRICE_2]
      ,[UNIT_PRICE_3]
      ,[UNIT_PRICE_4]
      ,[UNIT_PRICE_5]
      ,[UNIT_PRICE_6]
      ,[UNIT_PRICE_7]
      ,[UNIT_PRICE_8]
      ,[UNIT_PRICE_9]
      ,[UNIT_PRICE_10]
      ,[DEFAULT_UNIT_PRICE]
      ,[BY_DATE_CODE]
  FROM [LIVE].[dbo].[CUST_PRICE_EFFECT]

  select [BY_DATE_CODE], count(*)
  FROM [LIVE].[dbo].[CUST_PRICE_EFFECT]
  where [DISCONTINUE_DATE] > getdate()
  group by [BY_DATE_CODE]

DROP TABLE #T1

SELECT CPE.*
INTO #T1
FROM [LIVE].[dbo].[CUST_PRICE_EFFECT] CPE
INNER JOIN PART P
ON P.ID = CPE.PART_ID
WHERE CPE.[DISCONTINUE_DATE] > GETDATE()
AND (P.STATUS IS NULL OR P.STATUS != 'O')
AND CPE.BY_DATE_CODE = 'S'

SELECT * FROM #T1

SELECT *
FROM [LIVE].[dbo].[CUST_PRICE_EFFECT] CPE
INNER JOIN PART P
ON P.ID = CPE.PART_ID
WHERE CPE.[DISCONTINUE_DATE] > GETDATE()
AND CPE.BY_DATE_CODE = 'S'


/*
BEGIN TRANSACTION;
UPDATE CUST_PRICE_EFFECT
	SET BY_DATE_CODE = 'O'
FROM [LIVE].[dbo].[CUST_PRICE_EFFECT] CPE
INNER JOIN PART P
	ON P.ID = CPE.PART_ID
WHERE CPE.[DISCONTINUE_DATE] > GETDATE()
	AND (P.STATUS IS NULL OR P.STATUS != 'O')
	AND CPE.BY_DATE_CODE = 'S'
--> 2618 ROWS AFFECTED
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
