use datawarehouse
go

--> VISUAL ENTERPRISE > SHIPPING REPORTS > CUST_ORDER_AND_SHIPMENTS DATASET
DECLARE @StartDate DATE = '1/1/'+CAST(YEAR(GETDATE()) AS NVARCHAR(4)); 

SELECT A.*
	, CASE
		WHEN DSL.SUPPLY_TYPE = 'CP' THEN 'CP'
		ELSE 'WO'
	END AS SUPPLY_TYPE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
FROM 
(
	SELECT CO.CUSTOMER_ID 
		, CO.ID AS CUST_ORDER_ID
		, COL.LINE_NO AS COL_LINE_NO
		, CO.ORDER_DATE
		, ISNULL(COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) AS DESIRED_SHIP_DATE
		, COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) AS FILTER_SHIP_DATE
		, CO.[STATUS] AS CO_STATUS
		, CO.TOTAL_AMT_ORDERED AS CO_TOTAL_ORDERED
		, CO.TOTAL_AMT_SHIPPED AS CO_TOTAL_SHIPPED
		, COL.TOTAL_AMT_SHIPPED AS COL_AMT_SHIPPED
		, COL.TOTAL_AMT_ORDERED AS COL_AMT_ORDERED
		, COL.SERVICE_CHARGE_ID
		, CASE
			WHEN COL.SERVICE_CHARGE_ID IS NOT NULL THEN COL.MISC_REFERENCE
			ELSE ''
		END AS CHARGE_TYPE
		, COL.PART_ID
		, P.[DESCRIPTION]
		, CASE
			WHEN COL.SERVICE_CHARGE_ID IS NULL THEN COL.MISC_REFERENCE
			ELSE ''
		END AS CUST_PART_DESC
		, P.PRODUCT_CODE AS PART_PROD_CODE
		, P.COMMODITY_CODE AS PART_COMM_CODE
		, P.PLANNER_USER_ID
		, P.BUYER_USER_ID
		, COL.LINE_STATUS AS SHIP_SHORT
		, COL.ORDER_QTY
		, COL.TOTAL_SHIPPED_QTY
		, COL.UNIT_PRICE
		, UDF.STRING_VAL AS BUS_STREAM
		, UDF1.STRING_VAL AS MATERIAL_TYPE
		--, MAX(S.SHIPPED_DATE) AS SHIPPED_DATE
		--, SUM(RL.QTY) AS INVOICE_QTY
		--, SUM(RL.AMOUNT) AS INVOICE_AMT
		, S.PACKLIST_ID
		, SL.SHIPPED_QTY
		, S.SHIPPED_DATE AS SHIPPED_DATE
		, RL.INVOICE_ID
		, R.INVOICE_DATE
		, RL.LINE_NO AS INVOICE_LINE
		, RL.QTY AS INV_QTY
		, RL.AMOUNT AS INVOICE_AMT
		, CASE
			WHEN ltrim(rtrim(RIGHT(R.INVOICE_ID,1))) = 'M' THEN 0
			ELSE RL.QTY
		END AS INVOICE_QTY
	FROM CUST_ORDER_LINE COL
	INNER JOIN CUSTOMER_ORDER CO
		ON CO.ID = COL.CUST_ORDER_ID
	LEFT OUTER JOIN PART P
		ON COL.PART_ID = P.ID
	LEFT OUTER JOIN SHIPPER_LINE SL
		ON COL.CUST_ORDER_ID = SL.CUST_ORDER_ID
		AND COL.LINE_NO = SL.CUST_ORDER_LINE_NO
		AND SL.SHIPPED_QTY <> 0
	LEFT OUTER JOIN SHIPPER S
		ON SL.PACKLIST_ID = S.PACKLIST_ID
	LEFT OUTER JOIN RECEIVABLE_LINE RL
		ON SL.PACKLIST_ID = RL.PACKLIST_ID
		AND SL.LINE_NO = RL.PACKLIST_LINE_NO
	LEFT OUTER JOIN RECEIVABLE R
		ON RL.INVOICE_ID = R.INVOICE_ID
	LEFT OUTER JOIN USER_DEF_FIELDS UDF
		ON UDF.DOCUMENT_ID = CO.CUSTOMER_ID
		AND PROGRAM_ID = 'VMCUSMNT'
		AND UDF.ID = 'UDF-0000072'
	LEFT OUTER JOIN USER_DEF_FIELDS UDF1
		ON UDF1.DOCUMENT_ID = P.ID
		AND UDF1.PROGRAM_ID = 'VMPRTMNT'
		AND UDF1.ID = 'UDF-0000035'
	WHERE CO.[STATUS] IN ('H', 'R', 'C')
		AND COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) >= @StartDate
	--GROUP BY CO.CUSTOMER_ID 
	--	, CO.ID
	--	, COL.LINE_NO
	--	, CO.ORDER_DATE
	--	, ISNULL(COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)
	--	, COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)
	--	, CO.[STATUS]
	--	, CO.TOTAL_AMT_ORDERED
	--	, CO.TOTAL_AMT_SHIPPED
	--	, COL.TOTAL_AMT_SHIPPED
	--	, COL.TOTAL_AMT_ORDERED
	--	, COL.SERVICE_CHARGE_ID
	--	, CASE
	--		WHEN COL.SERVICE_CHARGE_ID IS NOT NULL THEN COL.MISC_REFERENCE
	--		ELSE ''
	--	END
	--	, COL.PART_ID
	--	, P.[DESCRIPTION]
	--	, CASE
	--		WHEN COL.SERVICE_CHARGE_ID IS NULL THEN COL.MISC_REFERENCE
	--		ELSE ''
	--	END
	--	, P.PRODUCT_CODE
	--	, P.COMMODITY_CODE
	--	, P.PLANNER_USER_ID
	--	, P.BUYER_USER_ID
	--	, COL.LINE_STATUS
	--	, COL.ORDER_QTY
	--	, COL.TOTAL_SHIPPED_QTY
	--	, COL.UNIT_PRICE
	--	, UDF.STRING_VAL
	--	, UDF1.STRING_VAL
	--	, S.PACKLIST_ID
	--	, SL.SHIPPED_QTY
	--	, S.SHIPPED_DATE
	--	, RL.INVOICE_ID
	--	, RL.LINE_NO 
	--	, R.INVOICE_DATE
	--	, RL.QTY
	--	, RL.AMOUNT
	--	, CASE
	--		WHEN ltrim(rtrim(RIGHT(R.INVOICE_ID,1))) = 'M' THEN 0
	--		ELSE R.INVOICE_QTY
	--	END
	----       HAVING COALESCE(MAX(S.SHIPPED_DATE), COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) >= @StartDate
) A
LEFT OUTER  JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = A.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = A.COL_LINE_NO
LEFT OUTER JOIN WORK_ORDER WO
	ON DSL.SUPPLY_TYPE = 'WO' 
	AND DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
	AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
	AND WO.[TYPE] = 'W'
