USE DataWarehouse
GO

DECLARE @StartDate DATE = DATEADD(YEAR,-1,DATEADD(DAY,1,(EOMONTH(DATEADD(MONTH,-1,GETDATE())))));
 
WITH CTE_BASE AS
(SELECT A.*
	, TOTAL_SHIPPED_QTY * UNIT_PRICE AS SHIPPED_AMOUNT
	, UNSHIPPEDQTY * UNIT_PRICE AS UNSHIPPED_AMOUNT
	, CONVERT(DATE, DATEADD(DD, REASONING, DESIRED_SHIP_DATE)) AS ADJUSTED_DUE_DATE
	, CASE
		WHEN DSL.SUPPLY_TYPE = 'CP' THEN 'CP'
		ELSE 'WO'
	END AS SUPPLY_TYPE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, CASE
		WHEN UNSHIPPEDQTY = 0 THEN 'COMPLETE'
		WHEN SHIPPED_DATE IS NULL THEN 'INCOMPLETE'
		WHEN ORDER_QTY = '0' THEN 'NO QTY'
		ELSE 'INCOMPLETE'
	END AS ORDER_STATUS
FROM 
(SELECT CO.CUSTOMER_ID 
	, CO.ID AS CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE_NO
	, CONVERT(DATE, CO.ORDER_DATE) AS ORDER_DATE
	, CONVERT(DATE, CO.CREATE_DATE) AS CREATE_DATE
	, CONVERT(DATE, ISNULL(COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)) AS DESIRED_SHIP_DATE
	, CONVERT(DATE, CASE
		WHEN COL.LINE_STATUS = 'C' THEN COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)
		WHEN COL.ORDER_QTY = 0 THEN COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)
		WHEN CO.[STATUS] = 'C' THEN COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)
		WHEN COL.ORDER_QTY - COL.TOTAL_SHIPPED_QTY > 0 THEN COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)
		WHEN COL.TOTAL_SHIPPED_QTY > 0 THEN COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)
		WHEN S.SHIPPED_DATE IS NOT NULL THEN S.SHIPPED_DATE
		WHEN COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) <=  GETDATE() THEN GETDATE()
		ELSE COALESCE(S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)
	END) AS FILTER_DATE
	, CO.[STATUS] AS CO_STATUS
	, COL.SERVICE_CHARGE_ID
	, CASE
		WHEN COL.SERVICE_CHARGE_ID IS NOT NULL THEN 'SERVICE CHARGE'
		WHEN COL.PART_ID IS NOT NULL THEN 'PART PROCESSING'
		ELSE 'OTHER'
	END AS LINE_TYPE
	, CASE
		WHEN COL.SERVICE_CHARGE_ID IS NOT NULL THEN COL.SERVICE_CHARGE_ID
		ELSE COL.PART_ID
	END AS LINE_ITEM
	, CASE
		WHEN COL.SERVICE_CHARGE_ID IS NOT NULL THEN COL.MISC_REFERENCE
		ELSE ''
	END AS CHARGE_TYPE
	, CASE
		WHEN COL.SERVICE_CHARGE_ID IS NULL THEN COL.MISC_REFERENCE
		ELSE ''
	END AS CUST_PART_DESC
	, COL.PART_ID
	, P.[DESCRIPTION]
	, P.PRODUCT_CODE AS PART_PROD_CODE
	, P.COMMODITY_CODE AS PART_COMM_CODE
	, P.PLANNER_USER_ID
	, P.BUYER_USER_ID
	, CASE
		WHEN CO.CUSTOMER_ID != 'BOE609' THEN 0
		WHEN P.PLANNER_USER_ID = 'FIN' THEN 1
		WHEN P.PLANNER_USER_ID = 'FIN-HOURLY' THEN 7
		WHEN LEFT(P.BUYER_USER_ID,2) = '59' THEN 7
		WHEN P.PLANNER_USER_ID LIKE 'MFG-HOURLY%' THEN 25
		WHEN LEFT(P.BUYER_USER_ID,2) = '09' THEN 25
		ELSE 0 
	END AS REASONING
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, COL.ORDER_QTY - COL.TOTAL_SHIPPED_QTY AS REMQTY
	, CASE
		WHEN COL.LINE_STATUS = 'C' THEN 0
		WHEN CO.[STATUS] = 'C' THEN 0
		WHEN COL.ORDER_QTY < COL.TOTAL_SHIPPED_QTY THEN 0
		ELSE COL.ORDER_QTY - COL.TOTAL_SHIPPED_QTY
	END AS UNSHIPPEDQTY
	, COL.UNIT_PRICE
	, CASE
		WHEN CO.CUSTOMER_ID != 'BOE609' THEN UDF.STRING_VAL
		WHEN LEFT(P.BUYER_USER_ID,2) = '59' THEN 'CMP-FIN'
		WHEN LEFT(P.BUYER_USER_ID,2) = '09' THEN  'CMP-MFG'
		WHEN P.PLANNER_USER_ID IN ('FIN', 'MFG', 'BUSSOL') THEN P.PLANNER_USER_ID
		WHEN P.PLANNER_USER_ID = 'FIN-HOURLY' THEN 'CMP-FIN'
		WHEN P.PLANNER_USER_ID LIKE 'MFG-HOURLY%' THEN  'CMP-MFG'
		WHEN LEFT(P.PLANNER_USER_ID,3) IN ('MFG') THEN 'MFG'
		WHEN COL.SERVICE_CHARGE_ID IS NOT NULL THEN 'SERVICE CHARGE'
		ELSE 'UNKNOWN'	END AS BUS_STREAM
	, UDF1.STRING_VAL AS MATERIAL_TYPE
	, S.PACKLIST_ID
	, SL.LINE_NO AS PACKLIST_LINE_NO
	, CASE
		WHEN LTRIM(RTRIM(RIGHT(R.INVOICE_ID,1))) = 'M' THEN 0
		ELSE SHIPPED_QTY
	END AS SHIPPED_QTY
	, CONVERT(DATE, S.SHIPPED_DATE) AS SHIPPED_DATE
	, CONVERT(DATE, R.INVOICE_DATE) AS INVOICE_DATE
	, RL.INVOICE_ID
	, RL.LINE_NO AS INVOICE_LINE
	, RL.AMOUNT AS INVOICE_AMT
	, CASE
		WHEN LTRIM(RTRIM(RIGHT(R.INVOICE_ID,1))) = 'M' THEN 0
		ELSE RL.QTY
	END AS INVOICE_QTY
FROM CUST_ORDER_LINE COL
	INNER JOIN CUSTOMER_ORDER CO
		ON CO.ID = COL.CUST_ORDER_ID
	LEFT OUTER JOIN PART P
		ON COL.PART_ID = P.ID
	LEFT OUTER JOIN SHIPPER_LINE SL
		ON COL.CUST_ORDER_ID = SL.CUST_ORDER_ID
		AND COL.LINE_NO = SL.CUST_ORDER_LINE_NO
		AND SL.SHIPPED_QTY <> 0
	LEFT OUTER JOIN SHIPPER S
		ON SL.PACKLIST_ID = S.PACKLIST_ID
	LEFT OUTER JOIN RECEIVABLE_LINE RL
		ON SL.PACKLIST_ID = RL.PACKLIST_ID
		AND SL.LINE_NO = RL.PACKLIST_LINE_NO
	LEFT OUTER JOIN RECEIVABLE R
		ON RL.INVOICE_ID = R.INVOICE_ID
	LEFT OUTER JOIN USER_DEF_FIELDS UDF
		ON UDF.DOCUMENT_ID = CO.CUSTOMER_ID
		AND PROGRAM_ID = 'VMCUSMNT'
		AND UDF.ID = 'UDF-0000072'
	LEFT OUTER JOIN USER_DEF_FIELDS UDF1
		ON UDF1.DOCUMENT_ID = P.ID
		AND UDF1.PROGRAM_ID = 'VMPRTMNT'
		AND UDF1.ID = 'UDF-0000035'
WHERE CO.[STATUS] IN ('H', 'R', 'C')
	AND COALESCE(R.INVOICE_DATE, S.SHIPPED_DATE, COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) >= @StartDate
--	AND COL.ORDER_QTY != '0'
) A
LEFT OUTER  JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = A.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = A.COL_LINE_NO
LEFT OUTER JOIN WORK_ORDER WO
	ON DSL.SUPPLY_TYPE = 'WO' 
	AND DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
	AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
	AND WO.[TYPE] = 'W'
)

, CTE_REMAINING AS
(SELECT *
FROM CTE_BASE
where CO_STATUS = 'R'
	and SHIP_SHORT <> 'C'
	and ORDER_QTY > TOTAL_SHIPPED_QTY
	and TOTAL_SHIPPED_QTY > 0
)

, CTE_FULL AS 
(SELECT 'BASE' AS CTE
	, *
FROM CTE_BASE
UNION ALL
SELECT 'REMAINING' AS CTE
	, CUSTOMER_ID
	, CUST_ORDER_ID
	, COL_LINE_NO
	, ORDER_DATE
	, CREATE_DATE
	, DESIRED_SHIP_DATE
	, DESIRED_SHIP_DATE AS FILTER_DATE
	, CO_STATUS
	, SERVICE_CHARGE_ID
	, LINE_TYPE
	, LINE_ITEM
	, CHARGE_TYPE
	, CUST_PART_DESC
	, PART_ID
	, [DESCRIPTION]
	, PART_PROD_CODE
	, PART_COMM_CODE
	, PLANNER_USER_ID
	, BUYER_USER_ID
	, REASONING
	, SHIP_SHORT
	, ORDER_QTY
	, TOTAL_SHIPPED_QTY
	, UNSHIPPEDQTY
	, REMQTY
	, UNIT_PRICE
	, BUS_STREAM
	, MATERIAL_TYPE
	, NULL AS PACKLIST_ID
	, NULL AS PACKLIST_LINE_NO
	, NULL AS SHIPPED_QTY
	, NULL AS SHIPPED_DATE
	, NULL AS INVOICE_DATE
	, NULL AS INVOICE_ID
	, NULL AS INVOICE_LINE
	, NULL AS INVOICE_AMT
	, NULL AS INVOICE_QTY
	, NULL AS SHIPPED_AMOUNT
	, NULL AS UNSHIPPED_AMOUNT
	, ADJUSTED_DUE_DATE
	, SUPPLY_TYPE
	, BASE_ID
	, LOT_ID
	, SPLIT_ID
	, SUB_ID
	, ORDER_STATUS
FROM CTE_REMAINING
)

SELECT A.* 
	, MAX(DATEADD(DD,-(DAY(FILTER_DATE)-1), FILTER_DATE)) AS FILTER_PERIOD
	, PSF.[Target] AS TARGET_GOALS
FROM CTE_FULL A
LEFT OUTER JOIN [LIVESupplemental].[dbo].[Plant_Shipment_Forecast] PSF
	ON PSF.BusStream = A.BUS_STREAM
	AND PSF.[Date] = DATEADD(DD,-(DAY(A.FILTER_DATE)-1), A.FILTER_DATE)
GROUP BY CTE
	, CUSTOMER_ID
	, CUST_ORDER_ID
	, COL_LINE_NO
	, ORDER_DATE
	, CREATE_DATE
	, DESIRED_SHIP_DATE
	, FILTER_DATE
	, CO_STATUS
	, SERVICE_CHARGE_ID
	, LINE_TYPE
	, LINE_ITEM
	, CHARGE_TYPE
	, CUST_PART_DESC
	, PART_ID
	, [DESCRIPTION]
	, PART_PROD_CODE
	, PART_COMM_CODE
	, PLANNER_USER_ID
	, BUYER_USER_ID
	, REASONING
	, SHIP_SHORT
	, ORDER_QTY
	, TOTAL_SHIPPED_QTY
	, UNSHIPPEDQTY
	, REMQTY
	, UNIT_PRICE
	, BUS_STREAM
	, MATERIAL_TYPE
	, PACKLIST_ID
	, PACKLIST_LINE_NO
	, SHIPPED_QTY
	, SHIPPED_DATE
	, INVOICE_DATE
	, INVOICE_ID
	, INVOICE_LINE
	, INVOICE_AMT
	, INVOICE_QTY
	, SHIPPED_AMOUNT
	, UNSHIPPED_AMOUNT
	, ADJUSTED_DUE_DATE
	, SUPPLY_TYPE
	, BASE_ID
	, LOT_ID
	, SPLIT_ID
	, SUB_ID
	, ORDER_STATUS
	, PSF.[Target]
