USE DataWarehouse
GO

set datefirst 1;

SELECT NCM_ID
	, NCM.NCM_DATE
	, COALESCE(NCM.SK_FIN_NCM_PROCESS, NCM.SK_MFG_NCM_PROCESS, '_BLANK') AS [PROCESS]
	, COALESCE(NCM.SK_FIN_NCM_SUBPROCESS, NCM.SK_MFG_NCM_SUBPROCESS, '_BLANK') AS [SUBPROCESS]
	, ISNULL(NCM.USER_DEFINED_4, NCM.USER_DEFINED_7) AS [DEFECT]
	, NCM.DISPOSITION_TYPE
	, DATEPART(YYYY, NCM.NCM_DATE) AS [YEAR]
	, DATEPART(MM, NCM.NCM_DATE) AS [MONTH]
	, DATEPART(QQ, NCM.NCM_DATE) AS [QUARTER]
	, DATEPART(WW, NCM.NCM_DATE) AS [WEEK]
 	, SR.USER_1 AS BUSUNIT
	, CASE
		WHEN SR.USER_1 = 'A' THEN 'FIN'
		WHEN SR.USER_1 = 'M' THEN 'MFG'
		WHEN SR.USER_1 = 'O' THEN 'OUTREACH'
		WHEN SR.USER_1 = 'B' THEN 'BALLARD'
		WHEN SR.USER_1 = 'C' THEN 'CLOSED'
	END AS BUSINESSUNIT
	, SR.USER_2 AS DEPARTMENT
	, SR.USER_3 AS SUBDEPARTMENT
	, SR.USER_4 AS SUPERVISOR
	, SR.USER_5 AS PLANT
	, CASE
		WHEN @TIMEFRAME IN ('LAST WEEK', 'CURRENT WEEK') THEN DATENAME(WEEKDAY, NCM.NCM_DATE)   
		WHEN @TIMEFRAME IN ('LAST MONTH', 'CURRENT MONTH') THEN CONVERT(VARCHAR(20), DATEADD(wk, 0, DATEADD(DAY, 1-DATEPART(WEEKDAY, NCM.NCM_DATE), DATEDIFF(dd, 0, NCM.NCM_DATE))), 101)
		ELSE DATENAME(MONTH, NCM.NCM_DATE)
	END AS TIMEFRAME
	, CASE
		WHEN @TIMEFRAME IN ('LAST WEEK', 'CURRENT WEEK') THEN DATEPART(DD, NCM.NCM_DATE)
		WHEN @TIMEFRAME IN ('LAST MONTH', 'CURRENT MONTH') THEN DATEPART(WW, NCM.NCM_DATE)
		ELSE DATEPART(MM, NCM.NCM_DATE)
	END CHARTSORT

FROM VQ_NONCONFORMANCE NCM
LEFT OUTER JOIN VQ_OPERATION O
	ON O.RECORD_ID = NCM.OPERATION_REC_ID
LEFT OUTER JOIN SHOP_RESOURCE_SITE SR
	ON O.CONST_RESOURCE_ID = SR.RESOURCE_ID
WHERE COALESCE(NCM.SK_FIN_NCM_PROCESS, NCM.SK_MFG_NCM_PROCESS, '_BLANK') IN (@PROCESS)
	AND SR.USER_2 IN (@DEPARTMENT)
	AND CASE
		WHEN SR.USER_1 = 'A' THEN 'FIN'
		WHEN SR.USER_1 = 'M' THEN 'MFG'
		WHEN SR.USER_1 = 'O' THEN 'OUTREACH'
		WHEN SR.USER_1 = 'B' THEN 'BALLARD'
		WHEN SR.USER_1 = 'C' THEN 'CLOSED'
	END IN (@BUSUNIT)
	AND SR.USER_5 IN (@PLANT)
	AND SR.USER_4 IN (@SUPERVISOR)
	AND ISNULL(NCM.USER_DEFINED_4, NCM.USER_DEFINED_7) IN (@DEFECT)
	AND NCM.DISPOSITION_TYPE NOT IN ('NON-DISCREPANT', 'OVERAGE')
	AND NCM.DISPOSITION_TYPE IS NOT NULL
	AND
	(
		(@TIMEFRAME = 'LAST YEAR' AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) - 1
			)
		OR (@TIMEFRAME = 'CURRENT YEAR' AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE())
			)
		OR (@TIMEFRAME = 'CURRENT WEEK' AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) AND DATEPART(WW, NCM.NCM_DATE) = DATEPART(WW, GETDATE())
			)
		OR (@TIMEFRAME = 'CURRENT MONTH' AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) AND DATEPART(MM, NCM.NCM_DATE) = DATEPART(MM, GETDATE())
			)
	---- in same year
		OR (@TIMEFRAME = 'LAST WEEK' AND DATEPART(WW, GETDATE()) > 1 AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) AND DATEPART(WW, NCM.NCM_DATE) = DATEPART(WW, GETDATE()) - 1
			)
	---- in different year, over the gap
		OR (@TIMEFRAME = 'LAST WEEK' AND DATEPART(WW, GETDATE()) = 1 AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) - 1 AND DATEPART(WW, NCM.NCM_DATE) >= 52
			)
	---- in same year
		OR (@TIMEFRAME = 'LAST MONTH' AND DATEPART(MM, GETDATE()) > 1 AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) AND DATEPART(MM, NCM.NCM_DATE) = DATEPART(MM, GETDATE()) - 1
			)
	---- in different year, over the gap
		OR (@TIMEFRAME = 'LAST MONTH'  AND DATEPART(MM, GETDATE()) = 1 AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) - 1 AND DATEPART(MM, NCM.NCM_DATE) = 12
			)
	---- in same year
		OR (@TIMEFRAME = 'LAST QUARTER'  AND DATEPART(QQ, GETDATE()) > 1 AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) AND DATEPART(QQ, NCM.NCM_DATE) = DATEPART(QQ, GETDATE()) - 1
			)
	---- in different year, over the gap
		OR (@TIMEFRAME = 'LAST QUARTER' AND DATEPART(QQ, GETDATE()) = 1 AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) -1 AND DATEPART(QQ, NCM.NCM_DATE) = 4
			)
	 )
