use DataWarehouse
go

DECLARE @IQM_PROCESS NVARCHAR() = ''
, @IQM_SUBPROCESS NVARCHAR() = ''
, @IQM_DEFECT NVARCHAR() = ''
, @BUSUNIT NVARCHAR() = ''
, @PRIMARY NVARCHAR() = ''
, @SECONDARY NVARCHAR() = ''
, @SUPERVISOR NVARCHAR() = ''
, @FACILITY NVARCHAR() = ''
, @PROCESS NVARCHAR() = ''
, @DEPARTMENT NVARCHAR() = ''
, @TIMEFRAME NVARCHAR() = ''

set datefirst 1;

SELECT NCM.NCM_ID
	, NCM.NCM_DATE
	, COALESCE(NCM.SK_FIN_NCM_PROCESS, NCM.SK_MFG_NCM_PROCESS, '_BLANK') AS [IQM_PROCESS]
	, COALESCE(NCM.SK_FIN_NCM_SUBPROCESS, NCM.SK_MFG_NCM_SUBPROCESS, '_BLANK') AS [IQM_SUBPROCESS]
	, ISNULL(NCM.USER_DEFINED_4, NCM.USER_DEFINED_7) AS [IQM_DEFECT]
	, NCM.DISPOSITION_TYPE
 	, SR.USER_1 AS BUSUNIT
	, CASE
		WHEN SR.USER_1 = 'A' THEN 'FIN'
		WHEN SR.USER_1 = 'M' THEN 'MFG'
		WHEN SR.USER_1 = 'O' THEN 'OUTREACH'
		WHEN SR.USER_1 = 'B' THEN 'BALLARD'
		WHEN SR.USER_1 = 'C' THEN 'CLOSED'
	END AS BUSINESS_UNIT
	, SR.USER_2 AS [PRIMARY]
	, SR.USER_3 AS [SECONDARY]
	, SR.USER_4 AS SUPERVISOR
	, SR.USER_5 AS FACILITY
	, SR.USER_7 AS PROCESS
	, SR.USER_8 AS DEPARTMENT
	, CASE
		WHEN @TIMEFRAME IN ('LAST WEEK', 'CURRENT WEEK') THEN DATENAME(WEEKDAY, NCM.NCM_DATE)   
		WHEN @TIMEFRAME IN ('LAST MONTH', 'CURRENT MONTH') THEN CONVERT(VARCHAR(20), DATEADD(wk, 0, DATEADD(DAY, 1-DATEPART(WEEKDAY, NCM.NCM_DATE), DATEDIFF(dd, 0, NCM.NCM_DATE))), 101)
		ELSE DATENAME(MONTH, NCM.NCM_DATE)
	END AS TIMEFRAME
	, CASE
		WHEN @TIMEFRAME IN ('LAST WEEK', 'CURRENT WEEK') THEN DATEPART(DD, NCM.NCM_DATE)
		WHEN @TIMEFRAME IN ('LAST MONTH', 'CURRENT MONTH') THEN DATEPART(WW, NCM.NCM_DATE)
		ELSE DATEPART(MM, NCM.NCM_DATE)
	END CHARTSORT
	, CASE
		WHEN @TIMEFRAME = 'LAST WEEK' THEN CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 7, GETDATE()), 0))
		WHEN @TIMEFRAME = 'CURRENT WEEK' THEN CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0))
		WHEN @TIMEFRAME = 'LAST MONTH' THEN CONVERT(DATE, DATEADD(D, -(DAY(DATEADD(M, -1, GETDATE()-2))), DATEADD(M, -1, GETDATE()-1)))
		WHEN @TIMEFRAME = 'CURRENT MONTH' THEN CONVERT(DATE, DATEADD(D, -(DAY(GETDATE()-1)), GETDATE()))
		WHEN @TIMEFRAME = 'LAST YEAR' THEN CONVERT(DATE, DATEADD(YEAR, DATEDIFF(YEAR, 0, GETDATE()) - 1, 0))
		WHEN @TIMEFRAME = 'CURRENT YEAR' THEN CONVERT(DATE, DATEADD(YY, DATEDIFF(YY, 0, GETDATE()), 0))
		WHEN @TIMEFRAME = 'LAST QUARTER' THEN CONVERT(DATE, dateadd(quarter, datediff(quarter, 0 , GETDATE()) - 1, 0))
		WHEN @TIMEFRAME = 'CURRENT QUARTER' THEN DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()), 0)
	END AS STARTDATE
	, CASE
		WHEN @TIMEFRAME = 'LAST WEEK' THEN CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 7, GETDATE()), 6))
		WHEN @TIMEFRAME = 'CURRENT WEEK' THEN CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 6))
		WHEN @TIMEFRAME = 'LAST MONTH' THEN CONVERT(DATE, DATEADD(D, -(DAY(GETDATE())), GETDATE()))
		WHEN @TIMEFRAME = 'CURRENT MONTH' THEN CONVERT(DATE, DATEADD(D, -(DAY(DATEADD(M, 1, GETDATE()))), DATEADD(M, 1, GETDATE())))
		WHEN @TIMEFRAME = 'LAST YEAR' THEN CONVERT(DATE, DATEADD(YEAR, DATEDIFF(YEAR, 0, GETDATE()), -1))
		WHEN @TIMEFRAME = 'CURRENT YEAR' THEN CONVERT(DATE, DATEADD(YY, DATEDIFF(YY, 0, GETDATE()) + 1, -1))
		WHEN @TIMEFRAME = 'LAST QUARTER' THEN CONVERT(DATE, dateadd(quarter, datediff(quarter, 0 , GETDATE()) - 1, 0))
		WHEN @TIMEFRAME = 'CURRENT QUARTER' THEN DATEADD (DD, -1, DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()) + 1, 0))
	END AS ENDDATE
FROM VQ_NONCONFORMANCE NCM
LEFT OUTER JOIN VQ_OPERATION O
	ON O.RECORD_ID = NCM.OPERATION_REC_ID
LEFT OUTER JOIN SHOP_RESOURCE_SITE SR
	ON O.CONST_RESOURCE_ID = SR.RESOURCE_ID
WHERE CASE
		WHEN SR.USER_1 = 'A' THEN 'FIN'
		WHEN SR.USER_1 = 'M' THEN 'MFG'
		WHEN SR.USER_1 = 'O' THEN 'OUTREACH'
		WHEN SR.USER_1 = 'B' THEN 'BALLARD'
		WHEN SR.USER_1 = 'C' THEN 'CLOSED'
	END IN (@BUSUNIT)
	AND SR.USER_2 IN (@PRIMARY)
	AND SR.USER_3 IN (@SECONDARY)
	AND SR.USER_4 IN (@SUPERVISOR)
	AND SR.USER_5 IN (@FACILITY)
	AND SR.USER_7 IN (@PROCESS)
	AND SR.USER_8 IN (@DEPARTMENT)
	AND COALESCE(NCM.USER_DEFINED_4, NCM.USER_DEFINED_7, '_Blank') IN (@IQM_DEFECT)
	AND COALESCE(NCM.SK_FIN_NCM_PROCESS, NCM.SK_MFG_NCM_PROCESS, '_BLANK') IN (@IQM_PROCESS)
	AND COALESCE(NCM.SK_FIN_NCM_SUBPROCESS, NCM.SK_MFG_NCM_SUBPROCESS, '_BLANK') IN (@IQM_SUBPROCESS)
	AND NCM.DISPOSITION_TYPE NOT IN ('NON-DISCREPANT', 'OVERAGE')
	AND NCM.DISPOSITION_TYPE IS NOT NULL
	AND
	(
		(@TIMEFRAME = 'LAST WEEK' 
			AND NCM.NCM_DATE >= CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 7, GETDATE()), 0))
			AND NCM.NCM_DATE <=  CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 7, GETDATE()), 6))
		)
		OR (@TIMEFRAME = 'CURRENT WEEK' 
			AND NCM.NCM_DATE >= CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 0))
			AND NCM.NCM_DATE <= CONVERT(DATE, DATEADD(WEEK, DATEDIFF(WEEK, 0, GETDATE()), 6))
		)
		OR (@TIMEFRAME = 'LAST MONTH' 
			AND NCM.NCM_DATE >= CONVERT(DATE, DATEADD(D, -(DAY(DATEADD(M, -1, GETDATE()-2))), DATEADD(M, -1, GETDATE()-1)))
			AND NCM.NCM_DATE <= CONVERT(DATE, DATEADD(D, -(DAY(GETDATE())), GETDATE()))
		)
		OR (@TIMEFRAME = 'CURRENT MONTH' 
			AND NCM.NCM_DATE >= CONVERT(DATE, DATEADD(D, -(DAY(GETDATE()-1)), GETDATE()))
			AND NCM.NCM_DATE <= CONVERT(DATE, DATEADD(D, -(DAY(DATEADD(M, 1, GETDATE()))), DATEADD(M, 1, GETDATE())))
		)
		OR (@TIMEFRAME = 'LAST YEAR' 
			AND NCM.NCM_DATE >= CONVERT(DATE, DATEADD(YEAR, DATEDIFF(YEAR, 0, GETDATE()) - 1, 0))
			AND NCM.NCM_DATE <= CONVERT(DATE, DATEADD(YEAR, DATEDIFF(YEAR, 0, GETDATE()), -1))
		)
		OR (@TIMEFRAME = 'CURRENT YEAR' 
			AND NCM.NCM_DATE >= CONVERT(DATE, DATEADD(YY, DATEDIFF(YY, 0, GETDATE()), 0))
			AND NCM.NCM_DATE <= CONVERT(DATE, DATEADD(YY, DATEDIFF(YY, 0, GETDATE()) + 1, -1))
		)
		OR (@TIMEFRAME = 'LAST QUARTER' 
			AND NCM.NCM_DATE >= CONVERT(DATE, dateadd(quarter, datediff(quarter, 0 , GETDATE()) - 1, 0))
			AND NCM.NCM_DATE <= CONVERT(DATE, dateadd(quarter, datediff(quarter, 0 , GETDATE()) - 1, 0))
		)
		OR (@TIMEFRAME = 'CURRENT QUARTER' 
			AND NCM.NCM_DATE >= DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()), 0)
			AND NCM.NCM_DATE <= DATEADD (DD, -1, DATEADD(QQ, DATEDIFF(QQ, 0, GETDATE()) + 1, 0))
		)
	)

/*
	(
		(@TIMEFRAME = 'LAST YEAR' AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) - 1
			)
		OR (@TIMEFRAME = 'CURRENT YEAR' AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE())
			)
		OR (@TIMEFRAME = 'CURRENT WEEK' AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) AND DATEPART(WW, NCM.NCM_DATE) = DATEPART(WW, GETDATE())
			)
		OR (@TIMEFRAME = 'CURRENT MONTH' AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) AND DATEPART(MM, NCM.NCM_DATE) = DATEPART(MM, GETDATE())
			)
		OR (@TIMEFRAME = 'CURRENT QUARTER' AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) AND DATEPART(QQ, NCM.NCM_DATE) = DATEPART(QQ, GETDATE())
			)
	---- in same year
		OR (@TIMEFRAME = 'LAST WEEK' AND DATEPART(WW, GETDATE()) > 1 AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) AND DATEPART(WW, NCM.NCM_DATE) = DATEPART(WW, GETDATE()) - 1
			)
	---- in different year, over the gap
		OR (@TIMEFRAME = 'LAST WEEK' AND DATEPART(WW, GETDATE()) = 1 AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) - 1 AND DATEPART(WW, NCM.NCM_DATE) >= 52
			)
	---- in same year
		OR (@TIMEFRAME = 'LAST MONTH' AND DATEPART(MM, GETDATE()) > 1 AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) AND DATEPART(MM, NCM.NCM_DATE) = DATEPART(MM, GETDATE()) - 1
			)
	---- in different year, over the gap
		OR (@TIMEFRAME = 'LAST MONTH'  AND DATEPART(MM, GETDATE()) = 1 AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) - 1 AND DATEPART(MM, NCM.NCM_DATE) = 12
			)
	---- in same year
		OR (@TIMEFRAME = 'LAST QUARTER'  AND DATEPART(QQ, GETDATE()) > 1 AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) AND DATEPART(QQ, NCM.NCM_DATE) = DATEPART(QQ, GETDATE()) - 1
			)
	---- in different year, over the gap
		OR (@TIMEFRAME = 'LAST QUARTER' AND DATEPART(QQ, GETDATE()) = 1 AND YEAR(NCM.NCM_DATE) = YEAR(GETDATE()) -1 AND DATEPART(QQ, NCM.NCM_DATE) = 4
			)
	 )

*/
