SELECT CASE
	WHEN [TYPE] = 'I' AND [CLASS] = 'R' THEN 'RECEIVE IN'
	WHEN [TYPE] = 'O' AND [CLASS] = 'R' THEN 'RECEIVE OUT'
	WHEN [TYPE] = 'O' AND [CLASS] = 'I' THEN 'ISSUE OUT'
	WHEN [TYPE] = 'I' AND [CLASS] = 'I' THEN 'ISSUE IN'
	WHEN [TYPE] = 'I' AND [CLASS] = 'A' THEN 'ADJUST IN'
	WHEN [TYPE] = 'O' AND [CLASS] = 'A' THEN 'ADJUST OUT'
	ELSE NULL
END AS INV_TYPES
, SUM(CASE
		WHEN TYPE = 'I' AND CLASS = 'R' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'I' THEN -1
		WHEN TYPE = 'O' AND CLASS = 'A' THEN -1
		WHEN TYPE = 'I' AND CLASS = 'A' THEN 1
		WHEN TYPE = 'I' AND CLASS = 'I' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'R' THEN -1
		ELSE 0
	END * QTY) AS INV_QTY
INTO #CTE_INV