SELECT * FROM LIVESUPPLEMENTAL.[DBO].[OPERATOR_VARIABLE_DATA] OVD WHERE OPERATION_TYPE_ID in (N'STAGING', N'AREVIEW2', N'CMPFL-REVIEW', N'CM-REVIEW', N'CM-REVIEW1', N'FIN-REVIEW', N'MFG-REVIEW', N'REVIEW', N'REVIEW-FAI')
--> 1285 - 6 = 1279

/*
;BEGIN TRANSACTION
DELETE FROM LIVESUPPLEMENTAL.[DBO].[OPERATOR_VARIABLE_DATA]
WHERE RESOURCE_ID = 'P1F1-REVIEW'
AND OPERATION_TYPE_ID = 'AREVIEW2'
--> 6 ROWS
COMMIT TRANSACTION

;BEGIN TRANSACTION
DELETE FROM LIVESUPPLEMENTAL.[DBO].[OPERATOR_VARIABLE_DATA]
WHERE RESOURCE_ID = 'P1F1-REVIEWCM'
AND OPERATION_TYPE_ID = 'CM-REVIEW1'
--> 6 ROWS
COMMIT TRANSACTION
*/