USE LIVE
GO

DECLARE @WOTYPE NVARCHAR(50) = ''
	, @CATEGORY NVARCHAR(50) = ''
	, @REVID NVARCHAR(50) = ''
--	, @BASEID NVARCHAR(50) = '214T3436-7003'
	, @BASEID NVARCHAR(50) = NULL

SELECT D.ID
	, D.[DESCRIPTION]
	, CASE 
		WHEN D.REFERENCE_TYPE =  'G' THEN 'GENERAL'
		ELSE 'LOOKUP'
	END AS REFERENCE_TYPE
	, D.CATEGORY_ID
	, D.REVISION_ID
	, CASE
		WHEN D.[DOC_FILE_PATH] = '-' THEN ''
		WHEN D.[DOC_FILE_PATH] = ' /' THEN ''
		WHEN D.[DOC_FILE_PATH] = '/' THEN ''
		WHEN D.[DOC_FILE_PATH] = '//' THEN ''
		WHEN D.[DOC_FILE_PATH] = '///' THEN ''
		WHEN D.[DOC_FILE_PATH] = '\\' THEN ''
		WHEN D.[DOC_FILE_PATH] = '\\\' THEN ''
		ELSE D.[DOC_FILE_PATH]
	END AS [DOC_FILE_PATH]
	, D.[STAGE_ID]
	, D.[USER_10]
	, D.[ALLOW_EMAIL]
	, D.[PATH_TYPE]
	, D.[ECN_REVISION]
	, D.[ECN_REV_CONTROL]
	, UDF31.STRING_VAL AS [Location]
	, UDF32.STRING_VAL AS [ADCN]
	, UDF33.STRING_VAL AS [Serial Number]
	, UDF34.STRING_VAL AS [MFG Note]
	, UDF50.STRING_VAL AS [Property]
	, CASE
		WHEN UDF51.BOOL_VAL = '1' THEN 'YES'
		ELSE 'NO'
	END AS [ITAR Controlled]
	, UDF52.STRING_VAL AS [Status]
	, CASE
		WHEN UDF53.BOOL_VAL = '1' THEN 'YES'
		ELSE 'NO'
	END AS [Received Date]
	, UDF54.STRING_VAL AS [Stamped Revision]
	, UDF55.NUMBER_VAL AS [Number of Pieces]
	, UDF56.STRING_VAL AS [Usage Instructions]
	, UDF57.STRING_VAL AS [AUTM]
	, UDF58.STRING_VAL AS [Category]
	, UDF59.STRING_VAL AS [Current Location]
	, ISNULL(DRW.WORKORDER_TYPE, '-') AS WORKORDER_TYPE
	, DRW.WORKORDER_BASE_ID
	, DRW.WORKORDER_LOT_ID 
	, DRW.WORKORDER_SPLIT_ID
	, DRW.WORKORDER_SUB_ID
	, DRW.SEQUENCE_NO
	, DRW.PIECE_NO
FROM DOCUMENT D
LEFT OUTER JOIN DOCUMENT_REF_WO DRW
	ON D.ID = DRW.DOCUMENT_ID 
LEFT OUTER JOIN USER_DEF_FIELDS UDF31
	ON UDF31.[PROGRAM_ID] = 'VMDOCMNT'
	AND D.ID = UDF31.DOCUMENT_ID
	AND UDF31.ID = 'UDF-0000031'
LEFT OUTER JOIN USER_DEF_FIELDS UDF32
	ON UDF32.[PROGRAM_ID] = 'VMDOCMNT'
	AND D.ID = UDF32.DOCUMENT_ID
	AND UDF32.ID = 'UDF-0000032'
LEFT OUTER JOIN USER_DEF_FIELDS UDF33
	ON UDF33.[PROGRAM_ID] = 'VMDOCMNT'
	AND D.ID = UDF33.DOCUMENT_ID
	AND UDF33.ID = 'UDF-0000033'
LEFT OUTER JOIN USER_DEF_FIELDS UDF34
	ON UDF34.[PROGRAM_ID] = 'VMDOCMNT'
	AND D.ID = UDF34.DOCUMENT_ID
	AND UDF34.ID = 'UDF-0000034'
LEFT OUTER JOIN USER_DEF_FIELDS UDF50
	ON UDF50.[PROGRAM_ID] = 'VMDOCMNT'
	AND D.ID = UDF50.DOCUMENT_ID
	AND UDF50.ID = 'UDF-0000050'
LEFT OUTER JOIN USER_DEF_FIELDS UDF51
	ON UDF51.[PROGRAM_ID] = 'VMDOCMNT'
	AND D.ID = UDF51.DOCUMENT_ID
	AND UDF51.ID = 'UDF-0000051'
LEFT OUTER JOIN USER_DEF_FIELDS UDF52
	ON UDF52.[PROGRAM_ID] = 'VMDOCMNT'
	AND D.ID = UDF52.DOCUMENT_ID
	AND UDF52.ID = 'UDF-0000052'
LEFT OUTER JOIN USER_DEF_FIELDS UDF53
	ON UDF53.[PROGRAM_ID] = 'VMDOCMNT'
	AND D.ID = UDF53.DOCUMENT_ID
	AND UDF53.ID = 'UDF-0000053'
LEFT OUTER JOIN USER_DEF_FIELDS UDF54
	ON UDF54.[PROGRAM_ID] = 'VMDOCMNT'
	AND D.ID = UDF54.DOCUMENT_ID
	AND UDF54.ID = 'UDF-0000054'
LEFT OUTER JOIN USER_DEF_FIELDS UDF55
	ON UDF55.[PROGRAM_ID] = 'VMDOCMNT'
	AND D.ID = UDF55.DOCUMENT_ID
	AND UDF55.ID = 'UDF-0000055'
LEFT OUTER JOIN USER_DEF_FIELDS UDF56
	ON UDF56.[PROGRAM_ID] = 'VMDOCMNT'
	AND D.ID = UDF56.DOCUMENT_ID
	AND UDF56.ID = 'UDF-0000056'
LEFT OUTER JOIN USER_DEF_FIELDS UDF57
	ON UDF57.[PROGRAM_ID] = 'VMDOCMNT'
	AND D.ID = UDF57.DOCUMENT_ID
	AND UDF57.ID = 'UDF-0000057'
LEFT OUTER JOIN USER_DEF_FIELDS UDF58
	ON UDF58.[PROGRAM_ID] = 'VMDOCMNT'
	AND D.ID = UDF58.DOCUMENT_ID
	AND UDF58.ID = 'UDF-0000058'
LEFT OUTER JOIN USER_DEF_FIELDS UDF59
	ON UDF59.[PROGRAM_ID] = 'VMDOCMNT'
	AND D.ID = UDF59.DOCUMENT_ID
	AND UDF59.ID = 'UDF-0000059'

--WHERE ISNULL(WORKORDER_TYPE, '-') IN (@WOTYPE)
--	AND CATEGORY_ID IN (@CATEGORY)
--	AND REVISION_ID IN (@REVID)
--	AND (WORKORDER_BASE_ID LIKE '%' + @BASEID + '%' OR WORKORDER_BASE_ID IS NULL)
