USE LIVE
GO

DECLARE @ECID NVARCHAR(15) = 'EC-04385'

SELECT *
FROM [LIVE].[dbo].[EC]
--WHERE STATUS != 'C'
--where create_date >= '8/17/2020'    ---originator = 'cathie'
--and create_date >= '8/17/2020'
WHERE ID = @ECID

/*
BEGIN TRANSACTION;
UPDATE EC
SET [STATUS] = 'I'
, ORIGINATOR = 'KEITHW'
, ORIGIN_ID = 'KEITHW'
, ASSIGNED_TO = 'KEITHW'
, CREATED_BY = 'KEITHW'
--, APRV_DATE = GETDATE()
--, EXT_TASKS_DONE = 'N'
WHERE ID IN ('EC-04385')
-->COMMIT TRANSACTION;

BEGIN TRANSACTION;
DELETE FROM EC
WHERE ID IN ('5141-701(AMT1)')
-->COMMIT TRANSACTION;

*/

SELECT *
FROM [LIVE].[dbo].[EC_LINE]
--WHERE WO_BASE_ID = '413A3008-59B'
WHERE EC_ID = @ECID

/*
BEGIN TRANSACTION;
UPDATE EC_LINE
SET [STATUS] = 'X'
WHERE EC_ID = 'EC-04387'
AND LINE_NO IN ('1', '2')
-->COMMIT TRANSACTION;

BEGIN TRANSACTION;
DELETE FROM EC_LINE
WHERE EC_ID = 'EC-04245'
AND LINE_NO IN ('2')
-->COMMIT TRANSACTION;

*/

SELECT *
FROM [LIVE].[dbo].[EC_GROUP_USER]
WHERE EC_ID = @ECID

/*
INSERT INTO [LIVE].[dbo].[EC_GROUP_USER] VALUES ('DC-2021-233', 'A', 'KEITHW', NULL, GETDATE(), NULL)
INSERT INTO [LIVE].[dbo].[EC_GROUP_USER] VALUES ('8914-2001-02', 'AP', 'SHAWN', NULL, GETDATE(), 'Y')

BEGIN TRANSACTION;
UPDATE [EC_GROUP_USER]
SET [USER_ID] = 'KEITHW'
--, [USER_SIGNOFF] = NULL
WHERE EC_ID = 'EC-04385'
AND GROUP_TYPE = 'AT'
--AND [USER_ID] IN ('SHANNEN', 'SHAWN')
AND ROWID IN (186135, 186141)
-->COMMIT TRANSACTION;

BEGIN TRANSACTION;
DELETE FROM [EC_GROUP_USER]
WHERE EC_ID = 'EC-04385'
AND GROUP_TYPE = 'I'
AND [USER_ID] IN ('ELIZABETHW')
AND ROWID IN (186141)
-->COMMIT TRANSACTION;
*/

SELECT *
FROM [LIVE].[dbo].[task]
--where task_no = '10605'
--WHERE USER_ID = 'ERICC'
WHERE EC_ID = @ECID

/*
INSERT INTO [LIVE].[dbo].[TASK] values ('ECN', '8465', '10', 'KEITHW', 'A', 'DC-2021-233', 'P', NULL, NULL, NULL, NULL, GETDATE(), NULL, GETDATE())
--insert into [LIVE].[dbo].[task] values ('ECN', '6097', '8', 'SHAWN', 'AP', '8914-2001-02', 'P', NULL, NULL, NULL, NULL, GETDATE(), NULL, GETDATE())

BEGIN TRANSACTION;
UPDATE TASK
SET STATUS = 'P'
, USER_ID = 'KEITHW'
--, COMPLETED_DATE = GETDATE()
--, REJ_TASK_NO = NULL
--, REJ_SEQ_NO = NULL
--, SUB_TYPE = 'A'
WHERE EC_ID = 'EC-04385'
AND TASK_NO = '9157'
AND SEQ_NO IN ('1')
--AND [STATUS] NOT IN ('C', 'X')
-->COMMIT TRANSACTION;

BEGIN TRANSACTION;
DELETE FROM TASK
WHERE EC_ID = 'EC-04385'
AND TASK_NO = '9157'
AND SEQ_NO IN ('3')
AND ROWID IN ('81150')
--AND [STATUS] NOT IN ('C', 'X')
--> COMMIT TRANSACTION;

*/

/*
SELECT *
	, CAST(CAST(EB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [BINARY]
FROM EC_LINE_BINARY EB
WHERE EC_ID = @ECID

SELECT *
	, CAST(CAST(EB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [BINARY]
FROM EC_RESPONSE EB
WHERE EC_ID = @ECID

SELECT *
	, CAST(CAST(EB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [BINARY]
FROM EC_HISTORY EB
WHERE EC_ID = @ECID

SELECT *
	, CAST(CAST(EB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [BINARY]
FROM EC_REQUEST EB
WHERE EC_ID = @ECID

/*
UPDATE EC_REQUEST
SET BINARY = CAST(CAST(CAST(CAST(EB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) 
*/

SELECT *
	, CAST(CAST(EB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [BINARY]
FROM TASK_BINARY EB
INNER JOIN TASK T
ON EB.TASK_NO = T.TASK_NO
AND EB.SEQ_NO = T.SEQ_NO
AND TASK_TYPE = 'ECN'
WHERE EC_ID = @ECID
AND EB.TASK_TYPE = 'ECN'


*/



