USE LIVE
GO

DECLARE @ECID NVARCHAR(15) = 'EC-02804'


SELECT EC.ID AS EC_ID
, EC.[STATUS]
, EC.CREATE_DATE
, EC.WANT_DATE
, EC.ORIGINATOR
, EC.ASSIGNED_TO
--, ECG.GROUP_TYPE
--, ECG.[USER_ID]
, T.[TYPE]
, T.TASK_NO
, T.SEQ_NO
, T.[USER_ID]
, T.[STATUS]
FROM [LIVE].[dbo].[EC]
LEFT OUTER JOIN EMPLOYEE EE
ON EC.ASSIGNED_TO = EE.[USER_ID]
--LEFT OUTER JOIN [LIVE].[dbo].[EC_GROUP_USER] ECG
--ON ECG.EC_ID = EC.ID
--LEFT OUTER JOIN EMPLOYEE EEG
--ON ECG.[USER_ID] = EEG.[USER_ID]
LEFT OUTER JOIN [LIVE].[dbo].[TASK] T
ON T.EC_ID = EC.ID
AND T.[STATUS] NOT IN ('C', 'X')
LEFT OUTER JOIN EMPLOYEE EET
ON T.[USER_ID] = EET.[USER_ID]
WHERE EC.[STATUS] NOT IN ('C', 'X')
AND (
	EET.[USER_ID] IS NULL AND T.[STATUS] NOT IN ('C', 'X')
	OR 
	EE.[USER_ID] IS NULL
	)
