USE LIVE
GO

DECLARE @STARTDATE DATE = '6/1/2020'

SELECT ID AS EC_ID
	, ORIGINATOR
	, [STATUS]
	, REQUEST_DATE
	, WANT_DATE
	, AUTH_DATE
	, IMPL_DATE
	, APRV_DATE
FROM EC
WHERE IMPL_DATE >= @STARTDATE --IS NOT NULL
--	AND APRV_DATE IS NULL
--	AND [STATUS] NOT IN ('C', 'X')