USE LIVE
GO

DECLARE @ECID NVARCHAR(15) = 'EC-01920'

; WITH CTE_USERS AS
(SELECT [USER_ID] FROM EMPLOYEE WHERE [USER_ID] IS NOT NULL)

SELECT EC.ID
	, EC.ORIGINATOR
	, EC.ASSIGNED_TO
	, EC.[STATUS]
	, EC.ON_HOLD_STATUS
	, EC.REQUEST_DATE
	, EC.WANT_DATE
	, EC.AUTH_DATE
	, EC.IMPL_DATE
	, EC.APRV_DATE
	, EC.DIST_DATE
	, EC.ORIGIN_ID
	, EC.CREATED_BY
	, EC.UPDATE_PART_REV
	, EC.UPDATE_DOC_REV
	, EC.UPDATE_LEVEL
	, T.[TYPE]
	, T.TASK_NO
	, T.SEQ_NO
	, T.[USER_ID]
	, T.SUB_TYPE
	, T.[STATUS]
FROM [LIVE].[dbo].[EC]
LEFT OUTER JOIN [LIVE].[dbo].[EC_GROUP_USER] ECG
	ON EC.ID = ECG.EC_ID
LEFT OUTER JOIN [LIVE].[dbo].[TASK] T
	ON EC.ID = T.EC_ID
	AND ECG.GROUP_TYPE = T.SUB_TYPE
	AND ECG.[USER_ID] = T.[USER_ID]
WHERE T.[STATUS] NOT IN ('C', 'X')
	AND EC.[STATUS] NOT IN ('C', 'X')
	AND (
		EC.ASSIGNED_TO NOT IN (SELECT * FROM CTE_USERS CTE WHERE EC.ASSIGNED_TO = CTE.[USER_ID])
		OR 
		EC.ORIGINATOR NOT IN (SELECT * FROM CTE_USERS CTE WHERE EC.ORIGINATOR = CTE.[USER_ID])
		OR 
		EC.ORIGIN_ID NOT IN (SELECT * FROM CTE_USERS CTE WHERE EC.ORIGIN_ID = CTE.[USER_ID])
		OR 
		EC.CREATED_BY NOT IN (SELECT * FROM CTE_USERS CTE WHERE EC.CREATED_BY = CTE.[USER_ID])
		OR 
		T.[USER_ID] NOT IN (SELECT * FROM CTE_USERS CTE WHERE T.[USER_ID] = CTE.[USER_ID])
		)
--AND EC.ID = @ECID


