--> DON'T FORGET SUBSCRIPTIONS

SELECT TOP (1000) [ROWID]
      ,[GROUP_ID]
      ,[USER_ID]
      ,[IS_LEADER]
      ,[CREATE_DATE]
      ,[USER_SIGNOFF]
  FROM [LIVE].[dbo].[GROUP_USER]
  where user_id = 'shannen'

SELECT ID AS RESOURCE_ID
, [DESCRIPTION]
, USER_6 AS DEPARTMENT
, USER_7 AS PROCESS
, USER_4 AS SUPERVISOR
FROM SHOP_RESOURCE 
WHERE (USER_4 LIKE 'SHANNEN%' OR USER_4 LIKE 'JACOB HELLE%') 
	AND (STATUS IS NULL OR STATUS != 'O')
ORDER BY USER_4

/*
UPDATE SHOP_RESOURCE
SET USER_4 = 'MICHAEL KEIL'
WHERE ID IN (SELECT ID FROM SHOP_RESOURCE WHERE USER_4 = 'JACOB BROWN')

UPDATE SHOP_RESOURCE
SET USER_4 = 'JACOB BROWN'
WHERE ID IN (SELECT ID FROM SHOP_RESOURCE WHERE USER_4 = 'JACOB HELLE')

UPDATE SHOP_RESOURCE
SET USER_4 = 'KEITH WOOLRIDGE'
WHERE ID IN (SELECT ID FROM SHOP_RESOURCE WHERE USER_4 = 'SHANNEN HELLE')

UPDATE SHOP_RESOURCE_SITE
SET USER_4 = 'MICHAEL KEIL'
WHERE RESOURCE_ID IN (SELECT RESOURCE_ID FROM SHOP_RESOURCE_SITE WHERE USER_4 = 'JACOB BROWN')

UPDATE SHOP_RESOURCE_SITE
SET USER_4 = 'JACOB BROWN'
WHERE RESOURCE_ID IN (SELECT ID FROM SHOP_RESOURCE WHERE USER_4 = 'JACOB BROWN')

UPDATE SHOP_RESOURCE_SITE
SET USER_4 = 'KEITH WOOLRIDGE'
WHERE RESOURCE_ID IN (SELECT RESOURCE_ID FROM SHOP_RESOURCE_SITE WHERE USER_4 = 'SHANNEN HELLE')

*/

SELECT *
FROM [EC]
LEFT OUTER JOIN EC_LINE ECL
	ON EC.ID = ECL.EC_ID
WHERE EC.[STATUS] != 'C'
	AND EC.ORIGINATOR = 'SHANNEN'
	AND EC.ORIGIN_ID = 'SHANNEN'
	AND EC.ASSIGNED_TO = 'SHANNEN'
	AND EC.CREATED_BY = 'SHANNEN'

SELECT *
FROM [LIVE].[dbo].[EC]
LEFT OUTER JOIN EC_LINE ECL
ON EC.ID = ECL.EC_ID 
WHERE EC.STATUS != 'C'
AND (ORIGINATOR = 'SHANNEN' OR ASSIGNED_TO = 'SHANNEN')

SELECT *
FROM [LIVE].[dbo].[task]
WHERE USER_ID = 'SHANNEN'
AND STATUS NOT IN ('X', 'C')