use live
go

-- VISUAL ENTERPRISE > LABOR REPORTS > EE_Op_Counts
declare @CALDATE date = '3/1/2018'
DECLARE	@STARTWEEK DATE = DATEADD(DD, -(DATEPART(DW, @CALDATE)-3), @CALDATE)
DECLARE @ENDWEEK DATE = DATEADD(DD, 7-(DATEPART(DW, @CALDATE)-2), @CALDATE)
;

SELECT EMPLOYEE_ID
	, [LAST NAME]
	, [FIRST NAME]
	, [JOB TITLE]
	, [LOCATION]
	, DEPARTMENT_ID
	, [ASSIGNED SHIFT CODE] AS [SHIFT]
	, CONVERT(DATE, LT.CLOCK_IN) AS CLOCKIN
	, COUNT(*) AS DAILY_TOTAL
FROM LABOR_TICKET LT
INNER JOIN LIVESUPPLEMENTAL.DBO.EMP_ADP ADP
	ON LT.EMPLOYEE_ID = ADP.EMPID
WHERE WORKORDER_TYPE IS NOT NULL 
	AND CONVERT(DATE, LT.CLOCK_IN) BETWEEN @STARTWEEK AND @ENDWEEK
	AND LT.SETUP_COMPLETED = 'Y' 
	AND LT.TYPE ='R'
GROUP BY EMPLOYEE_ID
	, [LAST NAME]
	, [FIRST NAME]
	, [JOB TITLE]
	, [LOCATION]
	, DEPARTMENT_ID
	, [ASSIGNED SHIFT CODE]
	, CONVERT(DATE, LT.CLOCK_IN)