USE LIVE
GO

SELECT ID AS PART_ID
, FABRICATED
, INSPECTION_REQD
FROM PART
WHERE ([STATUS] IS NULL OR [STATUS] != 'O')
AND FABRICATED = 'Y'
AND INSPECTION_REQD = 'Y'
UNION
SELECT PART_ID
, FABRICATED
, INSPECTION_REQD
FROM PART_SITE
WHERE ([STATUS] IS NULL OR [STATUS] != 'O')
AND FABRICATED = 'Y'
AND INSPECTION_REQD = 'Y'