--http://SQL-BI-1/reports/api/v2.0/datasets(Path='/Datasets/WODailyStatusData')/data


SELECT O.WORKORDER_BASE_ID AS BASE_ID
	, O.WORKORDER_LOT_ID AS LOT_ID
	, O.WORKORDER_SPLIT_ID AS SPLIT_ID
	, O.WORKORDER_SUB_ID AS SUB_ID
	, O.WORKORDER_BASE_ID + CASE 
			WHEN O.WORKORDER_SUB_ID != 0 THEN '-' + O.WORKORDER_SUB_ID
			ELSE ''
			END 
		+ '/' + O.WORKORDER_LOT_ID + CASE
			WHEN O.WORKORDER_SPLIT_ID != '0' THEN '.' + O.WORKORDER_SPLIT_ID
			ELSE ''
	END AS WONUM
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.OPERATION_TYPE
	, O.[STATUS] AS OSTATUS
	, O.CLOSE_DATE
	, WO.PART_ID
	, WO.DESIRED_QTY
	, WO.DESIRED_WANT_DATE
	, LT.EMPLOYEE_ID
	, LT.CLOCK_IN
	, LT.CLOCK_OUT
	, LT.HOURS_WORKED
	, LT.GOOD_QTY
	, LT.BAD_QTY
	, LT.TRANSACTION_DATE
	, LT.[ACT_BURDEN_COST]
	, LT.[ACT_LABOR_COST]
	, EE.[FIRST_NAME] + ' ' + EE.[LAST_NAME] AS FULLNAME
	, EE.SHIFT_ID
	, EE.DEPARTMENT_ID
	, SR.USER_1 AS SKILLS_TYPE
	, SR.USER_2 AS PRIMARY_GROUP
	, SR.USER_3 AS SECONDARY_GROUP
	, SR.USER_4 AS DEPT_SUPV
	, SR.USER_5 AS FACILITY
	, SR.USER_8 AS REPT_DEPT
FROM DataWarehouse.dbo.OPERATION O
INNER JOIN DataWarehouse.dbo.WORK_ORDER WO
	ON WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O.WORKORDER_SUB_ID
	AND WO.[TYPE] = O.WORKORDER_TYPE
LEFT OUTER JOIN DataWarehouse.dbo.LABOR_TICKET LT
	ON O.WORKORDER_BASE_ID = LT.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = LT.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = LT.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = LT.WORKORDER_TYPE
	AND LT.OPERATION_SEQ_NO = O.SEQUENCE_NO
LEFT OUTER JOIN DataWarehouse.dbo.EMPLOYEE EE
	ON LT.EMPLOYEE_ID = EE.ID
LEFT OUTER JOIN DataWarehouse.dbo.[SHIFT] S
	ON EE.SHIFT_ID = S.ID
LEFT OUTER JOIN DataWarehouse.dbo.[SHOP_RESOURCE] SR
	ON SR.ID = O.RESOURCE_ID
WHERE O.WORKORDER_TYPE = 'W'
AND LT.TRANSACTION_DATE >= DATEADD(YEAR, -1,GETDATE())
--AND ISNULL(WO.CREATE_DATE) >= DATEADD(YEAR, -1,GETDATE())
