USE LIVE
GO

/*
We are looking at some contracted POP parts that we will be renewing and noticed there are times when we are sending 
the job out to outside machining, but its costing us more to send them out than we are being paid for the part itself. 
Is there a way to get a report that will show us by part number, what we are spending on the outside machining? 
Then Ann can push that against her demand list to see what we should either put out for re-bid or pull 
back in house.

We are needing something a little different. We need a list of all PN that have a contractor (or multiple) operations, 
the cost we spent per part at the OM and the price we currently get paid to make them. The last time we ran the job is 
sufficient, we don’t need cost line by PO line. We would like just outside machining, but outside processing also uses 
the contractor op. Would there be a way to have which vendor the part is going to?
*/

SELECT WO.[TYPE]
, WO.BASE_ID
, WO.LOT_ID
, WO.SPLIT_ID
, WO.SUB_ID
, WO.PART_ID
, WO.DESIRED_QTY
, WO.CREATE_DATE
, WO.CLOSE_DATE
, WO.[STATUS]
, WO.ACT_MATERIAL_COST
, WO.ACT_LABOR_COST
, WO.ACT_BURDEN_COST
, WO.ACT_SERVICE_COST
, WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_BURDEN_COST + WO.ACT_SERVICE_COST AS WO_COSTS
, PO.ID AS PO_ID
, PO.VENDOR_ID
, PO.ORDER_DATE
, PO.DESIRED_RECV_DATE
, PO.[STATUS] AS PO_STATUS
--, (SELECT SUM(POL.TOTAL_AMT_RECVD) 
--	FROM PURC_ORDER_LINE POL
--	WHERE DSL.SUPPLY_BASE_ID = POL.PURC_ORDER_ID
----		AND DSL.SUPPLY_SEQ_NO = POL.LINE_NO
--		AND DSL.[SUPPLY_TYPE] = 'PO'
--	GROUP BY POL.PURC_ORDER_ID
--	) AS POL_AMT_RECVD
--, (SELECT SUM(POL.TOTAL_AMT_ORDERED) 
--	FROM PURC_ORDER_LINE POL
--	WHERE DSL.SUPPLY_BASE_ID = POL.PURC_ORDER_ID
----		AND DSL.SUPPLY_SEQ_NO = POL.LINE_NO
--		AND DSL.[SUPPLY_TYPE] = 'PO'
--	GROUP BY POL.PURC_ORDER_ID
--	) AS POL_AMT_ORDERED

--'WO' AS MSG01
--, WO.*
--, 'IT' AS MSG02
--, IT.*
--, 'ITD' AS MSG03
--, ITD.*
--, 'OT' AS MSG04
--, OT.*
--, 'SL' AS MSG05
--, SL.*
--, 'COL' AS MSG06
--, COL.*
--, 'RL' AS MSG07
--, RL.*
--, 'S' AS MSG08
--, S.*
--, 'CO' AS MSG09
--, CO.*
--, 'R' AS MSG10
--, R.*
--, 'PS' AS MSG11
--, PS.*
--, 'DSL' AS MSG12
--, DSL.*
--, 'PO' AS MSG13
--, PO.*
--, 'POL' AS MSG14
--, POL.*
FROM LIVE.dbo.WORK_ORDER WO
LEFT OUTER JOIN LIVE.dbo.PART_SITE PS
ON WO.PART_ID = PS.PART_ID
--LEFT OUTER JOIN LIVE.dbo.OPERATION O
--	ON O.WORKORDER_BASE_ID = WO.BASE_ID
--	AND O.WORKORDER_LOT_ID = WO.LOT_ID
--	AND O.WORKORDER_SPLIT_ID = WO.SPLIT_ID
--	AND O.WORKORDER_SUB_ID = WO.SUB_ID
--	AND O.WORKORDER_TYPE = WO.[TYPE]

--> ISSUED OUT OF INVENTORY
--LEFT OUTER JOIN LIVE.dbo.INVENTORY_TRANS IT
--	ON IT.WORKORDER_BASE_ID = WO.BASE_ID
--	AND IT.WORKORDER_LOT_ID = WO.LOT_ID
--	AND IT.WORKORDER_SPLIT_ID = WO.SPLIT_ID
--	AND IT.WORKORDER_SUB_ID = WO.SUB_ID
--	AND IT.WORKORDER_TYPE = WO.[TYPE]

--LEFT OUTER JOIN LIVE.dbo.INV_TRANS_DIST ITD
--	ON IT.TRANSACTION_ID = ITD.IN_TRANS_ID

----> TAKEN OUT OF INVENTORY, ISSUED TO CUSTOMER ORDER
--LEFT OUTER JOIN LIVE.dbo.INVENTORY_TRANS OT
--	ON ITD.OUT_TRANS_ID = OT.TRANSACTION_ID
--LEFT OUTER JOIN LIVE.dbo.SHIPPER_LINE SL
--	ON SL.TRANSACTION_ID = OT.TRANSACTION_ID
--LEFT OUTER JOIN LIVE.dbo.CUST_ORDER_LINE COL
--	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
--	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
--	AND COL.PART_ID IS NOT NULL
--LEFT OUTER JOIN LIVE.dbo.RECEIVABLE_LINE RL
--	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
--	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
--	AND SL.PACKLIST_ID = RL.PACKLIST_ID 
--	AND SL.LINE_NO = RL.PACKLIST_LINE_NO 
--	AND RL.PACKLIST_ID IS NOT NULL
--LEFT OUTER JOIN LIVE.dbo.SHIPPER S
--	ON SL.PACKLIST_ID = S.PACKLIST_ID 
--LEFT OUTER JOIN LIVE.dbo.CUSTOMER_ORDER CO
--	ON COL.CUST_ORDER_ID = CO.ID
--LEFT OUTER JOIN LIVE.dbo.RECEIVABLE R
--	ON RL.INVOICE_ID = R.INVOICE_ID
--LEFT OUTER JOIN LIVE.dbo.TRACE_INV_TRANS  T
--	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
--LEFT OUTER JOIN LIVE.dbo.DEMAND_SUPPLY_LINK DSL
--	ON DSL.DEMAND_TYPE = 'CO'
--	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
--	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO

--> PO ISSUED FOR WO
LEFT OUTER JOIN [LIVE].[dbo].[DEMAND_SUPPLY_LINK] DSL
ON DSL.[DEMAND_TYPE] = 'OP'
AND DSL.DEMAND_BASE_ID = WO.BASE_ID
AND DSL.DEMAND_LOT_ID = WO.LOT_ID
AND DSL.DEMAND_SPLIT_ID = WO.SPLIT_ID
AND DSL.DEMAND_SUB_ID = WO.SUB_ID
--AND DSL.DEMAND_SEQ_NO = O.SEQUENCE_NO
LEFT OUTER JOIN PURC_ORDER_LINE POL
ON DSL.SUPPLY_BASE_ID = POL.PURC_ORDER_ID
AND DSL.SUPPLY_SEQ_NO = POL.LINE_NO
AND DSL.[SUPPLY_TYPE] = 'PO'
LEFT OUTER JOIN [LIVE].[dbo].PURCHASE_ORDER PO
ON PO.ID = DSL.SUPPLY_BASE_ID
WHERE WO.PART_ID != 'REWORK MFG'
AND WO.CREATE_DATE >= '1/1/2020'
AND WO.[STATUS] = 'C'

AND WO.BASE_ID IN ('1610070')--('1618677')
--('1594233', '1342914')--, '1463115', '1581739', '1583115', '1584517')
--AND S.SHIPPED_DATE >= @START
--AND SL.SHIPPED_QTY <> 0
--AND DSL.SUPPLY_BASE_ID IS NULL
--AND COL.ORDER_QTY > 0
AND EXISTS (SELECT 1
	FROM [LIVE].[dbo].OPERATION O
	WHERE WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O.WORKORDER_SUB_ID
	AND WO.[TYPE] = O.WORKORDER_TYPE
	AND O.RESOURCE_ID = 'CONTRACTOR'
	)
GROUP BY WO.[TYPE]
, WO.BASE_ID
, WO.LOT_ID
, WO.SPLIT_ID
, WO.SUB_ID
, WO.PART_ID
, WO.DESIRED_QTY
, WO.CREATE_DATE
, WO.CLOSE_DATE
, WO.[STATUS]
, WO.ACT_MATERIAL_COST
, WO.ACT_LABOR_COST
, WO.ACT_BURDEN_COST
, WO.ACT_SERVICE_COST
, DSL.SUPPLY_BASE_ID
, DSL.DEMAND_SEQ_NO
, DSL.[SUPPLY_TYPE]
, PO.ID
, PO.VENDOR_ID
, PO.ORDER_DATE
, PO.DESIRED_RECV_DATE
, PO.[STATUS] 
ORDER BY WO.[TYPE]
, WO.BASE_ID
, WO.LOT_ID
, WO.SPLIT_ID
, WO.SUB_ID
, PO.ID

/*
--, IT.TRANSACTION_ID
--, IT.WORKORDER_TYPE
--, IT.WORKORDER_BASE_ID
--, IT.WORKORDER_LOT_ID
--, IT.WORKORDER_SPLIT_ID
--, IT.WORKORDER_SUB_ID
--, IT.OPERATION_SEQ_NO
--, IT.REQ_PIECE_NO
--, IT.CUST_ORDER_ID
--, IT.CUST_ORDER_LINE_NO
--, IT.PURC_ORDER_ID
--, IT.PURC_ORDER_LINE_NO
--, IT.PART_ID
--, IT.[TYPE]
--, IT.CLASS
--, CASE
--	WHEN IT.[TYPE] = 'I' AND IT.CLASS = 'R' THEN 'RETURN ISSUE'
--	WHEN IT.[TYPE] = 'O' AND IT.CLASS = 'I' THEN 'ISSUED OUT'
--	WHEN IT.[TYPE] = 'O' AND IT.CLASS = 'A' THEN 'ADJUST OUT'
--	WHEN IT.[TYPE] = 'I' AND IT.CLASS = 'A' THEN 'ADJUST IN'
--	WHEN IT.[TYPE] = 'I' AND IT.CLASS = 'I' THEN 'ISSUE RETURN'
--	WHEN IT.[TYPE] = 'O' AND IT.CLASS = 'R' THEN 'RECEIVER RETURN'
--	ELSE 'INVALID'
--END AS IN_INV_DESC
--, IT.QTY
--, IT.COSTED_QTY
--, IT.TRANSACTION_DATE
--, IT.WAREHOUSE_ID
--, IT.LOCATION_ID
--, IT.[DESCRIPTION]
--, IT.[USER_ID]
--, IT.ACT_MATERIAL_COST
--, IT.ACT_LABOR_COST
--, IT.ACT_BURDEN_COST
--, IT.ACT_SERVICE_COST
--, ITD.IN_TRANS_ID
--, ITD.OUT_TRANS_ID
--, ITD.DIST_QTY
--, ITD.ACT_MATERIAL_COST
--, ITD.ACT_LABOR_COST
--, ITD.ACT_BURDEN_COST
--, ITD.ACT_SERVICE_COST
--, ITD.DEMAND_SUPPLY_ID
--, OT.TRANSACTION_ID
--, OT.WORKORDER_TYPE
--, OT.WORKORDER_BASE_ID
--, OT.WORKORDER_LOT_ID
--, OT.WORKORDER_SPLIT_ID
--, OT.WORKORDER_SUB_ID
--, OT.OPERATION_SEQ_NO
--, OT.REQ_PIECE_NO
--, OT.CUST_ORDER_ID
--, OT.CUST_ORDER_LINE_NO
--, OT.PURC_ORDER_ID
--, OT.PURC_ORDER_LINE_NO
--, OT.PART_ID
--, OT.[TYPE]
--, OT.CLASS
--, CASE
--	WHEN OT.[TYPE] = 'I' AND OT.CLASS = 'R' THEN 'RETURN ISSUE'
--	WHEN OT.[TYPE] = 'O' AND OT.CLASS = 'I' THEN 'ISSUED'
--	WHEN OT.[TYPE] = 'O' AND OT.CLASS = 'A' THEN 'ADJUST OUT'
--	WHEN OT.[TYPE] = 'I' AND OT.CLASS = 'A' THEN 'ADJUST IN'
--	WHEN OT.[TYPE] = 'I' AND OT.CLASS = 'I' THEN 'ISSUE RETURN'
--	WHEN OT.[TYPE] = 'O' AND OT.CLASS = 'R' THEN 'RECEIVER RETURN'
--	ELSE 'INVALID'
--END AS OUT_INV_DESC
--, OT.QTY
--, OT.COSTED_QTY
--, OT.TRANSACTION_DATE
--, OT.ADJ_REASON_ID
--, OT.ACT_MATERIAL_COST
--, OT.ACT_LABOR_COST
--, OT.ACT_BURDEN_COST
--, OT.ACT_SERVICE_COST
--, OT.CREATE_DATE
--, SL.PACKLIST_ID
--, SL.LINE_NO
--, SL.CUST_ORDER_ID
--, SL.CUST_ORDER_LINE_NO
--, SL.USER_SHIPPED_QTY
--, SL.SHIPPED_QTY
--, SL.TRANSACTION_ID
--, SL.UNIT_PRICE
--, COL.CUST_ORDER_ID
--, COL.LINE_NO
--, COL.PART_ID
--, COL.CUSTOMER_PART_ID
--, COL.LINE_STATUS
--, COL.ORDER_QTY
--, COL.USER_ORDER_QTY
--, COL.DESIRED_SHIP_DATE
--, COL.UNIT_PRICE
--, COL.MISC_REFERENCE
--, COL.PRODUCT_CODE
--, COL.COMMODITY_CODE
--, COL.TOTAL_SHIPPED_QTY
--, COL.TOTAL_USR_SHIP_QTY
--, COL.TOTAL_AMT_SHIPPED
--, COL.TOTAL_AMT_ORDERED
--, RL.INVOICE_ID
--, RL.LINE_NO
--, RL.REFERENCE
--, RL.QTY
--, RL.AMOUNT
--, RL.CUST_ORDER_ID
--, RL.CUST_ORDER_LINE_NO
--, RL.PACKLIST_ID
--, RL.PACKLIST_LINE_NO
--, S.CUST_ORDER_ID
--, S.SHIPPED_DATE
--, S.INVOICE_ID
--, S.INVOICED_DATE
--, S.CREATE_DATE
--, CO.CUSTOMER_ID
--, CO.CUSTOMER_PO_REF
--, CO.SHIP_TO_ADDR_NO
--, CO.SALESREP_ID
--, CO.ORDER_DATE
--, CO.DESIRED_SHIP_DATE
--, CO.[STATUS]
--, CO.TOTAL_AMT_ORDERED
--, CO.TOTAL_AMT_SHIPPED
--, CO.SHIPTO_ID
--, CO.CREATE_DATE
--, R.INVOICE_ID
--, R.CUSTOMER_ID
--, R.[TYPE]
--, R.INVOICE_DATE
--, R.TOTAL_AMOUNT
--, R.PAID_AMOUNT
--, R.CREATE_DATE
--, R.[USER_ID]
--, R.[STATUS]
--, PS.PART_ID
--, PS.PLANNER_USER_ID
--, PS.BUYER_USER_ID
--, PS.UNIT_PRICE
--, PS.UNIT_MATERIAL_COST
--, PS.UNIT_LABOR_COST
--, PS.PURC_BUR_PERCENT
--, PS.UNIT_BURDEN_COST
--, PS.FIXED_COST
--, PS.UNIT_SERVICE_COST
--, DSL.ID
--, DSL.DEMAND_TYPE
--, DSL.DEMAND_BASE_ID
--, DSL.DEMAND_LOT_ID
--, DSL.DEMAND_SPLIT_ID
--, DSL.DEMAND_SUB_ID
--, DSL.DEMAND_SEQ_NO
--, DSL.DEMAND_NO
--, DSL.SUPPLY_TYPE
--, DSL.SUPPLY_BASE_ID
--, DSL.SUPPLY_LOT_ID
--, DSL.SUPPLY_SPLIT_ID
--, DSL.SUPPLY_SUB_ID
--, DSL.SUPPLY_SEQ_NO
--, DSL.SUPPLY_NO
--, DSL.WAREHOUSE_ID
--, DSL.DEMAND_PART_ID
--, DSL.SUPPLY_PART_ID
--, DSL.ALLOCATED_QTY
--, DSL.RECEIVED_QTY
--, DSL.ISSUED_QTY
--, DSL.SUPPLY_MODE
--, DSL.CREATE_DATE
--, DSL.[TYPE]
--, PO.VENDOR_ID
--, PO.ORDER_DATE
--, PO.DESIRED_RECV_DATE
--, PO.[STATUS]
--, PO.TOTAL_AMT_ORDERED
--, PO.TOTAL_AMT_RECVD
--, POL.PURC_ORDER_ID
--, POL.LINE_NO
--, POL.PART_ID
--, POL.VENDOR_PART_ID
--, POL.SERVICE_ID
--, POL.USER_ORDER_QTY
--, POL.ORDER_QTY
--, POL.UNIT_PRICE
--, POL.FIXED_CHARGE
--, POL.DESIRED_RECV_DATE
--, POL.LINE_STATUS
--, POL.TOTAL_USR_RECD_QTY
--, POL.TOTAL_RECEIVED_QTY
--, SUM(POL.TOTAL_AMT_RECVD) AS POL_TOTAL_AMT_RECVD
--, SUM(POL.TOTAL_AMT_ORDERED) AS POL_TOTAL_AMT_ORDERED
--, POL.MINIMUM_CHARGE

--SELECT 'WO' AS MSG01
--, WO.*
--, 'IT' AS MSG02
--, IT.*
--, 'ITD' AS MSG03
--, ITD.*
--, 'OT' AS MSG04
--, OT.*
--, 'SL' AS MSG05
--, SL.*
--, 'COL' AS MSG06
--, COL.*
--, 'RL' AS MSG07
--, RL.*
--, 'S' AS MSG08
--, S.*
--, 'CO' AS MSG09
--, CO.*
--, 'R' AS MSG10
--, R.*
--, 'PS' AS MSG11
--, PS.*
--, 'DSL' AS MSG12
--, DSL.*
--, 'PO' AS MSG13
--, PO.*
--, 'POL' AS MSG14
--, POL.*

*/