USE LIVE
GO

SELECT WO.BASE_ID
, WO.LOT_ID
, WO.SPLIT_ID
, WO.SUB_ID
, O.SEQUENCE_NO
, O.RESOURCE_ID
, WO.PART_ID
, P.PLANNER_USER_ID
, P.BUYER_USER_ID
, WO.DESIRED_QTY
, WO.RECEIVED_QTY
, WO.CREATE_DATE
, WO.DESIRED_RLS_DATE
, WO.DESIRED_WANT_DATE
, WO.CLOSE_DATE
, WO.[STATUS]
, O.ACT_ATL_LAB_COST AS OPS_LABOR_COST
, O.ACT_ATL_BUR_COST AS OPS_BURDEN_COST
, O.ACT_ATL_SER_COST AS OPS_SERVICE_COST
, WO.ACT_MATERIAL_COST AS WO_MATERIAL_COST
, WO.ACT_LABOR_COST AS WO_LABOR_COST
, WO.ACT_BURDEN_COST AS WO_BURDEN_COST
, WO.ACT_SERVICE_COST AS WO_SERVICE_COST
--, O.ACT_TTL_MAT_COST
--, O.ACT_TTL_LAB_COST
--, O.ACT_TTL_BUR_COST
--, O.ACT_TTL_SER_COST
--, IT.TRANSACTION_ID
--, IT.WORKORDER_TYPE
--, IT.WORKORDER_BASE_ID
--, IT.WORKORDER_LOT_ID
--, IT.WORKORDER_SPLIT_ID
--, IT.WORKORDER_SUB_ID
--, IT.OPERATION_SEQ_NO
--, IT.REQ_PIECE_NO
--, IT.CUST_ORDER_ID
--, IT.CUST_ORDER_LINE_NO
--, IT.PURC_ORDER_ID
--, IT.PURC_ORDER_LINE_NO
--, IT.PART_ID
--, IT.[TYPE]
--, IT.CLASS
--, IT.QTY
--, IT.COSTED_QTY
--, IT.TRANSACTION_DATE
--, IT.WAREHOUSE_ID
--, IT.LOCATION_ID
--, IT.[DESCRIPTION]
--, IT.POSTING_CANDIDATE
--, IT.ADJ_REASON_ID
--, IT.ACT_MATERIAL_COST
--, IT.ACT_LABOR_COST
--, IT.ACT_BURDEN_COST
--, IT.ACT_SERVICE_COST
--, ITD.IN_TRANS_ID
--, ITD.OUT_TRANS_ID
--, ITD.DIST_QTY
--, ITD.ACT_MATERIAL_COST
--, ITD.ACT_LABOR_COST
--, ITD.ACT_BURDEN_COST
--, ITD.ACT_SERVICE_COST
--, ITD.DEMAND_SUPPLY_ID
--, OT.TRANSACTION_ID
--, OT.WORKORDER_TYPE
--, OT.WORKORDER_BASE_ID
--, OT.WORKORDER_LOT_ID
--, OT.WORKORDER_SPLIT_ID
--, OT.WORKORDER_SUB_ID
--, OT.OPERATION_SEQ_NO
--, OT.REQ_PIECE_NO
--, OT.CUST_ORDER_ID
--, OT.CUST_ORDER_LINE_NO
--, OT.PURC_ORDER_ID
--, OT.PURC_ORDER_LINE_NO
--, OT.PART_ID
--, OT.[TYPE]
--, OT.CLASS
--, OT.QTY
--, OT.COSTED_QTY
--, OT.TRANSACTION_DATE
--, OT.WAREHOUSE_ID
--, OT.LOCATION_ID
--, OT.[DESCRIPTION]
--, OT.POSTING_CANDIDATE
--, OT.ADJ_REASON_ID
--, OT.ACT_MATERIAL_COST
--, OT.ACT_LABOR_COST
--, OT.ACT_BURDEN_COST
--, OT.ACT_SERVICE_COST
--, SL.PACKLIST_ID
--, SL.LINE_NO
--, SL.CUST_ORDER_ID
--, SL.CUST_ORDER_LINE_NO
--, SL.USER_SHIPPED_QTY
--, SL.SHIPPED_QTY
--, SL.ACT_FREIGHT
--, SL.SHIPPING_WEIGHT
--, SL.TRANSACTION_ID
--, SL.UNIT_PRICE
, COL.CUST_ORDER_ID
, COL.LINE_NO
, COL.PART_ID
, COL.CUSTOMER_PART_ID
, COL.LINE_STATUS
, COL.ORDER_QTY
, COL.USER_ORDER_QTY
, COL.DESIRED_SHIP_DATE
, COL.UNIT_PRICE
, COL.MISC_REFERENCE
, COL.PRODUCT_CODE
, COL.COMMODITY_CODE
--, COL.GL_REVENUE_ACCT_ID
--, COL.MAT_GL_ACCT_ID
--, COL.LAB_GL_ACCT_ID
--, COL.BUR_GL_ACCT_ID
--, COL.SER_GL_ACCT_ID
, COL.TOTAL_SHIPPED_QTY
, COL.TOTAL_AMT_SHIPPED
, COL.TOTAL_AMT_ORDERED
--, RL.INVOICE_ID
--, RL.LINE_NO
--, RL.REFERENCE
--, RL.QTY
--, RL.AMOUNT
--, RL.GL_ACCOUNT_ID
--, S.SHIPPED_DATE
--, S.INVOICED_DATE
, CO.CUSTOMER_ID
, CO.CUSTOMER_PO_REF
--, CO.SHIP_TO_ADDR_NO
, CO.ORDER_DATE
, CO.DESIRED_SHIP_DATE
, CO.[STATUS]
, CO.TOTAL_AMT_ORDERED
, CO.TOTAL_AMT_SHIPPED
--, R.CUSTOMER_ID
--, R.[TYPE]
--, R.INVOICE_DATE
--, R.TOTAL_AMOUNT
--, R.PAID_AMOUNT
--, R.POSTING_DATE
--, T.PART_ID
--, T.TRACE_ID
--, T.TRANSACTION_ID
--, T.QTY
--, T.CREATE_DATE
--, T.COSTED_QTY
, WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_BURDEN_COST + WO.ACT_SERVICE_COST AS WO_TOTAL_COST
, O.ACT_ATL_LAB_COST + O.ACT_ATL_BUR_COST + O.ACT_ATL_SER_COST AS OPS_TOTAL_COST
, COL.TOTAL_AMT_SHIPPED
, (WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_BURDEN_COST + WO.ACT_SERVICE_COST) / WO.DESIRED_QTY AS WO_UNIT_COST
, (O.ACT_ATL_LAB_COST + O.ACT_ATL_BUR_COST + O.ACT_ATL_SER_COST) / WO.DESIRED_QTY AS OPS_UNIT_COST
, COL.UNIT_PRICE

FROM WORK_ORDER WO
LEFT OUTER JOIN PART_SITE P
	ON P.PART_ID = WO.PART_ID
LEFT OUTER JOIN OPERATION O
	ON O.WORKORDER_TYPE = WO.[TYPE]
	AND O.WORKORDER_BASE_ID = WO.BASE_ID
	AND O.WORKORDER_LOT_ID = WO.LOT_ID
	AND O.WORKORDER_SPLIT_ID = WO.SPLIT_ID
	AND O.WORKORDER_SUB_ID = WO.SUB_ID

--LEFT OUTER JOIN LIVE.dbo.DEMAND_SUPPLY_LINK DSL
--	ON DSL.DEMAND_TYPE = 'CO'
--	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
--	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO

LEFT OUTER JOIN LIVE.dbo.INVENTORY_TRANS IT
	ON IT.WORKORDER_BASE_ID = WO.BASE_ID
	AND IT.WORKORDER_LOT_ID = WO.LOT_ID

LEFT OUTER JOIN LIVE.dbo.INV_TRANS_DIST ITD
	ON IT.TRANSACTION_ID = ITD.IN_TRANS_ID
LEFT OUTER JOIN LIVE.dbo.INVENTORY_TRANS OT
	ON ITD.OUT_TRANS_ID = OT.TRANSACTION_ID

LEFT OUTER JOIN LIVE.dbo.SHIPPER_LINE SL
	ON SL.TRANSACTION_ID = OT.TRANSACTION_ID
LEFT OUTER JOIN LIVE.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
--LEFT OUTER JOIN LIVE.dbo.RECEIVABLE_LINE RL
--	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
--	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
--	AND SL.PACKLIST_ID = RL.PACKLIST_ID 
--	AND SL.LINE_NO = RL.PACKLIST_LINE_NO 
--	AND RL.PACKLIST_ID IS NOT NULL
--LEFT OUTER JOIN LIVE.dbo.SHIPPER S
--	ON SL.PACKLIST_ID = S.PACKLIST_ID 
LEFT OUTER JOIN LIVE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
--LEFT OUTER JOIN LIVE.dbo.RECEIVABLE R
--	ON RL.INVOICE_ID = R.INVOICE_ID
--LEFT OUTER JOIN LIVE.dbo.TRACE_INV_TRANS  T
--	ON SL.TRANSACTION_ID = T.TRANSACTION_ID

WHERE WO.CREATE_DATE >= '1/1/2019'
AND O.RESOURCE_ID = 'CONTRACTOR'
AND WO.[STATUS] = 'C'
AND CO.CUSTOMER_ID IS NOT NULL
AND WO.DESIRED_QTY > 0
AND COL.ORDER_QTY > 0
AND COL.UNIT_PRICE != 0

--WO.BASE_ID IN ('1594233', '1342914')--, '1463115', '1581739', '1583115', '1584517')
--WHERE S.SHIPPED_DATE >= @START
--	AND SL.SHIPPED_QTY <> 0
--	AND DSL.SUPPLY_BASE_ID IS NULL
	AND (O.ACT_ATL_LAB_COST + O.ACT_ATL_BUR_COST + O.ACT_ATL_SER_COST) / WO.DESIRED_QTY >= COL.UNIT_PRICE
