USE [Datamart]
GO

/****** Object:  StoredProcedure [dbo].[usp_Gross_Margin_tlt]    Script Date: 12/8/2020 7:53:10 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/**********************************************************************************************
Description:	Gross Marging Version 2
Sample:			EXEC Datamart.[dbo].usp_Gross_Margin 

Date        Modified By         Change Description
----------  ------------------  ------------------------------------------------------------
11/22/2019	Traci and Luke		v1 
11/24/2019	William Thompson	v2 used xact
11/29/2019	William	Thompson	v2.1 re-write, transactions rewrite, unit rewrite, using BOE_BILLING v2 broken depends
12/05/2019	William Thompson	amt rib, v2.2
12/12/2019	William Thompson	offsetting negative (refund for charges) line item.
01/22/2020	William Thompson	13 month rolling.
09/17/2020	William Thompson	updated defective boe billing code to type cast numeric in udf
10/1/2020	William Thompson	converted defective boe billing finish code to ETL
12/8/2020	traci treffert		figuring out what is wrong now
*********************************************************************************************/

CREATE PROCEDURE [dbo].[usp_Gross_Margin_tlt]  
AS

truncate table DataWarehouse.dbo.GROSS_MARGIN

SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DEADLOCK_PRIORITY LOW

IF OBJECT_ID('tempdb..#Results') IS NOT NULL DROP TABLE #Results
IF OBJECT_ID('tempdb..#Tester') IS NOT NULL DROP TABLE #Tester
IF OBJECT_ID('tempdb..#INVENTORY_TRANS') IS NOT NULL DROP TABLE #INVENTORY_TRANS
IF OBJECT_ID('tempdb..#CUSTOMER_ORDER') IS NOT NULL DROP TABLE #CUSTOMER_ORDER
IF OBJECT_ID('tempdb..#C_AGG') IS NOT NULL DROP TABLE #C_AGG
IF OBJECT_ID('tempdb..#L_AGG') IS NOT NULL DROP TABLE #L_AGG
IF OBJECT_ID('tempdb..#DIFF_AGG') IS NOT NULL DROP TABLE #DIFF_AGG
IF OBJECT_ID('tempdb..#GM_CP_NET_ADJ') IS NOT NULL DROP TABLE #GM_CP_NET_ADJ
IF OBJECT_ID('tempdb..#ADJ_CP') IS NOT NULL DROP TABLE #ADJ_CP
IF OBJECT_ID('tempdb..#NET_ADJ_CP') IS NOT NULL DROP TABLE #NET_ADJ_CP
IF OBJECT_ID('tempdb..#ADJ_CP') IS NOT NULL DROP TABLE #ADJ_CP
IF OBJECT_ID('tempdb..#GM_ADJ_CP') IS NOT NULL DROP TABLE #GM_ADJ_CP
IF OBJECT_ID('tempdb..#ADJUSTED_TO_COPRODUCT') IS NOT NULL DROP TABLE #ADJUSTED_TO_COPRODUCT
IF OBJECT_ID('tempdb..#GM_CP_ADJ') IS NOT NULL DROP TABLE #GM_CP_ADJ
IF OBJECT_ID('tempdb..#linked') IS NOT NULL DROP TABLE #linked;
IF OBJECT_ID('tempdb..#unlinked1') IS NOT NULL DROP TABLE #unlinked1;
IF OBJECT_ID('tempdb..#unlinked2') IS NOT NULL DROP TABLE #unlinked2;
IF OBJECT_ID('tempdb..#unlinked3') IS NOT NULL DROP TABLE #unlinked3;
IF OBJECT_ID('tempdb..#temp7') IS NOT NULL DROP TABLE #temp7;
IF OBJECT_ID('tempdb..#temp8') IS NOT NULL DROP TABLE #temp8;
IF OBJECT_ID('tempdb..#temp81') IS NOT NULL DROP TABLE #temp81;
IF OBJECT_ID('tempdb..#temp82') IS NOT NULL DROP TABLE #temp82;
IF OBJECT_ID('tempdb..#temp83') IS NOT NULL DROP TABLE #temp83;
IF OBJECT_ID('tempdb..#temp84') IS NOT NULL DROP TABLE #temp84;
IF OBJECT_ID('tempdb..#temp92') IS NOT NULL DROP TABLE #temp92;
IF OBJECT_ID('tempdb..#inserted') IS NOT NULL DROP TABLE #inserted;
IF OBJECT_ID('tempdb..#inserted1') IS NOT NULL DROP TABLE #inserted1;
IF OBJECT_ID('tempdb..#xx') IS NOT NULL DROP TABLE #xx;
IF OBJECT_ID('tempdb..#xx1') IS NOT NULL DROP TABLE #xx1;
IF OBJECT_ID('tempdb..#xx2') IS NOT NULL DROP TABLE #xx2;

DECLARE @START DATE =  DATEADD(DAY,1,EOMONTH( DATEADD(YEAR,-1,GETDATE()),0)) 
	, @END DATE = GETDATE()-1

CREATE TABLE #results(
    [REC_ISSUES] [varchar](7) NULL,
    [ORDER_TYPE] [varchar](9) NULL,
    [BUS_STREAM] [nvarchar](254) NULL,
    [BUS_UNIT] [nvarchar](254) NULL,
    [PLANNER_USER_ID] [nvarchar](20) NULL,
    [BUYER_USER_ID] [nvarchar](20) NULL,
    [Salesperson_ID] [nvarchar](255) NULL,
    [CO_CREATE_DATE] [datetime] NULL,
    [WO_CREATE_DATE] [datetime] NULL,
    [SHIPPED_DATE] [datetime] NULL,
    [CUSTOMER_ID] [nvarchar](15) NULL,
    [CUST_ORDER_ID] [nvarchar](15) NULL,
    [COL_LINE] [smallint] NULL,
    [BASE_ID] [nvarchar](30) NULL,
    [LOT_ID] [nvarchar](3) NULL,
    [SPLIT_ID] [nvarchar](3) NULL,
    [SUB_ID] [nvarchar](3) NULL,
    [WO_STATUS] [nchar](1) NULL,
    [PACKLIST_ID] [nvarchar](15) NULL,
    [TRANSACTION_ID] [int] NULL,
    [INVOICE_ID] [nvarchar](15) NULL,
    [INV_LINE] [smallint] NULL,
    [PART_ID] [nvarchar](30) NULL,
    [SHIP_SHORT] [nchar](1) NULL,
    [TRACE_ID] [nvarchar](30) NULL,
    [TOTAL_SHIPPED_QTY] [decimal](14, 4) NULL,
    [COL_ORDER_QTY] [decimal](14, 4) NULL,
    [DESIRED_QTY] [decimal](14, 4) NULL,
    [TRACE_QTY] [decimal](16, 4) NULL,
    [SHIPPED_QTY] [decimal](14, 4) NULL,
    [REC_QTY] [numeric](14, 4) NULL,
    [COL_UNIT_PRICE] [decimal](15, 6) NULL,
    [REC_AMOUNT] [numeric](15, 2) NULL,
    [TRACE_CHARGE_ALLOC] [decimal](38, 8) NULL,
    [TOTAL_INVOICE_AMOUNT] [float] NULL,
    [TRACE_INVOICE_AMOUNT] [float] NULL,
    [UNIT_INVOICE_AMOUNT] [float] NULL,
    [TOTAL_BURDEN_COST] [decimal](15, 2) NULL,
    [TOTAL_MATERIAL_COST] [decimal](15, 2) NULL,
    [TOTAL_LABOR_COST] [decimal](15, 2) NULL,
    [TOTAL_SERVICE_COST] [decimal](15, 2) NULL,
    [TRACE_BURDEN_COST] [decimal](38, 6) NULL,
    [TRACE_MATERIAL_COST] [decimal](38, 6) NULL,
    [TRACE_LABOR_COST] [decimal](38, 6) NULL,
    [TRACE_SERVICE_COST] [decimal](38, 6) NULL,
    [UNIT_BURDEN_COST] [decimal](38, 6) NULL,
    [UNIT_MATERIAL_COST] [decimal](38, 6) NULL,
    [UNIT_LABOR_COST] [decimal](38, 6) NULL,
    [UNIT_SERVICE_COST] [decimal](38, 6) NULL,
    [TOTAL_CHARGE] [decimal](15, 2) NULL,
    [PART_QTY] [decimal](38, 4) NULL,
    [UNIT_CHARGE_ALLOC] [decimal](38, 21) NULL,
    [PART NUMBER] [nvarchar](30) NULL,
    [SUM_EXTENDED_DOLLARS] [float] NULL,
    [TOTAL_HOURS] [decimal](38, 2) NULL,
    [AMT_BASE_ID] [nvarchar](4000) NULL,
    [AMT_REC_AMOUNT] [numeric](38, 2) NULL,
    [AMT_BURDEN_COST] [decimal](38, 2) NULL,
    [AMT_MATERIAL_COST] [decimal](38, 2) NULL,
    [AMT_LABOR_COST] [decimal](38, 2) NULL,
    [AMT_SERVICE_COST] [decimal](38, 2) NULL,
    [TRACE_BURDEN_COST_HDR] [decimal](38, 6) NULL,
    [TRACE_MATERIAL_COST_HDR] [decimal](38, 6) NULL,
    [TRACE_LABOR_COST_HDR] [decimal](38, 6) NULL,
    [TRACE_SERVICE_COST_HDR] [decimal](38, 6) NULL,
    [TRACE_PRICE] [float] NULL,
    [INV_UNIT_PRICE] [float] NULL,
    [UNITPRICE_DELTA] [float] NULL,
    [TOTAL_TRACE_COST] [decimal](38, 6) NULL,
    [TRACE_UNIT_COST] [decimal](38, 6) NULL,
    [TOTAL_UNIT_COST] [decimal](38, 6) NULL
)
;

SELECT X.DW_XACT_FLAG
	, X.BASE_ID
	, X.LOT_ID
	, X.SPLIT_ID
	, X.PART_ID
	, X.[DESCRIPTION]
	, X.DESIRED_QTY
	, X.CUMM_CP_QTY
	, X.TOTAL_WO_QTY
	, X.ACT_MATERIAL_COST
	, X.ACT_LABOR_COST
	, X.ACT_BURDEN_COST
	, X.ACT_SERVICE_COST
	, X.TTL_COST
	, X.FLD1
	, X.SUB_ID
	, X.[STATUS] 		
	, X.CREATE_DATE
	, X.[TYPE]		
	INTO #ADJ_CP
FROM (SELECT DW_XACT_FLAG = 'WO'
		,W.BASE_ID, W.LOT_ID, W.SPLIT_ID, W.PART_ID, P.DESCRIPTION
		, W.DESIRED_QTY, 

		ISNULL((SELECT SUM(DESIRED_QTY) 
		FROM DATAWAREHOUSE.dbo.CO_PRODUCT CP 
		WHERE WORKORDER_TYPE = W.TYPE 
		 AND WORKORDER_BASE_ID = W.BASE_ID AND WORKORDER_LOT_ID = W.LOT_ID AND 
		 WORKORDER_SPLIT_ID = W.SPLIT_ID AND WORKORDER_SUB_ID = W.SUB_ID),0) AS CUMM_CP_QTY, 


			W.DESIRED_QTY+ISNULL((SELECT SUM(DESIRED_QTY) FROM DATAWAREHOUSE.dbo.CO_PRODUCT CP WHERE WORKORDER_TYPE = W.TYPE 
		 AND WORKORDER_BASE_ID = W.BASE_ID AND WORKORDER_LOT_ID = W.LOT_ID AND 
		 WORKORDER_SPLIT_ID = W.SPLIT_ID AND WORKORDER_SUB_ID = W.SUB_ID),0) AS TOTAL_WO_QTY,

		W.ACT_MATERIAL_COST, W.ACT_LABOR_COST, W.ACT_BURDEN_COST, W.ACT_SERVICE_COST, 
		W.ACT_MATERIAL_COST+W.ACT_LABOR_COST+W.ACT_BURDEN_COST+W.ACT_SERVICE_COST AS TTL_COST 

		, replace(LEFT(SUBSTRING(replace(replace(replace(replace(replace(W.BASE_ID,'(',''),')',''),'-',''),' ',''),',','')
		, PATINDEX('%[0-9.-]%', replace(replace(replace(replace(replace(W.BASE_ID,'(',''),')',''),'-',''),' ',''),',',''))
		, 8000), PATINDEX('%[^0-9.-]%', SUBSTRING(replace(replace(replace(replace(replace(
		W.BASE_ID,'(',''),')',''),'-',''),' ',''),',','')
		, PATINDEX('%[0-9.-]%', replace(replace(replace(replace(replace(W.BASE_ID
		,'(',''),')',''),'-',''),' ',''),',','')), 8000) + 'X') -1),'.','') AS FLD1

	, W.SUB_ID
	, W.[STATUS] AS STATUS		
	, W.CREATE_DATE AS CREATE_DATE
	, W.[TYPE]		

	FROM DATAWAREHOUSE.dbo.WORK_ORDER W 
	INNER JOIN DATAWAREHOUSE.dbo.PART P 
	ON W.PART_ID = P.ID 
	WHERE W.TYPE = 'W' AND W.SUB_ID = 0
	AND W.BASE_ID IN (
				SELECT
				  CP2.WORKORDER_BASE_ID
				FROM DATAWAREHOUSE.dbo.CO_PRODUCT CP2 
				INNER JOIN DATAWAREHOUSE.dbo.PART P2 ON CP2.PART_ID = P2.ID 
				WHERE NOT EXISTS(
						SELECT 1
						FROM DATAWAREHOUSE.dbo.WORK_ORDER W3 
						INNER JOIN DATAWAREHOUSE.dbo.PART P3 
						ON W3.PART_ID = P3.ID 
						WHERE W3.TYPE = 'M' 
						AND CP2.WORKORDER_BASE_ID = W3.BASE_ID )
				AND CP2.STATUS_EFF_DATE >='2019-01-01'
				)
	UNION --ALL

	SELECT 
		DW_XACT_FLAG = 'CP',

		 CP.WORKORDER_BASE_ID, CP.WORKORDER_LOT_ID, CP.WORKORDER_SPLIT_ID
		 , CP.PART_ID, P.DESCRIPTION, CP.DESIRED_QTY, 
		 ISNULL(
			(
				SELECT SUM(DESIRED_QTY) 
				FROM DATAWAREHOUSE.dbo.CO_PRODUCT SCP 
				WHERE SCP.WORKORDER_TYPE = CP.WORKORDER_TYPE 
				AND	SCP.WORKORDER_BASE_ID = CP.WORKORDER_BASE_ID 
				AND SCP.WORKORDER_LOT_ID = CP.WORKORDER_LOT_ID 
				AND SCP.WORKORDER_SPLIT_ID = CP.WORKORDER_SPLIT_ID 
				AND SCP.WORKORDER_SUB_ID = CP.WORKORDER_SUB_ID 
				AND SCP.PART_ID <> CP.PART_ID
			),0
		)
		+
		(		SELECT DESIRED_QTY 
				FROM DATAWAREHOUSE.dbo.WORK_ORDER 
				WHERE TYPE = CP.WORKORDER_TYPE 
				AND BASE_ID = CP.WORKORDER_BASE_ID 
				AND LOT_ID = CP.WORKORDER_LOT_ID 
				AND SPLIT_ID = CP.WORKORDER_SPLIT_ID 
				AND SUB_ID = CP.WORKORDER_SUB_ID
		 )
		AS CUMM_OTHER_QTY, 
		CP.DESIRED_QTY 
		+ 
		ISNULL((
			SELECT SUM(DESIRED_QTY) FROM DATAWAREHOUSE.dbo.CO_PRODUCT SCP WHERE SCP.WORKORDER_TYPE = CP.WORKORDER_TYPE AND 
			SCP.WORKORDER_BASE_ID = CP.WORKORDER_BASE_ID AND SCP.WORKORDER_LOT_ID = CP.WORKORDER_LOT_ID AND 
			SCP.WORKORDER_SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SCP.WORKORDER_SUB_ID = CP.WORKORDER_SUB_ID 
			AND SCP.PART_ID <> CP.PART_ID
		),0)
		+
		(
			SELECT DESIRED_QTY 
			FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE 
			AND BASE_ID = CP.WORKORDER_BASE_ID 
			AND LOT_ID = CP.WORKORDER_LOT_ID 
			AND SPLIT_ID = CP.WORKORDER_SPLIT_ID 
			AND SUB_ID = CP.WORKORDER_SUB_ID
		)
		AS Some_OTHER_QTY, 

			(SELECT ACT_MATERIAL_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
			 AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID) AS ACT_MATERIAL_COST, 

			(SELECT ACT_LABOR_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
			 AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID) AS ACT_LABOR_COST, 

			(SELECT ACT_BURDEN_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
			 AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID) AS ACT_BURDEN_COST, 

			(SELECT ACT_SERVICE_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
			 AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID) AS ACT_SERVICE_COST, 

			 -- TTL_COST:
						(SELECT ACT_MATERIAL_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
						 AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID) 
						  +
						(SELECT ACT_LABOR_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
						 AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID)
						  +
						(SELECT ACT_BURDEN_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
						 AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID)
						  +
						(SELECT ACT_SERVICE_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
						 AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID) 
			AS TTL_COST

			, replace(LEFT(SUBSTRING(replace(replace(replace(replace(replace(CP.WORKORDER_BASE_ID,'(',''),')',''),'-',''),' ',''),',','')
			, PATINDEX('%[0-9.-]%', replace(replace(replace(replace(replace(CP.WORKORDER_BASE_ID,'(',''),')',''),'-',''),' ',''),',',''))
			, 8000), PATINDEX('%[^0-9.-]%', SUBSTRING(replace(replace(replace(replace(replace(
			CP.WORKORDER_BASE_ID,'(',''),')',''),'-',''),' ',''),',','')
			, PATINDEX('%[0-9.-]%', replace(replace(replace(replace(replace(CP.WORKORDER_BASE_ID
			,'(',''),')',''),'-',''),' ',''),',','')), 8000) + 'X') -1),'.','') AS FLD1

		,[WORKORDER_SUB_ID] AS SUB_ID
		, NULL AS STATUS		
        , NULL AS CREATE_DATE	
		,[WORKORDER_TYPE] AS [TYPE]	

	FROM DATAWAREHOUSE.dbo.CO_PRODUCT CP 
	INNER JOIN DATAWAREHOUSE.dbo.PART P 
	ON CP.PART_ID = P.ID 
	WHERE NOT EXISTS(
			SELECT 1
			FROM DATAWAREHOUSE.dbo.WORK_ORDER W 
			INNER JOIN DATAWAREHOUSE.dbo.PART P 
			ON W.PART_ID = P.ID 
			WHERE W.TYPE = 'M' 
			AND CP.WORKORDER_BASE_ID = W.BASE_ID )
	AND CP.STATUS_EFF_DATE >='2019-01-01'
	AND CP.STATUS_EFF_DATE >=  @START

	) AS X

	ORDER BY 2, 1

update_wo_fields_for_gm_rpt:
update t
SET STATUS = w.STATUS
, CREATE_DATE = W.CREATE_DATE
FROM #ADJ_CP t
JOIN DATAWAREHOUSE.dbo.WORK_ORDER w
ON t.BASE_ID = w.BASE_ID

contine_cp_adj_data:

-- This is requirement 1.2 in order to pull adjusted order that were transformed into CP
-- DW_XACT_FLAG is wo if the record is from the wo, cp if from the co-product.
-- The work order is zero for these 'adjusted orders transformed into co-products
SELECT * 
INTO #GM_CP_ADJ
FROM #ADJ_CP 
WHERE DW_XACT_FLAG = 'CP'
AND BASE_ID IN (
    SELECT BASE_ID FROM #ADJ_CP 
	WHERE DW_XACT_FLAG = 'WO'
	AND DESIRED_QTY = 0
)
ORDER BY 2,1,3

/**********************************************************************************************
ADJUSTED CO_PRODUCTS *** ////////////////////////////////////////////////////////////////
projection ends; use #GM_CP_ADJ in gm projection

CO_PRODUCTS_UNADJ
PART II. co-products (actual) net of any adjusted orders using the convert-to-cp.

**********************************************************************************************/

SELECT CP.*
INTO #GM_CP_NET_ADJ
FROM (
SELECT 
    DW_XACT_FLAG = 'WO'
	,W.BASE_ID, W.LOT_ID, W.SPLIT_ID, W.PART_ID, P.DESCRIPTION, W.DESIRED_QTY, 
	ISNULL((SELECT SUM(DESIRED_QTY) FROM DATAWAREHOUSE.dbo.CO_PRODUCT CP WHERE WORKORDER_TYPE = W.TYPE 
	AND WORKORDER_BASE_ID = W.BASE_ID AND WORKORDER_LOT_ID = W.LOT_ID AND 
	WORKORDER_SPLIT_ID = W.SPLIT_ID AND WORKORDER_SUB_ID = W.SUB_ID),0) AS CUMM_CP_QTY, 
	W.DESIRED_QTY+ISNULL((SELECT SUM(DESIRED_QTY) FROM DATAWAREHOUSE.dbo.CO_PRODUCT CP WHERE WORKORDER_TYPE = W.TYPE 
	AND WORKORDER_BASE_ID = W.BASE_ID AND WORKORDER_LOT_ID = W.LOT_ID AND 
	WORKORDER_SPLIT_ID = W.SPLIT_ID AND WORKORDER_SUB_ID = W.SUB_ID),0) AS TOTAL_WO_QTY,
	W.ACT_MATERIAL_COST, W.ACT_LABOR_COST, W.ACT_BURDEN_COST, W.ACT_SERVICE_COST, 
	W.ACT_MATERIAL_COST+W.ACT_LABOR_COST+W.ACT_BURDEN_COST+W.ACT_SERVICE_COST AS TTL_COST 
	, replace(LEFT(SUBSTRING(replace(replace(replace(replace(replace(W.BASE_ID,'(',''),')',''),'-',''),' ',''),',','')
	, PATINDEX('%[0-9.-]%', replace(replace(replace(replace(replace(W.BASE_ID,'(',''),')',''),'-',''),' ',''),',',''))
	, 8000), PATINDEX('%[^0-9.-]%', SUBSTRING(replace(replace(replace(replace(replace(
	W.BASE_ID,'(',''),')',''),'-',''),' ',''),',','')
	, PATINDEX('%[0-9.-]%', replace(replace(replace(replace(replace(W.BASE_ID
	,'(',''),')',''),'-',''),' ',''),',','')), 8000) + 'X') -1),'.','') AS FLD1
	, W.SUB_ID
	, W.[STATUS] AS STATUS		
	, W.CREATE_DATE AS CREATE_DATE
	, W.[TYPE]		
FROM DATAWAREHOUSE.dbo.WORK_ORDER W 
INNER JOIN DATAWAREHOUSE.dbo.PART P 
ON W.PART_ID = P.ID 
WHERE W.TYPE = 'W' AND W.SUB_ID = 0
-- William in test
--AND w.base_id like '1499857' + '%'

UNION -- ALL

SELECT 
     DW_XACT_FLAG = 'CP'
	 ,CP.WORKORDER_BASE_ID BASE_ID
	 , CP.WORKORDER_LOT_ID
	 , CP.WORKORDER_SPLIT_ID
	 , CP.PART_ID
	 , P.DESCRIPTION
	 , CP.DESIRED_QTY
	 , ISNULL(
		(
			SELECT SUM(DESIRED_QTY) 
			FROM DATAWAREHOUSE.dbo.CO_PRODUCT SCP 
			WHERE SCP.WORKORDER_TYPE = CP.WORKORDER_TYPE 
			AND	SCP.WORKORDER_BASE_ID = CP.WORKORDER_BASE_ID 
			AND SCP.WORKORDER_LOT_ID = CP.WORKORDER_LOT_ID 
			AND SCP.WORKORDER_SPLIT_ID = CP.WORKORDER_SPLIT_ID 
			AND SCP.WORKORDER_SUB_ID = CP.WORKORDER_SUB_ID 
			AND SCP.PART_ID <> CP.PART_ID
		),0
	)
	+
	(		SELECT DESIRED_QTY 
			FROM DATAWAREHOUSE.dbo.WORK_ORDER 
			WHERE TYPE = CP.WORKORDER_TYPE 
			AND BASE_ID = CP.WORKORDER_BASE_ID 
			AND LOT_ID = CP.WORKORDER_LOT_ID 
			AND SPLIT_ID = CP.WORKORDER_SPLIT_ID 
			AND SUB_ID = CP.WORKORDER_SUB_ID
	 )
	AS CUMM_OTHER_QTY, 
	CP.DESIRED_QTY 
	+ 
	ISNULL((
		SELECT SUM(DESIRED_QTY) 
		FROM DATAWAREHOUSE.dbo.CO_PRODUCT SCP WHERE SCP.WORKORDER_TYPE = CP.WORKORDER_TYPE AND 
		SCP.WORKORDER_BASE_ID = CP.WORKORDER_BASE_ID AND SCP.WORKORDER_LOT_ID = CP.WORKORDER_LOT_ID AND 
		SCP.WORKORDER_SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SCP.WORKORDER_SUB_ID = CP.WORKORDER_SUB_ID 
		AND SCP.PART_ID <> CP.PART_ID
	),0)
	+
	(
		SELECT DESIRED_QTY 
		FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE 
		AND BASE_ID = CP.WORKORDER_BASE_ID 
		AND LOT_ID = CP.WORKORDER_LOT_ID 
		AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID
	)
	AS CUMM_OTHER_QTY, 

		(SELECT ACT_MATERIAL_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
		 AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID) AS ACT_MATERIAL_COST, 

		(SELECT ACT_LABOR_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
		 AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID) AS ACT_LABOR_COST, 

		(SELECT ACT_BURDEN_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
		 AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID) AS ACT_BURDEN_COST, 

		(SELECT ACT_SERVICE_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
		 AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID) AS ACT_SERVICE_COST, 

		 -- TTL_COST:
		(SELECT ACT_MATERIAL_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
			AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID) 
			+
		(SELECT ACT_LABOR_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
			AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID)
			+
		(SELECT ACT_BURDEN_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
			AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID)
			+
		(SELECT ACT_SERVICE_COST FROM DATAWAREHOUSE.dbo.WORK_ORDER WHERE TYPE = CP.WORKORDER_TYPE AND BASE_ID = CP.WORKORDER_BASE_ID 
			AND LOT_ID = CP.WORKORDER_LOT_ID AND SPLIT_ID = CP.WORKORDER_SPLIT_ID AND SUB_ID = CP.WORKORDER_SUB_ID) 
		AS TTL_COST

		, replace(LEFT(SUBSTRING(replace(replace(replace(replace(replace(CP.WORKORDER_BASE_ID,'(',''),')',''),'-',''),' ',''),',','')
		, PATINDEX('%[0-9.-]%', replace(replace(replace(replace(replace(CP.WORKORDER_BASE_ID,'(',''),')',''),'-',''),' ',''),',',''))
		, 8000), PATINDEX('%[^0-9.-]%', SUBSTRING(replace(replace(replace(replace(replace(
		CP.WORKORDER_BASE_ID,'(',''),')',''),'-',''),' ',''),',','')
		, PATINDEX('%[0-9.-]%', replace(replace(replace(replace(replace(CP.WORKORDER_BASE_ID
		,'(',''),')',''),'-',''),' ',''),',','')), 8000) + 'X') -1),'.','') AS FLD1

		,[WORKORDER_SUB_ID] AS SUB_ID
		, NULL AS STATUS		
        , NULL AS CREATE_DATE	
		,[WORKORDER_TYPE] AS [TYPE]	

	FROM DATAWAREHOUSE.dbo.CO_PRODUCT CP 
	INNER JOIN DATAWAREHOUSE.dbo.PART P ON CP.PART_ID = P.ID 
	WHERE NOT EXISTS(
			SELECT 1
			FROM DATAWAREHOUSE.dbo.WORK_ORDER W 
			INNER JOIN DATAWAREHOUSE.dbo.PART P 
			ON W.PART_ID = P.ID 
			WHERE W.TYPE = 'M' 
			AND CP.WORKORDER_BASE_ID = W.BASE_ID )
	AND CP.STATUS_EFF_DATE >='2019-01-01'
	AND CP.STATUS_EFF_DATE >=@START
	AND CP.STATUS_EFF_DATE BETWEEN @START and @END

) AS CP
WHERE CP.BASE_ID NOT IN
(
SELECT BASE_ID FROM #GM_CP_ADJ (NOLOCK)
)
--SELECT BASE_ID FROM #GM_CP_NET_ADJ
update_wo_fields_for_gm_rpt2:
update t
 SET
  STATUS = w.STATUS
  ,CREATE_DATE = W.CREATE_DATE
FROM #GM_CP_NET_ADJ t
JOIN DATAWAREHOUSE.dbo.WORK_ORDER w
ON t.BASE_ID = w.BASE_ID

/**********************************************************************************************
CO_PRODUCTS_UNADJ
PART II. Ends ////////////////////////////////////////////////////////////////

**********************************************************************************************/

IF OBJECT_ID('tempdb..#BUS_UNIT') IS NOT NULL DROP TABLE #BUS_UNIT
SELECT * 
INTO #BUS_UNIT
FROM [SQL-LAB-2].[LIVE].dbo.USER_DEF_FIELDS UDF
WHERE PROGRAM_ID = 'VMCUSMNT'
	AND UDF.ID = 'UDF-0000072'
;

-----------------------------> BOE QUERIES
IF OBJECT_ID('tempdb..#BOE_BILLING') IS NOT NULL DROP TABLE #BOE_BILLING

CREATE TABLE #BOE_BILLING
    ([SPROC] NVARCHAR(15)
    , [COST ITEM] NVARCHAR(1)
    , [POS] NVARCHAR(5)
    , [PART NUMBER] NVARCHAR(30)
    , [RAMAC] NVARCHAR(20)
    , [BILLED QTY] FLOAT
    , [UNIT PRICE] FLOAT
    , [EXTENDED DOLLARS] FLOAT
    , [EXPEDITE DOLLARS] FLOAT
    , [SPECIAL FEES] FLOAT  
    , [SETUP HOURS] [decimal](14, 2)
    , [RUN HOURS] [decimal](14, 2)
    , [EXPEDITE HOURS] FLOAT
    , [PACK SLIPS] NVARCHAR(MAX)
    , [COMMENTS] NVARCHAR(MAX)
    , [INVOICE ID] NVARCHAR(MAX)   -- not in all structures
    , [SORTATION] INT
    , [SERVICE_FEES] [int] NULL
    )

INSERT INTO #BOE_BILLING EXEC Datamart.dbo.usp_BOE_BILLING_605 @START, @END
INSERT INTO #BOE_BILLING EXEC Datamart.dbo.usp_BOE_BILLING_ASSY @START, @END
INSERT INTO #BOE_BILLING EXEC Datamart.dbo.usp_BOE_BILLING_MFG @START, @END   -- schema 1
INSERT INTO #BOE_BILLING EXEC Datamart.dbo.usp_BOE_BILLING_5AXIS @START, @END   -- schema 2
INSERT INTO #BOE_BILLING EXEC Datamart.dbo.usp_BOE_BILLING_BOLTBOARDS @START, @END
INSERT INTO #BOE_BILLING EXEC Datamart.dbo.usp_BOE_BILLING_FINISH @START, @END   -- schema 1

CREATE CLUSTERED INDEX CL_IDX_RAMAC ON #BOE_BILLING (RAMAC)
  
-- BOE billing ends /////////////////////////////////////////////   
;

WITH CTE_BOE AS 	
(SELECT RAMAC AS ID
	, [PART NUMBER]
	, SUM([EXTENDED DOLLARS]) AS SUM_EXTENDED_DOLLARS
	, SUM([SETUP HOURS]) + SUM([RUN HOURS]) AS TOTAL_HOURS
	, SUM([SPECIAL FEES]) AS [SPECIAL FEES]
FROM #BOE_BILLING
GROUP BY RAMAC
	, [PART NUMBER]
)

, CTE_CHARGES AS
(SELECT COL.CUST_ORDER_ID
    , CONVERT(DECIMAL(15,2), SUM(RL.AMOUNT)) AS TOTAL_CHARGE
FROM dbo.CUST_ORDER_LINE COL
INNER JOIN dbo.CUSTOMER_ORDER CO
    ON COL.CUST_ORDER_ID = CO.ID
LEFT OUTER JOIN dbo.RECEIVABLE_LINE RL
    ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
    AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
LEFT OUTER JOIN dbo.RECEIVABLE R
    ON RL.INVOICE_ID = R.INVOICE_ID
WHERE COL.PART_ID IS NULL
    AND COL.SERVICE_CHARGE_ID IS NOT NULL
    AND CO.CREATE_DATE >= '1/1/2015'
    AND CO.[STATUS] != 'X'
    AND COL.ORDER_QTY > 0
    AND RL.AMOUNT > 0
--> tt 20201208  this makes no sense
	--and 0 < ALL (select rl2.amount 
	--	from dbo.shipper_line sl2
	--	inner join dbo.shipper s2
	--		on sl2.packlist_id = s2.packlist_id
	--	join dbo.cust_order_line col2
	--		on sl2.cust_order_id = col2.cust_order_id
	--		and sl2.cust_order_line_no = col2.line_no
	--	inner join dbo.customer_order co2
	--		on col2.cust_order_id = co2.id
	--	left outer join dbo.receivable_line rl2
	--		on rl2.cust_order_id = col2.cust_order_id
	--		and rl2.cust_order_line_no = col2.line_no
	--	left outer join dbo.receivable r2
	--		on rl2.invoice_id = r2.invoice_id
	--	where (1=1)
	--		and COL.cust_order_id = col2.cust_order_id
	--		    AND COL2.SERVICE_CHARGE_ID IS NOT NULL
	--	)
GROUP BY COL.CUST_ORDER_ID
)
--SELECT * FROM CTE_CHARGES

, CTE_PARTS AS
(SELECT COL.CUST_ORDER_ID
	, SUM(COL.ORDER_QTY) AS PART_QTY
FROM dbo.CUST_ORDER_LINE COL
INNER JOIN dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN CTE_CHARGES CTE
	ON COL.CUST_ORDER_ID = CTE.CUST_ORDER_ID
LEFT OUTER JOIN dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE COL.PART_ID IS NOT NULL
	AND COL.ORDER_QTY > 0
	AND (DSL.SUPPLY_BASE_ID NOT LIKE '%R%' 
		OR DSL.SUPPLY_BASE_ID IS NULL)
GROUP BY COL.CUST_ORDER_ID
)
--SELECT * FROM CTE_PARTS

, CTE_CHGAMTS AS
(SELECT CTE1.CUST_ORDER_ID
	, CTE1.TOTAL_CHARGE
	, CTE2.PART_QTY
	, CASE  
	    WHEN CTE1.TOTAL_CHARGE > 0 THEN
	CTE1.TOTAL_CHARGE / CTE2.PART_QTY
	ELSE NULL END AS UNIT_CHARGE_ALLOC
FROM CTE_CHARGES CTE1
INNER JOIN CTE_PARTS CTE2
	ON CTE1.CUST_ORDER_ID = CTE2.CUST_ORDER_ID
)
--SELECT * FROM CTE_CHGAMTS  where CUST_ORDER_ID = '346106'

, CTE_LINKED as 
(SELECT 'LINKED' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, SL.SHIPPED_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
	, ACT_BURDEN_COST_HDR =  WO.ACT_BURDEN_COST
	, ACT_MATERIAL_COST_HDR = WO.ACT_MATERIAL_COST
	, ACT_LABOR_COST_HDR = WO.ACT_LABOR_COST
	, ACT_SERVICE_COST_HDR = WO.ACT_SERVICE_COST
	, WO.ACT_BURDEN_COST
	, WO.ACT_MATERIAL_COST
	, WO.ACT_LABOR_COST
	, WO.ACT_SERVICE_COST
FROM dbo.SHIPPER_LINE SL
INNER JOIN dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
INNER JOIN dbo.WORK_ORDER WO
    ON DSL.SUPPLY_TYPE = 'WO' 
    AND DSL.SUPPLY_BASE_ID = WO.BASE_ID
    AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
    AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
    AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
	AND WO.[TYPE] = 'W'
INNER JOIN dbo.RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND RL.PACKLIST_ID = SL.PACKLIST_ID
	AND RL.PACKLIST_LINE_NO = SL.LINE_NO
INNER JOIN dbo.RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
LEFT OUTER JOIN dbo.TRACE_INV_TRANS T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
WHERE RL.PACKLIST_ID IS NOT NULL
	AND S.SHIPPED_DATE >= @START
	AND COL.PART_ID IS NOT NULL
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NOT NULL
	AND COL.ORDER_QTY > 0

union
 
SELECT 'CP_ADJ' AS [ORDER_TYPE]
    , T.TRACE_ID
    , SL.TRANSACTION_ID
    , RL.INVOICE_ID
    , RL.LINE_NO AS INV_LINE
    , T.QTY * -1 AS TRACE_QTY
    , RL.PACKLIST_ID
    , S.SHIPPED_DATE
    , CO.CREATE_DATE AS CO_CREATE_DATE
    , COL.CUST_ORDER_ID
    , COL.LINE_NO AS COL_LINE
    , CO.CUSTOMER_ID
    , COL.PART_ID
    , COL.LINE_STATUS AS SHIP_SHORT
    , COL.ORDER_QTY AS COL_ORDER_QTY
    , COL.TOTAL_SHIPPED_QTY
    , RL.QTY AS REC_QTY
    , COL.UNIT_PRICE AS COL_UNIT_PRICE
    , RL.AMOUNT AS REC_AMOUNT
    , SL.SHIPPED_QTY
    , WO.[STATUS] AS WO_STATUS
    , WO.CREATE_DATE AS WO_CREATE_DATE
    , WO.BASE_ID
    , WO.LOT_ID
    , WO.SPLIT_ID
    , WO.SUB_ID
    , WO.DESIRED_QTY
    , ACT_BURDEN_COST_HDR =  WO.ACT_BURDEN_COST
    , ACT_MATERIAL_COST_HDR = WO.ACT_MATERIAL_COST
    , ACT_LABOR_COST_HDR = WO.ACT_LABOR_COST
    , ACT_SERVICE_COST_HDR = WO.ACT_SERVICE_COST
    , WO.ACT_BURDEN_COST
    , WO.ACT_MATERIAL_COST
    , WO.ACT_LABOR_COST
    , WO.ACT_SERVICE_COST
FROM DATAWAREHOUSE.dbo.SHIPPER_LINE SL
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S
    ON SL.PACKLIST_ID = S.PACKLIST_ID
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
    ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
    AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
    ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
    ON
    DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
    AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
INNER JOIN #GM_CP_ADJ WO
    ON
    DSL.SUPPLY_BASE_ID = WO.BASE_ID
    AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
    AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
    AND DSL.SUPPLY_SUB_ID = WO.SUB_ID
    AND WO.[TYPE] = 'W'
INNER JOIN DATAWAREHOUSE.dbo.RECEIVABLE_LINE RL
    ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
    AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
    AND RL.PACKLIST_ID = SL.PACKLIST_ID
    AND RL.PACKLIST_LINE_NO = SL.LINE_NO
INNER JOIN DATAWAREHOUSE.dbo.RECEIVABLE R
    ON RL.INVOICE_ID = R.INVOICE_ID
LEFT OUTER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS T
    ON SL.TRANSACTION_ID = T.TRANSACTION_ID
WHERE DSL.SUPPLY_TYPE = 'CP'

/**********************************************************************************************
ADJUSTED CO_PRODUCTS DATASET ENDS!!!!!!//////////////////////////////////////////////////////////////////////////
PART I. orders thatl had bad part # and weree converted to co-products
can swap out wo table for #GM_CP_ADJ
NOTE: USE #GM_CP_ADJ.BASE_ID TO ENSURE EXCLUSION OF ADJUSTMENTS
These were a special case, there were orders with bad part #s converted to co-products.
 
**********************************************************************************************/
UNION
/**************************************************************
PART II.
**************************************************************/
SELECT 'CP_UNADJ' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, SL.SHIPPED_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
    , ACT_BURDEN_COST_HDR =  WO.ACT_BURDEN_COST
    , ACT_MATERIAL_COST_HDR = WO.ACT_MATERIAL_COST
    , ACT_LABOR_COST_HDR = WO.ACT_LABOR_COST
    , ACT_SERVICE_COST_HDR = WO.ACT_SERVICE_COST
	, WO.ACT_BURDEN_COST
	, WO.ACT_MATERIAL_COST
	, WO.ACT_LABOR_COST
	, WO.ACT_SERVICE_COST
FROM DATAWAREHOUSE.dbo.SHIPPER_LINE SL
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
INNER JOIN #GM_CP_NET_ADJ WO
    ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
    AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
    AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
    AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
	AND WO.[TYPE] = 'W'
INNER JOIN DATAWAREHOUSE.dbo.RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND RL.PACKLIST_ID = SL.PACKLIST_ID
	AND RL.PACKLIST_LINE_NO = SL.LINE_NO
--	AND RL.AMOUNT != 0
INNER JOIN DATAWAREHOUSE.dbo.RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
LEFT OUTER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
where WO.BASE_ID IN (SELECT BASE_ID FROM #GM_CP_NET_ADJ)
)

, CTE_UNLINKED as
(SELECT 'UNLINKED1' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, SL.SHIPPED_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
	, ACT_BURDEN_COST_HDR = WO.ACT_BURDEN_COST
	, ACT_MATERIAL_COST_HDR = WO.ACT_MATERIAL_COST
	, ACT_LABOR_COST_HDR = WO.ACT_LABOR_COST
	, ACT_SERVICE_COST_HDR = WO.ACT_SERVICE_COST
	, ACT_BURDEN_COST =iXact.ACT_BURDEN_COST
	, ACT_MATERIAL_COST = iXact.ACT_MATERIAL_COST
	, ACT_LABOR_COST = iXact.ACT_LABOR_COST
	, ACT_SERVICE_COST = iXact.ACT_SERVICE_COST
FROM dbo.SHIPPER_LINE SL
INNER JOIN dbo.TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
inner join DATAWAREHOUSE.dbo.inventory_trans iXact
	on T.TRANSACTION_ID = iXact.TRANSACTION_ID
inner join DATAWAREHOUSE.dbo.Trace tra
	on t.TRACE_ID = tra.Id
INNER JOIN dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN dbo.RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND SL.PACKLIST_ID = RL.PACKLIST_ID 
	AND SL.LINE_NO = RL.PACKLIST_LINE_NO 
	AND RL.PACKLIST_ID IS NOT NULL
INNER JOIN dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN dbo.RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN dbo.WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SPLIT_ID = '0'
	AND WO.SUB_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE S.SHIPPED_DATE >= @START
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NULL
	AND COL.ORDER_QTY > 0
UNION ALL
SELECT 'UNLINKED2' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, SL.SHIPPED_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
	, ACT_BURDEN_COST_HDR = WO.ACT_BURDEN_COST
	, ACT_MATERIAL_COST_HDR = WO.ACT_MATERIAL_COST
	, ACT_LABOR_COST_HDR = WO.ACT_LABOR_COST
	, ACT_SERVICE_COST_HDR = WO.ACT_SERVICE_COST
	, ACT_BURDEN_COST =iXact.ACT_BURDEN_COST
	, ACT_MATERIAL_COST = iXact.ACT_MATERIAL_COST
	, ACT_LABOR_COST = iXact.ACT_LABOR_COST
	, ACT_SERVICE_COST = iXact.ACT_SERVICE_COST
FROM dbo.SHIPPER_LINE SL
INNER JOIN dbo.TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
inner join DATAWAREHOUSE.dbo.inventory_trans iXact
	on T.TRANSACTION_ID = iXact.TRANSACTION_ID
inner join DATAWAREHOUSE.dbo.Trace tra
	on t.TRACE_ID = tra.Id
INNER JOIN dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN dbo.RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND SL.PACKLIST_ID = RL.PACKLIST_ID 
	AND SL.LINE_NO = RL.PACKLIST_LINE_NO 
	AND RL.PACKLIST_ID IS NOT NULL
INNER JOIN dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN dbo.RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN dbo.WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID + '/' + WO.SUB_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SPLIT_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE S.SHIPPED_DATE >= @START
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NULL
	AND COL.ORDER_QTY > 0
UNION ALL
SELECT 'UNLINKED3' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, SL.SHIPPED_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
	, ACT_BURDEN_COST_HDR =  WO.ACT_BURDEN_COST
	, ACT_MATERIAL_COST_HDR = WO.ACT_MATERIAL_COST
	, ACT_LABOR_COST_HDR = WO.ACT_LABOR_COST
	, ACT_SERVICE_COST_HDR = WO.ACT_SERVICE_COST
	, ACT_BURDEN_COST =iXact.ACT_BURDEN_COST
	, ACT_MATERIAL_COST = iXact.ACT_MATERIAL_COST
	, ACT_LABOR_COST = iXact.ACT_LABOR_COST
	, ACT_SERVICE_COST = iXact.ACT_SERVICE_COST
FROM dbo.SHIPPER_LINE SL
INNER JOIN dbo.TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
inner join DATAWAREHOUSE.dbo.inventory_trans iXact
	on T.TRANSACTION_ID = iXact.TRANSACTION_ID
inner join DATAWAREHOUSE.dbo.Trace tra
	on t.TRACE_ID = tra.Id
INNER JOIN dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN dbo.RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND SL.PACKLIST_ID = RL.PACKLIST_ID 
	AND SL.LINE_NO = RL.PACKLIST_LINE_NO 
	AND RL.PACKLIST_ID IS NOT NULL
INNER JOIN dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN dbo.RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN dbo.WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID + '.' + WO.SPLIT_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SUB_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE S.SHIPPED_DATE >= @START
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NULL
	AND COL.ORDER_QTY > 0
)

, CTE_COMBINED AS
(SELECT * 
FROM CTE_LINKED
UNION ALL
SELECT * 
FROM CTE_UNLINKED 
)
--SELECT * FROM CTE_COMBINED WHERE CUST_ORDER_ID = '001550232'

, CTE_AMTRIB AS
(SELECT CUST_ORDER_ID
	, REPLACE(REPLACE(BASE_ID, 'A', ''), 'B', '') AS AMT_BASE_ID
	, SUM(REC_AMOUNT) AS AMT_REC_AMOUNT
	, SUM(ACT_BURDEN_COST) AS AMT_BURDEN_COST
	, SUM(ACT_MATERIAL_COST) AS AMT_MATERIAL_COST
	, SUM(ACT_LABOR_COST) AS AMT_LABOR_COST
	, SUM(ACT_SERVICE_COST) AS AMT_SERVICE_COST
FROM CTE_COMBINED
WHERE CUSTOMER_ID = 'AMTRIB'
GROUP BY CUST_ORDER_ID
	, REPLACE(REPLACE(BASE_ID, 'A', ''), 'B', '')
	, REC_QTY
	, SHIPPED_QTY
)
--SELECT * FROM CTE_AMTRIB WHERE CUST_ORDER_ID = '429280'

, CTE_MERGE AS
(SELECT CMB.ORDER_TYPE
	, UDF.STRING_VAL AS BUS_STREAM
	, CASE
		WHEN CMB.CUSTOMER_ID = 'BOE609' AND P.PLANNER_USER_ID = 'FIN-HOURLY' THEN 'CMP-FIN'
		WHEN CMB.CUSTOMER_ID = 'BOE609' AND P.PLANNER_USER_ID = 'FIN' THEN 'CMP-FIN'
		WHEN CMB.CUSTOMER_ID = 'BOE609' AND P.PLANNER_USER_ID = 'MFG-HOURLY' THEN 'CMP-MFG'
		WHEN CMB.CUSTOMER_ID = 'BOE609' AND P.PLANNER_USER_ID = 'MFG' THEN 'CMP-MFG'
		ELSE UDF.STRING_VAL
	END AS BUS_UNIT
	, P.PLANNER_USER_ID
	, P.BUYER_USER_ID
	, B.Salesperson_ID
	, CMB.CO_CREATE_DATE
	, CMB.WO_CREATE_DATE
	, CMB.SHIPPED_DATE
	, CMB.CUSTOMER_ID
	, CMB.CUST_ORDER_ID
	, CMB.COL_LINE
	, CMB.BASE_ID
	, CMB.LOT_ID
	, CMB.SPLIT_ID
	, CMB.SUB_ID
	, CMB.WO_STATUS
	, CMB.PACKLIST_ID
	, CMB.TRANSACTION_ID
	, CMB.INVOICE_ID
	, CMB.INV_LINE
	, CMB.PART_ID
	, CMB.SHIP_SHORT
	, CMB.TRACE_ID
	, CMB.TOTAL_SHIPPED_QTY
	, CMB.COL_ORDER_QTY
	, CMB.DESIRED_QTY
	, CMB.TRACE_QTY
	, CMB.SHIPPED_QTY
	, CMB.REC_QTY
	, CMB.COL_UNIT_PRICE
	, CMB.REC_AMOUNT
	, CASE
		WHEN CMB.BASE_ID LIKE '%R%' THEN 0						--> REWORK
		WHEN CMB.INVOICE_ID LIKE '%DM%' THEN 0						--> DM
		WHEN CMB.INVOICE_ID LIKE '%CM%' THEN 0						--> CM
		WHEN CMB.COL_ORDER_QTY <= 0 THEN 0
		WHEN BOE.ID IS NOT NULL THEN BOE.[SPECIAL FEES]
		ELSE ISNULL(CTE01.UNIT_CHARGE_ALLOC, 0) * ISNULL(TRACE_QTY, SHIPPED_QTY)
	END AS TRACE_CHARGE_ALLOC
	, CASE 
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.AMT_REC_AMOUNT
		WHEN BOE.ID IS NOT NULL THEN BOE.SUM_EXTENDED_DOLLARS
		ELSE CMB.REC_AMOUNT
	END AS TOTAL_INVOICE_AMOUNT
	, ISNULL(TRACE_QTY, SHIPPED_QTY) * (CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.AMT_REC_AMOUNT
		WHEN BOE.ID IS NOT NULL THEN BOE.SUM_EXTENDED_DOLLARS
		ELSE CMB.REC_AMOUNT
	END / ISNULL(REC_QTY, SHIPPED_QTY)) AS TRACE_INVOICE_AMOUNT
	, CASE 
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.AMT_REC_AMOUNT
		WHEN BOE.ID IS NOT NULL THEN BOE.SUM_EXTENDED_DOLLARS
		ELSE CMB.REC_AMOUNT
	END / ISNULL(REC_QTY, SHIPPED_QTY) AS UNIT_INVOICE_AMOUNT

	/************************************************************
		GROSS MARGIN REPORT REQUIREMENTS

		#1 TOTAL_BURDEN COST = ACT_BURDEN_COST -- HDR
		 * line cost is @header-cost-unit
		#2 UNIT_BURDEN_COST = TOTAL_BURDEN_COST (#1) / DESIRED_QTY  -- HDR
		#3 TRACE_BURDEN_COST = TRACE_QTY @line-level * #2 UNIT @header-level  -- LINE

		##Totals##
		#4 TOTAL_TRACE_COST = SUM OF COSTS @line-level
		#5 TRACE_UNIT_COST =  SUM OF COSTS @line-level /TRACE_QTY --LINE AGGREGATE
		#6 TOTAL_UNIT_COST =  SUM OF UNIT COSTS @header-level / DESIRED_QTY --HDR AGGREGATE

		Function Requirements Test
		Base_id = 1502771, transaction_id = 2509230
		#1 TOTAL_BURDEN COST = 1107.49
		#2 UNIT_BURDEN_COST  = 4.429960
		#3 TRACE_BURDEN_COST = 13.289880
		#4 TOTAL_TRACE_COST = 137.655960
		#5 TRACE_UNIT_COST = 45.986210
		#6 TOTAL_UNIT_COST = 45.986210

		CHARGE ALLOCATIONS ARE PRORATED ACROSS PART QTY.
		ORDERS THAT CONTAIN ANY NEGATUVE CHARGE AMOUNT (REFUNDS) WILL HAVE THE
		CHARGE ALLLOCATIONS LANDING ON INVOICE_ID, INV_LINE FOR PACKLIST

	*************************************************************/
	, CMB.ACT_BURDEN_COST AS TOTAL_BURDEN_COST_LINE   --
	, CMB.ACT_MATERIAL_COST AS TOTAL_MATERIAL_COST_LINE
	, CMB.ACT_LABOR_COST AS TOTAL_LABOR_COST_LINE
	, CMB.ACT_SERVICE_COST AS TOTAL_SERVICE_COST_LINE
	, CMB.ACT_BURDEN_COST_HDR AS TOTAL_BURDEN_COST
	, CMB.ACT_MATERIAL_COST_HDR AS TOTAL_MATERIAL_COST
	, CMB.ACT_LABOR_COST_HDR AS TOTAL_LABOR_COST
	, CMB.ACT_SERVICE_COST_HDR AS TOTAL_SERVICE_COST
	, ISNULL(TRACE_QTY, SHIPPED_QTY) * (CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.AMT_BURDEN_COST
		WHEN CMB.CUSTOMER_ID = 'AMTRIB' AND CMB.BASE_ID != REPLACE(REPLACE(CMB.BASE_ID, 'A', ''), 'B', '') THEN 0
		ELSE CMB.ACT_BURDEN_COST_HDR
		END / CMB.DESIRED_QTY ) AS TRACE_BURDEN_COST
	, ISNULL(TRACE_QTY, SHIPPED_QTY) * (CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.AMT_BURDEN_COST
		WHEN CMB.CUSTOMER_ID = 'AMTRIB' AND CMB.BASE_ID != REPLACE(REPLACE(CMB.BASE_ID, 'A', ''), 'B', '') THEN 0
		ELSE CMB.ACT_BURDEN_COST_HDR
		END / CMB.DESIRED_QTY) AS TRACE_BURDEN_COST_HDR
	, ISNULL(TRACE_QTY, SHIPPED_QTY) * (CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.AMT_MATERIAL_COST
		WHEN CMB.CUSTOMER_ID = 'AMTRIB' AND CMB.BASE_ID != REPLACE(REPLACE(CMB.BASE_ID, 'A', ''), 'B', '') THEN 0
		ELSE CMB.ACT_MATERIAL_COST_HDR
		END / CMB.DESIRED_QTY) AS TRACE_MATERIAL_COST
	, ISNULL(TRACE_QTY, SHIPPED_QTY) * (CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.AMT_MATERIAL_COST
		WHEN CMB.CUSTOMER_ID = 'AMTRIB' AND CMB.BASE_ID != REPLACE(REPLACE(CMB.BASE_ID, 'A', ''), 'B', '') THEN 0
		ELSE CMB.ACT_MATERIAL_COST_HDR
		END / CMB.DESIRED_QTY)  AS TRACE_MATERIAL_COST_HDR
	, ISNULL(TRACE_QTY, SHIPPED_QTY) * (CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.AMT_LABOR_COST
		WHEN CMB.CUSTOMER_ID = 'AMTRIB' AND CMB.BASE_ID != REPLACE(REPLACE(CMB.BASE_ID, 'A', ''), 'B', '') THEN 0
		ELSE CMB.ACT_LABOR_COST_HDR
		END / CMB.DESIRED_QTY) AS TRACE_LABOR_COST
	, ISNULL(TRACE_QTY, SHIPPED_QTY) * (CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.AMT_LABOR_COST
		WHEN CMB.CUSTOMER_ID = 'AMTRIB' AND CMB.BASE_ID != REPLACE(REPLACE(CMB.BASE_ID, 'A', ''), 'B', '') THEN 0
		ELSE CMB.ACT_LABOR_COST_HDR
		END / CMB.DESIRED_QTY) AS TRACE_LABOR_COST_HDR
	, ISNULL(TRACE_QTY, SHIPPED_QTY) * (CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.AMT_SERVICE_COST
		WHEN CMB.CUSTOMER_ID = 'AMTRIB' AND CMB.BASE_ID != REPLACE(REPLACE(CMB.BASE_ID, 'A', ''), 'B', '') THEN 0
		ELSE CMB.ACT_SERVICE_COST_HDR
		END / CMB.DESIRED_QTY) AS TRACE_SERVICE_COST
		, ISNULL(TRACE_QTY, SHIPPED_QTY) * (CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.AMT_SERVICE_COST
		WHEN CMB.CUSTOMER_ID = 'AMTRIB' AND CMB.BASE_ID != REPLACE(REPLACE(CMB.BASE_ID, 'A', ''), 'B', '') THEN 0
		ELSE CMB.ACT_SERVICE_COST_HDR
		END / CMB.DESIRED_QTY) AS TRACE_SERVICE_COST_HDR
	, CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.AMT_BURDEN_COST
		WHEN CMB.CUSTOMER_ID = 'AMTRIB' AND CMB.BASE_ID != REPLACE(REPLACE(CMB.BASE_ID, 'A', ''), 'B', '') THEN 0
		WHEN INVOICE_ID LIKE '%DM%' THEN 0						--> DM
		WHEN INVOICE_ID LIKE '%CM%' THEN 0						--> CM
		ELSE CMB.ACT_BURDEN_COST_HDR   -- Version 2
		END / (CMB.DESIRED_QTY) AS UNIT_BURDEN_COST
	, CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.AMT_MATERIAL_COST
		WHEN CMB.CUSTOMER_ID = 'AMTRIB' AND CMB.BASE_ID != REPLACE(REPLACE(CMB.BASE_ID, 'A', ''), 'B', '') THEN 0
		WHEN INVOICE_ID LIKE '%DM%' THEN 0						--> DM
		WHEN INVOICE_ID LIKE '%CM%' THEN 0						--> CM
		ELSE CMB.ACT_MATERIAL_COST_HDR  -- Version 2
		END / (CMB.DESIRED_QTY) AS UNIT_MATERIAL_COST
	, CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.AMT_LABOR_COST
		WHEN CMB.CUSTOMER_ID = 'AMTRIB' AND CMB.BASE_ID != REPLACE(REPLACE(CMB.BASE_ID, 'A', ''), 'B', '') THEN 0
		WHEN INVOICE_ID LIKE '%DM%' THEN 0						--> DM
		WHEN INVOICE_ID LIKE '%CM%' THEN 0						--> CM
		ELSE CMB.ACT_LABOR_COST_HDR  -- Version 2
	END / (CMB.DESIRED_QTY) AS UNIT_LABOR_COST
	, CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.AMT_SERVICE_COST
		WHEN CMB.CUSTOMER_ID = 'AMTRIB' AND CMB.BASE_ID != REPLACE(REPLACE(CMB.BASE_ID, 'A', ''), 'B', '') THEN 0
		WHEN INVOICE_ID LIKE '%DM%' THEN 0						--> DM
		WHEN INVOICE_ID LIKE '%CM%' THEN 0						--> CM
		ELSE CMB.ACT_SERVICE_COST_HDR
	END / (CMB.DESIRED_QTY) AS UNIT_SERVICE_COST

-->  audit purposes
	, CTE01.TOTAL_CHARGE
	, CTE01.PART_QTY
	, CTE01.UNIT_CHARGE_ALLOC
	, BOE.[PART NUMBER]
	, BOE.SUM_EXTENDED_DOLLARS
	, BOE.TOTAL_HOURS
	, AMT.AMT_BASE_ID
	, AMT.AMT_REC_AMOUNT
	, AMT.AMT_BURDEN_COST
	, AMT.AMT_MATERIAL_COST
	, AMT.AMT_LABOR_COST
	, AMT.AMT_SERVICE_COST
-->

FROM CTE_COMBINED CMB 
LEFT OUTER JOIN #BUS_UNIT UDF
	ON UDF.DOCUMENT_ID = CMB.CUSTOMER_ID
	AND UDF.PROGRAM_ID = 'VMCUSMNT'
	AND UDF.ID = 'UDF-0000072'
LEFT OUTER JOIN dbo.PART_SITE P
	ON P.PART_ID = CMB.PART_ID
LEFT OUTER JOIN LIVESupplemental.dbo.buyer_assn B
	ON LEFT(P.BUYER_USER_ID, 2) = B.Account_ID
LEFT OUTER JOIN CTE_CHGAMTS CTE01
	ON CMB.CUST_ORDER_ID = CTE01.CUST_ORDER_ID
LEFT OUTER JOIN CTE_BOE BOE
	ON BOE.ID = CMB.CUST_ORDER_ID
--	AND BOE.BASE_ID = CMB.BASE_ID
LEFT OUTER JOIN CTE_AMTRIB AMT
	ON AMT.CUST_ORDER_ID = CMB.CUST_ORDER_ID
	AND AMT.AMT_BASE_ID = CMB.BASE_ID
)
--SELECT *  into #temp7 FROM CTE_MERGE   -- WHERE CUST_ORDER_ID = '431574'

INSERT INTO #Results
           (
            [REC_ISSUES]
           ,[ORDER_TYPE]
           ,[BUS_STREAM]
           ,[BUS_UNIT]
           ,[PLANNER_USER_ID]
           ,[BUYER_USER_ID]
           ,[Salesperson_ID]
           ,[CO_CREATE_DATE]
           ,[WO_CREATE_DATE]
           ,[SHIPPED_DATE]
           ,[CUSTOMER_ID]
           ,[CUST_ORDER_ID]
           ,[COL_LINE]
           ,[BASE_ID]
           ,[LOT_ID]
           ,[SPLIT_ID]
           ,[SUB_ID]
           ,[WO_STATUS]
           ,[PACKLIST_ID]
           ,[TRANSACTION_ID]
           ,[INVOICE_ID]
           ,[INV_LINE]
           ,[PART_ID]
           ,[SHIP_SHORT]
           ,[TRACE_ID]
           ,[TOTAL_SHIPPED_QTY]
           ,[COL_ORDER_QTY]
           ,[DESIRED_QTY]
           ,[TRACE_QTY]
           ,[SHIPPED_QTY]
           ,[REC_QTY]
           ,[COL_UNIT_PRICE]
           ,[REC_AMOUNT]
           ,[TRACE_CHARGE_ALLOC]
           ,[TOTAL_INVOICE_AMOUNT]
           ,[TRACE_INVOICE_AMOUNT]
           ,[UNIT_INVOICE_AMOUNT]
           ,[TOTAL_BURDEN_COST]
           ,[TOTAL_MATERIAL_COST]
           ,[TOTAL_LABOR_COST]
           ,[TOTAL_SERVICE_COST]
           ,[TRACE_BURDEN_COST]
           ,[TRACE_MATERIAL_COST]
           ,[TRACE_LABOR_COST]
           ,[TRACE_SERVICE_COST]
           ,[UNIT_BURDEN_COST]
           ,[UNIT_MATERIAL_COST]
           ,[UNIT_LABOR_COST]
           ,[UNIT_SERVICE_COST]
           ,[TOTAL_CHARGE]
           ,[PART_QTY]
           ,[UNIT_CHARGE_ALLOC]
           ,[PART NUMBER]
           ,[SUM_EXTENDED_DOLLARS]
           ,[TOTAL_HOURS]
           ,[AMT_BASE_ID]
           ,[AMT_REC_AMOUNT]
           ,[AMT_BURDEN_COST]
           ,[AMT_MATERIAL_COST]
           ,[AMT_LABOR_COST]
           ,[AMT_SERVICE_COST]
           ,[TRACE_BURDEN_COST_HDR]
           ,[TRACE_MATERIAL_COST_HDR]
           ,[TRACE_LABOR_COST_HDR]
           ,[TRACE_SERVICE_COST_HDR]
           ,[TRACE_PRICE]
           ,[INV_UNIT_PRICE]
           ,[UNITPRICE_DELTA]
           ,[TOTAL_TRACE_COST]
           ,[TRACE_UNIT_COST]
           ,[TOTAL_UNIT_COST]
           )

SELECT 
   CASE
		WHEN CUSTOMER_ID = 'AMTRIB' THEN 'AMTRIB'
		WHEN CUSTOMER_ID = 'SPIAER' THEN 'SPIAER'
		WHEN INVOICE_ID LIKE '%DM' OR INVOICE_ID LIKE '%DM' THEN 'DM/CM'
		WHEN BASE_ID LIKE '%R%' THEN 'REWORK'
		WHEN TRACE_INVOICE_AMOUNT < 0 AND REC_QTY < 0 THEN 'RETURN'
		WHEN TRACE_INVOICE_AMOUNT < 0 AND REC_QTY > 0 THEN 'CREDIT'
		WHEN TRACE_INVOICE_AMOUNT = 0 AND TRACE_CHARGE_ALLOC > 0 THEN 'CHARGE'
--		WHEN REC_AMOUNT = 0 AND CHARGE_ALLOC = 0 AND MRG.[STATUS] = 'X' THEN 'CANCELLED'
		WHEN TRACE_INVOICE_AMOUNT > 0 THEN 'INVOICE'
		ELSE 'ISSUES'
	END AS REC_ISSUES
	
 ,MRG.ORDER_TYPE,MRG.BUS_STREAM ,MRG.BUS_UNIT ,MRG.PLANNER_USER_ID
 ,MRG.BUYER_USER_ID,MRG.Salesperson_ID ,MRG.CO_CREATE_DATE ,MRG.WO_CREATE_DATE
 ,MRG.SHIPPED_DATE,MRG.CUSTOMER_ID ,MRG.CUST_ORDER_ID ,MRG.COL_LINE
 
 ,MRG.BASE_ID
 ,MRG.LOT_ID 
 ,MRG.SPLIT_ID ,MRG.SUB_ID
 ,MRG.WO_STATUS 

 ,MRG.PACKLIST_ID ,MRG.TRANSACTION_ID ,MRG.INVOICE_ID
 ,MRG.INV_LINE 
 ,MRG.PART_ID 
 
 ,MRG.SHIP_SHORT 
 ,MRG.TRACE_ID
 ,MRG.TOTAL_SHIPPED_QTY ,MRG.COL_ORDER_QTY 
 ,MRG.DESIRED_QTY ,MRG.TRACE_QTY
 
 ,MRG.SHIPPED_QTY 
 ,MRG.REC_QTY 
 ,MRG.COL_UNIT_PRICE 
 ,MRG.REC_AMOUNT
 ,MRG.TRACE_CHARGE_ALLOC ,MRG.TOTAL_INVOICE_AMOUNT ,MRG.TRACE_INVOICE_AMOUNT 
 ,MRG.UNIT_INVOICE_AMOUNT
 
 ,MRG.TOTAL_BURDEN_COST 
 ,MRG.TOTAL_MATERIAL_COST 
 ,MRG.TOTAL_LABOR_COST 
 ,MRG.TOTAL_SERVICE_COST
 ,MRG.TRACE_BURDEN_COST 
 ,MRG.TRACE_MATERIAL_COST 
 ,MRG.TRACE_LABOR_COST 
 ,MRG.TRACE_SERVICE_COST
 ,MRG.UNIT_BURDEN_COST 
 ,MRG.UNIT_MATERIAL_COST ,MRG.UNIT_LABOR_COST ,MRG.UNIT_SERVICE_COST

 ,MRG.TOTAL_CHARGE ,MRG.PART_QTY ,MRG.UNIT_CHARGE_ALLOC, MRG.[PART NUMBER]
 ,MRG.SUM_EXTENDED_DOLLARS ,MRG.TOTAL_HOURS ,MRG.AMT_BASE_ID ,MRG.AMT_REC_AMOUNT
 
 ,MRG.AMT_BURDEN_COST 
 ,MRG.AMT_MATERIAL_COST 
 ,MRG.AMT_LABOR_COST
 ,MRG.AMT_SERVICE_COST

,TRACE_BURDEN_COST_HDR   -- TESTING
,TRACE_MATERIAL_COST_HDR 
,TRACE_LABOR_COST_HDR 
,TRACE_SERVICE_COST_HDR

, (TRACE_CHARGE_ALLOC + TRACE_INVOICE_AMOUNT) / ISNULL(NULLIF(TRACE_QTY,0.), SHIPPED_QTY) AS TRACE_PRICE
, (TRACE_CHARGE_ALLOC + TRACE_INVOICE_AMOUNT) / ISNULL(NULLIF(TRACE_QTY,0.), SHIPPED_QTY) AS INV_UNIT_PRICE
, (COL_UNIT_PRICE - ((TRACE_CHARGE_ALLOC + TRACE_INVOICE_AMOUNT) / ISNULL(NULLIF(TRACE_QTY,0.), SHIPPED_QTY))) AS UNITPRICE_DELTA

----, (TRACE_BURDEN_COST + TRACE_MATERIAL_COST + TRACE_LABOR_COST + TRACE_SERVICE_COST) AS TOTAL_TRACE_COST
, (TRACE_BURDEN_COST_HDR + TRACE_MATERIAL_COST_HDR + TRACE_LABOR_COST_HDR + TRACE_SERVICE_COST_HDR) AS TOTAL_TRACE_COST
	
, (TRACE_BURDEN_COST + TRACE_MATERIAL_COST + TRACE_LABOR_COST + TRACE_SERVICE_COST) / ISNULL(NULLIF(TRACE_QTY,0), SHIPPED_QTY) AS TRACE_UNIT_COST

, UNIT_BURDEN_COST + UNIT_MATERIAL_COST + UNIT_LABOR_COST + UNIT_SERVICE_COST AS TOTAL_UNIT_COST

FROM CTE_MERGE MRG

WHERE (1=1)

update_fact_table2:
 
set transaction isolation level read uncommitted
set deadlock_priority low
-- declare @start date = '2017-12-01'
 
if object_id('tempdb..#fact1') is not null drop table #fact1;
if object_id('tempdb..#fact2') is not null drop table #fact2;
if object_id('tempdb..#fact3') is not null drop table #fact3;
if object_id('tempdb..#detail1') is not null drop table #detail1;
if object_id('tempdb..#detail2') is not null drop table #detail2;
if object_id('tempdb..#detail3') is not null drop table #detail3;
if object_id('tempdb..#fact2Data') is not null drop table #fact2Data;
IF OBJECT_ID('tempdb..#alloc_4') IS NOT NULL DROP TABLE #alloc_4
if object_id('tempdb..#fact2Data') is not null drop table #fact2Data;
IF OBJECT_ID('tempdb..#CTE_PARTS') IS NOT NULL DROP TABLE #CTE_PARTS
IF OBJECT_ID('tempdb..#CTE_PARTS2') IS NOT NULL DROP TABLE #CTE_PARTS2
IF OBJECT_ID('tempdb..#CTE_CHARGES2 ') IS NOT NULL DROP TABLE #CTE_CHARGES2 
IF OBJECT_ID('tempdb..#Parts_Level2') IS NOT NULL DROP TABLE #Parts_Level2
IF OBJECT_ID('tempdb..#Parts_Level1') IS NOT NULL DROP TABLE #Parts_Level1

select 
	 'fact2_1' as dw_report_group,
	 col.cust_order_id
	,col.line_no as col_line
	,sl.packlist_id
	,sl.line_no as packlist_line_no
	,rl.invoice_id
	,rl.line_no inv_line 
	,col.PART_ID Line1_Part_ID
	,col.PART_ID
	,convert(decimal(15,2),max(rl.AMOUNT)) rec_amount
	--,rl.packlist_line_no
	,count(distinct rl.invoice_id) ct_invoices
	,iif(col.SERVICE_CHARGE_ID is not null,'Y',NULL) service_charge_id  -- is not null for chgs
	,iif(col.SERVICE_CHARGE_ID is not null,null,1) IsAllocated 

	--,colLine1.LINE_NO Line1_COL_LINE
	--,rlLine1.Line_No Line1_inv_line

	into #fact1
from dbo.shipper_line sl
inner join dbo.shipper s
	on sl.packlist_id = s.packlist_id
join dbo.cust_order_line col
	on sl.cust_order_id = col.cust_order_id
	and sl.CUST_ORDER_LINE_NO = col.line_no
inner join dbo.customer_order co
	on col.cust_order_id = co.id
left outer join dbo.receivable_line rl
	on rl.cust_order_id = col.cust_order_id
	and rl.cust_order_line_no = col.line_no
	-- william in test
    and rl.packlist_id = sl.packlist_id
    and rl.packlist_line_no = sl.line_no
left outer join dbo.receivable r
	on rl.invoice_id = r.invoice_id
where (1=1) 
	and co.create_date >= '1/1/2015'
	and co.[status] != 'x'
	and 0 > some (select rl2.amount 
		from dbo.shipper_line sl2
		inner join dbo.shipper s2
			on sl2.packlist_id = s2.packlist_id
		join dbo.cust_order_line col2
			on sl2.cust_order_id = col2.cust_order_id
			and sl2.cust_order_line_no = col2.line_no
		inner join dbo.customer_order co2
			on col2.cust_order_id = co2.id
		left outer join dbo.receivable_line rl2
			on rl2.cust_order_id = col2.cust_order_id
			and rl2.cust_order_line_no = col2.line_no
		left outer join dbo.receivable r2
			on rl2.invoice_id = r2.invoice_id
		where (1=1)
			and sl.cust_order_id = col2.cust_order_id
			    AND COL2.SERVICE_CHARGE_ID IS NOT NULL
		)
    AND S.SHIPPED_DATE >= @START
group by col.cust_order_id
	, col.line_no
	, sl.packlist_id
	, sl.line_no 
	, rl.invoice_id
	, rl.packlist_id
	, rl.LINE_NO 
	, col.PART_ID
	, rl.PACKLIST_LINE_NO
	, iif(col.SERVICE_CHARGE_ID is not null,'Y',null) 
	, iif(col.SERVICE_CHARGE_ID is not null,null,1)
order by col.cust_order_id
, col.line_no
, sl.packlist_id
, sl.line_no 
, rl.invoice_id
, rl.packlist_id

/*************************************************************************************
description:	fact2_2 ; aggregates in order to check for multiple invoices outside of grain
purpose:	fact table2.2
note: ** gets the min col_line from the set of records within the co, in order to land the aggregated chgs.		
note: ** gets the min inv_line from the set of records within the co, in order to land the aggregated chgs.	

date        modified by         change description
----------  ------------------  -----------------------------------------------------------
12/12/2019	William Thompson	added inv_line to fact tables.
12/12/2019	William Thompson	rl.line_no (inv_line) and invoice_id used to land charges/refunded chgs
12/13/2019	William Thompson	The aggregations are done here in order to summarize the allocation
12/17/2019  William Thompson	Land allocations.

****************************************************************************************/

select
    'fact2_2' as dw_report_group,
	 cust_order_id
	,convert(smallint,min(col_line)) as col_line  -- col_line **
	,convert(smallint,min(col_line)) as Line1_COL_LINE  -- col_line **
	,convert(nvarchar(15),min(packlist_id)) as packlist_id
	,invoice_id
	,max(INVOICE_ID) max_invoice_id
	,min(INVOICE_ID) min_invoice_id
	,part_id
	,Line1_Part_ID
	, convert(smallint,min(inv_line)) as inv_line
	,sum(convert(decimal(15,2), rec_amount)) rec_amount
	, count(distinct invoice_id) ct
	, max(IsAllocated) IsAllocated
	, iif(service_charge_id is not null,1,0) IsServiceCharge
	into #fact2
from #fact1
where (1=1)
group by cust_order_id
	, invoice_id
	, part_id
	, Line1_Part_ID
	, iif(service_charge_id is not null,1,0)
order by cust_order_id
	, col_line -- col.line_no
	, packlist_id
	, invoice_id
	, part_id
	, Line1_Part_ID

test_table_fact_2_2:
-- select * from #fact2
-- select * from #fact1

/**********************************************************************************************
 fact table.2.2. ENDS //////////////////////////////////////////////////////////		

**********************************************************************************************/ 

-- **********************************  allocations *******************************************
-- **********************************  allocations *******************************************
-- **********************************  allocations *******************************************



 /**********************************************************************************************
Description:	cte_part2
Sample:			

Date        Modified By         Change Description
----------  ------------------  ------------------------------------------------------------
12/17/2019	William Thompson	Allocation 1 ** - cte_parts determine if IsAllocated


**********************************************************************************************/
 ---- ALLOC1ALLOC1ALLOC1
 -- DECLARE @START DATETIME = '2017-12-01'

---- #CTE_PARTS2 *******
----, CTE_PARTS AS
	select
	   		'CTE_parts2' as descript
  
			-- level_2.descript
			,level_2.dw_level
			,level_2.CUST_ORDER_ID
			,level_2.COL_LINE
			,level_2.ORDER_QTY
			,level_2.PART_ID
			,level_2.SERVICE_CHARGE_ID
			,level_2.IsBaseReworked
			,level_2.SUPPLY_BASE_ID
			,level_2.SUPPLY_TYPE
			,level_2.IsSupplyBaseIdNull
			,level_2.IsPartIDNull
			,level_2.IsBothDemandBaseDemandSeqNull
			,level_2.SumOfParts
	  into #CTE_PARTS2
	from (
		select 
			'CTE-parts2' as descript
  
			-- level_1.descript
			,dw_level = 'level_2'
			,level_1.CUST_ORDER_ID
			,level_1.COL_LINE
			,level_1.ORDER_QTY
			,level_1.PART_ID
			,level_1.SERVICE_CHARGE_ID
			,level_1.IsBaseReworked
			,level_1.SUPPLY_BASE_ID
			,level_1.SUPPLY_TYPE
			,level_1.IsSupplyBaseIdNull
			,level_1.IsPartIDNull
			,level_1.IsBothDemandBaseDemandSeqNull

			,SumOfParts = CASE level_1.IsBothDemandBaseDemandSeqNull
					WHEN 0 THEN
						CASE level_1.IsPartIDNull
						WHEN 0 THEN
							CASE level_1.IsBaseReworked
							WHEN 0 THEN
								1   -- SumOfParts
							ELSE
								0
							END
						ELSE
							0
						END
					ELSE
						0
					END
	
		from (
		SELECT 
			-- Test select star 12/16
			  dw_level = 'level_1'
			, col.CUST_ORDER_ID
			, col.LINE_NO COL_LINE
			, col.ORDER_QTY
			, col.PART_ID
			, COL.SERVICE_CHARGE_ID 
			, iif(ISNULL(DSL.SUPPLY_BASE_ID,'') NOT LIKE '%R%',0,1) IsBaseReworked
			, DSL.SUPPLY_BASE_ID
			, DSL.SUPPLY_TYPE
			, iif(DSL.SUPPLY_BASE_ID IS NULL,1,0) IsSupplyBaseIdNull
			, iif(COL.PART_ID is null, 1, 0) IsPartIDNull
			, iif(DEMAND_BASE_ID is null and DEMAND_SEQ_NO is null, 1, 0) IsBothDemandBaseDemandSeqNull
			-- cte2 is calculated 
			-- sumOfParts is calculated function of order_qty
			-- note: constraints moved to level1
		FROM dbo.CUST_ORDER_LINE COL
		INNER JOIN dbo.CUSTOMER_ORDER CO
			ON COL.CUST_ORDER_ID = CO.ID

		LEFT OUTER JOIN dbo.DEMAND_SUPPLY_LINK DSL
			ON DSL.DEMAND_TYPE = 'CO'
			AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
			AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
			--AND DSL.SUPPLY_BASE_ID NOT LIKE '%R%' 
		WHERE (1=1)
		  -- William in Test 12/17/19
		 -- and CUST_ORDER_ID IN (SELECT ID FROM #CUSTOMER_ORDER)


		) level_1
		where (1=1)

    ) level_2
	where (1=1)

test_cte_parts2:
--select * from #CTE_PARTS2

 /**********************************************************************************************
Description:	Agg_parts2
Sample:			

Date        Modified By         Change Description
----------  ------------------  ------------------------------------------------------------
12/17/2019	William Thompson	Allocation 2 ** - sum of parts, isAllocated = 1

**********************************************************************************************/

test_cte_parts2_level2:

SELECT 'Agg_parts2' DESCRIPT
    ,level_2.dw_level
	,level_2.CUST_ORDER_ID
	,IsAllocated = convert(FLOAT,1.)    -- join
	, CAST(
	sum(level_2.SumOfParts)
	AS FLOAT) SumOfParts
	into #Parts_Level2
FROM #CTE_PARTS2 level_2
--WHERE CUST_ORDER_ID IN (SELECT ID FROM #CUSTOMER_ORDER)
GROUP BY
     level_2.dw_level
	,level_2.CUST_ORDER_ID

ORDER BY CUST_ORDER_ID

profile_cte_parts2_level2:
--select * from #Parts_Level2

/**********************************************************************************************
 Agg_parts2 ENDS (ALLOC2) //////////////////////////////////////////////////////////		

**********************************************************************************************/

/**********************************************************************************************
Description:	land_parts2
Sample:			

Date        Modified By         Change Description
----------  ------------------  ------------------------------------------------------------
12/17/2019	William Thompson	Allocation 3 - allocation formula
12/17/2019	William Thompson	join on cust_order_ID, isAllocation

Tester:
Allocation Formula:
    a.) Is the sum of charges - $900
    b.) Sum of quantity of parts on CO - 3

    a / b.
     ($900/3) = $300 per part quantity

**********************************************************************************************/

test_ctePart2_level1:
SELECT 'land_parts2' DESCRIPT
    ,level_1.dw_level
	,level_1.CUST_ORDER_ID
	,level_1.COL_LINE
	,level_1.ORDER_QTY
	,level_1.PART_ID
	,level_1.SERVICE_CHARGE_ID
	--,level_1.IsBaseReworked
	,level_1.SUPPLY_BASE_ID
	,level_1.SumOfParts IsAllocated    -- join
	,level_2.SumOfParts
	,CONVERT(FLOAT,level_1.SumOfParts)/CONVERT(float,level_2.SumOfParts) unit_charge_alloc
	into #Parts_Level1

from #CTE_PARTS2 level_1
left join #Parts_Level2 level_2
on level_2.IsAllocated = level_1.SumOfParts
and level_2.CUST_ORDER_ID = level_1.CUST_ORDER_ID
ORDER BY level_1.CUST_ORDER_ID

-- drop table #Parts_Level1
profile_parts_level2:
--select * from #Parts_Level1
-- select * from #parts_level2 order by CUST_ORDER_ID, COL_LINE

/**********************************************************************************************
Description:	allocation 4 ** intro invoice 
Sample:			

Date        Modified By         Change Description
----------  ------------------  ------------------------------------------------------------
12/17/2019	William Thompson	## fact2_2 will join with land_parts2 on --- > cust_order_id, col_line, isAllocated


**********************************************************************************************/

select
	 dw_report_group = 'alloc-join'
	,f2.cust_order_id
	,f2.col_line
	,f2.Line1_COL_LINE
	,f2.packlist_id
	,f2.invoice_id
	,f2.max_invoice_id
	,f2.min_invoice_id
	,f2.part_id
	,f2.Line1_Part_ID
	,f2.inv_line
	,f2.rec_amount
	,f2.ct
	,f2.IsAllocated
	,f2.IsServiceCharge
	,land.dw_level
	,land.ORDER_QTY
	--,land.PART_ID
	,land.SERVICE_CHARGE_ID
	,land.SumOfParts
	,land.unit_charge_alloc
	into #alloc_4
from #fact2 f2
left join #Parts_Level1 land
on f2.CUST_ORDER_ID = land.CUST_ORDER_ID
and f2.col_line = land.COL_LINE
and f2.IsAllocated = land.IsAllocated

test_alloc4:

/**********************************************************************************************
description:	profile adjusting inv-003 multiple packlists some negative fact table by isneg.sql
purpose: fact table.2.3.		

date        modified by         change description
----------  ------------------  ------------------------------------------------------------
12/12/2019	William Thompson	Created.
12/13/2019  William Thompson	fact3 defines the grain of data to be allocated and rolls up charges
fact table keys
========================
	cust_order_id,col_line,packlist_id,invoice_id
	,invoice_line_no,packlist_line_no, part_id

	*packlist_line_no may be excluded
**********************************************************************************************/
----- 333333333333333333 ------------------------------------------------------------33333333333333333333
-- declare @start date = '2017-12-01'

select
     dw_report_group = 'fact2_3_Level_2'
	,level_1.cust_order_id
	,level_1.col_line
	,level_1.rec_amount
	,level_1.invoiceisnegative
	,level_1.packlist_id
	,level_1.invoice_id
	,level_1.line1_Part_Id
	,level_1.part_id
	,level_1.inv_line
	,level_1.packlist_line_no
	,iif(dw_isServiceCharge = 1,1,0) Allocated  -- > allocation
    
	 into #fact3
from (
	select 
		'fact2_3_Level_1' as dw_report_group,
		  col.cust_order_id
		, f22.col_line col_line  
	--	, f22.Line1_COL_LINE line1_col_line			-- note aggregated line 1 value of col_line.
		, rec_amount = f22.rec_amount				-- note aggregated rl.amount
		, invoiceisnegative = iif (rl.amount < 0 , 1, 0 )
		, sl.packlist_id
		, rl.invoice_id
		, colLine1.part_id line1_Part_Id
		, coalesce(col.part_id,colline1.part_id) part_id
		, rl.LINE_NO inv_line
		--, f22.Line1_inv_line line1_inv_line
		, rl.packlist_line_no
		, iif(col.service_charge_id is null,0,1) dw_isServiceCharge

	FROM dbo.shipper_line sl
		--on sl.packlist_id = tt.packlist_id
		--and sl.line_no =tt.packlist_line_no
	inner join dbo.shipper s
		on sl.packlist_id = s.packlist_id
	join dbo.cust_order_line col
		on sl.cust_order_id = col.cust_order_id
		and sl.CUST_ORDER_LINE_NO = col.line_no

	join dbo.cust_order_line colLine1
		on colLine1.cust_order_id = col.cust_order_id
		and colLine1.line_no = 1
	inner join dbo.customer_order co
		on col.cust_order_id = co.id
	left outer join dbo.receivable_line rl
		on rl.cust_order_id = col.cust_order_id
		and rl.cust_order_line_no = col.line_no
		--  william in test 12/10
		and rl.packlist_id = sl.packlist_id
		and rl.packlist_line_no = sl.line_no
		--AND rl.LINE_NO = sl.inv_line
		--and rl.INVOICE_ID = sl.invoice_id
	left outer join dbo.receivable r
		on rl.invoice_id = r.invoice_id
	join #fact2 f22
	   on f22.CUST_ORDER_ID = col.CUST_ORDER_ID
	   AND F22.packlist_id = s.PACKLIST_ID
	   AND F22.inv_line = rl.line_no
	   AND F22.INVOICE_ID = rl.INVOICE_ID
	where (1=1)
	   -- AND col.part_id is null
		and col.service_charge_id is not null
		and co.create_date >= '1/1/2015'
		and co.[status] != 'x'
		--and col.order_qty > 0
		AND S.SHIPPED_DATE >= @START

		and exists (
			select 1 
			from #fact2 f2
			where (1=1)
			and col.cust_order_id 		=   f2.cust_order_id 	
			and s.PACKLIST_ID = f2.packlist_id
			and rl.line_no = f2.inv_line

			and rl.invoice_id 		=   f2.invoice_id 	
		)	


	) level_1  -- f23
	order by cust_order_id  --, packlist_id
	

-- drop	table #fact3
test_fact_2_3:
-- select * from #fact3
  -- select * from #fact3 order by cust_order_id, packlist_id
     -- select * from #fact2
	      -- select * from #alloc_4

/**********************************************************************************************
 fact table.2.3. ENDS //////////////////////////////////////////////////////////		

**********************************************************************************************/ 
/**********************************************************************************************
Description:   Detail 1 - Fact.2.4.1 Detail to comport with gm fields	
Sample:			

Date        Modified By         Change Description
----------  ------------------  ------------------------------------------------------------
12/13/2019	William Thompson	Dataset is Merged from #detail1 to results
12/13/2019	William Thompson	lands aggregated amounts on col.line_no 1


**********************************************************************************************/
----- 444444444 ------------------------------------------------------------4444444444
-- declare @start date = '2017-12-01'

detail_for_testing1Fact2:

select
	'fact2_Det1' as dw_report_group
	,'chgs' as [order_type]  -- 'chgoffset' 
	,invoiceisnegative = iif (rl.amount < 0 , 1, 0 )
	, null as trace_id
	, rl.invoice_id
	, rl.line_no as inv_line
	, null as  trace_qty
	, rl.packlist_id
	, s.shipped_date
	, co.create_date as co_create_date
	, col.cust_order_id
	, col.line_no as col_line  -- data relational integrity may hold up in test - line 1
	, co.customer_id
	, col.PART_ID
	, col.line_status as ship_short
	, col.order_qty as col_order_qty
	, col.total_shipped_qty
	, rl.qty as rec_qty
	, col.unit_price as col_unit_price
    , rl.amount as rec_amount
	, rl.amount as trace_charge_alloc
	, null as wo_status
	, null as wo_create_date
	, null as base_id
	, null as lot_id
	, null as split_id
	, null as sub_id
	, null as desired_qty
	, null as act_burden_cost
	, null as act_material_cost
	, null as act_labor_cost
	, null as act_service_cost
	into #detail1
from dbo.shipper_line sl
inner join dbo.shipper s
	on sl.packlist_id = s.packlist_id
join dbo.cust_order_line col
	on sl.cust_order_id = col.cust_order_id
inner join dbo.customer_order co
	on col.cust_order_id = co.id
join dbo.receivable_line rl    -- left outer join
	on rl.cust_order_id = col.cust_order_id
	and rl.cust_order_line_no = col.line_no
	and rl.packlist_id = sl.packlist_id
	and rl.PACKLIST_LINE_NO = sl.LINE_NO
join dbo.receivable r      -- left outer join
	on rl.invoice_id = r.invoice_id
join #alloc_4  a4
   on a4.CUST_ORDER_ID = col.CUST_ORDER_ID
   and a4.col_line = col.LINE_NO
   --AND a4.packlist_id = s.PACKLIST_ID
   AND a4.inv_line = rl.line_no
   AND a4.INVOICE_ID = rl.INVOICE_ID
where (1=1)
	and co.create_date >= '1/1/2015'
	AND S.SHIPPED_DATE >= @START
order by col.cust_order_id, col.line_no, rl.invoice_id, sl.packlist_id

-- select * from #fact3
------ drop table #detail1
test_detail1:
--select * from #detail1
--select * from #alloc_4
/***************************************************************************

 Detail 1 - Fact.2.4.1 ENDS ////////////////////////////////////////////////////

**************************************************************************/

/**********************************************************************************************
Description:	Merge Fact2.5.91 1 of 2 - Inserts
Sample:			merge-1 the inserts pass insert from select * from #alloc_4 to #results

Date        Modified By         Change Description
----------  ------------------  ------------------------------------------------------------
12/13/2019	William Thompson	Created.
12/13/2019  William Thompson	Fact table 2 detail 1
12/17/2019	William Thompson	Do the inserts first in Merge 2.5.91
								** then do updates pass in 2.6.0

TESTER:

truncate table DataWarehouse.williamt.gm_test2
-- fROM
SELECT * FROM  #alloc_4  Src (NOLOCK)

-- tO
SELECT * FROM #results Trgt

merge-1 the inserts pass insert from select * from #alloc_4 to #results

select * from DataWarehouse.williamt.gm_test2

**********************************************************************************************/

DECLARE @TransactionStartDate DATETIME2(7) = SYSDATETIME()
	, @TransactionEndDate DATETIME2(7)
	, @StoredProcedureStartDate DATETIME2(7) = SYSDATETIME()
	, @DurationSeconds INT
	, @Rows INT = 0
	, @RowsPerSecond INT
	, @Error INT
	, @InsertedRows INT = 0
	, @UpdatedRows INT = 0
	, @DeletedRows INT = 0
	, @StoredProcedureName SYSNAME = 
		(SELECT @@SERVERNAME + '.' + DB_NAME() + '.' + s.name + '.' + o.name 
		FROM sys.objects o (NOLOCK) 
		JOIN sys.schemas s (NOLOCK) 
			ON o.schema_id = s.schema_id 
		WHERE o.object_id = @@PROCID)
	, @TargetServer SYSNAME = @@SERVERNAME
	, @TargetDatabase SYSNAME = 'DataWarehouse'
	, @TargetSchema SYSNAME = 'williamt'
	, @TargetTable SYSNAME = 'gm_test'
	, @StepId INT = 1
	, @Step VARCHAR(4000)

DECLARE @MergeResult TABLE (ActionTaken VARCHAR(20) NOT NULL);
	
declare @MyInserted1 table (
cust_order_id nvarchar(15) null
, packlist_id nvarchar(15) null
, invoice_id  nvarchar(15) null
, customer_id nvarchar(15) null
, col_line smallint null
, inv_line smallint null
, rec_amount decimal(15,2)
, ActionTaken VARCHAR(20) NOT NULL)

MERGE #results Trgt

USING #detail1 AS Src (nolock)
	   on trgt.cust_order_id = src.cust_order_id
	   and trgt.invoice_id = src.invoice_id
	   and trgt.customer_id = src.Customer_id

WHEN NOT MATCHED BY TARGET
	THEN INSERT ( 
	  order_type
	, trace_id
	, invoice_id
	, inv_line
	, packlist_id
	, shipped_date
	, co_create_date
	, cust_order_id
	, col_line
	, customer_id
	, part_id
	, ship_short
	, col_order_qty
	, total_shipped_qty
	, rec_qty
	, col_unit_price
	, rec_amount
	, wo_status
	, wo_create_date
	, base_id
	, lot_id
	, split_id
	, sub_id
	, desired_qty
	, trace_charge_alloc
) VALUES ( 
	  order_type
	, trace_id
	, invoice_id
	, inv_line
	, packlist_id
	, shipped_date
	, co_create_date
	, cust_order_id
	, col_line
	, customer_id
	, part_id
	, ship_short
	, col_order_qty
	, total_shipped_qty
	, rec_qty
	, col_unit_price
	, rec_amount
	, wo_status
	, wo_create_date
	, base_id
	, lot_id
	, split_id
	, sub_id
	, desired_qty
	, trace_charge_alloc
)
	
OUTPUT 
    CASE WHEN $action = 'INSERT' THEN inserted.cust_order_id
		ELSE deleted.cust_order_id
	 END,
	 CASE WHEN $action = 'INSERT' THEN inserted.packlist_id
	     ELSE deleted.packlist_id
	 END, 
	 CASE WHEN $Action = 'INSERT' THEN inserted.invoice_ID
		 ELSE deleted.invoice_ID
	 END,
	 CASE WHEN $Action = 'INSERT' THEN inserted.customer_id
	    ELSE deleted.customer_id
	 END,

	 CASE WHEN $action = 'INSERT' THEN inserted.col_line
	     ELSE deleted.col_line
	 END, 

	 CASE WHEN $action = 'INSERT' THEN inserted.inv_line
	     ELSE deleted.inv_line
	 END, 

	 CASE WHEN $action = 'INSERT' THEN inserted.rec_amount
	     ELSE inserted.rec_amount
	 END, 

	 $Action
	INTO @MyInserted1;


-- drop table #inserted1
test_inserted_from_merge:
-- select * from #inserted1

	select distinct * 
	into #inserted1
	from @MyInserted1

--/***************************************************************************
-- MERGE - Fact.2.5.9 ENDS ////////////////////////////////////////////////////
--**************************************************************************/

/**********************************************************************************************
Description:	Merge Fact2.6.0 Gross Margin Charge Allocations
Sample:			EXEC managedData.usp_Load_gm_charge_alloc

Date        Modified By         Change Description
----------  ------------------  ------------------------------------------------------------
12/13/2019	William Thompson	Created.
12/13/2019  William Thompson	Fact table 2 detail 1

TESTER:

truncate table DataWarehouse.williamt.gm_test2
-- fROM
SELECT * FROM  DataWarehouse.williamT.gm_fact2_det1  Src (NOLOCK)

-- tO
SELECT * FROM DataWarehouse.williamt.gm_test2 Trgt

**********************************************************************************************/
	
declare @MyInserted table 
(cust_order_id nvarchar(15) null
, packlist_id nvarchar(15) null
, invoice_id  nvarchar(15) null
, customer_id nvarchar(15) null
, col_line smallint null
, inv_line smallint null
, rec_amount decimal(15,2)
, ActionTaken VARCHAR(20) NOT NULL
);

IF OBJECT_ID('tempdb..#agg') IS NOT NULL DROP TABLE #agg
IF OBJECT_ID('tempdb..#a4') IS NOT NULL DROP TABLE #a4
IF OBJECT_ID('tempdb..#Allocation') IS NOT NULL DROP TABLE #Allocation

select agg.dw_report_group
	,agg.cust_order_id
	,agg.col_line
	,agg.Line1_COL_LINE
	,agg.packlist_id
	,agg.invoice_id
	,agg.max_invoice_id
	,agg.min_invoice_id
	,agg.part_id
	,agg.Line1_Part_ID
	,agg.inv_line
	,agg.rec_amount
	,agg.ct
	,agg.IsAllocated
	,agg.dw_level
	,agg.ORDER_QTY
	,agg.SERVICE_CHARGE_ID
	,agg.SumOfParts
	,agg.IsServiceCharge
into #agg
FROM #alloc_4 agg
WHERE Agg.IsServiceCharge = 1

select a4.dw_report_group
	,a4.cust_order_id
	,a4.col_line
	,a4.Line1_COL_LINE
	,a4.packlist_id
	,a4.invoice_id
	,a4.max_invoice_id
	,a4.min_invoice_id
	,a4.part_id
	,a4.Line1_Part_ID
	,a4.inv_line
	,a4.rec_amount
	,a4.ct
	,a4.IsServiceCharge
	,a4.dw_level
	,a4.ORDER_QTY
	,a4.SERVICE_CHARGE_ID
	,a4.SumOfParts
	,a4.unit_charge_alloc 
	,a4.IsAllocated
	into #a4
from #alloc_4 a4
where isAllocated = 1
order by CUST_ORDER_ID, INVOICE_ID, col_line

select a4.dw_report_group
	,a4.cust_order_id
	,a4.col_line
	,a4.Line1_COL_LINE
	,a4.packlist_id
	,a4.invoice_id
	,a4.max_invoice_id
	,a4.min_invoice_id
	,a4.part_id
	,a4.Line1_Part_ID
	,a4.inv_line
	,a4.rec_amount
	,a4.ct
	,a4.dw_level
	,a4.ORDER_QTY
	,a4.SERVICE_CHARGE_ID
	,a4.SumOfParts
	,a4.unit_charge_alloc 
	,a4.IsAllocated
	, #agg.IsServiceCharge
	, #agg.rec_amount * a4.unit_charge_alloc  TRACE_CHARGE_ALLOC
into #Allocation
from #a4 a4
join #agg
	on a4.CUST_ORDER_ID = #agg.CUST_ORDER_ID
	and a4.INVOICE_ID = #agg.INVOICE_ID
	and a4.IsAllocated = #agg.IsServiceCharge

test_the_allocation1:
-- select * from #a4
-- select * from #agg
-- select * from #Allocation

Update_the_allocations_accum:
update al
set rec_amount = isnull(rec_amount,0) + isnull(al.trace_charge_alloc,0)
from #Allocation al

-- land the receivable
MERGE #results Trgt
USING #Allocation AS Src (nolock)
on trgt.cust_order_id = src.cust_order_id
and trgt.col_line = src.col_line
and trgt.invoice_id = src.invoice_id

WHEN MATCHED AND
 -- The charges land for offsets
 abs(ISNULL(src.trace_charge_alloc, 0)) > 0
 OR ISNULL(trgt.rec_amount, -30) <> ISNULL(src.rec_amount, -30)
 OR ISNULL(trgt.trace_charge_alloc, -30) <> ISNULL(src.trace_charge_alloc, -30)
THEN UPDATE 
SET trgt.rec_amount = isnull(src.rec_amount,0) 
,trgt.trace_charge_alloc = isnull(src.trace_charge_alloc,0)
,trgt.unit_charge_alloc = isnull(src.unit_charge_alloc,0.)

OUTPUT 
     CASE WHEN $action = 'INSERT' THEN inserted.cust_order_id
		ELSE deleted.cust_order_id
	 END,
	 CASE WHEN $action = 'INSERT' THEN inserted.packlist_id
	     ELSE deleted.packlist_id
	 END, 
	 CASE WHEN $Action = 'INSERT' THEN inserted.invoice_ID
		 ELSE deleted.invoice_ID
	 END,
	 CASE WHEN $Action = 'INSERT' THEN inserted.customer_id
	    ELSE deleted.customer_id
	 END,

	 CASE WHEN $action = 'INSERT' THEN inserted.col_line
	     ELSE deleted.col_line
	 END, 

	 CASE WHEN $action = 'INSERT' THEN inserted.inv_line
	     ELSE deleted.inv_line
	 END, 

 	 CASE WHEN $action = 'INSERT' THEN inserted.rec_amount
	     ELSE inserted.rec_amount
	 END, 

	 $Action
	INTO @MyInserted;


 -- drop table #inserted
 test_inserted_from_merge1:
 -- select * from #inserted
 -- select * from #results

	select distinct * 
	into #inserted
	from @MyInserted

-- select * from #inserted

--/***************************************************************************
-- MERGE - Fact.2.6.0 ENDS ////////////////////////////////////////////////////
--**************************************************************************/	
-- UPDATE VERSION 2.3  --------------------------------------------------------
-- accumulate the negative amounts into the data by updating invoice.
 
update t
set	rec_issues = 'chgs'
from #Results t
join (select sum(d4.rec_amount) rec_amount 
			,d4.invoice_id
			,d4.cust_order_id
			,d4.customer_id 
			,d4.col_line
			,d4.inv_line
	from #detail1 d4
	group by d4.invoice_id
			,d4.cust_order_id
			--,d4.packlist_id
			,d4.invoice_id 
			,d4.customer_id 
			,d4.col_line
			,d4.inv_line
	) as x
	on t.cust_order_id = x.cust_order_id
	and t.invoice_id = x.INVOICE_ID
	and t.customer_id = x.customer_id
	and t.col_line = x.col_line
	and t.inv_line = x.inv_line
where t.REC_ISSUES is null


update cmb
set BUS_STREAM = UDF.STRING_VAL
, BUS_UNIT = CASE
		WHEN CMB.CUSTOMER_ID = 'BOE609' AND P.PLANNER_USER_ID = 'FIN-HOURLY' THEN 'CMP-FIN'
		WHEN CMB.CUSTOMER_ID = 'BOE609' AND P.PLANNER_USER_ID = 'FIN' THEN 'CMP-FIN'
		WHEN CMB.CUSTOMER_ID = 'BOE609' AND P.PLANNER_USER_ID = 'MFG-HOURLY' THEN 'CMP-MFG'
		WHEN CMB.CUSTOMER_ID = 'BOE609' AND P.PLANNER_USER_ID = 'MFG' THEN 'CMP-MFG'
		ELSE UDF.STRING_VAL
END 
, PLANNER_USER_ID = P.PLANNER_USER_ID
, BUYER_USER_ID = P.BUYER_USER_ID
, Salesperson_ID = B.Salesperson_ID
FROM #Results CMB 
LEFT OUTER JOIN #BUS_UNIT UDF
	ON UDF.DOCUMENT_ID = CMB.CUSTOMER_ID
	AND UDF.PROGRAM_ID = 'VMCUSMNT'
	AND UDF.ID = 'UDF-0000072'
LEFT OUTER JOIN dbo.PART_SITE P
	ON P.PART_ID = CMB.PART_ID
LEFT OUTER JOIN LIVESupplemental.dbo.buyer_assn B
	ON LEFT(P.BUYER_USER_ID, 2) = B.Account_ID	
where exists (
    select
     1
    from #inserted1 i2
	where
     CMB.cust_order_id = i2.cust_order_id
    and CMB.packlist_id = i2.packlist_id
    and CMB.invoice_id = i2.invoice_id 
	and CMB.customer_id = i2.customer_id)

profile_and_test1:
---- select customer_id, TRACE_CHARGE_ALLOC, * from #results where rec_issues =  'ChgRfd'
---- select * from #Bus_unit
---- select * from #temp92
---- select * from #results where bus_stream is null

--update_the_total_invoiced1:

update t
set TOTAL_INVOICE_AMOUNT = ISNULL(TOTAL_INVOICE_AMOUNT,0) + ISNULL(TRACE_CHARGE_ALLOC,0)
from #Results t

update t
set TRACE_INVOICE_AMOUNT = ISNULL(TRACE_INVOICE_AMOUNT,0) + ISNULL(TRACE_CHARGE_ALLOC,0)
from #Results t
 
profile_data_chg_ref1:
-- select * from #detail1
-- select * from #detail2
-- select * from #inserted
-- select * from #inserted1
-- select * from #results

profile_diffs1:

archive_old1:
----SELECT * 
----  into Datawarehouse.dbo.GROSS_MARGIN_20191211
----FROM Datawarehouse.dbo.GROSS_MARGIN
render1:

---- in production, uncomment the following *******

uncomment_below_for_production0:

INSERT INTO Datawarehouse.[dbo].[GROSS_MARGIN]
           (
	[REC_ISSUES] ,[ORDER_TYPE] ,[BUS_STREAM] ,[BUS_UNIT]
	,[PLANNER_USER_ID] ,[BUYER_USER_ID] ,[Salesperson_ID] ,[CO_CREATE_DATE]
	,[WO_CREATE_DATE] ,[SHIPPED_DATE] ,[CUSTOMER_ID] ,[CUST_ORDER_ID]
	,[COL_LINE] ,[BASE_ID] ,[LOT_ID] ,[SPLIT_ID]
	,[SUB_ID] ,[WO_STATUS] ,[PACKLIST_ID] ,[TRANSACTION_ID]
	,[INVOICE_ID] ,[INV_LINE] ,[PART_ID] ,[SHIP_SHORT] ,[TRACE_ID] 
	,[TOTAL_SHIPPED_QTY] ,[COL_ORDER_QTY] ,[DESIRED_QTY] ,[TRACE_QTY] 
	,[SHIPPED_QTY] ,[REC_QTY] ,[COL_UNIT_PRICE] 
	,[REC_AMOUNT] ,[TRACE_CHARGE_ALLOC] ,[TOTAL_INVOICE_AMOUNT] 
	,[TRACE_INVOICE_AMOUNT] ,[UNIT_INVOICE_AMOUNT] ,[TOTAL_BURDEN_COST],[TOTAL_MATERIAL_COST] 
	,[TOTAL_LABOR_COST],[TOTAL_SERVICE_COST] ,[TRACE_BURDEN_COST] ,[TRACE_MATERIAL_COST] ,[TRACE_LABOR_COST]
	,[TRACE_SERVICE_COST] ,[UNIT_BURDEN_COST] ,[UNIT_MATERIAL_COST] ,[UNIT_LABOR_COST] ,[UNIT_SERVICE_COST]
	,[TOTAL_CHARGE],[PART_QTY] ,[UNIT_CHARGE_ALLOC] ,[PART NUMBER] ,[SUM_EXTENDED_DOLLARS]
	,[TOTAL_HOURS] ,[AMT_BASE_ID] ,[AMT_REC_AMOUNT] ,[AMT_BURDEN_COST] ,[AMT_MATERIAL_COST]
	,[AMT_LABOR_COST] ,[AMT_SERVICE_COST] ,[TRACE_PRICE] ,[INV_UNIT_PRICE] ,[UNITPRICE_DELTA]
	,[TOTAL_TRACE_COST] ,[TRACE_UNIT_COST] ,[TOTAL_UNIT_COST]		   
   )  -- end parens
	   
   
   SELECT
	[REC_ISSUES] ,[ORDER_TYPE] ,[BUS_STREAM] ,[BUS_UNIT]
	,[PLANNER_USER_ID] ,[BUYER_USER_ID] ,[Salesperson_ID] ,[CO_CREATE_DATE] ,[WO_CREATE_DATE]
	,[SHIPPED_DATE] ,[CUSTOMER_ID] ,[CUST_ORDER_ID] ,[COL_LINE] ,[BASE_ID]
	,[LOT_ID] ,[SPLIT_ID] ,[SUB_ID] ,[WO_STATUS] ,[PACKLIST_ID]
	,[TRANSACTION_ID] ,[INVOICE_ID] ,[INV_LINE] ,[PART_ID] ,[SHIP_SHORT]
	,[TRACE_ID] ,[TOTAL_SHIPPED_QTY] ,[COL_ORDER_QTY] ,[DESIRED_QTY] ,[TRACE_QTY]
	,[SHIPPED_QTY] ,[REC_QTY] ,[COL_UNIT_PRICE] ,[REC_AMOUNT] ,[TRACE_CHARGE_ALLOC]
	,[TOTAL_INVOICE_AMOUNT] ,[TRACE_INVOICE_AMOUNT] ,[UNIT_INVOICE_AMOUNT] ,[TOTAL_BURDEN_COST] ,[TOTAL_MATERIAL_COST]
	,[TOTAL_LABOR_COST] ,[TOTAL_SERVICE_COST] ,[TRACE_BURDEN_COST] ,[TRACE_MATERIAL_COST] ,[TRACE_LABOR_COST]
	,[TRACE_SERVICE_COST] ,[UNIT_BURDEN_COST] ,[UNIT_MATERIAL_COST] ,[UNIT_LABOR_COST] ,[UNIT_SERVICE_COST]
	,[TOTAL_CHARGE] ,[PART_QTY] ,[UNIT_CHARGE_ALLOC] ,[PART NUMBER] ,[SUM_EXTENDED_DOLLARS]
	,[TOTAL_HOURS] ,[AMT_BASE_ID] ,[AMT_REC_AMOUNT] ,[AMT_BURDEN_COST] ,[AMT_MATERIAL_COST]
	,[AMT_LABOR_COST] ,[AMT_SERVICE_COST] ,[TRACE_PRICE] ,[INV_UNIT_PRICE] 
	, UNITPRICE_DELTA = round([UNITPRICE_DELTA],4)
	,[TOTAL_TRACE_COST] ,[TRACE_UNIT_COST] ,[TOTAL_UNIT_COST]

  FROM #RESULTS
  order by [CUST_ORDER_ID],INVOICE_ID,COL_LINE

GO


