USE DATAWAREHOUSE
GO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DEADLOCK_PRIORITY LOW

DECLARE @STARTDATE DATE = DATEADD(YEAR,-1,DATEADD(DAY,1,(EOMONTH(DATEADD(MONTH,-1,GETDATE())))))
;

WITH CTE_CHARGES AS
(SELECT COL.CUST_ORDER_ID
--	, COL.MISC_REFERENCE
--	, COL.SERVICE_CHARGE_ID   --> TAKEN OUT DUE TO MULTIPLE CHARGES
--	, SUM(COL.TOTAL_AMT_ORDERED) AS TOTAL_AMT_ORDERED
	, SUM(COL.UNIT_PRICE * COL.ORDER_QTY) AS TOTAL_AMT_ORDERED
FROM CUST_ORDER_LINE COL
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
WHERE COL.PART_ID IS NULL
--	AND COL.MISC_REFERENCE IS NOT NULL
	AND COL.SERVICE_CHARGE_ID IS NOT NULL
	AND CO.CREATE_DATE >= '1/1/2015'
	AND CO.[STATUS] != 'X'
	AND COL.ORDER_QTY > 0
GROUP BY COL.CUST_ORDER_ID
)
--SELECT * FROM CTE_CHARGES

--> remove reworks!!
, CTE_LINES AS
(SELECT COL.CUST_ORDER_ID
	, MAX(COL.LINE_NO) AS LINE_COUNT
	--, COL.LINE_NO
	--, COL.PART_ID
	--, COL.SERVICE_CHARGE_ID
	--, COL.MISC_REFERENCE
	--, DSL.SUPPLY_BASE_ID
FROM CUST_ORDER_LINE COL
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN CTE_CHARGES CTE
	ON COL.CUST_ORDER_ID = CTE.CUST_ORDER_ID
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE COL.PART_ID IS NOT NULL
	AND (DSL.SUPPLY_BASE_ID NOT LIKE '%R%' 
		OR DSL.SUPPLY_BASE_ID IS NULL)
GROUP BY COL.CUST_ORDER_ID
)
--SELECT * FROM CTE_LINES

, CTE_CHGAMTS AS
(SELECT CTE1.CUST_ORDER_ID
--	, CTE1.MISC_REFERENCE
--	, CTE1.SERVICE_CHARGE_ID   --> TAKEN OUT DUE TO MULTIPLE CHARGES
	, CTE1.TOTAL_AMT_ORDERED
	, CTE2.LINE_COUNT
	, CTE1.TOTAL_AMT_ORDERED / CTE2.LINE_COUNT AS CHARGE_ALLOC
FROM CTE_CHARGES CTE1
INNER JOIN CTE_LINES CTE2
	ON CTE1.CUST_ORDER_ID = CTE2.CUST_ORDER_ID
)
--SELECT * FROM CTE_CHGAMTS 

, CTE_LINKED as 
(SELECT 'LINKED' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
--	, COL.MISC_REFERENCE                             --> TAKEN OUT DUE TO MULTIPLE CHARGES
--	, CTE01.MISC_REFERENCE AS CHG_MISC_REFERENCE     --> TAKEN OUT DUE TO MULTIPLE CHARGES
	, ISNULL(CTE01.CHARGE_ALLOC, 0) AS CHARGE_ALLOC
	, COL.TOTAL_AMT_ORDERED
	, COL.TOTAL_AMT_SHIPPED
	, SL.SHIPPED_QTY
	, ISNULL(CTE01.CHARGE_ALLOC, 0) + (SL.SHIPPED_QTY * COL.UNIT_PRICE) AS TOTAL_PRICE
	, WO.ACT_BURDEN_COST AS TOTAL_BURDEN_COST
	, WO.ACT_MATERIAL_COST AS TOTAL_MATERIAL_COST
	, WO.ACT_LABOR_COST AS TOTAL_LABOR_COST
	, WO.ACT_SERVICE_COST AS TOTAL_SERVICE_COST
	, (WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) AS TOTAL_COST
	, WO.[STATUS]
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	--, O.SEQUENCE_NO
	--, O.RESOURCE_ID
	, WO.DESIRED_QTY
	, CASE
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_BURDEN_COST
		ELSE ((T.QTY * -1) * (WO.ACT_BURDEN_COST / WO.DESIRED_QTY)) 
	END AS TRACE_BURDEN_COST
	, CASE
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_MATERIAL_COST
		ELSE ((T.QTY * -1) * (WO.ACT_MATERIAL_COST / WO.DESIRED_QTY)) 
	END AS TRACE_MATERIAL_COST
	, CASE
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_LABOR_COST
		ELSE ((T.QTY * -1) * (WO.ACT_LABOR_COST / WO.DESIRED_QTY)) 
	END AS TRACE_LABOR_COST
	, CASE
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_SERVICE_COST
		ELSE ((T.QTY * -1) * (WO.ACT_SERVICE_COST / WO.DESIRED_QTY)) 
	END AS TRACE_SERVICE_COST
	, CASE
		WHEN T.TRACE_ID IS NULL THEN (WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST)
		ELSE ((T.QTY * -1) * ((WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) / WO.DESIRED_QTY))
	END AS TOTAL_TRACE_COST
	, ((WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) / WO.DESIRED_QTY) AS TRACE_UNIT_COST
	--, O.ACT_ATL_LAB_COST
	--, O.ACT_ATL_BUR_COST
	--, O.ACT_ATL_SER_COST
	--, O.ACT_TTL_MAT_COST
	--, O.ACT_TTL_LAB_COST
	--, O.ACT_TTL_BUR_COST
	--, O.ACT_TTL_SER_COST
	--, O.ACT_ATL_LAB_COST + O.ACT_ATL_BUR_COST + O.ACT_ATL_SER_COST + O.ACT_TTL_MAT_COST + O.ACT_TTL_LAB_COST 
	--	+ O.ACT_TTL_BUR_COST + O.ACT_TTL_SER_COST AS OPS_TOTAL_COST
	--, (O.ACT_ATL_LAB_COST + O.ACT_ATL_BUR_COST + O.ACT_ATL_SER_COST + O.ACT_TTL_MAT_COST + O.ACT_TTL_LAB_COST 
	--	+ O.ACT_TTL_BUR_COST + O.ACT_TTL_SER_COST) / WO.DESIRED_QTY AS OPS_UNIT_COST
	--, O.ACT_SETUP_HRS
	--, O.ACT_RUN_HRS
	--, O.ACT_SETUP_HRS + O.ACT_RUN_HRS AS TOTAL_HOURS
FROM SHIPPER_LINE SL
INNER JOIN SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
INNER JOIN WORK_ORDER WO
    ON DSL.SUPPLY_TYPE = 'WO' 
    AND DSL.SUPPLY_BASE_ID = WO.BASE_ID
    AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
    AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
    AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
	AND WO.[TYPE] = 'W'
--INNER JOIN OPERATION O
--	ON WO.BASE_ID = O.WORKORDER_BASE_ID
--	AND WO.LOT_ID = O.WORKORDER_LOT_ID
--	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
--	AND WO.SUB_ID = O.WORKORDER_SUB_ID
--	AND WO.[TYPE] = O.WORKORDER_TYPE
INNER JOIN RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND RL.PACKLIST_ID = SL.PACKLIST_ID
	AND RL.PACKLIST_LINE_NO = SL.LINE_NO
INNER JOIN RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
LEFT OUTER JOIN TRACE_INV_TRANS T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
LEFT OUTER JOIN CTE_CHGAMTS CTE01
	ON COL.CUST_ORDER_ID = CTE01.CUST_ORDER_ID
WHERE RL.PACKLIST_ID IS NOT NULL
	AND S.SHIPPED_DATE >= @STARTDATE
	AND COL.PART_ID IS NOT NULL
	AND SL.SHIPPED_QTY <> 0
)

--> TOTAL TRACE COSTS FOR UNLINKED ORDERS
, CTE_TRACE_COSTS as
(SELECT CUST_ORDER_ID
	, LINE_NO
	, SUM(TRACE_BURDEN_COST) AS TOTAL_BURDEN_COST
	, SUM(TRACE_MATERIAL_COST) AS TOTAL_MATERIAL_COST
	, SUM(TRACE_LABOR_COST) AS TOTAL_LABOR_COST
	, SUM(TRACE_SERVICE_COST) AS TOTAL_SERVICE_COST
	, SUM(TOTAL_TRACE_COST) AS TOTAL_COST
FROM
	(SELECT COL.CUST_ORDER_ID
		, COL.LINE_NO
		, T.TRACE_ID
		, ((T.QTY * -1) * (WO.ACT_BURDEN_COST / WO.DESIRED_QTY)) AS TRACE_BURDEN_COST
		, ((T.QTY * -1) * (WO.ACT_MATERIAL_COST / WO.DESIRED_QTY)) AS TRACE_MATERIAL_COST
		, ((T.QTY * -1) * (WO.ACT_LABOR_COST / WO.DESIRED_QTY)) AS TRACE_LABOR_COST
		, ((T.QTY * -1) * (WO.ACT_SERVICE_COST / WO.DESIRED_QTY)) AS TRACE_SERVICE_COST
		, ((T.QTY * -1) * ((WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) / WO.DESIRED_QTY)) AS TOTAL_TRACE_COST
	FROM SHIPPER_LINE SL
	INNER JOIN TRACE_INV_TRANS  T
		ON SL.TRANSACTION_ID = T.TRANSACTION_ID
	INNER JOIN CUST_ORDER_LINE COL
		ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
		AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
		AND COL.PART_ID IS NOT NULL
	INNER JOIN RECEIVABLE_LINE RL
		ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
		AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
		AND RL.PACKLIST_ID = SL.PACKLIST_ID 
		AND RL.PACKLIST_LINE_NO = SL.LINE_NO
		AND RL.PACKLIST_ID IS NOT NULL
	INNER JOIN SHIPPER S
		ON S.PACKLIST_ID = SL.PACKLIST_ID 
	INNER JOIN RECEIVABLE R
		ON RL.INVOICE_ID = R.INVOICE_ID
	INNER JOIN CUSTOMER_ORDER CO
		ON COL.CUST_ORDER_ID = CO.ID
	LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
		ON DSL.DEMAND_TYPE = 'CO'
		AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
		AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
		AND DSL.SUPPLY_BASE_ID IS NULL
	LEFT OUTER JOIN WORK_ORDER WO
		ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID)
		AND WO.[TYPE] = 'W'
		AND WO.[STATUS] = 'C'
		AND WO.DESIRED_QTY <> 0
		AND WO.SPLIT_ID = '0'
		AND WO.SUB_ID = '0'
	WHERE S.SHIPPED_DATE >= @STARTDATE
		AND SL.SHIPPED_QTY <> 0
	----
	UNION ALL
	----
	SELECT COL.CUST_ORDER_ID
			, COL.LINE_NO
		, T.TRACE_ID
		, ((T.QTY * -1) * (WO.ACT_BURDEN_COST / WO.DESIRED_QTY)) AS TRACE_BURDEN_COST
		, ((T.QTY * -1) * (WO.ACT_MATERIAL_COST / WO.DESIRED_QTY)) AS TRACE_MATERIAL_COST
		, ((T.QTY * -1) * (WO.ACT_LABOR_COST / WO.DESIRED_QTY)) AS TRACE_LABOR_COST
		, ((T.QTY * -1) * (WO.ACT_SERVICE_COST / WO.DESIRED_QTY)) AS TRACE_SERVICE_COST
		, ((T.QTY * -1) * ((WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) / WO.DESIRED_QTY)) AS TOTAL_TRACE_COST
	FROM SHIPPER_LINE SL
	INNER JOIN TRACE_INV_TRANS  T
		ON SL.TRANSACTION_ID = T.TRANSACTION_ID
	INNER JOIN CUST_ORDER_LINE COL
		ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
		AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
		AND COL.PART_ID IS NOT NULL
	INNER JOIN RECEIVABLE_LINE RL
		ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
		AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
		AND RL.PACKLIST_ID = SL.PACKLIST_ID 
		AND RL.PACKLIST_LINE_NO = SL.LINE_NO
		AND RL.PACKLIST_ID IS NOT NULL
	INNER JOIN SHIPPER S
		ON S.PACKLIST_ID = SL.PACKLIST_ID 
	INNER JOIN RECEIVABLE R
		ON RL.INVOICE_ID = R.INVOICE_ID
	INNER JOIN CUSTOMER_ORDER CO
		ON COL.CUST_ORDER_ID = CO.ID
	LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
		ON DSL.DEMAND_TYPE = 'CO'
		AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
		AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
		AND DSL.SUPPLY_BASE_ID IS NULL
	LEFT OUTER JOIN WORK_ORDER WO
		ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID + '/' + WO.SUB_ID)
		AND WO.[TYPE] = 'W'
		AND WO.[STATUS] = 'C'
		AND WO.DESIRED_QTY <> 0
		AND WO.SPLIT_ID = '0'
	WHERE S.SHIPPED_DATE >= @STARTDATE
		AND SL.SHIPPED_QTY <> 0
	) A
GROUP BY CUST_ORDER_ID
	, LINE_NO
)
--select * from CTE_TRACE_COSTS

, CTE_UNLINKED as
(SELECT 'UNLINKED' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
--	, COL.MISC_REFERENCE                             --> TAKEN OUT DUE TO MULTIPLE CHARGES
--	, CTE01.MISC_REFERENCE AS CHG_MISC_REFERENCE     --> TAKEN OUT DUE TO MULTIPLE CHARGES
	, ISNULL(CTE01.CHARGE_ALLOC, 0) AS CHARGE_ALLOC
	, COL.TOTAL_AMT_ORDERED
	, COL.TOTAL_AMT_SHIPPED
	, SL.SHIPPED_QTY
	, ISNULL(CTE01.CHARGE_ALLOC, 0) + (SL.SHIPPED_QTY * COL.UNIT_PRICE) AS TOTAL_PRICE
	, ISNULL(CTE02.TOTAL_BURDEN_COST, WO.ACT_BURDEN_COST) AS TOTAL_BURDEN_COST
	, ISNULL(CTE02.TOTAL_LABOR_COST, WO.ACT_LABOR_COST) AS TOTAL_LABOR_COST
	, ISNULL(CTE02.TOTAL_MATERIAL_COST, WO.ACT_MATERIAL_COST) AS TOTAL_MATERIAL_COST
	, ISNULL(CTE02.TOTAL_SERVICE_COST, WO.ACT_SERVICE_COST) AS TOTAL_SERVICE_COST
	, CASE
		WHEN CTE02.TOTAL_BURDEN_COST IS NULL THEN (WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) 
		ELSE (CTE02.TOTAL_BURDEN_COST + CTE02.TOTAL_LABOR_COST + CTE02.TOTAL_MATERIAL_COST + CTE02.TOTAL_SERVICE_COST)
	END AS TOTAL_COST
	, WO.[STATUS]
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	--, O.SEQUENCE_NO
	--, O.RESOURCE_ID
	, WO.DESIRED_QTY
	, CASE
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_BURDEN_COST
		ELSE ((T.QTY * -1) * (WO.ACT_BURDEN_COST / WO.DESIRED_QTY)) 
	END AS TRACE_BURDEN_COST
	, CASE
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_MATERIAL_COST
		ELSE ((T.QTY * -1) * (WO.ACT_MATERIAL_COST / WO.DESIRED_QTY)) 
	END AS TRACE_MATERIAL_COST
	, CASE
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_LABOR_COST
		ELSE ((T.QTY * -1) * (WO.ACT_LABOR_COST / WO.DESIRED_QTY)) 
	END AS TRACE_LABOR_COST
	, CASE
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_SERVICE_COST
		ELSE ((T.QTY * -1) * (WO.ACT_SERVICE_COST / WO.DESIRED_QTY)) 
	END AS TRACE_SERVICE_COST
	, CASE
		WHEN T.TRACE_ID IS NULL THEN (WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST)
		ELSE ((T.QTY * -1) * ((WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) / WO.DESIRED_QTY))
	END AS TOTAL_TRACE_COST
	, ((WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) / WO.DESIRED_QTY) AS TRACE_UNIT_COST
	--, O.ACT_ATL_LAB_COST
	--, O.ACT_ATL_BUR_COST
	--, O.ACT_ATL_SER_COST
	--, O.ACT_TTL_MAT_COST
	--, O.ACT_TTL_LAB_COST
	--, O.ACT_TTL_BUR_COST
	--, O.ACT_TTL_SER_COST
	--, O.ACT_ATL_LAB_COST + O.ACT_ATL_BUR_COST + O.ACT_ATL_SER_COST + O.ACT_TTL_MAT_COST + O.ACT_TTL_LAB_COST 
	--	+ O.ACT_TTL_BUR_COST + O.ACT_TTL_SER_COST AS OPS_TOTAL_COST
	--, (O.ACT_ATL_LAB_COST + O.ACT_ATL_BUR_COST + O.ACT_ATL_SER_COST + O.ACT_TTL_MAT_COST + O.ACT_TTL_LAB_COST 
	--	+ O.ACT_TTL_BUR_COST + O.ACT_TTL_SER_COST) / WO.DESIRED_QTY AS OPS_UNIT_COST
	--, O.ACT_SETUP_HRS
	--, O.ACT_RUN_HRS
	--, O.ACT_SETUP_HRS + O.ACT_RUN_HRS AS TOTAL_HOURS
FROM SHIPPER_LINE SL
INNER JOIN TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND SL.PACKLIST_ID = RL.PACKLIST_ID 
	AND SL.LINE_NO = RL.PACKLIST_LINE_NO 
	AND RL.PACKLIST_ID IS NOT NULL
LEFT OUTER JOIN SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SPLIT_ID = '0'
	AND WO.SUB_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
	AND DSL.SUPPLY_BASE_ID IS NULL
LEFT OUTER JOIN CTE_CHGAMTS CTE01
	ON COL.CUST_ORDER_ID = CTE01.CUST_ORDER_ID
LEFT OUTER JOIN CTE_TRACE_COSTS CTE02
	ON CTE02.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND CTE02.LINE_NO = COL.LINE_NO
--LEFT OUTER JOIN OPERATION O
--	ON WO.BASE_ID = O.WORKORDER_BASE_ID
--	AND WO.LOT_ID = O.WORKORDER_LOT_ID
--	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
--	AND WO.SUB_ID = O.WORKORDER_SUB_ID
--	AND WO.[TYPE] = O.WORKORDER_TYPE
WHERE S.SHIPPED_DATE >= @STARTDATE
	AND SL.SHIPPED_QTY <> 0
----
UNION ALL
----
SELECT 'UNLINKED' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
--	, COL.MISC_REFERENCE                             --> TAKEN OUT DUE TO MULTIPLE CHARGES
--	, CTE01.MISC_REFERENCE AS CHG_MISC_REFERENCE     --> TAKEN OUT DUE TO MULTIPLE CHARGES
	, ISNULL(CTE01.CHARGE_ALLOC, 0) AS CHARGE_ALLOC
	, COL.TOTAL_AMT_ORDERED
	, COL.TOTAL_AMT_SHIPPED
	, SL.SHIPPED_QTY
	, ISNULL(CTE01.CHARGE_ALLOC, 0) + (SL.SHIPPED_QTY * COL.UNIT_PRICE) AS TOTAL_PRICE
	, ISNULL(CTE02.TOTAL_BURDEN_COST, WO.ACT_BURDEN_COST) AS TOTAL_BURDEN_COST
	, ISNULL(CTE02.TOTAL_LABOR_COST, WO.ACT_LABOR_COST) AS TOTAL_LABOR_COST
	, ISNULL(CTE02.TOTAL_MATERIAL_COST, WO.ACT_MATERIAL_COST) AS TOTAL_MATERIAL_COST
	, ISNULL(CTE02.TOTAL_SERVICE_COST, WO.ACT_SERVICE_COST) AS TOTAL_SERVICE_COST
	, CASE
		WHEN CTE02.TOTAL_BURDEN_COST IS NULL THEN (WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) 
		ELSE (CTE02.TOTAL_BURDEN_COST + CTE02.TOTAL_LABOR_COST + CTE02.TOTAL_MATERIAL_COST + CTE02.TOTAL_SERVICE_COST)
	END AS TOTAL_COST
	, WO.[STATUS]
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	--, O.SEQUENCE_NO
	--, O.RESOURCE_ID
	, WO.DESIRED_QTY
	, CASE
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_BURDEN_COST
		ELSE ((T.QTY * -1) * (WO.ACT_BURDEN_COST / WO.DESIRED_QTY)) 
	END AS TRACE_BURDEN_COST
	, CASE
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_MATERIAL_COST
		ELSE ((T.QTY * -1) * (WO.ACT_MATERIAL_COST / WO.DESIRED_QTY)) 
	END AS TRACE_MATERIAL_COST
	, CASE
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_LABOR_COST
		ELSE ((T.QTY * -1) * (WO.ACT_LABOR_COST / WO.DESIRED_QTY)) 
	END AS TRACE_LABOR_COST
	, CASE
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_SERVICE_COST
		ELSE ((T.QTY * -1) * (WO.ACT_SERVICE_COST / WO.DESIRED_QTY)) 
	END AS TRACE_SERVICE_COST
	, CASE
		WHEN T.TRACE_ID IS NULL THEN (WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST)
		ELSE ((T.QTY * -1) * ((WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) / WO.DESIRED_QTY))
	END AS TOTAL_TRACE_COST
	, ((WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) / WO.DESIRED_QTY) AS TRACE_UNIT_COST
	--, O.ACT_ATL_LAB_COST
	--, O.ACT_ATL_BUR_COST
	--, O.ACT_ATL_SER_COST
	--, O.ACT_TTL_MAT_COST
	--, O.ACT_TTL_LAB_COST
	--, O.ACT_TTL_BUR_COST
	--, O.ACT_TTL_SER_COST
	--, O.ACT_ATL_LAB_COST + O.ACT_ATL_BUR_COST + O.ACT_ATL_SER_COST + O.ACT_TTL_MAT_COST + O.ACT_TTL_LAB_COST 
	--	+ O.ACT_TTL_BUR_COST + O.ACT_TTL_SER_COST AS OPS_TOTAL_COST
	--, (O.ACT_ATL_LAB_COST + O.ACT_ATL_BUR_COST + O.ACT_ATL_SER_COST + O.ACT_TTL_MAT_COST + O.ACT_TTL_LAB_COST 
	--	+ O.ACT_TTL_BUR_COST + O.ACT_TTL_SER_COST) / WO.DESIRED_QTY AS OPS_UNIT_COST
	--, O.ACT_SETUP_HRS
	--, O.ACT_RUN_HRS
	--, O.ACT_SETUP_HRS + O.ACT_RUN_HRS AS TOTAL_HOURS
FROM SHIPPER_LINE SL
INNER JOIN TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND SL.PACKLIST_ID = RL.PACKLIST_ID 
	AND SL.LINE_NO = RL.PACKLIST_LINE_NO 
	AND RL.PACKLIST_ID IS NOT NULL
LEFT OUTER JOIN SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID + '/' + WO.SUB_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SPLIT_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
	AND DSL.SUPPLY_BASE_ID IS NULL
LEFT OUTER JOIN CTE_CHGAMTS CTE01
	ON COL.CUST_ORDER_ID = CTE01.CUST_ORDER_ID
LEFT OUTER JOIN CTE_TRACE_COSTS CTE02
	ON CTE02.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND CTE02.LINE_NO = COL.LINE_NO
--LEFT OUTER JOIN OPERATION O
--	ON WO.BASE_ID = O.WORKORDER_BASE_ID
--	AND WO.LOT_ID = O.WORKORDER_LOT_ID
--	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
--	AND WO.SUB_ID = O.WORKORDER_SUB_ID
--	AND WO.[TYPE] = O.WORKORDER_TYPE
WHERE S.SHIPPED_DATE >= @STARTDATE
	AND SL.SHIPPED_QTY <> 0
)
--select * from cte_unlinked

SELECT * FROM CTE_LINKED 
UNION ALL
SELECT * FROM CTE_UNLINKED 


