USE [DataWarehouse]
GO
/****** Object:  StoredProcedure [dbo].[usp_Gross_Margin]    Script Date: 9/3/2019 7:33:42 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[usp_Gross_Margin_Ops]  

AS

BEGIN

--IF OBJECT_ID('tempdb..#GROSS_MARGIN_OPS') IS NOT NULL DROP TABLE #GROSS_MARGIN_OPS

SET NOCOUNT ON;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DEADLOCK_PRIORITY LOW

DECLARE @STARTDATE DATE = DATEADD(YEAR,-1,DATEADD(DAY,1,(EOMONTH(DATEADD(MONTH,-1,GETDATE())))))
;

-----------------------------> BOE QUERIES
WITH CTE_LINKED as 
(SELECT 'LINKED' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, SL.SHIPPED_QTY
	, WO.[STATUS]
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
	, WO.ACT_BURDEN_COST
	, WO.ACT_MATERIAL_COST
	, WO.ACT_LABOR_COST
	, WO.ACT_SERVICE_COST
FROM SHIPPER_LINE SL
INNER JOIN SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
INNER JOIN WORK_ORDER WO
    ON DSL.SUPPLY_TYPE = 'WO' 
    AND DSL.SUPPLY_BASE_ID = WO.BASE_ID
    AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
    AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
    AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
	AND WO.[TYPE] = 'W'
INNER JOIN RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND RL.PACKLIST_ID = SL.PACKLIST_ID
	AND RL.PACKLIST_LINE_NO = SL.LINE_NO
INNER JOIN RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
LEFT OUTER JOIN TRACE_INV_TRANS T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
WHERE RL.PACKLIST_ID IS NOT NULL
	AND S.SHIPPED_DATE >= @STARTDATE
	AND COL.PART_ID IS NOT NULL
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NOT NULL
)
--SELECT * FROM CTE_LINKED WHERE CUST_ORDER_ID = '429280' --AND LINE_NO = '1'
--ORDER BY CUST_ORDER_ID, LINE_NO, INVOICE_ID

, CTE_UNLINKED as
(SELECT 'UNLINKED1' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, SL.SHIPPED_QTY
	, WO.[STATUS]
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
	, WO.ACT_BURDEN_COST
	, WO.ACT_MATERIAL_COST
	, WO.ACT_LABOR_COST
	, WO.ACT_SERVICE_COST
FROM SHIPPER_LINE SL
INNER JOIN TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND SL.PACKLIST_ID = RL.PACKLIST_ID 
	AND SL.LINE_NO = RL.PACKLIST_LINE_NO 
	AND RL.PACKLIST_ID IS NOT NULL
INNER JOIN SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SPLIT_ID = '0'
	AND WO.SUB_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE S.SHIPPED_DATE >= @STARTDATE
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NULL
----
UNION ALL
----
SELECT 'UNLINKED2' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
--	, (RL.AMOUNT / ISNULL(RL.QTY, SL.SHIPPED_QTY)) AS INV_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, SL.SHIPPED_QTY
	, WO.[STATUS]
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
	, WO.ACT_BURDEN_COST
	, WO.ACT_MATERIAL_COST
	, WO.ACT_LABOR_COST
	, WO.ACT_SERVICE_COST
FROM SHIPPER_LINE SL
INNER JOIN TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND SL.PACKLIST_ID = RL.PACKLIST_ID 
	AND SL.LINE_NO = RL.PACKLIST_LINE_NO 
	AND RL.PACKLIST_ID IS NOT NULL
INNER JOIN SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID + '/' + WO.SUB_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SPLIT_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE S.SHIPPED_DATE >= @STARTDATE
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NULL
)
--select * from cte_unlinked

, CTE_COMBINED AS
(SELECT * 
FROM CTE_LINKED
UNION ALL
SELECT * 
FROM CTE_UNLINKED 
)
--select * from CTE_COMBINED where cust_order_id = '443416'

SELECT WORKORDER_BASE_ID
	, WORKORDER_LOT_ID
	, WORKORDER_SPLIT_ID
	, WORKORDER_SUB_ID
	, SEQUENCE_NO
	, RESOURCE_ID
	, SETUP_HRS
	, O.CLOSE_DATE
	, OPERATION_TYPE
	, ACT_ATL_LAB_COST
	, ACT_ATL_BUR_COST
	, ACT_ATL_SER_COST
	, ACT_TTL_MAT_COST
	, ACT_TTL_LAB_COST
	, ACT_TTL_BUR_COST
	, ACT_TTL_SER_COST
	, SPLIT_ADJUSTMENT
	, O.STATUS_EFF_DATE
--INTO #GROSS_MARGIN_OPS
FROM WORK_ORDER WO
INNER JOIN OPERATION O
ON O.WORKORDER_TYPE = WO.[TYPE]
AND O.WORKORDER_BASE_ID = WO.BASE_ID
AND O.WORKORDER_LOT_ID = WO.LOT_ID
AND O.WORKORDER_SPLIT_ID = WO.SPLIT_ID
AND O.WORKORDER_SUB_ID = WO.SUB_ID
WHERE EXISTS (SELECT 1
	FROM CTE_COMBINED T
	WHERE T.BASE_ID = O.WORKORDER_BASE_ID
		AND T.LOT_ID = O.WORKORDER_LOT_ID
		AND T.SPLIT_ID = O.WORKORDER_SPLIT_ID
		AND T.SUB_ID = O.WORKORDER_SUB_ID
		AND O.WORKORDER_TYPE = 'W'
	)
ORDER BY WORKORDER_BASE_ID

END