USE DATAWAREHOUSE
GO

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DEADLOCK_PRIORITY LOW

DECLARE @STARTDATE DATE = DATEADD(YEAR,-1,DATEADD(DAY,1,(EOMONTH(DATEADD(MONTH,-1,GETDATE())))))
;

WITH CTE_CHARGES AS
(SELECT COL.CUST_ORDER_ID
	, SUM(COL.UNIT_PRICE * COL.ORDER_QTY) AS TOTAL_AMT_ORDERED
FROM CUST_ORDER_LINE COL
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
WHERE COL.PART_ID IS NULL
	AND COL.SERVICE_CHARGE_ID IS NOT NULL
	AND CO.CREATE_DATE >= '1/1/2015'
	AND CO.[STATUS] != 'X'
	AND COL.ORDER_QTY > 0
GROUP BY COL.CUST_ORDER_ID
)
--SELECT * FROM CTE_CHARGES

--> remove reworks!!
, CTE_LINES AS
(SELECT COL.CUST_ORDER_ID
	, COUNT(COL.LINE_NO) AS LINE_COUNT
FROM CUST_ORDER_LINE COL
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN CTE_CHARGES CTE
	ON COL.CUST_ORDER_ID = CTE.CUST_ORDER_ID
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE COL.PART_ID IS NOT NULL
	AND (DSL.SUPPLY_BASE_ID NOT LIKE '%R%' 
		OR DSL.SUPPLY_BASE_ID IS NULL)
GROUP BY COL.CUST_ORDER_ID
)
--SELECT * FROM CTE_LINES

, CTE_CHGAMTS AS
(SELECT CTE1.CUST_ORDER_ID
	, CTE1.TOTAL_AMT_ORDERED
	, CTE2.LINE_COUNT
	, CTE1.TOTAL_AMT_ORDERED / CTE2.LINE_COUNT AS CHARGE_ALLOC
FROM CTE_CHARGES CTE1
INNER JOIN CTE_LINES CTE2
	ON CTE1.CUST_ORDER_ID = CTE2.CUST_ORDER_ID
)
--SELECT * FROM CTE_CHGAMTS  where CUST_ORDER_ID = '436991'

, CTE_LINKED as 
(SELECT 'LINKED' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, (RL.AMOUNT / ISNULL(RL.QTY, SL.SHIPPED_QTY)) AS INV_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, CASE
		WHEN SL.SHIPPED_QTY < 0 OR RL.AMOUNT < 0 THEN 0
		WHEN WO.BASE_ID LIKE '%R%' THEN 0
		ELSE ISNULL(CTE01.CHARGE_ALLOC, 0) 
	END AS CHARGE_ALLOC
	, SL.SHIPPED_QTY
	, CASE	
		WHEN SL.SHIPPED_QTY < 0 OR RL.AMOUNT < 0 THEN RL.AMOUNT
		WHEN WO.BASE_ID LIKE '%R%' THEN 0
		WHEN T.QTY IS NULL THEN ISNULL(CTE01.CHARGE_ALLOC, 0) + (RL.AMOUNT) 
		ELSE ((ISNULL(CTE01.CHARGE_ALLOC, 0) + RL.AMOUNT) / ISNULL(RL.QTY, SL.SHIPPED_QTY)) * (T.QTY * -1)
	END AS TOTAL_PRICE
	, WO.[STATUS]
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_BURDEN_COST
		ELSE ((T.QTY * -1) * (WO.ACT_BURDEN_COST / WO.DESIRED_QTY)) 
	END AS TRACE_BURDEN_COST
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_MATERIAL_COST
		ELSE ((T.QTY * -1) * (WO.ACT_MATERIAL_COST / WO.DESIRED_QTY)) 
	END AS TRACE_MATERIAL_COST
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_LABOR_COST
		ELSE ((T.QTY * -1) * (WO.ACT_LABOR_COST / WO.DESIRED_QTY)) 
	END AS TRACE_LABOR_COST
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_SERVICE_COST
		ELSE ((T.QTY * -1) * (WO.ACT_SERVICE_COST / WO.DESIRED_QTY)) 
	END AS TRACE_SERVICE_COST
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		WHEN T.TRACE_ID IS NULL THEN (WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST)
		ELSE ((T.QTY * -1) * ((WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) / WO.DESIRED_QTY))
	END AS TOTAL_TRACE_COST
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		ELSE ((WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) / WO.DESIRED_QTY) 
	END AS TRACE_UNIT_COST
FROM SHIPPER_LINE SL
INNER JOIN SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
INNER JOIN WORK_ORDER WO
    ON DSL.SUPPLY_TYPE = 'WO' 
    AND DSL.SUPPLY_BASE_ID = WO.BASE_ID
    AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
    AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
    AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
	AND WO.[TYPE] = 'W'
INNER JOIN RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND RL.PACKLIST_ID = SL.PACKLIST_ID
	AND RL.PACKLIST_LINE_NO = SL.LINE_NO
INNER JOIN RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
LEFT OUTER JOIN TRACE_INV_TRANS T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
LEFT OUTER JOIN CTE_CHGAMTS CTE01
	ON COL.CUST_ORDER_ID = CTE01.CUST_ORDER_ID
WHERE RL.PACKLIST_ID IS NOT NULL
	AND S.SHIPPED_DATE >= @STARTDATE
	AND COL.PART_ID IS NOT NULL
	AND SL.SHIPPED_QTY <> 0
)
--SELECT * FROM CTE_LINKED WHERE CUST_ORDER_ID = '429280'

-----------------------------> BOE QUERIES
, BOE_01 AS 
(SELECT 'BOE_01' AS [ORDER_TYPE]
	, CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
	, SUM(LT.HOURS_WORKED) AS TOTAL_HOURS_WORKED
	, ((SUM(LT.HOURS_WORKED) * 75) / COL.ORDER_QTY) AS UNIT_PRICE
	, SUM(LT.HOURS_WORKED) * 75 AS TOTAL_PRICE
	, SUM(LT.HOURS_WORKED) * 75 AS REC_AMOUNT
	, SUM(LT.HOURS_WORKED) * 75 AS TOTAL_AMT_ORDERED	
	, SUM(LT.HOURS_WORKED) * 75 AS TOTAL_AMT_SHIPPED
FROM SHIPPER S
INNER JOIN SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID 
LEFT OUTER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO 
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
LEFT OUTER JOIN WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
INNER JOIN OPERATION O
	ON WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O.WORKORDER_SUB_ID
	AND WO.[TYPE] = O.WORKORDER_TYPE
LEFT OUTER JOIN LABOR_TICKET LT
	ON O.SEQUENCE_NO = LT.OPERATION_SEQ_NO
	AND O.WORKORDER_BASE_ID = LT.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = LT.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
WHERE SL.SHIPPED_QTY > 0
--	AND CO.CUSTOMER_ID = N'BOE602' OR CO.CUSTOMER_ID = N'BOE605')
	AND CO.CUSTOMER_ID IN (N'BOE602', N'BOE605', N'BOEEME')
	AND WO.BASE_ID NOT LIKE N'%R%'
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.ResourceID_ReportSettings EX
		WHERE O.RESOURCE_ID = EX.RESOURCE_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE605revF'
	)
	AND (S.INVOICED_DATE >= @STARTDATE)
GROUP BY CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
)

--BOE609 - Finish - G:\ACCTG\AR\2019\Crystal Reports\Finish 609v1 – (Hours + Setup Hrs) * 70
, BOE_02 AS
(SELECT 'BOE_02' AS [ORDER_TYPE]
	, CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
	, SUM(LT.HOURS_WORKED) AS TOTAL_HOURS_WORKED
	, ((SUM(LT.HOURS_WORKED) * 70) / COL.ORDER_QTY) AS UNIT_PRICE
	, SUM(LT.HOURS_WORKED) * 70 AS TOTAL_PRICE
	, SUM(LT.HOURS_WORKED) * 70 AS REC_AMOUNT
	, SUM(LT.HOURS_WORKED) * 70 AS TOTAL_AMT_ORDERED	
	, SUM(LT.HOURS_WORKED) * 70 AS TOTAL_AMT_SHIPPED
FROM SHIPPER S
INNER JOIN SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
INNER JOIN LABOR_TICKET LT
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
INNER JOIN SHOP_RESOURCE SR
	ON LT.RESOURCE_ID = SR.ID
WHERE SL.SHIPPED_QTY > 0
	AND SR.SKILLS_TYPE <> N'M'
	AND CO.CUSTOMER_ID = N'BOE609'
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.ResourceID_ReportSettings EX
		WHERE LT.RESOURCE_ID = EX.RESOURCE_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 - Finish 609v1'
	)
	AND (S.INVOICED_DATE >= @STARTDATE)
GROUP BY CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
)

, BOE_03 AS 
--BOE609 - MFG - G:\ACCTG\AR\2019\Crystal Reports\Mfg 609 V7 no 5 axis1 – (Hours + Setup Hrs) * 68.40
(SELECT 'BOE_03' AS [ORDER_TYPE]
	, CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
	, SUM(LT.HOURS_WORKED) AS TOTAL_HOURS_WORKED
	, ((SUM(LT.HOURS_WORKED) * 68.40) / COL.ORDER_QTY) AS UNIT_PRICE
	, SUM(LT.HOURS_WORKED) * 68.40 AS TOTAL_PRICE
	, SUM(LT.HOURS_WORKED) * 68.40 AS REC_AMOUNT
	, SUM(LT.HOURS_WORKED) * 68.40 AS TOTAL_AMT_ORDERED	
	, SUM(LT.HOURS_WORKED) * 68.40 AS TOTAL_AMT_SHIPPED
FROM SHIPPER S
INNER JOIN SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
INNER JOIN LABOR_TICKET LT
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
INNER JOIN SHOP_RESOURCE SR
	ON LT.RESOURCE_ID = SR.ID
WHERE  SL.SHIPPED_QTY > 0
	AND SR.SKILLS_TYPE IN (N'D', N'E', N'M')
	AND CO.CUSTOMER_ID = N'BOE609'
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.PartID_ReportSettings EX
		WHERE COL.PART_ID = EX.PART_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Mfg 609 V7 no 5 axis1'
	)
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.ResourceID_ReportSettings EX
		WHERE LT.RESOURCE_ID = EX.RESOURCE_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Mfg 609 V7 no 5 axis1'
			AND REPORT_SECTION = 'BOE609 Mfg 609 V7 no 5 axis1'
	)
	AND (S.INVOICED_DATE >= @STARTDATE)
GROUP BY CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
)

, BOE_04 AS
--BOE609 - ASSY - G:\ACCTG\AR\2019\Crystal Reports\Assy 609 V7a – (Hours + Setup Hrs) * 55.10
(SELECT 'BOE_04' AS [ORDER_TYPE]
	, CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
	, SUM(LT.HOURS_WORKED) AS TOTAL_HOURS_WORKED
	, ((SUM(LT.HOURS_WORKED) * 55.10) / COL.ORDER_QTY) AS UNIT_PRICE
	, SUM(LT.HOURS_WORKED) * 55.10 AS TOTAL_PRICE
	, SUM(LT.HOURS_WORKED) * 55.10 AS REC_AMOUNT
	, SUM(LT.HOURS_WORKED) * 55.10 AS TOTAL_AMT_ORDERED	
	, SUM(LT.HOURS_WORKED) * 55.10 AS TOTAL_AMT_SHIPPED
FROM SHIPPER S
INNER JOIN SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
INNER JOIN LABOR_TICKET LT
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
INNER JOIN SHOP_RESOURCE SR
	ON LT.RESOURCE_ID = SR.ID
WHERE SL.SHIPPED_QTY > 0
	AND SR.SKILLS_TYPE IN (N'D', N'E', N'M')
	AND CO.CUSTOMER_ID = N'BOE609'
	AND EXISTS (SELECT 1 FROM LIVESupplemental.dbo.PartID_ReportSettings EX
		WHERE COL.PART_ID = EX.PART_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Assy 609 V7a'
	)
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.ResourceID_ReportSettings EX
		WHERE LT.RESOURCE_ID = EX.RESOURCE_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Assy 609 V7a'
	)
	AND (S.INVOICED_DATE >= @STARTDATE)
GROUP BY CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
)

, BOE_05 AS
--BOE609 - 5AXIS - G:\ACCTG\AR\2019\Crystal Reports\Mfg 609 5 Axis – (Hours + Setup Hrs) * 80
(SELECT 'BOE_05' AS [ORDER_TYPE]
	, CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
	, SUM(LT.HOURS_WORKED) AS TOTAL_HOURS_WORKED
	, ((SUM(LT.HOURS_WORKED) * 80) / COL.ORDER_QTY) AS UNIT_PRICE
	, SUM(LT.HOURS_WORKED) * 80 AS TOTAL_PRICE
	, SUM(LT.HOURS_WORKED) * 80 AS REC_AMOUNT
	, SUM(LT.HOURS_WORKED) * 80 AS TOTAL_AMT_ORDERED	
	, SUM(LT.HOURS_WORKED) * 80 AS TOTAL_AMT_SHIPPED
FROM SHIPPER S
INNER JOIN SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
INNER JOIN LABOR_TICKET LT
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
INNER JOIN SHOP_RESOURCE SR
	ON LT.RESOURCE_ID = SR.ID
WHERE SL.SHIPPED_QTY > 0
	AND SR.SKILLS_TYPE IN (N'D', N'E', N'M')
	AND CO.CUSTOMER_ID = N'BOE609'
	AND EXISTS (SELECT 1 FROM LIVESupplemental.dbo.PartID_ReportSettings EX
		WHERE COL.PART_ID = EX.PART_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Mfg 609 5 Axis'
	)
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.ResourceID_ReportSettings EX
		WHERE LT.RESOURCE_ID = EX.RESOURCE_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Mfg 609 5 Axis'
	)
	AND (S.INVOICED_DATE >= @STARTDATE)
GROUP BY CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
)

, BOE_06 AS
--BOE614 - G:\ACCTG\AR\2019\Crystal Reports\boe614 boltboards 2 – (Hours + Setup Hrs) * 60
(SELECT 'BOE_06' AS [ORDER_TYPE]
	, CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
	, SUM(LT.HOURS_WORKED) AS TOTAL_HOURS_WORKED
	, ((SUM(LT.HOURS_WORKED) * 60) / COL.ORDER_QTY) AS UNIT_PRICE
	, SUM(LT.HOURS_WORKED) * 60 AS TOTAL_PRICE
	, SUM(LT.HOURS_WORKED) * 60 AS REC_AMOUNT
	, SUM(LT.HOURS_WORKED) * 60 AS TOTAL_AMT_ORDERED	
	, SUM(LT.HOURS_WORKED) * 60 AS TOTAL_AMT_SHIPPED
FROM RECEIVABLE_LINE RL
INNER JOIN CUST_ORDER_LINE COL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
LEFT OUTER JOIN WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
	AND DSL.SUPPLY_SUB_ID = WO.SUB_ID
LEFT OUTER JOIN LABOR_TICKET LT
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
WHERE RL.QTY > 0
	AND CO.CUSTOMER_ID = N'BOE614'
	AND (R.INVOICE_DATE >= @STARTDATE)
GROUP BY CO.ID
	, WO.BASE_ID
	, COL.ORDER_QTY
)

, CTE_BOE AS 	
(SELECT ID
	, BASE_ID
	, ORDER_QTY
	, SUM(TOTAL_HOURS_WORKED) AS TOTAL_HOURS_WORKED
	, (SUM(TOTAL_PRICE) / ORDER_QTY) AS UNIT_PRICE
	, SUM(TOTAL_PRICE) AS TOTAL_PRICE
	, SUM(REC_AMOUNT) AS REC_AMOUNT
FROM 
	(SELECT * FROM BOE_01
		UNION ALL
		SELECT * FROM BOE_02
		UNION ALL
		SELECT * FROM BOE_03
		UNION ALL
		SELECT * FROM BOE_04
		UNION ALL
		SELECT * FROM BOE_05
		UNION ALL
		SELECT * FROM BOE_06
	) A
GROUP BY ID
	, BASE_ID
	, ORDER_QTY
)
--SELECT * FROM CTE_BOE WHERE ID = '001614604'
-----------------------------> BOE QUERIES

, CTE_AMTRIB AS
(SELECT *
	--[ORDER_TYPE]
	--, CUST_ORDER_ID
	--, CUSTOMER_ID
	--, REPLACE(REPLACE(BASE_ID, 'A', ''), 'B', '') AS BASE_ID
	--, (SUM(REC_AMOUNT) / ISNULL(REC_QTY, SHIPPED_QTY)) AS INV_UNIT_PRICE
	--, SUM(REC_AMOUNT) AS REC_AMOUNT
	--, SUM(CHARGE_ALLOC) AS CHARGE_ALLOC
	--, SUM(TOTAL_PRICE) AS TOTAL_PRICE
	--, SUM(TRACE_BURDEN_COST) AS TRACE_BURDEN_COST
	--, SUM(TRACE_MATERIAL_COST) AS TRACE_MATERIAL_COST
	--, SUM(TRACE_LABOR_COST) AS TRACE_LABOR_COST
	--, SUM(TRACE_SERVICE_COST) AS TRACE_SERVICE_COST
	--, SUM(TOTAL_TRACE_COST) AS TOTAL_TRACE_COST
	--, (SUM(TOTAL_TRACE_COST) / ISNULL(REC_QTY, SHIPPED_QTY)) AS TRACE_UNIT_COST
FROM CTE_LINKED
WHERE CUSTOMER_ID = 'AMTRIB'
--GROUP BY [ORDER_TYPE]
--	, CUST_ORDER_ID
--	, CUSTOMER_ID
--	, REPLACE(REPLACE(BASE_ID, 'A', ''), 'B', '')
--	, REC_QTY
--	, SHIPPED_QTY
)
SELECT * FROM CTE_AMTRIB WHERE CUST_ORDER_ID = '429280'

, CTE_LINKED_ORDERS AS
(SELECT CASE 
		WHEN BOE.ID IS NOT NULL THEN 'BOE'
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN 'AMTRIB'
		ELSE LINKED.[ORDER_TYPE]
	END AS [ORDER_TYPE]
	, LINKED.TRACE_ID
	, LINKED.TRANSACTION_ID
	, LINKED.INVOICE_ID
	, LINKED.LINE_NO AS INV_LINE
	, LINKED.TRACE_QTY
	, LINKED.PACKLIST_ID
	, LINKED.SHIPPED_DATE
	, LINKED.CO_CREATE_DATE
	, LINKED.CUST_ORDER_ID
	, LINKED.LINE_NO
	, LINKED.CUSTOMER_ID
	, LINKED.PART_ID
	, LINKED.SHIP_SHORT
	, LINKED.COL_ORDER_QTY
	, LINKED.TOTAL_SHIPPED_QTY
	, LINKED.REC_QTY
	, CASE 
		WHEN BOE.ID IS NOT NULL THEN BOE.UNIT_PRICE
		ELSE LINKED.COL_UNIT_PRICE
	END AS COL_UNIT_PRICE
	, CASE 
		WHEN BOE.ID IS NOT NULL THEN BOE.UNIT_PRICE
		ELSE LINKED.INV_UNIT_PRICE
	END AS INV_UNIT_PRICE
	, CASE 
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.REC_AMOUNT
		WHEN BOE.ID IS NOT NULL THEN BOE.REC_AMOUNT
		ELSE LINKED.REC_AMOUNT
	END AS REC_AMOUNT
	, CASE 
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.CHARGE_ALLOC
		ELSE LINKED.CHARGE_ALLOC
	END AS CHARGE_ALLOC
	, LINKED.SHIPPED_QTY
	, CASE 
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.TOTAL_PRICE
		WHEN BOE.ID IS NOT NULL THEN BOE.TOTAL_PRICE
		ELSE LINKED.TOTAL_PRICE
	END AS TOTAL_PRICE
	, LINKED.[STATUS]
	, LINKED.WO_CREATE_DATE
	, LINKED.BASE_ID
	, LINKED.LOT_ID
	, LINKED.SPLIT_ID
 	, LINKED.SUB_ID
	, LINKED.DESIRED_QTY
	, CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.TRACE_BURDEN_COST
		WHEN LINKED.CUSTOMER_ID = 'AMTRIB' AND LINKED.BASE_ID != REPLACE(REPLACE(LINKED.BASE_ID, 'A', ''), 'B', '') THEN 0
		WHEN BOE.ID IS NULL AND LINKED.REC_AMOUNT < 0 THEN 0
--		WHEN LINKED.REC_QTY < 0 THEN 0
		WHEN BOE.REC_AMOUNT < 0 THEN 0
		ELSE LINKED.TRACE_BURDEN_COST
	END AS TRACE_BURDEN_COST
	, CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.TRACE_MATERIAL_COST
		WHEN LINKED.CUSTOMER_ID = 'AMTRIB' AND LINKED.BASE_ID != REPLACE(REPLACE(LINKED.BASE_ID, 'A', ''), 'B', '') THEN 0
		WHEN BOE.ID IS NULL AND LINKED.REC_AMOUNT < 0 THEN 0
--		WHEN LINKED.REC_QTY < 0 THEN 0
		WHEN BOE.REC_AMOUNT < 0 THEN 0
		ELSE LINKED.TRACE_MATERIAL_COST
	END AS TRACE_MATERIAL_COST
	, CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.TRACE_LABOR_COST
		WHEN LINKED.CUSTOMER_ID = 'AMTRIB' AND LINKED.BASE_ID != REPLACE(REPLACE(LINKED.BASE_ID, 'A', ''), 'B', '') THEN 0
		WHEN BOE.ID IS NULL AND LINKED.REC_AMOUNT < 0 THEN 0
--		WHEN LINKED.REC_QTY < 0 THEN 0
		WHEN BOE.REC_AMOUNT < 0 THEN 0
		ELSE LINKED.TRACE_LABOR_COST
	END AS TRACE_LABOR_COST
	, CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.TRACE_SERVICE_COST
		WHEN LINKED.CUSTOMER_ID = 'AMTRIB' AND LINKED.BASE_ID != REPLACE(REPLACE(LINKED.BASE_ID, 'A', ''), 'B', '') THEN 0
		WHEN BOE.ID IS NULL AND LINKED.REC_AMOUNT < 0 THEN 0
--		WHEN LINKED.REC_QTY < 0 THEN 0
		WHEN BOE.REC_AMOUNT < 0 THEN 0
		ELSE LINKED.TRACE_SERVICE_COST
	END AS TRACE_SERVICE_COST
	, CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.TOTAL_TRACE_COST
		WHEN LINKED.CUSTOMER_ID = 'AMTRIB' AND LINKED.BASE_ID != REPLACE(REPLACE(LINKED.BASE_ID, 'A', ''), 'B', '') THEN 0
		WHEN BOE.ID IS NULL AND LINKED.REC_AMOUNT < 0 THEN 0
--		WHEN LINKED.REC_QTY < 0 THEN 0
		WHEN BOE.REC_AMOUNT < 0 THEN 0
		ELSE LINKED.TOTAL_TRACE_COST
	END AS TOTAL_TRACE_COST
	, CASE
		WHEN AMT.CUST_ORDER_ID IS NOT NULL THEN AMT.TRACE_UNIT_COST
		WHEN LINKED.CUSTOMER_ID = 'AMTRIB' AND LINKED.BASE_ID != REPLACE(REPLACE(LINKED.BASE_ID, 'A', ''), 'B', '') THEN 0
		WHEN BOE.ID IS NULL AND LINKED.REC_AMOUNT < 0 THEN 0
--		WHEN LINKED.REC_QTY < 0 THEN 0
		WHEN BOE.REC_AMOUNT < 0 THEN 0
		ELSE LINKED.TRACE_UNIT_COST
	END AS TRACE_UNIT_COST
FROM CTE_LINKED LINKED
LEFT OUTER JOIN CTE_BOE BOE
	ON BOE.ID = LINKED.CUST_ORDER_ID
	AND BOE.BASE_ID = LINKED.BASE_ID
LEFT OUTER JOIN CTE_AMTRIB AMT
	ON AMT.CUST_ORDER_ID = LINKED.CUST_ORDER_ID
	AND AMT.BASE_ID = LINKED.BASE_ID

)
--SELECT * FROM CTE_LINKED_ORDERS WHERE CUST_ORDER_ID = '437020'   --CUSTOMER_ID = 'AMTRIB'
SELECT * FROM CTE_AMTRIB WHERE CUST_ORDER_ID = '429280'

/*
, CTE_UNLINKED as
(SELECT 'UNLINKED' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, (RL.AMOUNT / ISNULL(RL.QTY, SL.SHIPPED_QTY)) AS INV_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, CASE
		WHEN SL.SHIPPED_QTY < 0 OR RL.AMOUNT < 0 THEN 0
		WHEN WO.BASE_ID LIKE '%R%' THEN 0
		ELSE ISNULL(CTE01.CHARGE_ALLOC, 0) 
	END AS CHARGE_ALLOC
	, SL.SHIPPED_QTY
	, CASE	
		WHEN SL.SHIPPED_QTY < 0 OR RL.AMOUNT < 0 THEN RL.AMOUNT
		WHEN WO.BASE_ID LIKE '%R%' THEN 0
		WHEN T.QTY IS NULL THEN ISNULL(CTE01.CHARGE_ALLOC, 0) + (RL.AMOUNT) 
		ELSE ((ISNULL(CTE01.CHARGE_ALLOC, 0) + RL.AMOUNT) / ISNULL(RL.QTY, SL.SHIPPED_QTY)) * (T.QTY * -1)
	END AS TOTAL_PRICE
	, WO.[STATUS]
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_BURDEN_COST
		ELSE ((T.QTY * -1) * (WO.ACT_BURDEN_COST / WO.DESIRED_QTY)) 
	END AS TRACE_BURDEN_COST
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_MATERIAL_COST
		ELSE ((T.QTY * -1) * (WO.ACT_MATERIAL_COST / WO.DESIRED_QTY)) 
	END AS TRACE_MATERIAL_COST
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_LABOR_COST
		ELSE ((T.QTY * -1) * (WO.ACT_LABOR_COST / WO.DESIRED_QTY)) 
	END AS TRACE_LABOR_COST
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_SERVICE_COST
		ELSE ((T.QTY * -1) * (WO.ACT_SERVICE_COST / WO.DESIRED_QTY)) 
	END AS TRACE_SERVICE_COST
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		WHEN T.TRACE_ID IS NULL THEN (WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST)
		ELSE ((T.QTY * -1) * ((WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) / WO.DESIRED_QTY))
	END AS TOTAL_TRACE_COST
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		ELSE ((WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) / WO.DESIRED_QTY) 
	END AS TRACE_UNIT_COST
FROM SHIPPER_LINE SL
INNER JOIN TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND SL.PACKLIST_ID = RL.PACKLIST_ID 
	AND SL.LINE_NO = RL.PACKLIST_LINE_NO 
	AND RL.PACKLIST_ID IS NOT NULL
LEFT OUTER JOIN SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SPLIT_ID = '0'
	AND WO.SUB_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
--	AND DSL.SUPPLY_BASE_ID IS NULL
LEFT OUTER JOIN CTE_CHGAMTS CTE01
	ON COL.CUST_ORDER_ID = CTE01.CUST_ORDER_ID
WHERE S.SHIPPED_DATE >= @STARTDATE
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NULL

----
UNION ALL
----
SELECT 'UNLINKED' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, (RL.AMOUNT / ISNULL(RL.QTY, SL.SHIPPED_QTY)) AS INV_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, CASE
		WHEN SL.SHIPPED_QTY < 0 OR RL.AMOUNT < 0 THEN 0
		WHEN WO.BASE_ID LIKE '%R%' THEN 0
		ELSE ISNULL(CTE01.CHARGE_ALLOC, 0) 
	END AS CHARGE_ALLOC
	, SL.SHIPPED_QTY
	, CASE	
		WHEN SL.SHIPPED_QTY < 0 OR RL.AMOUNT < 0 THEN RL.AMOUNT
		WHEN WO.BASE_ID LIKE '%R%' THEN 0
		WHEN T.QTY IS NULL THEN ISNULL(CTE01.CHARGE_ALLOC, 0) + (RL.AMOUNT) 
		ELSE ((ISNULL(CTE01.CHARGE_ALLOC, 0) + RL.AMOUNT) / ISNULL(RL.QTY, SL.SHIPPED_QTY)) * (T.QTY * -1)
	END AS TOTAL_PRICE
	, WO.[STATUS]
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_BURDEN_COST
		ELSE ((T.QTY * -1) * (WO.ACT_BURDEN_COST / WO.DESIRED_QTY)) 
	END AS TRACE_BURDEN_COST
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_MATERIAL_COST
		ELSE ((T.QTY * -1) * (WO.ACT_MATERIAL_COST / WO.DESIRED_QTY)) 
	END AS TRACE_MATERIAL_COST
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_LABOR_COST
		ELSE ((T.QTY * -1) * (WO.ACT_LABOR_COST / WO.DESIRED_QTY)) 
	END AS TRACE_LABOR_COST
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		WHEN T.TRACE_ID IS NULL THEN WO.ACT_SERVICE_COST
		ELSE ((T.QTY * -1) * (WO.ACT_SERVICE_COST / WO.DESIRED_QTY)) 
	END AS TRACE_SERVICE_COST
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		WHEN T.TRACE_ID IS NULL THEN (WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST)
		ELSE ((T.QTY * -1) * ((WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) / WO.DESIRED_QTY))
	END AS TOTAL_TRACE_COST
	, CASE
		WHEN RL.AMOUNT < 0 THEN 0
		ELSE ((WO.ACT_BURDEN_COST + WO.ACT_MATERIAL_COST + WO.ACT_LABOR_COST + WO.ACT_SERVICE_COST) / WO.DESIRED_QTY) 
	END AS TRACE_UNIT_COST
FROM SHIPPER_LINE SL
INNER JOIN TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND SL.PACKLIST_ID = RL.PACKLIST_ID 
	AND SL.LINE_NO = RL.PACKLIST_LINE_NO 
	AND RL.PACKLIST_ID IS NOT NULL
LEFT OUTER JOIN SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID + '/' + WO.SUB_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SPLIT_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
LEFT OUTER JOIN CTE_CHGAMTS CTE01
	ON COL.CUST_ORDER_ID = CTE01.CUST_ORDER_ID
WHERE S.SHIPPED_DATE >= @STARTDATE
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NULL
)
--select * from cte_unlinked

, CTE_COMBINED AS
(SELECT * 
FROM CTE_LINKED_ORDERS
UNION ALL
SELECT * 
FROM CTE_UNLINKED 
)

SELECT CASE
	WHEN REC_AMOUNT < 0 AND REC_QTY < 0 THEN 'RETURN'
	WHEN REC_AMOUNT < 0 AND REC_QTY > 0 THEN 'CREDIT'
	WHEN REC_AMOUNT = 0 AND CHARGE_ALLOC > 0 THEN 'CHARGE'
	WHEN REC_AMOUNT = 0 AND CHARGE_ALLOC = 0 AND BASE_ID LIKE '%R%' THEN 'REWORK'
	WHEN REC_AMOUNT = 0 AND CHARGE_ALLOC = 0 AND [STATUS] = 'X' THEN 'CANCELLED'
	WHEN CUSTOMER_ID = 'AMTRIB' THEN 'AMTRIB'
	WHEN CUSTOMER_ID = 'SPIAER' THEN 'SPIAER'
	WHEN REC_AMOUNT > 0 THEN 'INVOICE'
	ELSE 'ISSUES'
	END AS REC_ISSUES
	, (COL_UNIT_PRICE - INV_UNIT_PRICE) AS UNITPRICE_DELTA
	, *
FROM CTE_COMBINED 
*/