USE DataWarehouse
GO

DECLARE @STARTDATE DATETIME = '8/1/2018',
	@ENDDATE DATETIME = '8/22/2019'
;

--BOE605 - G:\ACCTG\AR\2019\Crystal Reports\BOE605revF – (Hours + Setup Hrs) * 75
WITH CTE_01 AS 
(SELECT CO.ID
	, WO.BASE_ID
	, LT.HOURS_WORKED
	, COL.PART_ID
	, COL.TOTAL_SHIPPED_QTY
	, LT.[TYPE]
	, LT.TRANSACTION_ID
	, CO.CUSTOMER_ID
	, LT.TRANSACTION_DATE
	, SL.SHIPPED_QTY
	, S.INVOICE_ID
	, S.INVOICED_DATE
	, S.PACKLIST_ID
	, O.RESOURCE_ID
	, O.SEQUENCE_NO
	, O.SETUP_COMPLETED
	, CO.CUSTOMER_PO_REF
FROM SHIPPER S
INNER JOIN SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID 
LEFT OUTER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO 
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
LEFT OUTER JOIN WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
INNER JOIN OPERATION O
	ON WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O.WORKORDER_SUB_ID
	AND WO.[TYPE] = O.WORKORDER_TYPE
LEFT OUTER JOIN LABOR_TICKET LT
	ON O.SEQUENCE_NO = LT.OPERATION_SEQ_NO
	AND O.WORKORDER_BASE_ID = LT.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = LT.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
WHERE SL.SHIPPED_QTY > 0
--	AND CO.CUSTOMER_ID = N'BOE602' OR CO.CUSTOMER_ID = N'BOE605')
	AND CO.CUSTOMER_ID IN (N'BOE602', N'BOE605')
	AND WO.BASE_ID NOT LIKE N'%R%'
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.ResourceID_ReportSettings EX
		WHERE O.RESOURCE_ID = EX.RESOURCE_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE605revF'
	)
	AND (S.INVOICED_DATE >= @STARTDATE
		AND S.INVOICED_DATE <= @ENDDATE)
)

--BOE609 - Finish - G:\ACCTG\AR\2019\Crystal Reports\Finish 609v1 – (Hours + Setup Hrs) * 70
, CTE_02 AS
(SELECT CO.ID AS CUST_ORDER_ID
	, WO.BASE_ID
	, LT.HOURS_WORKED
	, COL.PART_ID AS CO_PART_ID
	, COL.TOTAL_SHIPPED_QTY
	, LT.[TYPE]
	, LT.TRANSACTION_ID
	, CO.CUSTOMER_ID
	, SR.SKILLS_TYPE
	, SL.SHIPPED_QTY
	, S.INVOICE_ID
	, S.INVOICED_DATE
	, S.PACKLIST_ID
	, SR.ID AS RESOURCE_ID
	, WO.PART_ID AS WO_PART_ID
FROM SHIPPER S
INNER JOIN SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
INNER JOIN LABOR_TICKET LT
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
INNER JOIN SHOP_RESOURCE SR
	ON LT.RESOURCE_ID = SR.ID
WHERE SL.SHIPPED_QTY > 0
	AND SR.SKILLS_TYPE <> N'M'
	AND CO.CUSTOMER_ID = N'BOE609'
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.ResourceID_ReportSettings EX
		WHERE LT.RESOURCE_ID = EX.RESOURCE_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 - Finish 609v1'
	)
	AND (S.INVOICED_DATE >= @STARTDATE
		AND S.INVOICED_DATE <= @ENDDATE)
)

, CTE_03 AS 
--BOE609 - MFG - G:\ACCTG\AR\2019\Crystal Reports\Mfg 609 V7 no 5 axis1 – (Hours + Setup Hrs) * 68.40
(SELECT CO.ID AS CUST_ORDER_ID
	, WO.BASE_ID
	, LT.HOURS_WORKED
	, COL.PART_ID AS CO_PART_ID
	, COL.TOTAL_SHIPPED_QTY
	, LT.[TYPE]
	, LT.TRANSACTION_ID
	, CO.CUSTOMER_ID
	, SR.SKILLS_TYPE
	, SL.SHIPPED_QTY
	, S.INVOICE_ID
	, S.INVOICED_DATE
	, S.PACKLIST_ID
	, SR.ID AS RESOURCE_ID
	, WO.PART_ID AS WO_PART_ID
	, WO.ACT_SERVICE_COST
FROM SHIPPER S
INNER JOIN SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
INNER JOIN LABOR_TICKET LT
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
INNER JOIN SHOP_RESOURCE SR
	ON LT.RESOURCE_ID = SR.ID
WHERE  SL.SHIPPED_QTY > 0
	AND SR.SKILLS_TYPE IN (N'D', N'E', N'M')
	AND CO.CUSTOMER_ID = N'BOE609'
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.PartID_ReportSettings EX
		WHERE COL.PART_ID = EX.PART_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Mfg 609 V7 no 5 axis1'
	)
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.ResourceID_ReportSettings EX
		WHERE LT.RESOURCE_ID = EX.RESOURCE_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Mfg 609 V7 no 5 axis1'
			AND REPORT_SECTION = 'BOE609 Mfg 609 V7 no 5 axis1'
	)
	AND (S.INVOICED_DATE >= @STARTDATE
		AND S.INVOICED_DATE <= @ENDDATE)
)

, CTE_04 AS
--BOE609 - ASSY - G:\ACCTG\AR\2019\Crystal Reports\Assy 609 V7a – (Hours + Setup Hrs) * 55.10
(SELECT CO.ID AS CUST_ORDER_ID
	, WO.BASE_ID
	, LT.HOURS_WORKED
	, COL.PART_ID AS CO_PART_ID
	, COL.TOTAL_SHIPPED_QTY
	, LT.[TYPE]
	, LT.TRANSACTION_ID
	, CO.CUSTOMER_ID
	, SR.SKILLS_TYPE
	, SL.SHIPPED_QTY
	, S.INVOICE_ID
	, S.INVOICED_DATE
	, S.PACKLIST_ID
	, SR.ID AS RESOURCE_ID
	, WO.PART_ID AS WO_PART_ID
	, WO.ACT_SERVICE_COST
FROM SHIPPER S
INNER JOIN SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
INNER JOIN LABOR_TICKET LT
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
INNER JOIN SHOP_RESOURCE SR
	ON LT.RESOURCE_ID = SR.ID
WHERE SL.SHIPPED_QTY > 0
	AND SR.SKILLS_TYPE IN (N'D', N'E', N'M')
	AND CO.CUSTOMER_ID = N'BOE609'
	AND EXISTS (SELECT 1 FROM LIVESupplemental.dbo.PartID_ReportSettings EX
		WHERE COL.PART_ID = EX.PART_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Assy 609 V7a'
	)
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.ResourceID_ReportSettings EX
		WHERE LT.RESOURCE_ID = EX.RESOURCE_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Assy 609 V7a'
	)
	AND (S.INVOICED_DATE >= @STARTDATE
		AND S.INVOICED_DATE <= @ENDDATE)
)

, CTE_05 AS
--BOE609 - 5AXIS - G:\ACCTG\AR\2019\Crystal Reports\Mfg 609 5 Axis – (Hours + Setup Hrs) * 80
(SELECT CO.ID AS CUST_ORDER_ID
	, WO.BASE_ID
	, LT.HOURS_WORKED
	, COL.PART_ID AS CO_PART_ID
	, COL.TOTAL_SHIPPED_QTY
	, LT.[TYPE]
	, LT.TRANSACTION_ID
	, CO.CUSTOMER_ID
	, SR.SKILLS_TYPE
	, SL.SHIPPED_QTY
	, S.INVOICE_ID
	, S.INVOICED_DATE
	, S.PACKLIST_ID
	, SR.ID AS RESOURCE_ID
	, WO.PART_ID AS WO_PART_ID
	, WO.ACT_SERVICE_COST
FROM SHIPPER S
INNER JOIN SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID
INNER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
INNER JOIN LABOR_TICKET LT
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
INNER JOIN SHOP_RESOURCE SR
	ON LT.RESOURCE_ID = SR.ID
WHERE SL.SHIPPED_QTY > 0
	AND SR.SKILLS_TYPE IN (N'D', N'E', N'M')
	AND CO.CUSTOMER_ID = N'BOE609'
	AND EXISTS (SELECT 1 FROM LIVESupplemental.dbo.PartID_ReportSettings EX
		WHERE COL.PART_ID = EX.PART_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Mfg 609 5 Axis'
	)
	AND NOT EXISTS (SELECT 1 FROM LIVESupplemental.dbo.ResourceID_ReportSettings EX
		WHERE LT.RESOURCE_ID = EX.RESOURCE_ID
			AND REPORT_NAME = 'Gross Margin'
			AND REPORT_SECTION = 'BOE609 Mfg 609 5 Axis'
	)
	AND (S.INVOICED_DATE >= @STARTDATE
		AND S.INVOICED_DATE <= @ENDDATE)
)

, CTE_06 AS
--BOE614 - G:\ACCTG\AR\2019\Crystal Reports\boe614 boltboards 2 – (Hours + Setup Hrs) * 60
(SELECT CO.ID AS CUST_ORDER_ID
	, WO.BASE_ID
	, RL.QTY
	, LT.HOURS_WORKED
	, RL.PACKLIST_ID
	, RL.INVOICE_ID AS RL_INV_ID
	, COL.PART_ID AS CO_PART_ID
	, COL.TOTAL_SHIPPED_QTY
	, R.INVOICE_DATE
	, LT.[TYPE]
	, LT.TRANSACTION_ID
	, CO.CUSTOMER_ID
	, COL.UNIT_PRICE
	, R.INVOICE_ID AS R_INV_ID
	, RL.AMOUNT
FROM RECEIVABLE_LINE RL
INNER JOIN CUST_ORDER_LINE COL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
LEFT OUTER JOIN WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
	AND DSL.SUPPLY_SUB_ID = WO.SUB_ID
LEFT OUTER JOIN LABOR_TICKET LT
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
WHERE RL.QTY > 0
	AND CO.CUSTOMER_ID = N'BOE614'
	AND (R.INVOICE_DATE >= @STARTDATE
		AND R.INVOICE_DATE <= @ENDDATE)
)

--SELECT * FROM CTE_01
SELECT * FROM CTE_02
--SELECT * FROM CTE_03
--SELECT * FROM CTE_04
--SELECT * FROM CTE_05
--SELECT * FROM CTE_06

