use DataWarehouse
go

declare @timeframe nvarchar(20) = 'LAST MONTH'

set datefirst 1;

SELECT O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.WORKORDER_TYPE
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.OPERATION_TYPE
	, O.CLOSE_DATE
	, SR.USER_1
	, SR.USER_2
	, SR.USER_3
	, SR.USER_4
	, SR.USER_5
	, DATEPART(YYYY, O.CLOSE_DATE) AS [YEAR]
	, DATEPART(MM, O.CLOSE_DATE) AS [MONTH]
	, DATEPART(QQ, O.CLOSE_DATE) AS [QUARTER]
	, DATEPART(WW, O.CLOSE_DATE) AS [WEEK]
	, CASE
		WHEN @TIMEFRAME IN ('LAST WEEK', 'CURRENT WEEK') THEN DATEPART(DD, O.CLOSE_DATE)
		WHEN @TIMEFRAME IN ('LAST MONTH', 'CURRENT MONTH') THEN DATEPART(WW, O.CLOSE_DATE)
		WHEN @TIMEFRAME IN ('LAST QUARTER', 'CURRENT QUARTER') THEN DATEPART(MM, O.CLOSE_DATE)
		WHEN @TIMEFRAME IN ('LAST YEAR', 'CURRENT YEAR') THEN DATEPART(MM, O.CLOSE_DATE)
	END AS TIMEFRAME
FROM OPERATION O
LEFT OUTER JOIN SHOP_RESOURCE_SITE SR
	ON O.RESOURCE_ID = SR.RESOURCE_ID
WHERE 
	(@TIMEFRAME = 'LAST YEAR' AND YEAR(O.CLOSE_DATE) = YEAR(GETDATE()) - 1
		)
	OR (@TIMEFRAME = 'CURRENT YEAR' AND YEAR(O.CLOSE_DATE) = YEAR(GETDATE())
		)
	OR (@TIMEFRAME = 'CURRENT WEEK' AND YEAR(O.CLOSE_DATE) = YEAR(GETDATE()) AND DATEPART(WW, O.CLOSE_DATE) = DATEPART(WW, GETDATE())
		)
	OR (@TIMEFRAME = 'CURRENT MONTH' AND YEAR(O.CLOSE_DATE) = YEAR(GETDATE()) AND DATEPART(MM, O.CLOSE_DATE) = DATEPART(MM, GETDATE())
		)
---- in same year
	OR (@TIMEFRAME = 'LAST WEEK' AND DATEPART(WW, GETDATE()) > 1 AND YEAR(O.CLOSE_DATE) = YEAR(GETDATE()) AND DATEPART(WW, O.CLOSE_DATE) = DATEPART(WW, GETDATE()) - 1
		)
---- in different year, over the gap
	OR (@TIMEFRAME = 'LAST WEEK' AND DATEPART(WW, GETDATE()) = 1 AND YEAR(O.CLOSE_DATE) = YEAR(GETDATE()) - 1 AND DATEPART(WW, O.CLOSE_DATE) >= 52
		)
---- in same year
	OR (@TIMEFRAME = 'LAST MONTH' AND DATEPART(MM, GETDATE()) > 1 AND YEAR(O.CLOSE_DATE) = YEAR(GETDATE()) AND DATEPART(MM, O.CLOSE_DATE) = DATEPART(MM, GETDATE()) - 1
--		)
---- in different year, over the gap
	OR (@TIMEFRAME = 'LAST MONTH'  AND DATEPART(MM, GETDATE()) = 1 AND YEAR(O.CLOSE_DATE) = YEAR(GETDATE()) - 1 AND DATEPART(MM, O.CLOSE_DATE) = 12
		)
---- in same year
	OR (@TIMEFRAME = 'LAST QUARTER'  AND DATEPART(QQ, GETDATE()) > 1 AND YEAR(O.CLOSE_DATE) = YEAR(GETDATE()) AND DATEPART(QQ, O.CLOSE_DATE) = DATEPART(QQ, GETDATE()) - 1
		)
---- in different year, over the gap
	OR (@TIMEFRAME = 'LAST QUARTER' AND DATEPART(QQ, GETDATE()) = 1 AND YEAR(O.CLOSE_DATE) = YEAR(GETDATE()) -1 AND DATEPART(QQ, O.CLOSE_DATE) = 4
		)
	 )

/*
select getdate()
, datepart(yyyy, getdate()) as [year]
, datepart(mm, getdate()) as [month]
, datepart(qq, getdate()) as [quarter]
, datepart(ww, getdate()) as [week]

-- Sunday is first day of week
set datefirst 7; 
select DATEPART(dw,getdate()) as weekday


-- Monday is first day of week
set datefirst 1;
select DATEPART(dw,getdate()) as weekday

*/
