--RUN IN BI-1
/*
DROP TABLE [LIVESupplemental].[dbo].[Barcode_Employee_Total_Hours$_old]
DROP TABLE [LIVESupplemental].[dbo].[Bin Location List$_old]
DROP TABLE [LIVESupplemental].[dbo].[BOEDEF_Q831$_old]
DROP TABLE [LIVESupplemental].[dbo].[BOEDEF_Q831_2$_old]
DROP TABLE [LIVESupplemental].[dbo].[BuyerID_report_old]
DROP TABLE [LIVESupplemental].[dbo].[carousel_location_list$_old]
DROP TABLE [LIVESupplemental].[dbo].[Contract_List_Skills$_old]
DROP TABLE [LIVESupplemental].[dbo].[contract_parts_details_check$_old]
DROP TABLE [LIVESupplemental].[dbo].[cust_address_import_to_update_salesrep_id$_old]
DROP TABLE [LIVESupplemental].[dbo].[Cust_Reps_old]
DROP TABLE [LIVESupplemental].[dbo].[customer_reps_old]
DROP TABLE [LIVESupplemental].[dbo].[Doc_Refs_Finish$_old]
DROP TABLE [LIVESupplemental].[dbo].[DOCREF_eSCM$_old]
DROP TABLE [LIVESupplemental].[dbo].[email updates_old]
DROP TABLE [LIVESupplemental].[dbo].[emp_ADP_OLD]
DROP TABLE [LIVESupplemental].[dbo].[Facility Division_old]
DROP TABLE [LIVESupplemental].[dbo].[Filtered for MFG Only_old]
DROP TABLE [LIVESupplemental].[dbo].[Finish_Customers$_old]
DROP TABLE [LIVESupplemental].[dbo].[FixedAssets_hold]
DROP TABLE [LIVESupplemental].[dbo].[headcount_titles_old]
DROP TABLE [LIVESupplemental].[dbo].[LMC_MRP_EXCEPTIONS_HISTORY_OLD]
DROP TABLE [LIVESupplemental].[dbo].[MAG_PARTIAL_INSPECT_old]
DROP TABLE [LIVESupplemental].[dbo].[master_schedule_forecast$_old]
DROP TABLE [LIVESupplemental].[dbo].[MasterOperationRuntimesUpload_old]
DROP TABLE [LIVESupplemental].[dbo].[MFG_Backlog_old]
DROP TABLE [LIVESupplemental].[dbo].[MFG_Quotes_2016$_old]
DROP TABLE [LIVESupplemental].[dbo].[Op_Type_Assignments_old]
DROP TABLE [LIVESupplemental].[dbo].[paint_commodity_codes_update$_old]
DROP TABLE [LIVESupplemental].[dbo].[PaintPrime breakout$_old]
DROP TABLE [LIVESupplemental].[dbo].[part_and_wo_list$_old]
DROP TABLE [LIVESupplemental].[dbo].[Part_ID$_old]
DROP TABLE [LIVESupplemental].[dbo].[part_ids_needing_cost_info$_old]
DROP TABLE [LIVESupplemental].[dbo].[part_number_for_SNN$_old]
DROP TABLE [LIVESupplemental].[dbo].[part_price_import$_old]
DROP TABLE [LIVESupplemental].[dbo].[PartMaintUpdates$_old]
DROP TABLE [LIVESupplemental].[dbo].[parts_update_buyer$_old]
DROP TABLE [LIVESupplemental].[dbo].[parts_update_buyer_old]
DROP TABLE [LIVESupplemental].[dbo].[PeriodNames_old]
DROP TABLE [LIVESupplemental].[dbo].[Periods_old]
DROP TABLE [LIVESupplemental].[dbo].[Planners_old]
DROP TABLE [LIVESupplemental].[dbo].[punch_press_tooling$_old]
DROP TABLE [LIVESupplemental].[dbo].[RESOURCE_GROUP_ASSIGNMENTS_old]
DROP TABLE [LIVESupplemental].[dbo].[RESOURCE_GROUPS_old]
DROP TABLE [LIVESupplemental].[dbo].[resource_ids_removed_reportsettings$_old]
DROP TABLE [LIVESupplemental].[dbo].[resource_ids_removed_reportsettings2$_old]
DROP TABLE [LIVESupplemental].[dbo].[Resource_IDs_update_description$_old]
DROP TABLE [LIVESupplemental].[dbo].[ResourceID_Assignments_2018_old]
DROP TABLE [LIVESupplemental].[dbo].[ResourceID_Assignments_NOT_IN_USE_old]
DROP TABLE [LIVESupplemental].[dbo].[ResourceID_Group_Primary_old]
DROP TABLE [LIVESupplemental].[dbo].[ResourceID_Group_Secondary_old]
DROP TABLE [LIVESupplemental].[dbo].[ResourceID_History_old]
DROP TABLE [LIVESupplemental].[dbo].[ResourceID_Supervisor_old]
DROP TABLE [LIVESupplemental].[dbo].[rplus_part_inventory$_old]
DROP TABLE [LIVESupplemental].[dbo].[Service_ID_with_specs3$_old]
DROP TABLE [LIVESupplemental].[dbo].[SINC_UM_old]
DROP TABLE [LIVESupplemental].[dbo].[Skills_Finish_Open_Orders_old]
DROP TABLE [LIVESupplemental].[dbo].[skills_powerbi_URLs_20191210_old]
DROP TABLE [LIVESupplemental].[dbo].[Skills_RES_OP_SupervisorMatrix_old]
DROP TABLE [LIVESupplemental].[dbo].[SKILLS_TYPE_old]
DROP TABLE [LIVESupplemental].[dbo].[Supervisors_old]
DROP TABLE [LIVESupplemental].[dbo].[supplier_monitoring$_old]
DROP TABLE [LIVESupplemental].[dbo].[T_part_site$_old]
DROP TABLE [LIVESupplemental].[dbo].[Tally_old]
DROP TABLE [LIVESupplemental].[dbo].[Target_Totals_old]
DROP TABLE [LIVESupplemental].[dbo].[tmpRES_OP_SupervisorMatrix_old]
DROP TABLE [LIVESupplemental].[dbo].[Truck_Manifest_old]
DROP TABLE [LIVESupplemental].[dbo].[Truck_Manifest_Packlists_old]
DROP TABLE [LIVESupplemental].[dbo].[UDF Values_old]
DROP TABLE [LIVESupplemental].[dbo].[UPDATE_CNT_DT$_old]
DROP TABLE [LIVESupplemental].[dbo].[Update_docref_id$_old]
DROP TABLE [LIVESupplemental].[dbo].[update_masters_resource_ids$_old]
DROP TABLE [LIVESupplemental].[dbo].[update_part_buyer_user_IDs$_old]
DROP TABLE [LIVESupplemental].[dbo].[update_Plane_Model$_old]
DROP TABLE [LIVESupplemental].[dbo].[update_planning_leadtime$_old]
DROP TABLE [LIVESupplemental].[dbo].[update_property$_old]
DROP TABLE [LIVESupplemental].[dbo].[USER_NO_EMAIL_old]
DROP TABLE [LIVESupplemental].[dbo].[Valid_Planner_User_IDs-old]
DROP TABLE [LIVESupplemental].[dbo].[Vendor_Buyers_old]
DROP TABLE [LIVESupplemental].[dbo].[VendorUpdate_Log_old]
DROP TABLE [LIVESupplemental].[dbo].[visual_upload_part$_old]
DROP TABLE [LIVESupplemental].[dbo].[visual_upload_part_old]
DROP TABLE [LIVESupplemental].[dbo].[wo_DailyStatustemp_old]
DROP TABLE [LIVESupplemental].[dbo].[WO_OPERATION_ALERTS_EMAILS_old]
DROP TABLE [LIVESupplemental].[dbo].[WO_OPERATION_ALERTS_LOG_old]
DROP TABLE [LIVESupplemental].[dbo].[WO_OPERATION_ALERTS_old]
DROP TABLE [LIVESupplemental].[dbo].[WORK_ORDER_PRINTED_old]

*/