USE LIVE
GO

--> FIRST OF THE MONTH:
--DECLARE @STARTDATE DATE = DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0)
DECLARE @STARTDATE DATE = '1/1/2010'


SELECT * FROM 
	(SELECT CASE
	--> OUTPUTS
--	WHEN ISNULL(I.PART_ID, '') != '' AND ISNULL(DIST.IN_TRANS_ID, '') = '' THEN 'ISSUE RETURNS'
	WHEN ISNULL(I.WORKORDER_TYPE, '') = '' 
		AND (I.[DESCRIPTION] LIKE 'Transfer from location%' 
			OR I.[DESCRIPTION] LIKE 'Transfer to location%' 
			OR I.[DESCRIPTION] LIKE 'PHYSICAL COUNT%'
			) THEN 'TRANSFER/COUNT ADJ'
	WHEN I.WORKORDER_TYPE = 'W' AND ISNULL(I.WORKORDER_BASE_ID, '') = ''
		AND ISNULL(I.[PART_ID], '') != '' AND ISNULL(I.[CUST_ORDER_ID], '') = ''
		AND ISNULL(I.[PURC_ORDER_ID], '') = '' AND I.[CLASS] = 'A' --AND I.[TYPE] = 'I'
			THEN 'COUNT CORRECTIONS'
	WHEN ISNULL(I.PART_ID, '') = '' AND ISNULL(DI.IN_TRANS_ID, '') = '' THEN 'EXTRANEOUS PO CHARGES'
	WHEN ISNULL(I.WORKORDER_TYPE, '') = '' AND I.[CLASS] = 'R' --AND I.[TYPE] = 'I' 
		AND ISNULL(I.[PART_ID], '') != '' AND ISNULL(I.[PURC_ORDER_ID], '') != ''
			THEN 'PO RETURNS'
	WHEN ISNULL(I.WORKORDER_TYPE, '') = '' AND I.[CLASS] = 'A' 
		AND ISNULL(I.[PART_ID], '') != '' AND ISNULL(I.[PURC_ORDER_ID], '') != ''
			THEN 'PART RETURNS'
	WHEN ISNULL(I.WORKORDER_TYPE, '') = '' AND I.[CLASS] = 'I' AND I.[TYPE] = 'O' 
		AND ISNULL(I.[PART_ID], '') != '' AND ISNULL(I.[CUST_ORDER_ID], '') != ''
		AND ISNULL(I.[PURC_ORDER_ID], '') != ''
			THEN 'CUSTOMER RETURNS'
	--> INPUTS
	WHEN ISNULL(O.WORKORDER_BASE_ID, '') = '' --AND O.WORKORDER_TYPE = 'W'
		AND ISNULL(O.[PART_ID], '') != '' --AND ISNULL(O.[CUST_ORDER_ID], '') = ''
		AND ISNULL(O.[PURC_ORDER_ID], '') = '' AND O.[CLASS] = 'A' AND O.[TYPE] = 'I'
			THEN 'COUNT CORRECTIONS'
	WHEN O.WORKORDER_TYPE = 'W' AND ISNULL(O.WORKORDER_BASE_ID, '') != ''
		AND ISNULL(O.[PART_ID], '') != '' AND ISNULL(O.[CUST_ORDER_ID], '') = ''
		AND ISNULL(O.[PURC_ORDER_ID], '') = '' --AND O.[CLASS] = 'I' AND O.[TYPE] = 'I'
			THEN 'WO PRODUCED'
	WHEN I.WORKORDER_TYPE = 'W' AND ISNULL(I.WORKORDER_BASE_ID, '') != ''
		AND ISNULL(I.[PART_ID], '') != '' AND ISNULL(I.[CUST_ORDER_ID], '') = ''
		AND ISNULL(I.[PURC_ORDER_ID], '') = '' AND I.[TYPE] = 'I' --AND I.[CLASS] = 'R' 
			THEN 'WO RETURNED'
	WHEN ISNULL(O.WORKORDER_TYPE, '') = '' AND O.[DESCRIPTION] LIKE 'PHYSICAL COUNT%'
			AND ISNULL(O.[PURC_ORDER_ID], '') = '' THEN 'PHYSICAL COUNT ADJ'
	ELSE ''
	END AS FILTERS
	--, 'OT' AS MSG01
	--, I.*
	--, 'DIST' AS MSG02
	--, DIST.*
	--, 'IT' AS MSG03
	--, O.*
	--, 'TRACE IN' AS MSG04
	--, TI.*
	--, 'TRACE OUT' AS MSG05
	--, [TO].*
	--, 'PO' AS MSG06
	--, PO.*
		, I.PART_ID
		, I.WAREHOUSE_ID
		, I.LOCATION_ID
		, I.TRANSACTION_DATE AS ORIG_DATE
		, I.TRANSACTION_ID AS ORIG_TRANS
		, O.TRANSACTION_DATE AS IN_DATE
		, O.TRANSACTION_ID AS IN_TRANS
		, I.CUST_ORDER_ID AS IN_CO
		, I.PURC_ORDER_ID AS IN_PO
		, O.CUST_ORDER_ID AS ORIG_CO
		, O.PURC_ORDER_ID AS ORIG_PO
		, TI.TRACE_ID AS TRACE_IN
		, [TO].TRACE_ID AS TRACE_ORIG
		, PO1.VENDOR_ID AS IN_VENDOR
		, PO2.VENDOR_ID AS ORIG_VENDOR
		, DI.IN_TRANS_ID AS DI_INTRANS
		, DO.IN_TRANS_ID AS DO_INTRANS
		, DI.OUT_TRANS_ID 
	FROM INVENTORY_TRANS I
	LEFT OUTER JOIN INV_TRANS_DIST DI
		ON DI.IN_TRANS_ID = I.TRANSACTION_ID
	LEFT OUTER JOIN INV_TRANS_DIST DI
		ON DI.IN_TRANS_ID = I.TRANSACTION_ID
	LEFT OUTER JOIN INV_TRANS_DIST DO
		ON DO.OUT_TRANS_ID = I.TRANSACTION_ID
	LEFT OUTER JOIN INVENTORY_TRANS O
		ON DO.IN_TRANS_ID = O.TRANSACTION_ID
	LEFT OUTER JOIN TRACE_INV_TRANS T
		ON O.TRANSACTION_ID = T.TRANSACTION_ID
	LEFT OUTER JOIN PURCHASE_ORDER PO
		ON I.PURC_ORDER_ID = PO.ID
	WHERE I.WAREHOUSE_ID IN ('Auburn', 'Auburn Mtl Cage', 'Cargo Panels', 'Door Handles', 'FGA', 'P3', 'STDS')
--		AND I.WAREHOUSE_ID = 'Auburn Mtl Cage'
		AND I.TRANSACTION_DATE >= @STARTDATE

		AND (I.TRANSACTION_ID = '2780357' OR O.TRANSACTION_ID = '2780357')

	) X
WHERE X.FILTERS = ''
ORDER BY ORIG_TRANS






/*
--	AND PO.VENDOR_ID IS NULL
	--AND PO.ID ='124527'

Select * from INV_TRANS_DIST where IN_TRANS_ID in ('823471', '826508', '826636')

select * from INV_TRANS_DIST where OUT_TRANS_ID in ('878857')
--> INVENTORY


select * from inventory_trans where TRANSACTION_ID = '2780357'
select * from inventory_trans where TRANSACTION_ID = '878857'

select * from trace_inv_trans where TRANSACTION_ID = '878857'
--trace_id = '124527/1'

select * from INV_TRANS_DIST where IN_TRANS_ID in ('2820340')

select * from INV_TRANS_DIST where OUT_TRANS_ID in ('2820340')

--select * from INVENTORY_TRANS where TRANSACTION_ID in ('2592875', '2592877', '2592878', '2708990', '2714838', '2730316', '2822690')

SELECT * FROM PURCHASE_ORDER WHERE ID = '135220'
SELECT * FROM PURC_ORDER_LINE WHERE purc_order_ID = '45815'
*/