USE LIVE
GO

; WITH CTE_TRACE AS
(SELECT PART_ID
	, ID AS TRACE_ID
	, SUM(IN_QTY - OUT_QTY) AS TRACE_QTY
FROM TRACE
GROUP BY PART_ID
, ID
)

, CTE_TRACE_TOT AS
(SELECT PART_ID
	, SUM(IN_QTY - OUT_QTY) AS TRACE_TOT_QTY
FROM TRACE
GROUP BY PART_ID
)

, CTE_XCT AS
(SELECT PART_ID
	, TRACE_ID
	, SUM(QTY) AS TI_XCT_QTY
FROM TRACE_INV_TRANS
GROUP BY PART_ID
	, TRACE_ID
)

, CTE_XCT_TOT AS
(SELECT PART_ID
	, SUM(QTY) AS TI_XCT_TOT_QTY
FROM TRACE_INV_TRANS
GROUP BY PART_ID
)

, CTE_PL AS
(SELECT PART_ID
	, SUM(QTY) AS PL_TOT_QTY
FROM PART_LOCATION
GROUP BY PART_ID
)

, CTE_PW AS
(SELECT PART_ID
	, SUM([MIN_INV_QTY] + [COMMITTED_CO] + [COMMITTED_REQ] + [COMMITTED_PLREQ] + [COMMITTED_IBT] 
		+ [AVAILABLE_QTY] + [OUTBOUND_QTY] + [ON_HOLD_QTY] + [LOCKED_QTY] + [UNAVAILABLE_QTY]) AS PW_TOT_QTY
FROM PART_WAREHOUSE PW
GROUP BY PART_ID
)

, CTE_IB AS
(SELECT PART_ID
	, MAX(POSTING_DATE) AS POSTING_DATE
	, SUM(QTY) AS IB_TOT_QTY
FROM INVENTORY_BALANCE IB
WHERE POSTING_DATE > DATEADD(MONTH, DATEDIFF(MONTH, -1, GETDATE())-1, -1) 
GROUP BY PART_ID
)

, CTE_INV AS
(SELECT PART_ID
	, SUM(CASE
		WHEN TYPE = 'I' AND CLASS = 'R' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'I' THEN -1
		WHEN TYPE = 'O' AND CLASS = 'A' THEN -1
		WHEN TYPE = 'I' AND CLASS = 'A' THEN 1
		WHEN TYPE = 'I' AND CLASS = 'I' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'R' THEN -1
		ELSE 0
	END * QTY) AS INV_QTY
FROM INVENTORY_TRANS
GROUP BY PART_ID
)

SELECT CASE
		WHEN T.TRACE_QTY < 0 THEN 'NEGATIVE QTY'
		WHEN X.TI_XCT_QTY < 0 THEN 'NEGATIVE QTY'
		WHEN ISNULL(P.QTY_ON_HAND, 0) != ISNULL(PS.QTY_ON_HAND, 0) THEN 'P != PS' 
		WHEN ISNULL(P.QTY_ON_HAND, 0) != ISNULL(PW.PW_TOT_QTY, 0) THEN 'P != PW' 		
		WHEN ISNULL(PL.PL_TOT_QTY, 0) != ISNULL(PW.PW_TOT_QTY, 0) THEN 'PL != PW' 
		WHEN TP.PART_ID IS NULL THEN '' --> NO TRACE PROFILE
		WHEN ISNULL(TT.TRACE_TOT_QTY, 0) > ISNULL(C.TI_XCT_TOT_QTY, 0) THEN 'TRACE > XCT_TOT' 
		WHEN ISNULL(TT.TRACE_TOT_QTY, 0) < ISNULL(C.TI_XCT_TOT_QTY, 0) THEN 'TRACE < XCT_TOT' 
		WHEN ISNULL(I.INV_QTY, 0) != ISNULL(TT.TRACE_TOT_QTY, 0) THEN 'INV != TRACE_TOT'
		WHEN ISNULL(I.INV_QTY, 0) != ISNULL(C.TI_XCT_TOT_QTY, 0) THEN 'INV != XCT_TOT' 
		WHEN ISNULL(I.INV_QTY, 0) != ISNULL(P.QTY_ON_HAND, 0) THEN 'INV != ON_HAND' 
		WHEN ISNULL(X.TI_XCT_QTY, 0) != ISNULL(T.TRACE_QTY, 0) THEN 'TI_XCT != TRACE'
		ELSE ''
	END AS MSG 
	, P.ID
	, P.[STATUS]
	, P.QTY_ON_HAND AS P_QTY_ON_HAND
	, PS.QTY_ON_HAND AS PS_QTY_ON_HAND
	, ISNULL(PL.PL_TOT_QTY, 0) AS PL_TOT_QTY
	, ISNULL(PW.PW_TOT_QTY, 0) AS PW_TOT_QTY
	, ISNULL(IB.IB_TOT_QTY, 0) AS IB_TOT_QTY
	, ISNULL(I.INV_QTY, 0) AS INV_QTY
	, ISNULL(C.TI_XCT_TOT_QTY, 0) AS TI_XCT_TOT_QTY
	, ISNULL(TT.TRACE_TOT_QTY, 0) AS TRACE_TOT_QTY
	, ISNULL(T.TRACE_ID, '') AS TRACE_ID
	, ISNULL(T.TRACE_QTY, 0) AS TRACE_QTY
	, ISNULL(X.TI_XCT_QTY, 0) AS TI_XCT_QTY
FROM PART P
LEFT OUTER JOIN PART_SITE PS
	ON P.ID = PS.PART_ID
LEFT OUTER JOIN TRACE_PROFILE TP
	ON P.ID = TP.PART_ID
LEFT OUTER JOIN CTE_PL PL
	ON P.ID = PL.PART_ID
LEFT OUTER JOIN CTE_PW PW
	ON P.ID = PW.PART_ID
LEFT OUTER JOIN	CTE_IB IB
	ON P.ID = IB.PART_ID
LEFT OUTER JOIN CTE_INV I
	ON P.ID = I.PART_ID
LEFT OUTER JOIN CTE_TRACE T
	ON P.ID = T.PART_ID
LEFT OUTER JOIN CTE_XCT X
	ON P.ID = X.PART_ID
	AND X.TRACE_ID = T.TRACE_ID
LEFT OUTER JOIN CTE_XCT_TOT C
	ON P.ID = C.PART_ID
LEFT OUTER JOIN CTE_TRACE_TOT TT
	ON P.ID = TT.PART_ID
WHERE CASE
	WHEN T.TRACE_QTY < 0 THEN 'NEGATIVE QTY'
	WHEN X.TI_XCT_QTY < 0 THEN 'NEGATIVE QTY'
	WHEN ISNULL(P.QTY_ON_HAND, 0) != ISNULL(PS.QTY_ON_HAND, 0) THEN 'P != PS' 
	WHEN ISNULL(P.QTY_ON_HAND, 0) != ISNULL(PW.PW_TOT_QTY, 0) THEN 'P != PW' 		
	WHEN ISNULL(PL.PL_TOT_QTY, 0) != ISNULL(PW.PW_TOT_QTY, 0) THEN 'PL != PW' 
	WHEN TP.PART_ID IS NULL THEN '' --> NO TRACE PROFILE
	WHEN ISNULL(TT.TRACE_TOT_QTY, 0) > ISNULL(C.TI_XCT_TOT_QTY, 0) THEN 'TRACE > XCT_TOT' 
	WHEN ISNULL(TT.TRACE_TOT_QTY, 0) < ISNULL(C.TI_XCT_TOT_QTY, 0) THEN 'TRACE < XCT_TOT' 
	WHEN ISNULL(I.INV_QTY, 0) != ISNULL(TT.TRACE_TOT_QTY, 0) THEN 'INV != TRACE_TOT'
	WHEN ISNULL(I.INV_QTY, 0) != ISNULL(C.TI_XCT_TOT_QTY, 0) THEN 'INV != XCT_TOT' 
	WHEN ISNULL(I.INV_QTY, 0) != ISNULL(P.QTY_ON_HAND, 0) THEN 'INV != ON_HAND' 
	WHEN ISNULL(X.TI_XCT_QTY, 0) != ISNULL(T.TRACE_QTY, 0) THEN 'TI_XCT != TRACE'
	ELSE ''
END != ''
ORDER BY P.ID
	, T.TRACE_ID


/*
DECLARE @PART_ID NVARCHAR(50) = '20243E-32003'

SELECT I.TRANSACTION_ID
, I.TRANSACTION_DATE
, I.PART_ID
, I.WAREHOUSE_ID
, I.LOCATION_ID
, I.QTY
, I.[TYPE]
, I.[CLASS]
, CASE
	WHEN TYPE = 'I' AND CLASS = 'R' THEN 1
	WHEN TYPE = 'O' AND CLASS = 'I' THEN -1
	WHEN TYPE = 'O' AND CLASS = 'A' THEN -1
	WHEN TYPE = 'I' AND CLASS = 'A' THEN 1
	WHEN TYPE = 'I' AND CLASS = 'I' THEN 1
	WHEN TYPE = 'O' AND CLASS = 'R' THEN -1
	ELSE 0
END * I.QTY AS INV_QTY
, TI.QTY AS TRACE_QTY
, TI.TRACE_ID
, I.USER_ID
FROM INVENTORY_TRANS I
INNER JOIN PART P
ON P.ID = I.PART_ID
LEFT OUTER JOIN TRACE_INV_TRANS TI
ON I.TRANSACTION_ID = TI.TRANSACTION_ID
WHERE I.PART_ID = @PART_ID
ORDER BY TRANSACTION_ID DESC

SELECT * FROM TRACE WHERE PART_ID = '140T2101-2082'

SELECT * FROM TRACE_INV_TRANS WHERE TRACE_ID = '1665499/1'

SELECT * FROM INVENTORY_TRANS WHERE PART_ID = '140T2101-2082' ORDER BY TRANSACTION_DATE DESC
SELECT * FROM TRACE_INV_TRANS WHERE PART_ID = '140T2101-2082' ORDER BY TRACE_ID
SELECT * FROM TRACE WHERE PART_ID = '140T2101-2082' ORDER BY ID

SELECT * FROM TRACE_INV_TRANS WHERE TRACE_ID = '1665499/1'

UPDATE TRACE 
SET IN_QTY = 12
WHERE ID = '1665409/1'

DELETE FROM TRACE WHERE ID = '1665499/1'

--> TYPO CORRECTION:
DECLARE @PART_ID NVARCHAR(50) = '140T2101-2082'
DECLARE @CORRECT_TRACEID NVARCHAR(50) = '1665409/1'
DECLARE @BAD_TRACEID NVARCHAR(50) = '1665499/1'
DECLARE @TRANSID NVARCHAR(20) = '3022293'
DECLARE @IN_QTY NVARCHAR(20) = '6'
DECLARE @OUT_QTY NVARCHAR(20) = '6'
DECLARE @INV_DATE DATETIME = (SELECT TRANSACTION_DATE FROM INVENTORY_TRANS WHERE TRANSACTION_ID IN (@TRANSID))

--> CREATE CORRECT TRACE_ID
INSERT INTO LIVE.dbo.TRACE (PART_ID, ID, NUMBERING_ID, OUT_QTY, IN_QTY, REPORTED_QTY, ASSIGNED_QTY, APROPERTY_1, APROPERTY_2, APROPERTY_3, APROPERTY_4, APROPERTY_5, NPROPERTY_1, NPROPERTY_2, NPROPERTY_3, NPROPERTY_4, NPROPERTY_5, COMMENTS, EXPIRATION_DATE, CREATE_DATE, DISP_IN_QTY, DISP_OUT_QTY, UNAVAILABLE_QTY, OWNER_ID, LOT_ID, SERIAL_ID, COMMITTED_QTY, PRODUCTION_DATE, RECEIVE_BY_DATE, AVAILABLE_DATE, SHIP_BY_DATE, SITE_ID)
	VALUES (@PART_ID, @CORRECT_TRACEID, @PART_ID, @OUT_QTY, @IN_QTY, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @INV_DATE, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

--> CORRECT TRACE TRANSACTION RECORD
UPDATE TRACE_INV_TRANS
SET TRACE_ID = '1665409/1'
WHERE TRANSACTION_ID IN ('3022293')
AND PART_ID = '140T2101-2082'

--> ZERO OUR BAD TRACE_ID
UPDATE TRACE
SET OUT_QTY = 1540
, IN_QTY = 1540
WHERE ID IN ('20252631')
AND PART_ID = '7075T73511FB-2.00X4.00X144 CMP'



*/