USE SANDBOX_Baseline_App
GO

SELECT P.PREVENTIVE
	, P.ERP_ID2
	, P.COMPONENT_NUMBER
	, EC.[NAME] AS PM_ACT_TYPE
	, CASE 
		WHEN P.RESULT = 'F' THEN 'Failed'
		WHEN P.RESULT = 'PA' THEN 'Passed'
		WHEN P.RESULT = 'PE' THEN 'Pending'
		WHEN P.RESULT = 'S' THEN 'Status'
		ELSE 'ISSUES'
	END AS RESULT
	, P.DUE_DATE
	, E.EQUIPMENT_ID
	, E.[NAME] AS EQUIP_NAME
	, E.MAJOR_LOCATION
	, MAJ.[DESCRIPTION] AS MAJOR_DESC
	, E.MINOR_LOCATION
	, MIL.[DESCRIPTION] AS MINOR_DESC
	, E.BUSINESS_UNIT_ID
	, E.COMMENTS
	, ISNULL(C.INSTRUCTIONS, EC.INSTRUCTIONS) AS INSTRUCTIONS
FROM [dbo].[VQ_PREVENTIVE] P
LEFT OUTER JOIN [dbo].[VQ_EQUIPMENT] E
	ON P.[EQUIPMENT_REC_ID] = E.[RECORD_ID]
LEFT OUTER JOIN [dbo].[VQ_EQUP_TYPE_COMP] EC
	ON E.[EQUIPMENT_TYPE_REC_ID] = EC.[EQUIPMENT_TYPE_REC_ID]
	AND P.COMPONENT_NUMBER = EC.COMPONENT_NUMBER
LEFT OUTER JOIN [dbo].[VQ_COMPONENTS] C
	ON P.[EQUIPMENT_REC_ID] = C.[EQUIPMENT_REC_ID]
	AND P.COMPONENT_NUMBER = C.COMPONENT_NUMBER
LEFT OUTER JOIN [dbo].[VQ_MAJOR_LOCATION] MAJ
	ON E.MAJOR_LOCATION = MAJ.MAJOR_LOCATION
LEFT OUTER JOIN [dbo].[VQ_MINOR_LOCATION] MIL
	ON E.MINOR_LOCATION = MIL.MINOR_LOCATION
WHERE P.PREVENTIVE IN (RIGHT('000000' + @PM, 7))
--WHERE ISNULL(EC.INSTRUCTIONS, '') != ISNULL(C.INSTRUCTIONS, '')
