use SANDBOX_Baseline_App
go

SELECT NCM_ID
	, NCM.SITE_ID
	, PO.DISPLAY_ID AS PRODUCTION_ORDER_ID
	, NCM.MADE_BY_EMP_REC_ID
	, MADE_EE.EMPLOYEE_ID + ' - ' +	MADE_EE.FIRST_NAME + ' ' + MADE_EE.LAST_NAME AS MADE_BY_EE
	, ASSGN_EE.EMPLOYEE_ID + ' - ' + ASSGN_EE.FIRST_NAME + ' ' + ASSGN_EE.LAST_NAME AS ASSGN_TO_EE
	, NCM.LOT_SIZE
	, NCM.REJECTED
	, P.PRODUCT_ID
FROM VQ_NONCONFORMANCE NCM
LEFT OUTER JOIN VQ_PRODUCT P
	ON P.RECORD_ID = NCM.PRODUCT_REC_ID
LEFT OUTER JOIN VQ_PRODUCTION_ORDER PO
	ON PO.RECORD_ID = NCM.PROD_ORDER_REC_ID
LEFT OUTER JOIN VQ_EMPLOYEE MADE_EE
	ON MADE_EE.RECORD_ID = NCM.MADE_BY_EMP_REC_ID
LEFT OUTER JOIN VQ_EMPLOYEE ASSGN_EE
	ON ASSGN_EE.RECORD_ID = NCM.ASSIGNED_TO_REC_ID
WHERE NCM.NCM_ID = @NCM_ID
	AND NCM.SITE_ID = @SITE_ID
