use SANDBOX_Baseline_App
go

SELECT NCM_ID
	, NCM.RECORD_ID
	, NCM.SITE_ID
	, PO.DISPLAY_ID AS PRODUCTION_ORDER_ID
	, NCM.PO_NUMBER AS VENDOR_PO_NUM
	, O.DISPLAY_ID AS OPERATION_ID
	, O.NEXT_ID AS [NEXT_OPERATION_ID]
	, O.CONST_RESOURCE_ID
	, NCM.REFERENCE_5 AS [CUSTOMER_REFERENCE]
	, MADE_EE.EMPLOYEE_ID + ' - ' + MADE_EE.FIRST_NAME + ' ' + MADE_EE.LAST_NAME AS MADE_BY_EE_NAME
	, ASSGN_EE.EMPLOYEE_ID + ' - ' + ASSGN_EE.FIRST_NAME + ' ' + ASSGN_EE.LAST_NAME AS ASSGN_BY_EE_NAME
	, NCM.LOT_NUMBER AS CERT_NUM
	, NCM.LOT_SIZE
	, NCM.ACCEPTED
	, NCM.REJECTED
	, NCM.NCM_TYPE
	, NCM.NCM_DATE
	, NCM.[STATUS]
	, NCM.CLOSED_DATE
	, NCM.DUE_DATE
	, NCM.BUSINESS_UNIT_ID
	, P.PRODUCT_ID
	, P.[NAME] AS PROD_ID_NAME
	, NCM.REFERENCE_1 AS [SPEC_SECT]
	, NCM.REFERENCE_2 AS [DRAW_REF]
	, NCM.REFERENCE_3 AS [ASIS_DIM]
	, NCM.REFERENCE_4 AS [SHOULD_BE_DIM]
	, NCM.[DESCRIPTION] AS NCM_DESC
	, ISNULL(NCM.USER_DEFINED_1, NCM.USER_DEFINED_5) AS [PROCESS]
	, ISNULL(NCM.USER_DEFINED_2, NCM.USER_DEFINED_6) AS [SUBPROCESS]
	, NCM.USER_DEFINED_3 AS [CATEGORY]
	, ISNULL(NCM.USER_DEFINED_4, NCM.USER_DEFINED_7) AS [DEFECT]
	, NCM.DISPOSITION_TYPE
	, DT.[DESCRIPTION] AS DISP_DESC
	, NCM.DISP_DATE
	, NCM.DISP_DUE_DATE
	, NCM.DISP_STATUS
	, NCM.DISP_CLOSED_DATE
	, DISP_ASSG.EMPLOYEE_ID + ' - ' + DISP_ASSG.FIRST_NAME + ' ' + DISP_ASSG.LAST_NAME AS DISP_ASSG_BY_EE_NAME
	, DISP_EE.EMPLOYEE_ID + ' - ' + DISP_EE.FIRST_NAME + ' ' + DISP_EE.LAST_NAME AS DISP_BY_EE_NAME
	, NCM.REFERENCE_6 AS [REWORK_QTY]
	, NCM.REFERENCE_7 AS [SCRAP_QTY]
	, NCM.REFERENCE_8 AS [OVERAGE_QTY]
	, NCM.REFERENCE_9 AS [RETURN_QTY]
	, NCM.REFERENCE_10 AS [ASIS_QTY]
	, NCM.DISPOSITION
FROM VQ_NONCONFORMANCE NCM
LEFT OUTER JOIN VQ_PRODUCT P
	ON P.RECORD_ID = NCM.PRODUCT_REC_ID
LEFT OUTER JOIN VQ_PRODUCTION_ORDER PO
	ON PO.RECORD_ID = NCM.PROD_ORDER_REC_ID
LEFT OUTER JOIN VQ_OPERATION O
	ON O.RECORD_ID = NCM.OPERATION_REC_ID
LEFT OUTER JOIN VQ_DISPOSITION_TYPE DT
	ON DT.[DISPOSITION_TYPE] = NCM.[DISPOSITION_TYPE]
LEFT OUTER JOIN VQ_EMPLOYEE MADE_EE
	ON MADE_EE.RECORD_ID = NCM.MADE_BY_EMP_REC_ID
LEFT OUTER JOIN VQ_EMPLOYEE ASSGN_EE
	ON ASSGN_EE.RECORD_ID = NCM.ASSIGNED_TO_REC_ID
LEFT OUTER JOIN VQ_EMPLOYEE DISP_EE
	ON DISP_EE.RECORD_ID = NCM.DISP_EMP_REC_ID
LEFT OUTER JOIN VQ_EMPLOYEE DISP_ASSG
	ON DISP_ASSG.RECORD_ID = NCM.DISP_ASSG_TO_REC_ID
WHERE NCM.SITE_ID = @SITE_ID
	AND NCM.NCM_ID IN (@NCM_ID)
	AND @START_DATE >= NCM_DATE
	AND @END_DATE <= NCM_DATE
	AND NCM_TYPE IN (@NCMTYPE)
	AND NCM.[STATUS] IN (@NCMSTATUS)
	AND NCM.BUSINESS_UNIT_ID IN (@BUSSTREAM)
	AND PRODUCT_ID IN (@PRODUCTID)
	AND ISNULL(NCM.USER_DEFINED_1, NCM.USER_DEFINED_5) IN (@PROCESS)
	AND ISNULL(NCM.USER_DEFINED_2, NCM.USER_DEFINED_6) IN (@SUBPROCESS)
	AND NCM.DISPOSITION_TYPE IN (@DISPTYPE)
	AND DISP_STATUS IN (@DISPSTATUS)


SELECT PRODUCT_ID
FROM VQ_PRODUCT
GROUP BY PRODUCT_ID
ORDER BY PRODUCT_ID


