use SANDBOX_Baseline_App
go

--IQM Report > Tags not Closed
SELECT NCM_ID
	, PO.DISPLAY_ID AS PRODUCTION_ORDER_ID
	, NCM.PO_NUMBER AS VENDOR_PO_NUM
	, O.DISPLAY_ID AS OPERATION_ID
	, MADE_EE.EMPLOYEE_ID AS MADE_BY_EEID
	, MADE_EE.FIRST_NAME AS MADE_BY_EE_FNAME
	, MADE_EE.LAST_NAME AS MADE_BY_EE_LNAME
	, NCM.LOT_SIZE
	, NCM.ACCEPTED
	, NCM.REJECTED
	, NCM.NCM_TYPE
	, NCM.NCM_DATE
	, ISNULL(NCM.[STATUS], '_BLANK') AS [STATUS]
	, NCM.CLOSED_DATE
	, NCM.DUE_DATE
	, P.PRODUCT_ID
	, ISNULL(NCM.USER_DEFINED_1, NCM.USER_DEFINED_5) AS [PROCESS]
	, ISNULL(NCM.USER_DEFINED_2, NCM.USER_DEFINED_6) AS [SUBPROCESS]
	, NCM.USER_DEFINED_3 AS [CATEGORY]
	, ISNULL(NCM.USER_DEFINED_4, NCM.USER_DEFINED_7) AS [DEFECT]
	, NCM.DISPOSITION_TYPE
	, DT.[DESCRIPTION] AS DISP_DESC
	, NCM.DISP_DATE
	, NCM.REFERENCE_6 AS [REWORK_QTY]
	, NCM.REFERENCE_7 AS [SCRAP_QTY]
	, NCM.REFERENCE_8 AS [OVERAGE_QTY]
	, NCM.REFERENCE_9 AS [RETURN_QTY]
	, NCM.REFERENCE_10 AS [ASIS_QTY]
FROM VQ_NONCONFORMANCE NCM
LEFT OUTER JOIN VQ_PRODUCT P
	ON P.RECORD_ID = NCM.PRODUCT_REC_ID
LEFT OUTER JOIN VQ_PRODUCTION_ORDER PO
	ON PO.RECORD_ID = NCM.PROD_ORDER_REC_ID
LEFT OUTER JOIN VQ_OPERATION O
	ON O.RECORD_ID = NCM.OPERATION_REC_ID
LEFT OUTER JOIN VQ_DISPOSITION_TYPE DT
	ON DT.[DISPOSITION_TYPE] = NCM.[DISPOSITION_TYPE]
LEFT OUTER JOIN VQ_EMPLOYEE MADE_EE
	ON MADE_EE.RECORD_ID = NCM.MADE_BY_EMP_REC_ID
WHERE NCM.NCM_DATE >= @StartDate
	AND NCM.NCM_DATE <= @EndDate
	AND NCM.[STATUS] IN (@Status)

SELECT DISTINCT ISNULL(NCM.[STATUS], '_BLANK') AS [STATUS]
FROM VQ_NONCONFORMANCE NCM
ORDER BY ISNULL(NCM.[STATUS], '_BLANK')

