
-- QUALITY > DEPARTMENT DEFECTS
SELECT NCM_ID
	, PS.BUYER_USER_ID
	, P.PRODUCT_ID
	, PO.DISPLAY_ID AS PRODUCTION_ORDER_ID
	, CO.CUSTOMER_ID
	, NCM.PO_NUMBER AS VENDOR_PO_NUM
	, O.DISPLAY_ID AS OPERATION_ID
	, MADE_EE.EMPLOYEE_ID AS MADE_BY_EEID
	, MADE_EE.FIRST_NAME AS MADE_BY_EE_FNAME
	, MADE_EE.LAST_NAME AS MADE_BY_EE_LNAME
	, NCM.LOT_SIZE
	, NCM.ACCEPTED
	, NCM.REJECTED
	, NCM.NCM_DATE
	, NCM.DUE_DATE
	, NCM.REFERENCE_1 AS [SPEC_SECT]
	, NCM.REFERENCE_2 AS [DRAW_REF]
	, NCM.REFERENCE_3 AS [ASIS_DIM]
	, NCM.REFERENCE_4 AS [SHOULD_BE_DIM]
	, COALESCE(NCM.SK_FIN_NCM_PROCESS, NCM.SK_MFG_NCM_PROCESS, '_BLANK') AS [PROCESS]
	, COALESCE(NCM.SK_FIN_NCM_SUBPROCESS, NCM.SK_MFG_NCM_SUBPROCESS, '_BLANK') AS [SUBPROCESS]
	, NCM.USER_DEFINED_3 AS [CATEGORY]
	, ISNULL(NCM.USER_DEFINED_4, NCM.USER_DEFINED_7) AS [DEFECT]
	, NCM.DISPOSITION_TYPE
	, DT.[DESCRIPTION] AS DISP_DESC
	, NCM.DISP_DATE
	, NCM.REFERENCE_6 AS [REWORK_QTY]
	, NCM.REFERENCE_7 AS [SCRAP_QTY]
	, NCM.REFERENCE_8 AS [OVERAGE_QTY]
	, NCM.REFERENCE_9 AS [RETURN_QTY]
	, NCM.REFERENCE_10 AS [ASIS_QTY]
	, NCM.DISPOSITION
FROM VQ_NONCONFORMANCE NCM
LEFT OUTER JOIN VQ_PRODUCT P
	ON P.RECORD_ID = NCM.PRODUCT_REC_ID
LEFT OUTER JOIN VQ_PRODUCTION_ORDER PO
	ON PO.RECORD_ID = NCM.PROD_ORDER_REC_ID
LEFT OUTER JOIN VQ_OPERATION O
	ON O.RECORD_ID = NCM.OPERATION_REC_ID
LEFT OUTER JOIN VQ_DISPOSITION_TYPE DT
	ON DT.[DISPOSITION_TYPE] = NCM.[DISPOSITION_TYPE]
LEFT OUTER JOIN VQ_EMPLOYEE MADE_EE
	ON MADE_EE.RECORD_ID = NCM.MADE_BY_EMP_REC_ID
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.SUPPLY_BASE_ID = PO.ALT_ID_2
	AND DSL.SUPPLY_LOT_ID = PO.ALT_ID_3
	AND DSL.SUPPLY_TYPE = 'WO'
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON DSL.DEMAND_BASE_ID = CO.ID
	AND DSL.DEMAND_TYPE = 'CO'
LEFT OUTER JOIN PART_SITE PS
	ON PS.PART_ID = P.PRODUCT_ID
WHERE COALESCE(NCM.SK_FIN_NCM_PROCESS, NCM.SK_MFG_NCM_PROCESS, '_BLANK') IN (@PROCESS)
	AND NCM.NCM_DATE >= @StartDate
	AND NCM.NCM_DATE <= @EndDate