SELECT CO.CUSTOMER_ID 
	, CO.ID AS CO_ID
	, COL.LINE_NO
	, COL.PART_ID AS CO_PART
	, COL.ORDER_QTY AS CO_QTY
	, WO.PART_ID AS WO_PART
	, WO.DESIRED_QTY AS WO_QTY
	, LT.TRANSACTION_ID
	, LT.TRANSACTION_DATE
	, LT.WORKORDER_BASE_ID AS BASE
	, LT.WORKORDER_LOT_ID AS LOT
	, LT.WORKORDER_SPLIT_ID AS SPLIT
	, LT.WORKORDER_SUB_ID AS SUB
	, LT.OPERATION_SEQ_NO AS SEQ_NO
	, CASE
		WHEN LT.[TYPE] = 'I' THEN 'INDIRECT'
		ELSE 'DIRECT'
	END AS LABOR_TYPE
	, LT.EMPLOYEE_ID
	, EE.FIRST_NAME
	, EE.LAST_NAME
	, ADP.[REPORTS TO NAME] AS EE_SUPRTVISOR
	, LT.DEPARTMENT_ID
	, LT.CLOCK_IN
	, LT.CLOCK_OUT
	, LT.HOURS_WORKED
	, LT.GOOD_QTY
	, LT.BAD_QTY
	, LT.[DESCRIPTION] AS LT_DESC
	, LT.RESOURCE_ID
	, LT.ACT_LABOR_COST
	, LT.ACT_BURDEN_COST
	, SR.USER_4 AS FL_SUPERVISOR
	, SR.USER_5 AS FACILITY
	, SR.USER_8 AS DEPARTMENT
	, P.[DESCRIPTION] AS PART_DESC
	, P.BUYER_USER_ID
	, P.PLANNER_USER_ID
	, P.COMMODITY_CODE
FROM LABOR_TICKET LT
LEFT OUTER JOIN SHOP_RESOURCE SR
ON LT.RESOURCE_ID = SR.ID
LEFT OUTER JOIN EMPLOYEE EE
	ON EE.ID = LT.EMPLOYEE_ID
LEFT OUTER JOIN [SQL-LAB-2].LIVESUPPLEMENTAL.dbo.ADP_EMP ADP
	ON CONVERT(NVARCHAR(15), RIGHT('0000' + LT.EMPLOYEE_ID, 6)) = ADP.[File Number]
LEFT OUTER JOIN WORK_ORDER WO
	ON WO.[TYPE] = LT.WORKORDER_TYPE
	AND WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
LEFT OUTER JOIN PART P
	ON P.ID = WO.PART_ID
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
ON DSL.SUPPLY_TYPE = 'WO'
AND DSL.SUPPLY_BASE_ID = LT.WORKORDER_BASE_ID
AND DSL.SUPPLY_LOT_ID = LT.WORKORDER_LOT_ID
AND DSL.SUPPLY_SPLIT_ID = LT.WORKORDER_SPLIT_ID
AND DSL.SUPPLY_SUB_ID = LT.WORKORDER_SUB_ID
AND LT.WORKORDER_TYPE = 'W'
LEFT OUTER JOIN CUST_ORDER_LINE COL
ON DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
LEFT OUTER JOIN CUSTOMER_ORDER CO
ON COL.CUST_ORDER_ID = CO.ID
WHERE LT.TRANSACTION_DATE >= @STARTDATE
AND LT.TRANSACTION_DATE <= @ENDDATE
AND CO.CUSTOMER_ID IN (@CUST_ID)
AND ADP.[REPORTS TO NAME] IN (@SUPERVISOR)
