USE DataWarehouse
GO

DECLARE @COID NVARCHAR(20) = '001689810'

SELECT * FROM SHIPPER WHERE CUST_ORDER_ID = @COID

SELECT * FROM SHIPPER_LINE WHERE CUST_ORDER_ID = @COID

SELECT * FROM INVENTORY_TRANS 
--WHERE TRANSACTION_ID IN ('2891105', '2850893')
WHERE CUST_ORDER_ID = @COID
--AND CUST_ORDER_LINE_NO = '1'
ORDER BY TRANSACTION_DATE DESC

--SELECT * FROM INVENTORY_TRANS WHERE TRANSACTION_ID = '2728390'
SELECT * FROM TRACE_INV_TRANS WHERE TRANSACTION_ID IN (SELECT TRANSACTION_ID FROM INVENTORY_TRANS 
WHERE CUST_ORDER_ID = @COID
AND CUST_ORDER_LINE_NO = '1'
)
--IN ('2891246', '2891248')

SELECT * FROM INV_TRANS_DIST 
WHERE OUT_TRANS_ID IN (SELECT TRANSACTION_ID FROM INVENTORY_TRANS 
WHERE CUST_ORDER_ID = @COID
AND CUST_ORDER_LINE_NO = '1'
)
--('2891246', '2891248') --, '2798100', '2764913')
--OR IN_TRANS_ID IN ('2891246', '2891248', '2798100', '2764913')

SELECT CASE 
		WHEN DSL.SUPPLY_BASE_ID IS NULL THEN 'UNLINKED'
		ELSE  'LINKED'
	END AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, SL.SHIPPED_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
	, WO.ACT_BURDEN_COST
	, WO.ACT_MATERIAL_COST
	, WO.ACT_LABOR_COST
	, WO.ACT_SERVICE_COST
FROM DATAWAREHOUSE.dbo.SHIPPER_LINE SL
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
LEFT OUTER JOIN DATAWAREHOUSE.dbo.RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND SL.PACKLIST_ID = RL.PACKLIST_ID 
	AND SL.LINE_NO = RL.PACKLIST_LINE_NO 
	AND RL.PACKLIST_ID IS NOT NULL
LEFT OUTER JOIN DATAWAREHOUSE.dbo.RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
LEFT OUTER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
	AND T.QTY != 0
LEFT OUTER JOIN INVENTORY_TRANS ITOUT
	ON SL.TRANSACTION_ID = ITOUT.TRANSACTION_ID
LEFT OUTER JOIN INV_TRANS_DIST ITD
	ON ITOUT.TRANSACTION_ID = ITD.OUT_TRANS_ID
LEFT OUTER JOIN INVENTORY_TRANS ITIN
	ON ITIN.TRANSACTION_ID = ITD.IN_TRANS_ID
LEFT OUTER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
--	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID + '.' + WO.SPLIT_ID)
	ON ITIN.WORKORDER_BASE_ID = WO.BASE_ID
	AND ITIN.WORKORDER_LOT_ID = WO.LOT_ID
	AND ITIN.WORKORDER_SPLIT_ID = WO.SPLIT_ID
	AND ITIN.WORKORDER_SUB_ID = WO.SUB_ID
	AND ITIN.WORKORDER_TYPE = WO.[TYPE]
	AND WO.DESIRED_QTY <> 0
	AND WO.SUB_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE (1 = 1)
--	AND RL.PACKLIST_ID IS NOT NULL
--	AND S.SHIPPED_DATE >= @START
	AND COL.PART_ID IS NOT NULL
	AND SL.SHIPPED_QTY <> 0
--	AND DSL.SUPPLY_BASE_ID IS NOT NULL
	AND COL.ORDER_QTY > 0

	AND CO.ID = @COID