use Live
go

SELECT CREATE_DATE
	, TRANSACTION_ID
	, TRANSACTION_DATE
	, CLOCK_IN
	, CLOCK_OUT
	, EMPLOYEE_ID
	, [USER_ID]
	, [DESCRIPTION]
	, WORKORDER_BASE_ID
	, RESOURCE_ID
	, OPERATION_SEQ_NO
	, HOURS_WORKED
	, GOOD_QTY
	, BAD_QTY
FROM LABOR_TICKET 
WHERE TRANSACTION_DATE > GETDATE()-3
AND BAD_QTY <> 0
	--OR CLOCK_IN > GETDATE()
	--OR CLOCK_OUT > GETDATE()
	order by resource_id
