USE LIVESupplemental
GO

DROP TABLE LIVESupplemental.dbo.[TransitTimes]

SELECT O.WORKORDER_TYPE
, O.WORKORDER_BASE_ID
, O.WORKORDER_LOT_ID
, O.WORKORDER_SPLIT_ID
, O.WORKORDER_SUB_ID
, O.SEQUENCE_NO
, O.RESOURCE_ID
, O.TRANSIT_DAYS
, T.*
FROM LIVESupplemental.dbo.[TransitTimes] T
INNER JOIN LIVE.dbo.OPERATION O
ON O.WORKORDER_TYPE = 'M'
AND O.WORKORDER_BASE_ID = T.WORKORDER_BASE_ID
AND O.WORKORDER_LOT_ID = T.WORKORDER_LOT_ID
AND O.WORKORDER_SUB_ID = T.WORKORDER_SUB_ID
AND O.SEQUENCE_NO = T.SEQUENCE_NO
--AND O.RESOURCE_ID = 'CONTRACTOR'
--WHERE O.WORKORDER_BASE_ID IS NULL

/*
USE LIVE
GO

UPDATE OPERATION
SET TRANSIT_DAYS = T.TRANSIT_DAYS
--select *
FROM LIVE.dbo.OPERATION O
INNER JOIN LIVESupplemental.dbo.[TransitTimes] T
ON O.WORKORDER_TYPE = 'M'
AND O.WORKORDER_BASE_ID = T.WORKORDER_BASE_ID
AND O.WORKORDER_LOT_ID = T.WORKORDER_LOT_ID
AND O.WORKORDER_SUB_ID = T.WORKORDER_SUB_ID
AND O.SEQUENCE_NO = T.SEQUENCE_NO
--(3768 rows affected)

*/