USE LIVE
GO

SELECT * FROM [LIVESupplemental].dbo.[OpUpdate20210406] U
-- 84472 RECORDS

SELECT U.BASE_ID
	, U.LOT_ID
	, U.SUB_ID
	, U.[GLOBAL_RANK]
	, WO.TYPE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
FROM [LIVESupplemental].dbo.[OpUpdate20210406] U
--INNER JOIN WORK_ORDER WO
LEFT OUTER JOIN WORK_ORDER WO
	ON WO.TYPE = 'M'
	AND WO.BASE_ID = U.BASE_ID
	AND WO.LOT_ID	= U.LOT_ID
	AND WO.SPLIT_ID = '0'
	AND WO.SUB_ID = U.SUB_ID
WHERE WO.BASE_ID IS NOT NULL
--> tt20210406: 83976 records 

/*
BEGIN TRANSACTION;
UPDATE WORK_ORDER     
SET [GLOBAL_RANK] = CONVERT(SMALLINT, T.[GLOBAL_RANK])
--SELECT *
FROM WORK_ORDER WO
INNER JOIN [LIVESupplemental].dbo.[OpUpdate20210406] T
	ON WO.TYPE = 'M'
	AND WO.BASE_ID = T.BASE_ID
	AND WO.LOT_ID	= T.LOT_ID
	AND WO.SPLIT_ID = '0'
	AND WO.SUB_ID = T.SUB_ID
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

*/

SELECT X.BASE_ID
	, X.LOT_ID
	, X.SUB_ID
	, X.[GLOBAL_RANK]
	, WO.TYPE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
FROM [LIVESupplemental].dbo.[OpUpdate20210406] X
--INNER JOIN WORK_ORDER WO
LEFT OUTER JOIN WORK_ORDER WO
	ON WO.TYPE = 'M'
	AND WO.BASE_ID = X.BASE_ID
	AND WO.LOT_ID	= X.LOT_ID
	AND WO.SPLIT_ID = '0'
	AND WO.SUB_ID = X.SUB_ID
WHERE WO.[GLOBAL_RANK] != X.[GLOBAL_RANK]
--> tt20210419: 2828 records TOTAL

