USE [LIVESupplemental]
GO

/****** Object:  Table [dbo].[UDFUpd20211028]    Script Date: 10/28/2021 10:12:20 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--CREATE TABLE [dbo].[UDFUpd20211028](
--	[DOCUMENT_ID] [nvarchar](50) NULL,
--	[WORKORDER_TYPE] [nvarchar](5) NULL,
--	[WORKORDER_BASE_ID] [nvarchar](50) NULL,
--	[WORKORDER_SUB_ID] [nvarchar](5) NULL,
--	[WORKORDER_LOT_ID] [nvarchar](5) NULL,
--	[WORKORDER_SPLIT_ID] [nvarchar](5) NULL,
--	[SEQUENCE_NO] [nvarchar](5) NULL
--) ON [PRIMARY]
--GO

SELECT * 
FROM LIVESupplemental.dbo.UDFUpd20211028 U
LEFT OUTER JOIN LIVE.dbo.OPERATION O
ON U.WORKORDER_TYPE = O.WORKORDER_TYPE
AND U.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
AND U.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
AND U.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
AND U.WORKORDER_SUB_ID = O.WORKORDER_SUB_ID
AND U.SEQUENCE_NO = O.SEQUENCE_NO
--> 29271 ROWS

SELECT O.WORKORDER_BASE_ID
, T.* 
, UDF.*
FROM LIVESupplemental.dbo.UDFUpd20211028 T
LEFT OUTER JOIN LIVE.dbo.USER_DEF_FIELDS UDF (NOLOCK)
	ON T.DOCUMENT_ID = UDF.DOCUMENT_ID 
LEFT OUTER JOIN LIVE.dbo.OPERATION O
	ON T.WORKORDER_TYPE = O.WORKORDER_TYPE
	AND T.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
	AND T.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
	AND T.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND T.WORKORDER_SUB_ID = O.WORKORDER_SUB_ID
	AND T.SEQUENCE_NO = O.SEQUENCE_NO
--WHERE UDF.PROGRAM_ID = 'VMMFGWIN_OP'
--> 38519 ROWS

/*
BEGIN TRANSACTION;
DELETE FROM LIVE.dbo.USER_DEF_FIELDS 
WHERE PROGRAM_ID = 'VMMFGWIN_OP'
AND DOCUMENT_ID IN (SELECT DOCUMENT_ID FROM LIVESupplemental.dbo.UDFUpd20211028 U)
--> 38519 ROWS DELETED
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

