USE LIVE
GO

; WITH CTE_WOS AS
(SELECT PART_ID
, MAX(CLOSE_DATE) AS LAST_CLOSE_DATE
FROM WORK_ORDER WO
GROUP BY PART_ID
)

SELECT WO.PART_ID
, P.[STATUS] AS PART_STATUS
, P.PLANNER_USER_ID
, WO.[STATUS] AS WO_STATUS
, [TYPE]
, BASE_ID
, LOT_ID
, SPLIT_ID
, SUB_ID
, WO.CREATE_DATE
, CTE.LAST_CLOSE_DATE
, DATEDIFF(MONTH, ISNULL(CTE.LAST_CLOSE_DATE, WO.CREATE_DATE), GETDATE()) / 12.0 AS TIMELAPSE
FROM WORK_ORDER WO
LEFT OUTER JOIN PART P
ON WO.PART_ID = P.ID
LEFT OUTER JOIN CTE_WOS CTE
ON CTE.PART_ID = WO.PART_ID
WHERE WO.[TYPE] = 'M'
AND DATEDIFF(MONTH, ISNULL(CTE.LAST_CLOSE_DATE, WO.CREATE_DATE), GETDATE()) / 12.0 > 1