USE LIVE908SP4
GO

--> DELETE THESE WORK ORDERS
SELECT * FROM [dbo].[Update20210301] U
--> 20,797 records

--> WORK ORDERS:
SELECT * FROM CO_PRODUCT CO
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE CO.WORKORDER_BASE_ID = U.BASEID
		AND CO.WORKORDER_LOT_ID = U.LOT
		AND CO.WORKORDER_SPLIT_ID = U.SPLIT
		AND CO.WORKORDER_SUB_ID = U.SUB
		AND CO.WORKORDER_TYPE = 'M'
)
--> 16 RECORDS

SELECT * FROM CUST_ORDER_ALLOC X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.BASE_ID = U.BASEID
		AND X.LOT_ID = U.LOT
		AND X.SPLIT_ID = U.SPLIT
--		AND X.SUB_ID = U.SUB
--		AND X.[TYPE] = 'M'
)
--> 0 RECORDS

SELECT * FROM DEMAND_SUPPLY_LINK X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.DEMAND_BASE_ID = U.BASEID
		AND X.DEMAND_LOT_ID = U.LOT
		AND X.DEMAND_SPLIT_ID = U.SPLIT
		AND X.DEMAND_SUB_ID = U.SUB
--		AND X.[TYPE] = 'M'
)
--> 0 RECORDS

SELECT * FROM DEMAND_SUPPLY_LINK X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.SUPPLY_BASE_ID = U.BASEID
		AND X.SUPPLY_LOT_ID = U.LOT
		AND X.SUPPLY_SPLIT_ID = U.SPLIT
		AND X.SUPPLY_SUB_ID = U.SUB
--		AND X.[TYPE] = 'M'
)
--> 0 RECORDS

SELECT * FROM DOCUMENT_REF_WO X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 75180 RECORDS

SELECT * FROM EC_LINE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WO_BASE_ID = U.BASEID
		AND X.WO_LOT_ID = U.LOT
		AND X.WO_SPLIT_ID = U.SPLIT
--		AND X.WO_SUB_ID = U.SUB
		AND X.WO_TYPE = 'M'
)
--> 2423 RECORDS

SELECT * FROM INSPECTION_ORDER X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM INVENTORY_TRANS X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM INVENTORY_TRANS_GOOD X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM LABOR_TICKET X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM OPERATION X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 360,175 RECORDS

SELECT * FROM OPERATION_BINARY X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 359,936 RECORDS

SELECT * FROM OPERATION_SCHED X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM PAYABLE_LINE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM PURC_REQ_LINE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
--		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM REQUIREMENT X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 129 RECORDS

SELECT * FROM REQUIREMENT_BINARY X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 84 RECORDS

SELECT * FROM REQUIREMENT_SCHED X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM SERVICE_DISPATCHED X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM SERVICE_RECEIPT X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM SI_BATCH_LABOR X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> X RECORDS

SELECT * FROM SPLIT_TRANS X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> X RECORDS

SELECT * FROM VR_WORKORDER_HDR X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM WIP_BALANCE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM WIP_ISSUE_DETAIL X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM WIP_ISSUE_DIST X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM WIP_LABOR_DETAIL X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM WIP_PAYB_DETAIL X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM WIP_RECEIPT_DETAIL X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM WIP_RECEIPT_DIST X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM WIP_SERVICE_DETAIL X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM WIP_SPLIT_DETAIL X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM WO_SCH_PRIORITY X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM WORK_ORDER X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.BASE_ID = U.BASEID
		AND X.LOT_ID = U.LOT
		AND X.SPLIT_ID = U.SPLIT
		AND X.SUB_ID = U.SUB
		AND X.TYPE = 'M'
)
--> 20,794 RECORDS

SELECT * FROM WORK_ORDER_SCHED X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 0 RECORDS

SELECT * FROM WORKORDER_BINARY X
WHERE EXISTS(SELECT 1
    FROM [dbo].[Update20210301] U
    WHERE X.WORKORDER_BASE_ID = U.BASEID
		AND X.WORKORDER_LOT_ID = U.LOT
		AND X.WORKORDER_SPLIT_ID = U.SPLIT
		AND X.WORKORDER_SUB_ID = U.SUB
		AND X.WORKORDER_TYPE = 'M'
)
--> 16,832 RECORDS


