/****** Object:  Table [dbo].[MastersUpd20211112]    Script Date: 11/12/2021 1:09:14 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--CREATE TABLE [dbo].[MastersUpd20211112](
--	[Base_ID] [nvarchar](50) NULL,
--	[Lot_ID] [nvarchar](5) NULL,
--	[Sub_ID] [nvarchar](5) NULL,
--	[Split_ID] [nvarchar](5) NULL,
--	[SEQUENCE_NO] [nvarchar](5) NULL,
--	[Resource_ID] [nvarchar](50) NULL,
--	[SETUP_HRS] [decimal](8, 3) NULL,
--	[RUN_HRS] [decimal](7, 2) NULL,
--	[RUN_TYPE] [nvarchar](15) NULL,
--) ON [PRIMARY]
--GO

--SELECT * FROM [LIVESupplemental].dbo.[MastersUpd20211112] U

DROP TABLE #T1

SELECT O.WORKORDER_TYPE
	, O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.OPERATION_TYPE
	, O.RUN
	, O.[SETUP_HRS] AS OP_SETUP_HRS
	, U.[SETUP_HRS]
	, O.[RUN_HRS] AS OP_RUN_HRS
	, U.[RUN_HRS]
	, O.[RUN_TYPE] AS OP_RUN_TYPE
	, U.[RUN_TYPE]
INTO #T1
FROM [LIVESupplemental].dbo.[MastersUpd20211112] U
INNER JOIN OPERATION O
	ON O.WORKORDER_BASE_ID = U.Base_ID
	AND O.WORKORDER_LOT_ID = U.Lot_ID
	AND O.WORKORDER_SPLIT_ID = U.SPLIT_ID
	AND O.WORKORDER_SUB_ID = U.Sub_ID
	AND O.WORKORDER_TYPE = 'M'
	AND O.SEQUENCE_NO = U.SEQUENCE_NO
	AND O.RESOURCE_ID = U.Resource_ID
--WHERE O.[RUN_HRS] != U.[RUN_HRS]
--	AND O.[RUN_HRS] = 0
WHERE O.[SETUP_HRS] != U.[SETUP_HRS]
	OR O.[RUN_HRS] != U.[RUN_HRS]
	--AND LEFT(WORKORDER_BASE_ID, 3) = '68A'
--	AND O.[SETUP_HRS] = 0.3
	--AND O.[RUN_TYPE] = 'HRS/PC'
	--AND O.RESOURCE_ID = 'P2M1-SM-TPUNCH'
	--AND O.OPERATION_TYPE = 'AMADA'
	--AND O.SEQUENCE_NO = '20'
	--AND O.[SETUP_HRS] > 0.25
	--AND O.[SETUP_HRS] < 0.3

--SELECT * FROM #T1
--SELECT LEFT(WORKORDER_BASE_ID, 3) AS BASE_ID
--, COUNT(*) 
--FROM #T1 
--GROUP BY LEFT(WORKORDER_BASE_ID, 3)
--ORDER BY LEFT(WORKORDER_BASE_ID, 3)

/*
BEGIN TRANSACTION;
UPDATE OPERATION     
--SET [SETUP_HRS] = T.[SETUP_HRS]
SET [RUN_HRS] = T.[RUN_HRS]
FROM OPERATION O
INNER JOIN #T1 T
	ON O.WORKORDER_TYPE = T.WORKORDER_TYPE
	AND O.WORKORDER_BASE_ID = T.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID	= T.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = T.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = T.WORKORDER_SUB_ID
	AND O.SEQUENCE_NO = T.SEQUENCE_NO
	AND O.RESOURCE_ID = T.Resource_ID

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

--SELECT O.WORKORDER_TYPE
--	, O.WORKORDER_BASE_ID
--	, O.WORKORDER_LOT_ID
--	, O.WORKORDER_SPLIT_ID
--	, O.WORKORDER_SUB_ID
--	, O.SEQUENCE_NO
--	, O.RESOURCE_ID
--	, O.[SETUP_HRS] AS OP_SETUP_HRS
--	, U.[SETUP_HRS]
--	, O.[RUN_HRS] AS OP_RUN_HRS
--	, U.[RUN_HRS]
--	, O.[RUN] AS OP_RUN
--	, U.[RUN]
--FROM [LIVESupplemental].dbo.[MastersUpd20211112] U
--INNER JOIN OPERATION O
--	ON O.WORKORDER_BASE_ID = U.Base_ID
--	AND O.WORKORDER_LOT_ID = U.Lot_ID
--	AND O.WORKORDER_SPLIT_ID = U.SPLIT_ID
--	AND O.WORKORDER_SUB_ID = U.Sub_ID
--	AND O.WORKORDER_TYPE = 'M'
--	AND O.SEQUENCE_NO = U.SEQUENCE_NO
--	AND O.RESOURCE_ID = U.Resource_ID
--WHERE O.[SETUP_HRS] != U.[SETUP_HRS]
--	OR O.[RUN_HRS] AS OP_RUN_HRS != U.[RUN_HRS]
