USE DATAWAREHOUSE
GO

SELECT CUSTOMER_ID
, CUST_ORDER_ID
, LINE_NO
, ORDER_DATE
, PART_ID
, SERVICE_CHARGE_ID
, MISC_REFERENCE
FROM CUST_ORDER_LINE COL
INNER JOIN CUSTOMER_ORDER CO
ON CO.ID = COL.CUST_ORDER_ID
WHERE COL.PART_ID IS NULL
AND COL.SERVICE_CHARGE_ID IS NULL
AND ORDER_DATE >= '1/1/2020'
