USE DataWarehouse
GO

SELECT CONVERT(DATE, S.SHIPPED_DATE, 101) AS SHIPPED_DATE
, CONVERT(DATE, LT.TRANSACTION_DATE, 101) AS TRANSACTION_DATE
, CONVERT(DATE, LT.CREATE_DATE, 101) AS CREATE_DATE
, CONVERT(DATE, LT._DATE, 101) AS _DATE

, DATEADD(mm, DATEDIFF(mm, 0, S.SHIPPED_DATE), 0) AS FOM
, DATEADD(day, (5 - datepart(weekday, S.SHIPPED_DATE)), S.SHIPPED_DATE) AS THURSDAY
, MONTH(DATEADD(mm, DATEDIFF(mm, 0, S.SHIPPED_DATE), 0)) AS FOMONTH
, MONTH(DATEADD(day, (5 - datepart(weekday, S.SHIPPED_DATE)), S.SHIPPED_DATE)) AS THURSMONTH
, LT.SHIFT_DATE
, LT.TRANSACTION_ID
, LT.HOURS_WORKED
, LT.WORKORDER_BASE_ID
, LT.OPERATION_SEQ_NO
, LT.RESOURCE_ID
, LT.EMPLOYEE_ID
, LT.CLOCK_IN
, LT.CLOCK_OUT
, LT.ACT_CLOCK_IN
, LT.ACT_CLOCK_OUT
, LT.UNADJ_CLOCK_IN
, LT.UNADJ_CLOCK_OUT
FROM DataWarehouse.dbo.SHIPPER S
INNER JOIN DataWarehouse.dbo.SHIPPER_LINE SL
	ON S.PACKLIST_ID = SL.PACKLIST_ID
INNER JOIN DataWarehouse.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN DataWarehouse.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DataWarehouse.dbo.DEMAND_SUPPLY_LINK DSL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
INNER JOIN DataWarehouse.dbo.WORK_ORDER WO
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
INNER JOIN DataWarehouse.dbo.LABOR_TICKET LT
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
	AND WO.[TYPE] = LT.WORKORDER_TYPE
WHERE CONVERT(DATE, S.SHIPPED_DATE, 101) < CONVERT(DATE, LT.CREATE_DATE, 101)
AND S.SHIPPED_DATE >= '1/1/2020'
AND CO.CUSTOMER_ID = 'BOE609'

--AND MONTH(DATEADD(mm, DATEDIFF(mm, 0, S.SHIPPED_DATE), 0)) != MONTH(DATEADD(day, (5 - datepart(weekday, S.SHIPPED_DATE)), S.SHIPPED_DATE))


--select * from labor_ticket where transaction_id = 19807411