USE LIVE
GO

SELECT NOE.SHIPPER
	, SL.PACKLIST_ID
	, SL.LINE_NO AS SHIPPER_LINE
	, S.SHIPPED_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS CO_LINE
	, COL.PART_ID
	, CA.CUSTOMER_ID
	, CA.[NAME]
	, CA.ADDR_1
	, CA.ADDR_2
	, CA.CITY
	, CA.[STATE]
	, CA.ZIPCODE
	, CA.COUNTRY
FROM LIVESupplemental..NoE20210691 NOE
LEFT OUTER JOIN SHIPPER_LINE SL
	ON NOE.PACKLIST_ID = SL.PACKLIST_ID
	AND NOE.LINE_NO = SL.LINE_NO
LEFT OUTER JOIN SHIPPER S
	ON S.PACKLIST_ID = SL.PACKLIST_ID 
LEFT OUTER JOIN CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
LEFT OUTER JOIN CUST_ADDRESS CA
	ON S.SHIP_TO_ADDR_NO = CA.ADDR_NO
	AND CO.CUSTOMER_ID = CA.CUSTOMER_ID
GROUP BY NOE.SHIPPER
	, SL.PACKLIST_ID
	, SL.LINE_NO
	, S.SHIPPED_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO
	, COL.PART_ID
	, CA.CUSTOMER_ID
	, CA.[NAME]
	, CA.ADDR_1
	, CA.ADDR_2
	, CA.ADDR_3
	, CA.CITY
	, CA.[STATE]
	, CA.ZIPCODE
	, CA.COUNTRY
ORDER BY COL.CUST_ORDER_ID
	, COL.LINE_NO
	, COL.PART_ID
	, CA.CUSTOMER_ID
	, CA.[NAME]
	, CA.ADDR_1
	, CA.ADDR_2
	, CA.ADDR_3
	, CA.CITY
	, CA.[STATE]
	, CA.ZIPCODE
	, CA.COUNTRY