use DataWarehouse
go
/* 
2019/10/15 - Monica
Can you please provide a report that list all part numbers that we have previously shipped or have in WIP for Northrup Gruman (NORGRU)?
It should include part number, last sales date, and if it goes through mfg and or finish. In addition, we need to know if it goes through masking.
If we could please have this before Friday. Northrup will be here next week for an audit and we would like to show progress on this corrective action project.

CO = 406676 LINE = 3
*/

DECLARE @START DATE = '1/1/2016'
;

WITH CTE_UNLINKED AS
(SELECT 'UNLINKED1' AS [ORDER_TYPE]
	, CO.CUSTOMER_ID
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, ISNULL(COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) AS DESIRED_SHIP_DATE
	, S.SHIPPED_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.[STATUS]
	, COL.PART_ID
	, CASE
		WHEN COL.LINE_STATUS = 'C' THEN 'YES'
		ELSE 'NO'
	END AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, SL.SHIPPED_QTY
	, SL.TRANSACTION_ID
	, T.TRACE_ID
	, T.QTY * -1 AS TRACE_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
FROM DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER_LINE SL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SPLIT_ID = '0'
	AND WO.SUB_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE DSL.SUPPLY_BASE_ID IS NULL
	AND CO.ORDER_DATE >= @START
	AND CO.CUSTOMER_ID = 'NORGRU'
----
UNION ALL
----
SELECT 'UNLINKED2' AS [ORDER_TYPE]
	, CO.CUSTOMER_ID
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, ISNULL(COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) AS DESIRED_SHIP_DATE
	, S.SHIPPED_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.[STATUS]
	, COL.PART_ID
	, CASE
		WHEN COL.LINE_STATUS = 'C' THEN 'YES'
		ELSE 'NO'
	END AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, SL.SHIPPED_QTY
	, SL.TRANSACTION_ID
	, T.TRACE_ID
	, T.QTY * -1 AS TRACE_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
FROM DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER_LINE SL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID + '/' + WO.SUB_ID)
	AND WO.DESIRED_QTY <> 0
 	AND WO.SPLIT_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE DSL.SUPPLY_BASE_ID IS NULL
	AND CO.ORDER_DATE >= @START
	AND CO.CUSTOMER_ID = 'NORGRU'
----
UNION ALL
----
SELECT 'UNLINKED3' AS [ORDER_TYPE]
	, CO.CUSTOMER_ID
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, ISNULL(COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) AS DESIRED_SHIP_DATE
	, S.SHIPPED_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.[STATUS]
	, COL.PART_ID
	, CASE
		WHEN COL.LINE_STATUS = 'C' THEN 'YES'
		ELSE 'NO'
	END AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, SL.SHIPPED_QTY
	, SL.TRANSACTION_ID
	, T.TRACE_ID
	, T.QTY * -1 AS TRACE_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
FROM DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER_LINE SL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID + '.' + WO.SPLIT_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SUB_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE DSL.SUPPLY_BASE_ID IS NULL
	AND CO.ORDER_DATE >= @START
	AND CO.CUSTOMER_ID = 'NORGRU'
UNION ALL
----
SELECT 'UNSHIPPED' AS [ORDER_TYPE]
	, CO.CUSTOMER_ID
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, ISNULL(COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) AS DESIRED_SHIP_DATE
	, S.SHIPPED_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.[STATUS]
	, COL.PART_ID
	, CASE
		WHEN COL.LINE_STATUS = 'C' THEN 'YES'
		ELSE 'NO'
	END AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, SL.SHIPPED_QTY
	, SL.TRANSACTION_ID
	, T.TRACE_ID
	, T.QTY * -1 AS TRACE_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
FROM DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
LEFT OUTER JOIN DATAWAREHOUSE.dbo.SHIPPER_LINE SL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
--	AND COL.PART_ID IS NOT NULL
LEFT OUTER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
LEFT OUTER JOIN DATAWAREHOUSE.dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
LEFT OUTER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
LEFT OUTER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
--	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID + '.' + WO.SPLIT_ID)
	ON COL.PART_ID = WO.PART_ID
--	AND WO.DESIRED_QTY <> 0
	AND WO.[TYPE] = 'M'
--	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE DSL.SUPPLY_BASE_ID IS NULL
	AND CO.ORDER_DATE >= @START
	AND CO.CUSTOMER_ID = 'NORGRU'
	AND SL.TRANSACTION_ID IS NULL

)


SELECT * 
	, (SELECT DISTINCT sr.user_1 
		FROM operation o
		inner join SHOP_RESOURCE sr
			on o.RESOURCE_ID = sr.ID
			and sr.user_1 = 'M'
		WHERE CTE.base_id = o.workorder_base_id
			and CTE.lot_id = o.workorder_lot_id
			and CTE.split_id = o.workorder_split_id
			and CTE.sub_id = o.workorder_sub_id
			and o.workorder_type = 'W'
		) AS [MFG]
	, (SELECT DISTINCT sr.user_1 
		FROM operation o
		inner join SHOP_RESOURCE sr
			on o.RESOURCE_ID = sr.ID
			and sr.user_1 = 'A'
		WHERE CTE.base_id = o.workorder_base_id
			and CTE.lot_id = o.workorder_lot_id
			and CTE.split_id = o.workorder_split_id
			and CTE.sub_id = o.workorder_sub_id
			and o.workorder_type = 'W'
		) AS [FIN]
	, (SELECT DISTINCT sr.user_1 
		FROM operation o
		inner join SHOP_RESOURCE sr
			on o.RESOURCE_ID = sr.ID
			and sr.user_1 = 'B'
		WHERE CTE.base_id = o.workorder_base_id
			and CTE.lot_id = o.workorder_lot_id
			and CTE.split_id = o.workorder_split_id
			and CTE.sub_id = o.workorder_sub_id
			and o.workorder_type = 'W'
		) AS [BALLARD]
	, SUBSTRING((SELECT ', ' + o.RESOURCE_ID  AS [text()]
		FROM operation o
		inner join SHOP_RESOURCE sr
			on o.RESOURCE_ID = sr.ID
			and sr.user_2 = 'MASKING'
		WHERE CTE.base_id = o.workorder_base_id
			and CTE.lot_id = o.workorder_lot_id
			and CTE.split_id = o.workorder_split_id
			and CTE.sub_id = o.workorder_sub_id
			and o.workorder_type = 'W'
		ORDER BY o.SEQUENCE_NO
		FOR XML PATH ('')
	), 2, 1000) [Resource_IDs]
		, SUBSTRING((SELECT ', ' + o.operation_type  AS [text()]
		FROM operation o
		inner join SHOP_RESOURCE sr
			on o.RESOURCE_ID = sr.ID
			and sr.user_2 = 'MASKING'
		WHERE CTE.base_id = o.workorder_base_id
			and CTE.lot_id = o.workorder_lot_id
			and CTE.split_id = o.workorder_split_id
			and CTE.sub_id = o.workorder_sub_id
			and o.workorder_type = 'W'
		ORDER BY o.SEQUENCE_NO
		FOR XML PATH ('')
	), 2, 1000) [Op_Types]
FROM CTE_UNLINKED CTE
WHERE PART_ID IS NOT NULL
ORDER BY DESIRED_SHIP_DATE, SHIPPED_DATE, CUST_ORDER_ID, COL_LINE

SELECT * FROM CUSTOMER_ORDER WHERE CUSTOMER_ID = 'NORGRU'