USE DataWarehouse
GO

-- VISUAL ENTERPRISE REPORTS/LABOR REPORTS/NULL LABOR TICKETS

WITH CTE_LTS AS
(SELECT *
FROM LABOR_TICKET LT
WHERE TRANSACTION_DATE >= '1/1/2018'
)
--select * from CTE_LTS 

, CTE_OPSEQNO AS
-- PULL SUMMATION OF ALL LABOR TICKETS FOR ALL OPERATIONS WITHIN TIME FRAME
(SELECT LT.WORKORDER_TYPE
	, LT.WORKORDER_BASE_ID
	, LT.WORKORDER_LOT_ID
	, LT.WORKORDER_SPLIT_ID
	, LT.WORKORDER_SUB_ID
	, LT.OPERATION_SEQ_NO
	, LT.RESOURCE_ID
	, SUM(LT.HOURS_WORKED) AS TTLHOURS
FROM LABOR_TICKET LT
INNER JOIN WORK_ORDER WO
	ON LT.WORKORDER_BASE_ID = WO.BASE_ID
	AND LT.WORKORDER_LOT_ID = WO.LOT_ID
	AND LT.WORKORDER_SPLIT_ID = WO.SPLIT_ID
	AND LT.WORKORDER_SUB_ID = WO.SUB_ID
	AND LT.WORKORDER_TYPE = WO.[TYPE]
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON  WO.BASE_ID = DSL.SUPPLY_BASE_ID
	AND WO.LOT_ID = DSL.SUPPLY_LOT_ID 
	AND WO.SPLIT_ID = DSL.SUPPLY_SPLIT_ID
	AND WO.SUB_ID = DSL.SUPPLY_SUB_ID
	AND DSL.SUPPLY_TYPE = 'WO'
LEFT OUTER JOIN CUST_ORDER_LINE COL 
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO 
	AND DSL.DEMAND_TYPE = 'CO'
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
WHERE CO.CUSTOMER_ID = 'BOE609'
	AND WO.[STATUS] NOT IN ('C', 'X')
	AND HOURS_WORKED > 0
GROUP BY LT.WORKORDER_TYPE
	, LT.WORKORDER_BASE_ID
	, LT.WORKORDER_LOT_ID
	, LT.WORKORDER_SPLIT_ID
	, LT.WORKORDER_SUB_ID
	, LT.OPERATION_SEQ_NO
	, LT.RESOURCE_ID
) 
--SELECT * FROM CTE_OPSEQNO

, CTE_MINMAX AS
-- PULL FIRST AND LAST OPS WITHIN TIMEFRAME
(SELECT L1.WORKORDER_TYPE
	, L1.WORKORDER_BASE_ID
	, L1.WORKORDER_LOT_ID
	, L1.WORKORDER_SPLIT_ID
	, L1.WORKORDER_SUB_ID
	, MIN(L1.OPERATION_SEQ_NO) AS STARTSEQNO
	, MAX(L1.OPERATION_SEQ_NO) AS LASTSEQNO
FROM CTE_OPSEQNO L1
GROUP BY L1.WORKORDER_TYPE
	, L1.WORKORDER_BASE_ID
	, L1.WORKORDER_LOT_ID
	, L1.WORKORDER_SPLIT_ID
	, L1.WORKORDER_SUB_ID
) 
--SELECT * FROM CTE_MINMAX 

, CTE_OPNULLS AS
-- PULLS ANY GAPS (OPERATIONS WITHOUT LABOR TICKETS)
(SELECT O.WORKORDER_TYPE
	, O.WORKORDER_BASE_ID 
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
FROM OPERATION O
WHERE NOT EXISTS
	(SELECT 1
	FROM LIVESUPPLEMENTAL.DBO.RESOURCEID_REPORTSETTINGS EX
	WHERE O.RESOURCE_ID = EX.RESOURCE_ID
		AND REPORT_NAME = 'NULL LABOR TICKETS'
	)
	AND NOT EXISTS
-- remove operations with labor tickets
		(SELECT 1
		FROM CTE_OPSEQNO S
		WHERE O.WORKORDER_TYPE = S.WORKORDER_TYPE 
			AND O.WORKORDER_BASE_ID = S.WORKORDER_BASE_ID 
			AND O.WORKORDER_LOT_ID = S.WORKORDER_LOT_ID 
			AND O.WORKORDER_SPLIT_ID = S.WORKORDER_SPLIT_ID 
			AND O.WORKORDER_SUB_ID = S.WORKORDER_SUB_ID
			AND O.SEQUENCE_NO = S.OPERATION_SEQ_NO
		)
	AND EXISTS
-- pull operations with workorder that has other labor tickets
		(SELECT 1
		FROM CTE_OPSEQNO S
		WHERE O.WORKORDER_TYPE = S.WORKORDER_TYPE 
			AND O.WORKORDER_BASE_ID = S.WORKORDER_BASE_ID 
			AND O.WORKORDER_LOT_ID = S.WORKORDER_LOT_ID 
			AND O.WORKORDER_SPLIT_ID = S.WORKORDER_SPLIT_ID 
			AND O.WORKORDER_SUB_ID = S.WORKORDER_SUB_ID
		)
	AND EXISTS
--pull operations between min and max
		(SELECT 1
		FROM CTE_MINMAX S
		WHERE O.WORKORDER_TYPE = S.WORKORDER_TYPE 
			AND O.WORKORDER_BASE_ID = S.WORKORDER_BASE_ID 
			AND O.WORKORDER_LOT_ID = S.WORKORDER_LOT_ID 
			AND O.WORKORDER_SPLIT_ID = S.WORKORDER_SPLIT_ID 
			AND O.WORKORDER_SUB_ID = S.WORKORDER_SUB_ID
			AND O.SEQUENCE_NO > S.STARTSEQNO
			AND O.SEQUENCE_NO < S.LASTSEQNO
		)
)
--select * from CTE_OPNULLS


, CTE_DISTINCTGAPS AS
(
SELECT A.*
	, CASE 
		WHEN GAP = 'GAP' THEN 
			CASE 
				WHEN LAG(GAP) OVER(PARTITION BY WORKORDER_TYPE, WORKORDER_BASE_ID, WORKORDER_LOT_ID, WORKORDER_SPLIT_ID, WORKORDER_SUB_ID ORDER BY SEQNO) = GAP THEN 0 
				ELSE DENSE_RANK() OVER(PARTITION BY A.WORKORDER_TYPE, A.WORKORDER_BASE_ID, A.WORKORDER_LOT_ID, A.WORKORDER_SPLIT_ID, A.WORKORDER_SUB_ID, A.GAP ORDER BY SEQNO) 
			END
		ELSE 0 
	END AS NEWGAP
FROM 
	(SELECT WORKORDER_TYPE
		, WORKORDER_BASE_ID
		, WORKORDER_LOT_ID
		, WORKORDER_SPLIT_ID
		, WORKORDER_SUB_ID
		, SEQUENCE_NO AS SEQNO
		, RESOURCE_ID
		, 'GAP' AS GAP
	FROM CTE_OPNULLS N
	UNION ALL
	SELECT WORKORDER_TYPE
		, WORKORDER_BASE_ID
		, WORKORDER_LOT_ID
		, WORKORDER_SPLIT_ID
		, WORKORDER_SUB_ID
		, OPERATION_SEQ_NO AS SEQNO
		, RESOURCE_ID
		, 'NO GAP' AS GAP
	FROM CTE_OPSEQNO O
	) A
)
--SELECT * FROM CTE_DISTINCTGAPS

, CTE_GAPMEMBERS AS
(SELECT 
	CASE 
		WHEN NEWGAP <> 0 THEN SEQNO 
	END AS STARTSEQ
	, CASE 
		WHEN LEAD(GAP) OVER (PARTITION BY WORKORDER_TYPE, WORKORDER_BASE_ID, WORKORDER_LOT_ID, WORKORDER_SPLIT_ID, WORKORDER_SUB_ID ORDER BY  SEQNO) <> GAP
			THEN SEQNO
	END AS ENDSEQUENCE
	,* 
FROM CTE_DISTINCTGAPS A
)
--SELECT * FROM CTE_GAPMEMBERS

, CTE_LEADINGTRAILINGSEQ AS
(SELECT 
	CASE 
		WHEN NEWGAP <> 0 THEN LAG(SEQNO) OVER(PARTITION BY A.WORKORDER_TYPE, A.WORKORDER_BASE_ID, A.WORKORDER_LOT_ID, A.WORKORDER_SPLIT_ID, A.WORKORDER_SUB_ID ORDER BY SEQNO)
		ELSE 0
	END AS LEADINGSEQ
	, CASE 
		WHEN ENDSEQUENCE IS NOT NULL THEN LEAD(SEQNO) OVER(PARTITION BY A.WORKORDER_TYPE, A.WORKORDER_BASE_ID, A.WORKORDER_LOT_ID, A.WORKORDER_SPLIT_ID, A.WORKORDER_SUB_ID ORDER BY SEQNO)
		ELSE 0
	END AS TRAILINGSEQ
	,* 
	FROM CTE_GAPMEMBERS A
)
--select * from CTE_LEADINGTRAILINGSEQ where WORKORDER_BASE_ID = '1497029'

SELECT COL.CUST_ORDER_ID
	, COL.PART_ID
	, COL.ORDER_QTY 
	, B4.WORKORDER_BASE_ID
	, B4.WORKORDER_LOT_ID
	, B4.WORKORDER_SPLIT_ID
	, B4.WORKORDER_SUB_ID
	, B4.SEQNO AS NULLSEQNO
	, B4.RESOURCE_ID AS NULLRESOURCEID
	, LT.EMPLOYEE_ID
	, ADP.[FIRST NAME] AS FNAME
	, ADP.[LAST NAME] AS LNAME
	, LT.HOURS_WORKED
	, ADP.[REPORTS TO]
	, L1.OPERATION_SEQ_NO AS SEQNOB4
	, L1.RESOURCE_ID AS RESOURCEIDB4
	, L1.LASTCLOCKOUT
	, CASE
		WHEN L1.LASTCLOCKOUT IS NULL THEN NULL
		WHEN DATEPART(DW, L1.LASTCLOCKOUT) >= 2 AND DATEPART(DW, L1.LASTCLOCKOUT) <= 6 
			AND (CAST(L1.LASTCLOCKOUT AS TIME) >= '07:00:00' AND CAST(L1.LASTCLOCKOUT AS TIME) <= '15:30:00')
			THEN 1  --> M-F 0700-1530
		WHEN DATEPART(DW, L1.LASTCLOCKOUT) >= 2 AND DATEPART(DW, L1.LASTCLOCKOUT) <= 6 
			AND (CAST(L1.LASTCLOCKOUT AS TIME) >= '15:30:00')
			THEN 2  --> M-F 1530-0000
		WHEN DATEPART(DW, L1.LASTCLOCKOUT) >= 1 AND DATEPART(DW, L1.LASTCLOCKOUT) <= 5 
			AND (CAST(L1.LASTCLOCKOUT AS TIME) >= '23:00:00' OR CAST(L1.LASTCLOCKOUT AS TIME) <= '07:00:00')
			THEN 3  --> S-TH 2300-0700
		WHEN DATEPART(DW, L1.LASTCLOCKOUT) >= 6 OR DATEPART(DW, L1.LASTCLOCKOUT) = 1 
			AND (CAST(L1.LASTCLOCKOUT AS TIME) >= '06:00:00' AND CAST(L1.LASTCLOCKOUT AS TIME) <= '18:30:00')
			THEN 4  --> F-S 0600-1830
		WHEN DATEPART(DW, L1.LASTCLOCKOUT) >= 2 OR DATEPART(DW, L1.LASTCLOCKOUT) <= 5 
			AND (CAST(L1.LASTCLOCKOUT AS TIME) >= '06:00:00' AND CAST(L1.LASTCLOCKOUT AS TIME) <= '16:30:00')
			THEN 5  --> M-TH 0600-1630
		WHEN DATEPART(DW, L1.LASTCLOCKOUT) >= 2 OR DATEPART(DW, L1.LASTCLOCKOUT) <= 5 
			AND (CAST(L1.LASTCLOCKOUT AS TIME) >= '21:30:00' OR CAST(L1.LASTCLOCKOUT AS TIME) <= '07:30:00')
			THEN 6  --> M-TH 2130-0730
		WHEN DATEPART(DW, L1.LASTCLOCKOUT) >= 2 OR DATEPART(DW, L1.LASTCLOCKOUT) <= 5 
			AND (CAST(L1.LASTCLOCKOUT AS TIME) >= '16:30:00' OR CAST(L1.LASTCLOCKOUT AS TIME) <= '03:00:00')
			THEN 7  --> M-TH 1630-0300
		WHEN DATEPART(DW, L1.LASTCLOCKOUT) >= 6 OR DATEPART(DW, L1.LASTCLOCKOUT) = 1 
			AND (CAST(L1.LASTCLOCKOUT AS TIME) >= '18:00:00' OR CAST(L1.LASTCLOCKOUT AS TIME) <= '06:30:00')
			THEN 8  --> F-S 1800-0630
		ELSE 0
	END AS PREVSHIFT
	, L2.OPERATION_SEQ_NO AS SEQNOAFTER
	, L2.RESOURCE_ID AS RESOURCEIDAFTER
	, L2.NEXTCLOCKIN
	, CASE
		WHEN L2.NEXTCLOCKIN IS NULL THEN NULL
		WHEN DATEPART(DW, L2.NEXTCLOCKIN) >= 2 AND DATEPART(DW, L2.NEXTCLOCKIN) <= 6 
			AND (CAST(L2.NEXTCLOCKIN AS TIME) >= '07:00:00' AND CAST(L2.NEXTCLOCKIN AS TIME) <= '15:30:00')
			THEN 1  --> M-F 0700-1530
		WHEN DATEPART(DW, L2.NEXTCLOCKIN) >= 2 AND DATEPART(DW, L2.NEXTCLOCKIN) <= 6 
			AND (CAST(L2.NEXTCLOCKIN AS TIME) >= '15:30:00')
			THEN 2  --> M-F 1530-0000
		WHEN DATEPART(DW, L2.NEXTCLOCKIN) >= 1 AND DATEPART(DW, L2.NEXTCLOCKIN) <= 5 
			AND (CAST(L2.NEXTCLOCKIN AS TIME) >= '23:00:00' OR CAST(L2.NEXTCLOCKIN AS TIME) <= '07:00:00')
			THEN 3  --> S-TH 2300-0700
		WHEN DATEPART(DW, L2.NEXTCLOCKIN) >= 6 OR DATEPART(DW, L2.NEXTCLOCKIN) = 1 
			AND (CAST(L2.NEXTCLOCKIN AS TIME) >= '06:00:00' AND CAST(L2.NEXTCLOCKIN AS TIME) <= '18:30:00')
			THEN 4  --> F-S 0600-1830
		WHEN DATEPART(DW, L2.NEXTCLOCKIN) >= 2 OR DATEPART(DW, L2.NEXTCLOCKIN) <= 5 
			AND (CAST(L2.NEXTCLOCKIN AS TIME) >= '06:00:00' AND CAST(L2.NEXTCLOCKIN AS TIME) <= '16:30:00')
			THEN 5  --> M-TH 0600-1630
		WHEN DATEPART(DW, L2.NEXTCLOCKIN) >= 2 OR DATEPART(DW, L2.NEXTCLOCKIN) <= 5 
			AND (CAST(L2.NEXTCLOCKIN AS TIME) >= '21:30:00' OR CAST(L2.NEXTCLOCKIN AS TIME) <= '07:30:00')
			THEN 6  --> M-TH 2130-0730
		WHEN DATEPART(DW, L2.NEXTCLOCKIN) >= 2 OR DATEPART(DW, L2.NEXTCLOCKIN) <= 5 
			AND (CAST(L2.NEXTCLOCKIN AS TIME) >= '16:30:00' OR CAST(L2.NEXTCLOCKIN AS TIME) <= '03:00:00')
			THEN 7  --> M-TH 1630-0300
		WHEN DATEPART(DW, L2.NEXTCLOCKIN) >= 6 OR DATEPART(DW, L2.NEXTCLOCKIN) = 1 
			AND (CAST(L2.NEXTCLOCKIN AS TIME) >= '18:00:00' OR CAST(L2.NEXTCLOCKIN AS TIME) <= '06:30:00')
			THEN 8  --> F-S 1800-0630
		ELSE 0
	END AS NEXTSHIFT
FROM CTE_LEADINGTRAILINGSEQ B4
LEFT OUTER JOIN CTE_LTS LT
	ON B4.WORKORDER_BASE_ID = LT.WORKORDER_BASE_ID
	AND B4.WORKORDER_LOT_ID = LT.WORKORDER_LOT_ID
	AND B4.WORKORDER_SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND B4.WORKORDER_SUB_ID = LT.WORKORDER_SUB_ID
	AND B4.WORKORDER_TYPE = LT.WORKORDER_TYPE
	AND B4.SEQNO = LT.OPERATION_SEQ_NO
LEFT OUTER JOIN LIVESUPPLEMENTAL.DBO.EMP_ADP ADP
	ON LT.EMPLOYEE_ID = ADP.EMPID
LEFT OUTER JOIN 
	(SELECT WORKORDER_BASE_ID
		, WORKORDER_LOT_ID
		, WORKORDER_SPLIT_ID
		, WORKORDER_SUB_ID
		, WORKORDER_TYPE
		, OPERATION_SEQ_NO
		, RESOURCE_ID
		, MAX(CLOCK_OUT) AS LASTCLOCKOUT
	FROM CTE_LTS L1
	WHERE WORKORDER_BASE_ID IS NOT NULL
	GROUP BY WORKORDER_BASE_ID
		, WORKORDER_LOT_ID
		, WORKORDER_SPLIT_ID
		, WORKORDER_SUB_ID
		, WORKORDER_TYPE
		, OPERATION_SEQ_NO
		, RESOURCE_ID
	) L1
		ON B4.WORKORDER_BASE_ID = L1.WORKORDER_BASE_ID
		AND B4.WORKORDER_LOT_ID = L1.WORKORDER_LOT_ID
		AND B4.WORKORDER_SPLIT_ID = L1.WORKORDER_SPLIT_ID
		AND B4.WORKORDER_SUB_ID = L1.WORKORDER_SUB_ID
		AND B4.WORKORDER_TYPE = L1.WORKORDER_TYPE
		AND B4.LEADINGSEQ = L1.OPERATION_SEQ_NO
LEFT OUTER JOIN 
	(SELECT WORKORDER_BASE_ID
		, WORKORDER_LOT_ID
		, WORKORDER_SPLIT_ID
		, WORKORDER_SUB_ID
		, WORKORDER_TYPE
		, OPERATION_SEQ_NO
		, RESOURCE_ID
		, MIN(CLOCK_IN) AS NEXTCLOCKIN
	FROM CTE_LTS L2
	WHERE WORKORDER_BASE_ID IS NOT NULL
	GROUP BY WORKORDER_BASE_ID
		, WORKORDER_LOT_ID
		, WORKORDER_SPLIT_ID
		, WORKORDER_SUB_ID
		, WORKORDER_TYPE
		, OPERATION_SEQ_NO
		, RESOURCE_ID
	) L2
		ON B4.WORKORDER_BASE_ID = L2.WORKORDER_BASE_ID
		AND B4.WORKORDER_LOT_ID = L2.WORKORDER_LOT_ID
		AND B4.WORKORDER_SPLIT_ID = L2.WORKORDER_SPLIT_ID
		AND B4.WORKORDER_SUB_ID = L2.WORKORDER_SUB_ID
		AND B4.WORKORDER_TYPE = L2.WORKORDER_TYPE
		AND B4.TRAILINGSEQ = L2.OPERATION_SEQ_NO
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON  B4.WORKORDER_BASE_ID = DSL.SUPPLY_BASE_ID
	AND B4.WORKORDER_LOT_ID = DSL.SUPPLY_LOT_ID 
	AND B4.WORKORDER_SPLIT_ID = DSL.SUPPLY_SPLIT_ID
	AND B4.WORKORDER_SUB_ID = DSL.SUPPLY_SUB_ID
	AND DSL.SUPPLY_TYPE = 'WO'
LEFT OUTER JOIN CUST_ORDER_LINE COL 
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO 
	AND DSL.DEMAND_TYPE = 'CO'
WHERE GAP = 'GAP'