USE LIVE
GO

SELECT BASE_ID
, LOT_ID
, SPLIT_ID
, SUB_ID
, [TYPE]
, WO.[STATUS]
, PART_ID
, SEQUENCE_NO
, RESOURCE_ID
, OPERATION_TYPE
FROM WORK_ORDER WO
INNER JOIN PART P
ON P.ID = WO.PART_ID
AND P.[STATUS] = 'O'
INNER JOIN OPERATION O
ON WO.BASE_ID = O.WORKORDER_BASE_ID
AND WO.LOT_ID = O.WORKORDER_LOT_ID
AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
AND WO.SUB_ID = O.WORKORDER_SUB_ID
AND WO.[TYPE] = O.WORKORDER_TYPE
WHERE [TYPE] = 'M'
ORDER BY WO.BASE_ID
, WO.LOT_ID
, WO.SPLIT_ID
, WO.SUB_ID
, SEQUENCE_NO
