USE LIVE
GO

DROP TABLE #T1

SELECT O.WORKORDER_BASE_ID
, O.WORKORDER_LOT_ID
, O.WORKORDER_SPLIT_ID 
, O.WORKORDER_SUB_ID 
, O.WORKORDER_TYPE
, O.SEQUENCE_NO
, O.RESOURCE_ID
, O.RUN
, O.RUN_TYPE
, O.RUN_HRS
INTO #T1
FROM OPERATION O
WHERE RUN IS NULL
OR RUN_TYPE IS NULL
OR RUN_HRS IS NULL
--> 7444 RECORDS

SELECT * FROM #T1

/*
BEGIN TRANSACTION;
UPDATE OPERATION
SET RUN = 0.00
FROM OPERATION O
INNER JOIN #T1 U
	ON O.WORKORDER_BASE_ID = U.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = U.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = U.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = U.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = U.WORKORDER_TYPE
	AND O.SEQUENCE_NO = U.SEQUENCE_NO

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
--> tt20210720: 7444 RECORDS UPDATED
*/

SELECT O.WORKORDER_BASE_ID
, O.WORKORDER_LOT_ID
, O.WORKORDER_SPLIT_ID 
, O.WORKORDER_SUB_ID 
, O.WORKORDER_TYPE
, O.SEQUENCE_NO
, O.RESOURCE_ID
, O.RUN
FROM OPERATION O
WHERE RUN IS NULL
