USE LIVE
GO

--SELECT * FROM [LIVESupplemental].dbo.[OpUpdate20210420] U
-- 84472 RECORDS

DROP TABLE #T1

SELECT O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.WORKORDER_TYPE
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.[SETUP_HRS] AS OP_SETUP_HOURS
	, U.SETUP_HRS
INTO #T1
FROM OPERATION O
INNER JOIN [LIVESupplemental].dbo.[OpUpdate20210420] U
	ON O.WORKORDER_BASE_ID = U.BASE_ID
	AND O.WORKORDER_LOT_ID = U.LOT_ID
	AND O.WORKORDER_SPLIT_ID = '0'
	AND O.WORKORDER_SUB_ID = U.SUB_ID
	AND O.WORKORDER_TYPE = 'M'
	AND O.SEQUENCE_NO = U.SEQUENCE_NO
	AND O.RESOURCE_ID = U.Resource_ID
WHERE U.SETUP_HRS = '0.000'
	AND O.[SETUP_HRS] != U.SETUP_HRS
--> tt20210420: 3366 records TOTAL

SELECT * FROM #T1

/*
BEGIN TRANSACTION;
UPDATE OPERATION    
SET [SETUP_HRS] = 0.000
--SELECT *
FROM OPERATION O
INNER JOIN [LIVESupplemental].dbo.[OpUpdate20210420] T
	ON O.WORKORDER_BASE_ID = T.BASE_ID
	AND O.WORKORDER_LOT_ID = T.LOT_ID
	AND O.WORKORDER_SPLIT_ID = '0'
	AND O.WORKORDER_SUB_ID = T.SUB_ID
	AND O.WORKORDER_TYPE = 'M'
	AND O.SEQUENCE_NO = T.SEQUENCE_NO
	AND O.RESOURCE_ID = T.RESOURCE_ID
WHERE T.SETUP_HRS = 0.000
	AND O.[SETUP_HRS] != T.SETUP_HRS
	
--> tt20210420: 3366 records TOTAL
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
--> tt20210420:  RECORDS UPDATED
*/


