USE LIVE
GO

SELECT O.RESOURCE_ID
, O.OPERATION_TYPE
, CAST(CAST(OB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) OLD_TEXT
, CAST(CAST(OTB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS NEW_TEXT
FROM OPERATION_BINARY OB
INNER JOIN OPERATION O
	ON O.WORKORDER_TYPE = OB.WORKORDER_TYPE
	AND O.WORKORDER_BASE_ID = OB.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = OB.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = OB.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = OB.WORKORDER_SUB_ID
	AND O.SEQUENCE_NO = OB.SEQUENCE_NO
INNER JOIN DBO.OPER_TYPE_BINARY OTB
	ON OTB.OPERATION_TYPE_ID = O.OPERATION_TYPE
INNER JOIN LIVE.DBO.OPERATION_TYPE OT
	ON OT.ID = OTB.OPERATION_TYPE_ID
INNER JOIN SHOP_RESOURCE SR
ON SR.ID = O.RESOURCE_ID
WHERE SR.USER_7 IN ('PRIMER', 'TOPCOAT')
AND O.[STATUS] = 'R'

--SELECT [STATUS], COUNT(*) FROM OPERATION GROUP BY [STATUS]
--SELECT * FROM SHOP_RESOURCE WHERE USER_6 = 'PAINT'