USE [LIVESupplemental]
GO

/****** Object:  Table [dbo].[OpUpd20210720]    Script Date: 7/20/2021 12:44:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[OpUpd20210720](
	[Base_ID] [nvarchar](50) NULL,
	[Sub_ID] [nvarchar](5) NULL,
	[Lot_ID] [nvarchar](5) NULL,
	[Split_ID] [nvarchar](5) NULL,
	[SEQUENCE_NO] [nvarchar](5) NULL,
	[Part_ID] [nvarchar](50) NULL,
	[User10] [nvarchar](50) NULL,
) ON [PRIMARY]
GO

SELECT * FROM LIVESupplemental.dbo.OpUpd20210720

USE LIVE
GO

DROP TABLE #T1

SELECT U.* 
	, O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID 
	, O.WORKORDER_SUB_ID 
	, O.WORKORDER_TYPE
	, O.SEQUENCE_NO AS OP_SEQ_NO
	, WO.PART_ID AS WO_PART_ID
	, O.USER_10
--	, U.USER10
INTO #T1
FROM LIVESupplemental.dbo.OpUpd20210720 U
INNER JOIN OPERATION O
	ON U.BASE_ID = O.WORKORDER_BASE_ID
	AND U.LOT_ID = O.WORKORDER_LOT_ID
	AND U.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND U.SUB_ID = O.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = 'W'
	AND O.SEQUENCE_NO = U.SEQUENCE_NO
INNER JOIN WORK_ORDER WO
	ON WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O.WORKORDER_SUB_ID
	AND WO.[TYPE] = 'W'
	AND U.Part_ID = WO.PART_ID

SELECT * FROM #T1
--> 269 RECORDS

/*
BEGIN TRANSACTION;
UPDATE OPERATION
SET USER_10 = USER10
FROM OPERATION O
INNER JOIN WORK_ORDER WO
	ON WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O.WORKORDER_SUB_ID
	AND WO.[TYPE] = 'W'
INNER JOIN #T1 U
	ON O.WORKORDER_BASE_ID = U.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = U.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = U.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = U.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = U.WORKORDER_TYPE
	AND O.SEQUENCE_NO = U.SEQUENCE_NO
	AND U.Part_ID = WO.PART_ID

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
--> tt20210720: 7444 RECORDS UPDATED
*/

SELECT U.* 
	, O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID 
	, O.WORKORDER_SUB_ID 
	, O.WORKORDER_TYPE
	, O.SEQUENCE_NO AS OP_SEQ_NO
	, WO.PART_ID AS WO_PART_ID
	, O.USER_10
--	, U.USER10
FROM LIVESupplemental.dbo.OpUpd20210720 U
INNER JOIN OPERATION O
	ON U.BASE_ID = O.WORKORDER_BASE_ID
	AND U.LOT_ID = O.WORKORDER_LOT_ID
	AND U.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND U.SUB_ID = O.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = 'W'
	AND O.SEQUENCE_NO = U.SEQUENCE_NO
INNER JOIN WORK_ORDER WO
	ON WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O.WORKORDER_SUB_ID
	AND WO.[TYPE] = 'W'
	AND U.Part_ID = WO.PART_ID

