USE LIVE
GO

--SELECT * FROM [LIVESupplemental].dbo.[OpUpdate20210406] U
-- 84472 RECORDS

DROP TABLE #T1

SELECT *
INTO #T1
FROM (
SELECT CASE
		WHEN U.[SETUP_HRS] != O.[SETUP_HRS] THEN 'SETUP_HOURS'
		ELSE NULL
	END AS [SETUP_HRS_COMMENTS]
	, CASE
		WHEN O.[RUN_TYPE] != U.[RUN_TYPE] THEN 'RUN TYPE'
		ELSE NULL
	END AS [RUN_TYPE_COMMENTS]
	, CASE
		WHEN O.[MOVE_HRS] != U.[MOVE_HRS] THEN 'MOVE_HOURS'
		ELSE NULL
	END AS [MOVE_HRS_COMMENTS]
	, CASE
		WHEN O.[MINIMUM_MOVE_QTY] != U.[MINIMUM_MOVE_QTY] THEN 'MIN MOVE QTY'
		ELSE NULL
	END AS [MINIMUM_MOVE_QTY_COMMENTS]
	, CASE
		WHEN O.[TRANSIT_DAYS] != U.[TRANSIT_DAYS] THEN 'TRANSIT DAYS'
		ELSE NULL
	END AS [TRANSIT_DAYS_COMMENTS]
	, CASE
		WHEN WO.[GLOBAL_RANK] != U.[GLOBAL_RANK] THEN 'GLOBAL RANK'
		ELSE NULL
	END AS [GLOBAL_RANK_COMMENTS]
	, CASE
		WHEN ISNULL(O.WORKORDER_BASE_ID, '') = '' THEN 'DID NOT MATCH'
		ELSE NULL
	END AS [NO MATCH]	
	, U.BASE_ID
	, U.LOT_ID
	, U.SUB_ID
	, U.SEQUENCE_NO
	, U.RESOURCE_ID
	, O.[RUN_TYPE] AS OP_RUN_TYPE
	, U.[RUN_TYPE]
	, O.[SETUP_HRS] AS OP_SETUP_HRS
	, CAST(U.[SETUP_HRS] AS DECIMAL(8,3)) AS [SETUP_HRS]
	, O.[MOVE_HRS] AS OP_MOVE_HRS
	, U.[MOVE_HRS]
	, O.[MINIMUM_MOVE_QTY] AS OP_MINIMUM_MOVE_QTY
	, U.[MINIMUM_MOVE_QTY]
	, O.[TRANSIT_DAYS] AS OP_TRANSIT_DAYS
	, U.[TRANSIT_DAYS]
	, WO.[GLOBAL_RANK] AS WO_GLOBAL_RANK
	, U.[GLOBAL_RANK]
FROM [LIVESupplemental].dbo.[OpUpdate20210406] U
LEFT OUTER JOIN OPERATION O
	ON O.WORKORDER_BASE_ID = U.Base_ID
	AND O.WORKORDER_LOT_ID = U.Lot_ID
	AND O.WORKORDER_SPLIT_ID = '0'
	AND O.WORKORDER_SUB_ID = U.Sub_ID
	AND O.WORKORDER_TYPE = 'M'
	AND O.SEQUENCE_NO = U.SEQUENCE_NO
	AND O.RESOURCE_ID = U.Resource_ID
LEFT OUTER JOIN WORK_ORDER WO
	ON O.WORKORDER_BASE_ID = WO.BASE_ID
	AND O.WORKORDER_LOT_ID = WO.LOT_ID
	AND O.WORKORDER_SPLIT_ID = WO.SPLIT_ID
	AND O.WORKORDER_SUB_ID = WO.SUB_ID
	AND O.WORKORDER_TYPE = WO.[TYPE]
) X
WHERE CASE
		WHEN ISNULL([SETUP_HRS_COMMENTS], '') != '' THEN 1
		WHEN ISNULL([RUN_TYPE_COMMENTS], '') != '' THEN 1
		WHEN ISNULL([MOVE_HRS_COMMENTS], '') != '' THEN 1
		WHEN ISNULL([MINIMUM_MOVE_QTY_COMMENTS], '') != '' THEN 1
		WHEN ISNULL([TRANSIT_DAYS_COMMENTS], '') != '' THEN 1
		WHEN ISNULL([GLOBAL_RANK_COMMENTS], '') != '' THEN 1
		WHEN ISNULL([NO MATCH], '') != '' THEN 1
	END > 0 

SELECT * FROM #T1 --WHERE TRANSIT_DAYS_COMMENTS IS NOT NULL

/*
BEGIN TRANSACTION;
UPDATE OPERATION
SET [TRANSIT_DAYS] = U.TRANSIT_DAYS
--SELECT *
FROM OPERATION O
INNER JOIN #T1 U
	ON O.WORKORDER_BASE_ID = U.Base_ID
	AND O.WORKORDER_LOT_ID = U.Lot_ID
	AND O.WORKORDER_SPLIT_ID = '0'
	AND O.WORKORDER_SUB_ID = U.Sub_ID
	AND O.WORKORDER_TYPE = 'M'
	AND O.SEQUENCE_NO = U.SEQUENCE_NO
	AND O.RESOURCE_ID = U.Resource_ID
WHERE TRANSIT_DAYS_COMMENTS IS NOT NULL
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

--WHERE WORKORDER_BASE_ID IN ('140T2502-49', '141U0051-91084', '143T0056-27', '143T0056-27', '146U9311-13', '140T2502-29', '140U0057-405', '140U0057-531', '140U0057-678', '141T1000-9458', '146T1033-175', '258T3743-1', '69B04554-15')
--AND WORKORDER_LOT_ID = '0'
--AND WORKORDER_SPLIT_ID = '0'
--AND WORKORDER_SUB_ID = '0'
--AND WORKORDER_TYPE = 'M'
--AND SEQUENCE_NO = '210'
--AND RESOURCE_ID = 'CONTRACTOR'
*/