USE LIVE
GO

DROP TABLE #T1
SELECT OB.WORKORDER_TYPE
	, OB.WORKORDER_BASE_ID
	, OB.WORKORDER_LOT_ID
	, OB.WORKORDER_SPLIT_ID
	, OB.WORKORDER_SUB_ID
	, OB.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.OPERATION_TYPE
	, O.[STATUS]
	, CAST(CAST(OB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [BEFORE_OB]
	, OB.BITS_LENGTH AS [B4_BITLEN]
	, (SELECT BITS FROM OPERATION_BINARY O
		WHERE O.WORKORDER_TYPE = 'M'
		AND O.WORKORDER_BASE_ID = '232W2221-73'
		AND O.WORKORDER_LOT_ID = '0'
		AND O.WORKORDER_SPLIT_ID = '0'
		AND O.WORKORDER_SUB_ID = '0'
		AND O.SEQUENCE_NO = '410'
		) AS [AFTER_OB]
	, (SELECT BITS_LENGTH FROM OPERATION_BINARY O
		WHERE O.WORKORDER_TYPE = 'M'
		AND O.WORKORDER_BASE_ID = '232W2221-73'
		AND O.WORKORDER_LOT_ID = '0'
		AND O.WORKORDER_SPLIT_ID = '0'
		AND O.WORKORDER_SUB_ID = '0'
		AND O.SEQUENCE_NO = '410'
		) AS [AFTER_BITLEN]
INTO #T1
FROM OPERATION O
INNER JOIN OPERATION_BINARY OB
	ON O.WORKORDER_TYPE = OB.WORKORDER_TYPE
	AND O.WORKORDER_BASE_ID = OB.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = OB.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = OB.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = OB.WORKORDER_SUB_ID
	AND O.SEQUENCE_NO = OB.SEQUENCE_NO
WHERE (O.WORKORDER_TYPE = 'M' OR (O.WORKORDER_TYPE = 'W' AND O.[STATUS] IN ('F', 'U'))
	)
-- TT 6/19/2020  263 RECORDS
	AND O.RESOURCE_ID = 'P1F1-PNT-SAND'
--	AND CAST(CAST(OB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) LIKE 'PROCESS IAW SKF_520%PREPARE SURFACE AS REQUIRED%LIGHTLY SAND TO REACTIVATE '
-- TT 6/19/2020  127 RECORDS
--	AND CAST(CAST(OB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) LIKE 'PROCESS IAW SKF_520%PREPARE SURFACE AS REQUIRED%LIGHTLY SAND TO REACTIVATE'
-- TT 6/19/2020  23 RECORDS
	AND CAST(CAST(OB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) LIKE '%PREPARE SURFACE AS REQUIRED%'
--	AND O.WORKORDER_BASE_ID = '232W2221-74'

select * from #t1

/*
BEGIN TRANSACTION;
UPDATE OB
SET OB.BITS = T.[AFTER_OB]
	, OB.BITS_LENGTH = T.[AFTER_BITLEN]
FROM OPERATION_BINARY OB
INNER JOIN #T1 T
	ON OB.WORKORDER_TYPE = T.WORKORDER_TYPE
	AND OB.WORKORDER_BASE_ID = T.WORKORDER_BASE_ID
	AND OB.WORKORDER_LOT_ID	= T.WORKORDER_LOT_ID
	AND OB.WORKORDER_SPLIT_ID = T.WORKORDER_SPLIT_ID
	AND OB.WORKORDER_SUB_ID = T.WORKORDER_SUB_ID
	AND OB.SEQUENCE_NO = T.SEQUENCE_NO
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/