USE LIVE
GO

DROP TABLE #T1

; WITH CTE_BASE AS		
(SELECT WO.BASE_ID + '/' + WO.LOT_ID + CASE WHEN WO.SPLIT_ID = 0 THEN '' ELSE '.' + WO.SPLIT_ID END AS JOB_ID		
	, WO.BASE_ID 	
	, WO.LOT_ID 	
	, WO.SPLIT_ID	
	, WO.SUB_ID	
	, WO.[STATUS] AS WO_STATUS	
	, dbo.ufn_CurrOp(WO.[TYPE], WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID) AS CURRENT_OP	
	, MAX(O.SEQUENCE_NO) AS LAST_CLOSED_OPS
FROM OPERATION O
INNER JOIN WORK_ORDER WO
	ON WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O.WORKORDER_SUB_ID
	AND WO.[TYPE] = O.WORKORDER_TYPE
WHERE O.WORKORDER_TYPE = 'W'
	AND O.[STATUS] IN ('C')
	AND WO.[STATUS] IN ('R') --, 'F')
	AND ISNULL(WO.[CLOSE_DATE], GETDATE()) > GETDATE() - 30
GROUP BY WO.[TYPE]
	, WO.BASE_ID 	
	, WO.LOT_ID 	
	, WO.SPLIT_ID	
	, WO.SUB_ID	
	, WO.[STATUS]
)

, CTE_DATES AS
(SELECT CTE.JOB_ID		
	, CTE.BASE_ID 	
	, CTE.LOT_ID 	
	, CTE.SPLIT_ID	
	, CTE.SUB_ID	
	, CTE.WO_STATUS	
	, CTE.CURRENT_OP
	, O1.RESOURCE_ID AS CURR_RESOURCEID
	, O1.CLOSE_DATE AS CURR_CLOSE
	, O1.STATUS_EFF_DATE AS CURR_STATUSDATE
	, CTE.LAST_CLOSED_OPS
	, O2.RESOURCE_ID AS LAST_RESOURCEID
	, O2.CLOSE_DATE AS LAST_CLOSE
	, O2.STATUS_EFF_DATE AS LAST_STATUSDATE
FROM CTE_BASE CTE
LEFT OUTER JOIN OPERATION O1		
	ON O1.WORKORDER_TYPE = 'W'	
	AND CTE.BASE_ID = O1.WORKORDER_BASE_ID	
	AND CTE.LOT_ID = O1.WORKORDER_LOT_ID	
	AND CTE.SPLIT_ID = O1.WORKORDER_SPLIT_ID	
	AND CTE.SUB_ID = O1.WORKORDER_SUB_ID	
	AND CTE.CURRENT_OP = O1.SEQUENCE_NO	
LEFT OUTER JOIN OPERATION O2		
	ON O2.WORKORDER_TYPE = 'W'	
	AND CTE.BASE_ID = O2.WORKORDER_BASE_ID	
	AND CTE.LOT_ID = O2.WORKORDER_LOT_ID	
	AND CTE.SPLIT_ID = O2.WORKORDER_SPLIT_ID	
	AND CTE.SUB_ID = O2.WORKORDER_SUB_ID	
	AND CTE.LAST_CLOSED_OPS = O2.SEQUENCE_NO	
)
--> SELECT * FROM CTE_DATES

SELECT CTE.JOB_ID		
	, CTE.BASE_ID 	
	, CTE.LOT_ID 	
	, CTE.SPLIT_ID	
	, CTE.SUB_ID	
	, CTE.WO_STATUS	
	--, CTE.CURRENT_OP
	--, CTE.CURR_RESOURCEID
	--, CTE.CURR_CLOSE
	--, CTE.CURR_STATUSDATE
	, CTE.LAST_CLOSED_OPS
	, CTE.LAST_RESOURCEID
	, CTE.LAST_CLOSE
	, CTE.LAST_STATUSDATE
	, O.SEQUENCE_NO	
	, O.RESOURCE_ID
	, O.[STATUS] AS OP_STATUS
	, SR.USER_6
	, SR.USER_7
	, SR.USER_8
	, CASE 
		WHEN SR.USER_6 IN ('CHEMICAL PROCESSING', 'PAINT', 'PENETRANT') AND LAST_CLOSE >= GETDATE()-0.5 THEN 'NO'
		ELSE 'YES'
	END AS DECISION
INTO #T1
FROM CTE_DATES CTE		
LEFT OUTER JOIN OPERATION O		
	ON O.WORKORDER_TYPE = 'W'	
	AND CTE.BASE_ID = O.WORKORDER_BASE_ID	
	AND CTE.LOT_ID = O.WORKORDER_LOT_ID	
	AND CTE.SPLIT_ID = O.WORKORDER_SPLIT_ID	
	AND CTE.SUB_ID = O.WORKORDER_SUB_ID	
	AND CTE.CURRENT_OP > O.SEQUENCE_NO	
LEFT OUTER JOIN SHOP_RESOURCE SR
	ON SR.ID = O.RESOURCE_ID
WHERE O.[STATUS] NOT IN ('C', 'X')	
ORDER BY JOB_ID		
	, BASE_ID 	
	, LOT_ID 	
	, SPLIT_ID	
	, SUB_ID	
	, SEQUENCE_NO	

SELECT * FROM #T1 WHERE DECISION = 'YES'

/*
BEGIN TRANSACTION;
UPDATE OPERATION
SET CLOSE_DATE = GETDATE()
, [STATUS] = 'C'
FROM OPERATION O
INNER JOIN #T1 T
ON O.WORKORDER_TYPE = 'W'
AND O.WORKORDER_BASE_ID = T.BASE_ID 
AND O.WORKORDER_LOT_ID = T.LOT_ID 
AND O.WORKORDER_SPLIT_ID = T.SPLIT_ID 
AND O.WORKORDER_SUB_ID = T.SUB_ID 
AND O.SEQUENCE_NO = T.SEQUENCE_NO
WHERE DECISION = 'YES'
--> COMMIT TRANSACTION;
--> 494 ROWS UPDATED
--> 108 ROWS UPDATED
--> ROLLBACK TRANSACTION;
*/