USE DataWarehouse
GO

DECLARE @STARTDATE DATE = '1/1/2019'
, @ENDDATE DATE = '4/1/2020'

-- Visual Enterprise Reports > Labor Reports > Open Labor Tickets
SELECT ADP.[Reports To Name] AS SUPERVISOR
	, LT.EMPLOYEE_ID
	, LT.TRANSACTION_DATE
	, DATEDIFF(DD, LT.TRANSACTION_DATE, GETDATE()) AS DAYS_LATE
	, EE.LAST_NAME
	, EE.FIRST_NAME
	, EE.DEPARTMENT_ID
	, CASE
		WHEN SR.USER_1 = 'A' THEN 'FIN'
		WHEN SR.USER_1 = 'M' THEN 'MFG'
		WHEN SR.USER_1 = 'O' THEN 'OUTREACH'
		WHEN SR.USER_1 = 'B' THEN 'BALLARD'
		ELSE 'OTHER'
	END AS [BUSINESS_UNIT]
	, LT.WORKORDER_BASE_ID 
	--, LT.WORKORDER_LOT_ID
	--, LT.WORKORDER_SPLIT_ID 
	--, LT.WORKORDER_SUB_ID
	, LT.RESOURCE_ID
	, LT.HOURS_WORKED
	, EE.SHIFT_ID
	, LT.TRANSACTION_ID
	, L.[Time In]
	, L.[Time Out]
	, CASE
		WHEN LT.WORKORDER_BASE_ID IS NULL THEN 'Indirect'
		ELSE 'Direct'
	END AS [Ticket Type]
FROM LABOR_TICKET AS LT
INNER JOIN EMPLOYEE AS EE
	ON LT.EMPLOYEE_ID = EE.ID
LEFT OUTER JOIN SHOP_RESOURCE_SITE SR
	ON LT.RESOURCE_ID = SR.RESOURCE_ID
LEFT OUTER JOIN [SQL-LAB-2].LIVESupplemental.DBO.ADP_EMP AS ADP
	ON CONVERT(NVARCHAR(15), RIGHT('0000' + EE.ID, 6)) = ADP.[FILE NUMBER]
LEFT OUTER JOIN SimpleWarehouse.ADP_Labor AS L
	ON CONVERT(NVARCHAR(15), RIGHT('0000' + EE.ID, 6)) = L.[FILE NUMBER]
	AND LT.TRANSACTION_DATE = L.[Pay Date]
WHERE LT.ACT_CLOCK_OUT IS NULL
	AND LT.ACT_CLOCK_IN IS NOT NULL
	AND LT.HOURS_WORKED IS NULL
	AND (LT.TRANSACTION_DATE >= @StartDate 
	AND LT.TRANSACTION_DATE < @EndDate)
--	AND ADP.[Reports To Name] IN (@SUPERVISOR)
	--AND CASE
	--	WHEN SR.USER_1 = 'A' THEN 'FIN'
	--	WHEN SR.USER_1 = 'M' THEN 'MFG'
	--	WHEN SR.USER_1 = 'O' THEN 'OUTREACH'
	--	WHEN SR.USER_1 = 'B' THEN 'BALLARD'
	--	ELSE 'OTHER'
	--END IN (@BUS_UNIT)