USE LIVESupplemental
GO

SELECT tlt.*
, O.RESOURCE_ID
, SR.[DESCRIPTION]
FROM tlt_holly_report TLT
INNER JOIN DataWarehouse.dbo.OPERATION O
ON TLT.BASE_ID = O.WORKORDER_BASE_ID
AND TLT.LOT_ID = O.WORKORDER_LOT_ID
AND TLT.SEQ_NO = O.SEQUENCE_NO
INNER JOIN DataWarehouse.dbo.SHOP_RESOURCE SR
ON O.RESOURCE_ID = SR.ID

--select * from datawarehouse.dbo.OPERATION where WORKORDER_base_id = '1577054' AND SEQUENCE_NO = '320'