use live
go

SELECT 
	WO.[STATUS]
	, OT.ID
	, O.WORKORDER_BASE_ID
	, O.RESOURCE_ID
	, OT.[DESCRIPTION]
	, O.OPERATION_TYPE
	, WO.DESIRED_WANT_DATE
	, WO.DESIRED_QTY
	, DSL.DEMAND_BASE_ID
	, WO.PART_ID
	, DSL.DEMAND_SEQ_NO
FROM   
	DEMAND_SUPPLY_LINK DSL
LEFT OUTER JOIN 
	(OPERATION O 
	INNER JOIN WORK_ORDER WO 
		ON  O.WORKORDER_TYPE = WO.[TYPE]
		AND O.WORKORDER_BASE_ID = WO.BASE_ID
		AND O.WORKORDER_LOT_ID = WO.LOT_ID
		AND O.WORKORDER_SPLIT_ID = WO.SPLIT_ID
		AND O.WORKORDER_SUB_ID = WO.SUB_ID
	INNER JOIN OPERATION_TYPE OT
		ON O.OPERATION_TYPE = OT.ID
	) 
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	and DSL.SUPPLY_TYPE = 'WO'
WHERE  
	(O.RESOURCE_ID = 'AUB-pri' OR O.RESOURCE_ID='AUB-tc') 
	AND WO.STATUS='R' 
	AND (OT.ID LIKE 'f%' OR OT.ID LIKE 'm%')
ORDER BY 
	OT.ID
	, O.OPERATION_TYPE
	, WO.DESIRED_WANT_DATE

