USE LIVE
GO

SELECT OT.ID AS OP_TYPE
	, OT.[DESCRIPTION] AS OPTYPE_DESC
	, OT.RESOURCE_ID
	, SR.[DESCRIPTION] AS RESOURCE_DESC
	, CASE
		WHEN (SR.[STATUS] != 'O' OR SR.[STATUS] IS NULL) THEN 'ACTIVE'
		ELSE 'OBSOLETE'
	END AS [RESOURCE_STATUS]
	, CAST(CAST(OTB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [OPTYPE_BINARY]
FROM OPERATION_TYPE OT
INNER JOIN OPER_TYPE_BINARY OTB
	ON OTB.OPERATION_TYPE_ID = OT.ID
LEFT OUTER JOIN SHOP_RESOURCE SR
	ON OT.RESOURCE_ID = SR.ID
WHERE CAST(CAST(OTB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) NOT LIKE '%DO NOT USE%'
	AND OT.ID IN (@OPTYPE) 
	AND OT.RESOURCE_ID IN (@RESOURCEID)
	AND CASE
		WHEN (SR.[STATUS] != 'O' OR SR.[STATUS] IS NULL) THEN 'ACTIVE'
		ELSE 'OBSOLETE'
	END IN (@STATUS)
	AND (OT.ID LIKE @OPTYPESEARCH + '%' OR @OPTYPESEARCH IS NULL)
	AND (OT.[DESCRIPTION] LIKE  '%'+ @OPTYPEDESC + '%' OR @OPTYPEDESC IS NULL)
	AND (CAST(CAST(OTB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) LIKE '%'+ @OTBSPECS + '%' OR @OTBSPECS IS NULL)


SELECT O.WORKORDER_TYPE AS [TYPE]
	, O.WORKORDER_BASE_ID AS [BASE_ID]
	, O.WORKORDER_LOT_ID AS [LOT]
	, O.WORKORDER_SPLIT_ID AS [SPLIT]
	, O.WORKORDER_SUB_ID AS [SUB]
	, O.SEQUENCE_NO AS [SEQ_NO]
	, O.OPERATION_TYPE AS [OPTYPE]
	, O.RESOURCE_ID
	, OB.[SPECS]
FROM OPERATION AS O
INNER JOIN SHOP_RESOURCE AS SR
	ON O.RESOURCE_ID = SR.ID
INNER JOIN [SKILL_OPERATION_BINARY] OB
	ON OB.WORKORDER_TYPE = O.WORKORDER_TYPE
	AND OB.WORKORDER_BASE_ID= O.WORKORDER_BASE_ID
	AND OB.WORKORDER_LOT_ID= O.WORKORDER_LOT_ID
	AND OB.WORKORDER_SPLIT_ID= O.WORKORDER_SPLIT_ID
	AND OB.WORKORDER_SUB_ID = O.WORKORDER_SUB_ID
	AND OB.SEQUENCE_NO = O.SEQUENCE_NO
WHERE O.[WORKORDER_TYPE] = 'M'
	AND O.OPERATION_TYPE IN (@OPTYPE)
