USE LIVE
GO

--SELECT * FROM LIVESUPPLEMENTAL.DBO.OpUpdate20210428
--> 10236 RECORDS

DROP TABLE #T1

SELECT O.WORKORDER_TYPE
	, O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.[SETUP_HRS] AS OP_SETUP_HRS
--	, CAST(U.[SETUP_HRS] AS DECIMAL(8,3)) AS [SETUP_HRS]
	, U.[SETUP_HRS]
	, O.[RUN_HRS] AS OP_RUN_HRS
--	, CAST(U.[RUN_HRS] AS DECIMAL(7,2)) AS [RUN_HRS]
	, U.[RUN_HRS]
	, O.[RUN_TYPE] AS OP_RUN_TYPE
	, U.[RUN_TYPE]
	, O.[MOVE_HRS] AS OP_MOVE_HRS
	, U.[MOVE_HRS]
	, O.[MINIMUM_MOVE_QTY] AS OP_MINIMUM_MOVE_QTY
	, U.[MINIMUM_MOVE_QTY]
	, O.[TRANSIT_DAYS] AS OP_TRANSIT_DAYS
	, U.[TRANSIT_DAYS]
INTO #T1
FROM [LIVESupplemental].dbo.[OpUpdate20210428] U
INNER JOIN OPERATION O
	ON O.WORKORDER_BASE_ID = U.Base_ID
	AND O.WORKORDER_LOT_ID = U.Lot_ID
	AND O.WORKORDER_SPLIT_ID = '0'
	AND O.WORKORDER_SUB_ID = U.Sub_ID
	AND O.WORKORDER_TYPE = 'M'
	AND O.SEQUENCE_NO = U.SEQUENCE_NO
	AND O.RESOURCE_ID = U.Resource_ID
WHERE (1=1)
	--AND O.[SETUP_HRS] != CAST(U.[SETUP_HRS] AS DECIMAL(8,3))
--	AND U.[RUN_HRS] != O.[RUN_HRS]
	--AND O.[RUN_TYPE] != U.[RUN_TYPE]
	--AND O.[MOVE_HRS] != U.[MOVE_HRS]
	--AND O.[MINIMUM_MOVE_QTY] != U.[MINIMUM_MOVE_QTY]
	--AND O.[TRANSIT_DAYS] != U.[TRANSIT_DAYS]
--	AND U.[RUN_TYPE] = 'HRS/PC'
--	AND U.RESOURCE_ID LIKE 'P2M1-%' --IN ('P2M1-DB-VIBRA', 'P2M1-CNC-4')
--	AND U.SEQUENCE_NO IN ('420', '350', '360')
--	AND U.[SETUP_HRS] = '0.10'

SELECT * FROM #T1   WHERE [WORKORDER_Base_ID] = '140T2502-43'

SELECT * FROM OPERATION WHERE [WORKORDER_Base_ID] = '140T2502-43'

/*
BEGIN TRANSACTION;
UPDATE OPERATION     
SET [RUN_HRS] = T.[RUN_HRS]
FROM OPERATION O
INNER JOIN #T1 T
	ON O.WORKORDER_TYPE = T.WORKORDER_TYPE
	AND O.WORKORDER_BASE_ID = T.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID	= T.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = T.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = T.WORKORDER_SUB_ID
	AND O.SEQUENCE_NO = T.SEQUENCE_NO
	AND O.RESOURCE_ID = T.Resource_ID
WHERE O.[WORKORDER_Base_ID] = '140T2502-43'

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

*/

SELECT O.WORKORDER_TYPE
	, O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.[SETUP_HRS] 
	, T.[SETUP_HRS]
	, O.[RUN_HRS] 
	, T.[RUN_HRS]
FROM OPERATION O
INNER JOIN [LIVESupplemental].dbo.[OpUpdate20210428] T
	ON O.WORKORDER_TYPE = 'M'
	AND O.WORKORDER_BASE_ID = T.BASE_ID
	AND O.WORKORDER_LOT_ID = T.LOT_ID
	AND O.WORKORDER_SPLIT_ID = '0'
	AND O.WORKORDER_SUB_ID = T.SUB_ID
	AND O.SEQUENCE_NO = T.SEQUENCE_NO
	AND O.RESOURCE_ID = T.Resource_ID

WHERE O.[RUN_HRS] != T.[RUN_HRS]

--> tt20210428: records TOTAL

