USE LIVE
GO

DROP TABLE #T1

SELECT OB.WORKORDER_TYPE
	, OB.WORKORDER_BASE_ID
	, OB.WORKORDER_LOT_ID
	, OB.WORKORDER_SPLIT_ID
	, OB.WORKORDER_SUB_ID
	, OB.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.OPERATION_TYPE
	, O.[STATUS]
	, CAST(CAST(OB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [OB_BIN]
	, OB.BITS AS [OB_BINARY]
	, OB.BITS_LENGTH AS [OB_BITLEN]
	, CAST(CAST(OTB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [OTB_BIN]
	, OTB.BITS AS [OTB_BINARY]
	, OTB.BITS_LENGTH AS [OTB_BITLEN]
INTO #T1
FROM OPERATION O
INNER JOIN OPER_TYPE_BINARY OTB
	ON OTB.OPERATION_TYPE_ID = O.OPERATION_TYPE
INNER JOIN OPERATION_BINARY OB
	ON O.WORKORDER_TYPE = OB.WORKORDER_TYPE
	AND O.WORKORDER_BASE_ID = OB.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = OB.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = OB.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = OB.WORKORDER_SUB_ID
	AND O.SEQUENCE_NO = OB.SEQUENCE_NO
WHERE (O.WORKORDER_TYPE = 'M')
--> tt20210804: 4102 records TOTAL
--> FILL IN THE OP_TYPES:
	AND OPERATION_TYPE IN ('56325', 'F17.02N', 'F17.31N', 'F17.37B', 'F17.39', 'F17.41N', 'F17.50B', 'F18.13N', 'F18.18B')

SELECT WORKORDER_TYPE
	, WORKORDER_BASE_ID 
	, WORKORDER_LOT_ID
	, WORKORDER_SPLIT_ID
	, WORKORDER_SUB_ID
	, SEQUENCE_NO
	, RESOURCE_ID
	, OPERATION_TYPE
	, [STATUS]
	, [OB_BIN]
	, [OB_BINARY]
	, [OB_BITLEN]
	, [OTB_BIN]
	, [OTB_BINARY]
	, [OTB_BITLEN] 
FROM #T1 

/*
BEGIN TRANSACTION;
UPDATE OB     
SET OB.BITS = T.[OTB_BINARY]
	, OB.BITS_LENGTH = [OTB_BITLEN] 
--SELECT *
FROM OPERATION_BINARY OB
INNER JOIN #T1 T
	ON OB.WORKORDER_TYPE = T.WORKORDER_TYPE
	AND OB.WORKORDER_BASE_ID = T.WORKORDER_BASE_ID
	AND OB.WORKORDER_LOT_ID	= T.WORKORDER_LOT_ID
	AND OB.WORKORDER_SPLIT_ID = T.WORKORDER_SPLIT_ID
	AND OB.WORKORDER_SUB_ID = T.WORKORDER_SUB_ID
	AND OB.SEQUENCE_NO = T.SEQUENCE_NO
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

*/

SELECT OB.WORKORDER_TYPE
	, OB.WORKORDER_BASE_ID
	, OB.WORKORDER_LOT_ID
	, OB.WORKORDER_SPLIT_ID
	, OB.WORKORDER_SUB_ID
	, OB.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.OPERATION_TYPE
	, O.[STATUS]
	, CAST(CAST(OB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [OB_BIN]
	, OB.BITS AS [OB_BINARY]
	, OB.BITS_LENGTH AS [OB_BITLEN]
	, CAST(CAST(OTB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [OTB_BIN]
	, OTB.BITS AS [OTB_BINARY]
	, OTB.BITS_LENGTH AS [OTB_BITLEN]
FROM OPERATION O
INNER JOIN OPER_TYPE_BINARY OTB
	ON OTB.OPERATION_TYPE_ID = O.OPERATION_TYPE
INNER JOIN OPERATION_BINARY OB
	ON O.WORKORDER_TYPE = OB.WORKORDER_TYPE
	AND O.WORKORDER_BASE_ID = OB.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = OB.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = OB.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = OB.WORKORDER_SUB_ID
	AND O.SEQUENCE_NO = OB.SEQUENCE_NO
WHERE (O.WORKORDER_TYPE = 'M')
	AND CAST(CAST(OB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) != CAST(CAST(OTB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) 
--> FILL IN THE OP_TYPES:
	AND OPERATION_TYPE IN ('56325', 'F17.02N', 'F17.31N', 'F17.37B', 'F17.39', 'F17.41N', 'F17.50B', 'F18.13N', 'F18.18B')
