USE [LIVESupplemental]
GO

/****** Object:  Table [dbo].[OpUpd20211104]    Script Date: 11/4/2021 9:27:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--CREATE TABLE [dbo].OpUpd20211104 (
--	[Base_ID] [nvarchar](50) NULL,
--	[LOT_ID] [nvarchar](5) NULL,
--	[SUB_ID] [nvarchar](5) NULL,
--	[SEQUENCE_NO] [nvarchar](5) NULL,
--	[RESOURCE_ID] [nvarchar](50) NULL,
--	[MOVE_HRS] [INTEGER] NULL
--) ON [PRIMARY]
--GO

SELECT * FROM OpUpd20211104 U ORDER BY BASE_ID, SEQUENCE_NO
--> 3382 RECORDS

DROP TABLE #T1

SELECT O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID 
	, O.WORKORDER_SUB_ID 
	, O.WORKORDER_TYPE
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	--, U.[Base_ID] 
	--, U.[LOT_ID]
	--, U.[SUB_ID]
	--, U.[SEQUENCE_NO] AS UPD_SEQNO
	--, U.[RESOURCE_ID] AS UPD_RESOURCE_ID
	--, U.[MOVE_HRS]
INTO #T1
FROM OpUpd20211104 U
--LEFT OUTER JOIN LIVE.dbo.OPERATION O
INNER JOIN LIVE.dbo.OPERATION O
	ON U.BASE_ID = O.WORKORDER_BASE_ID
	AND U.LOT_ID = O.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = '0'
	AND U.SUB_ID = O.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = 'M'
	AND U.SEQUENCE_NO = O.SEQUENCE_NO
	AND U.RESOURCE_ID = O.RESOURCE_ID
--> 3371 RECORDS

SELECT * FROM #T1 ORDER BY WORKORDER_BASE_ID, SEQUENCE_NO

/*
USE LIVE
GO

BEGIN TRANSACTION;
UPDATE OPERATION
SET MOVE_HRS = 0.00
FROM LIVE.dbo.OPERATION O
INNER JOIN #T1 U
	ON O.WORKORDER_BASE_ID = U.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = U.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = U.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = U.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = U.WORKORDER_TYPE
	AND O.SEQUENCE_NO = U.SEQUENCE_NO
	AND O.RESOURCE_ID = U.RESOURCE_ID
--> 3371 ROWS AFFECTED
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
--> tt20211104: 3371 RECORDS UPDATED
*/

SELECT O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID 
	, O.WORKORDER_SUB_ID 
	, O.WORKORDER_TYPE
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.MOVE_HRS
	--, U.[Base_ID] 
	--, U.[LOT_ID]
	--, U.[SUB_ID]
	--, U.[SEQUENCE_NO] AS UPD_SEQNO
	--, U.[RESOURCE_ID] AS UPD_RESOURCE_ID
	--, U.[MOVE_HRS]
FROM LIVESupplemental.dbo.OpUpd20211104 U
--LEFT OUTER JOIN LIVE.dbo.OPERATION O
INNER JOIN LIVE.dbo.OPERATION O
	ON U.BASE_ID = O.WORKORDER_BASE_ID
	AND U.LOT_ID = O.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = '0'
	AND U.SUB_ID = O.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = 'M'
	AND U.SEQUENCE_NO = O.SEQUENCE_NO
	AND U.RESOURCE_ID = O.RESOURCE_ID
WHERE O.MOVE_HRS != 0.00
--> 3371 RECORDS
