USE LIVE
GO

SELECT * FROM [LIVESupplemental].dbo.[OpType20210419] U
-- 1125 RECORDS


SELECT U.[OPERATION TYPE ID]
, U.[SETUP_HRS]
, U.[RUN]
, U.[RUN_TYPE]
--, [MOVE_HRS]
--, [TRANSIT_DAYS]
--, [MINIMUM_MOVE_QTY]
--, [SERVICE_ID]
, OT.[ID]
, OT.[SETUP_HRS]
, OT.[RUN]
, OT.[RUN_TYPE]
FROM OPERATION_TYPE OT
INNER JOIN [LIVESupplemental].dbo.[OpType20210419] U
--LEFT OUTER JOIN [LIVESupplemental].dbo.[OpType20210419] U
	ON OT.ID = U.[OPERATION TYPE ID]
--> tt20210406: 1125 records TOTAL

/*
BEGIN TRANSACTION;
UPDATE OPERATION_TYPE     
SET [SETUP_HRS] = CONVERT(DECIMAL(20,8), U.[SETUP_HRS])
, [RUN] = CONVERT(DECIMAL(20,8), U.[RUN])
, [RUN_TYPE] = U.[RUN_TYPE]
, [MOVE_HRS] = NULL
, [TRANSIT_DAYS] = NULL
, [MINIMUM_MOVE_QTY] = NULL
, [SERVICE_ID] = NULL
FROM OPERATION_TYPE OT
INNER JOIN [LIVESupplemental].dbo.[OpType20210419] U
	ON OT.[ID] = U.[OPERATION TYPE ID]
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
--> tt20210406:  RECORDS UPDATED
*/

SELECT U.[OPERATION TYPE ID]
, U.[SETUP_HRS]
, U.[RUN]
, U.[RUN_TYPE]
, OT.[MOVE_HRS]
, OT.[TRANSIT_DAYS]
, OT.[MINIMUM_MOVE_QTY]
, OT.[SERVICE_ID]
, OT.[ID]
, OT.[SETUP_HRS]
, OT.[RUN]
, OT.[RUN_TYPE]
FROM OPERATION_TYPE OT
INNER JOIN [LIVESupplemental].dbo.[OpType20210419] U
	ON OT.ID = U.[OPERATION TYPE ID]
WHERE U.[SETUP_HRS] != OT.[SETUP_HRS]
	OR U.[RUN] != OT.[RUN]
	OR U.[RUN_TYPE] != OT.[RUN_TYPE]
	OR [MOVE_HRS] IS NOT NULL
	OR [TRANSIT_DAYS] IS NOT NULL
	OR [MINIMUM_MOVE_QTY] IS NOT NULL
	OR [SERVICE_ID] IS NOT NULL

--> tt20210316: 1125 records TOTAL

