use DataWarehouse
go	

DECLARE @STARTDATE	DATE = '10/30/2018'	
IF OBJECT_ID('tempdb..#t1') IS NOT NULL DROP TABLE #t1	
IF OBJECT_ID('tempdb..#t2') IS NOT NULL DROP TABLE #t2
IF OBJECT_ID('tempdb..#t3') IS NOT NULL DROP TABLE #t3
IF OBJECT_ID('tempdb..#CTE_COMBINED') IS NOT NULL DROP TABLE #CTE_COMBINED
	
select WO.BASE_ID	
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_WANT_DATE
	, WO.PART_ID
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, SR.USER_2
	, SR.USER_3
	, SR.USER_4
	, SR.USER_5
	, O.OPERATION_TYPE
into #t1
from WORK_ORDER WO	
INNER JOIN OPERATION O	
	ON WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O.WORKORDER_SUB_ID
	AND WO.[TYPE] = O.WORKORDER_TYPE
INNER JOIN SHOP_RESOURCE SR	
	ON SR.ID = O.RESOURCE_ID
	AND SR.USER_2 IN ('PAINT')	
	AND SR.USER_5 = 'AP1'	
WHERE WO.DESIRED_WANT_DATE >= @STARTDATE	
AND WO.[STATUS] IN ('C', 'R')	

SELECT T.* 
	, CAST(CAST(OB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) OPERATION_BINARY
	, CAST(CAST(OTB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) OPTYPE_BINARY
INTO #T2
FROM #T1 T
LEFT OUTER JOIN OPER_TYPE_BINARY OTB	
	ON T.OPERATION_TYPE = OTB.OPERATION_TYPE_ID
	AND OTB.SITE_ID = 'SK01'
	AND OTB.[TYPE] = 'D'
LEFT OUTER JOIN OPERATION_BINARY OB	
	ON T.BASE_ID = OB.WORKORDER_BASE_ID
	AND T.LOT_ID = OB.WORKORDER_LOT_ID
	AND T.SPLIT_ID = OB.WORKORDER_SPLIT_ID
	AND T.SUB_ID = OB.WORKORDER_SUB_ID
	AND T.SEQUENCE_NO = OB.SEQUENCE_NO

SELECT *
INTO #T3
FROM #T2
WHERE (OPERATION_BINARY LIKE '%10-79%' OR OPTYPE_BINARY LIKE '%10-79%')
OR (OPERATION_BINARY LIKE '%10-60%' OR OPTYPE_BINARY LIKE '%10-60%')
OR (OPERATION_BINARY LIKE '%10-11%' OR OPTYPE_BINARY LIKE '%10-11%')


DECLARE @START	DATE = '10/30/2018'	
;

WITH CTE_LINKED as 	
(SELECT 'LINKED' AS [ORDER_TYPE]	
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, T.QTY * -1 AS TRACE_QTY
	, SL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, SL.SHIPPED_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
FROM DATAWAREHOUSE.dbo.SHIPPER_LINE SL	
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S	
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL	
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO	
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL	
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO	
    ON DSL.SUPPLY_TYPE = 'WO' 	
    AND DSL.SUPPLY_BASE_ID = WO.BASE_ID	
    AND DSL.SUPPLY_LOT_ID = WO.LOT_ID	
    AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID	
    AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 	
	AND WO.[TYPE] = 'W'
LEFT OUTER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS T	
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
WHERE SL.PACKLIST_ID IS NOT NULL	
	AND S.SHIPPED_DATE >= @START
	AND COL.PART_ID IS NOT NULL
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NOT NULL
)	
	
, CTE_UNLINKED as	
(SELECT 'UNLINKED1' AS [ORDER_TYPE]	
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, T.QTY * -1 AS TRACE_QTY
	, SL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, SL.SHIPPED_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
FROM DATAWAREHOUSE.dbo.SHIPPER_LINE SL	
INNER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS  T	
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL	
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S	
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO	
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO	
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SPLIT_ID = '0'
	AND WO.SUB_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL	
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE S.SHIPPED_DATE >= @START	
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NULL
----	
UNION ALL	
----	
SELECT 'UNLINKED2' AS [ORDER_TYPE]	
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, T.QTY * -1 AS TRACE_QTY
	, SL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, SL.SHIPPED_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
FROM DATAWAREHOUSE.dbo.SHIPPER_LINE SL	
INNER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS  T	
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL	
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN #T1 P	
	ON COL.PART_ID = P.PART_ID
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S	
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO	
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO	
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID + '/' + WO.SUB_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SPLIT_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL	
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE S.SHIPPED_DATE >= @START	
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NULL
----	
UNION ALL	
----	
SELECT 'UNLINKED3' AS [ORDER_TYPE]	
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, T.QTY * -1 AS TRACE_QTY
	, SL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, SL.SHIPPED_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
FROM DATAWAREHOUSE.dbo.SHIPPER_LINE SL	
INNER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS  T	
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL	
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S	
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO	
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO	
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID + '.' + WO.SPLIT_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SUB_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL	
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE S.SHIPPED_DATE >= @START	
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NULL
)	
	
, CTE_COMBINED AS	
(SELECT * 	
FROM CTE_LINKED	
UNION ALL	
SELECT * 	
FROM CTE_UNLINKED 	
)	
SELECT * 
INTO #CTE_COMBINED
FROM  CTE_COMBINED

--SELECT * FROM #T3

SELECT [ORDER_TYPE]
, CASE 
	WHEN (OPERATION_BINARY LIKE '%10-79%' OR OPTYPE_BINARY LIKE '%10-79%') THEN '10-79'
	WHEN (OPERATION_BINARY LIKE '%10-60%' OR OPTYPE_BINARY LIKE '%10-60%') THEN '10-60'
	WHEN (OPERATION_BINARY LIKE '%10-11%' OR OPTYPE_BINARY LIKE '%10-11%') THEN '10-11'
	ELSE ''
END AS PAINT
, CASE
	WHEN (OPERATION_BINARY LIKE '%TYPE 1&2%' OR OPTYPE_BINARY LIKE '%TYPE 1&2%') THEN 'TYPE 1&2'
	WHEN (OPERATION_BINARY LIKE '%TYPE 2 & 3%' OR OPTYPE_BINARY LIKE '%TYPE 2 & 3%') THEN 'TYPE 2 & 3'
	WHEN (OPERATION_BINARY LIKE '%TYPE 2 AND 3%' OR OPTYPE_BINARY LIKE '%TYPE 2 AND 3%') THEN 'TYPE 2 AND 3'
	WHEN (OPERATION_BINARY LIKE '%TYPE II%' OR OPTYPE_BINARY LIKE '%TYPE II%') THEN 'TYPE II'
	WHEN (OPERATION_BINARY LIKE '%TYPE I%' OR OPTYPE_BINARY LIKE '%TYPE I%') THEN 'TYPE I'
	WHEN (OPERATION_BINARY LIKE '%TYPE 1%' OR OPTYPE_BINARY LIKE '%TYPE 1%') THEN 'TYPE 1'
	WHEN (OPERATION_BINARY LIKE '%TYPE 2%' OR OPTYPE_BINARY LIKE '%TYPE 2%') THEN 'TYPE 2'
	WHEN (OPERATION_BINARY LIKE '%TYPE 3%' OR OPTYPE_BINARY LIKE '%TYPE 3%') THEN 'TYPE 3'
	ELSE ''
END AS PAINT_TYPE
, CTE.CUSTOMER_ID
, CTE.CUST_ORDER_ID
, CTE.COL_LINE
, CTE.COL_ORDER_QTY
, CTE.TOTAL_SHIPPED_QTY
, T.BASE_ID
, T.LOT_ID
, T.SPLIT_ID
, T.SUB_ID
, T.DESIRED_WANT_DATE
, T.PART_ID
, P.BUYER_USER_ID
--, SEQUENCE_NO
, T.RESOURCE_ID
, T.USER_2
, T.USER_3
, T.USER_4
, T.USER_5
--, T.OPERATION_TYPE
, T.OPERATION_BINARY
, T.OPTYPE_BINARY
FROM #T3 T
LEFT OUTER JOIN #CTE_COMBINED CTE
ON T.BASE_ID = CTE.BASE_ID
AND T.LOT_ID = CTE.LOT_ID
AND T.SPLIT_ID = CTE.SPLIT_ID
AND T.SUB_ID = CTE.SUB_ID
LEFT OUTER JOIN PART P
ON T.PART_ID = P.ID
GROUP BY [ORDER_TYPE]
, CTE.CUSTOMER_ID
, CTE.CUST_ORDER_ID
, CTE.COL_LINE
, CTE.COL_ORDER_QTY
, CTE.TOTAL_SHIPPED_QTY
, T.BASE_ID
, T.LOT_ID
, T.SPLIT_ID
, T.SUB_ID
, T.DESIRED_WANT_DATE
, T.PART_ID
, P.BUYER_USER_ID
--, SEQUENCE_NO
, T.RESOURCE_ID
, T.USER_2
, T.USER_3
, T.USER_4
, T.USER_5
--, T.OPERATION_TYPE
, T.OPERATION_BINARY
, T.OPTYPE_BINARY
ORDER BY CTE.CUSTOMER_ID
, CTE.CUST_ORDER_ID
, CTE.COL_LINE


--select * FROM #CTE_COMBINED CTE where base_id = '1508943'
