USE LIVESupplemental
GO

SELECT * FROM operator_variable_data WHERE OPERATION_TYPE_ID LIKE '%SKY%'

BEGIN TRANSACTION;
DELETE FROM operator_variable_data  WHERE OPERATION_TYPE_ID = 'SKY'
DELETE FROM operator_variable_data  WHERE OPERATION_TYPE_ID = 'SKY-P2'
DELETE FROM operator_variable_data  WHERE OPERATION_TYPE_ID = 'INSP-SKY'
DELETE FROM operator_variable_data  WHERE OPERATION_TYPE_ID = 'INSP-SKY-P2'

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

SELECT ID, USER_5 FROM LIVE.DBO.SHOP_RESOURCE WHERE ID LIKE '%PM%' AND (STATUS IN ('A') OR STATUS IS NULL) AND USER_5 IN ('AP1', 'AP2')

SELECT ID, USER_5 FROM LIVE.DBO.SHOP_RESOURCE WHERE ID LIKE '%-IN-FNL%' AND (STATUS IN ('A') OR STATUS IS NULL) AND USER_5 IN ('AP1', 'AP2')

SELECT * FROM LIVE.DBO.OPERATION_TYPE WHERE ID LIKE '%SKY%'
