SELECT CO.CUSTOMER_ID 
	, COL.CUST_ORDER_ID
	, COL.LINE_NO
	, COL.PART_ID
	, COL.SERVICE_CHARGE_ID
	, COL.MISC_REFERENCE
	, S.SHIPPED_DATE
	, CO.CREATE_DATE
	, ADP.[LOCATION]
	, CASE
		WHEN MAX(S.SHIPPED_DATE) IS NULL THEN 'NOT SHIPPED'
		ELSE 'SHIPPED'
	END AS CATEGORY
	, CASE
		WHEN CO.CUSTOMER_ID = 'BOE609' THEN 'CMP'
		ELSE 'NON-CMP'
	END AS CMP
	, CASE
		WHEN UDF.STRING_VAL = 'FIN_MFG' THEN
			CASE
				WHEN EXISTS		
					(SELECT 1	
					FROM LIVESUPPLEMENTAL.DBO.PLANNER_USER_ID_ReportSettings EX	
					WHERE P.PLANNER_USER_ID = EX.PLANNER_USER_ID	
					AND REPORT_NAME = 'Orders_created_vs_shipped_chart_daily'
					) THEN 'FIN'
				ELSE 'MFG'
			END
		ELSE UDF.STRING_VAL 
	END AS BUS_STREAM
FROM CUST_ORDER_LINE COL 
INNER JOIN CUSTOMER_ORDER CO 
	ON COL.CUST_ORDER_ID = CO.ID
LEFT OUTER JOIN PART P
	ON COL.PART_ID = P.ID
LEFT OUTER JOIN USER_DEF_FIELDS UDF
	ON UDF.DOCUMENT_ID = CO.CUSTOMER_ID
	AND PROGRAM_ID = 'VMCUSMNT'
	AND UDF.ID = 'UDF-0000072'
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL 
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID 
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO 
	AND DSL.DEMAND_TYPE = 'CO' 
LEFT OUTER JOIN WORK_ORDER WO 
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID 
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID 
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID 
	AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
	AND WO.[TYPE] = 'W'
	AND DSL.SUPPLY_TYPE IN ('WO', 'CP') 
LEFT OUTER JOIN SHIPPER_LINE SL 
	ON  COL.CUST_ORDER_ID = SL.CUST_ORDER_ID
	AND COL.LINE_NO = SL.CUST_ORDER_LINE_NO 
LEFT OUTER JOIN SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID
WHERE COL.PART_ID NOT LIKE 'UP%'
	AND (ISNULL(S.SHIPPED_DATE, CO.CREATE_DATE) >= '1/1/2019') 
		AND NOT EXISTS (SELECT 1 FROM CUSTOMER C
			WHERE C.ID = CO.CUSTOMER_ID 
				AND C.USER_9 LIKE 'O%'
			)
GROUP BY CO.CUSTOMER_ID 
	, COL.CUST_ORDER_ID
	, COL.LINE_NO
	, COL.PART_ID
	, P.PLANNER_USER_ID
	, COL.SERVICE_CHARGE_ID
	, COL.MISC_REFERENCE
	, S.SHIPPED_DATE
	, CO.CREATE_DATE
	, UDF.STRING_VAL 


