USE DataWarehouse
GO

DECLARE @START_DATE DATE = GETDATE() -1
DECLARE @END_DATE DATE = GETDATE() 
;
WITH CTE_INITIAL AS
(SELECT COL.CUST_ORDER_ID
	, COL.LINE_NO
	, COL.PART_ID
	, CASE
		WHEN MAX(S.SHIPPED_DATE) IS NULL THEN 'Incoming Cust Orders'
		ELSE 'Shipped'
	END AS CATEGORY
	, CASE
		WHEN CO.CUSTOMER_ID = 'BOE609' THEN 'CMP'
		ELSE 'NON-CMP'
	END AS CMP
	, CASE 
		WHEN UDF.STRING_VAL = 'FIN_MFG' THEN 
			CASE
				WHEN P.PLANNER_USER_ID IN ('NA', 'FIN', '605F','609F') THEN 'FIN'
				ELSE 'MFG'
			END
		ELSE UDF.STRING_VAL 
	END AS BUS_STREAM
	, CASE
		WHEN COALESCE(COL.PART_ID, COL.SERVICE_CHARGE_ID, COL.MISC_REFERENCE, '') = '' THEN 0
		WHEN SL.SHIPPED_QTY <= 0 THEN 0 -- RETURNS
		WHEN COL.ORDER_QTY <= 0 THEN 0
		ELSE 1
	END AS CNTLINE 
FROM CUST_ORDER_LINE COL 
INNER JOIN CUSTOMER_ORDER CO 
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN CUSTOMER C
	ON CO.CUSTOMER_ID = C.ID
LEFT OUTER JOIN PART P
	ON COL.PART_ID = P.ID
LEFT OUTER JOIN USER_DEF_FIELDS UDF
	ON UDF.DOCUMENT_ID = CO.CUSTOMER_ID
	AND PROGRAM_ID = 'VMCUSMNT'
	AND UDF.ID = 'UDF-0000072'
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL 
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID 
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO 
	AND DSL.DEMAND_TYPE = 'CO' 
LEFT OUTER JOIN WORK_ORDER WO 
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID 
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID 
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID 
	AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
	AND WO.[TYPE] = 'W'
	AND DSL.SUPPLY_TYPE IN ('WO', 'CP') 
LEFT OUTER JOIN SHIPPER_LINE SL 
	ON  COL.CUST_ORDER_ID = SL.CUST_ORDER_ID
	AND COL.LINE_NO = SL.CUST_ORDER_LINE_NO 
LEFT OUTER JOIN SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID
WHERE COL.PART_ID NOT LIKE 'UP%'
	AND (ISNULL(S.SHIPPED_DATE, CO.CREATE_DATE) >= @START_DATE  
		AND ISNULL(S.SHIPPED_DATE, CO.CREATE_DATE) < @END_DATE) 
		AND C.USER_9 NOT LIKE 'O%'   -- REMOVE BusSolutions
GROUP BY CO.CUSTOMER_ID
	, CO.CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO
	, COL.PART_ID
	, CASE
		WHEN CO.CUSTOMER_ID = 'BOE609' THEN 'CMP'
		ELSE 'NON-CMP'
	END 
	, CASE 
		WHEN UDF.STRING_VAL = 'FIN_MFG' THEN 
			CASE
				WHEN P.PLANNER_USER_ID IN ('NA', 'FIN', '605F','609F') THEN 'FIN'
				ELSE 'MFG'
			END
		ELSE UDF.STRING_VAL 
	END
	, CASE
		WHEN COALESCE(COL.PART_ID, COL.SERVICE_CHARGE_ID, COL.MISC_REFERENCE, '') = '' THEN 0
		WHEN SL.SHIPPED_QTY <= 0 THEN 0 -- RETURNS
		WHEN COL.ORDER_QTY <= 0 THEN 0
		ELSE 1
	END 
)
--select * from CTE_INITIAL 

SELECT CATEGORY
	, CMP
	, BUS_STREAM
	, COUNT(CNTLINE) AS CNTLINE
FROM CTE_INITIAL
GROUP BY CATEGORY
	, CMP
	, BUS_STREAM
