DECLARE @START DATE = '7/15/2019'
;
WITH CTE_LINKED as 
(SELECT 'LINKED' AS [ORDER_TYPE]
	, S.SHIPPED_DATE
	, S.PACKLIST_ID
	, SL.SHIPPED_QTY
	, WO.PART_ID
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
FROM DATAWAREHOUSE.dbo.SHIPPER_LINE SL
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
    ON DSL.SUPPLY_TYPE = 'WO' 
    AND DSL.SUPPLY_BASE_ID = WO.BASE_ID
    AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
    AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
    AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
	AND WO.[TYPE] = 'W'
LEFT OUTER JOIN EMPLOYEE EE
	ON S.[USER_ID] = EE.[USER_ID]
LEFT OUTER JOIN LIVESupplemental.dbo.emp_ADP ADP
	ON EE.[ID] = ADP.[empID]
WHERE ADP.[LOCATION] = 'AUBURN SOUTH'
	AND S.PACKLIST_ID IS NOT NULL
	AND S.SHIPPED_DATE >= @START
	AND COL.PART_ID IS NOT NULL
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NOT NULL
--	AND RL.AMOUNT != 0
)

--SELECT * FROM CTE_LINKED WHERE CUST_ORDER_ID = '429280' --AND LINE_NO = '1'
--ORDER BY CUST_ORDER_ID, LINE_NO, INVOICE_ID

, CTE_UNLINKED as
(SELECT 'UNLINKED1' AS [ORDER_TYPE]
	, S.SHIPPED_DATE
	, S.PACKLIST_ID
	, SL.SHIPPED_QTY
	, WO.PART_ID
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
FROM DATAWAREHOUSE.dbo.SHIPPER_LINE SL
INNER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SPLIT_ID = '0'
	AND WO.SUB_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
LEFT OUTER JOIN EMPLOYEE EE
	ON S.[USER_ID] = EE.[USER_ID]
LEFT OUTER JOIN LIVESupplemental.dbo.emp_ADP ADP
	ON EE.[ID] = ADP.[empID]
WHERE ADP.[LOCATION] = 'AUBURN SOUTH'
	AND S.SHIPPED_DATE >= @START
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NULL
--	AND RL.AMOUNT != 0
----
UNION ALL
----
SELECT 'UNLINKED2' AS [ORDER_TYPE]
	, S.SHIPPED_DATE
	, S.PACKLIST_ID
	, SL.SHIPPED_QTY
	, WO.PART_ID
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
FROM DATAWAREHOUSE.dbo.SHIPPER_LINE SL
INNER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID + '/' + WO.SUB_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SPLIT_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
LEFT OUTER JOIN EMPLOYEE EE
	ON S.[USER_ID] = EE.[USER_ID]
LEFT OUTER JOIN LIVESupplemental.dbo.emp_ADP ADP
	ON EE.[ID] = ADP.[empID]
WHERE ADP.[LOCATION] = 'AUBURN SOUTH'
	AND S.SHIPPED_DATE >= @START
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NULL
--	AND RL.AMOUNT != 0
)

, CTE_COMBINED AS
(SELECT * 
FROM CTE_LINKED
UNION ALL
SELECT * 
FROM CTE_UNLINKED 
)
SELECT * FROM CTE_COMBINED
ORDER BY PACKLIST_ID