USE DataWarehouse
GO

SELECT LT.CLOCK_IN
, WO.PART_ID
, EE.FIRST_NAME
, EE.LAST_NAME
, EE.FIRST_NAME + ' ' + EE.LAST_NAME AS EE_NAME
, OT.RESOURCE_ID
, OT.[DESCRIPTION]
, NCM.NCM_ID
, COALESCE(NCM.SK_FIN_NCM_PROCESS, NCM.SK_MFG_NCM_PROCESS, '_BLANK') AS [PROCESS]
, COALESCE(NCM.SK_FIN_NCM_SUBPROCESS, NCM.SK_MFG_NCM_SUBPROCESS, '_BLANK') AS [SUBPROCESS]	
, ISNULL(NCM.USER_DEFINED_4, NCM.USER_DEFINED_7) AS [DEFECT]
, IIF(EE.FIRST_NAME = 'BLANK', 'FLAG', 'PAINT') AS RefProcess
FROM LABOR_TICKET LT
LEFT OUTER JOIN EMPLOYEE EE
	ON EE.ID = LT.EMPLOYEE_ID
LEFT OUTER JOIN OPERATION O
	ON O.WORKORDER_BASE_ID = LT.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = LT.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = LT.WORKORDER_SUB_ID
	AND O.SEQUENCE_NO = LT.OPERATION_SEQ_NO
LEFT OUTER JOIN SHOP_RESOURCE SR
	ON O.RESOURCE_ID = SR.ID
LEFT OUTER JOIN OPERATION_TYPE OT
	ON O.OPERATION_TYPE = OT.ID
LEFT OUTER JOIN VQ_PRODUCTION_ORDER PO
	ON O.WORKORDER_BASE_ID = PO.ALT_ID_2
	AND O.WORKORDER_LOT_ID = PO.ALT_ID_3
	AND O.WORKORDER_SPLIT_ID = PO.ALT_ID_4
	AND O.WORKORDER_SUB_ID = PO.ALT_ID_5
	AND O.WORKORDER_TYPE = PO.ALT_ID_1
LEFT OUTER JOIN WORK_ORDER WO
	ON WO.BASE_ID = LT.WORKORDER_BASE_ID
	AND WO.LOT_ID = LT.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = LT.WORKORDER_SUB_ID
LEFT OUTER JOIN VQ_NONCONFORMANCE NCM
	ON PO.RECORD_ID = NCM.PROD_ORDER_REC_ID
	AND COALESCE(NCM.SK_FIN_NCM_PROCESS, NCM.SK_MFG_NCM_PROCESS, '_BLANK') = 'PAINT'
WHERE LT.ACT_CLOCK_IN >= DATEADD(YEAR, -1, GETDATE())
	AND SR.USER_6 = 'PAINT'
	AND SR.USER_7 IN ('PRIMER', 'TOPCOAT')
	-->AND LT.RESOURCE_ID IN ('P1F1-PNT-PRIME', 'P1F2-PNT-PRIME', 'P1F1-PNT-TC', 'P1F2-PNT-TC')