/*
CO_PRODUCT
EC_LINE
ECN_OPERATION
OPERATION
OPERATION_BINARY
REQUIREMENT
REQUIREMENT_BINARY
WORK_ORDER
WORKORDER_BINARY

*/



SELECT P.ID
, P.[STATUS]
, P.[DESCRIPTION]
, U.PARTID
FROM PART P
INNER JOIN LIVESupplemental.dbo.LIVESupplemental.dbo.[Update20210301] U
ON P.ID = U.PARTID
--> 21039 RECORDS

 /*
; BEGIN TRANSACTION
UPDATE PART 
SET STATUS = 'O'
, [DESCRIPTION] = 'OBSOLETE - ' + REPLACE(REPLACE([DESCRIPTION], 'OBSOLETE - ', ''), 'OBSOLETE ', '')
FROM PART P
INNER JOIN [LIVESupplemental].dbo.LIVESupplemental.dbo.[Update20210301] U
ON P.ID = U.PARTID
--20998
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

SELECT U.BASEID
, U.LOT
, U.SPLIT
, U.SUB
, RB.WORKORDER_BASE_ID
, RB.WORKORDER_LOT_ID
, RB.WORKORDER_SPLIT_ID
, RB.WORKORDER_SUB_ID
FROM REQUIREMENT_BINARY RB
INNER JOIN LIVESupplemental.dbo.[Update20210301] U
ON RB.WORKORDER_BASE_ID = U.BASEID
AND RB.WORKORDER_LOT_ID = U.LOT
AND RB.WORKORDER_SPLIT_ID = U.SPLIT
AND RB.WORKORDER_SUB_ID = U.SUB
AND RB.WORKORDER_TYPE = 'M'
--> 84 RECORDS


SELECT U.BASEID
, U.LOT
, U.SPLIT
, U.SUB
, R.WORKORDER_BASE_ID
, R.WORKORDER_LOT_ID
, R.WORKORDER_SPLIT_ID
, R.WORKORDER_SUB_ID
FROM REQUIREMENT R
INNER JOIN LIVESupplemental.dbo.[Update20210301] U
ON R.WORKORDER_BASE_ID = U.BASEID
AND R.WORKORDER_LOT_ID = U.LOT
AND R.WORKORDER_SPLIT_ID = U.SPLIT
AND R.WORKORDER_SUB_ID = U.SUB
AND R.WORKORDER_TYPE = 'M'
-->129 RECORDS


SELECT U.BASEID
, U.LOT
, U.SPLIT
, U.SUB
, C.WORKORDER_BASE_ID
, C.WORKORDER_LOT_ID
, C.WORKORDER_SPLIT_ID
, C.WORKORDER_SUB_ID
FROM CO_PRODUCT C
INNER JOIN LIVESupplemental.dbo.[Update20210301] U
ON C.WORKORDER_BASE_ID = U.BASEID
AND C.WORKORDER_LOT_ID = U.LOT
AND C.WORKORDER_SPLIT_ID = U.SPLIT
AND C.WORKORDER_SUB_ID = U.SUB
AND C.WORKORDER_TYPE = 'M'
--> 16 RECORDS


SELECT U.BASEID
, U.LOT
, U.SPLIT
, U.SUB
, D.WORKORDER_BASE_ID
, D.WORKORDER_LOT_ID
, D.WORKORDER_SPLIT_ID
, D.WORKORDER_SUB_ID
FROM DOCUMENT_REF_WO D
INNER JOIN LIVESupplemental.dbo.[Update20210301] U
ON D.WORKORDER_BASE_ID = U.BASEID
AND D.WORKORDER_LOT_ID = U.LOT
AND D.WORKORDER_SPLIT_ID = U.SPLIT
AND D.WORKORDER_SUB_ID = U.SUB
AND D.WORKORDER_TYPE = 'M'
--> 76,330 RECORDS


SELECT U.BASEID
, U.LOT
, U.SPLIT
, U.SUB
, OB.WORKORDER_BASE_ID
, OB.WORKORDER_LOT_ID
, OB.WORKORDER_SPLIT_ID
, OB.WORKORDER_SUB_ID
FROM OPERATION_BINARY OB
INNER JOIN LIVESupplemental.dbo.[Update20210301] U
ON OB.WORKORDER_BASE_ID = U.BASEID
AND OB.WORKORDER_LOT_ID = U.LOT
AND OB.WORKORDER_SPLIT_ID = U.SPLIT
AND OB.WORKORDER_SUB_ID = U.SUB
AND OB.WORKORDER_TYPE = 'M'
--> 364,592 RECORDS


SELECT U.BASEID
, U.LOT
, U.SPLIT
, U.SUB
, O.WORKORDER_BASE_ID
, O.WORKORDER_LOT_ID
, O.WORKORDER_SPLIT_ID
, O.WORKORDER_SUB_ID
FROM OPERATION O
INNER JOIN LIVESupplemental.dbo.[Update20210301] U
ON O.WORKORDER_BASE_ID = U.BASEID
AND O.WORKORDER_LOT_ID = U.LOT
AND O.WORKORDER_SPLIT_ID = U.SPLIT
AND O.WORKORDER_SUB_ID = U.SUB
AND O.WORKORDER_TYPE = 'M'
--> 364833 RECORDS


SELECT U.BASEID
, U.LOT
, U.SPLIT
, U.SUB
, WB.WORKORDER_BASE_ID
, WB.WORKORDER_LOT_ID
, WB.WORKORDER_SPLIT_ID
, WB.WORKORDER_SUB_ID
FROM LIVESupplemental.dbo.[Update20210301] U
INNER JOIN WORKORDER_BINARY WB
ON WB.WORKORDER_BASE_ID = U.BASEID
AND WB.WORKORDER_LOT_ID = U.LOT
AND WB.WORKORDER_SPLIT_ID = U.SPLIT
AND WB.WORKORDER_SUB_ID = U.SUB
AND WB.[TYPE] = 'M'
--> 0 RECORDS


SELECT U.BASEID
, U.LOT
, U.SPLIT
, U.SUB
, WO.BASE_ID
, WO.LOT_ID
, WO.SPLIT_ID
, WO.SUB_ID
, WO.[STATUS]
FROM WORK_ORDER WO
INNER JOIN LIVESupplemental.dbo.[Update20210301] U
ON WO.BASE_ID = U.BASEID
AND WO.LOT_ID = U.LOT
AND WO.SPLIT_ID = U.SPLIT
AND WO.SUB_ID = U.SUB
AND WO.[TYPE] = 'M'
--> 21036 RECORDS

/*
; BEGIN TRANSACTION

DELETE FROM WORK_ORDER
WHERE EXISTS(SELECT 1
    FROM [LIVESupplemental.[dbo].LIVESupplemental.dbo.[Update20210301] U
    WHERE WO.BASE_ID = U.BASEID
		AND WO.LOT_ID = U.LOT
		AND WO.SPLIT_ID = U.SPLIT
		AND WO.SUB_ID = U.SUB
		AND WO.[TYPE] = 'M'
)
-->  records
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

