use live
go

SELECT P.ID
, P.USER_1
, PS.USER_1
, P.USER_2
, PS.USER_2
, P.USER_3
, PS.USER_3
, P.USER_4
, PS.USER_4
, P.USER_5
, PS.USER_5
, P.USER_6
, PS.USER_6
, P.USER_7
, PS.USER_7
, P.USER_8
, PS.USER_8
, P.USER_9
, PS.USER_9
, P.USER_10
, PS.USER_10

FROM PART P
INNER JOIN PART_SITE PS
ON P.ID = PS.PART_ID
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
AND (
ISNULL(P.USER_1, '') != ISNULL(PS.USER_1, '')
OR ISNULL(P.USER_2, '') != ISNULL(PS.USER_2, '')
OR ISNULL(P.USER_3, '') != ISNULL(PS.USER_3, '')
OR ISNULL(P.USER_4, '') != ISNULL(PS.USER_4, '')
OR ISNULL(P.USER_5, '') != ISNULL(PS.USER_5, '')
OR ISNULL(P.USER_6, '') != ISNULL(PS.USER_6, '')
OR ISNULL(P.USER_7, '') != ISNULL(PS.USER_7, '')
OR ISNULL(P.USER_8, '') != ISNULL(PS.USER_8, '')
OR ISNULL(P.USER_9, '') != ISNULL(PS.USER_9, '')
OR ISNULL(P.USER_10, '') != ISNULL(PS.USER_10, '')
)


SELECT P.USER_1
, COUNT(*)
FROM PART P
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
GROUP BY P.USER_1
ORDER BY P.USER_1

SELECT P.USER_2
, COUNT(*)
FROM PART P
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
GROUP BY P.USER_2
ORDER BY P.USER_2

SELECT P.USER_3
, COUNT(*)
FROM PART P
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
GROUP BY P.USER_3
ORDER BY P.USER_3

SELECT P.USER_4
, COUNT(*)
FROM PART P
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
GROUP BY P.USER_4
ORDER BY P.USER_4

SELECT P.USER_5
, COUNT(*)
FROM PART P
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
GROUP BY P.USER_5
ORDER BY P.USER_5

SELECT P.USER_6
, COUNT(*)
FROM PART P
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
GROUP BY P.USER_6
ORDER BY P.USER_6

SELECT P.USER_7
, COUNT(*)
FROM PART P
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
GROUP BY P.USER_7
ORDER BY P.USER_7

SELECT P.USER_8
, COUNT(*)
FROM PART P
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
GROUP BY P.USER_8
ORDER BY P.USER_8

SELECT P.USER_9
, COUNT(*)
FROM PART P
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
GROUP BY P.USER_9
ORDER BY P.USER_9

SELECT P.USER_10
, COUNT(*)
FROM PART P
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
GROUP BY P.USER_10
ORDER BY P.USER_10

SELECT P.ID
, P.USER_7
, PS.USER_7
FROM PART P
INNER JOIN PART_SITE PS
ON P.ID = PS.PART_ID
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
AND ISNULL(P.USER_7, '') != ISNULL(PS.USER_7, '')

DROP TABLE #T1

SELECT ID
, USER_7
INTO #T1
FROM PART
WHERE USER_7 IN ('10/14/2009 7:22', '11/1/2009 9:50', '11/2/2009 9:28', '11/2/2009 9:29', '8-8-01 DEG=.71 BOB', '9/18/2009 8:39', '9-22-00 P/A/P/TC=2.29 BOB', 'ADD STRIP @$14.40(Q)', 'DEBURR (49.00 per hour)', 'JLMFG - ANO 2PRI 3.12', 'JWD,DAVIS)', 'LAST ORDER 3.25', 'OLYTOO', 'PHASE TWO MASK PRI', 'PHASE2 CHEM MASK PRI T/C', 'PRESSCO)', 'QUEST', 'SAW ONLY $6.15', 'STRIP $14.40(QUAPRE)', 'SVS-AAC602332', 'SVS-AAD037224', 'TOTAL $3.60', 'TOTAL 4.19(NO-BID)', 'TOTAL 6.16(NO-BID)', 'TOTAL 6.48(NO-BID)', 'TOTAL 7.03(NO-CON)')

/*
BEGIN TRANSACTION;
UPDATE PART
SET USER_7 = NULL
FROM PART P
INNER JOIN #T1 T
	ON T.ID = P.ID
*/

SELECT T.ID
, T.USER_7 AS BEFORE_7
, P.USER_7 AS AFTER_7
FROM #T1 T
INNER JOIN PART P
ON T.ID = P.ID

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

/*
Start Step2:
update both tables
status where null => A

*/

SELECT ID
, [STATUS]
INTO #T2
FROM PART
WHERE [STATUS] IS NULL

SELECT * FROM #T2
SELECT STATUS, COUNT(*) FROM PART GROUP BY STATUS ORDER BY STATUS
/*
-- 103071 RECORDS
BEGIN TRANSACTION;
UPDATE PART
SET [STATUS] = 'A'
FROM PART P
INNER JOIN #T2 T
	ON T.ID = P.ID
*/

SELECT T.ID
, T.[STATUS] AS BEFORE_STATUS
, P.[STATUS] AS AFTER__STATUS
FROM #T2 T
INNER JOIN PART P
ON T.ID = P.ID

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

DROP TABLE #T1
DROP TABLE #T2
DROP TABLE #T3

SELECT PART_ID
, [STATUS]
INTO #T3
FROM PART_SITE
WHERE [STATUS] IS NULL

SELECT * FROM #T3

SELECT STATUS, COUNT(*) FROM PART_SITE GROUP BY STATUS ORDER BY STATUS
/*
-- 123515 RECORDS
BEGIN TRANSACTION;
UPDATE PART_SITE
SET [STATUS] = 'A'
FROM PART_SITE PS
INNER JOIN #T3 T
	ON T.PART_ID = PS.PART_ID
*/

SELECT STATUS, COUNT(*) FROM PART_SITE GROUP BY STATUS ORDER BY STATUS

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/


/*
Start Step3:
update both tables
blank out user_1-6, 8

SELECT COUNT(*) FROM PART
--138170 records

BEGIN TRANSACTION;
UPDATE PART
SET USER_1 = NULL
, USER_2 = NULL
, USER_3 = NULL
, USER_4 = NULL
, USER_5 = NULL
, USER_6 = NULL
, USER_8 = NULL
*/

select USER_1 
, USER_2
, USER_3
, USER_4
, USER_5
, USER_6
, USER_8
, count(*) from part group by USER_1 
, USER_2
, USER_3
, USER_4
, USER_5
, USER_6
, USER_8

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

/*
-- 138095

BEGIN TRANSACTION;
UPDATE PART_SITE
SET USER_1 = NULL
, USER_2 = NULL
, USER_3 = NULL
, USER_4 = NULL
, USER_5 = NULL
, USER_6 = NULL
, USER_8 = NULL

*/

select USER_1 
, USER_2
, USER_3
, USER_4
, USER_5
, USER_6
, USER_8
, count(*) from part_SITE group by USER_1 
, USER_2
, USER_3
, USER_4
, USER_5
, USER_6
, USER_8

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

*/

-----------------------------------
/* 
COMPARE THE STATUS AND USER FIELDS OF PART AND PART_SITE
*/

