/*
parts create_date < '1/1/2018'
no inventory xct
no master
no requirement
no co_product
no COL part_id
*/

USE LIVE
GO

DECLARE @STARTDATE DATE = '1/1/2018'

; WITH CTE_PARTS AS
(SELECT P.ID AS PART_ID
	, P.[DESCRIPTION]
	, P.PLANNER_USER_ID
	, P.BUYER_USER_ID
	, P.CREATE_DATE
--	, PS.PART_ID AS PS_PARTID
FROM PART P
LEFT OUTER JOIN PART_SITE PS
	ON P.ID = PS.PART_ID
LEFT OUTER JOIN PART_BINARY PB
	ON P.ID = PB.PART_ID
WHERE P.CREATE_DATE < @STARTDATE
AND PB.PART_ID IS NULL
AND P.[STATUS] != 'O'
AND P.[DESCRIPTION] NOT LIKE '%OBSOLETE%'
)
--SELECT * FROM CTE_PARTS
--> 128,880 PARTS

/*
, CTE_SLCT AS
(SELECT 'ADJUSTMENT_DETAIL' AS SRC, PART_ID FROM ADJUSTMENT_DETAIL
UNION ALL 
SELECT 'CARTON_LINE' AS SRC, PART_ID FROM CARTON_LINE
UNION ALL 
SELECT 'CO_PRODUCT' AS SRC, PART_ID FROM CO_PRODUCT
UNION ALL 
SELECT 'CUST_BOOK_LINE' AS SRC, PART_ID FROM CUST_BOOK_LINE
UNION ALL 
SELECT 'CUST_ORDER_LINE' AS SRC, PART_ID FROM CUST_ORDER_LINE
UNION ALL 
SELECT 'CUST_ORDER_LINE' AS SRC, CUSTOMER_PART_ID AS PART_ID FROM CUST_ORDER_LINE
UNION ALL 
SELECT 'CUST_PRICE_EFFECT' AS SRC, PART_ID FROM CUST_PRICE_EFFECT
UNION ALL 
SELECT 'CUST_PRICE_EFFECT' AS SRC, CUSTOMER_PART_ID AS PART_ID FROM CUST_PRICE_EFFECT
UNION ALL 
SELECT 'CUSTOMER_PRICE' AS SRC, PART_ID FROM CUSTOMER_PRICE
UNION ALL 
SELECT 'CUSTOMER_PRICE' AS SRC, CUSTOMER_PART_ID AS PART_ID FROM CUSTOMER_PRICE
UNION ALL 
SELECT 'CYCLE_COUNT_PART' AS SRC, PART_ID FROM CYCLE_COUNT_PART
UNION ALL 
SELECT 'DEMAND_SUPPLY_LINK' AS SRC, DEMAND_PART_ID AS PART_ID FROM DEMAND_SUPPLY_LINK
UNION ALL 
SELECT 'DEMAND_SUPPLY_LINK' AS SRC, SUPPLY_PART_ID AS PART_ID FROM DEMAND_SUPPLY_LINK
UNION ALL 
SELECT 'IBT_LINE' AS SRC, PART_ID FROM IBT_LINE
UNION ALL 
SELECT 'INVENTORY_BALANCE' AS SRC, PART_ID FROM INVENTORY_BALANCE
UNION ALL 
SELECT 'INVENTORY_TRANS' AS SRC, PART_ID FROM INVENTORY_TRANS
UNION ALL 
SELECT 'INVENTORY_TRANS_GOOD' AS SRC, PART_ID FROM INVENTORY_TRANS_GOOD
UNION ALL 
SELECT 'MASTER_SCHEDULE' AS SRC, PART_ID FROM MASTER_SCHEDULE
UNION ALL 
SELECT 'OPERATION' AS SRC, SERVICE_PART_ID AS PART_ID FROM OPERATION
UNION ALL 
SELECT 'OPERATION_TYPE' AS SRC, SERVICE_PART_ID AS PART_ID FROM OPERATION_TYPE
--UNION ALL 
--SELECT 'PART_BINARY' AS SRC, PART_ID FROM PART_BINARY
UNION ALL 
SELECT 'PART_CO_BINARY' AS SRC, PART_ID FROM PART_CO_BINARY
UNION ALL 
SELECT 'PART_LOCATION' AS SRC, PART_ID FROM PART_LOCATION
UNION ALL 
SELECT 'PART_MFG_BINARY' AS SRC, PART_ID FROM PART_MFG_BINARY
UNION ALL 
SELECT 'PART_PO_BINARY' AS SRC, PART_ID FROM PART_PO_BINARY
UNION ALL 
SELECT 'PART_UNITS_CONV' AS SRC, PART_ID FROM PART_UNITS_CONV
UNION ALL 
SELECT 'PART_WAREHOUSE' AS SRC, PART_ID FROM PART_WAREHOUSE
UNION ALL 
SELECT 'PHYS_COUNT_TAG' AS SRC, PART_ID FROM PHYS_COUNT_TAG
UNION ALL 
SELECT 'PLANNED_MATL_REQ' AS SRC, PARENT_PART_ID AS PART_ID FROM PLANNED_MATL_REQ
UNION ALL 
SELECT 'PLANNED_MATL_REQ' AS SRC, REQUIRED_PART_ID AS PART_ID FROM PLANNED_MATL_REQ
UNION ALL 
SELECT 'PLANNED_ORDER' AS SRC, PART_ID FROM PLANNED_ORDER
UNION ALL 
SELECT 'PLANNED_ORDER' AS SRC, MAIN_PART_ID AS PART_ID FROM PLANNED_ORDER
UNION ALL 
SELECT 'PURC_MATL_DETAIL' AS SRC, PART_ID FROM PURC_MATL_DETAIL
UNION ALL 
SELECT 'PURC_ORDER_LINE' AS SRC, PART_ID FROM PURC_ORDER_LINE
UNION ALL 
SELECT 'PURC_ORDER_LINE' AS SRC, VENDOR_PART_ID AS PART_ID FROM PURC_ORDER_LINE
UNION ALL 
SELECT 'PURC_ORDER_LINE' AS SRC, MFG_PART_ID AS PART_ID FROM PURC_ORDER_LINE
UNION ALL 
SELECT 'REQUIREMENT' AS SRC, PART_ID FROM REQUIREMENT
UNION ALL 
SELECT 'REQUIREMENT' AS SRC, VENDOR_PART_ID AS PART_ID FROM REQUIREMENT
UNION ALL 
SELECT 'REQUIREMENT' AS SRC, MFG_PART_ID AS PART_ID FROM REQUIREMENT 
UNION ALL 
SELECT 'REQUIREMENT_SCHED' AS SRC, PART_ID FROM REQUIREMENT_SCHED
UNION ALL 
SELECT 'SERVICE' AS SRC, SERVICE_PART_ID AS PART_ID FROM [SERVICE]
UNION ALL 
SELECT 'SERVICE_DISP_LINE' AS SRC, SERVICE_PART_ID AS PART_ID FROM SERVICE_DISP_LINE
UNION ALL 
SELECT 'SERVICE_RECEIPT' AS SRC, SERVICE_PART_ID AS PART_ID FROM SERVICE_RECEIPT
UNION ALL 
SELECT 'SERVICE_SITE' AS SRC, SERVICE_PART_ID AS PART_ID FROM SERVICE_SITE
UNION ALL 
SELECT 'SHIPMENT_DETAIL' AS SRC, PART_ID FROM SHIPMENT_DETAIL
UNION ALL 
SELECT 'SHIPMENT_DIST' AS SRC, PART_ID FROM SHIPMENT_DIST
UNION ALL 
SELECT 'TRACE' AS SRC, PART_ID FROM TRACE
UNION ALL 
SELECT 'TRACE_HISTORY' AS SRC, PART_ID FROM TRACE_HISTORY
UNION ALL 
SELECT 'TRACE_INV_TRANS' AS SRC, PART_ID FROM TRACE_INV_TRANS
UNION ALL 
SELECT 'TRACE_PROFILE' AS SRC, PART_ID FROM TRACE_PROFILE
UNION ALL 
SELECT 'TRACE_SERV_TRANS' AS SRC, PART_ID FROM TRACE_SERV_TRANS
UNION ALL 
SELECT 'VENDOR_PART' AS SRC, PART_ID FROM VENDOR_PART
UNION ALL 
SELECT 'VENDOR_PART' AS SRC, VENDOR_PART_ID AS PART_ID FROM VENDOR_PART
UNION ALL 
SELECT 'VENDOR_QUOTE' AS SRC, VENDOR_PART_ID AS PART_ID FROM VENDOR_QUOTE
UNION ALL 
SELECT 'VENDOR_QUOTE' AS SRC, MFG_PART_ID AS PART_ID FROM VENDOR_QUOTE
UNION ALL 
SELECT 'VR_CUSTORD_DET' AS SRC, PART_ID FROM VR_CUSTORD_DET
UNION ALL 
SELECT 'VR_PURCORD_DET' AS SRC, PART_ID FROM VR_PURCORD_DET
UNION ALL 
SELECT 'VR_RECEIVER_DET' AS SRC, PART_ID FROM VR_RECEIVER_DET
UNION ALL 
SELECT 'VR_SHIPMENT_DET' AS SRC, PART_ID FROM VR_SHIPMENT_DET
UNION ALL 
SELECT 'VR_WORKORDER_HDR' AS SRC, PART_ID FROM VR_WORKORDER_HDR
UNION ALL 
SELECT 'WIP_ISSUE_DETAIL' AS SRC, PART_ID FROM WIP_ISSUE_DETAIL
UNION ALL 
SELECT 'WIP_RECEIPT_DETAIL' AS SRC, PART_ID FROM WIP_RECEIPT_DETAIL
UNION ALL 
SELECT 'WORK_ORDER' AS SRC, PART_ID FROM WORK_ORDER
UNION ALL 
SELECT 'WORK_ORDER_SCHED' AS SRC, PART_ID FROM WORK_ORDER_SCHED
)

SELECT *
INTO #CTE_SLCT
FROM CTE_SLCT



--, CTE_ELIM AS
--(
DROP TABLE #CTE_ELIM

SELECT PART_ID, COUNT(*) AS [COUNT] 
INTO #CTE_ELIM
FROM #CTE_SLCT 
GROUP BY PART_ID HAVING COUNT(*) < 10
--)
--> 645691 rows affected)




SELECT S.*, E.[COUNT]
FROM #CTE_SLCT S
INNER JOIN #CTE_ELIM E
ON S.PART_ID = E.PART_ID
ORDER BY S.PART_ID
*/

SELECT *
FROM CTE_PARTS P
LEFT OUTER JOIN #CTE_SLCT SLCT
ON P.PART_ID = SLCT.PART_ID
LEFT OUTER JOIN #CTE_ELIM ELIM
ON P.PART_ID = ELIM.PART_ID
WHERE P.PART_ID NOT IN ('REWORK', 'REWORK MFG', ' REWORK', ' REWORK MFG')
--AND SLCT.PART_ID IS NULL
--> 535 PARTS
ORDER BY P.PART_ID

