USE LIVE
GO

SELECT P.ID 
, U.PARTID
, P.PLANNING_LEADTIME
, U.PlanningLeadTime
FROM [LIVESupplemental].[dbo].[PartUpdate20210308] U
INNER JOIN LIVE.dbo.PART P
ON P.ID = U.PARTID
WHERE P.PLANNING_LEADTIME != U.PlanningLeadTime
--> 5684 RECORDS

/*
USE LIVE
GO

; BEGIN TRANSACTION
UPDATE PART
SET PLANNING_LEADTIME = U.PlanningLeadTime
FROM [LIVESupplemental].[dbo].[PartUpdate20210308] U
INNER JOIN LIVE.dbo.PART P
ON P.ID = U.PARTID
WHERE P.PLANNING_LEADTIME != U.PlanningLeadTime
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

SELECT P.PART_ID 
, U.PARTID
, P.PLANNING_LEADTIME
, U.PlanningLeadTime
FROM [LIVESupplemental].[dbo].[PartUpdate20210308] U
INNER JOIN LIVE.dbo.PART_SITE P
ON P.PART_ID = U.PARTID
WHERE P.PLANNING_LEADTIME != U.PlanningLeadTime
--> 4319 RECORDS

/*
--; BEGIN TRANSACTION
UPDATE PART_SITE
SET PLANNING_LEADTIME = U.PlanningLeadTime
FROM [LIVESupplemental].[dbo].[PartUpdate20210308] U
INNER JOIN LIVE.dbo.PART_SITE P
ON P.PART_ID = U.PARTID
WHERE P.PLANNING_LEADTIME != U.PlanningLeadTime
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

*/