USE LIVE
GO

; WITH CTE_WOCLOSE AS
(SELECT WO.PART_ID, MAX(WO.CLOSE_DATE) CLOSE_DATE
	FROM WORK_ORDER WO
	LEFT OUTER JOIN REQUIREMENT R
	ON WO.BASE_ID = R.WORKORDER_BASE_ID
	AND WO.LOT_ID = R.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = R.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = R.WORKORDER_SUB_ID
	AND WO.[TYPE] = R.WORKORDER_TYPE
	--WHERE WO.PART_ID = P.ID
	--OR R.PART_ID = P.ID
GROUP BY WO.PART_ID
UNION
SELECT R.PART_ID, MAX(WO.CLOSE_DATE) CLOSE_DATE
	FROM REQUIREMENT R
	LEFT OUTER JOIN WORK_ORDER WO
	ON WO.BASE_ID = R.WORKORDER_BASE_ID
	AND WO.LOT_ID = R.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = R.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = R.WORKORDER_SUB_ID
	AND WO.[TYPE] = R.WORKORDER_TYPE
GROUP BY R.PART_ID
UNION
SELECT CP.PART_ID, MAX(WO.CLOSE_DATE) CLOSE_DATE
	FROM CO_PRODUCT CP
	LEFT OUTER JOIN WORK_ORDER WO
	ON WO.BASE_ID = CP.WORKORDER_BASE_ID
	AND WO.LOT_ID = CP.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = CP.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = CP.WORKORDER_SUB_ID
	AND WO.[TYPE] = CP.WORKORDER_TYPE
GROUP BY CP.PART_ID
)
--SELECT PART_ID, COUNT(*) FROM CTE_WOCLOSE GROUP BY PART_ID HAVING COUNT(*) > 1

SELECT ID
, [DESCRIPTION]
, [STATUS]
, PLANNER_USER_ID
, BUYER_USER_ID
, PART_CREATE_DATE
, LAST_ORDER
, DATEDIFF(MONTH, ISNULL(LAST_ORDER, PART_CREATE_DATE), GETDATE()) / 12.0 AS LAST_ORDER_DIFF
, LAST_WOCLOSE
, DATEDIFF(MONTH, ISNULL(LAST_WOCLOSE, PART_CREATE_DATE), GETDATE()) / 12.0 AS LAST_WOCLOSE_DIFF
, LAST_SHIPDATE
, DATEDIFF(MONTH, ISNULL(LAST_SHIPDATE, PART_CREATE_DATE), GETDATE()) / 12.0 AS LAST_SHIPPED_DIFF
, [TYPE]
, BASE_ID
, LOT_ID
, SPLIT_ID
, SUB_ID
, WO_CREATE_DATE
FROM (SELECT P.ID
, P.[DESCRIPTION]
, P.[STATUS]
, P.PLANNER_USER_ID
, P.BUYER_USER_ID
, P.CREATE_DATE AS PART_CREATE_DATE
, (SELECT MAX(ORDER_DATE) AS ORDER_DATE
	FROM CUST_ORDER_LINE COL
	INNER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
	WHERE COL.PART_ID = P.ID
	) AS LAST_ORDER
, (SELECT MAX(SHIPPED_DATE) AS SHIPPED_DATE
	FROM CUST_ORDER_LINE COL
	INNER JOIN SHIPPER_LINE SL
	ON COL.CUST_ORDER_ID = SL.CUST_ORDER_ID
	AND COL.LINE_NO = SL.CUST_ORDER_LINE_NO
	INNER JOIN SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID
	WHERE COL.PART_ID = P.ID
	) AS LAST_SHIPDATE
--, (SELECT MAX(WO.CLOSE_DATE) AS CLOSE_DATE
--	FROM WORK_ORDER WO
--	LEFT OUTER JOIN REQUIREMENT R
--	ON WO.BASE_ID = R.WORKORDER_BASE_ID
--	AND WO.LOT_ID = R.WORKORDER_LOT_ID
--	AND WO.SPLIT_ID = R.WORKORDER_SPLIT_ID
--	AND WO.SUB_ID = R.WORKORDER_SUB_ID
--	AND WO.[TYPE] = R.WORKORDER_TYPE
--	WHERE WO.PART_ID = P.ID
--	OR R.PART_ID = P.ID
--	) AS LAST_WOCLOSE
, (SELECT MAX(CLOSE_DATE) AS CLOSE_DATE
	FROM CTE_WOCLOSE WO
	WHERE WO.PART_ID = P.ID
	) AS LAST_WOCLOSE
, WO.[TYPE]
, WO.BASE_ID
, WO.LOT_ID
, WO.SPLIT_ID
, WO.SUB_ID
, WO.CREATE_DATE AS WO_CREATE_DATE
FROM PART P
LEFT OUTER JOIN WORK_ORDER WO
ON WO.PART_ID = P.ID
AND WO.[TYPE] = 'M'
WHERE P.[STATUS] = 'A'
AND P.CREATE_DATE < '1/1/2019'
) X
--WHERE CREATE_DATE > LAST_ORDER
