USE LIVE
GO

/*
SELECT ID 
, STOCKED
, FABRICATED
, INSPECTION_REQD
FROM PART 
WHERE STOCKED = 'Y' 
AND ([STATUS] != 'O' OR [STATUS] IS NULL)

SELECT PART_ID 
, STOCKED
, FABRICATED
, INSPECTION_REQD
FROM PART_SITE
WHERE STOCKED = 'Y' 
AND ([STATUS] != 'O' OR [STATUS] IS NULL)

; BEGIN TRANSACTION
UPDATE PART
SET INSPECTION_REQD = 'N'
WHERE STOCKED = 'Y' AND FABRICATED = 'Y'
AND ([STATUS] != 'O' OR [STATUS] IS NULL)
--18628
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

; BEGIN TRANSACTION
UPDATE PART_SITE
SET INSPECTION_REQD = 'N'
WHERE STOCKED = 'Y' AND FABRICATED = 'Y'
AND ([STATUS] != 'O' OR [STATUS] IS NULL)
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

*/

SELECT *
FROM (
SELECT ID 
, PLANNER_USER_ID
, STOCKED
, FABRICATED
, PURCHASED
, CONSUMABLE
, INSPECTION_REQD
, CASE
	WHEN STOCKED = 'Y' AND FABRICATED = 'Y' AND INSPECTION_REQD = 'Y' THEN 'INSPECTION'
	WHEN STOCKED = 'Y' AND FABRICATED = 'N' AND INSPECTION_REQD = 'Y' THEN NULL
END AS CHECK1
, CASE
	WHEN STOCKED = 'Y' AND PURCHASED = 'N' AND INSPECTION_REQD = 'Y' THEN 'PURCHASE'
	WHEN STOCKED = 'Y' AND PURCHASED = 'Y' AND INSPECTION_REQD = 'N' THEN 'INSPECTION'
END AS CHECK2
, CASE
	WHEN STOCKED = 'Y' AND FABRICATED = 'Y' AND PURCHASED = 'N' THEN NULL
	WHEN STOCKED = 'Y' AND FABRICATED = 'N' AND PURCHASED = 'N' THEN 'NEITHER'
	WHEN STOCKED = 'Y' AND FABRICATED = 'Y' AND PURCHASED = 'Y' THEN 'PURCHASE'
END AS CHECK3
FROM PART 
WHERE ([STATUS] != 'O' OR [STATUS] IS NULL)
) X
WHERE CHECK1 IS NOT NULL
OR CHECK2 IS NOT NULL
OR CHECK3 IS NOT NULL

