USE LIVE
GO

--SELECT * FROM LIVESupplemental.dbo.buyer_assn BA

SELECT P.ID
, P.BUYER_USER_ID
, C.ID
, UDF.STRING_VAL AS BUS_STREAM
, P.PLANNER_USER_ID
, C.SALESREP_ID AS CUST_SALESREP
, BA.Salesperson_ID AS BA_SALESREP
, C.ACTIVE_FLAG AS CUST_STATUS
, P.[STATUS] AS PART_STATUS
FROM PART P
LEFT OUTER JOIN CUSTOMER C
	ON C.ID = RIGHT(P.BUYER_USER_ID, 6)
LEFT OUTER JOIN LIVESupplemental.dbo.buyer_assn BA
	ON BA.Account_ID = LEFT(P.BUYER_USER_ID, 2)
LEFT OUTER JOIN USER_DEF_FIELDS UDF
	ON UDF.DOCUMENT_ID = C.ID
	AND PROGRAM_ID = 'VMCUSMNT'
	AND UDF.ID = 'UDF-0000072'
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
AND (P.BUYER_USER_ID IS NOT NULL)
AND C.SALESREP_ID != BA.Salesperson_ID
AND (NOT (P.PLANNER_USER_ID IN ('FIN-HOURLY', 'TOOLING') AND P.BUYER_USER_ID = '59-BOE609' AND BA.Salesperson_ID = 'Tiffany')
	AND NOT (P.PLANNER_USER_ID IN ('MFG-MRP', 'MFG-PLAN') AND BA.Salesperson_ID IN ('Tracey', 'Justin', 'Purchasing'))
	)

