SELECT 'PART'
	, ID AS PART_ID
	, P.[STATUS] AS P_STATUS
	, PS.[STATUS] AS PS_STATUS
	, CASE
		WHEN ISNULL(P.[STATUS], '') != ISNULL(PS.[STATUS], '') THEN 'STATUS'
	END AS STATUS_CHECK
	, P.USER_7 AS P_USER7
	, PS.USER_7 AS PS_USER7
	, CASE
		WHEN ISNULL(P.[USER_7], '') != ISNULL(PS.[USER_7], '') THEN 'USER_7'
	END AS [7_CHECK]
	, P.USER_9 AS P_USER9
	, PS.USER_9 AS PS_USER9
	, CASE
		WHEN ISNULL(P.[USER_9], '') != ISNULL(PS.[USER_9], '') THEN 'USER_9'
	END AS [9_CHECK]
	, P.USER_10 AS P_USER10
	, PS.USER_10 AS PS_USER10
	, CASE
		WHEN ISNULL(P.[USER_10], '') != ISNULL(PS.[USER_10], '') THEN 'USER_10'
	END AS [10_CHECK]
FROM PART P
LEFT OUTER JOIN PART_SITE PS
ON P.ID = PS.PART_ID
WHERE (ISNULL(P.[STATUS], '') != ISNULL(PS.[STATUS], ''))
OR (ISNULL(P.[USER_7], '') != ISNULL(PS.[USER_7], ''))
OR (ISNULL(P.[USER_9], '') != ISNULL(PS.[USER_9], ''))
OR (ISNULL(P.[USER_10], '') != ISNULL(PS.[USER_10], ''))

UNION ALL

SELECT 'PART_SITE'
	, PS.PART_ID
	, P.[STATUS] AS P_STATUS
	, PS.[STATUS] AS PS_STATUS
	, CASE
		WHEN ISNULL(P.[STATUS], '') != ISNULL(PS.[STATUS], '') THEN 'STATUS'
	END AS STATUS_CHECK
	, P.USER_7 AS P_USER7
	, PS.USER_7 AS PS_USER7
	, CASE
		WHEN ISNULL(P.[USER_7], '') != ISNULL(PS.[USER_7], '') THEN 'USER_7'
	END AS [7_CHECK]
	, P.USER_9 AS P_USER9
	, PS.USER_9 AS PS_USER9
	, CASE
		WHEN ISNULL(P.[USER_9], '') != ISNULL(PS.[USER_9], '') THEN 'USER_9'
	END AS [9_CHECK]
	, P.USER_10 AS P_USER10
	, PS.USER_10 AS PS_USER10
	, CASE
		WHEN ISNULL(P.[USER_10], '') != ISNULL(PS.[USER_10], '') THEN 'USER_10'
	END AS [10_CHECK]
FROM PART_SITE PS
LEFT OUTER JOIN PART P
ON P.ID = PS.PART_ID
WHERE (ISNULL(P.[STATUS], '') != ISNULL(PS.[STATUS], ''))
OR (ISNULL(P.[USER_7], '') != ISNULL(PS.[USER_7], ''))
OR (ISNULL(P.[USER_9], '') != ISNULL(PS.[USER_9], ''))
OR (ISNULL(P.[USER_10], '') != ISNULL(PS.[USER_10], ''))

SELECT * FROM PART_SITE WHERE PART_ID = 'XX'
SELECT * FROM PART WHERE ID = 'XX'