USE [LIVESupplemental]
GO

/****** Object:  Table [dbo].[PartUpdate20211110]    Script Date: 11/10/2021 7:06:01 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--CREATE TABLE [dbo].[PartUpdate20211110](
--	[PartID] [nvarchar](50) NULL,
--	[DRAWING_REV_NO] [nvarchar](20) NULL
--) ON [PRIMARY]
--GO

TRUNCATE TABLE [dbo].[PartUpdate20211110]

SELECT * FROM [dbo].[PartUpdate20211110]
--> 1571 ROWS

DROP TABLE #T1

SELECT P.ID
, P.DRAWING_REV_NO
, RTRIM(LTRIM(U.DRAWING_REV_NO)) AS NEW_DRAWING_REV_NO
INTO #T1
FROM LIVESupplemental.[dbo].[PartUpdate20211110] U
INNER JOIN LIVE.dbo.PART P
ON P.ID = U.PARTID

SELECT * FROM #T1

/*
USE LIVE
GO

BEGIN TRANSACTION;
UPDATE PART
SET DRAWING_REV_NO = NEW_DRAWING_REV_NO
FROM LIVE.dbo.PART P
INNER JOIN #T1 U
ON P.ID = U.ID
--> 1571 ROWS
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;


