USE LIVE

SELECT BASE_ID
, LOT_ID
, SPLIT_ID
, SUB_ID
, O.SEQUENCE_NO
, O2.RESOURCE_ID
, O2.OPERATION_TYPE
FROM WORK_ORDER WO
INNER JOIN 
(SELECT WORKORDER_BASE_ID
	, WORKORDER_LOT_ID
	, WORKORDER_SPLIT_ID
	, WORKORDER_SUB_ID
	, WORKORDER_TYPE
	, MIN(SEQUENCE_NO) AS SEQUENCE_NO
FROM OPERATION O
GROUP BY WORKORDER_BASE_ID
	, WORKORDER_LOT_ID
	, WORKORDER_SPLIT_ID
	, WORKORDER_SUB_ID
	, WORKORDER_TYPE
) O
	ON WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O.WORKORDER_SUB_ID
	AND WO.[TYPE] = O.WORKORDER_TYPE
INNER JOIN OPERATION O2
	ON WO.BASE_ID = O2.WORKORDER_BASE_ID
	AND WO.LOT_ID = O2.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O2.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O2.WORKORDER_SUB_ID
	AND WO.[TYPE] = O2.WORKORDER_TYPE
	AND O.SEQUENCE_NO = O2.SEQUENCE_NO
WHERE WO.[TYPE] = 'M'
	AND (WO.PART_ID LIKE '140W9013%' 
		OR WO.PART_ID LIKE '140W9014%')
