USE LIVE
GO

SELECT U.ID
, PS.PART_ID
FROM [LIVESupplemental].[dbo].[PART upload 20201117$] U
LEFT OUTER JOIN PART_SITE PS
ON PS.PART_ID = U.ID


/*
UPDATE PART
SET USER_9 = NULL

BEGIN TRANSACTION;
UPDATE PART_SITE
SET USER_9 = NULL

select user_9, count(*) from part_site group by user_9 order by user_9

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

SELECT P.ID
, P.BUYER_USER_ID
, P.USER_2
, P.USER_3
, P.USER_4
, P.USER_5
, P.USER_7
, P.USER_9
, P.USER_10
FROM PART P
INNER JOIN [LIVESupplemental].[dbo].[PART upload 20201117$] U
ON P.ID = U.ID
ORDER BY P.ID

/*
BEGIN TRANSACTION;
UPDATE PART
SET [BUYER_USER_ID] = U.[BUYER_USER_ID]
, [USER_2] = U.[U2]
, [USER_3] = U.[U3]
, [USER_4] = U.[U4]
, [USER_5] = U.[U5]
, [USER_7] = U.[U7]
, [USER_9] = U.[U9]
, [USER_10] = U.[U10]
FROM PART P
INNER JOIN [LIVESupplemental].[dbo].[PART upload 20201117$] U
ON P.ID = U.ID

--15886
SELECT P.ID
, P.BUYER_USER_ID
, P.USER_2
, P.USER_3
, P.USER_4
, P.USER_5
, P.USER_7
, P.USER_9
, P.USER_10
FROM PART P
INNER JOIN [LIVESupplemental].[dbo].[PART upload 20201117$] U
ON P.ID = U.ID
ORDER BY P.ID

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

*/

SELECT PS.PART_ID
, PS.BUYER_USER_ID
, PS.USER_2
, PS.USER_3
, PS.USER_4
, PS.USER_5
, PS.USER_7
, PS.USER_9
, PS.USER_10
FROM PART_SITE PS
INNER JOIN [LIVESupplemental].[dbo].[PART upload 20201117$] U
ON PS.PART_ID = U.ID
ORDER BY PS.PART_ID

/*
BEGIN TRANSACTION;
UPDATE PART_SITE
SET [BUYER_USER_ID] = U.[BUYER_USER_ID]
, [USER_2] = U.[U2]
, [USER_3] = U.[U3]
, [USER_4] = U.[U4]
, [USER_5] = U.[U5]
, [USER_7] = U.[U7]
, [USER_9] = U.[U9]
, [USER_10] = U.[U10]
FROM PART_SITE P
INNER JOIN [LIVESupplemental].[dbo].[PART upload 20201117$] U
ON P.PART_ID = U.ID

SELECT P.PART_ID
, P.BUYER_USER_ID
, P.USER_2
, P.USER_3
, P.USER_4
, P.USER_5
, P.USER_7
, P.USER_9
, P.USER_10
FROM PART_SITE P
INNER JOIN [LIVESupplemental].[dbo].[PART upload 20201117$] U
ON P.PART_ID = U.ID
ORDER BY P.PART_ID

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

*/

/*
BEGIN TRANSACTION;
UPDATE PART_SITE
SET [BUYER_USER_ID] = U.[BUYER_USER_ID]
, [PLANNER_USER_ID] = U.[PLANNER_USER_ID]
, [USER_1] = U.[USER_1]
, [USER_2] = U.[USER_2]
, [USER_3] = U.[USER_3]
, [USER_4] = U.[USER_4]
, [USER_5] = U.[USER_5]
, [USER_6] = U.[USER_6]
, [USER_7] = U.[USER_7]
, [USER_8] = U.[USER_8]
, [USER_9] = U.[USER_9]
, [USER_10] = U.[USER_10]
, [STATUS] = U.[STATUS]
FROM PART_SITE P
INNER JOIN PART U
ON P.PART_ID = U.ID
--> 138089 rows affected

SELECT P.PART_ID
, P.BUYER_USER_ID
, P.USER_2
, P.USER_3
, P.USER_4
, P.USER_5
, P.USER_7
, P.USER_9
, P.USER_10
FROM PART_SITE P
LEFT OUTER JOIN PART U
ON P.PART_ID = U.ID
WHERE P.[BUYER_USER_ID] != U.[BUYER_USER_ID]
OR P.[PLANNER_USER_ID] != U.[PLANNER_USER_ID]
OR P.[USER_1] != U.[USER_1]
OR P.[USER_2] != U.[USER_2]
OR P.[USER_3] != U.[USER_3]
OR P.[USER_4] != U.[USER_4]
OR P.[USER_5] != U.[USER_5]
OR P.[USER_6] != U.[USER_6]
OR P.[USER_7] != U.[USER_7]
OR P.[USER_8] != U.[USER_8]
OR P.[USER_9] != U.[USER_9]
OR P.[USER_10] != U.[USER_10]
OR P.[STATUS] != U.[STATUS]
ORDER BY P.PART_ID

--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

*/