USE LIVE
GO

SELECT P.ID AS PART_ID
, P.[STATUS]
, P.[DESCRIPTION]
, P.CREATE_DATE
, P.PLANNER_USER_ID
, P.COMMODITY_CODE
, P.PURCHASED
, P.QTY_IN_DEMAND
, P.QTY_ON_HAND
, TP.[TRACE_ID_LABEL]
, TP.[APROPERTY_LABEL_1]
, TP.[APROPERTY_LABEL_2]
, TP.[APROPERTY_LABEL_3]
, TP.[APROPERTY_LABEL_4]
, TP.[APROPERTY_LABEL_5]
, TP.[APROPERTY_1_REQD]
, TP.[APROPERTY_2_REQD]
, TP.[APROPERTY_3_REQD]
, TP.[APROPERTY_4_REQD]
, TP.[APROPERTY_5_REQD]
, TP.[APROPERTY_1_EDIT]
, TP.[APROPERTY_2_EDIT]
, TP.[APROPERTY_3_EDIT]
, TP.[APROPERTY_4_EDIT]
, TP.[APROPERTY_5_EDIT]
, TP.[APROPERTY_1_VIS]
, TP.[APROPERTY_2_VIS]
, TP.[APROPERTY_3_VIS]
, TP.[APROPERTY_4_VIS]
, TP.[APROPERTY_5_VIS]
FROM PART P
LEFT OUTER JOIN TRACE_PROFILE TP
ON P.ID = TP.PART_ID
WHERE (P.[STATUS] = 'A' OR P.[STATUS] IS NULL)
AND P.PLANNER_USER_ID IN ('MFG-PLAN', 'MFG-MRP')


/*
SELECT [TRACE_ID_LABEL]
, [APROPERTY_LABEL_1]
, [APROPERTY_LABEL_2]
, [APROPERTY_LABEL_3]
, [APROPERTY_LABEL_4]
, [APROPERTY_LABEL_5]
, [APROPERTY_1_REQD]
, [APROPERTY_2_REQD]
, [APROPERTY_3_REQD]
, [APROPERTY_4_REQD]
, [APROPERTY_5_REQD]
, [APROPERTY_1_EDIT]
, [APROPERTY_2_EDIT]
, [APROPERTY_3_EDIT]
, [APROPERTY_4_EDIT]
, [APROPERTY_5_EDIT]
, [APROPERTY_1_VIS]
, [APROPERTY_2_VIS]
, [APROPERTY_3_VIS]
, [APROPERTY_4_VIS]
, [APROPERTY_5_VIS]
, *
FROM TRACE_PROFILE WHERE PART_ID = 'TEMPLATE- ADHESIVE'

*/
