USE LIVE
GO
SELECT * FROM [LIVESupplemental].[dbo].[PartUpdate20210322] U

SELECT P.ID 
, U.[PARTID]
, P.PLANNING_LEADTIME
, U.PlanningLeadTime
, P.USER_1
, U.USER_1
FROM [LIVESupplemental].[dbo].[PartUpdate20210322] U
LEFT OUTER JOIN LIVE.dbo.PART P
ON P.ID = U.[PARTID]
--WHERE P.ID IS NULL
WHERE P.PLANNING_LEADTIME != U.PlanningLeadTime
	OR ISNULL(P.USER_1, '') != U.USER_1
--> 3368 RECORDS

/*
USE LIVE
GO

; BEGIN TRANSACTION
UPDATE PART
SET PLANNING_LEADTIME = U.PlanningLeadTime
, USER_1 = U.USER_1
FROM [LIVESupplemental].[dbo].[PartUpdate20210322] U
INNER JOIN LIVE.dbo.PART P
ON P.ID = U.PARTID
WHERE P.PLANNING_LEADTIME != U.PlanningLeadTime
	OR ISNULL(P.USER_1, '') != U.USER_1
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

140W9614-99507
*/

SELECT P.PART_ID 
, U.PARTID
, P.PLANNING_LEADTIME
, U.PlanningLeadTime
, P.USER_1
, U.USER_1
FROM [LIVESupplemental].[dbo].[PartUpdate20210322] U
INNER JOIN LIVE.dbo.PART_SITE P
ON P.PART_ID = U.PARTID
WHERE P.PLANNING_LEADTIME != U.PlanningLeadTime
	OR ISNULL(P.USER_1, '') != U.USER_1
--> 3368 RECORDS

/*
; BEGIN TRANSACTION
UPDATE PART_SITE
SET PLANNING_LEADTIME = U.PlanningLeadTime
, USER_1 = U.USER_1
FROM [LIVESupplemental].[dbo].[PartUpdate20210322] U
INNER JOIN LIVE.dbo.PART_SITE P
ON P.PART_ID = U.PARTID
WHERE P.PLANNING_LEADTIME != U.PlanningLeadTime
	OR ISNULL(P.USER_1, '') != U.USER_1
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

*/