USE Datamart
GO

-- VISUAL ENTERPRISE REPORTS > PART REPORTS > PARTS_CATALOG
--DECLARE @COMMODITY AS NVARCHAR(15) = 'LAB TESTS'
--, @PLANNER AS NVARCHAR(15) = 'MFG-MRP'
--, @PURCHASED AS NVARCHAR(1) = 'Y'
--, @STOCKED AS NVARCHAR(1)= 'N'
--, @CONTROLLED AS NVARCHAR(15) = ('QPL CONTROLLED')
--, @FABRICATED AS NVARCHAR(1) = 'N'
--, @BUYER AS NVARCHAR(15) = ''

SELECT 'SK01' AS SITE
	, P.PART_ID
	, ISNULL(P.[DESCRIPTION], '_BLANK') AS PART_DESCRIPTION
	, P.INSPECTION_REQD AS INSP_REQD
	, ISNULL(P.COMMODITY_CODE, '_BLANK') AS COMMODITY_CODE
	, UDF.CONTROLLED
	, UDF.CERTS_NEEDED
	, CAST(CAST(PB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS PART_SPECIFICATIONS
	, P.STOCK_UM AS UM
	, STUFF((SELECT ', ' + d.id +' REV '+ d.REVISION_ID 
		FROM DOCUMENT D
		INNER JOIN DOCUMENT_REFERENCE DF
			ON DF.DOCUMENT_ID = D.ID
		AND D.CATEGORY_ID = 'SPECIFICATION'
		WHERE P.PART_ID = DF.ID
		FOR XML PATH('')), 1, 1, '') AS SPEC_LIST
	, P.PREF_VENDOR_ID AS PREF_VENDOR
	, ISNULL(P.BUYER_USER_ID, '_BLANK') AS BUYER_USER_ID
	, ISNULL(B.SALESPERSON_ID, '_BLANK') AS BUYER_ID
	, P.PLANNER_USER_ID AS PLANNER_ID
	, ISNULL(P.STOCKED, '-') AS STOCKED
	, ISNULL(P.FABRICATED, '-') AS FABRICATED
	, ISNULL(P.PURCHASED, '-') AS PURCHASED
	, ISNULL(P.CONSUMABLE, '-') AS CONSUMABLE
FROM PART_SITE_VIEW P
LEFT OUTER JOIN SKILLS_PART_UDF UDF
	ON P.PART_ID = UDF.PART_ID
LEFT OUTER JOIN PART_BINARY PB
	ON P.PART_ID = PB.PART_ID
LEFT OUTER JOIN LIVESUPPLEMENTAL.DBO.BUYER_ASSN B
	ON LEFT(P.BUYER_USER_ID, 2) = B.ACCOUNT_ID
LEFT OUTER JOIN DOCUMENT_REFERENCE DF
	ON P.PART_ID = DF.ID
LEFT OUTER JOIN DOCUMENT D
	ON DF.DOCUMENT_ID = D.ID
	AND D.CATEGORY_ID = 'SPECIFICATION'
WHERE (P.[STATUS] != 'O'
		OR P.[STATUS] IS NULL)
	AND P.COMMODITY_CODE IN (@COMMODITY)
	AND P.PLANNER_USER_ID IN (@PLANNER)
	AND ISNULL(B.SALESPERSON_ID, '_BLANK') IN (@BUYER)
	AND ISNULL(P.FABRICATED, '-') IN (@FABRICATED)
	AND ISNULL(P.PURCHASED, '-') IN (@PURCHASED)
	AND ISNULL(P.STOCKED, '-') IN (@STOCKED)
	AND ISNULL(UDF.CONTROLLED, '-') IN (@CONTROLLED)
GROUP BY P.PART_ID
	, ISNULL(P.[DESCRIPTION], '_BLANK')
	, P.INSPECTION_REQD
	, ISNULL(P.COMMODITY_CODE, '_BLANK')
	, UDF.CONTROLLED
	, UDF.CERTS_NEEDED
	, CAST(CAST(PB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX))
	, P.STOCK_UM
	, P.PREF_VENDOR_ID
	, ISNULL(P.BUYER_USER_ID, '_BLANK')
	, ISNULL(B.SALESPERSON_ID, '_BLANK')
	, P.PLANNER_USER_ID
	, ISNULL(P.STOCKED, '-')
	, ISNULL(P.FABRICATED, '-')
	, ISNULL(P.PURCHASED, '-')
	, ISNULL(P.CONSUMABLE, '-')
	, UDF.PART_ID