USE LIVE
GO

SELECT * FROM [LIVESupplemental].[dbo].[PartUpdate20210519] U
--TRUNCATE TABLE [LIVESupplemental].[dbo].[PartUpdate20210330]

SELECT P.ID 
, U.[PARTID]
, P.BUYER_USER_ID
, U.BUYER_USER_ID
FROM [LIVESupplemental].[dbo].[PartUpdate20210519] U
LEFT OUTER JOIN LIVE.dbo.PART P
ON P.ID = U.[PARTID]
--WHERE P.ID IS NULL
WHERE ISNULL(P.BUYER_USER_ID, '') != U.BUYER_USER_ID
--> 3506 RECORDS

/*
USE LIVE
GO

; BEGIN TRANSACTION
UPDATE PART
SET BUYER_USER_ID = U.BUYER_USER_ID
FROM [LIVESupplemental].[dbo].[PartUpdate20210519] U
INNER JOIN LIVE.dbo.PART P
ON P.ID = U.PARTID
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

SELECT P.ID 
, U.[PARTID]
, P.BUYER_USER_ID
, U.BUYER_USER_ID
FROM [LIVESupplemental].[dbo].[PartUpdate20210519] U
LEFT OUTER JOIN LIVE.dbo.PART P
ON P.ID = U.[PARTID]
--WHERE P.ID IS NULL
WHERE ISNULL(P.BUYER_USER_ID, '') != U.BUYER_USER_ID
--> 0 RECORDS

-------------------------
SELECT P.PART_ID 
, U.PARTID
, P.BUYER_USER_ID
, U.BUYER_USER_ID
FROM [LIVESupplemental].[dbo].[PartUpdate20210519] U
INNER JOIN LIVE.dbo.PART_SITE P
ON P.PART_ID = U.PARTID
WHERE ISNULL(P.BUYER_USER_ID, '') != U.BUYER_USER_ID
--> 3506 RECORDS

/*
; BEGIN TRANSACTION
UPDATE PART_SITE
SET BUYER_USER_ID = U.BUYER_USER_ID
FROM [LIVESupplemental].[dbo].[PartUpdate20210519] U
INNER JOIN LIVE.dbo.PART_SITE P
ON P.PART_ID = U.PARTID
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

SELECT P.PART_ID 
, U.PARTID
, P.BUYER_USER_ID
, U.BUYER_USER_ID
FROM [LIVESupplemental].[dbo].[PartUpdate20210519] U
INNER JOIN LIVE.dbo.PART_SITE P
ON P.PART_ID = U.PARTID
WHERE ISNULL(P.BUYER_USER_ID, '') != U.BUYER_USER_ID
--> 0 RECORDS