USE LIVE
GO

SELECT A.*
, IT.CLASS
, IT.[TYPE]
, CO.CUSTOMER_ID
, C.ACTIVE_FLAG
, CO.ORDER_DATE
, IT.CUST_ORDER_ID
, IT.WORKORDER_BASE_ID
, IT.TRANSACTION_DATE
FROM 
(SELECT P.ID AS PART_ID
, P.[DESCRIPTION]
, P.[STATUS]
, P.PLANNER_USER_ID
, P.BUYER_USER_ID
, MAX(IT.TRANSACTION_ID) AS TRANSACTION_ID
FROM PART P
INNER JOIN INVENTORY_TRANS IT
ON P.ID = IT.PART_ID
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
AND IT.[CLASS] != 'A'
GROUP BY P.ID
, P.[DESCRIPTION]
, P.[STATUS]
, P.PLANNER_USER_ID
, P.BUYER_USER_ID
) A
INNER JOIN INVENTORY_TRANS IT
ON A.TRANSACTION_ID = IT.TRANSACTION_ID
LEFT OUTER JOIN CUSTOMER_ORDER CO
ON CO.ID = IT.CUST_ORDER_ID
LEFT OUTER JOIN CUSTOMER C
ON CO.CUSTOMER_ID = C.ID
ORDER BY A.PART_ID
, A.[STATUS]
, A.PLANNER_USER_ID
, A.BUYER_USER_ID

--SELECT * FROM INVENTORY_TRANS WHERE PART_ID = '146W0176-86' ORDER BY TRANSACTION_DATE

