USE LIVE
GO

--> DELETE THESE PARTS
SELECT * FROM [dbo].[ObsoleteParts20210224] U

SELECT * FROM ADJUSTMENT_DETAIL X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM CARTON_LINE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS


SELECT * FROM CO_PRODUCT X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 89 ROWS


SELECT * FROM CUST_BOOK_LINE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 1320 ROWS


SELECT * FROM CUST_ORDER_ALLOC X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS


SELECT * FROM CUST_ORDER_LINE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 587 ROWS


SELECT * FROM CUST_PRICE_EFFECT X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 31,550 ROWS

SELECT * FROM CUSTOMER_PRICE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 9,626 ROWS

SELECT * FROM CYCLE_COUNT_PART X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 568 ROWS

SELECT * FROM DEMAND_FORECAST X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM DEMAND_SUPPLY_LINK X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.SUPPLY_PART_ID = U.PART_ID
)
--> 580 ROWS

SELECT * FROM EC_LINE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM ECN_OPERATION X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.SERVICE_PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM ECN_REQUIREMENT X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM ECN_WORKORDER X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM INVENTORY_BALANCE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM INVENTORY_TRANS X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM INVENTORY_TRANS_GOOD X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM LMC_MRP_EXCEPTIONS X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM MASTER_SCHEDULE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM OPERATION X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.SERVICE_PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM OPERATION_TYPE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.SERVICE_PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM PART X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.ID = U.PART_ID
)
--> 37,802 ROWS

SELECT * FROM PART_BINARY X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 668 ROWS

SELECT * FROM PART_CO_BINARY X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM PART_LOCATION X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 23,521 ROWS

SELECT * FROM PART_PO_BINARY X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM PART_SITE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 37,802 ROWS

SELECT * FROM PART_SYNC X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 3,630 ROWS

SELECT * FROM PART_UNITS_CONV X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM PART_WAREHOUSE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 23,683 ROWS

SELECT * FROM PHYS_COUNT_TAG X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 46 ROWS

SELECT * FROM PLANNED_MATL_REQ X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PARENT_PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM PLANNED_MATL_REQ X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.REQUIRED_PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM PLANNED_ORDER X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM PLANNING_FORECAST X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM PURC_MATL_DETAIL X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM PURC_ORDER_LINE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 76 ROWS


SELECT * FROM PURC_REQ_LINE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 2 ROWS

SELECT * FROM REQUIREMENT X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 2 ROWS

SELECT * FROM REQUIREMENT_SCHED X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM SERVICE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.SERVICE_PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM SERVICE_DISP_LINE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.SERVICE_PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM SERVICE_RECEIPT X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.SERVICE_PART_ID = U.PART_ID
)
--> 6 ROWS

SELECT * FROM SERVICE_SITE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.SERVICE_PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM SHIPMENT_DETAIL X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM SHIPMENT_DIST X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM T_ABC_PART X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM TRACE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM TRACE_HISTORY X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM TRACE_INV_TRANS X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM TRACE_PROFILE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 14 ROWS

SELECT * FROM VENDOR_PART X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 2 ROWS

SELECT * FROM VENDOR_QUOTE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.VENDOR_PART_ID = U.PART_ID
)
--> 2 ROWS

SELECT * FROM VENDOR_QUOTE X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.MFG_PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM VR_CUSTORD_DET X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 4 ROWS

SELECT * FROM VR_PURCORD_DET X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 19 ROWS

SELECT * FROM VR_RECEIVER_DET X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 20 ROWS

SELECT * FROM VR_SHIPMENT_DET X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM VR_WORKORDER_HDR X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 13 ROWS

SELECT * FROM WIP_ISSUE_DETAIL X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM WIP_RECEIPT_DETAIL X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 0 ROWS

SELECT * FROM WORK_ORDER X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 808 ROWS

SELECT * FROM WORK_ORDER_SCHED X
WHERE EXISTS(SELECT 1
    FROM [dbo].[ObsoleteParts20210224] U
    WHERE X.PART_ID = U.PART_ID
)
--> 1 ROWS




