SELECT WO.PART_ID AS WO_PART_Id
	, R.PART_ID AS REQ_PART_ID
	, R.USAGE_UM
	, R.CALC_QTY
	, WO.DESIRED_WANT_DATE
	, P.COMMODITY_CODE
	, P.PLANNER_USER_ID
	, WO.BASE_ID
	, WO.SPLIT_ID
	, O.SEQUENCE_NO
	, R.PIECE_NO
	, WO.DESIRED_RLS_DATE
	, PM.QTY_AVAILABLE_ISS
	, PM.[QTY_ON_ORDER]
FROM Datamart.dbo.WORK_ORDER WO
LEFT OUTER JOIN Datamart.dbo.OPERATION O
	ON WO.[TYPE] = 'W'
	AND O.WORKORDER_BASE_ID = WO.BASE_ID
	AND O.WORKORDER_LOT_ID = WO.LOT_ID
	AND O.WORKORDER_SPLIT_ID = WO.SPLIT_ID
	AND O.WORKORDER_SUB_ID = WO.SUB_ID
	AND WO.DESIRED_RLS_DATE >= '1/1/2016'
	AND O.[STATUS] = 'R' 
LEFT OUTER JOIN Datamart.dbo.REQUIREMENT R 
	ON O.WORKORDER_TYPE = R.WORKORDER_TYPE
	AND O.WORKORDER_BASE_ID = R.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = R.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = R.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = R.WORKORDER_SUB_ID
	AND O.SEQUENCE_NO = R.OPERATION_SEQ_NO
LEFT OUTER JOIN Datamart.dbo.PART_SITE_VIEW PM 
	ON R.PART_ID = PM.PART_ID
LEFT OUTER JOIN Datamart.dbo.PART_SITE_VIEW P
	ON WO.PART_ID = P.PART_ID
WHERE WO.[STATUS] = 'R'
	AND PM.PLANNER_USER_ID IN ('MRP', 'NEW', 'PLAN') 
	AND ISNULL(R.PART_ID, '') <> ''

UNION 

SELECT WO.PART_ID AS WO_PART_ID
	, '' AS REQ_PART_ID
	, '' AS USAGE_UM
	, DESIRED_QTY AS CALC_QTY
	, WO.DESIRED_WANT_DATE
	, P.COMMODITY_CODE
	, P.PLANNER_USER_ID
	, WO.BASE_ID
	, WO.SPLIT_ID
	, NULL AS SEQUENCE_NO
	, NULL AS PIECE_NO
	, WO.DESIRED_RLS_DATE
	, P.QTY_AVAILABLE_ISS
	, P.[QTY_ON_ORDER]
FROM Datamart.dbo.WORK_ORDER WO
LEFT OUTER JOIN Datamart.dbo.PART_SITE_VIEW P
	ON WO.PART_ID = P.PART_ID
	AND P.PART_ID <> 'REWORK MFG'
WHERE WO.[STATUS] = 'R' 
	AND P.PLANNER_USER_ID IN ('MRP', 'NEW', 'PLAN') 
ORDER BY WO.PART_ID
	, WO.DESIRED_RLS_DATE
