USE DataWarehouse
GO

/* Planning MFG On Time 
Separates CMP and Non-CMP by Planner_user_id on the part table.
Sliding year for showing trends

-- calculating the start_date
-- if the desired release date is before the create date then it is a replacement so use the create date
-- if the base_id contains an R then it is a rework work order and it is expected to use the create date
-- if the desired release date is after the create date then it is regular

-- calculating Ontime/Late
-- if the start_date is MFG-CMP then only 4 work days is allowed for completion
-- if the start_date is MFG-NON-CMP then only 7 work days is allowed for completion 
*/

; WITH CTE_WO AS 
(SELECT CASE 
	WHEN P.PLANNER_USER_ID = 'MFG-HOURLY' THEN 'MFG-CMP' 
	ELSE 'MFG-NON-CMP'
	END AS CMP_NON_CMP
	, CASE 
		WHEN WO.BASE_ID NOT LIKE '%R%' AND DATEDIFF(DD, WO.CREATE_DATE,WO.DESIRED_RLS_DATE) < 0 THEN 'REPLACEMENT'
		WHEN WO.BASE_ID LIKE '%R%' AND DATEDIFF(DD, WO.CREATE_DATE,WO.DESIRED_RLS_DATE) < 0 THEN 'REWORK'
		ELSE 'REGULAR'
	END AS WO_CATEGORY
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.[TYPE]
	, WO.PART_ID
	, P.PLANNER_USER_ID
	, CONVERT(DATE, WO.CREATE_DATE) AS CREATE_DATE
	, WO.DESIRED_RLS_DATE
	, WO.PRINTED_DATE
	, CASE 
		WHEN WO.BASE_ID NOT LIKE '%R%' AND DATEDIFF(DD, WO.CREATE_DATE, WO.DESIRED_RLS_DATE) < 0 THEN CONVERT(DATE, WO.CREATE_DATE) -- REPLACEMENT
		WHEN WO.BASE_ID LIKE '%R%' AND DATEDIFF(DD, WO.CREATE_DATE, WO.DESIRED_RLS_DATE) < 0 THEN CONVERT(DATE, WO.CREATE_DATE) -- REWORK
		ELSE CONVERT(DATE, WO.DESIRED_RLS_DATE)--'REGULAR'
	END AS [START_DATE]
FROM WORK_ORDER WO
INNER JOIN PART P
	ON WO.PART_ID = P.ID
WHERE LEFT(P.PLANNER_USER_ID, 3) = 'MFG'
	AND CONVERT(DATE, WO.DESIRED_RLS_DATE) >= GETDATE() - 365
	AND WO.[TYPE] = 'W'
	AND WO.SUB_ID = '0'
	AND WO.SPLIT_ID = '0'
)

, CTE_WO2 AS 
(SELECT CMP_NON_CMP
	, WO_CATEGORY
	, BASE_ID
	, LOT_ID 
	, SPLIT_ID
	, SUB_ID
	, [TYPE]
	, PART_ID
	, PLANNER_USER_ID
	, CREATE_DATE
	, DESIRED_RLS_DATE
	, PRINTED_DATE
	, DATENAME(DW, [START_DATE]) AS DAYNAME
	, [START_DATE]
	, CASE 
		WHEN DATEPART(WEEKDAY, [START_DATE]) = 7 THEN DATEADD(DW, 2, [START_DATE]) 
		WHEN DATEPART(WEEKDAY, [START_DATE]) = 1 THEN DATEADD(DW, 1, [START_DATE]) 
		ELSE [START_DATE]
	END AS START_DATE_ADJ
FROM CTE_WO
)

, CTE_WAITDAYS AS
(SELECT WO.CMP_NON_CMP
	, WO_CATEGORY
	, WO.BASE_ID 
	, WO.LOT_ID 
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.[TYPE]
	, WO.PART_ID
	, PLANNER_USER_ID
	, WO.CREATE_DATE 
	, WO.DESIRED_RLS_DATE
	, O.CLOSE_DATE
	, O.[STATUS]
	, O.RESOURCE_ID
	, O.OPERATION_TYPE
	, WO.PRINTED_DATE 
	, WO.START_DATE_ADJ
	, DATEDIFF(DW,WO.START_DATE_ADJ, COALESCE(O.CLOSE_DATE, WO.PRINTED_DATE, GETDATE())) AS WAIT_DAYS
	, CASE 
		WHEN CMP_NON_CMP = 'MFG-NON-CMP' AND DATEDIFF(DW, WO.START_DATE_ADJ, COALESCE(O.CLOSE_DATE, WO.PRINTED_DATE, GETDATE())) <= 7 THEN 'ON-TIME'
		WHEN CMP_NON_CMP = 'MFG-CMP' AND DATEDIFF(DW, WO.START_DATE_ADJ, COALESCE(O.CLOSE_DATE, WO.PRINTED_DATE, GETDATE())) <= 4 THEN 'ON-TIME'
		ELSE 'LATE'
	END AS ONTIME_LATE
FROM CTE_WO2 WO
INNER JOIN OPERATION O
	ON WO.TYPE = O.WORKORDER_TYPE
	AND WO.BASE_ID = O.WORKORDER_BASE_ID
	AND WO.LOT_ID = O.WORKORDER_LOT_ID
	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND WO.SUB_ID = O.WORKORDER_SUB_ID
WHERE O.RESOURCE_ID LIKE '%REVIEW%'
	AND O.[STATUS] NOT IN ('X')
)
--SELECT *  FROM CTE_WAITDAYS

SELECT CMP_NON_CMP
	, WO_CATEGORY
	, BASE_ID
	, LOT_ID 
	, SPLIT_ID
	, SUB_ID
	, [TYPE]
	, PART_ID
	, RESOURCE_ID
	, OPERATION_TYPE
	, PLANNER_USER_ID
	, CREATE_DATE
	, DESIRED_RLS_DATE
	, CLOSE_DATE
	, [STATUS]
	, PRINTED_DATE
	, START_DATE_ADJ
	, WAIT_DAYS
	, ONTIME_LATE
	, RIGHT('00' + CONVERT(VARCHAR(2), MONTH(START_DATE_ADJ)), 2) + '-' + CONVERT(VARCHAR(4), YEAR(START_DATE_ADJ)) AS START_LABEL
FROM CTE_WAITDAYS