
SELECT RL.[INVOICE_ID]
, RL.[LINE_NO]
, RL.[REFERENCE]
, RL.[QTY]
, RL.[GL_ACCOUNT_ID]
, RL.[CUST_ORDER_ID]
, RL.[CUST_ORDER_LINE_NO]
, RL.[PACKLIST_ID]
, RL.[PACKLIST_LINE_NO]
, R.[CUSTOMER_ID]
, R.[TYPE]
, R.[INVOICE_DATE]
, R.[TOTAL_AMOUNT]
, R.[PAID_AMOUNT]
, R.[POSTING_DATE]
, CO.[ORDER_DATE]
, CO.[DESIRED_SHIP_DATE]
, CO.[STATUS]
, CO.[TOTAL_AMT_ORDERED] AS CO_TOTAL_AMOUNT
, CO.[TOTAL_AMT_SHIPPED] AS CO_TOTAL_SHIPPED
, COL.[PART_ID]
, COL.[LINE_STATUS]
, COL.[ORDER_QTY]
, COL.[COMMODITY_CODE]
, COL.[TOTAL_SHIPPED_QTY] AS COL_TOTAL_SHIPQTY
, COL.[TOTAL_AMT_SHIPPED] AS COL_TOTAL_SHIPPED
, COL.[TOTAL_AMT_ORDERED] AS COL_TOTAL_ORDERED
--'[RECEIVABLE_LINE] RL' AS MSG01
--, RL.*
--, 'RECEIVABLE R' AS MSG02
--, R.*
--, 'CUST_ORDER_LINE COL' AS MSG03
--, CO.*
--, 'CUSTOMER_ORDER CO' AS MSG04
--, COL.*
FROM [LIVE].[dbo].[RECEIVABLE_LINE] RL
INNER JOIN RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
LEFT OUTER JOIN CUST_ORDER_LINE COL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON CO.ID = RL.[CUST_ORDER_ID]
WHERE CO.ORDER_DATE >= '1/1/2020'
and r.invoice_id = '1298137'
