USE DataWarehouse
GO

DECLARE @STARTDATE DATE = '1/25/2021'
, @ENDDATE DATE = '2/1/2021'

; WITH CTE_PLANNERS AS
(SELECT P.*
FROM LIVESupplemental.dbo.PlannersList AS P
INNER JOIN EMPLOYEE EE
	ON P.EMPID = EE.ID
--	AND EE.[ACTIVE] = 'Y'
)

SELECT CASE
		WHEN SUBSTRING(WO.ENGINEERED_BY, CHARINDEX(P.FILTER_STRING, WO.ENGINEERED_BY), LEN(P.FILTER_STRING)) 
			= P.FILTER_STRING THEN P.[LOCATION]
		WHEN SUBSTRING(WO.ENGINEERED_BY, CHARINDEX(P2.FILTER_STRING, WO.ENGINEERED_BY), LEN(P2.FILTER_STRING)) 
			= P2.FILTER_STRING THEN P2.[LOCATION]
		WHEN SUBSTRING(WO.ENGINEERED_BY, CHARINDEX(P3.FILTER_STRING, WO.ENGINEERED_BY), LEN(P3.FILTER_STRING)) 
			= P3.FILTER_STRING THEN P3.[LOCATION]
		WHEN SUBSTRING(WO.ENGINEERED_BY, CHARINDEX(P4.FILTER_STRING, WO.ENGINEERED_BY), LEN(P4.FILTER_STRING)) 
			= P4.FILTER_STRING THEN P4.[LOCATION]
		WHEN SUBSTRING(WO.ENGINEERED_BY, CHARINDEX(P5.FILTER_STRING, WO.ENGINEERED_BY), LEN(P5.FILTER_STRING)) 
			= P5.FILTER_STRING THEN P5.[LOCATION]
		WHEN SUBSTRING(WO.ENGINEERED_BY, CHARINDEX(P6.FILTER_STRING, WO.ENGINEERED_BY), LEN(P6.FILTER_STRING)) 
			= P6.FILTER_STRING THEN P6.[LOCATION]
		ELSE '_BLANK'
	END AS LOCATION
	, COALESCE(P.LINE_OF_BUSINESS, P2.LINE_OF_BUSINESS, P3.LINE_OF_BUSINESS, P4.LINE_OF_BUSINESS, P5.LINE_OF_BUSINESS, P6.LINE_OF_BUSINESS, '_BLANK') AS LINE_OF_BUSINESS
	, COALESCE(P.EMPID, P2.EMPID, P3.EMPID, P4.EMPID, P5.EMPID, P6.EMPID, '_BLANK') AS EMPID
	, CASE
		WHEN SUBSTRING(WO.ENGINEERED_BY, CHARINDEX(P.FILTER_STRING, WO.ENGINEERED_BY), LEN(P.FILTER_STRING)) = P.FILTER_STRING 
				THEN P.[NAME]
		WHEN SUBSTRING(WO.ENGINEERED_BY, CHARINDEX(P2.FILTER_STRING, WO.ENGINEERED_BY), LEN(P2.FILTER_STRING)) = P2.FILTER_STRING 
			THEN P2.[NAME]
		WHEN SUBSTRING(WO.ENGINEERED_BY, CHARINDEX(P3.FILTER_STRING, WO.ENGINEERED_BY), LEN(P3.FILTER_STRING)) = P3.FILTER_STRING 
			THEN P3.[NAME]
		WHEN SUBSTRING(WO.ENGINEERED_BY, CHARINDEX(P4.FILTER_STRING, WO.ENGINEERED_BY), LEN(P4.FILTER_STRING)) = P4.FILTER_STRING 
			THEN P4.[NAME]
		WHEN SUBSTRING(WO.ENGINEERED_BY, CHARINDEX(P5.FILTER_STRING, WO.ENGINEERED_BY), LEN(P5.FILTER_STRING)) = P5.FILTER_STRING 
			THEN P5.[NAME]
		WHEN SUBSTRING(WO.ENGINEERED_BY, CHARINDEX(P6.FILTER_STRING, WO.ENGINEERED_BY), LEN(P6.FILTER_STRING)) = P6.FILTER_STRING 
			THEN P6.[NAME]
		ELSE '_BLANK'
	END AS [NAME]
	, WO.[TYPE]
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, CAST(WO.CREATE_DATE AS DATE) AS CREATE_DATE
	, WO.[STATUS]
	, WO.ENGINEERED_BY
FROM WORK_ORDER AS WO
LEFT OUTER JOIN CTE_PLANNERS AS P
	ON RIGHT(WO.ENGINEERED_BY, 4) = P.FILTER_STRING
LEFT OUTER JOIN CTE_PLANNERS AS P2
	ON RIGHT(WO.ENGINEERED_BY, 3) = P2.FILTER_STRING
LEFT OUTER JOIN CTE_PLANNERS AS P3
	ON RIGHT(WO.ENGINEERED_BY, 2) = P3.FILTER_STRING
LEFT OUTER JOIN CTE_PLANNERS AS P4
	ON LEFT(WO.ENGINEERED_BY, 4) = P4.FILTER_STRING
LEFT OUTER JOIN CTE_PLANNERS AS P5
	ON LEFT(WO.ENGINEERED_BY, 3) = P5.FILTER_STRING
LEFT OUTER JOIN CTE_PLANNERS AS P6
	ON LEFT(WO.ENGINEERED_BY, 2) = P6.FILTER_STRING
WHERE WO.CREATE_DATE >= @STARTDATE
	AND WO.CREATE_DATE < @ENDDATE
	AND WO.[TYPE] IN (@WOTYPE)
	AND WO.[STATUS] IN (@WOSTATUS)

/*
SELECT * FROM
(SELECT LINE_OF_BUSINESS
, [LOCATION]
, [NAME]
, BASE_ID
FROM CTE_BASE
) AS SOURCETABLE
PIVOT(
	COUNT (BASE_ID)
	FOR LINE_OF_BUSINESS IN ([FIN], [MFG], [No Longer Here], [_BLANK])
) AS PIVOT_TABLE;

*/

SELECT STATUS FROM WORK_ORDER GROUP BY STATUS ORDER BY STATUS