SELECT CO.CUSTOMER_ID
	, COL.LINE_NO
	, COL.PART_ID
	, COL.CUST_ORDER_ID
	, S.SHIPPED_DATE
	, SL.SHIPPED_QTY
	, COL.DESIRED_SHIP_DATE
	, SL.USER_SHIPPED_QTY
	, COL.UNIT_PRICE
	, COL.MISC_REFERENCE
	, P.BUYER_USER_ID
	, S.STATUS
FROM CUSTOMER_ORDER CO
LEFT OUTER JOIN CUST_ORDER_LINE COL
	ON CO.ID = COL.CUST_ORDER_ID
LEFT OUTER JOIN SHIPPER_LINE SL
	ON COL.CUST_ORDER_ID = SL.CUST_ORDER_ID
	AND COL.LINE_NO = SL.CUST_ORDER_LINE_NO 
LEFT OUTER JOIN PART P
	ON COL.PART_ID = P.ID
LEFT OUTER JOIN SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID
WHERE S.STATUS = 'A' 
	AND CO.CUSTOMER_ID in ('AMTMFG', 'BOEDEF', 'BOEPOP', 'BOETRN', 'GKNSOU', 'GLOMAC', 'KURMAN', 'NIKVIE', 'NORGRU' 
		', 'PMWINC', 'PREAER', 'PRIMUS', 'ROYFAB', 'SPIAER', 'TIGINC', 'TRICOM', 'TRIGRO', 'TRIINS', 'TRISLA' , 'TRISWI' , 'UNISWA') 
	AND (S.SHIPPED_DATE >= 1/1/2018 
		AND S.SHIPPED_DATE < '1/1/2019')
ORDER BY CO.CUSTOMER_ID
, S.SHIPPED_DATE
, COL.DESIRED_SHIP_DATE


