USE LIVE
GO

SELECT 
--> PARAMETERS
	CASE
		WHEN DSL2.DEMAND_BASE_ID IS NOT NULL THEN CO.CUSTOMER_ID
		ELSE '_UNLINKED'
	END AS CUSTID
	, CASE
		WHEN DSL.DEMAND_BASE_ID IS NOT NULL THEN 'Y'
		ELSE 'N'
	END AS WO_RELATED
	, CASE
		WHEN R.PURC_ORDER_ID IS NOT NULL THEN 'Y'
		ELSE 'N'
	END AS RECEIVED
	, CASE
		WHEN YL.VOUCHER_ID IS NOT NULL THEN 'Y'
		ELSE 'N'
	END AS PAID
--> PURCHASE ORDER/LINE
	, POL.[PURC_ORDER_ID]
	, PO.[STATUS] AS PO_STATUS
	, POL.[LINE_NO] AS PO_LINE
	, POL.[LINE_STATUS] AS POL_LINE_STATUS
	, POL.[PART_ID] AS PO_PARTID
	, POL.[VENDOR_PART_ID] AS PO_VENDOR_PARTID
	, POL.[SERVICE_ID] AS PO_SERVICEID
	, PO.[ORDER_DATE] AS PO_ORDER_DATE
	, ISNULL(POL.[DESIRED_RECV_DATE], PO.[DESIRED_RECV_DATE]) AS PO_DESIRED_RECV_DATE
	, POL.[ORDER_QTY] AS POL_ORDER_QTY
	, POL.[PURCHASE_UM] AS PO_UM
	, POL.[UNIT_PRICE] AS POL_UNIT_PRICE
	, POL.[TOTAL_RECEIVED_QTY] AS POL_TTL_QTY_RCVD
	, POL.[TOTAL_AMT_RECVD] AS POL_TTL_AMT_RCVD
	, POL.[TOTAL_AMT_ORDERED] AS POL_TTL_AMT_ORDERED
	, POL.[ENTERED_BY] AS POL_ENTERED_BY
	, PO.[VENDOR_ID] AS PO_VENDOR
	, PO.[BUYER] AS PO_BUYER
	, PO.[TOTAL_AMT_ORDERED] AS PO_TTL_AMT_ORDERED
	, PO.[TOTAL_AMT_RECVD] AS PO_TTL_AMT_RCVD
	, CAST(CAST(POB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [PO_BINARY]
	, CAST(CAST(PLB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [POL_BINARY]
--> PURCHASE REQUISITION/LINE
	, PRL.PURC_REQ_ID
	, PR.[STATUS] AS PR_STATUS
	, PRL.LINE_NO AS PRL_LINE
	, PRL.LINE_STATUS AS PRL_STATUS
	, ISNULL(PRL.DESIRED_RECV_DATE, PR.DESIRED_RECV_DATE) AS PR_DESIRED_RECV_DATE
	, PR.REQUISITION_DATE
	, PRL.PART_ID AS PR_PARTID
	, PRL.VENDOR_ID AS PR_VENDOR
	, PRL.VENDOR_PART_ID AS PR_VENDOR_PARTID
	, PRL.ORDER_QTY AS PR_ORDER_QTY
	, PRL.UNIT_PRICE AS PR_UNIT_PRICE
	, PR.BUYER AS PR_BUYER
	, PR.PREPARER AS PR_PREPARER
	, PR.REQUESTOR AS PR_REQUESTOR
	, PR.ASSIGNED_TO AS PR_ASSIGNED_TO
--> RECEIVER/LINE
	, RL.[RECEIVER_ID]
	, RL.[LINE_NO] AS RCVR_LINE
	, RL.[RECEIVED_QTY]
	, RL.[WAREHOUSE_ID] AS RCVR_WAREHOUSE
	, RL.[LOCATION_ID] AS RCVR_LOCATION
	, RL.[TRANSACTION_ID] AS RL_TRANSACTION_ID
	, RL.[UNIT_PRICE] AS RCVL_UNIT_PRICE
	, R.[RECEIVED_DATE] AS RCVR_RECEIVED_DATE
	, R.[USER_ID] AS RCVR_RECEIVED_BY
--> PAYABLE_LINE
--	, Y.VOUCHER_ID AS PBL_VOUCHER_ID
	, Y.INVOICE_ID AS PBL_INVOICE_ID
--	, RL.INVOICE_ID AS RVCRLINE_INVOICE_ID
	, YL.VOUCHER_ID AS PAY_VOUCHER_ID
	, YL.LINE_NO AS PAY_LINE
	, YL.REFERENCE AS YL_REFERENCE
	, YL.QTY AS PAY_QTY
	, YL.AMOUNT AS PAY_AMOUNT
--> WORK ORDER
	, WO.[TYPE] AS WO_TYPE
	, WO.[BASE_ID]
	, WO.[LOT_ID]
	, WO.[SPLIT_ID]
	, WO.[SUB_ID]
	, WO.[PART_ID] AS WO_PART_ID
	, WO.[DESIRED_QTY] AS WO_DESIRED_QTY
	, WO.[CREATE_DATE] AS WO_CREATE_DATE
	, WO.[DESIRED_RLS_DATE] AS WO_DESIRED_RLS_DATE
	, WO.[DESIRED_WANT_DATE] AS WO_DESIRED_WANT_DATE 
	, WO.[CLOSE_DATE] AS WO_CLOSE_DATE
	, WO.[STATUS] AS WO_STATUS
--> WORK ORDER COSTS
	, WO.[ACT_MATERIAL_COST] AS WO_ACT_MATERIAL_COST
	, WO.[ACT_LABOR_COST] AS WO_ACT_LABOR_COST
	, WO.[ACT_BURDEN_COST] AS WO_ACT_BURDEN_COST
	, WO.[ACT_SERVICE_COST] AS WO_ACT_SERVICE_COST
--> CUSTOMER ORDER/LINE
	, COL.[CUST_ORDER_ID]
	, COL.[LINE_NO] AS COL_LINE
	, COL.[PART_ID] AS COL_PART_ID
	, COL.[CUSTOMER_PART_ID] AS COL_CUST_PARTID
	, COL.[LINE_STATUS] AS COL_STATUS
	, COL.[ORDER_QTY] AS COL_ORDER_QTY
	, COL.[DESIRED_SHIP_DATE] AS COL_DESIRED_SHIP_DATE
	, COL.[UNIT_PRICE] AS COL_UNIT_PRICE
	, COL.[TOTAL_AMT_SHIPPED] AS COL_TTL_AMT_SHIPPED
	, CO.[CUSTOMER_ID]
	, CO.[ORDER_DATE] AS CO_ORDER_DATE
	, CO.[STATUS] AS CO_STATUS
--> PART MAINTENANCE
	, ISNULL(P.[DESCRIPTION], P2.[DESCRIPTION]) AS [PART_DESCRIPTION]
	, ISNULL(P.[STOCK_UM], P.[STOCK_UM]) AS [STOCK_UM]
	, ISNULL(P.[COMMODITY_CODE], P.[COMMODITY_CODE]) AS [COMMODITY_CODE]
	, ISNULL(P.[FABRICATED], P.[FABRICATED]) AS [FABRICATED]
	, ISNULL(P.[PURCHASED], P.[PURCHASED]) AS [PURCHASED]
	, ISNULL(P.[STOCKED], P.[STOCKED]) AS [STOCKED]
	, ISNULL(P.[TOOL_OR_FIXTURE], P.[TOOL_OR_FIXTURE]) AS [TOOL_OR_FIXTURE]
	, ISNULL(P.[PLANNER_USER_ID], P.[PLANNER_USER_ID]) AS [PLANNER_USER_ID]
	, ISNULL(P.[BUYER_USER_ID], P.[BUYER_USER_ID]) AS [BUYER_USER_ID]
	, ISNULL(P.[QTY_ON_HAND], P.[QTY_ON_HAND]) AS [QTY_ON_HAND]
	, ISNULL(P.[QTY_AVAILABLE_ISS], P.[QTY_AVAILABLE_ISS]) AS [QTY_AVAILABLE_ISS]
	, ISNULL(P.[QTY_AVAILABLE_MRP], P.[QTY_AVAILABLE_MRP]) AS [QTY_AVAILABLE_MRP]
	, ISNULL(P.[QTY_ON_ORDER], P.[QTY_ON_ORDER]) AS [QTY_ON_ORDER]
	, ISNULL(P.[QTY_IN_DEMAND], P.[QTY_IN_DEMAND]) AS [QTY_IN_DEMAND]
FROM PURC_ORDER_LINE POL
INNER JOIN PURCHASE_ORDER PO
	ON PO.ID = POL.PURC_ORDER_ID
LEFT OUTER JOIN PURC_ORDER_REQ POR
	ON POL.PURC_ORDER_ID = POR.PURC_ORD_ID 
	AND POL.LINE_NO = POR.PURC_ORD_LINE_NO
LEFT OUTER JOIN PURC_REQ_LINE PRL
	ON PRL.PURC_REQ_ID = POR.PURC_REQ_ID 
	AND PRL.LINE_NO = POR.PURC_REQ_LINE_NO
LEFT OUTER JOIN PURC_REQUISITION PR
	ON PRL.PURC_REQ_ID = PR.ID 
LEFT OUTER JOIN RECEIVER_LINE RL
	ON POL.PURC_ORDER_ID = RL.PURC_ORDER_ID 
	AND POL.LINE_NO = RL.PURC_ORDER_LINE_NO
LEFT OUTER JOIN RECEIVER R
	ON RL.RECEIVER_ID = R.ID 
LEFT OUTER JOIN PAYABLE_LINE YL
	ON POL.PURC_ORDER_ID = YL.PURC_ORDER_ID 
	AND POL.LINE_NO = YL.PURC_ORDER_LINE_NO
LEFT OUTER JOIN PAYABLE Y
	ON YL.VOUCHER_ID = Y.VOUCHER_ID
--	AND Y.INVOICE_ID = RL.INVOICE_ID
LEFT OUTER JOIN DEMAND_SUPPLY_LINK AS DSL
	ON POL.PURC_ORDER_ID = DSL.SUPPLY_BASE_ID
	AND POL.LINE_NO = DSL.SUPPLY_SEQ_NO
	AND DSL.SUPPLY_TYPE = 'PO'
LEFT OUTER JOIN WORK_ORDER WO
	ON DSL.DEMAND_BASE_ID = WO.BASE_ID
	AND DSL.DEMAND_LOT_ID = WO.LOT_ID
	AND DSL.DEMAND_SPLIT_ID = WO.SPLIT_ID
	AND DSL.DEMAND_SUB_ID = WO.SUB_ID
	AND WO.[TYPE] = 'W'
LEFT OUTER JOIN DEMAND_SUPPLY_LINK AS DSL2
	ON DSL2.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL2.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL2.SUPPLY_SPLIT_ID = WO.SPLIT_ID
	AND DSL2.SUPPLY_SUB_ID = WO.SUB_ID
	AND DSL2.SUPPLY_TYPE = 'WO'
LEFT OUTER JOIN CUST_ORDER_LINE COL
	ON DSL2.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL2.DEMAND_SEQ_NO = COL.LINE_NO
	AND DSL2.DEMAND_TYPE = 'CO'
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
LEFT OUTER JOIN PART P
	ON POL.PART_ID = P.ID
LEFT OUTER JOIN PART P2
	ON WO.PART_ID = P2.ID
LEFT OUTER JOIN PURC_LINE_BINARY PLB
	ON POL.PURC_ORDER_ID = PLB.PURC_ORDER_ID 
	AND POL.LINE_NO = PLB.PURC_ORDER_LINE_NO
LEFT OUTER JOIN PURC_ORDER_BINARY POB
	ON PO.ID = POB.PURC_ORDER_ID
WHERE (PO.ORDER_DATE >= '1/1/2019') OR PO.[STATUS] IN ('F', 'R')

/*

--=Iif(InStr(Join(Parameters!IncludeColumns.Value, "," ), "PR WO Info") > 0, false, true)
IncludeColumns:
	PO BINARY
	POL BINARY
	PURC REQUEST
	RECEIVER
	PAYABLE
	WORK ORDER
	WO COSTS
	CUSTOMER ORDER
	PART DESCRIPTION
	PART QTY
	PARAMS


*/