SELECT P.ID AS PART_ID
	, P.[DESCRIPTION]
	, P.STOCK_UM
	, POL.PURCHASE_UM
	, POL.PURC_ORDER_ID
	, POL.ORDER_QTY
	, PO.CREATE_DATE
	, ISNULL(POL.DESIRED_RECV_DATE, PO.DESIRED_RECV_DATE) AS DESIRED_RECV_DATE
	, PO.[STATUS]
FROM PART P
INNER JOIN PURC_ORDER_LINE POL
	ON P.ID = POL.PART_ID
INNER JOIN PURCHASE_ORDER PO
	ON POL.PURC_ORDER_ID = PO.ID
WHERE P.STOCK_UM <> POL.PURCHASE_UM
	 AND PO.[STATUS] NOT IN ('C', 'X')
