USE [LIVE]
GO

/****** Object:  Trigger [dbo].[INSERT_PURCHASE_ORDER]    Script Date: 9/15/2021 7:20:36 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE trigger [dbo].[INSERT_PURCHASE_ORDER] ON [dbo].[PURCHASE_ORDER] FOR INSERT AS
DECLARE @nRcd INT,
	@ID NVARCHAR(15),
	@VENDOR_ID NVARCHAR(15),
	@SITE_ID NVARCHAR(15),
	@STATUS NCHAR,
	@TOTAL_AMT_ORDERED DEC(23,8),
	@TOTAL_AMT_RECVD DEC(23,8),
	@SELL_RATE DEC(15,8),
	@nCurrDigits INT,
	@sEntityID NVARCHAR(15),
	@ORDER_DATE DATETIME
SELECT @nRcd = 0
SET NOCOUNT ON
DECLARE PURCHASE_ORDER_INS CURSOR LOCAL FOR SELECT ID, VENDOR_ID, STATUS, TOTAL_AMT_ORDERED, TOTAL_AMT_RECVD, SELL_RATE, ORDER_DATE, SITE_ID FROM INSERTED
OPEN PURCHASE_ORDER_INS
FETCH PURCHASE_ORDER_INS INTO @ID, @VENDOR_ID, @STATUS, @TOTAL_AMT_ORDERED, @TOTAL_AMT_RECVD, @SELL_RATE, @ORDER_DATE, @SITE_ID
WHILE (@nRcd = 0 and @@FETCH_STATUS <> -1)
BEGIN
	EXEC EXE_DETECT_EVENT 'P', @ID, NULL, NULL, 'I'
	If @TOTAL_AMT_ORDERED + @TOTAL_AMT_RECVD != 0
		SELECT @nRcd = 30881
	If @nRcd = 0 
		And (@STATUS = 'R' Or @STATUS = 'F') 
		And @TOTAL_AMT_ORDERED > @TOTAL_AMT_RECVD
		BEGIN
		select @nCurrDigits = c.i_curr_digits
			, @sEntityID = s.entity_id from CURRENCY c
			, ACCOUNTING_ENTITY ae
			, SITE s where s.id = @SITE_ID 
			and ae.id = s.entity_id 
			and ae.functional_currency_id = c.id
		IF NOT EXISTS (SELECT VENDOR_ID FROM VENDOR_ENTITY WHERE vendor_id = @VENDOR_ID and entity_id = @sEntityID )
			INSERT INTO VENDOR_ENTITY (VENDOR_ID, ENTITY_ID) VALUES (@VENDOR_ID, @sEntityID)
		update VENDOR_ENTITY 
			set total_open_orders = total_open_orders + ROUND((@TOTAL_AMT_ORDERED - @TOTAL_AMT_RECVD) * @SELL_RATE, @nCurrDigits)
			, open_order_count = open_order_count + 1
			where vendor_id = @VENDOR_ID and entity_id = @sEntityID
		END
	UPDATE VENDOR 
		set last_order_date = @ORDER_DATE 
		where id = @VENDOR_ID
	FETCH PURCHASE_ORDER_INS INTO @ID, @VENDOR_ID, @STATUS, @TOTAL_AMT_ORDERED, @TOTAL_AMT_RECVD, @SELL_RATE, @ORDER_DATE, @SITE_ID
END
DEALLOCATE PURCHASE_ORDER_INS
IF (@nRcd <> 0) RAISERROR('VMFG-%d error in trigger INSERT_PURCHASE_ORDER', 16, -1, @nRcd)
IF (@nRcd <> 0 Or @@ERROR <> 0) ROLLBACK TRANSACTION 
GO

ALTER TABLE [dbo].[PURCHASE_ORDER] ENABLE TRIGGER [INSERT_PURCHASE_ORDER]
GO


