USE LIVE
GO

DECLARE @PO NVARCHAR(15) = '118367'

SELECT POL.PURC_ORDER_ID
, POL.LINE_NO AS PO_LINE
, PAL.RECEIVER_ID
, CD.CHECK_NO
, CDL.VOUCHER_ID
, PAY.INVOICE_ID
, PRL.PURC_REQ_ID
, PRL.LINE_NO AS PR_LINE
FROM PURCHASE_ORDER PO 
INNER JOIN PURC_ORDER_LINE POL 
	ON PO.ID = POL.PURC_ORDER_ID 
INNER JOIN PAYABLE_LINE PAL 
	ON POL.PURC_ORDER_ID = PAL.PURC_ORDER_ID 
	AND POL.LINE_NO = PAL.PURC_ORDER_LINE_NO 
INNER JOIN CASH_DISBURSE_LINE CDL 
	ON CDL.VOUCHER_ID = PAL.VOUCHER_ID 
INNER JOIN CASH_DISBURSEMENT CD 
	ON CD.BANK_ACCOUNT_ID = CDL.BANK_ACCOUNT_ID 
	AND CD.CONTROL_NO = CDL.CONTROL_NO 
INNER JOIN PAYABLE PAY
	ON PAL.VOUCHER_ID = PAY.VOUCHER_ID 
	AND CDL.VOUCHER_ID = PAY.VOUCHER_ID
LEFT OUTER JOIN PURC_ORDER_REQ POR
	ON POL.PURC_ORDER_ID = POR.PURC_ORD_ID
	AND POL.LINE_NO = POR.PURC_ORD_LINE_NO
LEFT OUTER JOIN PURC_REQ_LINE PRL
	ON POR.PURC_REQ_ID = PRL.PURC_REQ_ID
	AND POR.PURC_REQ_LINE_NO = PRL.LINE_NO
LEFT OUTER JOIN PURC_REQUISITION PR
	ON PRL.PURC_REQ_ID = PR.ID
WHERE PO.ID = @PO

--CDL.VOUCHER_ID = '204923'