USE LIVE
GO

--> POS THAT HAVE BEEN RECEIVED BUT NOT VOUCHERED
--> RECEIVERS NOT VOUCHERED

IF OBJECT_ID('tempdb..#T1') IS NOT NULL DROP TABLE #T1

SET DATEFIRST 7; -- Set's sunday as first day of week, won't work otherwise

DECLARE @STARTDATE DATE = '01/01/2021'
, @ENDDATE DATETIME = '12/31/2022'
, @CURRENTDATE DATETIME

DECLARE @TABLEOFDATES TABLE(DATEVALUE DATETIME)

SET @CURRENTDATE = @STARTDATE

WHILE @CURRENTDATE <= @ENDDATE
	BEGIN
		INSERT INTO @TABLEOFDATES(DATEVALUE) VALUES (@CURRENTDATE)
		SET @CURRENTDATE = DATEADD(DAY, 1, @CURRENTDATE)
	END

SELECT * 
INTO #T1
FROM @TABLEOFDATES 
WHERE DATEPART(WEEKDAY, DATEVALUE) = 2

SET DATEFIRST 7; -- Set's sunday as first day of week, won't work otherwise

; WITH CTEBASE AS 
(SELECT RL.RECEIVER_ID
	, RL.LINE_NO AS RCV_LN
	, RL.PURC_ORDER_ID
	, RL.PURC_ORDER_LINE_NO AS PO_LN
	, R.RECEIVED_DATE
	, RL.RECEIVED_QTY
	, RL.SERV_TRANS_ID
	, RL.TRANSACTION_ID
	, RL.UNIT_PRICE
	, RL.RECEIVED_QTY * RL.UNIT_PRICE AS ACCURAL_AMOUNT
--	, AP.INVOICE_DATE AS VOUCHER_DATE
--	, AP.CREATE_DATE AS VOUCHER_DATE
	, (SELECT MIN(CREATE_DATE) AS POSTING_DATE
		FROM PAYABLE_LINE APL 
		JOIN PAYABLE AP 
			ON APL.VOUCHER_ID = AP.VOUCHER_ID 
--			AND PAY_STATUS IN ('P', 'H')
			AND APL.RECEIVER_ID = RL.RECEIVER_ID 
			AND APL.RECEIVER_LINE_NO = RL.LINE_NO
	) AS VOUCHER_CREATE_DATE
	, (SELECT MIN(POSTING_DATE) AS POSTING_DATE
		FROM PAYABLE_LINE APL 
		JOIN PAYABLE AP 
			ON APL.VOUCHER_ID = AP.VOUCHER_ID 
			AND PAY_STATUS IN ('P', 'H')
			AND APL.RECEIVER_ID = RL.RECEIVER_ID 
			AND APL.RECEIVER_LINE_NO = RL.LINE_NO
	) AS VOUCHER_POSTING_DATE
	, (SELECT MAX(VOID_DATE) AS VOID_DATE
		FROM PAYABLE_LINE APL 
		JOIN PAYABLE AP 
			ON APL.VOUCHER_ID = AP.VOUCHER_ID 
			AND PAY_STATUS IN ('X')
			AND APL.RECEIVER_ID = RL.RECEIVER_ID 
			AND APL.RECEIVER_LINE_NO = RL.LINE_NO
	) AS VOUCHER_VOID_DATE
	, CASE 
		WHEN EXISTS (SELECT 1 FROM PURCHASE_DIST PD
			WHERE RL.PURC_ORDER_ID = PD.PURC_ORDER_ID
			) THEN 'Y' 
		ELSE 'N' 
	END AS DIST_TABLE
FROM RECEIVER_LINE RL 
JOIN RECEIVER R 
	ON RL.RECEIVER_ID = R.ID 
--LEFT OUTER JOIN (PAYABLE_LINE APL 
--LEFT OUTER JOIN PAYABLE AP 
--ON APL.VOUCHER_ID = AP.VOUCHER_ID 
--)
--ON APL.RECEIVER_ID = RL.RECEIVER_ID 
--AND APL.RECEIVER_LINE_NO = RL.LINE_NO
--AND AP.PAY_STATUS IN ('P','H')


--WHERE RL.PURC_ORDER_ID = '149553'
--	AND CAST(LEFT(CAST(R.RECEIVED_DATE AS VARCHAR), 11) AS DATETIME) <= @ASOFSTART
)

SELECT * 
FROM CTEBASE CTE
LEFT OUTER JOIN #T1 T
ON CTE.RECEIVED_DATE >= '1/1/2019'
AND T.DATEVALUE >= CTE.RECEIVED_DATE
AND T.DATEVALUE <= ISNULL(CTE.VOUCHER_CREATE_DATE, GETDATE())
WHERE T.DATEVALUE IS NOT NULL
--AND PURC_ORDER_ID = '127283'

/*
--> DO I NEED TO TAKE THE MAX(CREATE_DATE)???

SELECT 'RECEIVER_LINE RL ' AS MSG01
	, RL.*
	, 'RECEIVER R ' AS MSG02
	, R.*
	, 'PAYABLE_LINE APL ' AS MSG03
	, APL.*
	, 'PAYABLE AP ' AS MSG04
	, AP.*
FROM RECEIVER_LINE RL 
JOIN RECEIVER R 
	ON RL.RECEIVER_ID = R.ID 
LEFT OUTER JOIN (PAYABLE_LINE APL 
LEFT OUTER JOIN PAYABLE AP 
ON APL.VOUCHER_ID = AP.VOUCHER_ID 
)
ON APL.RECEIVER_ID = RL.RECEIVER_ID 
AND APL.RECEIVER_LINE_NO = RL.LINE_NO
--AND AP.PAY_STATUS IN ('P','H')
WHERE RL.PURC_ORDER_ID = '141038'

SELECT * FROM PAYABLE WHERE VOUCHER_ID IN ('220773', '224302')
*/

