USE LIVE
GO

--> POS THAT HAVE BEEN RECEIVED BUT NOT VOUCHERED

DECLARE @ASOFSTART DATETIME
, @ASOFEND DATETIME = '2021-07-31'

SET @ASOFSTART = (SELECT BEGIN_DATE - 1 FROM ACCOUNT_PERIOD WHERE END_DATE = @ASOFEND)

IF OBJECT_ID('tempdb..#T1') IS NOT NULL DROP TABLE #T1

SET DATEFIRST 7; -- Set's sunday as first day of week, won't work otherwise

DECLARE @STARTDATE DATE = '01/01/2021'
, @ENDDATE DATETIME = '12/31/2022'
, @CURRENTDATE DATETIME

DECLARE @TABLEOFDATES TABLE(DATEVALUE DATETIME)

SET @CURRENTDATE = @STARTDATE

WHILE @CURRENTDATE <= @ENDDATE
	BEGIN
		INSERT INTO @TABLEOFDATES(DATEVALUE) VALUES (@CURRENTDATE)
		SET @CURRENTDATE = DATEADD(DAY, 1, @CURRENTDATE)
	END

SELECT * 
INTO #T1
FROM @TABLEOFDATES 
WHERE DATEPART(WEEKDAY, DATEVALUE) = 2


; WITH CTEBASE AS 
(SELECT RL.RECEIVER_ID
	, RL.LINE_NO AS RCV_LN
	, RL.PURC_ORDER_ID
	, RL.PURC_ORDER_LINE_NO AS PO_LN
	, R.RECEIVED_DATE
	, RL.RECEIVED_QTY
	, RL.SERV_TRANS_ID
	, RL.TRANSACTION_ID
	, RL.UNIT_PRICE
	, CASE 
		WHEN EXISTS (SELECT 1 FROM PAYABLE_LINE APL 
			JOIN PAYABLE AP 
				ON APL.VOUCHER_ID = AP.VOUCHER_ID 
--				AND AP.POSTING_DATE <= @ASOFSTART 
				AND PAY_STATUS IN ('P','H')
				AND RECEIVER_ID = RL.RECEIVER_ID 
				AND RECEIVER_LINE_NO = RL.LINE_NO
			) THEN 'Y' 
		ELSE 'N' 
	END AS VOUCHERED
	, CASE 
		WHEN RL.SERV_TRANS_ID = 0
			THEN (SELECT TOP 1 ACT_MATERIAL_COST + ACT_LABOR_COST + ACT_SERVICE_COST
				FROM PURC_MATL_DETAIL DTL 
				JOIN PURCHASE_DIST DIST 
					ON DTL.PURC_ORDER_ID = DIST.PURC_ORDER_ID 
					AND DTL.DIST_NO = DIST.DIST_NO 
--					AND DIST.POSTING_DATE <= @ASOFSTART
				WHERE TRANSACTION_ID = RL.TRANSACTION_ID
				ORDER BY DTL.DIST_NO DESC
				)
		ELSE (SELECT TOP 1 ACT_SERVICE_COST 
			FROM PURC_SERV_DETAIL DTL 
			JOIN PURCHASE_DIST DIST 
				ON DTL.PURC_ORDER_ID = DIST.PURC_ORDER_ID 
				AND DTL.DIST_NO = DIST.DIST_NO 
--				AND DIST.POSTING_DATE <=  @ASOFSTART
			WHERE TRANSACTION_ID = RL.SERV_TRANS_ID
			ORDER BY DTL.DIST_NO DESC
			)
	END AS ACCRUAL_AMT 
FROM RECEIVER_LINE RL 
JOIN RECEIVER R 
	ON RL.RECEIVER_ID = R.ID 
--	AND CAST(LEFT(CAST(R.RECEIVED_DATE AS VARCHAR), 11) AS DATETIME) <= @ASOFSTART
)
--SELECT * FROM CTEBASE

, CTEBASEEND AS 
(SELECT RL.RECEIVER_ID
	, RL.LINE_NO AS RCV_LN
	, RL.PURC_ORDER_ID
	, RL.PURC_ORDER_LINE_NO AS PO_LN
	, R.RECEIVED_DATE
	, RL.RECEIVED_QTY
	, RL.SERV_TRANS_ID
	, RL.TRANSACTION_ID
	, RL.UNIT_PRICE
	, CASE 
		WHEN EXISTS (SELECT 1 FROM PAYABLE_LINE APL 
			JOIN PAYABLE AP 
			ON APL.VOUCHER_ID = AP.VOUCHER_ID 
			AND AP.POSTING_DATE <= @ASOFEND 
			AND PAY_STATUS IN ('P','H')
			AND RECEIVER_ID = RL.RECEIVER_ID 
			AND RECEIVER_LINE_NO = RL.LINE_NO
			) THEN 'Y' 
		ELSE 'N' 
	END AS VOUCHERED
	, CASE 
	WHEN RL.SERV_TRANS_ID = 0
		THEN (SELECT TOP 1 ACT_MATERIAL_COST + ACT_LABOR_COST + ACT_SERVICE_COST
			FROM PURC_MATL_DETAIL DTL 
			JOIN PURCHASE_DIST DIST 
				ON DTL.PURC_ORDER_ID = DIST.PURC_ORDER_ID 
				AND DTL.DIST_NO = DIST.DIST_NO 
				AND DIST.POSTING_DATE <= @ASOFEND
			WHERE TRANSACTION_ID = RL.TRANSACTION_ID
			ORDER BY DTL.DIST_NO DESC
			)
	ELSE (SELECT TOP 1 ACT_SERVICE_COST 
		FROM PURC_SERV_DETAIL DTL 
		JOIN PURCHASE_DIST DIST 
			ON DTL.PURC_ORDER_ID = DIST.PURC_ORDER_ID 
			AND DTL.DIST_NO = DIST.DIST_NO 
			AND DIST.POSTING_DATE <=  @ASOFEND
		WHERE TRANSACTION_ID = RL.SERV_TRANS_ID
		ORDER BY DTL.DIST_NO DESC
		)
	END AS ACCRUAL_AMT 
FROM RECEIVER_LINE RL 
JOIN RECEIVER R 
	ON RL.RECEIVER_ID = R.ID 
	AND CAST(LEFT(CAST(R.RECEIVED_DATE AS VARCHAR), 11) AS DATETIME) <= @ASOFEND
)
--SELECT * FROM CTEBASEEND WHERE PURC_ORDER_ID = '147408'

, CTEDISTINCT AS 
(SELECT RECEIVER_ID
	, RCV_LN
	, PURC_ORDER_ID
	, PO_LN 
FROM CTEBASE 
--WHERE VOUCHERED = 'N'
UNION 
SELECT RECEIVER_ID
	, RCV_LN
	, PURC_ORDER_ID
	, PO_LN 
FROM CTEBASEEND
--WHERE VOUCHERED = 'N'
)

, CTETRIALBAL AS 
(SELECT D.PURC_ORDER_ID
	, D.PO_LN
	, D.RECEIVER_ID
	, D.RCV_LN
	, SUM(ISNULL(B.ACCRUAL_AMT,0)) AS BEGBAL
	, SUM(ISNULL(E.ACCRUAL_AMT,0)) AS ENDBAL
FROM CTEDISTINCT D 
LEFT JOIN CTEBASE B 
	ON D.RECEIVER_ID = B.RECEIVER_ID 
	AND D.RCV_LN = B.RCV_LN 
	AND D.PURC_ORDER_ID = B.PURC_ORDER_ID 
	AND D.PO_LN = B.PO_LN 
	AND B.VOUCHERED = 'N'
LEFT JOIN CTEBASEEND E 
	ON D.RECEIVER_ID = E.RECEIVER_ID 
	AND D.RCV_LN = E.RCV_LN 
	AND D.PURC_ORDER_ID = E.PURC_ORDER_ID 
	AND D.PO_LN = E.PO_LN 
	AND E.VOUCHERED = 'N'
GROUP BY D.PURC_ORDER_ID
	, D.PO_LN
	, D.RECEIVER_ID
	, D.RCV_LN 
) 

SELECT T1.DATEVALUE
	, X.*
FROM (SELECT T.PURC_ORDER_ID
	, T.PO_LN
	, T.RECEIVER_ID
--	, T.RCV_LN
	, T.BEGBAL
	, T.ENDBAL
	, R.RECEIVED_DATE
	, P.CREATE_DATE
	, PL.VOUCHER_ID
	, PL.LINE_NO AS VOUCHER_LINE
	, PO.VENDOR_ID
	, V.[NAME] AS VENDOR_NAME
FROM CTETRIALBAL T 
LEFT OUTER JOIN RECEIVER_LINE RL 
	ON RL.RECEIVER_ID = T.RECEIVER_ID
	AND RL.LINE_NO = T.RCV_LN
LEFT OUTER JOIN RECEIVER R 
	ON RL.RECEIVER_ID = R.ID 
LEFT OUTER JOIN PAYABLE_LINE PL
	ON PL.RECEIVER_ID = T.RECEIVER_ID
	AND PL.RECEIVER_LINE_NO = T.RCV_LN
LEFT OUTER JOIN PAYABLE P
	ON PL.VOUCHER_ID = P.VOUCHER_ID
LEFT OUTER JOIN PURCHASE_ORDER PO
	ON T.PURC_ORDER_ID = PO.ID
LEFT OUTER JOIN VENDOR V
	ON PO.VENDOR_ID = V.ID
WHERE T.RECEIVER_ID != '44875'
--	AND ABS(ENDBAL) > .01
) X
--LEFT OUTER JOIN #T1 T
INNER JOIN #T1 T1
ON T1.DATEVALUE >= X.RECEIVED_DATE
AND T1.DATEVALUE <= X.CREATE_DATE

--WHERE X.PURC_ORDER_ID = '123155'

ORDER BY X.PURC_ORDER_ID
	, X.PO_LN
	, T1.DATEVALUE


/*
SELECT *
FROM PURC_ORDER_LINE POL 
JOIN PURCHASE_ORDER PO 
	ON POL.PURC_ORDER_ID = PO.ID 
WHERE POL.PURC_ORDER_ID = '84573'
AND POL.LINE_NO = '5'


SELECT *
FROM RECEIVER_LINE RL 
JOIN RECEIVER R 
	ON RL.RECEIVER_ID = R.ID 
WHERE RL.PURC_ORDER_ID = '84573'
AND RL.PURC_ORDER_LINE_NO = '5'

SELECT *
FROM PAYABLE_LINE APL 
JOIN PAYABLE AP 
ON APL.VOUCHER_ID = AP.VOUCHER_ID 
--				AND AP.POSTING_DATE <= @ASOFSTART 
AND PAY_STATUS IN ('P','H')
--AND RECEIVER_ID = RL.RECEIVER_ID 
--AND RECEIVER_LINE_NO = RL.LINE_NO
WHERE APL.PURC_ORDER_ID = '84573'
AND APL.PURC_ORDER_LINE_NO = '5'

--> ACCRUAL_AMT 
SELECT * --ACT_MATERIAL_COST + ACT_LABOR_COST + ACT_SERVICE_COST
FROM PURC_MATL_DETAIL DTL 
JOIN PURCHASE_DIST DIST 
ON DTL.PURC_ORDER_ID = DIST.PURC_ORDER_ID 
AND DTL.DIST_NO = DIST.DIST_NO 
--					AND DIST.POSTING_DATE <= @ASOFSTART
--WHERE TRANSACTION_ID = RL.TRANSACTION_ID
WHERE DTL.PURC_ORDER_ID = '84573'
AND DTL.PURC_ORDER_LINE_NO = '5'

-------------------------------
SELECT * --ACT_MATERIAL_COST + ACT_LABOR_COST + ACT_SERVICE_COST
FROM PURC_MATL_DETAIL DTL 
WHERE DTL.PURC_ORDER_ID = '84573'
AND DTL.PURC_ORDER_LINE_NO = '5'

SELECT * --ACT_MATERIAL_COST + ACT_LABOR_COST + ACT_SERVICE_COST
FROM PURCHASE_DIST DIST 
WHERE DIST.PURC_ORDER_ID = '84573'
-------------------------------

--> ACCRUAL_AMT 
SELECT * --ACT_SERVICE_COST 
FROM PURC_SERV_DETAIL DTL 
JOIN PURCHASE_DIST DIST 
ON DTL.PURC_ORDER_ID = DIST.PURC_ORDER_ID 
AND DTL.DIST_NO = DIST.DIST_NO 
--				AND DIST.POSTING_DATE <=  @ASOFSTART
--WHERE TRANSACTION_ID = RL.SERV_TRANS_ID
WHERE DTL.PURC_ORDER_ID = '84573'
AND DTL.PURC_ORDER_LINE_NO = '5'

*/

-->>>>>> new start
--> POS THAT HAVE BEEN RECEIVED BUT NOT VOUCHERED

DECLARE @ASOFSTART DATETIME
, @ASOFEND DATETIME = '2021-07-31'

SET @ASOFSTART = (SELECT BEGIN_DATE - 1 FROM ACCOUNT_PERIOD WHERE END_DATE = @ASOFEND)

IF OBJECT_ID('tempdb..#T1') IS NOT NULL DROP TABLE #T1

SET DATEFIRST 7; -- Set's sunday as first day of week, won't work otherwise

; WITH CTEBASE AS 
(SELECT RL.RECEIVER_ID
	, RL.LINE_NO AS RCV_LN
	, RL.PURC_ORDER_ID
	, RL.PURC_ORDER_LINE_NO AS PO_LN
	, R.RECEIVED_DATE
	, RL.RECEIVED_QTY
	, RL.SERV_TRANS_ID
	, RL.TRANSACTION_ID
	, RL.UNIT_PRICE
--	, CASE 
--		WHEN EXISTS (SELECT 1 FROM PAYABLE_LINE APL 
--			JOIN PAYABLE AP 
--				ON APL.VOUCHER_ID = AP.VOUCHER_ID 
----				AND AP.POSTING_DATE <= @ASOFSTART 
--				AND PAY_STATUS IN ('P','H')
--				AND RECEIVER_ID = RL.RECEIVER_ID 
--				AND RECEIVER_LINE_NO = RL.LINE_NO
--			) THEN 'Y' 
--		ELSE 'N' 
--	END AS VOUCHERED
	, (SELECT MIN(CREATE_DATE) AS VOUCHER_DATE
		FROM PAYABLE_LINE APL 
		JOIN PAYABLE AP 
		ON APL.VOUCHER_ID = AP.VOUCHER_ID 
--				AND AP.POSTING_DATE <= @ASOFSTART 
		AND PAY_STATUS IN ('P','H')
		AND RECEIVER_ID = RL.RECEIVER_ID 
		AND RECEIVER_LINE_NO = RL.LINE_NO
	) AS VOUCHER_DATE
--	, CASE 
--		WHEN RL.SERV_TRANS_ID = 0
--			THEN (SELECT TOP 1 ACT_MATERIAL_COST + ACT_LABOR_COST + ACT_SERVICE_COST
--				FROM PURC_MATL_DETAIL DTL 
--				JOIN PURCHASE_DIST DIST 
--					ON DTL.PURC_ORDER_ID = DIST.PURC_ORDER_ID 
--					AND DTL.DIST_NO = DIST.DIST_NO 
----					AND DIST.POSTING_DATE <= @ASOFSTART
--				WHERE TRANSACTION_ID = RL.TRANSACTION_ID
--				ORDER BY DTL.DIST_NO DESC
--				)
--		ELSE (SELECT TOP 1 ACT_SERVICE_COST 
--			FROM PURC_SERV_DETAIL DTL 
--			JOIN PURCHASE_DIST DIST 
--				ON DTL.PURC_ORDER_ID = DIST.PURC_ORDER_ID 
--				AND DTL.DIST_NO = DIST.DIST_NO 
----				AND DIST.POSTING_DATE <=  @ASOFSTART
--			WHERE TRANSACTION_ID = RL.SERV_TRANS_ID
--			ORDER BY DTL.DIST_NO DESC
--			)
--	END AS ACCRUAL_AMT 
FROM RECEIVER_LINE RL 
JOIN RECEIVER R 
	ON RL.RECEIVER_ID = R.ID 
--	AND CAST(LEFT(CAST(R.RECEIVED_DATE AS VARCHAR), 11) AS DATETIME) <= @ASOFSTART
)
SELECT * FROM CTEBASE WHERE PURC_ORDER_ID = '84573'

