USE LIVE
GO

DECLARE @ASOFSTART DATETIME
, @ASOFEND DATETIME = '2021-07-31'

SET @ASOFSTART = (SELECT BEGIN_DATE - 1 FROM ACCOUNT_PERIOD WHERE END_DATE = @ASOFEND)

; WITH CTEBASE AS 
(SELECT RL.RECEIVER_ID
	, RL.LINE_NO AS RCV_LN
	, RL.PURC_ORDER_ID
	, RL.PURC_ORDER_LINE_NO AS PO_LN
	, R.RECEIVED_DATE
	, RL.RECEIVED_QTY
	, RL.SERV_TRANS_ID
	, RL.TRANSACTION_ID
	, RL.UNIT_PRICE
	, CASE 
		WHEN EXISTS (SELECT 1 FROM PAYABLE_LINE APL 
			JOIN PAYABLE AP 
				ON APL.VOUCHER_ID = AP.VOUCHER_ID 
				AND AP.POSTING_DATE <= @ASOFSTART 
				AND PAY_STATUS IN ('P','H')
				AND RECEIVER_ID = RL.RECEIVER_ID 
				AND RECEIVER_LINE_NO = RL.LINE_NO
			) THEN 'Y' 
		ELSE 'N' 
	END AS VOUCHERED
	, CASE 
		WHEN RL.SERV_TRANS_ID = 0
			THEN (SELECT TOP 1 ACT_MATERIAL_COST + ACT_LABOR_COST + ACT_SERVICE_COST
				FROM PURC_MATL_DETAIL DTL 
				JOIN PURCHASE_DIST DIST 
					ON DTL.PURC_ORDER_ID = DIST.PURC_ORDER_ID 
					AND DTL.DIST_NO = DIST.DIST_NO 
					AND DIST.POSTING_DATE <= @ASOFSTART
				WHERE TRANSACTION_ID = RL.TRANSACTION_ID
				ORDER BY DTL.DIST_NO DESC
				)
		ELSE (SELECT TOP 1 ACT_SERVICE_COST 
			FROM PURC_SERV_DETAIL DTL 
			JOIN PURCHASE_DIST DIST 
				ON DTL.PURC_ORDER_ID = DIST.PURC_ORDER_ID 
				AND DTL.DIST_NO = DIST.DIST_NO 
				AND DIST.POSTING_DATE <=  @ASOFSTART
			WHERE TRANSACTION_ID = RL.SERV_TRANS_ID
			ORDER BY DTL.DIST_NO DESC
			)
	END AS ACCRUAL_AMT 
FROM RECEIVER_LINE RL 
JOIN RECEIVER R 
	ON RL.RECEIVER_ID = R.ID 
	AND CAST(LEFT(CAST(R.RECEIVED_DATE AS VARCHAR), 11) AS DATETIME) <= @ASOFSTART
)
--SELECT * FROM CTEBASE

, CTEBASEEND AS 
(SELECT RL.RECEIVER_ID
	, RL.LINE_NO AS RCV_LN
	, RL.PURC_ORDER_ID
	, RL.PURC_ORDER_LINE_NO AS PO_LN
	, R.RECEIVED_DATE
	, RL.RECEIVED_QTY
	, RL.SERV_TRANS_ID
	, RL.TRANSACTION_ID
	, RL.UNIT_PRICE
	, CASE 
		WHEN EXISTS (SELECT 1 FROM PAYABLE_LINE APL 
			JOIN PAYABLE AP 
			ON APL.VOUCHER_ID = AP.VOUCHER_ID 
			AND AP.POSTING_DATE <= @ASOFEND 
			AND PAY_STATUS IN ('P','H')
			AND RECEIVER_ID = RL.RECEIVER_ID 
			AND RECEIVER_LINE_NO = RL.LINE_NO
			) THEN 'Y' 
		ELSE 'N' 
	END AS VOUCHERED
	, CASE 
	WHEN RL.SERV_TRANS_ID = 0
		THEN (SELECT TOP 1 ACT_MATERIAL_COST + ACT_LABOR_COST + ACT_SERVICE_COST
			FROM PURC_MATL_DETAIL DTL 
			JOIN PURCHASE_DIST DIST 
				ON DTL.PURC_ORDER_ID = DIST.PURC_ORDER_ID 
				AND DTL.DIST_NO = DIST.DIST_NO 
				AND DIST.POSTING_DATE <= @ASOFEND
			WHERE TRANSACTION_ID = RL.TRANSACTION_ID
			ORDER BY DTL.DIST_NO DESC
			)
	ELSE (SELECT TOP 1 ACT_SERVICE_COST 
		FROM PURC_SERV_DETAIL DTL 
		JOIN PURCHASE_DIST DIST 
			ON DTL.PURC_ORDER_ID = DIST.PURC_ORDER_ID 
			AND DTL.DIST_NO = DIST.DIST_NO 
			AND DIST.POSTING_DATE <=  @ASOFEND
		WHERE TRANSACTION_ID = RL.SERV_TRANS_ID
		ORDER BY DTL.DIST_NO DESC
		)
	END AS ACCRUAL_AMT 
FROM RECEIVER_LINE RL 
JOIN RECEIVER R 
	ON RL.RECEIVER_ID = R.ID 
	AND CAST(LEFT(CAST(R.RECEIVED_DATE AS VARCHAR), 11) AS DATETIME) <= @ASOFEND
)

, CTEDISTINCT AS 
(SELECT RECEIVER_ID
	, RCV_LN
	, PURC_ORDER_ID
	, PO_LN 
FROM CTEBASE 
WHERE VOUCHERED = 'N'
UNION ALL 
SELECT RECEIVER_ID
	, RCV_LN
	, PURC_ORDER_ID
	, PO_LN 
FROM CTEBASEEND
WHERE VOUCHERED = 'N'
)

, CTETRIALBAL AS 
(SELECT D.PURC_ORDER_ID
	, D.RECEIVER_ID
	, D.RCV_LN
	, SUM(ISNULL(B.ACCRUAL_AMT,0)) AS BEGBAL
	, SUM(ISNULL(E.ACCRUAL_AMT,0)) AS ENDBAL
FROM CTEDISTINCT D 
LEFT JOIN CTEBASE B 
	ON D.RECEIVER_ID = B.RECEIVER_ID 
	AND D.RCV_LN = B.RCV_LN 
	AND D.PURC_ORDER_ID = B.PURC_ORDER_ID 
	AND D.PO_LN = B.PO_LN 
	AND B.VOUCHERED = 'N'
LEFT JOIN CTEBASEEND E 
	ON D.RECEIVER_ID = E.RECEIVER_ID 
	AND D.RCV_LN = E.RCV_LN 
	AND D.PURC_ORDER_ID = E.PURC_ORDER_ID 
	AND D.PO_LN = E.PO_LN 
	AND E.VOUCHERED = 'N'
GROUP BY D.PURC_ORDER_ID
	, D.RECEIVER_ID
	, D.RCV_LN 
) 

SELECT T.PURC_ORDER_ID
	, T.RECEIVER_ID
	, T.RCV_LN
	, T.BEGBAL
	, T.ENDBAL
	, R.RECEIVED_DATE
FROM CTETRIALBAL T 
LEFT OUTER JOIN RECEIVER_LINE RL 
	ON RL.RECEIVER_ID = T.RECEIVER_ID
	AND RL.LINE_NO = T.RCV_LN
LEFT OUTER JOIN RECEIVER R 
	ON RL.RECEIVER_ID = R.ID 
WHERE ABS(ENDBAL) > .01
	AND T.RECEIVER_ID != '44875'
ORDER BY PURC_ORDER_ID
