USE LIVE
GO

SELECT BUYER 
, YEAR(ORDER_DATE) AS ORDER_YR
, MONTH(ORDER_DATE) AS ORDER_MONTH
, COUNT(*)
FROM PURCHASE_ORDER
WHERE STATUS != 'X'
GROUP BY BUYER 
, YEAR(ORDER_DATE) 
, MONTH(ORDER_DATE)

SELECT USER_ID
, YEAR(RECEIVED_DATE) AS RECEIVED_YR
, MONTH(RECEIVED_DATE) AS RECEIVED_MONTH
, COUNT(*)
FROM RECEIVER
GROUP BY USER_ID
, YEAR(RECEIVED_DATE)
, MONTH(RECEIVED_DATE)