USE CRUNCH0122
GO

SELECT POSTING_STATUS, COUNT(*)
FROM WIP_ISSUE_DIST
--WHERE POSTING_DATE >= '1/1/2022'
GROUP BY POSTING_STATUS

SELECT *
FROM WIP_ISSUE_DIST
WHERE POSTING_DATE >= '1/1/2022'
ORDER BY POSTING_DATE DESC

BEGIN TRANSACTION;
UPDATE WIP_ISSUE_DIST
SET POSTING_STATUS = 'U'
WHERE POSTING_DATE >= '1/1/2022'
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

SELECT *
FROM PURCHASE_DIST
WHERE POSTING_DATE >= '1/1/2022'
ORDER BY POSTING_DATE DESC

BEGIN TRANSACTION;
UPDATE PURCHASE_DIST
SET POSTING_STATUS = 'U'
WHERE POSTING_DATE >= '1/1/2022'
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
