use datawarehouse
go

SELECT R.CUSTOMER_ID
	, R.INVOICE_DATE
	, R.INVOICE_ID
	, R.STATUS
	, RL.AMOUNT
	, RL.GL_ACCOUNT_ID
FROM   Datamart.dbo.RECEIVABLE R 
LEFT OUTER JOIN Datamart.dbo.RECEIVABLE_LINE RL
ON R.INVOICE_ID = RL.INVOICE_ID
WHERE RL.GL_ACCOUNT_ID in ('4230', '4310')
	AND RL.AMOUNT <> 0 
	AND R.STATUS = 'A' 
	AND (R.INVOICE_DATE >= '1/1/2018'
		AND R.INVOICE_DATE < '12/21/2018')
	AND R.CUSTOMER_ID = 'BOE609'
ORDER BY R.INVOICE_DATE
	, R.INVOICE_ID