-- VISUAL ENTERPRISE > PURCHASING REPORTS > PURCHASE REQUEST STATUS

SELECT CASE
             WHEN PR.[STATUS] = 'C' AND PRL.LINE_STATUS != 'C' THEN 'PRL ISSUE'
             WHEN PR.[STATUS] = 'X' AND PRL.LINE_STATUS != 'X' THEN 'PRL NOT CANCELLED'
             WHEN PR.[STATUS] = 'O' AND PO.[STATUS] IS NULL THEN 'OPEN NO PO'
             WHEN PR.[STATUS] != 'X' AND PO.[STATUS] = 'X' THEN 'PO CANCELLED PR NOT'
             WHEN PR.[STATUS] = 'I' AND PO.[STATUS] IS NULL THEN 'IN PROGRESS NO PO'
             WHEN PR.[STATUS] = 'T' AND PO.[STATUS] IS NULL THEN 'DRAFT PR'
             WHEN PR.[STATUS] != 'C' AND (POL.LINE_STATUS = 'C' OR PO.[STATUS] = 'C') THEN 'PO CLOSED PR NOT'
             WHEN PO.[STATUS] != 'C' AND (PRL.LINE_STATUS = 'C' OR PR.[STATUS] = 'C') THEN 'PR CLOSED PO NOT'
             WHEN PR.REQUISITION_DATE < '9/1/2020' OR PR.DESIRED_RECV_DATE < '9/1/2020' THEN 'OLD PR'
             ELSE ''
END AS ISSUES
	, PR.ID AS REQ_ID 
	, PRL.LINE_NO AS REQ_LINE 
	, PRL.LINE_STATUS AS PRL_STATUS
	, PR.[STATUS] AS PR_STATUS
	, POL.LINE_STATUS AS POL_STATUS
	, PO.[STATUS] AS PO_STATUS
	, POL.PURC_ORDER_ID 
	, POL.LINE_NO AS ORDER_LINE 
	, PRL.VENDOR_ID 
	, ISNULL(POL.VENDOR_PART_ID, PRL.VENDOR_PART_ID) AS VENDOR_PART_ID 
	, ISNULL(POL.PART_ID, PRL.PART_ID) AS PART_ID 
	, P.[DESCRIPTION] 
	, PR.REQUISITION_DATE 
	, PR.DESIRED_RECV_DATE 
	, PR.BUYER 
	, PR.ASSIGNED_TO 
	, PR.PREPARER 
	, COALESCE(EE2.FIRST_NAME + ' ' + EE2.LAST_NAME, EE1.FIRST_NAME + ' ' + EE1.LAST_NAME, PR.REQUESTOR) AS REQNAME 
	, PRL.ORDER_QTY 
	, PRL.PURCHASE_UM 
	, PRL.UNIT_PRICE 
	, PRL.TOTAL_AMT_ORDERED AS LINE_TOTAL 
	, PR.TOTAL_AMT_ORDERED AS REQ_TOTAL 
FROM PURC_REQUISITION PR 
INNER JOIN PURC_REQ_LINE PRL 
	ON PR.ID = PRL.PURC_REQ_ID 
LEFT OUTER JOIN PURC_ORDER_REQ POR 
	ON PRL.PURC_REQ_ID = POR.PURC_REQ_ID 
	AND PRL.LINE_NO = POR.PURC_REQ_LINE_NO 
LEFT OUTER JOIN PURC_ORDER_LINE POL 
	ON POL.PURC_ORDER_ID = POR.PURC_ORD_ID 
	AND POL.LINE_NO = POR.PURC_ORD_LINE_NO 
LEFT OUTER JOIN PURCHASE_ORDER PO
	ON PO.ID = POL.PURC_ORDER_ID
LEFT OUTER JOIN PART P 
	ON PRL.PART_ID = P.ID 
LEFT OUTER JOIN EMPLOYEE EE1 
	ON EE1.ID = PR.REQUESTOR 
LEFT OUTER JOIN EMPLOYEE EE2 
	ON EE2.[USER_ID] = PR.REQUESTOR 
WHERE CASE
             WHEN PO.[STATUS] = 'C' AND PR.[STATUS] = 'C' AND PRL.LINE_STATUS = 'C' THEN 'CLOSED'
             WHEN PO.[STATUS] = 'R' AND PR.[STATUS] = 'O' AND PRL.LINE_STATUS = 'O' THEN 'IP OPEN'
             WHEN PR.[STATUS] = 'X' AND PRL.LINE_STATUS = 'X' THEN 'PR CANCELLED'
	ELSE ''
	END = ''
/*
WHERE COALESCE(EE2.FIRST_NAME + ' ' + EE2.LAST_NAME, EE1.FIRST_NAME + ' ' + EE1.LAST_NAME, PR.REQUESTOR) IN (@REQUESTOR) 
	AND PRL.LINE_STATUS IN (@STATUS)


SELECT COALESCE(EE2.FIRST_NAME + ' ' + EE2.LAST_NAME, EE1.FIRST_NAME + ' ' + EE1.LAST_NAME, PR.REQUESTOR) AS REQUESTOR
FROM PURC_REQUISITION PR 
LEFT OUTER JOIN EMPLOYEE EE1 
	ON EE1.ID = PR.REQUESTOR 
LEFT OUTER JOIN EMPLOYEE EE2 
	ON EE2.[USER_ID] = PR.REQUESTOR 
GROUP BY COALESCE(EE2.FIRST_NAME + ' ' + EE2.LAST_NAME, EE1.FIRST_NAME + ' ' + EE1.LAST_NAME, PR.REQUESTOR)
ORDER BY COALESCE(EE2.FIRST_NAME + ' ' + EE2.LAST_NAME, EE1.FIRST_NAME + ' ' + EE1.LAST_NAME, PR.REQUESTOR)

*/