USE LIVE
GO

SELECT PR.ID AS REQ_ID
	, PRL.LINE_NO AS REQ_LINE
	, PRL.LINE_STATUS
	, POL.PURC_ORDER_ID
	, POL.LINE_NO AS ORDER_LINE
	, PRL.VENDOR_ID
	, ISNULL(POL.VENDOR_PART_ID, PRL.VENDOR_PART_ID) AS VENDOR_PART_ID
	, ISNULL(POL.PART_ID, PRL.PART_ID) AS PART_ID
	, P.[DESCRIPTION]
	, PR.REQUISITION_DATE
	, PR.DESIRED_RECV_DATE
	, PR.BUYER
	, PR.ASSIGNED_TO
	, PR.PREPARER
	, ISNULL(EE.FIRST_NAME + ' ' + EE.LAST_NAME, PR.REQUESTOR) AS REQNAME
	, PRL.ORDER_QTY
	, PRL.PURCHASE_UM
	, PRL.UNIT_PRICE
	, PRL.TOTAL_AMT_ORDERED AS LINE_TOTAL
	, PR.TOTAL_AMT_ORDERED AS REQ_TOTAL
FROM PURC_REQUISITION PR
	INNER JOIN PURC_REQ_LINE PRL
		ON PR.ID = PRL.PURC_REQ_ID
	INNER JOIN PURC_ORDER_REQ POR
		ON PRL.PURC_REQ_ID = POR.PURC_REQ_ID
		AND PRL.LINE_NO = POR.PURC_REQ_LINE_NO
	INNER JOIN PURC_ORDER_LINE POL
		ON POL.PURC_ORDER_ID = POR.PURC_ORD_ID
		AND POL.LINE_NO = POR.PURC_ORD_LINE_NO
	LEFT OUTER JOIN PART P
		ON PRL.PART_ID = P.ID
	LEFT OUTER JOIN EMPLOYEE EE
		ON EE.ID = PR.REQUESTOR
--WHERE REQUESTOR = @REQUESTOR
--	AND PRL.LINE_STATUS IN (@STATUS)