USE CRUNCH0221
GO

DECLARE @ORDER_ID NVARCHAR(10) = '144717'

/**********************************************************************************************
Date     Modified By	Change Description
-------- -------------  ------------------------------------------------------------
20200303 VME			Query changes;changed CASE statement for Document_ID was not picking up .12 
						and only one document was being filtered with the original case statement
						Report Changes: removed signature lines from the report itself 
20200305 VME			Query Changes added Case statement for Vendor_City_State_zip to pick up country when not US. added addr_2
20200708 WT				added logic for Limited vendors and limited parts. Flag if vendor is limited and part is not limited.
20200709 WT				Added email address of buyer per DI-46
20210325 tt				CLEANED OUT GARBAGE AND NEEDLESS PROCESSING
						updated documents to list all associated with operation and linked documents for
						the associated SUB_ID
**********************************************************************************************/

; WITH CTE_DOCS AS
--> OPERATIONAL DOCS
(SELECT 'OPS' AS SRC 
	, DSL.SUPPLY_PART_ID AS PART_ID
	, DRW.WORKORDER_BASE_ID
	, DRW.WORKORDER_LOT_ID 
	, DRW.WORKORDER_SPLIT_ID
	, DRW.WORKORDER_SUB_ID
	, DRW.WORKORDER_TYPE
	, DRW.SEQUENCE_NO
	, (SELECT D.ID + CASE
			WHEN D.REVISION_ID IS NULL THEN ' / REV: '
			ELSE ' / REV: ' + D.REVISION_ID
		END + CASE
			WHEN U1.STRING_VAL IS NULL THEN ' / ADCN: '
			ELSE ' / ADCN: ' + U1.STRING_VAL
		END + CHAR(10)
	) AS DOCUMENT_ID
FROM DOCUMENT_REF_WO DRW
INNER JOIN DOCUMENT D
	ON DRW.DOCUMENT_ID = D.ID
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON DRW.WORKORDER_BASE_ID = DSL.DEMAND_BASE_ID
	AND DRW.WORKORDER_LOT_ID = DSL.DEMAND_LOT_ID
	AND DRW.WORKORDER_SPLIT_ID = DSL.DEMAND_SPLIT_ID
	AND DRW.WORKORDER_SUB_ID = DSL.DEMAND_SUB_ID
	AND DRW.SEQUENCE_NO = DSL.DEMAND_SEQ_NO
LEFT JOIN USER_DEF_FIELDS U1  --> ADCN
	ON D.ID = U1.DOCUMENT_ID
	AND U1.PROGRAM_ID = 'VMDOCMNT'
	AND U1.ID = 'UDF-0000032'
WHERE DSL.SUPPLY_BASE_ID = @ORDER_ID
UNION
--> HEADER CARD DOCS
SELECT 'HEADER' AS SRC 
	, DSL.SUPPLY_PART_ID AS PART_ID
	, DRW.WORKORDER_BASE_ID
	, DRW.WORKORDER_LOT_ID 
	, DRW.WORKORDER_SPLIT_ID
	, DRW.WORKORDER_SUB_ID
	, DRW.WORKORDER_TYPE
	, DRW.SEQUENCE_NO
	, (SELECT D.ID + CASE
			WHEN D.REVISION_ID IS NULL THEN ' / REV: '
			ELSE ' / REV: ' + D.REVISION_ID
		END + CASE
			WHEN U1.STRING_VAL IS NULL THEN ' / ADCN: '
			ELSE ' / ADCN: ' + U1.STRING_VAL
		END + CHAR(10)
	) AS DOCUMENT_ID
FROM DOCUMENT_REF_WO DRW
INNER JOIN DOCUMENT D
	ON DRW.DOCUMENT_ID = D.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL
	ON DRW.WORKORDER_BASE_ID = DSL.DEMAND_BASE_ID
	AND DRW.WORKORDER_LOT_ID = DSL.DEMAND_LOT_ID
	AND DRW.WORKORDER_SPLIT_ID = DSL.DEMAND_SPLIT_ID
	AND DRW.WORKORDER_SUB_ID = DSL.DEMAND_SUB_ID
	AND DRW.SEQUENCE_NO = '0'
LEFT JOIN USER_DEF_FIELDS U1  --> ADCN
	ON D.ID = U1.DOCUMENT_ID
	AND U1.PROGRAM_ID = 'VMDOCMNT'
	AND U1.ID = 'UDF-0000032'
WHERE DSL.SUPPLY_BASE_ID = @ORDER_ID
UNION 
--> MASTERS DOCS
SELECT 'MASTERS' AS SRC 
	, DRW.WORKORDER_BASE_ID AS PART_ID
	, DRW.WORKORDER_BASE_ID
	, DRW.WORKORDER_LOT_ID 
	, DRW.WORKORDER_SPLIT_ID
	, DRW.WORKORDER_SUB_ID
	, DRW.WORKORDER_TYPE
	, DRW.SEQUENCE_NO
	, (SELECT D.ID + CASE
			WHEN D.REVISION_ID IS NULL THEN ' / REV: '
			ELSE ' / REV: ' + D.REVISION_ID
		END + CASE
			WHEN U1.STRING_VAL IS NULL THEN ' / ADCN: '
			ELSE ' / ADCN: ' + U1.STRING_VAL
		END + CHAR(10)
	) AS DOCUMENT_ID
FROM DOCUMENT_REF_WO DRW
INNER JOIN DOCUMENT D
ON DRW.DOCUMENT_ID = D.ID
INNER JOIN DEMAND_SUPPLY_LINK DSL
	ON DRW.WORKORDER_BASE_ID = DSL.SUPPLY_PART_ID
	AND DRW.WORKORDER_TYPE = 'M'
LEFT JOIN USER_DEF_FIELDS U1  --> ADCN
	ON D.ID = U1.DOCUMENT_ID
	AND U1.PROGRAM_ID = 'VMDOCMNT'
	AND U1.ID = 'UDF-0000032'
WHERE DSL.SUPPLY_BASE_ID = @ORDER_ID
)

SELECT PO.ID AS ORDER_ID
	, POL.LINE_NO
	, POL.PART_ID
	, P.[DESCRIPTION] AS PART_DESCRIPTION
	, POL.VENDOR_PART_ID
	, PO.VENDOR_ID
	, PO.CONTACT_PHONE AS VENDOR_PHONE
	, PO.CONTACT_FAX AS VENDOR_FAX
	, PO.ORDER_DATE
	, PO.DESIRED_RECV_DATE AS PO_DESIRED_RECV_DATE
	, PO.BUYER
	, PO.SHIP_VIA
	, PO.FREE_ON_BOARD
	, PO.SHIPTO_ID
	, DBO.SFNWONUMFORMAT(DSL.DEMAND_BASE_ID, DSL.DEMAND_LOT_ID, DSL.DEMAND_SPLIT_ID, DSL.DEMAND_SUB_ID) AS WORKORDER
	, DSL.DEMAND_BASE_ID
	, DSL.DEMAND_LOT_ID
	, DSL.DEMAND_SUB_ID
	, DSL.DEMAND_SEQ_NO
	, V.[NAME] AS VENDOR_NAME
	, V.ADDR_1 AS VENDOR_ADDR_1
	, V.ADDR_2 AS VENDOR_ADDR_2
	, V.ADDR_3 AS VENDOR_ADDR_3
	, V.CITY AS VENDOR_CITY
	, V.[STATE] AS VENDOR_STATE
	, V.ZIPCODE AS VENDOR_ZIPCODE
	, V.COUNTRY AS VENDOR_COUNTRY
	, CASE 
		WHEN V.COUNTRY IN ('US', 'USA', 'UNITED STATES') THEN V.CITY + ' ,' + V.[STATE] + '  '+ V.ZIPCODE
		ELSE V.ADDR_3 + ' ' + V.COUNTRY + ' ' + V.ZIPCODE
	END AS Vendor_City_State_Zip
	, CASE
		WHEN V.ACTIVE_FLAG = 'Y' AND ISNULL(V.USER_1, '') = '' AND ISNULL(V.USER_2, '') = '' THEN NULL
		WHEN V.USER_1 = 'Y' AND ISNULL(V.USER_2, '') != '' THEN 'Approval Status: ' + V.USER_2
		ELSE 'Not Approved Vendor'
	END AS SUPPLIER_APPROVAL
	, CASE
		WHEN V.ACTIVE_FLAG = 'Y' AND ISNULL(V.USER_1, '') = '' AND ISNULL(V.USER_2, '') = '' THEN NULL
		WHEN V.USER_1 = 'Y' AND ISNULL(V.USER_4, '') != '' THEN 'ITAR Expiration: ' + V.USER_4
		ELSE 'Not ITAR Approved'
	END AS ITAR_APPROVAL
	, CASE
		WHEN V.ACTIVE_FLAG = 'Y' AND ISNULL(V.USER_1, '') = '' AND ISNULL(V.USER_2, '') = '' THEN NULL
		WHEN V.USER_1 = 'Y' AND ISNULL(V.USER_5, '') != '' THEN 'DPD Expiration: ' + V.USER_5
		ELSE 'Not DPD Approved'
	END AS DPD_APPROVAL
	, CASE
		WHEN PO.VENDOR_ID = 'TMXDIV'
			THEN 'The INCOTERMS™ 2000 for all orders from Buyer will be Free on Board (FOB) if by ocean and Delivery Duty Unpaid (DDU); otherwise, Boeing will pay for freight per Boeing''s standard routing instructions.  When Buyer''s order requests delivery outside the United States of America, the Import of Record will be the Buyer placing the order.  Title and risk of loss shall pass at place of shipment (i.e. for orders shipped directly from a mill, title and risk of loss shall pass when Boeing, or it''s designee, assume control of the Material; for orders shipped from Boeing, or Boeing''s service provider, title and risk of loss shall pass at Boeing, or Boeing''s service provider''s, shipping dock and Buyer will maintain adequate insurance to cover shipments at the time of risk of loss of transfer to Buyer.)'
		ELSE 'invisible'
	END AS TMXMESSAGE
	, STA.[NAME] AS SHIPTO_NAME
	, STA.ADDR_1 AS SHIPTO_ADDR_1
	, STA.ADDR_2 AS SHIPTO_ADDR_2
	, STA.ADDR_3 AS SHIPTO_ADDR_3
	, STA.CITY AS SHIPTO_CITY
	, STA.[STATE] AS SHIPTO_STATE
	, STA.ZIPCODE AS SHIPTO_ZIPCODE
	, STA.COUNTRY AS SHIPTO_COUNTRY
	, CASE WHEN ISNULL(PrePaidCC.BOOL_VAL,0) = 1 THEN 'Prepaid via CC' ELSE T.[DESCRIPTION] END AS TERMS
	, CASE
		WHEN POL.VENDOR_PART_ID LIKE '%EXP%' THEN 'EXPEDITE'
		ELSE 'invisible'
	END AS EXPEDITE
	, POL.SERVICE_ID
	, ISNULL(POL.SERVICE_ID, 'invisible') AS QUALITY_SIGNATURE
	, POL.USER_ORDER_QTY
	, POL.PURCHASE_UM
	, POL.UNIT_PRICE 
	, POL.GL_EXPENSE_ACCT_ID
	, CASE
		WHEN POL.DESIRED_RECV_DATE IS NULL THEN PO.DESIRED_RECV_DATE
		ELSE POL.DESIRED_RECV_DATE
	END AS POL_DESIRED_RECV_DATE
	, POL.TOTAL_AMT_ORDERED
	, PO.TOTAL_AMT_ORDERED PO_TOTAL
	, POL.MFG_NAME
	, POL.MFG_PART_ID
	, POL.USER_1 AS POL_USER_1
	, CASE
		WHEN POL.USER_2 = 'Y' THEN CASE
				WHEN POL.TOTAL_AMT_ORDERED IS NULL THEN 0
				ELSE POL.TOTAL_AMT_ORDERED * .1
			END
		ELSE 0
	END AS POL_TAX
	, POL.USER_2 AS POL_USER_2
	, CAST(CAST(POB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS PO_LONG_DESCRIPTION  		 
	, CAST(CAST(PLB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS POL_LONG_DESCRIPTION
	, CAST(CAST(PAB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS PAB_LONG_DESCRIPTION
	, CASE
		WHEN V.USER_2 = 'Disapproved' THEN 'Check Vendor ASL information'
		WHEN V.ACTIVE_FLAG = 'Y' AND V.USER_1 = 'Y' AND V.USER_2 = 'Approved' AND ISNULL(CAST(V.USER_3 AS DATE), GETDATE() + 1) <= GETDATE()
			THEN 'Check Vendor ASL information'
		WHEN V.ACTIVE_FLAG = 'Y' AND V.USER_1 = 'Y' AND V.USER_2 = 'Approved' AND ISNULL(CAST(V.USER_4 AS DATE), GETDATE() + 1) <= GETDATE()
			THEN 'Check Vendor ASL information'
		WHEN V.ACTIVE_FLAG = 'Y' AND V.USER_1 = 'Y' AND V.USER_2 = 'Approved' AND ISNULL(CAST(V.USER_5 AS DATE), GETDATE() + 1) <= GETDATE()
			THEN 'Check Vendor ASL information'
		WHEN V.USER_2 = 'Pending' THEN 'Print PO'
		ELSE 'Print PO'
	END AS PRINTMESSAGE
	, UDF.STRING_VAL AS IS_ITAR_PART
	, CASE 
		WHEN UDF2.STRING_VAL = 'NONE' THEN NULL
		ELSE UDF2.STRING_VAL 
	END AS CONTROLLED
	, UDF3.STRING_VAL AS CERT_REQ
	, UDF4.STRING_VAL AS USED_ON
	, CASE 
		WHEN DR.DOCUMENT_ID = '3CXPhone for Windows.lnk' THEN '3CXPhone for Windows'
		ELSE DR.DOCUMENT_ID
	END AS DOCUMENT_ID
	, D.REVISION_ID
	, EE.EMAIL_ADDR BUYER_EMAIL
	, HasPrtLimited = ISNULL(HasPrtLimited.Bool_Val,0) 
	, HasVndLimited = ISNULL(HasVndLimited.Bool_Val,0)
	, IsFlaggedLimited = IIF(ISNULL(HasVndLimited.Bool_Val,0) = 1 and ISNULL(HasPrtLimited.Bool_Val, 0) = 0, 1, 0) 
	, STUFF((SELECT CHAR(032) + T.DOCUMENT_ID
		FROM (SELECT PART_ID, DOCUMENT_ID FROM CTE_DOCS GROUP BY PART_ID, DOCUMENT_ID
		) T
	WHERE T.PART_ID = POL.PART_ID
	FOR XML PATH('')), 1, 1, '') AS DOCUMENT
FROM PURCHASE_ORDER PO
LEFT OUTER JOIN PURC_ORDER_LINE POL
	ON PO.ID = POL.PURC_ORDER_ID
LEFT OUTER JOIN PART P
	ON POL.PART_ID = P.ID
LEFT OUTER JOIN EMPLOYEE EE
	ON PO.BUYER = EE.[USER_ID]
LEFT OUTER JOIN VENDOR V
	ON PO.VENDOR_ID = V.ID
LEFT OUTER JOIN TERMS T
	ON T.ID = V.DEF_TERMS_ID
LEFT OUTER JOIN SHIPTO_ADDRESS STA
	ON STA.ADDR_NO = PO.SHIPTO_ADDR_NO
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON POL.PURC_ORDER_ID = DSL.SUPPLY_BASE_ID
	AND POL.LINE_NO = DSL.SUPPLY_SEQ_NO
	AND DSL.SUPPLY_TYPE = 'PO'
	AND DSL.DEMAND_TYPE = 'OP'
LEFT OUTER JOIN DOCUMENT_REFERENCE DR
	ON DR.ID = POL.PART_ID
LEFT OUTER JOIN DOCUMENT D
	ON D.ID = DR.DOCUMENT_ID
	AND DR.SOURCE_TYPE = 'P'
	AND D.SITE_ID = 'SK01'
--> ITAR INFO
LEFT OUTER JOIN USER_DEF_FIELDS AS UDF
	ON UDF.DOCUMENT_ID = POL.PART_ID
	AND UDF.PROGRAM_ID = 'VMPRTMNT'
	AND UDF.ID = 'UDF-0000040'
	AND BOOL_VAL = 1
--> CONTROLLED INFO
LEFT OUTER JOIN USER_DEF_FIELDS AS UDF2
	ON UDF2.DOCUMENT_ID = POL.PART_ID
	AND UDF2.PROGRAM_ID = 'VMPRTMNT'
	AND UDF2.ID = 'UDF-0000082'
--> CERT INFO
LEFT OUTER JOIN USER_DEF_FIELDS AS UDF3
	ON UDF3.DOCUMENT_ID = POL.PART_ID
	AND UDF3.PROGRAM_ID = 'VMPRTMNT'
	AND UDF3.ID = 'UDF-0000084'
--> USED ON INFO
LEFT OUTER JOIN USER_DEF_FIELDS AS UDF4
	ON UDF4.DOCUMENT_ID = POL.PART_ID
	AND UDF4.PROGRAM_ID = 'VMPRTMNT'
	AND UDF4.ID = 'UDF-0000085'
--> limited Scope; VMPRTMNT; HasPrtLimited
LEFT OUTER JOIN dbo.USER_DEF_FIELDS HasPrtLimited (nolock)
	ON HasPrtLimited.Document_ID = POL.PART_ID
	AND HasPrtLimited.program_id = 'VMPRTMNT'
	AND HasPrtLimited.DOCUMENT_ID is NOT null
	AND ISNULL(HasPrtLimited.BOOL_VAL, 0) = 1
	AND HasPrtLimited.ID = ('UDF-0000091') 
--> limited Scope; VMVNDMNT; HasVndLimited
LEFT OUTER JOIN [dbo].[USER_DEF_FIELDS] HasVndLimited (nolock)
	ON HasVndLimited.Document_ID = PO.VENDOR_ID
	AND HasVndLimited.program_id = 'VMVNDMNT'
	AND HasVndLimited.DOCUMENT_ID is NOT null
	AND HasVndLimited.ID ='UDF-0000090'  
	AND HasVndLimited.BOOL_VAL = 1
--> limited Scope; VMPURENT; PrePaidCC
LEFT OUTER JOIN [dbo].[USER_DEF_FIELDS] PrePaidCC (nolock)
	ON PrePaidCC.Document_ID = PO.ID
	AND PrePaidCC.program_id = 'VMPURENT'
	AND PrePaidCC.DOCUMENT_ID is NOT null
	AND PrePaidCC.ID ='UDF-0000100'  
LEFT OUTER JOIN PURC_ORDER_BINARY POB
	ON PO.ID = POB.PURC_ORDER_ID
	AND POB.[TYPE] = 'D'
LEFT OUTER JOIN PURC_LINE_BINARY PLB
	ON POL.PURC_ORDER_ID = PLB.PURC_ORDER_ID
	AND POL.LINE_NO = PLB.PURC_ORDER_LINE_NO
	AND PLB.[TYPE] = 'D'
LEFT OUTER JOIN PART_BINARY PAB
	ON POL.PART_ID = PAB.PART_ID
	AND PAB.[TYPE] = 'D'
WHERE PO.ID = @ORDER_ID;