USE DATAWAREHOUSE
GO

--> VISUAL ENTERPRISE > SHIPPING REPORTS > PURCH_ORDERS_TO_REQS DATASET
DECLARE @StartDate DATE = '1/1/'+CAST(YEAR(GETDATE())-1 AS NVARCHAR(4)); 

SELECT POL.PURC_ORDER_ID
	, POL.LINE_NO AS POL_LINE_NO
	, POL.PART_ID AS PO_PART_ID
	, POL.VENDOR_PART_ID AS POL_VENDOR_PART_ID
	, POL.SERVICE_ID AS POL_SERVICE_ID
	, POL.ORDER_QTY AS POL_ORDER_QTY
	, POL.PURCHASE_UM AS POL_PURCH_UM
	, POL.UNIT_PRICE AS POL_UNIT_PRICE
	, POL.GL_EXPENSE_ACCT_ID AS POL_GL_EXP_ACCT_ID
	, POL.PRODUCT_CODE AS POL_PROD_CODE
	, POL.COMMODITY_CODE AS POL_COMM_CODE
	, POL.DESIRED_RECV_DATE AS POL_DESIRED_RECV_DATE
	, POL.LINE_STATUS AS POL_STATUS
	, POL.TOTAL_RECEIVED_QTY AS POL_TOTAL_RECVD_QTY
	, POL.TOTAL_AMT_RECVD AS POL_TOTAL_AMT_RECVD
	, POL.TOTAL_AMT_ORDERED AS POL_TOTAL_AMT_ORDERED
	, POL.MINIMUM_CHARGE AS POL_MINIMUM_CHARGE
	, POL.USER_1 AS POL_USER_1
	, POL.USER_2 AS POL_USER_2
	, POL.USER_9 AS POL_USER_9
	, POL.ENTERED_BY AS POL_ENTERED_BY
	, PO.VENDOR_ID AS PO_VENDOR_ID
	, PO.ORDER_DATE AS POL_ORDER_DATE
	, PO.DESIRED_RECV_DATE AS PO_DESIRED_RECV_DATE
	, PO.BUYER AS PO_BUYER
	, PO.[STATUS] AS PO_STATUS
	, PO.TOTAL_AMT_ORDERED AS PO_TOTAL_AMT_ORDERED
	, PO.TOTAL_AMT_RECVD AS PO_TOTAL_AMT_RECVD
	, PO.CREATE_DATE AS PO_CREATE_DATE
	, PO.CONTACT_ID AS PO_CONTACT_ID
	, PO.ENTERED_BY AS PO_ENTERED_BY
	, PRL.PURC_REQ_ID AS PRL_PURC_REQ_ID
	, PRL.LINE_NO AS PRL_LINE_NO
	, PRL.PART_ID AS PRL_PART_ID
	, PRL.VENDOR_ID AS PRL_VENDOR_ID
	, PRL.VENDOR_PART_ID AS PRL_VENDOR_PART_ID
	, PRL.USER_ORDER_QTY AS PRL_USER_ORDER_QTY
	, PRL.ORDER_QTY AS PRL_ORDER_QTY
	, PRL.PURCHASE_UM AS PRL_PURCHASE_UM
	, PRL.UNIT_PRICE AS PRL_UNIT_PRICE
	, PRL.GL_EXPENSE_ACCT_ID AS PRL_GL_EXPENSE_ACCT_ID
	, PRL.PRODUCT_CODE AS PRL_PRODUCT_CODE
	, PRL.COMMODITY_CODE AS PRL_COMMODITY_CODE
	, PRL.DESIRED_RECV_DATE AS PRL_DESIRED_RECV_DATE
	, PRL.LINE_STATUS AS PRL_LINE_STATUS
	, PRL.TOTAL_AMT_ORDERED AS PRL_TOTAL_AMT_ORDERED
	, PRL.USER_1 AS PRL_USER_1
	, PRL.USER_2 AS PRL_USER_2
	, PRL.USER_9 AS PRL_USER_9
	, PR.ID AS PR_ID
	, PR.VENDOR_ID AS PR_VENDOR_ID
	, PR.REQUISITION_DATE AS PR_REQUISITION_DATE
	, PR.DESIRED_RECV_DATE AS PR_DESIRED_RECV_DATE
	, PR.BUYER AS PR_BUYER
	, PR.PREPARER AS PR_PREPARER
	, PR.REQUESTOR AS PR_REQUESTOR
	, PR.ASSIGNED_TO AS PR_ASSIGNED_TO
	, PR.[STATUS] AS PR_STATUS
	, PR.TOTAL_AMT_ORDERED AS PR_TOTAL_AMT_ORDERED
FROM PURC_ORDER_LINE POL
	INNER JOIN PURCHASE_ORDER PO
		ON POL.PURC_ORDER_ID = PO.ID
	LEFT OUTER JOIN PURC_ORDER_REQ POR
		ON POL.PURC_ORDER_ID = POR.PURC_ORD_ID
		AND POL.LINE_NO = POR.PURC_ORD_LINE_NO
	LEFT OUTER JOIN PURC_REQ_LINE PRL
		ON POR.PURC_REQ_ID = PRL.PURC_REQ_ID
		AND POR.PURC_REQ_LINE_NO = PRL.LINE_NO
	LEFT OUTER JOIN PURC_REQUISITION PR
		ON PRL.[PURC_REQ_ID] = PR.ID
WHERE ([ORDER_DATE] >= @StartDate
	OR [REQUISITION_DATE] >= @StartDate)
	AND PO.[STATUS] <> 'X'

