USE LIVE
GO

--SELECT *
--FROM LIVESupplemental..PartPull_20220203

SELECT POL.PART_ID
	, A.LAST_ORDER_DATE
	, PO.VENDOR_ID
	, MAX(POL.UNIT_PRICE) AS UNIT_PRICE
FROM (SELECT POL.PART_ID
		, MAX(ORDER_DATE) AS LAST_ORDER_DATE
	FROM PURC_ORDER_LINE POL
	LEFT OUTER JOIN PURCHASE_ORDER PO
		ON POL.PURC_ORDER_ID = PO.ID
	WHERE EXISTS (SELECT 1 FROM LIVESupplemental..PartPull_20220203 P
		WHERE POL.PART_ID = P.PartID
		)
--		AND POL.TOTAL_RECEIVED_QTY > 0
	GROUP BY POL.PART_ID
	) A
INNER JOIN PURC_ORDER_LINE POL
	ON POL.PART_ID = A.PART_ID
INNER JOIN PURCHASE_ORDER PO
	ON POL.PURC_ORDER_ID = PO.ID
	AND A.LAST_ORDER_DATE = PO.ORDER_DATE
--WHERE POL.TOTAL_RECEIVED_QTY > 0
GROUP BY POL.PART_ID
	, A.LAST_ORDER_DATE
	, PO.VENDOR_ID
ORDER BY POL.PART_ID