use datawarehouse
go

SELECT WO.CREATE_DATE 
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID 
	, OP.SEQUENCE_NO
	, OP.RESOURCE_ID
	, WO.PART_ID
	, SR.USER_1
	, SR.USER_2
	, SR.USER_3
	, SR.USER_4
	, SR.USER_5
	, NCM_ID
	, P.PRODUCT_ID
	, PO.DISPLAY_ID AS PRODUCTION_ORDER_ID
	, NCM.PO_NUMBER AS VENDOR_PO_NUM
	, O.DISPLAY_ID AS OPERATION_ID
	, NCM.LOT_SIZE
	, NCM.ACCEPTED
	, NCM.REJECTED
	, NCM.NCM_DATE
	, NCM.DUE_DATE
	, NCM.REFERENCE_1 AS [SPEC_SECT]
	, NCM.REFERENCE_2 AS [DRAW_REF]
	, NCM.REFERENCE_3 AS [ASIS_DIM]
	, NCM.REFERENCE_4 AS [SHOULD_BE_DIM]
	, COALESCE(NCM.SK_FIN_NCM_PROCESS, NCM.SK_MFG_NCM_PROCESS, '_BLANK') AS [PROCESS]
	, COALESCE(NCM.SK_FIN_NCM_SUBPROCESS, NCM.SK_MFG_NCM_SUBPROCESS, '_BLANK') AS [SUBPROCESS]
	, NCM.USER_DEFINED_3 AS [CATEGORY]
	, ISNULL(NCM.USER_DEFINED_4, NCM.USER_DEFINED_7) AS [DEFECT]
	, NCM.DISPOSITION_TYPE
	, DT.[DESCRIPTION] AS DISP_DESC
	, NCM.DISP_DATE
	, NCM.REFERENCE_6 AS [REWORK_QTY]
	, NCM.REFERENCE_7 AS [SCRAP_QTY]
	, NCM.REFERENCE_8 AS [OVERAGE_QTY]
	, NCM.REFERENCE_9 AS [RETURN_QTY]
	, NCM.REFERENCE_10 AS [ASIS_QTY]
	, NCM.DISPOSITION
FROM WORK_ORDER WO
INNER JOIN OPERATION OP
	ON OP.WORKORDER_BASE_ID = WO.BASE_ID
	AND OP.WORKORDER_LOT_ID = WO.LOT_ID
	AND OP.WORKORDER_SPLIT_ID = WO.SPLIT_ID
	AND OP.WORKORDER_SUB_ID = WO.SUB_ID
	AND OP.WORKORDER_TYPE = WO.[TYPE]
INNER JOIN SHOP_RESOURCE_SITE SR
	ON OP.RESOURCE_ID = SR.RESOURCE_ID
--INNER JOIN LABOR_TICKET LT
--	ON LT.WORKORDER_BASE_ID = WO.BASE_ID
--	AND LT.WORKORDER_LOT_ID = WO.LOT_ID
--	AND LT.WORKORDER_SPLIT_ID = WO.SPLIT_ID
--	AND LT.WORKORDER_SUB_ID = WO.SUB_ID
--	AND LT.OPERATION_SEQ_NO = OP.SEQUENCE_NO
LEFT OUTER JOIN VQ_PRODUCTION_ORDER PO
	ON PO.ALT_ID_2 = WO.BASE_ID
	AND PO.ALT_ID_3 = WO.LOT_ID
	AND PO.ALT_ID_4	= WO.SPLIT_ID
	AND PO.ALT_ID_5 = WO.SUB_ID
	--ON PO.DISPLAY_ID = WO.BASE_ID + '/' + WO.LOT_ID
LEFT OUTER JOIN VQ_NONCONFORMANCE NCM
	ON PO.RECORD_ID = NCM.PROD_ORDER_REC_ID
	AND (COALESCE(NCM.SK_FIN_NCM_PROCESS, NCM.SK_MFG_NCM_PROCESS, '_BLANK') = SR.USER_2
		OR COALESCE(NCM.SK_FIN_NCM_SUBPROCESS, NCM.SK_MFG_NCM_SUBPROCESS, '_BLANK') = SR.USER_3
		OR 
		)
LEFT OUTER JOIN VQ_PRODUCT P
	ON P.RECORD_ID = NCM.PRODUCT_REC_ID
LEFT OUTER JOIN VQ_OPERATION O
	ON O.RECORD_ID = NCM.OPERATION_REC_ID
	AND O.DISPLAY_ID = OP.SEQUENCE_NO
LEFT OUTER JOIN VQ_DISPOSITION_TYPE DT
	ON DT.[DISPOSITION_TYPE] = NCM.[DISPOSITION_TYPE]
LEFT OUTER JOIN VQ_EMPLOYEE MADE_EE
	ON MADE_EE.RECORD_ID = NCM.MADE_BY_EMP_REC_ID
WHERE WO.[TYPE] = 'W'
	--AND WO.CREATE_DATE >= '1/1/2019'

	and wo.base_id = '1546091'
	--and ncm.ncm_id ='0000687'

ORDER BY WO.BASE_ID	
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, OP.SEQUENCE_NO