USE LIVE
GO

SELECT * FROM SHOP_RESOURCE_SITE WHERE USER_1 IN ('C', 'O', 'X')

SELECT USER_1, COUNT(*) FROM SHOP_RESOURCE_SITE 
--WHERE STATUS IS NULL OR STATUS != 'O'
GROUP BY USER_1
ORDER BY USER_1

SELECT * FROM SHOP_RESOURCE_SITE WHERE USER_1 IN ('M', 'X') AND (STATUS IS NULL OR STATUS != 'O')
SELECT * FROM SHOP_RESOURCE_SITE WHERE USER_1 IN ('A', 'B', 'O') AND (STATUS IS NULL OR STATUS != 'O')
/*
BEGIN TRANSACTION;
UPDATE SHOP_RESOURCE_SITE 
SET SETUP_COST_PER_HR = 32
, RUN_COST_PER_HR = 32
WHERE USER_1 IN ('M', 'X')
--> 218 ROWS AFFECTED
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

BEGIN TRANSACTION;
UPDATE SHOP_RESOURCE_SITE 
SET SETUP_COST_PER_HR = 31
, RUN_COST_PER_HR = 31
WHERE USER_1 IN ('A', 'B', 'O')
--> 200 ROWS AFFECTED
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

SELECT * FROM EMPLOYEE_SITE ES

SELECT DEPARTMENT_ID, BASE_PAY_RATE, COUNT(*)
FROM EMPLOYEE_SITE ES
INNER JOIN EMPLOYEE EE
ON EE.ID = ES.EMPLOYEE_ID
WHERE EE.ACTIVE = 'Y'
GROUP BY DEPARTMENT_ID, BASE_PAY_RATE
ORDER BY BASE_PAY_RATE

SELECT * FROM DEPARTMENT

SELECT ES.*
FROM EMPLOYEE_SITE ES
INNER JOIN EMPLOYEE EE
ON EE.ID = ES.EMPLOYEE_ID
WHERE EE.ACTIVE = 'Y'
AND DEPARTMENT_ID IN ('200100', '200200')

SELECT ES.*
FROM EMPLOYEE_SITE ES
INNER JOIN EMPLOYEE EE
ON EE.ID = ES.EMPLOYEE_ID
WHERE EE.ACTIVE = 'Y'
AND DEPARTMENT_ID IN ('300100', '300200', '400100', '700100', '700200', '800200')

SELECT ES.*
FROM EMPLOYEE_SITE ES
INNER JOIN EMPLOYEE EE
ON EE.ID = ES.EMPLOYEE_ID
WHERE EE.ACTIVE = 'Y'
AND DEPARTMENT_ID IN ('100100', '100200', '600100', '960000')


/*
BEGIN TRANSACTION;
UPDATE EMPLOYEE_SITE 
SET BASE_PAY_RATE = 31
FROM EMPLOYEE_SITE ES
INNER JOIN EMPLOYEE EE
ON EE.ID = ES.EMPLOYEE_ID
WHERE EE.ACTIVE = 'Y'
AND DEPARTMENT_ID IN ('300100', '300200', '400100', '400200', '700100', '700200', '800100', '800200')
--> 101 ROWS AFFECTED
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

BEGIN TRANSACTION;
UPDATE EMPLOYEE_SITE 
SET BASE_PAY_RATE = 32
FROM EMPLOYEE_SITE ES
INNER JOIN EMPLOYEE EE
ON EE.ID = ES.EMPLOYEE_ID
WHERE EE.ACTIVE = 'Y'
AND DEPARTMENT_ID IN ('100100', '100200', '600100', '600200', '960000')
--> 162 RWS AFFECTED
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

SELECT TOP 100 * FROM OPERATION WHERE WORKORDER_TYPE = 'M'

SELECT COUNT(*) FROM OPERATION WHERE WORKORDER_TYPE = 'M' -- RESOURCE_ID LIKE 'P3%' AND
