USE LIVE
GO

--> ACCOUNT CHAINS
SELECT ISNULL(A07.PARENT_ACCT_ID, '') AS ACCT01
, ISNULL(A06.PARENT_ACCT_ID, '') AS ACCT02
, ISNULL(A05.PARENT_ACCT_ID, '') AS ACCT03
, ISNULL(A04.PARENT_ACCT_ID, '') AS ACCT04
, ISNULL(A03.PARENT_ACCT_ID, '') AS ACCT05
, ISNULL(A02.PARENT_ACCT_ID, '') AS ACCT06
, ISNULL(A01.PARENT_ACCT_ID, '') AS ACCT07
, ISNULL(A01.ID, '') AS ACCT08
FROM ACCOUNT A01
LEFT OUTER JOIN ACCOUNT A02
ON A02.ID = A01.PARENT_ACCT_ID
LEFT OUTER JOIN ACCOUNT A03
ON A03.ID = A02.PARENT_ACCT_ID
LEFT OUTER JOIN ACCOUNT A04
ON A04.ID = A03.PARENT_ACCT_ID
LEFT OUTER JOIN ACCOUNT A05
ON A05.ID = A04.PARENT_ACCT_ID
LEFT OUTER JOIN ACCOUNT A06
ON A06.ID = A05.PARENT_ACCT_ID
LEFT OUTER JOIN ACCOUNT A07
ON A07.ID = A06.PARENT_ACCT_ID


--> ACCOUNT BALANCES
SELECT A.ID
, A.[DESCRIPTION]
, A.[TYPE]
, A.SUMMARY_ACCOUNT
, A.PARENT_ACCT_ID
, AB.ACCT_YEAR
, AB.ACCT_PERIOD
, AB.DEBIT_AMOUNT
, AB.CREDIT_AMOUNT
, AB.CURR_BALANCE
FROM ACCOUNT A
LEFT OUTER JOIN ACCOUNT_BALANCE AB
ON A.ID = AB.ACCOUNT_ID
WHERE ACCT_YEAR >= '2016'

--> JOURNAL MONTHLY BALANCES (I.E. GENERAL LEDGER)
SELECT J.ACCOUNT_ID
, J.ACCT_YEAR
, J.ACCT_PERIOD
, SUM(J.DEBIT_AMOUNT) AS DEBIT_AMOUNT
, SUM(J.CREDIT_AMOUNT) AS CREDIT_AMOUNT
FROM JOURNAL J
WHERE J.ACCT_YEAR >= '2016'
GROUP BY J.ACCOUNT_ID
, J.ACCT_YEAR
, J.ACCT_PERIOD

--> RECEIVABLE BALANCES
SELECT R.CUSTOMER_ID
	, C.[NAME]
	, C.USER_9
	, YEAR(R.POSTING_DATE) AS ACCT_YEAR
	, MONTH(R.POSTING_DATE) AS ACCT_PERIOD
	, SUM(R.TOTAL_AMOUNT) AS TOTAL_AMOUNT
	, SUM(R.PAID_AMOUNT) AS PAID_AMOUNT
FROM LIVE.dbo.RECEIVABLE R
INNER JOIN LIVE.dbo.CUSTOMER C
ON R.CUSTOMER_ID = C.ID
WHERE YEAR(R.POSTING_DATE) >= '2016'
GROUP BY R.CUSTOMER_ID
	, C.[NAME]
	, C.USER_9
	, YEAR(R.POSTING_DATE)
	, MONTH(R.POSTING_DATE)
ORDER BY R.CUSTOMER_ID
	, C.[NAME]
	, C.USER_9
	, YEAR(R.POSTING_DATE)
	, MONTH(R.POSTING_DATE)

