USE LIVE
GO

DECLARE @STARTDATE DATE = '2/1/2020'
, @ENDDATE DATE = '3/1/2020'

/* ORIGINAL CODE
SELECT R.CUSTOMER_ID
	, C.[NAME]
	, C.SALESREP_ID
	, C.ACTIVE_FLAG
	, R.POSTING_DATE
	, R.INVOICE_ID
	, R.INVOICE_DATE
	, R.TOTAL_AMOUNT
	, R.PAID_AMOUNT
FROM LIVE.dbo.RECEIVABLE R
INNER JOIN LIVE.dbo.CUSTOMER C
ON R.CUSTOMER_ID = C.ID
WHERE R.POSTING_DATE >= '2019-01-01'
AND R.POSTING_DATE < '2020-01-01'
ORDER BY R.CUSTOMER_ID
, R.INVOICE_ID
*/

-- MONTHLY CUSTOMER RECEIVABLES
SELECT R.CUSTOMER_ID
	, C.[NAME]
	, C.SALESREP_ID
	, C.ACTIVE_FLAG
	, C.USER_9
	, MONTH(R.POSTING_DATE) AS POSTING_MONTH
	--, R.INVOICE_ID
	--, R.INVOICE_DATE
	, SUM(R.TOTAL_AMOUNT) AS TOTAL_AMOUNT
	, SUM(R.PAID_AMOUNT) AS PAID_AMOUNT
FROM LIVE.dbo.RECEIVABLE R
INNER JOIN LIVE.dbo.CUSTOMER C
ON R.CUSTOMER_ID = C.ID
WHERE R.POSTING_DATE >= @STARTDATE
AND R.POSTING_DATE < @ENDDATE
GROUP BY R.CUSTOMER_ID
	, C.[NAME]
	, C.SALESREP_ID
	, C.ACTIVE_FLAG
	, C.USER_9
	, MONTH(R.POSTING_DATE)
ORDER BY R.CUSTOMER_ID
	, C.[NAME]
	, C.SALESREP_ID
	, C.ACTIVE_FLAG
	, C.USER_9
	, MONTH(R.POSTING_DATE)
	;

--INVENTORY ISSUES
SELECT CASE 
		WHEN ID.DEMAND_SUPPLY_ID IS NULL THEN 'UNLINKED'
		WHEN ID.DEMAND_SUPPLY_ID IS NOT NULL THEN 'LINKED'
	END AS [ORDER]
	, *
FROM SHIPPER_LINE SL
INNER JOIN SHIPPER S
	ON S.PACKLIST_ID = SL.PACKLIST_ID
INNER JOIN RECEIVABLE_LINE RL
	ON RL.INVOICE_ID = S.INVOICE_ID
INNER JOIN RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
--> links Shipper to CO
INNER JOIN LIVE.dbo.INVENTORY_TRANS IT 
	ON IT.TRANSACTION_ID = SL.TRANSACTION_ID
INNER JOIN LIVE.dbo.CUST_ORDER_LINE COL
	ON IT.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND IT.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN LIVE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN LIVE.dbo.CUSTOMER C
	ON CO.CUSTOMER_ID = C.ID
INNER JOIN LIVE.dbo.INV_TRANS_DIST ID
	ON IT.TRANSACTION_ID = ID.OUT_TRANS_ID 
--> Inventory Issued to Job
INNER JOIN LIVE.dbo.INVENTORY_TRANS I1
	ON ID.IN_TRANS_ID = I1.TRANSACTION_ID
--LEFT OUTER JOIN LIVE.dbo.OPERATION O
--	ON I1.WORKORDER_TYPE = O.WORKORDER_TYPE
--	AND I1.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
--	AND I1.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
--	AND I1.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
--LEFT OUTER JOIN LIVE.dbo.SHOP_RESOURCE SR
-- --	ON O.RESOURCE_ID = SR.ID
-- LEFT OUTER JOIN WORK_ORDER WO
-- 	ON WO.[TYPE] = O.WORKORDER_TYPE
-- 	AND WO.BASE_ID = O.WORKORDER_BASE_ID
-- 	AND WO.LOT_ID = O.WORKORDER_LOT_ID
-- 	AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
-- 	AND WO.SUB_ID = O.WORKORDER_SUB_ID
 --LEFT OUTER JOIN LIVE.dbo.SKILLS_WO_REC_QTY S
	--ON O.WORKORDER_BASE_ID = S.BASE_ID
	--AND O.WORKORDER_LOT_ID = S.LOT_ID
	--AND O.WORKORDER_SPLIT_ID = S.SPLIT_ID
WHERE (IT.TRANSACTION_DATE >= @STARTDATE
		AND IT.TRANSACTION_DATE < @ENDDATE)
	-- AND WO.RECEIVED_QTY > 0  -- ?? only if want to filter to completed jobs
	-- AND SR.RESOURCE_TYPE = N'LABOR'  -- ?? only if want to filter to labor resources

	AND IT.CLASS = N'I'
	AND IT.[TYPE] = N'O'
;