use DataWarehouse
go

SELECT R.CUSTOMER_ID
	, R.INVOICE_ID
	, R.INVOICE_DATE
	, R.TOTAL_AMOUNT
	, R.PAID_AMOUNT
	, C.NAME
	, R.POSTING_DATE
	, C.SALESREP_ID
	, C.ACTIVE_FLAG
FROM RECEIVABLE R
INNER JOIN CUSTOMER C
	ON R.CUSTOMER_ID = C.ID
WHERE R.POSTING_DATE >= '2019-05-01' 
	AND R.POSTING_DATE < '2019-06-01'
ORDER BY R.CUSTOMER_ID
	, R.INVOICE_ID


