use LIVESupplemental
go

SELECT * FROM ReportSettings_ResourceID 
WHERE REPORT_NAME = 'TRAVELLER' 
AND Report_Section = 'stamp'
AND RESOURCE_ID LIKE '%BLAST%'

--BEGIN TRANSACTION;
--DELETE FROM ReportSettings_ResourceID WHERE REPORT_NAME = 'TRAVELLER' AND RESOURCE_ID LIKE '%BLAST%'
--> 1 ROW DELETED
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;