SELECT SR.ID AS RESOURCE_ID, SR.STATUS, COUNT(*) 
FROM SHOP_RESOURCE SR
LEFT OUTER JOIN OPERATION O
ON O.RESOURCE_ID = SR.ID
WHERE WORKORDER_TYPE = 'M' 
GROUP BY SR.ID, SR.STATUS 
ORDER BY SR.ID, SR.STATUS

SELECT WORKORDER_BASE_ID
, WORKORDER_LOT_ID
, WORKORDER_SPLIT_ID
, WORKORDER_SUB_ID
, SEQUENCE_NO
, SR.ID AS RESOURCE_ID
, SR.STATUS
, O.STATUS
, WO.STATUS
FROM SHOP_RESOURCE SR
LEFT OUTER JOIN OPERATION O
ON O.RESOURCE_ID = SR.ID
LEFT OUTER JOIN WORK_ORDER WO
ON O.WORKORDER_BASE_ID = WO.BASE_ID
AND O.WORKORDER_LOT_ID = WO.LOT_ID
AND O.WORKORDER_SPLIT_ID = WO.SPLIT_ID
AND O.WORKORDER_SUB_ID = WO.SUB_ID
AND O.WORKORDER_TYPE = WO.TYPE
WHERE WORKORDER_TYPE = 'M' 
AND SR.STATUS = 'O'

SELECT ID
, DESCRIPTION
, STATUS
FROM SHOP_RESOURCE SR
WHERE SR.DESCRIPTION LIKE '%DO NOT%'
AND (STATUS IS NULL 
	OR STATUS != 'O')
