USE LIVE
GO

DECLARE @START DATETIME, @END DATETIME
SET @START = '2019-01-01'
SET @END = '2019-12-31'

; WITH CTEBASE AS 
(SELECT RD.INVOICE_ID
	, RD.BATCH_ID
	, RD.GL_ACCOUNT_ID
	, A.[DESCRIPTION]
	, SUM(CASE WHEN RD.AMOUNT_TYPE = 'CR' THEN RD.AMOUNT ELSE RD.AMOUNT * -1 END) AS AMOUNT
	, R.CUSTOMER_ID
	, C.[NAME]
	, R.POSTING_DATE
	, R.[STATUS]
	, ISNULL((SELECT SUM(AMOUNT) FROM RECEIVABLE_LINE WHERE INVOICE_ID = RD.INVOICE_ID AND GL_ACCOUNT_ID = RD.GL_ACCOUNT_ID), 0) AS LINE_AMT
	, (SELECT COUNT(*) FROM RECEIVABLE_DIST WHERE INVOICE_ID = RD.INVOICE_ID AND GL_ACCOUNT_ID = RD.GL_ACCOUNT_ID AND POSTING_DATE < @START) AS PRIORDISTENTRY
--> PULL ALL JOURNAL POSTINGS WITHIN TIMEFRAME
FROM RECEIVABLE_DIST RD
--> PULL ALL MATCHING INVOICES 
JOIN RECEIVABLE R ON RD.INVOICE_ID = R.INVOICE_ID
JOIN CUSTOMER C ON R.CUSTOMER_ID = C.ID
--!!!--> PULL ONLY REVENUE ACCOUNTS
JOIN ACCOUNT A ON RD.GL_ACCOUNT_ID = A.ID AND A.TYPE = 'R'
WHERE RD.POSTING_DATE BETWEEN @START AND @END
GROUP BY RD.INVOICE_ID
	, RD.BATCH_ID
	, RD.GL_ACCOUNT_ID
	, A.[DESCRIPTION]
	, R.CUSTOMER_ID
	, C.[NAME]
	, R.POSTING_DATE
	, R.[STATUS]
) 

SELECT 'ARI' AS SOURCE
	, B.INVOICE_ID AS DOCUMENT
	, B.BATCH_ID
	, B.GL_ACCOUNT_ID
	, B.[DESCRIPTION] AS GL_ACCOUNT_DESC
	, B.CUSTOMER_ID
	, B.[NAME]
	, B.POSTING_DATE
	, B.[STATUS]
	, B.AMOUNT AS INVAMT
	, RL.LINE_NO
	, ISNULL(RL.REFERENCE,'') AS REFERENCE
	, RL.QTY
	, CASE WHEN B.STATUS = 'X' AND B.PRIORDISTENTRY > 0 THEN RL.AMOUNT * -1 ELSE RL.AMOUNT END AS LNAMOUNT
FROM CTEBASE B 
--> APPEND INVOICE_LINE INFORMATION WHERE AMOUNT != 0
LEFT JOIN RECEIVABLE_LINE RL ON B.INVOICE_ID = RL.INVOICE_ID AND B.GL_ACCOUNT_ID = RL.GL_ACCOUNT_ID AND RL.AMOUNT <> 0
WHERE B.AMOUNT <> 0
UNION ALL
SELECT 'ARC' AS SOURCE
	, CR.CHECK_ID
	, D.BATCH_ID
	, D.GL_ACCOUNT_ID
	, A.[DESCRIPTION]
	, ISNULL(CR.CUSTOMER_ID, '') AS CUSTOMER_ID
	, ISNULL(C.[NAME], '') AS [NAME]
	, D.POSTING_DATE
	, CR.[STATUS]
	, CASE WHEN D.AMOUNT_TYPE = 'CR' THEN D.AMOUNT ELSE D.AMOUNT*-1 END AS PAYAMT
	, 0 AS LINE_NO
	, 'DISCOUNT AND/OR DIRECT CHARGE FROM PAYMENT'
	, 1 AS QTY
	, CASE WHEN D.AMOUNT_TYPE = 'CR' THEN D.AMOUNT ELSE D.AMOUNT * -1 END AS LINEAMT
FROM CASH_RECEIPT_DIST D 
--!!!--> PULL ONLY REVENUE ACCOUNTS 
JOIN ACCOUNT A ON D.GL_ACCOUNT_ID = A.ID AND A.[TYPE] = 'R'
JOIN CASH_RECEIPT CR ON D.CUSTOMER_ID = CR.CUSTOMER_ID AND D.CHECK_ID = CR.CHECK_ID
JOIN CUSTOMER C ON CR.CUSTOMER_ID = C.ID
WHERE D.POSTING_DATE BETWEEN @START AND @END
UNION ALL
SELECT 'GJ' AS SOURCE
	, L.GJ_ID
	, '' AS BATCH_ID
	, L.GL_ACCOUNT_ID 
	, A.[DESCRIPTION]
	, 'N/A' AS CUSTOMER_ID
	, GJ.[DESCRIPTION]
	, GJ.POSTING_DATE
	, '-' AS [STATUS]
	, L.CREDIT_AMOUNT - L.DEBIT_AMOUNT AS INVAMOUNT
	, L.LINE_NO
	, ISNULL(L.REFERENCE, '')
	, 0 AS QTY
	, L.CREDIT_AMOUNT - L.DEBIT_AMOUNT AS LNAMOUNT
FROM GJ 
JOIN GJ_LINE L ON GJ.ID = L.GJ_ID
--!!!--> PULL ONLY REVENUE ACCOUNTS 
JOIN ACCOUNT A ON L.GL_ACCOUNT_ID = A.ID AND A.[TYPE] = 'R'
WHERE GJ.POSTING_DATE BETWEEN @START AND @END
ORDER BY GL_ACCOUNT_ID

--A.[TYPE] = 'R' --> 43835
-- none --> 93130