USE DATAWAREHOUSE
GO

DECLARE @ReportSettings AS TABLE (Resource NVARCHAR(30), [1000] INT, [1200] INT, [600] INT, alo INT, ano INT, Blast INT, Boric INT, Chrome INT, Deburr INT, Pen INT, Polish INT, Prime INT, ShotPeen INT, Sulf INT, TopCoat INT)
INSERT INTO @ReportSettings
EXEC LIVESupplemental..usp_GetReportSettings 'ROYMFG Parts List'

;
WITH CTE_CPE AS 
(SELECT CUSTOMER_ID
	, PART_ID
	, MAX(EFFECTIVE_DATE) AS EFF_DATE
	, MAX(ISNULL(DISCONTINUE_DATE, GETDATE() + 1)) AS DISC_DATE
	, DEFAULT_UNIT_PRICE
FROM CUST_PRICE_EFFECT 
WHERE CUSTOMER_ID = 'ROYMFG'
	AND ISNULL(DISCONTINUE_DATE, GETDATE() + 1) > GETDATE()
	AND ISNULL(EFFECTIVE_DATE, GETDATE() - 1) <= GETDATE()
GROUP BY CUSTOMER_ID, PART_ID
	, DEFAULT_UNIT_PRICE
)

SELECT CO.CUSTOMER_ID
	, WO.PART_ID
	, UDF26.NUMBER_VAL AS SURFACE_AREA
	, UDF35.STRING_VAL AS MATL_TYPE
	, UDF36.STRING_VAL AS ALLOY
	, UDF37.NUMBER_VAL AS [LENGTH]
	, UDF38.NUMBER_VAL AS [WIDTH]
	, UDF39.NUMBER_VAL AS [THICKNESS]
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_WANT_DATE
	, WO.DESIRED_QTY
	, CPE.EFF_DATE
	, CPE.DISC_DATE
	, CPE.DEFAULT_UNIT_PRICE AS CONTRACT_PRICE
	, WO.[ACT_LABOR_COST]
	, WO.[ACT_BURDEN_COST]
	, WO.[ACT_MATERIAL_COST] + WO.[ACT_LABOR_COST] + WO.[ACT_BURDEN_COST] + WO.[ACT_SERVICE_COST] AS TotalActualCost
	, (WO.[ACT_MATERIAL_COST] + WO.[ACT_LABOR_COST] + WO.[ACT_BURDEN_COST] + WO.[ACT_SERVICE_COST])/WO.DESIRED_QTY AS AvgActualCost
	, [dbo].[sfn_All_OpTypes](wo.[type], WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID) AS OpTypes
	, [dbo].[sfn_all_operations](wo.[type], WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID) AS PROCESSES
	, O.RESOURCE_ID
	, CASE WHEN EXISTS (
				SELECT 1 
				FROM @ReportSettings S
				WHERE S.Resource = O.RESOURCE_ID
					AND ISNULL(S.Pen, -1) <> -1
					)
			THEN 'YES'
		ELSE 'NO'
	END AS PENETRANT
	, CASE 
		WHEN EXISTS (
				SELECT 1 
				FROM @ReportSettings S
				WHERE S.Resource = O.RESOURCE_ID
					AND ISNULL(S.ShotPeen, -1) <> -1
				)
			THEN 'YES'
		ELSE 'NO'
	END AS SHOTPEEN
	, CASE WHEN EXISTS (
				SELECT 1 
				FROM @ReportSettings S
				WHERE ISNULL(S.Prime, -1) <> -1
					AND EXISTS (
						SELECT 1 
						FROM OPERATION O
						WHERE S.RESOURCE = O.RESOURCE_ID
							AND WO.BASE_ID = O.WORKORDER_BASE_ID
							AND WO.LOT_ID = O.WORKORDER_LOT_ID
							AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
							AND WO.SUB_ID = O.WORKORDER_SUB_ID
							AND WO.[TYPE] = O.WORKORDER_TYPE
						)
					)
			THEN (SELECT OPERATION_TYPE 
			FROM OPERATION O2
			WHERE EXISTS (
				SELECT 1 
				FROM @ReportSettings S
				WHERE ISNULL(S.Prime, -1) <> -1
					AND S.Resource = O2.RESOURCE_ID
				)
			
			
		ELSE ''
	END AS PRIME
	, CASE WHEN EXISTS (
				SELECT 1 
				FROM @ReportSettings S
				WHERE S.Resource = O.RESOURCE_ID
					AND ISNULL(S.TopCoat, -1) <> -1
					)
			THEN O.OPERATION_TYPE
		ELSE ''
	END AS TOPCOAT
--1000
--1200
--600
--Blast
--Boric
--Chrome
--Deburr
--Polish
--Sulf
--alo
--ano


FROM WORK_ORDER WO
INNER JOIN [LIVESupplemental].[dbo].[PartID_ReportSettings] P
	ON WO.PART_ID = P.Part_ID

--INNER JOIN OPERATION O
--		ON WO.[TYPE] = O.WORKORDER_TYPE
--		AND WO.BASE_ID = O.WORKORDER_BASE_ID
--		AND WO.LOT_ID = O.WORKORDER_LOT_ID
--		AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
--		AND WO.SUB_ID = O.WORKORDER_SUB_ID
--		AND EXISTS (
--			SELECT 1
--			FROM LIVESupplemental..ResourceID_ReportSettings S
--			WHERE S.Report_Name = 'ROYMFG Parts List'
--				AND S.Resource_ID = O.RESOURCE_ID
--		)
LEFT OUTER JOIN CTE_CPE CPE
	ON CPE.PART_ID = WO.PART_ID
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.SUPPLY_TYPE = 'WO' 
	AND DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
	AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = CO.ID  
LEFT OUTER JOIN USER_DEF_FIELDS UDF26
-- SURFACE AREA
	ON UDF26.DOCUMENT_ID = WO.PART_ID
	AND UDF26.PROGRAM_ID = 'VMPRTMNT'
	AND UDF26.ID = 'UDF-0000026'
LEFT OUTER JOIN USER_DEF_FIELDS UDF35
-- MATERIAL TYPE
	ON UDF35.DOCUMENT_ID = WO.PART_ID
	AND UDF35.PROGRAM_ID = 'VMPRTMNT'
	AND UDF35.ID = 'UDF-0000035'
LEFT OUTER JOIN USER_DEF_FIELDS UDF36
-- ALLOY
	ON UDF36.DOCUMENT_ID = WO.PART_ID
	AND UDF36.PROGRAM_ID = 'VMPRTMNT'
	AND UDF36.ID = 'UDF-0000036'
LEFT OUTER JOIN USER_DEF_FIELDS UDF37
-- LENGTH
	ON UDF37.DOCUMENT_ID = WO.PART_ID
	AND UDF37.PROGRAM_ID = 'VMPRTMNT'
	AND UDF37.ID = 'UDF-0000037'
LEFT OUTER JOIN USER_DEF_FIELDS UDF38
-- WIDTH
	ON UDF38.DOCUMENT_ID = WO.PART_ID
	AND UDF38.PROGRAM_ID = 'VMPRTMNT'
	AND UDF38.ID = 'UDF-0000038'
LEFT OUTER JOIN USER_DEF_FIELDS UDF39
-- THICKNESS
	ON UDF39.DOCUMENT_ID = WO.PART_ID
	AND UDF39.PROGRAM_ID = 'VMPRTMNT'
	AND UDF39.ID = 'UDF-0000039'
WHERE WO.[TYPE] = 'W'
	AND WO.DESIRED_QTY > 0
	AND WO.DESIRED_WANT_DATE >= '1/1/2016'
	AND CO.CUSTOMER_ID = 'ROYMFG'

ORDER BY WO.PART_ID
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID




/*
SELECT TOP 10 * FROM USER_DEF_FIELDS WHERE PROGRAM_ID = 'VMPRTMNT'

SELECT * FROM WORK_ORDER WHERE BASE_ID = '1457770'
SELECT * FROM PART WHERE ID = '412A7230-9B'
SELECT * FROM PART_SITE WHERE PART_ID = '412A7230-9B'

select [dbo].[sfn_all_operations]('w', '1457770', '1', '0', '0')

select part_id
	, max(effective_date)
	, max(isnull(discontinue_date, getdate() + 1))
	, default_unit_price
from cust_price_effect 
where customer_id = 'royfab'
	and isnull(discontinue_date, getdate() + 1) > getdate()
	and effective_date <= getdate()
group by part_id
	, default_unit_price
order by part_id
	, default_unit_price

select * from cust_price_effect where part_id = '112U2717-18'
--IN ('112U2420-6', '112U9380-901', '112U9380-902', '112U9380-903', '112U9380-904', '112U9380-905', '112U9380-906', '112U9380-907', '112U9380-908', '112U9380-909', '112U9380-910', '412A7230-62B', '412A7231-1457B', '412A7231-1526B', '421W1189-11B', '421W1189-12B')
ORDER BY PART_ID
--in ('112U2401-51', '112U2402-5', '112U2402-51', '112U2403-5', '112U2405-6', '112U2407-5', '112U2407-6', '112U2409-5', '112U2409-6', '112U2410-5', '112U2410-6', '112U2414-5', '112U2414-6', '112U2415-5', '112U2415-6', '112U2416-5', '112U2417-5', '112U2417-6', '112U2419-5', '112U2419-6', '112U2420-5', '112U2421-5') -- = '112U2401-51'

select  [dbo].[sfn_All_OpTypes]('W', '1351167', '1', '0', '0') 
from work_order wo
WHERE BASE_ID = '1351167'

SELECT * 
from work_order wo
WHERE BASE_ID = '1351167'

SELECT * FROM OPERATION WHERE WORKORDER_BASE_ID = '1351167' ORDER BY SEQUENCE_NO

*/