use DataWarehouse
go

SELECT C.ID
	, UDF.STRING_VAL AS BUS_STREAM
	, BA.Business_Unit
	, C.SALESREP_ID AS CUST_SALES
	, CA.SALESREP_ID AS ADDR_SALES
	, CA.ADDR_NO
	, C.ACTIVE_FLAG
FROM CUSTOMER C
INNER JOIN CUST_ADDRESS CA
	ON C.ID = CA.CUSTOMER_ID
LEFT OUTER JOIN USER_DEF_FIELDS UDF
	ON UDF.DOCUMENT_ID = C.ID
	AND PROGRAM_ID = 'VMCUSMNT'
	AND UDF.ID = 'UDF-0000072'
LEFT OUTER JOIN LIVESupplemental.dbo.buyer_assn BA
	ON C.SALESREP_ID = BA.Salesperson_ID
WHERE C.ACTIVE_FLAG = 'Y'
AND C.ID NOT IN ('BOE609', 'SYSTEC', 'PRIMUS', 'RAMMOU')
AND UDF.STRING_VAL != BA.Business_Unit

SELECT * FROM LIVESupplemental.dbo.buyer_assn