USE LIVE
GO

SELECT C.ID
	, UDF.STRING_VAL AS BUS_STREAM
	, BA.Business_Unit
	, C.SALESREP_ID AS CUST_SALES
	, CA.SALESREP_ID AS ADDR_SALES
	, CA.ADDR_NO
	, C.ACTIVE_FLAG
FROM CUSTOMER C
INNER JOIN CUST_ADDRESS CA
	ON C.ID = CA.CUSTOMER_ID
LEFT OUTER JOIN USER_DEF_FIELDS UDF
	ON UDF.DOCUMENT_ID = C.ID
	AND PROGRAM_ID = 'VMCUSMNT'
	AND UDF.ID = 'UDF-0000072'
LEFT OUTER JOIN LIVESupplemental.dbo.buyer_assn BA
	ON C.SALESREP_ID = BA.Salesperson_ID
WHERE C.ACTIVE_FLAG = 'Y'
--AND C.SALESREP_ID IS NULL
--AND UDF.STRING_VAL != 'FIN_MFG'
--AND C.SALESREP_ID NOT IN ('DANIELLE', 'TIFFANY')
--AND C.SALESREP_ID IN ('SUNNI')
--AND C.ID NOT IN ('AERMAN', 'AMTRIB')
--AND (CA.SALESREP_ID IS NULL
--	OR C.SALESREP_ID != CA.SALESREP_ID)
--AND C.SALESREP_ID != CA.SALESREP_ID
AND C.ID NOT IN ('BOE609')
AND UDF.STRING_VAL != BA.Business_Unit
--AND UDF.STRING_VAL != 'FIN_MFG'
ORDER BY UDF.STRING_VAL

/*
UPDATE CUST_ADDRESS
SET SALESREP_ID = C.SALESREP_ID
FROM CUSTOMER C
INNER JOIN CUST_ADDRESS CA
ON C.ID = CA.CUSTOMER_ID
LEFT OUTER JOIN USER_DEF_FIELDS UDF
	ON UDF.DOCUMENT_ID = C.ID
	AND PROGRAM_ID = 'VMCUSMNT'
	AND UDF.ID = 'UDF-0000072'
--> 36 RECORDS
WHERE C.ACTIVE_FLAG = 'Y'
AND CA.SALESREP_ID IS NULL

--> 14 RECORDS
WHERE C.ACTIVE_FLAG = 'Y'
AND CA.SALESREP_ID != C.SALESREP_ID 
AND UDF.STRING_VAL = 'FIN'

--> 15 RECORDS
WHERE C.ACTIVE_FLAG = 'Y'
AND C.SALESREP_ID IS NULL

--> 39 RECORDs
WHERE C.ACTIVE_FLAG = 'Y'
AND UDF.STRING_VAL = 'FIN'
AND CA.SALESREP_ID IS NULL

--> 1 RECORD
WHERE C.ACTIVE_FLAG = 'Y'
AND CA.SALESREP_ID != C.SALESREP_ID 
AND UDF.STRING_VAL = 'FIN_MFG'

--> 1 RECORD
WHERE C.ACTIVE_FLAG = 'Y'
AND CA.SALESREP_ID != C.SALESREP_ID 
AND UDF.STRING_VAL = 'FIN_MFG'
AND C.ID = 'PRIMUS'

--> 134 RECORDS
WHERE C.ACTIVE_FLAG = 'Y'
AND CA.SALESREP_ID != C.SALESREP_ID 
AND UDF.STRING_VAL = 'FIN'

--> 10 RECORDS
WHERE C.ACTIVE_FLAG = 'Y'
AND CA.SALESREP_ID != C.SALESREP_ID 
AND UDF.STRING_VAL = 'OTHER'

--> 186 RECORDS
WHERE C.ACTIVE_FLAG = 'Y'
AND CA.SALESREP_ID IS NULL
AND UDF.STRING_VAL = 'MFG'

--> 162 RECORDS
WHERE C.ACTIVE_FLAG = 'Y'
AND C.SALESREP_ID != CA.SALESREP_ID
AND UDF.STRING_VAL = 'MFG'

--> 2 RECORDS
WHERE C.SALESREP_ID != CA.SALESREP_ID
AND C.ACTIVE_FLAG = 'Y'
AND C.ID = 'AMTMFG'

UPDATE CUSTOMER
SET SALESREP_ID = 'Danielle' 
WHERE ID IN ('SUBSOL')
--WHERE ID IN ('ANDMAC', 'BRIDGE', 'CONMAN', 'EDCINC', 'MAPAER', 'METCRA', 'MOTFLO', 'THRPRE', 'UNISWA')

UPDATE CUST_ADDRESS
SET SALESREP_ID = 'Danielle' 
WHERE CUSTOMER_ID IN ('SUBSOL')
--WHERE CUSTOMER_ID IN ('ANDMAC', 'BRIDGE', 'CONMAN', 'EDCINC', 'MAPAER', 'METCRA', 'MOTFLO', 'THRPRE', 'UNISWA')

*/