SELECT DISTINCT OBJECT_NAME(P.OBJECT_ID) AS TABLENAME
	, RESOURCE_TYPE
	, REQUEST_SESSION_ID
FROM SYS.DM_TRAN_LOCKS L
JOIN SYS.PARTITIONS P
ON L.RESOURCE_ASSOCIATED_ENTITY_ID = P.HOBT_ID
WHERE OBJECT_NAME(P.OBJECT_ID) LIKE '%'

--> CAN KILL SESSION VIA ACTIVITY MONITOR IF NEEDED