USE LIVE
GO

DECLARE  @REPORTSETTINGS TABLE(
    [RESOURCE] [NVARCHAR](15) NOT NULL,
    [BARCODE_ETCH] [INT] NULL,
    [BARCODE_PRE_ETCH] [INT] NULL,
    [BARCODE_REVIEW] [INT] NULL,
    [CHEM_TO_PRIME_HRS] [INT] NULL,
    [CLEAN_TO_SOLGEL_HRS] [INT] NULL,
    [FAI_NET_STAMP] [INT] NULL,
    [FAI_STAMP] [INT] NULL,
    [HEIGHTCHANGE] [INT] NULL,
    [PRINTUSER] [INT] NULL,
    [QTY_IN] [INT] NULL,
    [QTY_NOSHOW] [INT] NULL,
    [QTY_OUT] [INT] NULL,
    [SHIP_VIA] [INT] NULL,
    [STAMP] [INT] NULL,
    [START_OP_TO_SOLGEL] [INT] NULL
    ) 
 
INSERT INTO @REPORTSETTINGS
SELECT RESOURCE, [BARCODE_ETCH],[BARCODE_PRE_ETCH],[BARCODE_REVIEW],[CHEM_TO_PRIME_HRS],[CLEAN_TO_SOLGEL_HRS]
    ,[FAI_NET_STAMP],[FAI_STAMP],[HEIGHTCHANGE],[PRINTUSER],[QTY_IN],[QTY_NOSHOW],[QTY_OUT],[SHIP_VIA],[STAMP],[START_OP_TO_SOLGEL] 
FROM
        (
            SELECT RESOURCE
                , CAST(INCLUDE AS INT)INCLUDE
                , REPORT_SECTION
            FROM (    SELECT [RESOURCE_ID] AS RESOURCE, [REPORT_NAME], [REPORT_SECTION], [REASONING], [NOTES], [INCLUDE]
                    FROM [SQL-BI-1].LIVESUPPLEMENTAL.DBO.[RESOURCEID_REPORTSETTINGS] 
                ) A
            WHERE A.REPORT_NAME = 'TRAVELLER'
        ) X
        PIVOT
        (  MAX(INCLUDE)
            FOR REPORT_SECTION IN ([BARCODE_ETCH],[BARCODE_PRE_ETCH],[BARCODE_REVIEW],[CHEM_TO_PRIME_HRS],[CLEAN_TO_SOLGEL_HRS],[FAI_NET_STAMP],[FAI_STAMP],[HEIGHTCHANGE],[PRINTUSER],[QTY_IN],[QTY_NOSHOW],[QTY_OUT],[SHIP_VIA],[STAMP],[START_OP_TO_SOLGEL])
        )P 

--SELECT * FROM @REPORTSETTINGS

SELECT OT.ID AS OPTYPE
, OT.[DESCRIPTION] AS OT_DESC
, SR.ID AS RESOURCEID
, SR.[DESCRIPTION] AS SR_DESC
, SR.[STATUS]
, SR.USER_1 AS BUS_UNIT
, SR.USER_2 AS [PRIMARY]
, SR.USER_3 AS [SECONDARY]
, SR.USER_4 AS SUPERVISOR
, SR.USER_5 AS FACILITY
, SR.USER_6 AS DEPARTMENT
, SR.USER_7 AS PROCESS
, SR.USER_8 AS REPTGROUP
, SR.USER_9
, SR.USER_10
, RS.*
FROM SHOP_RESOURCE SR
LEFT OUTER JOIN OPERATION_TYPE OT
ON SR.ID = OT.RESOURCE_ID
LEFT OUTER JOIN @REPORTSETTINGS RS
ON RS.[RESOURCE] = SR.ID
WHERE SR.[STATUS] != 'O' OR SR.[STATUS] IS NULL