USE LIVE
GO

SELECT ID
, USER_4
FROM SHOP_RESOURCE
WHERE ID IN ('P2M1-REVIEW-CMP', 'P3M1-PM', 'P2M1-REC', 'P2M1-SHIP', 'P3M1-STAGNG-CMP')

UPDATE SHOP_RESOURCE
SET USER_4 = 'Catherine Bernsten'
WHERE ID IN ('P2M1-REVIEW-CMP')

UPDATE SHOP_RESOURCE
SET USER_4 = 'Larissa Brandenberg'
WHERE ID IN ('P3M1-PM')

UPDATE SHOP_RESOURCE
SET USER_4 = 'Kristen Reynolds'
WHERE ID IN ('P2M1-REC', 'P2M1-SHIP')

UPDATE SHOP_RESOURCE
SET USER_4 = 'Cynthia Hofer'
WHERE ID IN ('P3M1-STAGNG-CMP')


UPDATE SHOP_RESOURCE_SITE
SET USER_4 = 'Catherine Bernsten'
WHERE RESOURCE_ID IN ('P2M1-REVIEW-CMP')

UPDATE SHOP_RESOURCE_SITE
SET USER_4 = 'Larissa Brandenberg'
WHERE RESOURCE_ID IN ('P3M1-PM')

UPDATE SHOP_RESOURCE_SITE
SET USER_4 = 'Kristen Reynolds'
WHERE RESOURCE_ID IN ('P2M1-REC', 'P2M1-SHIP')

UPDATE SHOP_RESOURCE_SITE
SET USER_4 = 'Cynthia Hofer'
WHERE RESOURCE_ID IN ('P3M1-STAGNG-CMP')
