use live
go

update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'ANM-abrburr'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'ANM-assembly'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'ANM-brakfrmcold'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'ANM-cncrouter3'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'ANM-cncrouter4'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'ANM-countersink'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'ANM-FINALinsp'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'ANM-fladderburr'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'ANM-handburr'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'ANM-insp'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'ANM-mylar'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'ANM-Review'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'ANM-ship'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'ANM-stores'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-1000'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-600'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-alo'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-ano'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-assembly'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-assyINSP'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-assyPM'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-blast'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-boeingpkg'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-boric'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-cert'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-chemstrip'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-clean'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-eddycur'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-emu'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-etch'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-FINALinsp'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-handburr'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-insp'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-Insp-Cargo'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-mask'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-Mask-Cargo'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-msp'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-Mylar-Cargo'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-NrthMFGinsp'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-oven1'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-ovenPrime'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-ovenTC'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-panel'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-pen'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-PENetch'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-pkg'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-plan'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-pm'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-PM-Cargo'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-pri'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-rack'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-review'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-sand'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-setup'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-ship'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-solgel'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-sp'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-takedown'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-tc'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-tube'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-TurcoClean'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-unrack'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'AUB-verify'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'B1F1-ANO-BORIC'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'B1F1-CHCNV-1000'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'B1F1-CHCNV-1200'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'B1F1-CHCNV-600'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'B1F1-CH-EMU'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'B1F1-ETCH'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'B1F1-POLISH'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'B1F1-RACK'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'B1F1-REVIEW'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'B1F1-SHIP'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'B1F1-SULF'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'B1F1-UNRACK'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-1000'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-600'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-abrburr'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-alo'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-ano'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-blast'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-boeingpkg'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-boric'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-cert'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-emu'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-etch'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-FINALinsp'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-handburr'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-insp'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-mask'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-MFGinsp'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-ovenPrime'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-ovenTC'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-pen'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-PENetch'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-pkg'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-plan'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-pm'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-polish'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-pri'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-rack'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-review'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-sand'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-setup'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-ship'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-sp'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-sulf'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-takedown'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-tc'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-unrack'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'BAL-verify'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'bandsaw'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'boeingpkg'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'boltboard'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'bpmill'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'brakeform'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'buffalo-roller'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'Clean'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'CMM'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'cncdoosan'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'cncmill'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'cncmill-12'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'cncmill-4'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'cncmill-5'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'cncrouter'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'contractor'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'cutoffsaw'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'drill'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'FAI'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'handburr'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'honing'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'hot joggle'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'hydroform'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'insp'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'maint'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'mlathe'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'msp'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'notcher'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'okuma'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'panel'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'pm'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'polish'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'Programming'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'PROGS'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'punch press'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'review'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'rivet'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'rnotcher'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'rwec'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'shear'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'SouthAUB-blast'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'SouthAUB-boepkg'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'SouthAUB-cert'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'SouthAUB-Final'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'SouthAUB-pkg'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'SouthAUB-ship'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'SouthAUB-verify'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'Stores'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'straightening'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'sulf'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'tablesaw'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'Timesaver'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'tooling'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'tpunch'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'vibraburr'
update shop_resource set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where id = 'Waterjet'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'ASSEMBLY', USER_4 = 'Brian Swartley' where id = 'P2M1-IN-ASSY'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'CMM', USER_4 = 'Brian Swartley' where id = 'P2M1-IN-CMM'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'DIMENSIONAL', USER_4 = 'Brian Swartley' where id = 'P2M1-IN-DIM'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'FAI', USER_4 = 'Brian Swartley' where id = 'P2M1-IN-FAI'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'FINAL', USER_4 = 'Brian Swartley' where id = 'P2M1-IN-FNL'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'OSP', USER_4 = 'Brian Swartley' where id = 'P2M1-IN-OUTFIN'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'ROCKWELL', USER_4 = 'Brian Swartley' where id = 'P2M1-IN-RWEC'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'TOOLING', USER_4 = 'Brian Swartley' where id = 'P2M1-IN-TOOLING'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'DIMENSIONAL', USER_4 = 'Brian Swartley' where id = 'P2M2-IN-DIM-CMP'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'DIMENSIONAL', USER_4 = 'Brian Swartley' where id = 'P3M1-IN-DIM'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'FINAL', USER_4 = 'Brian Swartley' where id = 'P3M1-IN-FNL'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'CMP FINAL', USER_4 = 'Brian Swartley' where id = 'P3M1-IN-FNL-CMP'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'INSPECTION', USER_4 = 'Brian Swartley' where id = 'P3M1-IN-ASSY'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'INSPECTION', USER_4 = 'Brian Swartley' where id = 'P3M1-IN-FAI'
update shop_resource set USER_2 = 'RECEIVING', USER_3 = 'PANELS', USER_4 = 'Brian Swartley' where id = 'P2M1-PANEL'
update shop_resource set USER_2 = 'CARGO', USER_3 = 'ASSEMBLY', USER_4 = 'Christen Erickson' where id = 'P1M1-CP-AS'
update shop_resource set USER_2 = 'CARGO', USER_3 = 'CNC', USER_4 = 'Christen Erickson' where id = 'P1M1-CP-CNC-RT3'
update shop_resource set USER_2 = 'CARGO', USER_3 = 'CNC', USER_4 = 'Christen Erickson' where id = 'P1M1-CP-CNC-RT4'
update shop_resource set USER_2 = 'CARGO', USER_3 = 'COUNTERSINK', USER_4 = 'Christen Erickson' where id = 'P1M1-CP-CNTRSNK'
update shop_resource set USER_2 = 'CARGO', USER_3 = 'FINAL', USER_4 = 'Christen Erickson' where id = 'P1M1-CP-FINAL'
update shop_resource set USER_2 = 'CARGO', USER_3 = 'DEBURR', USER_4 = 'Christen Erickson' where id = 'P1M1-CP-FLADDER'
update shop_resource set USER_2 = 'CARGO', USER_3 = 'BRAKEFORM', USER_4 = 'Christen Erickson' where id = 'P1M1-CP-FM-RF'
update shop_resource set USER_2 = 'CARGO', USER_3 = 'DIMENSIONAL', USER_4 = 'Christen Erickson' where id = 'P1M1-CP-IN-DIM'
update shop_resource set USER_2 = 'CARGO', USER_3 = 'MYLAR', USER_4 = 'Christen Erickson' where id = 'P1M1-CP-MYLAR'
update shop_resource set USER_2 = 'CARGO', USER_3 = 'REVIEW', USER_4 = 'Christen Erickson' where id = 'P1M1-CP-REVIEW'
update shop_resource set USER_2 = 'CARGO', USER_3 = 'RAW MATERIAL', USER_4 = 'Christen Erickson' where id = 'P1M1-CP-RLSMTL'
update shop_resource set USER_2 = 'CARGO', USER_3 = 'SHIPPING', USER_4 = 'Christen Erickson' where id = 'P1M1-CP-SHIP'
update shop_resource set USER_2 = 'CARGO', USER_3 = 'DEBURR', USER_4 = 'Christen Erickson' where id = 'P1M1-DB-DBR'
update shop_resource set USER_2 = 'CARGO ', USER_3 = 'MASKING', USER_4 = 'Christen Erickson' where id = 'P1F1-CP-MASK'
update shop_resource set USER_2 = 'CARGO ', USER_3 = 'PART MARK', USER_4 = 'Christen Erickson' where id = 'P1F1-CP-PM'
update shop_resource set USER_2 = 'FINISHED GOODS', USER_3 = 'KITTING', USER_4 = 'Christi Morgan' where id = 'P2M1-KIT-FG'
update shop_resource set USER_2 = 'PROGRAMMING', USER_3 = 'CNC', USER_4 = 'Creg Crones' where id = 'P2M1-PROG-CNC'
update shop_resource set USER_2 = 'PROGRAMMING', USER_3 = 'LATHE', USER_4 = 'Creg Crones' where id = 'P2M1-PROG-LATHE'
update shop_resource set USER_2 = 'PROGRAMMING', USER_3 = 'TURRET PUNCH', USER_4 = 'Creg Crones' where id = 'P2M1-PROG-TP'
update shop_resource set USER_2 = 'PROGRAMMING', USER_3 = 'WATERJET', USER_4 = 'Creg Crones' where id = 'P2M1-PROG-WJ'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'QP REVIEW', USER_4 = 'Diane Booth' where id = 'P2M1-IN-QPREV'
update shop_resource set USER_2 = 'BALLARD', USER_3 = 'BUSINESS SOLUTIONS', USER_4 = 'Dmitriy Mandelman' where id = 'outreach'
update shop_resource set USER_2 = 'BALLARD', USER_3 = 'BUSINESS SOLUTIONS', USER_4 = 'Dmitriy Mandelman' where id = 'OUT-review'
update shop_resource set USER_2 = 'ASSEMBLY', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where id = 'P2M1-AS'
update shop_resource set USER_2 = 'ASSEMBLY', USER_3 = 'BUSHING', USER_4 = 'Greg Hartman' where id = 'P2M1-AS-BUSH'
update shop_resource set USER_2 = 'ASSEMBLY', USER_3 = 'DRILLING', USER_4 = 'Greg Hartman' where id = 'P2M1-AS-DRILL'
update shop_resource set USER_2 = 'ASSEMBLY', USER_3 = 'MECHANICAL', USER_4 = 'Greg Hartman' where id = 'P2M1-AS-MECH'
update shop_resource set USER_2 = 'ASSEMBLY', USER_3 = 'RIVETING', USER_4 = 'Greg Hartman' where id = 'P2M1-AS-RIVET'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where id = 'P3M1-AS'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where id = 'P3M1-AS-BOND'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where id = 'P3M1-AS-BUSH'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where id = 'P3M1-AS-DRILL'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where id = 'P3M1-AS-DRV-CMP'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where id = 'P3M1-AS-MECH'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where id = 'P3M1-AS-RIVET'
update shop_resource set USER_2 = 'DEBURR', USER_3 = 'DEBURR', USER_4 = 'Jacob Helle' where id = 'P2M1-DB-DBR'
update shop_resource set USER_2 = 'DEBURR', USER_3 = 'VIBRA DEBURR', USER_4 = 'Jacob Helle' where id = 'P2M1-DB-VIBRA'
update shop_resource set USER_2 = 'FORMING', USER_3 = 'BRAKEFORM', USER_4 = 'Jacob Helle' where id = 'P2M1-FM-BRAKE'
update shop_resource set USER_2 = 'FORMING', USER_3 = 'BUFFALO ROLLER', USER_4 = 'Jacob Helle' where id = 'P2M1-FM-BUFROLL'
update shop_resource set USER_2 = 'FORMING', USER_3 = 'HYDROFORM', USER_4 = 'Jacob Helle' where id = 'P2M1-FM-HYDRO'
update shop_resource set USER_2 = 'FORMING', USER_3 = 'HOT JOGGLE', USER_4 = 'Jacob Helle' where id = 'P2M1-FM-JOGGLE'
update shop_resource set USER_2 = 'FORMING', USER_3 = 'ROLLER', USER_4 = 'Jacob Helle' where id = 'P2M1-FM-ROLL'
update shop_resource set USER_2 = 'FORMING', USER_3 = 'STRAIGHTENING', USER_4 = 'Jacob Helle' where id = 'P2M1-FM-STRAIGH'
update shop_resource set USER_2 = 'SHEET METAL', USER_3 = 'NOTCHER', USER_4 = 'Jacob Helle' where id = 'P2M1-SM-NOTCHER'
update shop_resource set USER_2 = 'SHEET METAL', USER_3 = 'PUNCH PRESS', USER_4 = 'Jacob Helle' where id = 'P2M1-SM-PRESS'
update shop_resource set USER_2 = 'SHEET METAL', USER_3 = 'SHEAR', USER_4 = 'Jacob Helle' where id = 'P2M1-SM-SHEAR'
update shop_resource set USER_2 = 'SHEET METAL', USER_3 = 'TIMESAVER', USER_4 = 'Jacob Helle' where id = 'P2M1-SM-TIMESVR'
update shop_resource set USER_2 = 'SHEET METAL', USER_3 = 'TURRET PUNCH', USER_4 = 'Jacob Helle' where id = 'P2M1-SM-TPUNCH'
update shop_resource set USER_2 = 'SHEET METAL', USER_3 = 'WATERJET', USER_4 = 'Jacob Helle' where id = 'P2M1-SM-WTRJET'
update shop_resource set USER_2 = 'SHEET METAL', USER_3 = 'WATERJET', USER_4 = 'Jacob Helle' where id = 'P2M2-SM-WTRJET'
update shop_resource set USER_2 = 'CNC', USER_3 = 'VF 12', USER_4 = 'Jason Rice' where id = 'P2M1-CNC-12'
update shop_resource set USER_2 = 'CNC', USER_3 = 'VF 3', USER_4 = 'Jason Rice' where id = 'P2M1-CNC-3'
update shop_resource set USER_2 = 'CNC', USER_3 = 'VF 4', USER_4 = 'Jason Rice' where id = 'P2M1-CNC-4'
update shop_resource set USER_2 = 'CNC', USER_3 = 'DOOSAN', USER_4 = 'Jason Rice' where id = 'P2M1-CNC-5-DOOS'
update shop_resource set USER_2 = 'CNC', USER_3 = 'UMC', USER_4 = 'Jason Rice' where id = 'P2M1-CNC-5-UMC'
update shop_resource set USER_2 = 'CNC', USER_3 = 'VF 6', USER_4 = 'Jason Rice' where id = 'P2M1-CNC-5-VF6'
update shop_resource set USER_2 = 'CNC', USER_3 = 'OKUMA', USER_4 = 'Jason Rice' where id = 'P2M1-CNC-OKUMA'
update shop_resource set USER_2 = 'CNC', USER_3 = 'ROUTER', USER_4 = 'Jason Rice' where id = 'P2M1-CNC-RT'
update shop_resource set USER_2 = 'MANUAL MILL', USER_3 = 'BP', USER_4 = 'Jason Rice' where id = 'P2M1-MACH-BP'
update shop_resource set USER_2 = 'MANUAL MILL', USER_3 = 'HONING', USER_4 = 'Jason Rice' where id = 'P2M1-MACH-HONE'
update shop_resource set USER_2 = 'MANUAL MILL', USER_3 = 'MANUAL LATHE', USER_4 = 'Jason Rice' where id = 'P2M1-MACH-LATHE'
update shop_resource set USER_2 = 'SHEET METAL', USER_3 = 'SAW', USER_4 = 'Jason Rice' where id = 'P2M1-SAW'
update shop_resource set USER_2 = 'PACKAGING', USER_3 = 'PACKAGING', USER_4 = 'Jeff Morgan' where id = 'P1F1-PKG'
update shop_resource set USER_2 = 'PACKAGING', USER_3 = 'SHIPPING', USER_4 = 'Jeff Morgan' where id = 'P1F1-SHIP'
update shop_resource set USER_2 = 'RECEIVING', USER_3 = 'RECEIVING', USER_4 = 'Jeff Morgan' where id = 'P1F1-REC'
update shop_resource set USER_2 = 'RECEIVING', USER_3 = 'REVIEW', USER_4 = 'Jeff Morgan' where id = 'P1F1-REC-PANELS'
update shop_resource set USER_2 = 'PLANNING', USER_3 = 'PLANNING', USER_4 = 'Jeff Thiessen' where id = 'P1F1-PLAN'
update shop_resource set USER_2 = 'PLANNING', USER_3 = 'REVIEW', USER_4 = 'Jeff Thiessen' where id = 'P1F1-REVIEW'
update shop_resource set USER_2 = 'PLANNING', USER_3 = 'REVIEW', USER_4 = 'Jeff Thiessen' where id = 'P1F1-REVIEWCM'
update shop_resource set USER_2 = 'PLANNING', USER_3 = 'REVIEW', USER_4 = 'Jeff Thiessen' where id = 'P1F2-REVIEWCM'
update shop_resource set USER_2 = 'PACKAGING', USER_3 = 'PACKAGING', USER_4 = 'Jessica Eastman' where id = 'P2M1-PKG'
update shop_resource set USER_2 = 'PACKAGING', USER_3 = 'BOEING', USER_4 = 'Jessica Eastman' where id = 'P2M1-PKG-BOE'
update shop_resource set USER_2 = 'PART MARK', USER_3 = 'PART MARK', USER_4 = 'Jessica Eastman' where id = 'P2M1-PM'
update shop_resource set USER_2 = 'PAINT', USER_3 = 'OVEN', USER_4 = 'Jimmy Spears' where id = 'P1F1-OVEN-TC'
update shop_resource set USER_2 = 'PAINT', USER_3 = 'SANDING', USER_4 = 'Jimmy Spears' where id = 'P1F1-PNT-SAND'
update shop_resource set USER_2 = 'PAINT', USER_3 = 'TOPCOAT', USER_4 = 'Jimmy Spears' where id = 'P1F1-PNT-TC'
update shop_resource set USER_2 = 'RAW MATERIAL', USER_3 = 'STORES', USER_4 = 'Justin Rhett' where id = 'P2M1-RLSMTL'
update shop_resource set USER_2 = 'RECEIVING', USER_3 = 'RECEIVING', USER_4 = 'Justin Rhett' where id = 'P2M1-REC'
update shop_resource set USER_2 = 'SHIPPING', USER_3 = 'SHIPPING', USER_4 = 'Justin Rhett' where id = 'P2M1-SHIP'
update shop_resource set USER_2 = 'MASKING', USER_3 = 'RIB KIT', USER_4 = 'Kelsey Morgan' where id = 'P1F1-MASK-RIB'
update shop_resource set USER_2 = 'CMP', USER_3 = 'PACKAGING', USER_4 = 'Larissa Brandenburg' where id = 'P1F2-PKG-CMP'
update shop_resource set USER_2 = 'CMP', USER_3 = 'PART MARK', USER_4 = 'Larissa Brandenburg' where id = 'P1F2-PM-CMP'
update shop_resource set USER_2 = 'CMP', USER_3 = 'SHIPPING', USER_4 = 'Larissa Brandenburg' where id = 'P1F2-SHIP-CMP'
update shop_resource set USER_2 = 'CMP', USER_3 = 'TAKEDOWN', USER_4 = 'Larissa Brandenburg' where id = 'P1F2-TKDWN-CMP'
update shop_resource set USER_2 = 'CMP', USER_3 = 'FINAL', USER_4 = 'Larissa Brandenburg' where id = 'P1F2-IN-FNL-CMP'
update shop_resource set USER_2 = 'MASKING', USER_3 = 'MASKING', USER_4 = 'Larissa Brandenburg' where id = 'P1F1-MASK'
update shop_resource set USER_2 = 'PART MARK', USER_3 = 'PART MARK', USER_4 = 'Larissa Brandenburg' where id = 'P1F1-PM'
update shop_resource set USER_2 = 'TAKEDOWN', USER_3 = 'TAKEDOWN', USER_4 = 'Larissa Brandenburg' where id = 'P1F1-TKDWN'
update shop_resource set USER_2 = 'CARGO ', USER_3 = 'INSPECTION', USER_4 = 'Lorie Bourke' where id = 'P1F1-CP-INSP'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'CERTFICATION', USER_4 = 'Lorie Bourke' where id = 'P1F1-IN-CERT'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'EDDY CURRENT', USER_4 = 'Lorie Bourke' where id = 'P1F1-IN-EDCUR'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'FINISH', USER_4 = 'Lorie Bourke' where id = 'P1F1-IN-FINSH'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'FINAL', USER_4 = 'Lorie Bourke' where id = 'P1F1-IN-FNL'
update shop_resource set USER_2 = 'INSPECTION', USER_3 = 'FINISH', USER_4 = 'Lorie Bourke' where id = 'P1F1-IN-WET'
update shop_resource set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CHEMICAL CONVERSION', USER_4 = 'Mike Baker' where id = 'P1F1-CHCNV-1500'
update shop_resource set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'BORIC', USER_4 = 'Mike Baker' where id = 'P1F1-ANO-BORIC'
update shop_resource set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CHROMIC', USER_4 = 'Mike Baker' where id = 'P1F1-ANO-CHROME'
update shop_resource set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'SULFURIC', USER_4 = 'Mike Baker' where id = 'P1F1-ANO-SULF'
update shop_resource set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CLEAN', USER_4 = 'Mike Baker' where id = 'P1F1-CH-CLEAN'
update shop_resource set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CHEMICAL CONVERSION', USER_4 = 'Mike Baker' where id = 'P1F1-CHCNV-1000'
update shop_resource set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CHEMICAL CONVERSION', USER_4 = 'Mike Baker' where id = 'P1F1-CHCNV-1200'
update shop_resource set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CHEMICAL CONVERSION', USER_4 = 'Mike Baker' where id = 'P1F1-CHCNV-600'
update shop_resource set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CLEAN', USER_4 = 'Mike Baker' where id = 'P1F1-CH-EMU'
update shop_resource set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CLEAN', USER_4 = 'Mike Baker' where id = 'P1F1-CH-ETCH'
update shop_resource set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'RACK', USER_4 = 'Mike Baker' where id = 'P1F1-CH-RACK'
update shop_resource set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'STRIP', USER_4 = 'Mike Baker' where id = 'P1F1-CH-STRIP'
update shop_resource set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'STRIP', USER_4 = 'Mike Baker' where id = 'P1F1-CH-TURCO'
update shop_resource set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'UNRACK', USER_4 = 'Mike Baker' where id = 'P1F1-CH-UNRACK'
update shop_resource set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'SOL GEL', USER_4 = 'Mike Baker' where id = 'P1F1-SOLGEL'
update shop_resource set USER_2 = 'TOOLING', USER_3 = 'TOOLING', USER_4 = 'Richard Shoemaker' where id = 'P2M1-TOOLING'
update shop_resource set USER_2 = 'PENETRANT', USER_3 = 'PENETRANT', USER_4 = 'Shane Eastman' where id = 'P1F1-PEN'
update shop_resource set USER_2 = 'PENETRANT', USER_3 = 'CLEAN', USER_4 = 'Shane Eastman' where id = 'P1F1-PENETCH'
update shop_resource set USER_2 = 'PENETRANT', USER_3 = 'MASKING', USER_4 = 'Shane Eastman' where id = 'P1F1-PEN-MASK'
update shop_resource set USER_2 = 'PAINT', USER_3 = 'OVEN', USER_4 = 'Shane Hassman' where id = 'P1F1-OVEN-PRIME'
update shop_resource set USER_2 = 'PAINT', USER_3 = 'PRIMER', USER_4 = 'Shane Hassman' where id = 'P1F1-PNT-PRIME'
update shop_resource set USER_2 = 'PAINT', USER_3 = 'SETUP', USER_4 = 'Shane Hassman' where id = 'P1F1-PNT-SETUP'
update shop_resource set USER_2 = 'PAINT', USER_3 = 'OVEN', USER_4 = 'Shane Hassman' where id = 'P1F2-OVEN-PRIME'
update shop_resource set USER_2 = 'PAINT', USER_3 = 'PRIMER', USER_4 = 'Shane Hassman' where id = 'P1F2-PNT-PRIME'
update shop_resource set USER_2 = 'PAINT', USER_3 = 'SETUP', USER_4 = 'Shane Hassman' where id = 'P1F2-PNT-SETUP'
update shop_resource set USER_2 = 'CMP', USER_3 = 'PRE-PULL', USER_4 = 'Shannen Helle' where id = 'P2M1-PREPUL-CMP'
update shop_resource set USER_2 = 'CMP', USER_3 = 'PLANNING', USER_4 = 'Shannen Helle' where id = 'P2M1-REVIEW-CMP'
update shop_resource set USER_2 = 'CMP', USER_3 = 'STORES', USER_4 = 'Shannen Helle' where id = 'P2M1-STAGNG-CMP'
update shop_resource set USER_2 = 'CMP', USER_3 = 'STORES', USER_4 = 'Shannen Helle' where id = 'P2M2-KIT-CMP'
update shop_resource set USER_2 = 'CMP', USER_3 = 'STORES', USER_4 = 'Shannen Helle' where id = 'P2M2-RLSMTL-CMP'
update shop_resource set USER_2 = 'PLANNING', USER_3 = 'REVIEW', USER_4 = 'Shannen Helle' where id = 'P2M1-REVIEW'
update shop_resource set USER_2 = 'PLANNING', USER_3 = 'REVIEW', USER_4 = 'Shannen Helle' where id = 'P2M1-REVIEWCM'
update shop_resource set USER_2 = 'PLANNING', USER_3 = 'REVIEW', USER_4 = 'Shannen Helle' where id = 'P2M2-REVIEWCM'
update shop_resource set USER_2 = 'SHOT PEEN', USER_3 = 'AUTO SHOT', USER_4 = 'Sue Hoke' where id = 'P1F1-SP-AUTO'
update shop_resource set USER_2 = 'SHOT PEEN', USER_3 = 'BLASTING', USER_4 = 'Sue Hoke' where id = 'P1F1-SP-BLAST'
update shop_resource set USER_2 = 'SHOT PEEN', USER_3 = 'MANUAL SHOT', USER_4 = 'Sue Hoke' where id = 'P1F1-SP-MANUAL'
update shop_resource set USER_2 = 'DEBURR', USER_3 = 'DEBURR', USER_4 = 'Zebulan Cox' where id = 'P3M1-DB-DBR'
update shop_resource set USER_2 = 'FORMING', USER_3 = 'BLASTING', USER_4 = 'Zebulan Cox' where id = 'P3M1-FM-BLST-AU'
update shop_resource set USER_2 = 'FORMING', USER_3 = 'COLD FORM', USER_4 = 'Zebulan Cox' where id = 'P3M1-FM-CF'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'BLASTING', USER_4 = 'Zebulan Cox' where id = 'P3M1-FM-BLST-MN'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'HOT FORM', USER_4 = 'Zebulan Cox' where id = 'P3M1-FM-HF-LG'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'HOT FORM', USER_4 = 'Zebulan Cox' where id = 'P3M1-FM-HF-MED'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'HOT FORM', USER_4 = 'Zebulan Cox' where id = 'P3M1-FM-HF-SM'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'MANUAL MILL', USER_4 = 'Zebulan Cox' where id = 'P3M1-MACH-BP'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'PART MARK', USER_4 = 'Zebulan Cox' where id = 'P3M1-PM'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'RECEIVING', USER_4 = 'Zebulan Cox' where id = 'P3M1-REC'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'SHIPPING', USER_4 = 'Zebulan Cox' where id = 'P3M1-SHIP'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'BLASTING', USER_4 = 'Zebulan Cox' where id = 'P3M-BLAST'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'BRAKEFORM', USER_4 = 'Zebulan Cox' where id = 'P3M-BRAKE-COLD'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'HOT FORM', USER_4 = 'Zebulan Cox' where id = 'P3M-BRAKE-HOT'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'DEBURR', USER_4 = 'Zebulan Cox' where id = 'P3M-HANDBURR'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'INSPECTION', USER_4 = 'Zebulan Cox' where id = 'P3M-INSP-DIM'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'SHIPPING', USER_4 = 'Zebulan Cox' where id = 'P3M-SHIP'
update shop_resource set USER_2 = 'PLANT THREE', USER_3 = 'WATERJET', USER_4 = 'Zebulan Cox' where id = 'P3M-WATERJET'
update shop_resource set USER_2 = 'SHEET METAL', USER_3 = 'WATERJET', USER_4 = 'Zebulan Cox' where id = 'P3M1-SM-WTRJET'

update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'ANM-abrburr'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'ANM-assembly'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'ANM-brakfrmcold'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'ANM-cncrouter3'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'ANM-cncrouter4'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'ANM-countersink'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'ANM-FINALinsp'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'ANM-fladderburr'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'ANM-handburr'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'ANM-insp'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'ANM-mylar'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'ANM-Review'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'ANM-ship'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'ANM-stores'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-1000'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-600'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-alo'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-ano'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-assembly'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-assyINSP'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-assyPM'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-blast'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-boeingpkg'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-boric'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-cert'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-chemstrip'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-clean'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-eddycur'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-emu'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-etch'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-FINALinsp'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-handburr'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-insp'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-Insp-Cargo'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-mask'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-Mask-Cargo'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-msp'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-Mylar-Cargo'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-NrthMFGinsp'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-oven1'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-ovenPrime'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-ovenTC'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-panel'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-pen'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-PENetch'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-pkg'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-plan'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-pm'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-PM-Cargo'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-pri'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-rack'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-review'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-sand'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-setup'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-ship'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-solgel'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-sp'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-takedown'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-tc'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-tube'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-TurcoClean'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-unrack'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'AUB-verify'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'B1F1-ANO-BORIC'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'B1F1-CHCNV-1000'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'B1F1-CHCNV-1200'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'B1F1-CHCNV-600'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'B1F1-CH-EMU'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'B1F1-ETCH'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'B1F1-POLISH'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'B1F1-RACK'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'B1F1-REVIEW'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'B1F1-SHIP'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'B1F1-SULF'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'B1F1-UNRACK'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-1000'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-600'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-abrburr'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-alo'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-ano'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-blast'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-boeingpkg'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-boric'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-cert'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-emu'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-etch'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-FINALinsp'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-handburr'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-insp'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-mask'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-MFGinsp'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-ovenPrime'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-ovenTC'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-pen'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-PENetch'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-pkg'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-plan'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-pm'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-polish'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-pri'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-rack'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-review'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-sand'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-setup'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-ship'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-sp'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-sulf'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-takedown'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-tc'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-unrack'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'BAL-verify'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'bandsaw'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'boeingpkg'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'boltboard'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'bpmill'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'brakeform'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'buffalo-roller'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'Clean'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'CMM'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'cncdoosan'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'cncmill'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'cncmill-12'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'cncmill-4'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'cncmill-5'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'cncrouter'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'contractor'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'cutoffsaw'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'drill'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'FAI'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'handburr'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'honing'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'hot joggle'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'hydroform'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'insp'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'maint'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'mlathe'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'msp'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'notcher'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'okuma'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'panel'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'pm'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'polish'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'Programming'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'PROGS'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'punch press'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'review'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'rivet'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'rnotcher'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'rwec'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'shear'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'SouthAUB-blast'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'SouthAUB-boepkg'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'SouthAUB-cert'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'SouthAUB-Final'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'SouthAUB-pkg'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'SouthAUB-ship'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'SouthAUB-verify'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'Stores'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'straightening'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'sulf'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'tablesaw'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'Timesaver'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'tooling'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'tpunch'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'vibraburr'
update shop_resource_site set USER_2 = 'ARCHIVED', USER_3 = 'ARCHIVED', USER_4 = 'ARCHIVED' where resource_id = 'Waterjet'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'ASSEMBLY', USER_4 = 'Brian Swartley' where resource_id = 'P2M1-IN-ASSY'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'CMM', USER_4 = 'Brian Swartley' where resource_id = 'P2M1-IN-CMM'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'DIMENSIONAL', USER_4 = 'Brian Swartley' where resource_id = 'P2M1-IN-DIM'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'FAI', USER_4 = 'Brian Swartley' where resource_id = 'P2M1-IN-FAI'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'FINAL', USER_4 = 'Brian Swartley' where resource_id = 'P2M1-IN-FNL'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'OSP', USER_4 = 'Brian Swartley' where resource_id = 'P2M1-IN-OUTFIN'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'ROCKWELL', USER_4 = 'Brian Swartley' where resource_id = 'P2M1-IN-RWEC'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'TOOLING', USER_4 = 'Brian Swartley' where resource_id = 'P2M1-IN-TOOLING'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'DIMENSIONAL', USER_4 = 'Brian Swartley' where resource_id = 'P2M2-IN-DIM-CMP'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'DIMENSIONAL', USER_4 = 'Brian Swartley' where resource_id = 'P3M1-IN-DIM'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'FINAL', USER_4 = 'Brian Swartley' where resource_id = 'P3M1-IN-FNL'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'CMP FINAL', USER_4 = 'Brian Swartley' where resource_id = 'P3M1-IN-FNL-CMP'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'INSPECTION', USER_4 = 'Brian Swartley' where resource_id = 'P3M1-IN-ASSY'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'INSPECTION', USER_4 = 'Brian Swartley' where resource_id = 'P3M1-IN-FAI'
update shop_resource_site set USER_2 = 'RECEIVING', USER_3 = 'PANELS', USER_4 = 'Brian Swartley' where resource_id = 'P2M1-PANEL'
update shop_resource_site set USER_2 = 'CARGO', USER_3 = 'ASSEMBLY', USER_4 = 'Christen Erickson' where resource_id = 'P1M1-CP-AS'
update shop_resource_site set USER_2 = 'CARGO', USER_3 = 'CNC', USER_4 = 'Christen Erickson' where resource_id = 'P1M1-CP-CNC-RT3'
update shop_resource_site set USER_2 = 'CARGO', USER_3 = 'CNC', USER_4 = 'Christen Erickson' where resource_id = 'P1M1-CP-CNC-RT4'
update shop_resource_site set USER_2 = 'CARGO', USER_3 = 'COUNTERSINK', USER_4 = 'Christen Erickson' where resource_id = 'P1M1-CP-CNTRSNK'
update shop_resource_site set USER_2 = 'CARGO', USER_3 = 'FINAL', USER_4 = 'Christen Erickson' where resource_id = 'P1M1-CP-FINAL'
update shop_resource_site set USER_2 = 'CARGO', USER_3 = 'DEBURR', USER_4 = 'Christen Erickson' where resource_id = 'P1M1-CP-FLADDER'
update shop_resource_site set USER_2 = 'CARGO', USER_3 = 'BRAKEFORM', USER_4 = 'Christen Erickson' where resource_id = 'P1M1-CP-FM-RF'
update shop_resource_site set USER_2 = 'CARGO', USER_3 = 'DIMENSIONAL', USER_4 = 'Christen Erickson' where resource_id = 'P1M1-CP-IN-DIM'
update shop_resource_site set USER_2 = 'CARGO', USER_3 = 'MYLAR', USER_4 = 'Christen Erickson' where resource_id = 'P1M1-CP-MYLAR'
update shop_resource_site set USER_2 = 'CARGO', USER_3 = 'REVIEW', USER_4 = 'Christen Erickson' where resource_id = 'P1M1-CP-REVIEW'
update shop_resource_site set USER_2 = 'CARGO', USER_3 = 'RAW MATERIAL', USER_4 = 'Christen Erickson' where resource_id = 'P1M1-CP-RLSMTL'
update shop_resource_site set USER_2 = 'CARGO', USER_3 = 'SHIPPING', USER_4 = 'Christen Erickson' where resource_id = 'P1M1-CP-SHIP'
update shop_resource_site set USER_2 = 'CARGO', USER_3 = 'DEBURR', USER_4 = 'Christen Erickson' where resource_id = 'P1M1-DB-DBR'
update shop_resource_site set USER_2 = 'CARGO ', USER_3 = 'MASKING', USER_4 = 'Christen Erickson' where resource_id = 'P1F1-CP-MASK'
update shop_resource_site set USER_2 = 'CARGO ', USER_3 = 'PART MARK', USER_4 = 'Christen Erickson' where resource_id = 'P1F1-CP-PM'
update shop_resource_site set USER_2 = 'FINISHED GOODS', USER_3 = 'KITTING', USER_4 = 'Christi Morgan' where resource_id = 'P2M1-KIT-FG'
update shop_resource_site set USER_2 = 'PROGRAMMING', USER_3 = 'CNC', USER_4 = 'Creg Crones' where resource_id = 'P2M1-PROG-CNC'
update shop_resource_site set USER_2 = 'PROGRAMMING', USER_3 = 'LATHE', USER_4 = 'Creg Crones' where resource_id = 'P2M1-PROG-LATHE'
update shop_resource_site set USER_2 = 'PROGRAMMING', USER_3 = 'TURRET PUNCH', USER_4 = 'Creg Crones' where resource_id = 'P2M1-PROG-TP'
update shop_resource_site set USER_2 = 'PROGRAMMING', USER_3 = 'WATERJET', USER_4 = 'Creg Crones' where resource_id = 'P2M1-PROG-WJ'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'QP REVIEW', USER_4 = 'Diane Booth' where resource_id = 'P2M1-IN-QPREV'
update shop_resource_site set USER_2 = 'BALLARD', USER_3 = 'BUSINESS SOLUTIONS', USER_4 = 'Dmitriy Mandelman' where resource_id = 'outreach'
update shop_resource_site set USER_2 = 'BALLARD', USER_3 = 'BUSINESS SOLUTIONS', USER_4 = 'Dmitriy Mandelman' where resource_id = 'OUT-review'
update shop_resource_site set USER_2 = 'ASSEMBLY', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where resource_id = 'P2M1-AS'
update shop_resource_site set USER_2 = 'ASSEMBLY', USER_3 = 'BUSHING', USER_4 = 'Greg Hartman' where resource_id = 'P2M1-AS-BUSH'
update shop_resource_site set USER_2 = 'ASSEMBLY', USER_3 = 'DRILLING', USER_4 = 'Greg Hartman' where resource_id = 'P2M1-AS-DRILL'
update shop_resource_site set USER_2 = 'ASSEMBLY', USER_3 = 'MECHANICAL', USER_4 = 'Greg Hartman' where resource_id = 'P2M1-AS-MECH'
update shop_resource_site set USER_2 = 'ASSEMBLY', USER_3 = 'RIVETING', USER_4 = 'Greg Hartman' where resource_id = 'P2M1-AS-RIVET'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where resource_id = 'P3M1-AS'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where resource_id = 'P3M1-AS-BOND'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where resource_id = 'P3M1-AS-BUSH'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where resource_id = 'P3M1-AS-DRILL'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where resource_id = 'P3M1-AS-DRV-CMP'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where resource_id = 'P3M1-AS-MECH'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'ASSEMBLY', USER_4 = 'Greg Hartman' where resource_id = 'P3M1-AS-RIVET'
update shop_resource_site set USER_2 = 'DEBURR', USER_3 = 'DEBURR', USER_4 = 'Jacob Helle' where resource_id = 'P2M1-DB-DBR'
update shop_resource_site set USER_2 = 'DEBURR', USER_3 = 'VIBRA DEBURR', USER_4 = 'Jacob Helle' where resource_id = 'P2M1-DB-VIBRA'
update shop_resource_site set USER_2 = 'FORMING', USER_3 = 'BRAKEFORM', USER_4 = 'Jacob Helle' where resource_id = 'P2M1-FM-BRAKE'
update shop_resource_site set USER_2 = 'FORMING', USER_3 = 'BUFFALO ROLLER', USER_4 = 'Jacob Helle' where resource_id = 'P2M1-FM-BUFROLL'
update shop_resource_site set USER_2 = 'FORMING', USER_3 = 'HYDROFORM', USER_4 = 'Jacob Helle' where resource_id = 'P2M1-FM-HYDRO'
update shop_resource_site set USER_2 = 'FORMING', USER_3 = 'HOT JOGGLE', USER_4 = 'Jacob Helle' where resource_id = 'P2M1-FM-JOGGLE'
update shop_resource_site set USER_2 = 'FORMING', USER_3 = 'ROLLER', USER_4 = 'Jacob Helle' where resource_id = 'P2M1-FM-ROLL'
update shop_resource_site set USER_2 = 'FORMING', USER_3 = 'STRAIGHTENING', USER_4 = 'Jacob Helle' where resource_id = 'P2M1-FM-STRAIGH'
update shop_resource_site set USER_2 = 'SHEET METAL', USER_3 = 'NOTCHER', USER_4 = 'Jacob Helle' where resource_id = 'P2M1-SM-NOTCHER'
update shop_resource_site set USER_2 = 'SHEET METAL', USER_3 = 'PUNCH PRESS', USER_4 = 'Jacob Helle' where resource_id = 'P2M1-SM-PRESS'
update shop_resource_site set USER_2 = 'SHEET METAL', USER_3 = 'SHEAR', USER_4 = 'Jacob Helle' where resource_id = 'P2M1-SM-SHEAR'
update shop_resource_site set USER_2 = 'SHEET METAL', USER_3 = 'TIMESAVER', USER_4 = 'Jacob Helle' where resource_id = 'P2M1-SM-TIMESVR'
update shop_resource_site set USER_2 = 'SHEET METAL', USER_3 = 'TURRET PUNCH', USER_4 = 'Jacob Helle' where resource_id = 'P2M1-SM-TPUNCH'
update shop_resource_site set USER_2 = 'SHEET METAL', USER_3 = 'WATERJET', USER_4 = 'Jacob Helle' where resource_id = 'P2M1-SM-WTRJET'
update shop_resource_site set USER_2 = 'SHEET METAL', USER_3 = 'WATERJET', USER_4 = 'Jacob Helle' where resource_id = 'P2M2-SM-WTRJET'
update shop_resource_site set USER_2 = 'CNC', USER_3 = 'VF 12', USER_4 = 'Jason Rice' where resource_id = 'P2M1-CNC-12'
update shop_resource_site set USER_2 = 'CNC', USER_3 = 'VF 3', USER_4 = 'Jason Rice' where resource_id = 'P2M1-CNC-3'
update shop_resource_site set USER_2 = 'CNC', USER_3 = 'VF 4', USER_4 = 'Jason Rice' where resource_id = 'P2M1-CNC-4'
update shop_resource_site set USER_2 = 'CNC', USER_3 = 'DOOSAN', USER_4 = 'Jason Rice' where resource_id = 'P2M1-CNC-5-DOOS'
update shop_resource_site set USER_2 = 'CNC', USER_3 = 'UMC', USER_4 = 'Jason Rice' where resource_id = 'P2M1-CNC-5-UMC'
update shop_resource_site set USER_2 = 'CNC', USER_3 = 'VF 6', USER_4 = 'Jason Rice' where resource_id = 'P2M1-CNC-5-VF6'
update shop_resource_site set USER_2 = 'CNC', USER_3 = 'OKUMA', USER_4 = 'Jason Rice' where resource_id = 'P2M1-CNC-OKUMA'
update shop_resource_site set USER_2 = 'CNC', USER_3 = 'ROUTER', USER_4 = 'Jason Rice' where resource_id = 'P2M1-CNC-RT'
update shop_resource_site set USER_2 = 'MANUAL MILL', USER_3 = 'BP', USER_4 = 'Jason Rice' where resource_id = 'P2M1-MACH-BP'
update shop_resource_site set USER_2 = 'MANUAL MILL', USER_3 = 'HONING', USER_4 = 'Jason Rice' where resource_id = 'P2M1-MACH-HONE'
update shop_resource_site set USER_2 = 'MANUAL MILL', USER_3 = 'MANUAL LATHE', USER_4 = 'Jason Rice' where resource_id = 'P2M1-MACH-LATHE'
update shop_resource_site set USER_2 = 'SHEET METAL', USER_3 = 'SAW', USER_4 = 'Jason Rice' where resource_id = 'P2M1-SAW'
update shop_resource_site set USER_2 = 'PACKAGING', USER_3 = 'PACKAGING', USER_4 = 'Jeff Morgan' where resource_id = 'P1F1-PKG'
update shop_resource_site set USER_2 = 'PACKAGING', USER_3 = 'SHIPPING', USER_4 = 'Jeff Morgan' where resource_id = 'P1F1-SHIP'
update shop_resource_site set USER_2 = 'RECEIVING', USER_3 = 'RECEIVING', USER_4 = 'Jeff Morgan' where resource_id = 'P1F1-REC'
update shop_resource_site set USER_2 = 'RECEIVING', USER_3 = 'REVIEW', USER_4 = 'Jeff Morgan' where resource_id = 'P1F1-REC-PANELS'
update shop_resource_site set USER_2 = 'PLANNING', USER_3 = 'PLANNING', USER_4 = 'Jeff Thiessen' where resource_id = 'P1F1-PLAN'
update shop_resource_site set USER_2 = 'PLANNING', USER_3 = 'REVIEW', USER_4 = 'Jeff Thiessen' where resource_id = 'P1F1-REVIEW'
update shop_resource_site set USER_2 = 'PLANNING', USER_3 = 'REVIEW', USER_4 = 'Jeff Thiessen' where resource_id = 'P1F1-REVIEWCM'
update shop_resource_site set USER_2 = 'PLANNING', USER_3 = 'REVIEW', USER_4 = 'Jeff Thiessen' where resource_id = 'P1F2-REVIEWCM'
update shop_resource_site set USER_2 = 'PACKAGING', USER_3 = 'PACKAGING', USER_4 = 'Jessica Eastman' where resource_id = 'P2M1-PKG'
update shop_resource_site set USER_2 = 'PACKAGING', USER_3 = 'BOEING', USER_4 = 'Jessica Eastman' where resource_id = 'P2M1-PKG-BOE'
update shop_resource_site set USER_2 = 'PART MARK', USER_3 = 'PART MARK', USER_4 = 'Jessica Eastman' where resource_id = 'P2M1-PM'
update shop_resource_site set USER_2 = 'PAINT', USER_3 = 'OVEN', USER_4 = 'Jimmy Spears' where resource_id = 'P1F1-OVEN-TC'
update shop_resource_site set USER_2 = 'PAINT', USER_3 = 'SANDING', USER_4 = 'Jimmy Spears' where resource_id = 'P1F1-PNT-SAND'
update shop_resource_site set USER_2 = 'PAINT', USER_3 = 'TOPCOAT', USER_4 = 'Jimmy Spears' where resource_id = 'P1F1-PNT-TC'
update shop_resource_site set USER_2 = 'RAW MATERIAL', USER_3 = 'STORES', USER_4 = 'Justin Rhett' where resource_id = 'P2M1-RLSMTL'
update shop_resource_site set USER_2 = 'RECEIVING', USER_3 = 'RECEIVING', USER_4 = 'Justin Rhett' where resource_id = 'P2M1-REC'
update shop_resource_site set USER_2 = 'SHIPPING', USER_3 = 'SHIPPING', USER_4 = 'Justin Rhett' where resource_id = 'P2M1-SHIP'
update shop_resource_site set USER_2 = 'MASKING', USER_3 = 'RIB KIT', USER_4 = 'Kelsey Morgan' where resource_id = 'P1F1-MASK-RIB'
update shop_resource_site set USER_2 = 'CMP', USER_3 = 'PACKAGING', USER_4 = 'Larissa Brandenburg' where resource_id = 'P1F2-PKG-CMP'
update shop_resource_site set USER_2 = 'CMP', USER_3 = 'PART MARK', USER_4 = 'Larissa Brandenburg' where resource_id = 'P1F2-PM-CMP'
update shop_resource_site set USER_2 = 'CMP', USER_3 = 'SHIPPING', USER_4 = 'Larissa Brandenburg' where resource_id = 'P1F2-SHIP-CMP'
update shop_resource_site set USER_2 = 'CMP', USER_3 = 'TAKEDOWN', USER_4 = 'Larissa Brandenburg' where resource_id = 'P1F2-TKDWN-CMP'
update shop_resource_site set USER_2 = 'CMP', USER_3 = 'FINAL', USER_4 = 'Larissa Brandenburg' where resource_id = 'P1F2-IN-FNL-CMP'
update shop_resource_site set USER_2 = 'MASKING', USER_3 = 'MASKING', USER_4 = 'Larissa Brandenburg' where resource_id = 'P1F1-MASK'
update shop_resource_site set USER_2 = 'PART MARK', USER_3 = 'PART MARK', USER_4 = 'Larissa Brandenburg' where resource_id = 'P1F1-PM'
update shop_resource_site set USER_2 = 'TAKEDOWN', USER_3 = 'TAKEDOWN', USER_4 = 'Larissa Brandenburg' where resource_id = 'P1F1-TKDWN'
update shop_resource_site set USER_2 = 'CARGO ', USER_3 = 'INSPECTION', USER_4 = 'Lorie Bourke' where resource_id = 'P1F1-CP-INSP'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'CERTFICATION', USER_4 = 'Lorie Bourke' where resource_id = 'P1F1-IN-CERT'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'EDDY CURRENT', USER_4 = 'Lorie Bourke' where resource_id = 'P1F1-IN-EDCUR'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'FINISH', USER_4 = 'Lorie Bourke' where resource_id = 'P1F1-IN-FINSH'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'FINAL', USER_4 = 'Lorie Bourke' where resource_id = 'P1F1-IN-FNL'
update shop_resource_site set USER_2 = 'INSPECTION', USER_3 = 'FINISH', USER_4 = 'Lorie Bourke' where resource_id = 'P1F1-IN-WET'
update shop_resource_site set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CHEMICAL CONVERSION', USER_4 = 'Mike Baker' where resource_id = 'P1F1-CHCNV-1500'
update shop_resource_site set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'BORIC', USER_4 = 'Mike Baker' where resource_id = 'P1F1-ANO-BORIC'
update shop_resource_site set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CHROMIC', USER_4 = 'Mike Baker' where resource_id = 'P1F1-ANO-CHROME'
update shop_resource_site set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'SULFURIC', USER_4 = 'Mike Baker' where resource_id = 'P1F1-ANO-SULF'
update shop_resource_site set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CLEAN', USER_4 = 'Mike Baker' where resource_id = 'P1F1-CH-CLEAN'
update shop_resource_site set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CHEMICAL CONVERSION', USER_4 = 'Mike Baker' where resource_id = 'P1F1-CHCNV-1000'
update shop_resource_site set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CHEMICAL CONVERSION', USER_4 = 'Mike Baker' where resource_id = 'P1F1-CHCNV-1200'
update shop_resource_site set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CHEMICAL CONVERSION', USER_4 = 'Mike Baker' where resource_id = 'P1F1-CHCNV-600'
update shop_resource_site set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CLEAN', USER_4 = 'Mike Baker' where resource_id = 'P1F1-CH-EMU'
update shop_resource_site set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'CLEAN', USER_4 = 'Mike Baker' where resource_id = 'P1F1-CH-ETCH'
update shop_resource_site set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'RACK', USER_4 = 'Mike Baker' where resource_id = 'P1F1-CH-RACK'
update shop_resource_site set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'STRIP', USER_4 = 'Mike Baker' where resource_id = 'P1F1-CH-STRIP'
update shop_resource_site set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'STRIP', USER_4 = 'Mike Baker' where resource_id = 'P1F1-CH-TURCO'
update shop_resource_site set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'UNRACK', USER_4 = 'Mike Baker' where resource_id = 'P1F1-CH-UNRACK'
update shop_resource_site set USER_2 = 'CHEMICAL PROCESSING', USER_3 = 'SOL GEL', USER_4 = 'Mike Baker' where resource_id = 'P1F1-SOLGEL'
update shop_resource_site set USER_2 = 'TOOLING', USER_3 = 'TOOLING', USER_4 = 'Richard Shoemaker' where resource_id = 'P2M1-TOOLING'
update shop_resource_site set USER_2 = 'PENETRANT', USER_3 = 'PENETRANT', USER_4 = 'Shane Eastman' where resource_id = 'P1F1-PEN'
update shop_resource_site set USER_2 = 'PENETRANT', USER_3 = 'CLEAN', USER_4 = 'Shane Eastman' where resource_id = 'P1F1-PENETCH'
update shop_resource_site set USER_2 = 'PENETRANT', USER_3 = 'MASKING', USER_4 = 'Shane Eastman' where resource_id = 'P1F1-PEN-MASK'
update shop_resource_site set USER_2 = 'PAINT', USER_3 = 'OVEN', USER_4 = 'Shane Hassman' where resource_id = 'P1F1-OVEN-PRIME'
update shop_resource_site set USER_2 = 'PAINT', USER_3 = 'PRIMER', USER_4 = 'Shane Hassman' where resource_id = 'P1F1-PNT-PRIME'
update shop_resource_site set USER_2 = 'PAINT', USER_3 = 'SETUP', USER_4 = 'Shane Hassman' where resource_id = 'P1F1-PNT-SETUP'
update shop_resource_site set USER_2 = 'PAINT', USER_3 = 'OVEN', USER_4 = 'Shane Hassman' where resource_id = 'P1F2-OVEN-PRIME'
update shop_resource_site set USER_2 = 'PAINT', USER_3 = 'PRIMER', USER_4 = 'Shane Hassman' where resource_id = 'P1F2-PNT-PRIME'
update shop_resource_site set USER_2 = 'PAINT', USER_3 = 'SETUP', USER_4 = 'Shane Hassman' where resource_id = 'P1F2-PNT-SETUP'
update shop_resource_site set USER_2 = 'CMP', USER_3 = 'PRE-PULL', USER_4 = 'Shannen Helle' where resource_id = 'P2M1-PREPUL-CMP'
update shop_resource_site set USER_2 = 'CMP', USER_3 = 'PLANNING', USER_4 = 'Shannen Helle' where resource_id = 'P2M1-REVIEW-CMP'
update shop_resource_site set USER_2 = 'CMP', USER_3 = 'STORES', USER_4 = 'Shannen Helle' where resource_id = 'P2M1-STAGNG-CMP'
update shop_resource_site set USER_2 = 'CMP', USER_3 = 'STORES', USER_4 = 'Shannen Helle' where resource_id = 'P2M2-KIT-CMP'
update shop_resource_site set USER_2 = 'CMP', USER_3 = 'STORES', USER_4 = 'Shannen Helle' where resource_id = 'P2M2-RLSMTL-CMP'
update shop_resource_site set USER_2 = 'PLANNING', USER_3 = 'REVIEW', USER_4 = 'Shannen Helle' where resource_id = 'P2M1-REVIEW'
update shop_resource_site set USER_2 = 'PLANNING', USER_3 = 'REVIEW', USER_4 = 'Shannen Helle' where resource_id = 'P2M1-REVIEWCM'
update shop_resource_site set USER_2 = 'PLANNING', USER_3 = 'REVIEW', USER_4 = 'Shannen Helle' where resource_id = 'P2M2-REVIEWCM'
update shop_resource_site set USER_2 = 'SHOT PEEN', USER_3 = 'AUTO SHOT', USER_4 = 'Sue Hoke' where resource_id = 'P1F1-SP-AUTO'
update shop_resource_site set USER_2 = 'SHOT PEEN', USER_3 = 'BLASTING', USER_4 = 'Sue Hoke' where resource_id = 'P1F1-SP-BLAST'
update shop_resource_site set USER_2 = 'SHOT PEEN', USER_3 = 'MANUAL SHOT', USER_4 = 'Sue Hoke' where resource_id = 'P1F1-SP-MANUAL'
update shop_resource_site set USER_2 = 'DEBURR', USER_3 = 'DEBURR', USER_4 = 'Zebulan Cox' where resource_id = 'P3M1-DB-DBR'
update shop_resource_site set USER_2 = 'FORMING', USER_3 = 'BLASTING', USER_4 = 'Zebulan Cox' where resource_id = 'P3M1-FM-BLST-AU'
update shop_resource_site set USER_2 = 'FORMING', USER_3 = 'COLD FORM', USER_4 = 'Zebulan Cox' where resource_id = 'P3M1-FM-CF'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'BLASTING', USER_4 = 'Zebulan Cox' where resource_id = 'P3M1-FM-BLST-MN'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'HOT FORM', USER_4 = 'Zebulan Cox' where resource_id = 'P3M1-FM-HF-LG'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'HOT FORM', USER_4 = 'Zebulan Cox' where resource_id = 'P3M1-FM-HF-MED'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'HOT FORM', USER_4 = 'Zebulan Cox' where resource_id = 'P3M1-FM-HF-SM'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'MANUAL MILL', USER_4 = 'Zebulan Cox' where resource_id = 'P3M1-MACH-BP'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'PART MARK', USER_4 = 'Zebulan Cox' where resource_id = 'P3M1-PM'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'RECEIVING', USER_4 = 'Zebulan Cox' where resource_id = 'P3M1-REC'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'SHIPPING', USER_4 = 'Zebulan Cox' where resource_id = 'P3M1-SHIP'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'BLASTING', USER_4 = 'Zebulan Cox' where resource_id = 'P3M-BLAST'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'BRAKEFORM', USER_4 = 'Zebulan Cox' where resource_id = 'P3M-BRAKE-COLD'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'HOT FORM', USER_4 = 'Zebulan Cox' where resource_id = 'P3M-BRAKE-HOT'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'DEBURR', USER_4 = 'Zebulan Cox' where resource_id = 'P3M-HANDBURR'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'INSPECTION', USER_4 = 'Zebulan Cox' where resource_id = 'P3M-INSP-DIM'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'SHIPPING', USER_4 = 'Zebulan Cox' where resource_id = 'P3M-SHIP'
update shop_resource_site set USER_2 = 'PLANT THREE', USER_3 = 'WATERJET', USER_4 = 'Zebulan Cox' where resource_id = 'P3M-WATERJET'
update shop_resource_site set USER_2 = 'SHEET METAL', USER_3 = 'WATERJET', USER_4 = 'Zebulan Cox' where resource_id = 'P3M1-SM-WTRJET'
