USE [LIVESupplemental]
GO

CREATE TABLE [dbo].[SKY_Verification](
	[TYPE] [nvarchar](1) NULL,
	[BASE_ID] [nvarchar](20) NULL,
	[LOT_ID] [nvarchar](3) NULL,
	[SPLIT_ID] [nvarchar](3) NULL,
	[SUB_ID] [nvarchar](3) NULL,
) ON [PRIMARY]
GO

SELECT * FROM LIVESupplemental.dbo.[SKY_Verification] 
--> 645 ROWS

SELECT 645 * 3
--> 1935 ROWS

USE LIVE
GO

SELECT O.WORKORDER_TYPE
	, O.WORKORDER_BASE_ID 
	, O.WORKORDER_LOT_ID 
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID 
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.OPERATION_TYPE
	, USER_5
	, CAST(CAST(OB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [OP_BINARY]
	, CAST(CAST(OTB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [OT_BINARY]
	, OB.BITS
	, OB.BITS_LENGTH 
FROM OPERATION O
INNER JOIN LIVESupplemental.dbo.[SKY_Verification] U
	ON O.WORKORDER_TYPE = U.[TYPE]
	AND O.WORKORDER_BASE_ID = U.BASE_ID
	AND O.WORKORDER_LOT_ID = U.LOT_ID
	AND O.WORKORDER_SPLIT_ID = U.SPLIT_ID
	AND O.WORKORDER_SUB_ID = U.SUB_ID
LEFT OUTER JOIN OPERATION_BINARY OB
	ON O.WORKORDER_TYPE = OB.WORKORDER_TYPE 
	AND O.WORKORDER_BASE_ID = OB.WORKORDER_BASE_ID 
	AND O.WORKORDER_LOT_ID = OB.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = OB.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = OB.WORKORDER_SUB_ID
	AND O.SEQUENCE_NO = OB.SEQUENCE_NO
INNER JOIN OPER_TYPE_BINARY OTB
	ON OTB.OPERATION_TYPE_ID = O.OPERATION_TYPE
WHERE O.OPERATION_TYPE LIKE '%SKY%'

