USE LIVE
GO

SELECT * FROM LIVESupplemental.dbo.SKYDROL_Updates U
-- 301 ROWS
--DELETE FROM LIVESupplemental.dbo.SKYDROL_Updates WHERE BASE_ID IN ('272W1511-10' ,'272W1511-3' ,'287W4710-7' ,'343T0048-1' ,'343T0048-2' ,'65B03769-21')

IF OBJECT_ID('tempdb..#T1')IS NOT NULL DROP TABLE #T1

SELECT OB.WORKORDER_TYPE
	, OB.WORKORDER_BASE_ID
	, OB.WORKORDER_LOT_ID
	, OB.WORKORDER_SPLIT_ID
	, OB.WORKORDER_SUB_ID
	, OB.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.OPERATION_TYPE
	, O.[STATUS]
	, CAST(CAST(OB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [BEFORE_OB]
	, CAST(CAST(OTB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [OTB]
	, OTB.BITS AS [OTB_BINARY]
	, OTB.BITS_LENGTH AS [OTB_BITLEN]
INTO #T1
FROM LIVESupplemental.dbo.SKYDROL_Updates U
INNER JOIN OPERATION O
	ON O.WORKORDER_TYPE = U.[TYPE]
	AND O.WORKORDER_BASE_ID = U.BASE_ID
	AND O.WORKORDER_LOT_ID = U.LOT_ID
	AND O.WORKORDER_SPLIT_ID = U.SPLIT_ID
	AND O.WORKORDER_SUB_ID = U.SUB_ID
	AND O.SEQUENCE_NO = U.SEQ_NO
INNER JOIN OPER_TYPE_BINARY OTB
	ON OTB.OPERATION_TYPE_ID = O.OPERATION_TYPE
INNER JOIN OPERATION_BINARY OB
	ON O.WORKORDER_TYPE = OB.WORKORDER_TYPE
	AND O.WORKORDER_BASE_ID = OB.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = OB.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = OB.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = OB.WORKORDER_SUB_ID
	AND O.SEQUENCE_NO = OB.SEQUENCE_NO
WHERE (O.WORKORDER_TYPE = 'M')
	AND OPERATION_TYPE = 'SKY'

SELECT * FROM #T1 ORDER BY WORKORDER_BASE_ID, SEQUENCE_NO

/*
BEGIN TRANSACTION;
UPDATE OB
SET OB.BITS = T.OTB_BINARY
	, OB.BITS_LENGTH = T.OTB_BITLEN
FROM OPERATION_BINARY OB
INNER JOIN #T1 T
	ON OB.WORKORDER_TYPE = T.WORKORDER_TYPE
	AND OB.WORKORDER_BASE_ID = T.WORKORDER_BASE_ID
	AND OB.WORKORDER_LOT_ID	= T.WORKORDER_LOT_ID
	AND OB.WORKORDER_SPLIT_ID = T.WORKORDER_SPLIT_ID
	AND OB.WORKORDER_SUB_ID = T.WORKORDER_SUB_ID
	AND OB.SEQUENCE_NO = T.SEQUENCE_NO
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

SELECT OB.WORKORDER_TYPE
	, OB.WORKORDER_BASE_ID
	, OB.WORKORDER_LOT_ID
	, OB.WORKORDER_SPLIT_ID
	, OB.WORKORDER_SUB_ID
	, OB.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.OPERATION_TYPE
	, O.[STATUS]
	, CAST(CAST(OB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [BEFORE_OB]
	, CAST(CAST(OTB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS [OTB]
	, OTB.BITS AS [OTB_BINARY]
	, OTB.BITS_LENGTH AS [OTB_BITLEN]
FROM LIVESupplemental.dbo.SKYDROL_Updates U
INNER JOIN OPERATION O
	ON O.WORKORDER_TYPE = U.[TYPE]
	AND O.WORKORDER_BASE_ID = U.BASE_ID
	AND O.WORKORDER_LOT_ID = U.LOT_ID
	AND O.WORKORDER_SPLIT_ID = U.SPLIT_ID
	AND O.WORKORDER_SUB_ID = U.SUB_ID
	AND O.SEQUENCE_NO = U.SEQ_NO
INNER JOIN OPER_TYPE_BINARY OTB
	ON OTB.OPERATION_TYPE_ID = O.OPERATION_TYPE
INNER JOIN OPERATION_BINARY OB
	ON O.WORKORDER_TYPE = OB.WORKORDER_TYPE
	AND O.WORKORDER_BASE_ID = OB.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = OB.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = OB.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = OB.WORKORDER_SUB_ID
	AND O.SEQUENCE_NO = OB.SEQUENCE_NO
WHERE (O.WORKORDER_TYPE = 'M')
	AND OPERATION_TYPE = 'SKY'
	AND CAST(CAST(OB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) != CAST(CAST(OTB.BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX))
