USE LIVE
GO

SELECT P.ID AS PART_ID
, P.[STATUS] AS PART_STATUS
FROM PART P
INNER JOIN LIVESUPPLEMENTAL.[dbo].[INSPPM_Parts] PS
ON PS.PARTID = P.ID

SELECT P.ID AS PART_ID
, P.[STATUS] AS PART_STATUS
FROM PART P
INNER JOIN LIVESUPPLEMENTAL.[dbo].[Skydrol_Parts] PS
ON PS.PARTID = P.ID
