USE LIVE
GO

; WITH CTE_START AS
(SELECT CASE
	WHEN RIGHT(COL.CUST_ORDER_ID,3) = 'INV' THEN COL.MISC_REFERENCE
	ELSE ISNULL(COL.PART_ID, COL.MISC_REFERENCE)
END AS PARTID
, CASE
	WHEN RIGHT(COL.CUST_ORDER_ID,3) = 'INV' THEN 'SPIRIT'
	ELSE 'SHIPPED'
END AS CUSTTYPE
, CASE
	WHEN RIGHT(COL.CUST_ORDER_ID,3) = 'INV' THEN CAST(SHIPPED_QTY AS INT) * -1
	ELSE CAST(SHIPPED_QTY AS INT)
END AS INVENTORY
, SL.PACKLIST_ID
, SL.LINE_NO AS SHIPLINE
, SL.SHIPPED_QTY
, SL.TRANSACTION_ID
, SL.SERVICE_CHARGE_ID AS SHIP_CHARGE
, S.SHIPPED_DATE
, S.CREATE_DATE
, S.STATUS AS SHIP_STATUS
, COL.CUST_ORDER_ID
, COL.LINE_NO AS COL_LINE
, COL.PART_ID
--, COL.CUSTOMER_PART_ID
, COL.LINE_STATUS AS COL_STATUS
, COL.ORDER_QTY
, COL.SELLING_UM
, ISNULL(COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) AS DESIRED_SHIP_DATE
, COL.MISC_REFERENCE
, COL.TOTAL_SHIPPED_QTY
, COL.SERVICE_CHARGE_ID
, CO.CUSTOMER_ID
, CO.CUSTOMER_PO_REF
, CO.ORDER_DATE
, CO.STATUS AS CO_STATUS
FROM SHIPPER_LINE SL
INNER JOIN SHIPPER S
ON SL.PACKLIST_ID = S.PACKLIST_ID
LEFT OUTER JOIN CUST_ORDER_LINE COL
ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
LEFT OUTER JOIN CUSTOMER_ORDER CO
ON CO.ID = COL.CUST_ORDER_ID
WHERE CO.CUSTOMER_ID = 'SPIAER'
AND COL.SERVICE_CHARGE_ID IS NULL
--> AND COL.MISC_REFERENCE NOT LIKE '%NRE%'
)

, CTE_NEXT AS
(SELECT PARTID
, CUSTTYPE
, SUM(INVENTORY) AS INVENTORY
FROM CTE_START
GROUP BY PARTID, CUSTTYPE
)

SELECT * INTO #T1 FROM CTE_NEXT

SELECT * FROM #T1

SELECT PARTID
, SUM(INVENTORY) AS INVENTORY
FROM #T1
GROUP BY PARTID

