-->SELECT * FROM #T1 ORDER BY RESOURCE_ID

SELECT *
FROM (SELECT CASE 
		WHEN ISNULL(USER_1, '') = '' THEN 'SK_TYPE BLANK'
		ELSE NULL
	END AS ERROR_MESS01
	, CASE 
		WHEN ISNULL(SETUP_COST_PER_HR, 0) <> ISNULL(R_SETUP_COST_PER_HR, 0) THEN 'SETUP_COSTS ISSUES'
		ELSE NULL
	END AS ERROR_MESS02
	, CASE 
		WHEN ISNULL(RUN_COST_PER_HR, 0) <> ISNULL(R_RUN_COST_PER_HR, 0) THEN 'RUN_COSTS ISSUES'
		ELSE NULL
	END AS ERROR_MESS03
	, CASE 
		WHEN ISNULL(BUR_PERCENT_SETUP, 0) <> R_BUR_PERCENT_SETUP THEN 'BUR SETUP ISSUES'
		ELSE NULL
	END AS ERROR_MESS04
	, CASE 
		WHEN ISNULL(BUR_PERCENT_RUN, 0) <> R_BUR_PERCENT_RUN THEN 'BUR RUN ISSUES'
		ELSE NULL
	END AS ERROR_MESS05
	, CASE 
		WHEN ISNULL(AFC_GL_ACCT_ID, 0) <> R_AFC_GL_ACCT_ID THEN 'AFC_GL ISSUES'
		ELSE NULL
	END AS ERROR_MESS06
	, CASE 
		WHEN ISNULL(AFB_GL_ACCT_ID, 0) <> R_AFB_GL_ACCT_ID THEN 'AFB_GL ISSUES'
		ELSE NULL
	END AS ERROR_MESS07
--> VALID SUPERVISOR
	, CASE 
		WHEN ISNULL(USER_4, '') <> ISNULL(FL_SUPV, '') THEN 'FL_SUPV ISSUES'
		ELSE NULL
	END AS ERROR_MESS08
	, CASE 
		WHEN COALESCE(USER_1, USER_2, USER_3, USER_4, USER_5, USER_6, USER_7, USER_8, USER_9, USER_10, '') = '' THEN 'USER FLD ISSUES'
		ELSE NULL
	END AS ERROR_MESS09
	, CASE 
		WHEN ISNULL(SKILLS_TYPE, '') = '' THEN 'SKILLS_TYPE BLANK'
		WHEN ISNULL([STATUS], '') = '' THEN 'STATUS BLANK'
		ELSE NULL
	END AS ERROR_MESS10
	, CASE 
		WHEN ISNULL(USER_10, '') NOT IN ('1.73', '') THEN 'USER_10 ISSUE'
		WHEN ISNULL(USER_9, '') NOT IN ('BOE BILLING EXCLUDE', 'BOE BILLING INCLUDE', '') THEN 'USER_9 ISSUE'
		ELSE NULL
	END AS ERROR_MESS11
	, CASE 
		WHEN USER_1 != SKILLS_TYPE THEN 'SKILLS_TYPE ISSUE'
		ELSE NULL
	END AS ERROR_MESS12
	, CASE 
		WHEN ISNULL(USER_1, '') = 'B' AND ISNULL([STATUS], '') != 'O' THEN 'BALLARD ID ACTIVE'
		WHEN ISNULL([DESCRIPTION], '') LIKE '%DO NOT USE%' AND ISNULL([STATUS], '') != 'O' THEN 'DESC/STATUS ISSUE'
		ELSE NULL
	END AS ERROR_MESS13
	, T.*
FROM (SELECT SR.RESOURCE_ID
		, SR.[STATUS]
		, SR.[DESCRIPTION]
		, R.[BUSINESS_ENTITY]
		, SR.SKILLS_TYPE
		, SR.USER_1
		, SR.USER_2
		, SR.USER_3
		, SR.USER_4
		, EE.FIRST_NAME + ' ' + EE.LAST_NAME AS FL_SUPV
		, SR.USER_5
		, SR.USER_6
		, SR.USER_7
		, SR.USER_8
		, SR.USER_9
		, SR.USER_10
		, SR.SETUP_COST_PER_HR
		, R.[SETUP_COST_PER_HR] AS R_SETUP_COST_PER_HR
		, SR.RUN_COST_PER_HR
		, R.[RUN_COST_PER_HR] AS R_RUN_COST_PER_HR
		, SR.BUR_PERCENT_SETUP
		, R.[BUR_PERCENT_SETUP] AS R_BUR_PERCENT_SETUP
		, SR.BUR_PERCENT_RUN
		, R.[BUR_PERCENT_RUN] AS R_BUR_PERCENT_RUN
		, SR.AFC_GL_ACCT_ID
		, R.[AFC_GL_ACCT_ID] AS R_AFC_GL_ACCT_ID
		, SR.AFB_GL_ACCT_ID
		, R.[AFB_GL_ACCT_ID] AS R_AFB_GL_ACCT_ID
	FROM SHOP_RESOURCE_SITE_VIEW SR
	LEFT OUTER JOIN LIVESupplemental..RATES R
		ON SR.USER_1 = R.SKILLS_TYPE
		AND R.[STARTDATEOFRATE] <= GETDATE()
		AND R.[ENDDATEOFRATE] > GETDATE()
	LEFT OUTER JOIN EMPLOYEE EE
		ON SR.USER_4 = EE.FIRST_NAME + ' ' + EE.LAST_NAME
	WHERE SR.RESOURCE_ID NOT IN ('CONTRACTOR', 'TIMEKEEPING')
		AND SR.RESOURCE_ID NOT LIKE 'ANM-%'
		AND SR.RESOURCE_ID NOT LIKE 'ARL-%'
		AND ([STATUS] != 'O' OR [STATUS] IS NULL)
	) T
) X
WHERE COALESCE(ERROR_MESS01, ERROR_MESS02, ERROR_MESS03, ERROR_MESS04, ERROR_MESS05, ERROR_MESS06, ERROR_MESS07, ERROR_MESS08, 
	 ERROR_MESS09, ERROR_MESS10, ERROR_MESS11, ERROR_MESS12, ERROR_MESS13) != ''
