USE DataWarehouse
GO

SELECT WO.BASE_ID
, WO.LOT_ID
, WO.SUB_ID
, WO.PART_ID
, P.[DESCRIPTION]
, ISNULL(dbo.sfn_remaining_operations(wo.[TYPE], wo.BASE_ID, wo.LOT_ID, wo.SPLIT_ID, wo.SUB_ID), N'No Remaining Operations') AS RESOURCE_IDS
FROM PART P
LEFT OUTER JOIN WORK_ORDER WO
ON WO.PART_ID = P.ID
--LEFT OUTER JOIN OPERATION O
--ON WO.BASE_ID = O.WORKORDER_BASE_ID
--AND WO.LOT_ID = O.WORKORDER_LOT_ID
--AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
--AND WO.SUB_ID = O.WORKORDER_SUB_ID
--AND WO.[TYPE] = O.WORKORDER_TYPE

WHERE (P.[DESCRIPTION] LIKE '%STANCHION%' 
OR P.USER_9 LIKE '%STANCHION%')
AND WO.[TYPE] = 'M'
