USE LIVE
GO

--ANY PART THAT IS STOCKED SHOULD BE INSP REQD
SELECT ID
, STOCKED
, INSPECTION_REQD
FROM PART
WHERE ([STATUS] = 'A' OR [STATUS] IS NULL)
AND STOCKED = 'Y'
AND INSPECTION_REQD != 'Y'

SELECT PART_ID
, STOCKED
, INSPECTION_REQD
FROM PART_SITE
WHERE ([STATUS] = 'A' OR [STATUS] IS NULL)
AND STOCKED = 'Y'
AND INSPECTION_REQD != 'Y'

/*
UPDATE PART
SET INSPECTION_REQD = 'Y'
WHERE (STATUS = 'A' OR STATUS IS NULL) 
AND STOCKED = 'Y'

UPDATE PART_SITE
SET INSPECTION_REQD = 'Y'
WHERE (STATUS = 'A' OR STATUS IS NULL) 
AND STOCKED = 'Y'

*/


-- CONSUMABLE PARTS WITH INSPECTION REQD
SELECT ID
, CONSUMABLE
, INSPECTION_REQD
FROM PART
WHERE [STATUS] = 'A' 
AND CONSUMABLE = 'Y'
AND INSPECTION_REQD = 'Y'

SELECT PART_ID
, CONSUMABLE
, INSPECTION_REQD
FROM PART_SITE
WHERE [STATUS] = 'A' 
AND CONSUMABLE = 'Y'
AND INSPECTION_REQD = 'Y'

/*
UPDATE PART
SET INSPECTION_REQD = 'N'
WHERE (STATUS = 'A' OR STATUS IS NULL) 
AND CONSUMABLE = 'Y'

UPDATE PART_SITE
SET INSPECTION_REQD = 'N'
WHERE (STATUS = 'A' OR STATUS IS NULL) 
AND CONSUMABLE = 'Y'

*/
