SELECT 'EXEC MSDB.DBO.SP_START_JOB @job_name = ''' + CAST(J.NAME AS VARCHAR(40)) + '''' as [Exec]
	, CAT.PATH
	, CAT.NAME
	, S.DESCRIPTION
	, JS.LAST_RUN_DATE
	, JS.LAST_RUN_TIME
	, LASTSTATUS 
FROM 
	MSDB.dbo.SYSJOBS J  
JOIN  
	MSDB.dbo.SYSJOBSTEPS JS 
	ON JS.JOB_ID = J.JOB_ID 
JOIN  
	[REPORTSERVER].dbo.[SUBSCRIPTIONS] S  
	ON JS.COMMAND LIKE '%' + CAST(S.SUBSCRIPTIONID AS VARCHAR(40)) + '%' 
JOIN 
	[REPORTSERVER].[DBO].CATALOG AS CAT 
	ON CAT.ITEMID = S.REPORT_OID 
WHERE   
	LEFT(LASTSTATUS, 12) <> 'MAIL SENT TO'
	AND LEFT(LASTSTATUS, 8) <> 'DISABLED'
	AND LEFT(LASTSTATUS, 23) <> 'CACHE REFRESH SUCCEEDED'
	AND LEFT(LASTSTATUS, 22) <> 'Completed Data Refresh'
	AND LEFT(LASTSTATUS, 24) <> 'New Cache Refresh Plan'
	AND LEFT(LASTSTATUS, 17) <> 'New Subscription'
	AND LEFT(LASTSTATUS, 5) NOT IN ('READY', 'DONE:')
	AND LASTSTATUS NOT IN ('Saving model to the catalog', 'Refreshing data', 'Thread was being aborted.')
	AND LEFT(S.[DESCRIPTION],9) <> 'Wallboard'
