USE DataWarehouse
GO

--WHERE POL.PURC_ORDER_ID = '144553'

DECLARE @ENDDATE DATE = CAST(DATEADD(DD, -DAY(GETDATE()), GETDATE()) AS DATE)
, @STARTDATE DATE 

SELECT @STARTDATE = CAST(DATEADD(YEAR, -3, @ENDDATE) AS DATE)

; WITH CTE_PO AS
(SELECT PO.VENDOR_ID
	, POL.PURC_ORDER_ID
	, POL.LINE_NO AS POL_LINE
	, RL.RECEIVER_ID
	, RL.LINE_NO AS RCV_LINE
	, ISNULL(COALESCE(POL.PART_ID, POL.USER_1, POL.VENDOR_PART_ID), '') AS PART_ID
	, PO.[STATUS] AS PO_STATUS
	, ISNULL(POL.DESIRED_RECV_DATE, PO.DESIRED_RECV_DATE) AS DESIRED_RECV_DATE
	, R.RECEIVED_DATE
	, RL.RECEIVED_QTY
FROM RECEIVER R
LEFT OUTER JOIN RECEIVER_LINE RL
	ON R.ID = RL.RECEIVER_ID
LEFT OUTER JOIN PURC_ORDER_LINE POL
	ON RL.PURC_ORDER_ID = POL.PURC_ORDER_ID
	AND RL.PURC_ORDER_LINE_NO = POL.LINE_NO
LEFT OUTER JOIN PURCHASE_ORDER PO
	ON PO.ID = POL.PURC_ORDER_ID
WHERE R.RECEIVED_DATE >= @STARTDATE
	AND R.RECEIVED_DATE <= @ENDDATE
)
--SELECT * FROM CTE_PO WHERE PURC_ORDER_ID = '117306'

, CTE_RECEIVED AS
(SELECT VENDOR_ID
	, PURC_ORDER_ID
	, POL_LINE
	, PART_ID
	, MAX(DESIRED_RECV_DATE) AS DESIRED_RECV_DATE
	, MAX(RECEIVED_DATE) AS RECEIVED_DATE
	, SUM(RECEIVED_QTY) AS RECEIVED_QTY
FROM CTE_PO
GROUP BY VENDOR_ID
	, PURC_ORDER_ID
	, POL_LINE
	, PART_ID
)
--SELECT * FROM CTE_RECEIVED

, CTE_ONTIME AS
(SELECT VENDOR_ID
	, PURC_ORDER_ID
	, POL_LINE
	, PART_ID
	, DESIRED_RECV_DATE
	, RECEIVED_DATE
	, RECEIVED_QTY
	, CONVERT(DATE, DESIRED_RECV_DATE + 5, 101) AS DUE_DATE
	, CASE 
		WHEN RECEIVED_DATE <= DESIRED_RECV_DATE + 5 THEN 1
		ELSE 0
	END AS ONTIME
	, CASE 
		WHEN RECEIVED_DATE <= DESIRED_RECV_DATE + 5 THEN 0
		ELSE 1
	END AS LATE
	, 1 AS LINE_TOTALS
FROM CTE_RECEIVED
)
--SELECT * FROM CTE_ONTIME WHERE PURC_ORDER_ID = '144553' ORDER BY PURC_ORDER_ID, POL_LINE

, CTE_NCM AS
(SELECT CASE 
		WHEN CHARINDEX('/', NCM.PO_NUMBER,1) = 0 THEN NCM.PO_NUMBER
		ELSE SUBSTRING(NCM.PO_NUMBER, 1, CHARINDEX('/', NCM.PO_NUMBER, 1) -1)
	END AS PURC_ORDER_ID
	, ISNULL(VP.PRODUCT_ID, '') AS PART_ID
	, PO.VENDOR_ID
	, NCM.NCM_ID + ' ('+ NCM.PO_NUMBER + ') ' + CASE 
		WHEN VPO.ALT_ID_2 IS NOT NULL THEN 'WO CONTRACTOR'
		ELSE 'PURCHASE'
	END AS NCM_INFO
	, NCM.NCM_DATE
	, ISNULL(NCM.REJECTED, 0) AS REJECTED_QTY
FROM VQ_NONCONFORMANCE NCM
LEFT OUTER JOIN VQ_PRODUCT VP
	ON VP.RECORD_ID = NCM.PRODUCT_REC_ID
LEFT OUTER JOIN VQ_PRODUCTION_ORDER VPO
	ON VPO.RECORD_ID = NCM.PROD_ORDER_REC_ID
LEFT OUTER JOIN PURCHASE_ORDER PO
	ON PO.ID = CASE 
		WHEN CHARINDEX('/', NCM.PO_NUMBER,1) = 0 THEN NCM.PO_NUMBER
		ELSE SUBSTRING(NCM.PO_NUMBER, 1, CHARINDEX('/', NCM.PO_NUMBER, 1) -1)
	END
WHERE NCM.NCM_TYPE = 'SUPPLIER - MAJOR'
	AND PO.ID IS NOT NULL
	AND NCM.PO_NUMBER IS NOT NULL
)
--SELECT * FROM CTE_NCM

, CTE_MERGE AS
(SELECT VENDOR_ID
	, CONVERT(DATE, DESIRED_RECV_DATE + 5, 101) AS DUE_DATE
	, CONVERT(NVARCHAR,LEFT(CONVERT(VARCHAR, DESIRED_RECV_DATE + 5, 112), 6)) AS YYYYMM
	, PURC_ORDER_ID
	, POL_LINE
	, PART_ID
	, DESIRED_RECV_DATE
	, RECEIVED_DATE
	, RECEIVED_QTY
	, NULL AS NCM_INFO
	, 0 AS REJECTED_QTY
	, SUM(ONTIME) AS ONTIME
	, SUM(LATE) AS LATE
	, SUM(LINE_TOTALS) AS LINE_TOTALS
FROM CTE_ONTIME
GROUP BY VENDOR_ID
	, CONVERT(DATE, DESIRED_RECV_DATE + 5, 101)
	, CONVERT(NVARCHAR,LEFT(CONVERT(VARCHAR, DESIRED_RECV_DATE + 5, 112), 6))
	, PURC_ORDER_ID
	, POL_LINE
	, PART_ID
	, DESIRED_RECV_DATE
	, RECEIVED_DATE
	, RECEIVED_QTY
UNION 
SELECT VENDOR_ID
	, CONVERT(DATE, NCM_DATE, 101) AS DUE_DATE
	, CONVERT(NVARCHAR,LEFT(CONVERT(VARCHAR, NCM_DATE, 112), 6)) AS YYYYMM
	, PURC_ORDER_ID
	, 0 AS POL_LINE
	, PART_ID
	, 0 AS DESIRED_RECV_DATE
	, 0 AS RECEIVED_DATE
	, 0 AS RECEIVED_QTY
	, NCM_INFO
	, SUM(REJECTED_QTY) AS REJECTED_QTY
	, 0 AS ONTIME
	, 0 AS LATE
	, 0 AS LINE_TOTALS
FROM CTE_NCM
WHERE PURC_ORDER_ID IS NOT NULL
GROUP BY VENDOR_ID
	, CONVERT(DATE, NCM_DATE, 101)
	, CONVERT(NVARCHAR,LEFT(CONVERT(VARCHAR, NCM_DATE, 112), 6))
	, PURC_ORDER_ID
	, PART_ID
	, NCM_INFO
)

SELECT VENDOR_ID
	, YYYYMM
	, SUM(REJECTED_QTY) AS REJECTED_QTY
	, SUM(RECEIVED_QTY) AS RECEIVED_QTY
	, SUM(ONTIME) AS ONTIME
	, SUM(LATE) AS LATE
	, SUM(LINE_TOTALS) AS LINE_TOTALS
FROM CTE_MERGE 
GROUP BY VENDOR_ID
	, YYYYMM
ORDER BY VENDOR_ID
	, YYYYMM


/*
SELECT * 
FROM CTE_MERGE
WHERE VENDOR_ID  = 'AAAPLA'

*/