use datawarehouse
go

declare @startdate datetime = getdate() - 7,
	@enddate datetime = getdate() - 1

-- VISUAL ENTERPRISE > PARTS REPORTS > Surface Area Paint
WITH CTE_BASE AS 
(SELECT W.BASE_ID
	, W.LOT_ID
	, W.SPLIT_ID
	, W.SUB_ID
	, CASE
		WHEN W.PART_ID LIKE '%REWORK%' THEN W2.PART_ID
		WHEN W.PART_ID LIKE '%TOOLING%' THEN W2.PART_ID
		WHEN W.PART_ID IS NULL THEN W2.PART_ID
		ELSE W.PART_ID
	END AS PARTID
	, W.PART_ID AS CHILDPART
FROM WORK_ORDER W
INNER JOIN WORK_ORDER W2
	ON W.TYPE = W2.TYPE
	AND W.BASE_ID = W2.BASE_ID
	AND W.LOT_ID = W2.LOT_ID
	AND W.SPLIT_ID = W2.SPLIT_ID
	AND W2.SUB_ID = '0'
WHERE W.TYPE = 'W'
)

SELECT 'MAIN PART' AS REPT
	, CAST(W.STATUS_EFF_DATE AS DATE) TRANSACTION_DATE
	, DATEPART(YYYY, W.STATUS_EFF_DATE) TRANSACTION_DATE_YEAR
	, DATEPART(WK, W.STATUS_EFF_DATE) TRANSACTION_DATE_WEEK
	, DATEPART(D, W.STATUS_EFF_DATE) TRANSACTION_DATE_DAY
	, W.BASE_ID
	, W.LOT_ID
	, W.SPLIT_ID
	, W.SUB_ID
	, PARTID
	, CHILDPART
	, W.STATUS
	, W.ENGINEERED_BY
	, O.RESOURCE_ID
	, SR.USER_5
	, CASE 
		WHEN PSA.MATERIAL_TYPE IS NULL THEN 'NEED DIMENSIONS' 
		ELSE PSA.MATERIAL_TYPE
	END AS MATERIAL_TYPE
	, PSA.ALLOY
	, W.[DESIRED_QTY]
	, PSA.THICKNESS_VAL
	, PSA.LENGTH_VAL
	, PSA.WIDTH_VAL
	, W.DESIRED_QTY * ISNULL(PSA.SURFACE_AREA, 0) AS SURFACE_AREA
FROM WORK_ORDER AS W
INNER JOIN CTE_BASE CTE
	ON W.TYPE = 'W'
	AND W.BASE_ID = CTE.BASE_ID
	AND W.LOT_ID = CTE.LOT_ID
	AND W.SPLIT_ID = CTE.SPLIT_ID
	AND W.SUB_ID = CTE.SUB_ID
INNER JOIN OPERATION O
	ON W.TYPE = O.WORKORDER_TYPE
	AND W.BASE_ID = O.WORKORDER_BASE_ID
	AND W.LOT_ID = O.WORKORDER_LOT_ID
	AND W.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND W.SUB_ID = O.WORKORDER_SUB_ID
INNER JOIN SHOP_RESOURCE SR
	ON SR.ID = O.RESOURCE_ID
	AND O.RESOURCE_ID IN (
		SELECT RESOURCE_ID
		FROM LIVESupplemental..ResourceID_ReportSettings S
		WHERE S.REPORT_NAME = 'Surface Area Paint'
			AND S.REPORT_SECTION = 'Main Report'
	)
LEFT OUTER JOIN SKILLS_PART_SURFACE_AREA AS PSA
	ON CTE.PARTID = PSA.PART_ID
WHERE W.TYPE = 'W'
	AND W.[STATUS] = 'C'
	AND W.STATUS_EFF_DATE >= @STARTDATE 
	AND W.STATUS_EFF_DATE < @ENDDATE 

UNION

-- CANCELLED/WIP WITH LABOR TICKETS
SELECT 'LABOR TICKETS MAIN' AS REPT
	, CAST(W.STATUS_EFF_DATE AS DATE) TRANSACTION_DATE
	, DATEPART(YYYY, W.STATUS_EFF_DATE) TRANSACTION_DATE_YEAR
	, DATEPART(WK, W.STATUS_EFF_DATE) TRANSACTION_DATE_WEEK
	, DATEPART(D, W.STATUS_EFF_DATE) TRANSACTION_DATE_DAY
	, W.BASE_ID
	, W.LOT_ID
	, W.SPLIT_ID
	, W.SUB_ID
	, PARTID
	, CHILDPART
	, W.STATUS
	, W.ENGINEERED_BY
	, O.RESOURCE_ID
	, SR.USER_5
	--, RA.LOCATION,
	, CASE 
		WHEN PSA.MATERIAL_TYPE IS NULL THEN 'NEED DIMENSIONS' 
		ELSE PSA.MATERIAL_TYPE
	END AS MATERIAL_TYPE
	, PSA.ALLOY
	, W.[DESIRED_QTY]
	, PSA.THICKNESS_VAL
	, PSA.LENGTH_VAL
	, PSA.WIDTH_VAL
	, W.DESIRED_QTY * ISNULL(PSA.SURFACE_AREA, 0) AS SURFACE_AREA
FROM WORK_ORDER AS W
INNER JOIN CTE_BASE CTE
	ON W.TYPE = 'W'
	AND W.BASE_ID = CTE.BASE_ID
	AND W.LOT_ID = CTE.LOT_ID
	AND W.SPLIT_ID = CTE.SPLIT_ID
	AND W.SUB_ID = CTE.SUB_ID
INNER JOIN OPERATION O
	ON W.TYPE = O.WORKORDER_TYPE
	AND W.BASE_ID = O.WORKORDER_BASE_ID
	AND W.LOT_ID = O.WORKORDER_LOT_ID
	AND W.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND W.SUB_ID = O.WORKORDER_SUB_ID
INNER JOIN
	(SELECT LT.WORKORDER_TYPE
		, LT.WORKORDER_BASE_ID
		, LT.WORKORDER_LOT_ID
		, LT.WORKORDER_SPLIT_ID
		, LT.WORKORDER_SUB_ID
		, MIN(LT.TRANSACTION_DATE) AS TRANSDATE
	FROM LABOR_TICKET LT
	INNER JOIN OPERATION O
		ON LT.WORKORDER_TYPE = O.WORKORDER_TYPE
		AND LT.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
		AND LT.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
		AND LT.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
		AND LT.WORKORDER_SUB_ID = O.WORKORDER_SUB_ID
		AND LT.OPERATION_SEQ_NO = O.SEQUENCE_NO
		AND O.RESOURCE_ID IN (
		SELECT RESOURCE_ID
		FROM LIVESupplemental..ResourceID_ReportSettings S
		WHERE S.REPORT_NAME = 'Surface Area Paint'
			AND S.REPORT_SECTION = 'Main Report'
		)
	GROUP BY LT.WORKORDER_TYPE
		, LT.WORKORDER_BASE_ID
		, LT.WORKORDER_LOT_ID
		, LT.WORKORDER_SPLIT_ID
		, LT.WORKORDER_SUB_ID
	) AS LT
	ON O.WORKORDER_TYPE = LT.WORKORDER_TYPE
	AND O.WORKORDER_BASE_ID = LT.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = LT.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = LT.WORKORDER_SUB_ID
INNER JOIN SHOP_RESOURCE SR
	ON SR.ID = O.RESOURCE_ID
	AND O.RESOURCE_ID IN (
		SELECT RESOURCE_ID
		FROM LIVESupplemental..ResourceID_ReportSettings S
		WHERE S.REPORT_NAME = 'Surface Area Paint'
			AND S.REPORT_SECTION = 'Main Report'
	)
LEFT OUTER JOIN SKILLS_PART_SURFACE_AREA AS PSA
	ON CTE.PARTID = PSA.PART_ID
WHERE W.TYPE = 'W'
	AND W.STATUS <> 'C'
	AND W.STATUS_EFF_DATE >= @STARTDATE 
	AND W.STATUS_EFF_DATE < @ENDDATE 
 
UNION

-- CO-PRODUCTS
SELECT 'CO-PRODUCTS' AS REPT
	, CAST(W.STATUS_EFF_DATE AS DATE) TRANSACTION_DATE
	, DATEPART(YYYY, W.STATUS_EFF_DATE) TRANSACTION_DATE_YEAR
	, DATEPART(WK, W.STATUS_EFF_DATE) TRANSACTION_DATE_WEEK
	, DATEPART(D, W.STATUS_EFF_DATE) TRANSACTION_DATE_DAY
	, W.BASE_ID
	, W.LOT_ID
	, W.SPLIT_ID
	, W.SUB_ID
	, CP.PART_ID AS PARTID
	, 'CO-PRODUCT' AS CHILDPART
	, W.STATUS
	, W.ENGINEERED_BY
	, O.RESOURCE_ID
	, SR.USER_5
	, CASE 
		WHEN PSA.MATERIAL_TYPE IS NULL THEN 'NEED DIMENSIONS' 
		ELSE PSA.MATERIAL_TYPE
	END AS MATERIAL_TYPE
	, PSA.ALLOY
	, CP.[DESIRED_QTY]
	, PSA.THICKNESS_VAL
	, PSA.LENGTH_VAL
	, PSA.WIDTH_VAL
	, CP.DESIRED_QTY * ISNULL(PSA.SURFACE_AREA, 0) AS SURFACEAREA
FROM CO_PRODUCT AS CP
INNER JOIN WORK_ORDER AS W
	ON CP.WORKORDER_TYPE = 'W'
	AND CP.WORKORDER_BASE_ID = W.BASE_ID
	AND CP.WORKORDER_LOT_ID = W.LOT_ID
	AND CP.WORKORDER_SPLIT_ID = W.SPLIT_ID
INNER JOIN CTE_BASE CTE
	ON W.TYPE = 'W'
	AND W.BASE_ID = CTE.BASE_ID
	AND W.LOT_ID = CTE.LOT_ID
	AND W.SPLIT_ID = CTE.SPLIT_ID
	AND W.SUB_ID = CTE.SUB_ID
INNER JOIN OPERATION O
	ON W.TYPE = O.WORKORDER_TYPE
	AND W.BASE_ID = O.WORKORDER_BASE_ID
	AND W.LOT_ID = O.WORKORDER_LOT_ID
	AND W.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND W.SUB_ID = O.WORKORDER_SUB_ID
INNER JOIN SHOP_RESOURCE SR
	ON SR.ID = O.RESOURCE_ID
	AND O.RESOURCE_ID IN (
		SELECT RESOURCE_ID
		FROM LIVESupplemental..ResourceID_ReportSettings S
		WHERE S.REPORT_NAME = 'Surface Area Paint'
			AND S.REPORT_SECTION = 'Main Report'
	)
LEFT OUTER JOIN SKILLS_PART_SURFACE_AREA AS PSA
	ON CP.PART_ID = PSA.PART_ID
WHERE W.[TYPE] = 'W'
	AND W.[STATUS] = 'C'
	AND W.STATUS_EFF_DATE >= @STARTDATE 
	AND W.STATUS_EFF_DATE < @ENDDATE 

UNION

-- CANCELLED/WIP WITH LABOR TICKETS CO-PRODUCTS
SELECT 'LABOR TICKETS CO-PRODUCTS' AS REPT
	, CAST(W.STATUS_EFF_DATE AS DATE) TRANSACTION_DATE
	, DATEPART(YYYY, W.STATUS_EFF_DATE) TRANSACTION_DATE_YEAR
	, DATEPART(WK, W.STATUS_EFF_DATE) TRANSACTION_DATE_WEEK
	, DATEPART(D, W.STATUS_EFF_DATE) TRANSACTION_DATE_DAY
	, W.BASE_ID
	, W.LOT_ID
	, W.SPLIT_ID
	, W.SUB_ID
	, CP.PART_ID AS PARTID
	, 'CO-PRODUCT' AS CHILDPART
	, W.[STATUS]
	, W.ENGINEERED_BY
	, O.RESOURCE_ID
	, SR.USER_5
	, CASE 
		WHEN PSA.MATERIAL_TYPE IS NULL THEN 'NEED DIMENSIONS' 
		ELSE PSA.MATERIAL_TYPE
	END AS MATERIAL_TYPE
	, PSA.ALLOY
	, W.[DESIRED_QTY]
	, PSA.THICKNESS_VAL
	, PSA.LENGTH_VAL
	, PSA.WIDTH_VAL
	, W.DESIRED_QTY * ISNULL(PSA.SURFACE_AREA, 0) AS SURFACE_AREA
FROM CO_PRODUCT AS CP
INNER JOIN WORK_ORDER AS W
	ON (CP.WORKORDER_TYPE = 'W')
	AND (CP.WORKORDER_BASE_ID = W.BASE_ID)
	AND (CP.WORKORDER_LOT_ID = W.LOT_ID)
	AND (CP.WORKORDER_SPLIT_ID = W.SPLIT_ID)
INNER JOIN CTE_BASE CTE
	ON W.TYPE = 'W'
	AND W.BASE_ID = CTE.BASE_ID
	AND W.LOT_ID = CTE.LOT_ID
	AND W.SPLIT_ID = CTE.SPLIT_ID
	AND W.SUB_ID = CTE.SUB_ID
INNER JOIN OPERATION O
	ON W.TYPE = O.WORKORDER_TYPE
	AND W.BASE_ID = O.WORKORDER_BASE_ID
	AND W.LOT_ID = O.WORKORDER_LOT_ID
	AND W.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND W.SUB_ID = O.WORKORDER_SUB_ID
INNER JOIN SHOP_RESOURCE SR
	ON SR.ID = O.RESOURCE_ID
	AND O.RESOURCE_ID IN (
		SELECT RESOURCE_ID
		FROM LIVESupplemental..ResourceID_ReportSettings S
		WHERE S.REPORT_NAME = 'Surface Area Paint'
			AND S.REPORT_SECTION = 'Main Report'
	)
LEFT OUTER JOIN PART AS P
	ON CP.PART_ID = P.ID
LEFT OUTER JOIN SKILLS_PART_SURFACE_AREA AS PSA
	ON CP.PART_ID = PSA.PART_ID
INNER JOIN
	(SELECT LT.WORKORDER_TYPE
		, LT.WORKORDER_BASE_ID
		, LT.WORKORDER_LOT_ID
		, LT.WORKORDER_SPLIT_ID
		, LT.WORKORDER_SUB_ID
		, MIN(LT.TRANSACTION_DATE) AS TRANSDATE
	FROM LABOR_TICKET LT
	INNER JOIN OPERATION O
		ON LT.WORKORDER_TYPE = O.WORKORDER_TYPE
		AND LT.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
		AND LT.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
		AND LT.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
		AND LT.WORKORDER_SUB_ID = O.WORKORDER_SUB_ID
		AND LT.OPERATION_SEQ_NO = O.SEQUENCE_NO
		AND O.RESOURCE_ID IN (
			SELECT RESOURCE_ID
			FROM LIVESupplemental..ResourceID_ReportSettings S
			WHERE S.REPORT_NAME = 'Surface Area Paint'
				AND S.REPORT_SECTION = 'Main Report'
		)
	GROUP BY LT.WORKORDER_TYPE
		, LT.WORKORDER_BASE_ID
		, LT.WORKORDER_LOT_ID
		, LT.WORKORDER_SPLIT_ID
		, LT.WORKORDER_SUB_ID
	) AS LT
	ON O.WORKORDER_TYPE = LT.WORKORDER_TYPE
	AND O.WORKORDER_BASE_ID = LT.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = LT.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = LT.WORKORDER_SUB_ID
WHERE W.TYPE = 'W'
	AND W.[STATUS] <> 'C'
	AND W.STATUS_EFF_DATE >= @STARTDATE 
	AND W.STATUS_EFF_DATE < @ENDDATE 

