-- use to check for blocked transacions on sql-lab-1

use live
go

dbcc opentran 

SELECT DISTINCT OBJECT_NAME(P.OBJECT_ID) AS TABLENAME
	, RESOURCE_TYPE
	, REQUEST_SESSION_ID
FROM SYS.DM_TRAN_LOCKS L
JOIN SYS.PARTITIONS P
ON L.RESOURCE_ASSOCIATED_ENTITY_ID = P.HOBT_ID
WHERE OBJECT_NAME(P.OBJECT_ID) LIKE '%'

--> CAN KILL SESSION VIA ACTIVITY MONITOR IF NEEDED

dbcc inputbuffer (247)

kill 247