USE LIVE
GO

SELECT T.NAME AS TBL
FROM SYSCOLUMNS C
JOIN SYSOBJECTS T
ON C.ID = T.ID
AND T.XTYPE = 'U'
WHERE CHARINDEX('SEQ_NO', C.NAME) > 0
OR CHARINDEX('BASE_ID', C.NAME) > 0
OR CHARINDEX('WORKORDER', C.NAME) > 0
OR CHARINDEX('OP', C.NAME) > 0
ORDER BY T.NAME