/*  FROM KEITH VIA PHONE CALL 20210303
MASTER: 901-031-554-133
WO: 1648952/1

CUSTOMER SPEC LINES COPIES OVER BUT TIMELIMIT DOES NOT. WHY???
*/

SELECT * FROM USER_DEF_FIELDS WHERE DOCUMENT_ID IS NULL
AND (LABEL LIKE 'CUSTOMER SPECIFIC%'
	OR LABEL LIKE 'TIME LIMIT%'
	)

SELECT * FROM USER_DEF_FIELDS 
WHERE (1=1)
AND PROGRAM_ID = 'VMMFGWIN_OP'
--AND DOCUMENT_ID IS NULL
--AND TAB_ID IS NOT NULL
--AND ID IS NULL
AND TAB_ID IN ('Customer Specific Specs', 'OpType_Additional')
