WITH CTE_TRACE AS
(SELECT PART_ID
	, ID AS TRACE_ID
	, SUM(IN_QTY - OUT_QTY) AS TRACE_QTY
FROM TRACE
GROUP BY PART_ID
, ID
)

, CTE_TRACE_TOT AS
(SELECT PART_ID
	, SUM(IN_QTY - OUT_QTY) AS TRACE_TOT_QTY
FROM TRACE
GROUP BY PART_ID
)

, CTE_XCT AS
(SELECT PART_ID
	, TRACE_ID
	, SUM(QTY) AS XCT_QTY
FROM TRACE_INV_TRANS
GROUP BY PART_ID
	, TRACE_ID
)

, CTE_XCT_TOT AS
(SELECT PART_ID
	, SUM(QTY) AS XCT_TOT_QTY
FROM TRACE_INV_TRANS
GROUP BY PART_ID
)

, CTE_INV AS
(SELECT PART_ID
	, SUM(CASE
		WHEN TYPE = 'I' AND CLASS = 'R' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'I' THEN -1
		WHEN TYPE = 'O' AND CLASS = 'A' THEN -1
		WHEN TYPE = 'I' AND CLASS = 'A' THEN 1
		WHEN TYPE = 'I' AND CLASS = 'I' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'R' THEN -1
		ELSE 0
	END * QTY) AS INV_QTY
FROM INVENTORY_TRANS
GROUP BY PART_ID
)

SELECT P.ID
	, P.[STATUS]
	, I.INV_QTY
	, C.XCT_TOT_QTY
	, TT.TRACE_TOT_QTY
	, T.TRACE_ID
	, T.TRACE_QTY
	, X.XCT_QTY
	, ISNULL(I.INV_QTY, 0) AS INV_QTY_ISNULL
	, ISNULL(C.XCT_TOT_QTY, 0) AS XCT_TOT_ISNULL
	, ISNULL(TT.TRACE_TOT_QTY, 0) AS TRACE_TOT_ISNULL
	, ISNULL(T.TRACE_ID, '') AS TRACE_ID_ISNULL
	, ISNULL(T.TRACE_QTY, 0) AS TRACE_QTY_ISNULL
	, ISNULL(X.XCT_QTY, 0) AS XCT_QTY_ISNULL
INTO #T1
FROM PART P
LEFT OUTER JOIN TRACE_PROFILE TP
	ON P.ID = TP.PART_ID
LEFT OUTER JOIN CTE_INV I
	ON P.ID = I.PART_ID
LEFT OUTER JOIN CTE_TRACE T
	ON P.ID = T.PART_ID
LEFT OUTER JOIN CTE_XCT X
	ON P.ID = X.PART_ID
	AND X.TRACE_ID = T.TRACE_ID
LEFT OUTER JOIN CTE_XCT_TOT C
	ON P.ID = C.PART_ID
LEFT OUTER JOIN CTE_TRACE_TOT TT
	ON P.ID = TT.PART_ID
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
	AND TP.PART_ID IS NOT NULL
	AND (CASE
		WHEN T.TRACE_QTY < 0 THEN 'NEGATIVE QTY'
		WHEN ISNULL(TT.TRACE_TOT_QTY, 0) > ISNULL(C.XCT_TOT_QTY, 0) THEN 'TRACE > XCT_TOT' 
		WHEN ISNULL(TT.TRACE_TOT_QTY, 0) < ISNULL(C.XCT_TOT_QTY, 0) THEN 'TRACE < XCT_TOT' 
		WHEN ISNULL(I.INV_QTY, 0) != ISNULL(TT.TRACE_TOT_QTY, 0) THEN 'INV != TRACE_TOT'
		WHEN ISNULL(I.INV_QTY, 0) != ISNULL(C.XCT_TOT_QTY, 0) THEN 'INV != XCT_TOT' 
		ELSE ''
	END != ''
	)

IF EXISTS(SELECT * FROM #T1)
	SELECT 1 AS RESULT
	ELSE 
	SELECT 0 AS RESULT


-->>>>>>

SELECT 'TRACE ID' AS MSG
	, T.ID
	, CASE 
		WHEN T.ID = IT.WORKORDER_BASE_ID  THEN 'MATCH' 
		WHEN LEFT (T.ID,7) = IT.WORKORDER_BASE_ID  THEN 'MATCH' 
		WHEN LEFT (T.ID,2) = 'RW' AND RIGHT (T.ID, 7) = IT.WORKORDER_BASE_ID THEN 'MATCH' 
		WHEN LEFT (IT.WORKORDER_BASE_ID, 2) = 'RW' AND RIGHT (IT.WORKORDER_BASE_ID, 7) = LEFT (T.ID, 7) THEN 'MATCH' 
		WHEN IT.WORKORDER_BASE_ID + '/' + IT.WORKORDER_LOT_ID = T.ID THEN 'MATCH' 
		ELSE 'NO MATCH'
	END AS ISMATCH 
	, LEFT (T.ID, 7) AS TRACE_BASE_ID
	, T.PART_ID
	, IT.TRANSACTION_ID
	, IT.WORKORDER_BASE_ID
	, IT.[TYPE]
	, IT.CLASS
	, IT.[USER_ID]
	, IT.TRANSACTION_DATE
	, TI.QTY
	, IT.CUST_ORDER_ID
FROM TRACE T
INNER JOIN TRACE_INV_TRANS TI
	ON T.ID = TI.TRACE_ID
	AND T.PART_ID = TI.PART_ID
INNER JOIN INVENTORY_TRANS IT
	ON TI.TRANSACTION_ID = IT.TRANSACTION_ID
--> tt20210726: added to remove corrections
INNER JOIN (SELECT IT.WORKORDER_BASE_ID
		, IT.WORKORDER_LOT_ID
		, IT.WORKORDER_SPLIT_ID
		, IT.WORKORDER_SUB_ID
		, IT.PART_ID
		, TI.TRACE_ID
		, SUM(TI.QTY) AS QTY_SUM
	FROM TRACE_INV_TRANS TI
	INNER JOIN INVENTORY_TRANS IT
		ON TI.TRANSACTION_ID = IT.TRANSACTION_ID
	WHERE IT.CLASS = 'R'
		AND IT.TRANSACTION_DATE >= GETDATE()-4
		AND IT.WORKORDER_BASE_ID IS NOT NULL
	GROUP BY IT.WORKORDER_BASE_ID
		, IT.WORKORDER_LOT_ID
		, IT.WORKORDER_SPLIT_ID
		, IT.WORKORDER_SUB_ID
		, IT.PART_ID
		, TI.TRACE_ID
	HAVING SUM(TI.QTY) != 0
	) X
	ON IT.WORKORDER_BASE_ID = X.WORKORDER_BASE_ID
	AND IT.WORKORDER_LOT_ID = X.WORKORDER_LOT_ID
	AND IT.WORKORDER_SPLIT_ID = X.WORKORDER_SPLIT_ID
	AND IT.WORKORDER_SUB_ID = X.WORKORDER_SUB_ID
	AND IT.PART_ID = X.PART_ID
	AND TI.TRACE_ID = X.TRACE_ID
WHERE IT.CLASS = 'R'
	AND IT.TRANSACTION_DATE >= GETDATE()-4
	AND CASE 
		WHEN T.ID = IT.WORKORDER_BASE_ID  THEN 'MATCH' 
		WHEN LEFT (T.ID,7) = IT.WORKORDER_BASE_ID  THEN 'MATCH' 
		WHEN LEFT (T.ID,2) = 'RW' AND RIGHT (T.ID, 7) = IT.WORKORDER_BASE_ID THEN 'MATCH' 
		WHEN IT.WORKORDER_BASE_ID + '/' + IT.WORKORDER_LOT_ID = T.ID THEN 'MATCH' 
		WHEN LEFT (IT.WORKORDER_BASE_ID,2) = 'RW' AND RIGHT (IT.WORKORDER_BASE_ID,7) = LEFT (T.ID,7) THEN 'MATCH' 
		WHEN LEFT (T.ID,6) = IT.WORKORDER_BASE_ID  THEN 'MATCH' 
		ELSE 'NO MATCH'
	END = 'NO MATCH'
	AND IT.WORKORDER_BASE_ID IS NOT NULL
	AND TI.QTY != 0
