USE [LIVE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET NOCOUNT ON;

--DECLARE @BASE_ID NVARCHAR(20) = '1658631'
DECLARE @BASE_ID NVARCHAR(20) = '1658754'
, @LOT_ID NVARCHAR(5) = '1'
, @SPLIT_ID NVARCHAR(5) = '0'
, @SUB_ID NVARCHAR(5) = '0'
, @STARTING_SEQ_NO NVARCHAR(5) = '30'
--, @STARTING_SEQ_NO NVARCHAR(5) = '20'

SELECT dbo.SFNWONUMFORMAT(IT.WORKORDER_BASE_ID, IT.WORKORDER_LOT_ID, IT.WORKORDER_SPLIT_ID, IT.WORKORDER_SUB_ID) AS WO_NUM
	, dbo.SFNWONUMFORMAT_OLD(IT.WORKORDER_BASE_ID, IT.WORKORDER_LOT_ID, IT.WORKORDER_SPLIT_ID, IT.WORKORDER_SUB_ID) AS OLD_WO_ID
	, IT.WORKORDER_BASE_ID
	, IT.WORKORDER_LOT_ID
	, IT.WORKORDER_SPLIT_ID
	, IT.WORKORDER_SUB_ID
	, IT.OPERATION_SEQ_NO
	, IT.REQ_PIECE_NO
	, IT.PART_ID
	, IT.[TYPE]
	, IT.CLASS
	, IT.TRANSACTION_DATE
	, IT.WAREHOUSE_ID
	, IT.LOCATION_ID
	, IT.[DESCRIPTION]
	, IT.[USER_ID]
	, IT.TRANSACTION_ID
	, TRT.CREATE_DATE
	, ISNULL(T.ID, 'NO TRACE') AS TRACE_ID
	, T.APROPERTY_1
	, T.APROPERTY_2
	, ISNULL(TRT.QTY, (IT.QTY * -1)) AS QTY
	, TRT.PART_ID AS TRACEPART
	, P.[DESCRIPTION] AS TRACEPARTDESC
	, TP.APROPERTY_LABEL_1
	, TP.APROPERTY_LABEL_2
	, TP.APROPERTY_LABEL_3
	, TP.APROPERTY_LABEL_4
	, T.APROPERTY_3
	, T.APROPERTY_4
FROM INVENTORY_TRANS AS IT
LEFT OUTER JOIN TRACE_INV_TRANS AS TRT
	ON IT.TRANSACTION_ID = TRT.TRANSACTION_ID
LEFT OUTER JOIN TRACE AS T
	ON TRT.TRACE_ID = T.ID
	AND TRT.PART_ID = T.PART_ID
LEFT OUTER JOIN PART AS P
	ON IT.PART_ID = P.ID
LEFT OUTER JOIN TRACE_PROFILE AS TP
	ON T.PART_ID = TP.PART_ID
WHERE IT.CLASS <> 'R'
	AND IT.WORKORDER_BASE_ID = @BASE_ID
	AND IT.WORKORDER_LOT_ID IN (SELECT LTRIM(ITEM) FROM dbo.UFNSPLIT(@LOT_ID, ','))
	AND IT.WORKORDER_SPLIT_ID IN (SELECT LTRIM(ITEM) FROM dbo.UFNSPLIT(@SPLIT_ID, ','))
	AND IT.WORKORDER_SUB_ID IN (SELECT LTRIM(ITEM) FROM dbo.UFNSPLIT(@SUB_ID, ','))
	AND CONVERT(VARCHAR(3), IT.OPERATION_SEQ_NO) IN (SELECT LTRIM(ITEM) FROM dbo.UFNSPLIT(@STARTING_SEQ_NO, ','))
