USE LIVE
GO

DROP TABLE #T1

; WITH CTE_TRACE AS
(SELECT PART_ID
	, ID AS TRACE_ID
	, SUM(IN_QTY - OUT_QTY) AS TRACE_QTY
FROM TRACE
GROUP BY PART_ID
, ID
)

, CTE_TRACE_TOT AS
(SELECT PART_ID
	, SUM(IN_QTY - OUT_QTY) AS TRACE_TOT_QTY
FROM TRACE
GROUP BY PART_ID
)

, CTE_XCT AS
(SELECT PART_ID
	, TRACE_ID
	, SUM(QTY) AS TI_XCT_QTY
FROM TRACE_INV_TRANS
GROUP BY PART_ID
	, TRACE_ID
)

, CTE_XCT_TOT AS
(SELECT PART_ID
	, SUM(QTY) AS TI_XCT_TOT_QTY
FROM TRACE_INV_TRANS
GROUP BY PART_ID
)

, CTE_PL AS
(SELECT PART_ID
	, SUM(QTY) AS PL_TOT_QTY
FROM PART_LOCATION
GROUP BY PART_ID
)

, CTE_PW AS
(SELECT PART_ID
	, SUM([MIN_INV_QTY] + [COMMITTED_CO] + [COMMITTED_REQ] + [COMMITTED_PLREQ] + [COMMITTED_IBT] 
		+ [AVAILABLE_QTY] + [OUTBOUND_QTY] + [ON_HOLD_QTY] + [LOCKED_QTY] + [UNAVAILABLE_QTY]) AS PW_TOT_QTY
FROM PART_WAREHOUSE PW
GROUP BY PART_ID
)

, CTE_IB AS
(SELECT PART_ID
	, MAX(POSTING_DATE) AS POSTING_DATE
	, SUM(QTY) AS IB_TOT_QTY
FROM INVENTORY_BALANCE IB
WHERE POSTING_DATE > DATEADD(MONTH, DATEDIFF(MONTH, -1, GETDATE())-1, -1) 
GROUP BY PART_ID
)

, CTE_INV AS
(SELECT PART_ID
	, SUM(CASE
		WHEN TYPE = 'I' AND CLASS = 'R' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'I' THEN -1
		WHEN TYPE = 'O' AND CLASS = 'A' THEN -1
		WHEN TYPE = 'I' AND CLASS = 'A' THEN 1
		WHEN TYPE = 'I' AND CLASS = 'I' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'R' THEN -1
		ELSE 0
	END * QTY) AS INV_QTY
FROM INVENTORY_TRANS
GROUP BY PART_ID
)

SELECT CASE
		WHEN T.TRACE_QTY < 0 THEN 'NEGATIVE QTY'
		WHEN X.TI_XCT_QTY < 0 THEN 'NEGATIVE QTY'
		WHEN ISNULL(P.QTY_ON_HAND, 0) != ISNULL(PS.QTY_ON_HAND, 0) THEN 'P != PS' 
		WHEN ISNULL(P.QTY_ON_HAND, 0) != ISNULL(PW.PW_TOT_QTY, 0) THEN 'P != PW' 		
		WHEN ISNULL(PL.PL_TOT_QTY, 0) != ISNULL(PW.PW_TOT_QTY, 0) THEN 'PL != PW' 
		WHEN TP.PART_ID IS NULL THEN '' --> NO TRACE PROFILE
		WHEN ISNULL(TT.TRACE_TOT_QTY, 0) > ISNULL(C.TI_XCT_TOT_QTY, 0) THEN 'TRACE > XCT_TOT' 
		WHEN ISNULL(TT.TRACE_TOT_QTY, 0) < ISNULL(C.TI_XCT_TOT_QTY, 0) THEN 'TRACE < XCT_TOT' 
		WHEN ISNULL(I.INV_QTY, 0) != ISNULL(TT.TRACE_TOT_QTY, 0) THEN 'INV != TRACE_TOT'
		WHEN ISNULL(I.INV_QTY, 0) != ISNULL(C.TI_XCT_TOT_QTY, 0) THEN 'INV != XCT_TOT' 
		WHEN ISNULL(I.INV_QTY, 0) != ISNULL(P.QTY_ON_HAND, 0) THEN 'INV != ON_HAND' 
		WHEN ISNULL(X.TI_XCT_QTY, 0) != ISNULL(T.TRACE_QTY, 0) THEN 'TI_XCT != TRACE'
		ELSE ''
	END AS MSG 
	, P.ID
	, P.[STATUS]
	, P.QTY_ON_HAND AS P_QTY_ON_HAND
	, PS.QTY_ON_HAND AS PS_QTY_ON_HAND
	, ISNULL(PL.PL_TOT_QTY, 0) AS PL_TOT_QTY
	, ISNULL(PW.PW_TOT_QTY, 0) AS PW_TOT_QTY
	, ISNULL(IB.IB_TOT_QTY, 0) AS IB_TOT_QTY
	, ISNULL(I.INV_QTY, 0) AS INV_QTY
	, ISNULL(C.TI_XCT_TOT_QTY, 0) AS TI_XCT_TOT_QTY
	, ISNULL(TT.TRACE_TOT_QTY, 0) AS TRACE_TOT_QTY
	, ISNULL(T.TRACE_ID, '') AS TRACE_ID
	, ISNULL(T.TRACE_QTY, 0) AS TRACE_QTY
	, ISNULL(X.TI_XCT_QTY, 0) AS TI_XCT_QTY
INTO #T1
FROM PART P
LEFT OUTER JOIN PART_SITE PS
	ON P.ID = PS.PART_ID
LEFT OUTER JOIN TRACE_PROFILE TP
	ON P.ID = TP.PART_ID
LEFT OUTER JOIN CTE_PL PL
	ON P.ID = PL.PART_ID
LEFT OUTER JOIN CTE_PW PW
	ON P.ID = PW.PART_ID
LEFT OUTER JOIN	CTE_IB IB
	ON P.ID = IB.PART_ID
LEFT OUTER JOIN CTE_INV I
	ON P.ID = I.PART_ID
LEFT OUTER JOIN CTE_TRACE T
	ON P.ID = T.PART_ID
LEFT OUTER JOIN CTE_XCT X
	ON P.ID = X.PART_ID
	AND X.TRACE_ID = T.TRACE_ID
LEFT OUTER JOIN CTE_XCT_TOT C
	ON P.ID = C.PART_ID
LEFT OUTER JOIN CTE_TRACE_TOT TT
	ON P.ID = TT.PART_ID
WHERE CASE
	WHEN T.TRACE_QTY < 0 THEN 'NEGATIVE QTY'
	WHEN X.TI_XCT_QTY < 0 THEN 'NEGATIVE QTY'
	WHEN ISNULL(P.QTY_ON_HAND, 0) != ISNULL(PS.QTY_ON_HAND, 0) THEN 'P != PS' 
	WHEN ISNULL(P.QTY_ON_HAND, 0) != ISNULL(PW.PW_TOT_QTY, 0) THEN 'P != PW' 		
	WHEN ISNULL(PL.PL_TOT_QTY, 0) != ISNULL(PW.PW_TOT_QTY, 0) THEN 'PL != PW' 
	WHEN TP.PART_ID IS NULL THEN '' --> NO TRACE PROFILE
	WHEN ISNULL(TT.TRACE_TOT_QTY, 0) > ISNULL(C.TI_XCT_TOT_QTY, 0) THEN 'TRACE > XCT_TOT' 
	WHEN ISNULL(TT.TRACE_TOT_QTY, 0) < ISNULL(C.TI_XCT_TOT_QTY, 0) THEN 'TRACE < XCT_TOT' 
	WHEN ISNULL(I.INV_QTY, 0) != ISNULL(TT.TRACE_TOT_QTY, 0) THEN 'INV != TRACE_TOT'
	WHEN ISNULL(I.INV_QTY, 0) != ISNULL(C.TI_XCT_TOT_QTY, 0) THEN 'INV != XCT_TOT' 
	WHEN ISNULL(I.INV_QTY, 0) != ISNULL(P.QTY_ON_HAND, 0) THEN 'INV != ON_HAND' 
	WHEN ISNULL(X.TI_XCT_QTY, 0) != ISNULL(T.TRACE_QTY, 0) THEN 'TI_XCT != TRACE'
	ELSE ''
END != ''

SELECT * FROM #T1

-------> FIX TRACE SECTION

SELECT * FROM TRACE WHERE PART_ID = '20243C-071X60X96 CMPN' AND ID IN ('67844/01 pallet 4257', '67844/01 pallet 4258')
SELECT * FROM TRACE_INV_TRANS WHERE PART_ID = '20243C-071X60X96 CMPN' AND TRACE_ID IN ('67844/01 pallet 4257', '67844/01 pallet 4258')
SELECT * FROM INVENTORY_TRANS WHERE TRANSACTION_ID IN (SELECT TRANSACTION_ID FROM TRACE_INV_TRANS WHERE PART_ID = '20243C-071X60X96 CMPN' AND TRACE_ID IN ('67844/01 pallet 4257', '67844/01 pallet 4258'))

/*
BEGIN TRANSACTION;
UPDATE TRACE 
SET IN_QTY = 600
, OUT_QTY = 0
WHERE PART_ID = '20243C-071X60X96 CMPN' 
	AND ID = '67844/01 pallet 4258'
--	AND ID = '67844/01 pallet 4257' 
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/


--> FIX NEGATIVE QTY SECTION

SELECT * FROM TRACE WHERE PART_ID = '413A3008-229' AND ID = '1664288/1'
SELECT * FROM TRACE_INV_TRANS WHERE PART_ID = '413A3008-229' AND TRACE_ID IN ('1664288/1')
SELECT * FROM INVENTORY_TRANS WHERE TRANSACTION_ID IN (SELECT TRANSACTION_ID FROM TRACE_INV_TRANS WHERE PART_ID = '413A3008-229' AND TRACE_ID IN ('1664288/1'))

SELECT * FROM TRACE WHERE PART_ID = '413A3008-229' AND ID = '1670620/1'
SELECT * FROM TRACE_INV_TRANS WHERE PART_ID = '413A3008-229' AND TRACE_ID IN ('1670620/1')
SELECT * FROM INVENTORY_TRANS WHERE TRANSACTION_ID IN (SELECT TRANSACTION_ID FROM TRACE_INV_TRANS WHERE PART_ID = '413A3008-229' AND TRACE_ID IN ('1670620/1'))

/*
BEGIN TRANSACTION;
UPDATE TRACE 
SET IN_QTY = 19
, OUT_QTY = 19
WHERE PART_ID = '413A3008-229' 
	AND ID = '1664288/1'
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

BEGIN TRANSACTION;
UPDATE TRACE 
SET IN_QTY = 12
, OUT_QTY = 4
WHERE PART_ID = '413A3008-229' 
	AND ID = '1670620/1'
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

BEGIN TRANSACTION;
UPDATE TRACE_INV_TRANS 
SET TRACE_ID = '1670620/1'
WHERE PART_ID = '413A3008-229' 
	AND TRANSACTION_ID = '3058708'
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

-------> FIX BLEEDING TRACE SECTION

SELECT * FROM TRACE WHERE PART_ID = '453W3432-1' AND ID LIKE '148141/1%'
SELECT * FROM TRACE_INV_TRANS WHERE PART_ID = '453W3432-1' AND TRACE_ID LIKE '148141/1%'
SELECT * FROM INVENTORY_TRANS WHERE TRANSACTION_ID IN (SELECT TRANSACTION_ID FROM TRACE_INV_TRANS WHERE PART_ID = '453W3432-1' AND TRACE_ID LIKE '148141/1%')

/*
BEGIN TRANSACTION;
UPDATE TRACE 
SET IN_QTY = 1
, OUT_QTY = 0
WHERE PART_ID = '453W3432-1' 
	AND ID = '148141/1B'
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

BEGIN TRANSACTION;
UPDATE TRACE 
SET IN_QTY = 1
, OUT_QTY = 0
WHERE PART_ID = '453W3432-1' 
	AND ID = '148141/1C'
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

*/

