SELECT PL.PART_ID, 
		P.[DESCRIPTION],
        PL.WAREHOUSE_ID, 
        PL.LOCATION_ID, 
        PL.QTY
 FROM   LIVE.dbo.PART_LOCATION PL
 INNER JOIN LIVE.DBO.PART P
	ON PL.PART_ID = P.ID
 WHERE  PL.QTY <> 0
 AND PL.WAREHOUSE_ID = 'STDS'
 AND PL.LOCATION_ID = 'ADHESIVE'