USE LIVE
GO

SELECT 'TRACE ID' AS MSG
	, T.ID
	, CASE 
		WHEN T.ID = IT.WORKORDER_BASE_ID  THEN 'MATCH' 
		WHEN LEFT (T.ID,7) = IT.WORKORDER_BASE_ID  THEN 'MATCH' 
		WHEN LEFT (T.ID,2) = 'RW' AND RIGHT (T.ID, 7) = IT.WORKORDER_BASE_ID THEN 'MATCH' 
		WHEN LEFT (IT.WORKORDER_BASE_ID, 2) = 'RW' AND RIGHT (IT.WORKORDER_BASE_ID, 7) = LEFT (T.ID, 7) THEN 'MATCH' 
		WHEN IT.WORKORDER_BASE_ID + '/' + IT.WORKORDER_LOT_ID = T.ID THEN 'MATCH' 
		ELSE 'NO MATCH'
	END AS ISMATCH 
	, LEFT (T.ID, 7) AS TRACE_BASE_ID
	, T.PART_ID
	, IT.TRANSACTION_ID
	, IT.WORKORDER_BASE_ID
	, IT.[TYPE]
	, IT.CLASS
	, IT.[USER_ID]
	, IT.TRANSACTION_DATE
	, TI.QTY
	, IT.CUST_ORDER_ID
FROM TRACE T
INNER JOIN TRACE_INV_TRANS TI
	ON T.ID = TI.TRACE_ID
	AND T.PART_ID = TI.PART_ID
INNER JOIN INVENTORY_TRANS IT
	ON TI.TRANSACTION_ID = IT.TRANSACTION_ID
--> tt20210726: added to remove corrections
INNER JOIN (SELECT IT.WORKORDER_BASE_ID
		, IT.WORKORDER_LOT_ID
		, IT.WORKORDER_SPLIT_ID
		, IT.WORKORDER_SUB_ID
		, IT.PART_ID
		, TI.TRACE_ID
		, SUM(TI.QTY) AS QTY_SUM
	FROM TRACE_INV_TRANS TI
	INNER JOIN INVENTORY_TRANS IT
		ON TI.TRANSACTION_ID = IT.TRANSACTION_ID
	WHERE IT.CLASS = 'R'
		AND IT.TRANSACTION_DATE >= GETDATE()-4
		AND IT.WORKORDER_BASE_ID IS NOT NULL
	GROUP BY IT.WORKORDER_BASE_ID
		, IT.WORKORDER_LOT_ID
		, IT.WORKORDER_SPLIT_ID
		, IT.WORKORDER_SUB_ID
		, IT.PART_ID
		, TI.TRACE_ID
	HAVING SUM(TI.QTY) != 0
	) X
	ON IT.WORKORDER_BASE_ID = X.WORKORDER_BASE_ID
	AND IT.WORKORDER_LOT_ID = X.WORKORDER_LOT_ID
	AND IT.WORKORDER_SPLIT_ID = X.WORKORDER_SPLIT_ID
	AND IT.WORKORDER_SUB_ID = X.WORKORDER_SUB_ID
	AND IT.PART_ID = X.PART_ID
	AND TI.TRACE_ID = X.TRACE_ID
WHERE IT.CLASS = 'R'
	AND IT.TRANSACTION_DATE >= GETDATE()-4
	AND CASE 
		WHEN T.ID = IT.WORKORDER_BASE_ID  THEN 'MATCH' 
		WHEN LEFT (T.ID,7) = IT.WORKORDER_BASE_ID  THEN 'MATCH' 
		WHEN LEFT (T.ID,2) = 'RW' AND RIGHT (T.ID, 7) = IT.WORKORDER_BASE_ID THEN 'MATCH' 
		WHEN IT.WORKORDER_BASE_ID + '/' + IT.WORKORDER_LOT_ID = T.ID THEN 'MATCH' 
		WHEN LEFT (IT.WORKORDER_BASE_ID,2) = 'RW' AND RIGHT (IT.WORKORDER_BASE_ID,7) = LEFT (T.ID,7) THEN 'MATCH' 
		WHEN LEFT (T.ID,6) = IT.WORKORDER_BASE_ID  THEN 'MATCH' 
		ELSE 'NO MATCH'
	END = 'NO MATCH'
	AND IT.WORKORDER_BASE_ID IS NOT NULL
	AND TI.QTY != 0