USE LIVE
GO

WITH CTE_GO AS
(SELECT EC_ID, TASK_NO, SEQ_NO
FROM [LIVE].[dbo].[task]
WHERE USER_ID = 'TRACY'
AND [TYPE] = 'REQ'
AND [STATUS] NOT IN ('C', 'X')
)

UPDATE TASK
SET [STATUS] = 'P'
, [USER_ID] = 'TRACEY'
FROM TASK T
INNER JOIN CTE_GO CTE
ON T.EC_ID = CTE.EC_ID
AND T.TASK_NO = CTE.TASK_NO
AND T.SEQ_NO = CTE.SEQ_NO

