USE DataWarehouse
GO

SELECT 
--TRACE
	T.PART_ID
	, T.ID AS TRACE_ID
--	, ISNULL(PURC_ORDER_ID + '/' + CAST(PURC_ORDER_LINE_NO AS NVARCHAR(30)), WORKORDER_BASE_ID + '/' + WORKORDER_LOT_ID + '/' + WORKORDER_SUB_ID) AS ReceiptTraceID
	, T.IN_QTY
	, T.OUT_QTY
	, T.IN_QTY - OUT_QTY TRACE_DIFF
--TRACE_INV_TRANS
	, TI.TRANSACTION_ID
	, TI.QTY AS TIXCT_QTY
	, IT.TXCT_QTY

--INVENTORY_TRANS
	, CASE
		WHEN TYPE = 'I' AND CLASS = 'R' THEN 'RECEIPT'
		WHEN TYPE = 'O' AND CLASS = 'I' THEN 'ISSUE'
		WHEN TYPE = 'O' AND CLASS = 'A' THEN 'ADJUST OUT'
		WHEN TYPE = 'I' AND CLASS = 'A' THEN 'ADJUST IN'
		WHEN TYPE = 'I' AND CLASS = 'I' THEN 'RETURN ISSUE'
		WHEN TYPE = 'O' AND CLASS = 'R' THEN 'RETURN RECEIPT'
		ELSE 'FIX'
	END AS XCTTYPE
	, I.[TYPE]
	, I.CLASS
	, I.QTY
	, CASE
		WHEN TYPE = 'I' AND CLASS = 'R' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'I' THEN -1
		WHEN TYPE = 'O' AND CLASS = 'A' THEN -1
		WHEN TYPE = 'I' AND CLASS = 'A' THEN 1
		WHEN TYPE = 'I' AND CLASS = 'I' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'R' THEN -1
		ELSE 'FIX'
	END * I.QTY AS XCTQTY
	, I.WORKORDER_BASE_ID
	, I.WORKORDER_LOT_ID
	, I.WORKORDER_SPLIT_ID
	, I.WORKORDER_SUB_ID
	, I.CUST_ORDER_ID
	, I.CUST_ORDER_LINE_NO
	, I.PURC_ORDER_ID
	, I.PURC_ORDER_LINE_NO
	, I.[USER_ID]
	, I.TRANSACTION_DATE
	, I.WAREHOUSE_ID
	, I.LOCATION_ID
FROM TRACE_INV_TRANS TI
INNER JOIN 
	(SELECT TRANSACTION_ID
		, PART_ID
		, SUM(QTY) AS TXCT_QTY
	FROM TRACE_INV_TRANS IT
	GROUP BY TRANSACTION_ID
		, PART_ID
	) IT
	ON  IT.TRANSACTION_ID = TI.TRANSACTION_ID
	AND IT.PART_ID = TI.PART_ID
LEFT OUTER JOIN TRACE T
	ON  TI.TRACE_ID = T.ID
	AND TI.PART_ID = T.PART_ID
INNER JOIN INVENTORY_TRANS I
	ON  TI.TRANSACTION_ID = I.TRANSACTION_ID
	AND TI.PART_ID = I.PART_ID

WHERE
	TRANSACTION_DATE >= '1/1/2017'
	AND
	(
-->1.  Leading spaces
		--(CLASS = 'R') AND (LEFT(T.ID,1) = ' ')
		--OR
-->2.  Source of TraceID: PurchaseOrder or WorkOrder
		(
			(CLASS = 'R') 
			AND (
					(T.ID <> isnull(PURC_ORDER_ID, N'') + N'/' + CAST(isnull(PURC_ORDER_LINE_NO, N'') AS NVARCHAR(30)))
				AND (T.ID <> isnull(PURC_ORDER_ID, N''))
				AND (T.ID <> ISNULL((WORKORDER_BASE_ID + N'/' + WORKORDER_LOT_ID + N'/' + WORKORDER_SPLIT_ID + N'/' + WORKORDER_SUB_ID), N''))
				AND (T.ID <> ISNULL(WORKORDER_BASE_ID + N'/' + WORKORDER_LOT_ID + N'/' + WORKORDER_SUB_ID, N''))
				AND (T.ID <> ISNULL(WORKORDER_BASE_ID + N'/' + WORKORDER_LOT_ID, N''))
				AND (T.ID <> ISNULL(WORKORDER_BASE_ID, N''))

				--AND (T.ID <> WORKORDER_BASE_ID + IIF(WORKORDER_SUB_ID = '0', '', '-' + WORKORDER_SUB_ID) + '/' + WORKORDER_LOT_ID + IIF(WORKORDER_SPLIT_ID = '0', '', '.' + WORKORDER_SPLIT_ID))
				AND (T.ID <> (ISNULL(WORKORDER_BASE_ID, '') 
						+ (CASE
							WHEN WORKORDER_SUB_ID IS NULL THEN ''
							WHEN WORKORDER_SUB_ID = '0' THEN ''
							ELSE N'-' + WORKORDER_SUB_ID + N'/' 
						END) 
						+ ISNULL(WORKORDER_LOT_ID, '') 
						+ (CASE
							WHEN WORKORDER_SPLIT_ID IS NULL THEN ''
							WHEN WORKORDER_SPLIT_ID = '0' THEN ''
							ELSE N'.' + WORKORDER_SPLIT_ID
						END)
					)
				)
			)
	)

-->3.  Inventory Xct Qty <> sum(Trace_Inv_Trans Qty)
		OR
		(IT.TXCT_QTY <> CASE
			WHEN TYPE = 'I' AND CLASS = 'R' THEN 1
			WHEN TYPE = 'I' AND CLASS = 'A' THEN 1
			WHEN TYPE = 'I' AND CLASS = 'I' THEN 1
			WHEN TYPE = 'O' AND CLASS = 'I' THEN -1
			WHEN TYPE = 'O' AND CLASS = 'A' THEN -1
			WHEN TYPE = 'O' AND CLASS = 'R' THEN -1
			ELSE 0
		END * I.QTY
		)

-->3.  TRACE_ID DOES NOT EXIST
		OR 
		(TI.TRACE_ID IS NOT NULL AND T.ID IS NULL)
	)

SELECT *
FROM TRACE_INV_TRANS TI
INNER JOIN INVENTORY_TRANS IT
ON TI.TRANSACTION_ID = IT.TRANSACTION_ID
LEFT OUTER JOIN TRACE T
ON T.ID = TI.TRACE_ID
AND T.PART_ID = TI.PART_ID
WHERE ti.transaction_id = '2287690'

SELECT * FROM INVENTORY_TRANS WHERE TRANSACTION_ID IN ('2314315', '2314316')

SELECT * FROM TRACE_INV_TRANS WHERE TRANSACTION_ID IN ('2314315', '2314316')

SELECT * FROM TRACE_INV_TRANS WHERE part_id = '287T1101-21' --and TRACE_ID = '1284060/1/0'
/*

use datawarehouse
go

SELECT t.part_id
	, t.id
	, warehouse_id
	, location_id
	, T.IN_QTY
	, T.OUT_QTY
	, T.IN_QTY - OUT_QTY AS TRACE_DIFF
	, sum(TI.QTY) as TIXctQty
FROM TRACE_INV_TRANS TI
INNER JOIN 
	(SELECT TRANSACTION_ID
		, PART_ID
		, SUM(QTY) AS TXCT_QTY
	FROM TRACE_INV_TRANS IT
	GROUP BY TRANSACTION_ID
		, PART_ID
	) IT
	ON IT.TRANSACTION_ID = TI.TRANSACTION_ID
	AND IT.PART_ID = TI.PART_ID
LEFT OUTER JOIN TRACE T
	ON TI.TRACE_ID = T.ID
	AND TI.PART_ID = T.PART_ID
INNER JOIN INVENTORY_TRANS I
	ON TI.TRANSACTION_ID = I.TRANSACTION_ID
	AND TI.PART_ID = I.PART_ID
--WHERE 
--ti.transaction_id = '2200101'
--TI.TRACE_ID = '1270441/1/0'
--TI.TRACE_ID IS NOT NULL AND T.ID IS NULL
--IT.TRANSACTION_ID IN ('1838945', '1878069', '1820091', '1828136', '1842224', '1793983', '1802537', '1814689', '1830817', '1881872')
group by t.part_id
	, t.id
	, warehouse_id
	, location_id
	, T.IN_QTY
	, T.OUT_QTY
	, T.IN_QTY - OUT_QTY
having sum(TI.QTY) <>0
order by t.part_id
	, t.id
	, warehouse_id
	, location_id
	, T.IN_QTY
	, T.OUT_QTY
	, T.IN_QTY - OUT_QTY


SELECT 
	'TRACE ID' AS MSG
	, T.ID
	, CASE 
		WHEN T.ID = IT.WORKORDER_BASE_ID  THEN 'MATCH' 
		WHEN T.ID = (IT.WORKORDER_BASE_ID + '/' + IT.WORKORDER_LOT_ID) THEN 'MATCH' 
		WHEN T.ID = (IT.WORKORDER_BASE_ID + '/' + IT.WORKORDER_LOT_ID + '/' + IT.WORKORDER_SUB_ID) THEN 'MATCH' 
		WHEN LEFT (T.ID,7) = IT.WORKORDER_BASE_ID  THEN 'MATCH' 
		WHEN LEFT (T.ID,2) = 'RW' AND RIGHT (T.ID, 7) = IT.WORKORDER_BASE_ID THEN 'MATCH' 
		WHEN LEFT (IT.WORKORDER_BASE_ID,2) = 'RW' AND RIGHT (IT.WORKORDER_BASE_ID,7) = LEFT (T.ID,7) THEN 'MATCH' 
		ELSE 'NO MATCH'
	END AS ISMATCH 
	, LEFT (T.ID,7) AS TRACE_BASE_ID
	, T.PART_ID
	, IT.TRANSACTION_ID
	, IT.WORKORDER_BASE_ID
	, IT.[TYPE]
	, IT.CLASS
	, IT.[USER_ID]
	, IT.TRANSACTION_DATE
	, TI.QTY
	, IT.CUST_ORDER_ID
FROM TRACE T
	LEFT OUTER JOIN TRACE_INV_TRANS TI
		ON T.ID = TI.TRACE_ID
	LEFT OUTER JOIN INVENTORY_TRANS IT
		ON TI.TRANSACTION_ID = IT.TRANSACTION_ID
WHERE 
	IT.CLASS = 'R'
	AND IT.TRANSACTION_DATE >= '1/1/2016'
	AND CASE 
		WHEN T.ID = IT.WORKORDER_BASE_ID  THEN 'MATCH' 
		WHEN T.ID = (IT.WORKORDER_BASE_ID + '/' + IT.WORKORDER_LOT_ID) THEN 'MATCH' 
		WHEN T.ID = (IT.WORKORDER_BASE_ID + '/' + IT.WORKORDER_LOT_ID + '/' + IT.WORKORDER_SUB_ID) THEN 'MATCH' 
		WHEN LEFT (T.ID,7) = IT.WORKORDER_BASE_ID  THEN 'MATCH' 
		WHEN LEFT (T.ID,2) = 'RW' AND RIGHT (T.ID, 7) = IT.WORKORDER_BASE_ID THEN 'MATCH' 
		WHEN LEFT (IT.WORKORDER_BASE_ID,2) = 'RW' AND RIGHT (IT.WORKORDER_BASE_ID,7) = LEFT (T.ID,7) THEN 'MATCH' 
		ELSE 'NO MATCH'
	END = 'NO MATCH'
	AND WORKORDER_BASE_ID IS NOT NULL

SELECT * FROM WORK_ORDER WHERE BASE_ID = 'RW1356241'

*/