USE LIVE
GO

DECLARE @PART_ID NVARCHAR(50) = '453W3432-1' 

SELECT I.TRANSACTION_ID
, I.TRANSACTION_DATE
, I.PART_ID
, I.WAREHOUSE_ID
, I.LOCATION_ID
, I.QTY
, I.[TYPE]
, I.[CLASS]
, CASE
	WHEN TYPE = 'I' AND CLASS = 'R' THEN 1
	WHEN TYPE = 'O' AND CLASS = 'I' THEN -1
	WHEN TYPE = 'O' AND CLASS = 'A' THEN -1
	WHEN TYPE = 'I' AND CLASS = 'A' THEN 1
	WHEN TYPE = 'I' AND CLASS = 'I' THEN 1
	WHEN TYPE = 'O' AND CLASS = 'R' THEN -1
	ELSE 0
END * I.QTY AS INV_QTY
, TI.QTY AS TRACE_QTY
, TI.TRACE_ID
, I.USER_ID
FROM INVENTORY_TRANS I
INNER JOIN PART P
ON P.ID = I.PART_ID
LEFT OUTER JOIN TRACE_INV_TRANS TI
ON I.TRANSACTION_ID = TI.TRANSACTION_ID
WHERE I.PART_ID = @PART_ID
ORDER BY TRANSACTION_ID DESC

SELECT * FROM TRACE WHERE PART_ID = '140T2101-2082'

SELECT * FROM TRACE_INV_TRANS WHERE TRACE_ID IN ('145780/2A') ORDER BY CREATE_DATE DESC

SELECT * FROM INVENTORY_TRANS WHERE TRANSACTION_ID IN ('3044430', '3044429', '3044388')
SELECT * FROM TRACE_INV_TRANS WHERE TRANSACTION_ID IN ('3044430', '3044429', '3044388')

/*
BEGIN TRANSACTION;
UPDATE TRACE_INV_TRANS
SET TRACE_ID = '1655238/1'
WHERE TRANSACTION_ID = '3033126'
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

SELECT * FROM TRACE WHERE PART_ID = '70750B-090' AND ID IN ('123045/1', '125498/1')
/*
BEGIN TRANSACTION;
UPDATE TRACE
SET IN_QTY = 1
, OUT_QTY = 0
WHERE ID = '148140/1C'
AND PART_ID = '453W3432-1'
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

BEGIN TRANSACTION;
UPDATE TRACE
SET OUT_QTY = IN_QTY
WHERE ID = '125498/1'
AND PART_ID = '70750B-090'
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;

*/

INSERT INTO TRACE_INV_TRANS VALUES ('21248P-2000X2.25X7.50-MIL', '129735/2', '3029869', '-36', '2021-11-18 11:16:16.413', '0')


--> TYPO CORRECTION:
DECLARE @PART_ID NVARCHAR(50) = '311U8740-1'
DECLARE @CORRECT_TRACEID NVARCHAR(50) = '1655238/1'
DECLARE @BAD_TRACEID NVARCHAR(50) = ' 1655238/1'
DECLARE @TRANSID NVARCHAR(20) = '3032989'
DECLARE @IN_QTY NVARCHAR(20) = '18'
DECLARE @OUT_QTY NVARCHAR(20) = '18'
DECLARE @INV_DATE DATETIME = (SELECT TRANSACTION_DATE FROM INVENTORY_TRANS WHERE TRANSACTION_ID IN (@TRANSID))

--> CREATE CORRECT TRACE_ID
INSERT INTO LIVE.dbo.TRACE (PART_ID, ID, NUMBERING_ID, OUT_QTY, IN_QTY, REPORTED_QTY, ASSIGNED_QTY, APROPERTY_1, APROPERTY_2, APROPERTY_3, APROPERTY_4, APROPERTY_5, NPROPERTY_1, NPROPERTY_2, NPROPERTY_3, NPROPERTY_4, NPROPERTY_5, COMMENTS, EXPIRATION_DATE, CREATE_DATE, DISP_IN_QTY, DISP_OUT_QTY, UNAVAILABLE_QTY, OWNER_ID, LOT_ID, SERIAL_ID, COMMITTED_QTY, PRODUCTION_DATE, RECEIVE_BY_DATE, AVAILABLE_DATE, SHIP_BY_DATE, SITE_ID)
	VALUES (@PART_ID, @CORRECT_TRACEID, @PART_ID, @OUT_QTY, @IN_QTY, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @INV_DATE, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)

--> CORRECT TRACE TRANSACTION RECORD
UPDATE TRACE_INV_TRANS
SET TRACE_ID = '1665409/1'
WHERE TRANSACTION_ID IN ('3022293')
AND PART_ID = '140T2101-2082'

--> ZERO OUR BAD TRACE_ID
UPDATE TRACE
SET OUT_QTY = 1
, IN_QTY = 2
WHERE ID IN ('145780/2A')
AND PART_ID = '453W3432-1'

--> RUN THE REPORT TO CHECK UPDATES, NOTHING ELSE BROKEN
IF OBJECT_ID('tempdb..#CTE_INV') IS NOT NULL DROP TABLE #CTE_INV
IF OBJECT_ID('tempdb..#CTE_TRACE') IS NOT NULL DROP TABLE #CTE_TRACE
IF OBJECT_ID('tempdb..#CTE_XCT') IS NOT NULL DROP TABLE #CTE_XCT
IF OBJECT_ID('tempdb..#CTE_XCT_TOT') IS NOT NULL DROP TABLE #CTE_XCT_TOT
IF OBJECT_ID('tempdb..#CTE_TRACE_TOT') IS NOT NULL DROP TABLE #CTE_TRACE_TOT

SELECT PART_ID
	, ID AS TRACE_ID
	, SUM(IN_QTY - OUT_QTY) AS TRACE_QTY
INTO #CTE_TRACE 
FROM TRACE
GROUP BY PART_ID
, ID

SELECT PART_ID
	, SUM(IN_QTY - OUT_QTY) AS TRACE_TOT_QTY
INTO #CTE_TRACE_TOT 
FROM TRACE
GROUP BY PART_ID

SELECT PART_ID
	, TRACE_ID
	, SUM(QTY) AS XCT_QTY
INTO #CTE_XCT 
FROM TRACE_INV_TRANS
GROUP BY PART_ID
	, TRACE_ID

SELECT PART_ID
	, SUM(QTY) AS XCT_TOT_QTY
INTO #cte_xct_tot 
FROM TRACE_INV_TRANS
GROUP BY PART_ID

SELECT PART_ID
	, SUM(CASE
		WHEN TYPE = 'I' AND CLASS = 'R' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'I' THEN -1
		WHEN TYPE = 'O' AND CLASS = 'A' THEN -1
		WHEN TYPE = 'I' AND CLASS = 'A' THEN 1
		WHEN TYPE = 'I' AND CLASS = 'I' THEN 1
		WHEN TYPE = 'O' AND CLASS = 'R' THEN -1
		ELSE 0
	END * QTY) AS INV_QTY
INTO #CTE_INV
FROM INVENTORY_TRANS
GROUP BY PART_ID

/* for auditing purposes
SELECT ID, [STATUS] FROM PART WHERE ID = @PART_ID
SELECT '#CTE_TRACE' AS MSG, * FROM #CTE_TRACE WHERE PART_ID = @PART_ID 
SELECT '#CTE_TRACE_TOT' AS MSG, * FROM #CTE_TRACE_TOT WHERE PART_ID = '20240C-050'
SELECT '#CTE_XCT' AS MSG, * FROM #CTE_XCT WHERE PART_ID = @PART_ID 
SELECT '#CTE_XCT_TOT' AS MSG, * FROM #CTE_XCT_TOT WHERE PART_ID = @PART_ID 
SELECT '#CTE_INV' AS MSG, * FROM #CTE_INV WHERE PART_ID = @PART_ID 
*/


SELECT CASE
		WHEN ISNULL(TT.TRACE_TOT_QTY, 0) > ISNULL(C.XCT_TOT_QTY, 0) THEN 'TRACE > XCT_TOT' 
		WHEN ISNULL(TT.TRACE_TOT_QTY, 0) < ISNULL(C.XCT_TOT_QTY, 0) THEN 'TRACE < XCT_TOT' 
		WHEN ISNULL(I.INV_QTY, 0) != ISNULL(TT.TRACE_TOT_QTY, 0) THEN 'INV != TRACE_TOT'
		WHEN ISNULL(I.INV_QTY, 0) != ISNULL(C.XCT_TOT_QTY, 0) THEN 'INV != XCT_TOT' 
--		WHEN   THEN '' 
		ELSE ''
	END AS MSG 
	, P.ID
	, P.[STATUS]
	, I.INV_QTY
	, C.XCT_TOT_QTY
	, TT.TRACE_TOT_QTY
	, T.TRACE_ID
	, T.TRACE_QTY
	, X.XCT_QTY
	, ISNULL(I.INV_QTY, 0) AS INV_QTY_ISNULL
	, ISNULL(C.XCT_TOT_QTY, 0) AS XCT_TOT_ISNULL
	, ISNULL(TT.TRACE_TOT_QTY, 0) AS TRACE_TOT_ISNULL
	, ISNULL(T.TRACE_ID, '') AS TRACE_ID_ISNULL
	, ISNULL(T.TRACE_QTY, 0) AS TRACE_QTY_ISNULL
	, ISNULL(X.XCT_QTY, 0) AS XCT_QTY_ISNULL
FROM PART P
LEFT OUTER JOIN TRACE_PROFILE TP
	ON P.ID = TP.PART_ID
LEFT OUTER JOIN #CTE_INV I
	ON P.ID = I.PART_ID
LEFT OUTER JOIN #CTE_TRACE T
	ON P.ID = T.PART_ID
LEFT OUTER JOIN #CTE_XCT X
	ON P.ID = X.PART_ID
	AND X.TRACE_ID = T.TRACE_ID
LEFT OUTER JOIN #CTE_XCT_TOT C
	ON P.ID = C.PART_ID
LEFT OUTER JOIN #CTE_TRACE_TOT TT
	ON P.ID = TT.PART_ID
WHERE (P.[STATUS] IS NULL OR P.[STATUS] != 'O')
-- MUST HAVE TRACE_PROFILE
	AND TP.PART_ID IS NOT NULL
	AND (CASE
		WHEN T.TRACE_QTY < 0 THEN 'NEGATIVE QTY'
		WHEN ISNULL(TT.TRACE_TOT_QTY, 0) > ISNULL(C.XCT_TOT_QTY, 0) THEN 'TRACE > XCT_TOT' 
		WHEN ISNULL(TT.TRACE_TOT_QTY, 0) < ISNULL(C.XCT_TOT_QTY, 0) THEN 'TRACE < XCT_TOT' 
		WHEN ISNULL(I.INV_QTY, 0) != ISNULL(TT.TRACE_TOT_QTY, 0) THEN 'INV != TRACE_TOT'
		WHEN ISNULL(I.INV_QTY, 0) != ISNULL(C.XCT_TOT_QTY, 0) THEN 'INV != XCT_TOT' 
		ELSE ''
	END != ''
	)
--AND P.ID = @PART_ID 
--AND P.ID = '140T2101-2082'
ORDER BY P.ID
	, T.TRACE_ID



/*
SELECT * FROM INVENTORY_TRANS WHERE PART_ID = '140T2101-2082' ORDER BY TRANSACTION_DATE DESC
SELECT * FROM TRACE_INV_TRANS WHERE PART_ID = '140T2101-2082' ORDER BY TRACE_ID
SELECT * FROM TRACE WHERE PART_ID = '140T2101-2082' ORDER BY ID

SELECT * FROM TRACE_INV_TRANS WHERE TRACE_ID = '1665499/1'

UPDATE TRACE 
SET IN_QTY = 12
WHERE ID = '1665409/1'

DELETE FROM TRACE WHERE ID = '1665499/1'

*/