USE LIVE
GO

DECLARE @BASE_ID NVARCHAR(15) = '1626028'
, @LOT_ID NVARCHAR(5) = '1'
, @SPLIT_ID NVARCHAR(5) = '0'


-- =============================================
-- Author:		Vivian M Elia
-- Create date:	1/22/2020
-- Description:	Data set for the Work Order Traveller.

IF OBJECT_ID('tempdb..#CTE_WORKORDERS') IS NOT NULL DROP TABLE #CTE_WORKORDERS
IF OBJECT_ID('tempdb..#CTE_COPRODUCTS') IS NOT NULL DROP TABLE #CTE_COPRODUCTS  
IF OBJECT_ID('tempdb..#CTE_OPERATIONS') IS NOT NULL DROP TABLE #CTE_OPERATIONS
IF OBJECT_ID('tempdb..#CTE_FAI') IS NOT NULL DROP TABLE #CTE_FAI
IF OBJECT_ID('tempdb..#CTE_WOLINK') IS NOT NULL DROP TABLE #CTE_WOLINK
IF OBJECT_ID('tempdb..#CTE_HIDE_ETCH_BARCODE') IS NOT NULL DROP TABLE #CTE_HIDE_ETCH_BARCODE
IF OBJECT_ID('tempdb..#CTE_CHEM_PAINT_OP') IS NOT NULL DROP TABLE #CTE_CHEM_PAINT_OP 
IF OBJECT_ID('tempdb..#CTE_FIRST_PAINT_OPS') IS NOT NULL DROP TABLE #CTE_FIRST_PAINT_OPS
IF OBJECT_ID('tempdb..#CTE_TL_SEQS') IS NOT NULL DROP TABLE #CTE_TL_SEQS
IF OBJECT_ID('tempdb..#CTE_ISLIMITBETWEEN') IS NOT NULL DROP TABLE #CTE_ISLIMITBETWEEN
IF OBJECT_ID('tempdb..#CTE_SOLGEL_OP') IS NOT NULL DROP TABLE #CTE_SOLGEL_OP 
IF OBJECT_ID('tempdb..#CTE_FIRST_CLEAN_OPS') IS NOT NULL DROP TABLE #CTE_FIRST_CLEAN_OPS
IF OBJECT_ID('tempdb..#CTE_SOLGEL_TL_SEQS') IS NOT NULL DROP TABLE #CTE_SOLGEL_TL_SEQS
IF OBJECT_ID('tempdb..#CTE_SOLGEL_ISLIMITBETWEEN') IS NOT NULL DROP TABLE #CTE_SOLGEL_ISLIMITBETWEEN
IF OBJECT_ID('tempdb..#CTE_TIME_LIMIT') IS NOT NULL DROP TABLE #CTE_TIME_LIMIT

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DEADLOCK_PRIORITY LOW

DECLARE @REPORTSETTINGS TABLE(
    [RESOURCE] [NVARCHAR](15) NOT NULL
    , [BARCODE_ETCH] [INT] NULL
    , [BARCODE_PRE_ETCH] [INT] NULL
    , [BARCODE_REVIEW] [INT] NULL
    , [CHEM_TO_PRIME_HRS] [INT] NULL
    , [CLEAN_TO_SOLGEL_HRS] [INT] NULL
    , [FAI_NET_STAMP] [INT] NULL
    , [FAI_STAMP] [INT] NULL
    , [HEIGHTCHANGE] [INT] NULL
    , [PRINTUSER] [INT] NULL
    , [QTY_IN] [INT] NULL
    , [QTY_NOSHOW] [INT] NULL
    , [QTY_OUT] [INT] NULL
    , [SHIP_VIA] [INT] NULL
    , [STAMP] [INT] NULL
    , [START_OP_TO_SOLGEL] [INT] NULL
    ) 
 
INSERT INTO @REPORTSETTINGS
SELECT [RESOURCE]
	, [BARCODE_ETCH]
	, [BARCODE_PRE_ETCH]
	, [BARCODE_REVIEW]
	, [CHEM_TO_PRIME_HRS]
	, [CLEAN_TO_SOLGEL_HRS]
	, [FAI_NET_STAMP]
	, [FAI_STAMP]
	, [HEIGHTCHANGE]
	, [PRINTUSER]
	, [QTY_IN]
	, [QTY_NOSHOW]
	, [QTY_OUT]
	, [SHIP_VIA]
	, [STAMP]
	, [START_OP_TO_SOLGEL] 
FROM
	(SELECT [RESOURCE]
		, CAST([INCLUDE] AS INT) AS [INCLUDE]
		, REPORT_SECTION
	FROM 
		(SELECT [RESOURCE_ID] AS [RESOURCE]
			, [REPORT_NAME]
			, [REPORT_SECTION]
			, [REASONING]
			, [NOTES]
			, [INCLUDE]
		FROM [SQL-BI-1].LIVESUPPLEMENTAL.DBO.[RESOURCEID_REPORTSETTINGS] 
		) A
	WHERE A.REPORT_NAME = 'TRAVELLER'
	) X
PIVOT
(MAX([INCLUDE])
	FOR REPORT_SECTION IN ([BARCODE_ETCH]
		, [BARCODE_PRE_ETCH]
		, [BARCODE_REVIEW]
		, [CHEM_TO_PRIME_HRS]
		, [CLEAN_TO_SOLGEL_HRS]
		, [FAI_NET_STAMP]
		, [FAI_STAMP]
		, [HEIGHTCHANGE]
		, [PRINTUSER]
		, [QTY_IN]
		, [QTY_NOSHOW]
		, [QTY_OUT]
		, [SHIP_VIA]
		, [STAMP]
		, [START_OP_TO_SOLGEL]
	)
) P 

SELECT * FROM @REPORTSETTINGS rs

--> CHECK REPORTSETTINGS
SELECT [RESOURCE] 
	, [BARCODE_ETCH]
	, [BARCODE_PRE_ETCH]
	, [BARCODE_REVIEW]
	, [CHEM_TO_PRIME_HRS]
	, [CLEAN_TO_SOLGEL_HRS]
	, [FAI_NET_STAMP]
	, [FAI_STAMP]
	, [HEIGHTCHANGE]
	, [PRINTUSER]
	, [QTY_IN]
	, [QTY_NOSHOW]
	, [QTY_OUT]
	, [SHIP_VIA]
	, [STAMP]
	, [START_OP_TO_SOLGEL]
FROM @REPORTSETTINGS rs
INNER JOIN OPERATION O
	ON RS.[RESOURCE] = O.RESOURCE_ID
	AND O.WORKORDER_BASE_ID = @BASE_ID
	AND O.WORKORDER_LOT_ID = @LOT_ID
	AND O.WORKORDER_SPLIT_ID = @SPLIT_ID
                                         
DECLARE @PART_ID NVARCHAR(30) -- = '411T3484-66B'
SELECT @PART_ID = PART_ID 
FROM WORK_ORDER WO
WHERE WO.BASE_ID = @BASE_ID
    AND WO.LOT_ID = @LOT_ID
    AND WO.SUB_ID = '0'
    AND WO.SPLIT_ID = @SPLIT_ID
    AND WO.[TYPE] = 'W'
    
--> temp TABLES for primary part of traveller
IF OBJECT_ID('tempdb..#CTE_WORKORDERS') IS NOT NULL DROP TABLE #CTE_WORKORDERS 
IF OBJECT_ID('tempdb..#CTE_OPERATIONS') IS NOT NULL DROP TABLE #CTE_OPERATIONS

SELECT W.* 
	, CONVERT(NVARCHAR(MAX),CONVERT(VARBINARY(MAX),WB.BITS)) AS WO_SPECS
	, P.[DESCRIPTION]
	, SA.SURFACE_AREA
	, SA.ALLOY
	, SA.MATERIAL_TYPE
	, SA.MATERIAL_TYPE + ' ' + SA.ALLOY + ' '
		+ CONVERT(VARCHAR(15),CONVERT(DECIMAL(5,2),SA.THICKNESS_VAL)) + ' X '
		+ CONVERT(VARCHAR(15),CONVERT(DECIMAL(5,2),SA.WIDTH_VAL)) + ' X '
		+ CONVERT(VARCHAR(15),CONVERT(DECIMAL(5,2),SA.LENGTH_VAL)) AS SA_DESCRIPTION2
INTO #CTE_WORKORDERS
FROM WORK_ORDER W
LEFT OUTER JOIN WORKORDER_BINARY WB
	ON WB.WORKORDER_TYPE = W.[TYPE]
	AND WB.WORKORDER_BASE_ID = W.BASE_ID
	AND WB.WORKORDER_LOT_ID = W.LOT_ID
	AND WB.WORKORDER_SPLIT_ID = W.SPLIT_ID
	AND WB.WORKORDER_SUB_ID = W.SUB_ID
INNER JOIN PART P
	ON P.ID = W.PART_ID
LEFT OUTER JOIN DBO.SKILLS_WO_INC_LEG_SURFACE_AREA SA
	ON W.BASE_ID = SA.BASE_ID
	AND W.LOT_ID = SA.LOT_ID
	AND W.SPLIT_ID = SA.SPLIT_ID
	AND W.PART_ID = SA.PART_ID
	--AND W.SUB_ID = SA.SUB_ID
WHERE W.BASE_ID = @BASE_ID
	AND W.LOT_ID = @LOT_ID
	AND W.SPLIT_ID = @SPLIT_ID
	--AND W.SUB_ID IN (@SUB_ID)
	AND W.TYPE = 'W'

SELECT 'CTE_WORKORDERS' AS MSG, * FROM #CTE_WORKORDERS

--> CO-PRODUCTS
SELECT CP.WORKORDER_TYPE
	, CP.WORKORDER_BASE_ID
	, CP.WORKORDER_LOT_ID
	, CP.WORKORDER_SPLIT_ID
	, CP.WORKORDER_SUB_ID
	, CP.PART_ID
	, CP.DESIRED_QTY
	, CP.RECEIVED_QTY
	, P.[DESCRIPTION]
	, SA.SURFACE_AREA
	, SA.ALLOY
	, SA.MATERIAL_TYPE
	, SA.MATERIAL_TYPE + ' ' + SA.ALLOY + ' '
		+ CONVERT(VARCHAR(15),CONVERT(DECIMAL(5,2),SA.THICKNESS_VAL)) + ' X '
		+ CONVERT(VARCHAR(15),CONVERT(DECIMAL(5,2),SA.WIDTH_VAL)) + ' X '
		+ CONVERT(VARCHAR(15),CONVERT(DECIMAL(5,2),SA.LENGTH_VAL)) AS SA_DESCRIPTION2 
INTO #CTE_COPRODUCTS
FROM CO_PRODUCT CP 
INNER JOIN #CTE_WORKORDERS WO
	ON CP.WORKORDER_TYPE = WO.[TYPE]
	AND CP.WORKORDER_BASE_ID = WO.BASE_ID
	AND CP.WORKORDER_LOT_ID = WO.LOT_ID
	AND CP.WORKORDER_SPLIT_ID = WO.SPLIT_ID
	AND CP.WORKORDER_SUB_ID = WO.SUB_ID
INNER JOIN PART P
	ON P.ID = CP.PART_ID 
LEFT OUTER JOIN DBO.SKILLS_WO_INC_LEG_SURFACE_AREA SA
	ON CP.WORKORDER_BASE_ID = SA.BASE_ID
	AND CP.WORKORDER_LOT_ID = SA.LOT_ID
	AND CP.WORKORDER_SPLIT_ID = SA.SPLIT_ID
	AND CP.WORKORDER_SUB_ID = SA.SUB_ID

--> CHECK HERE FOR NEW OPTYPE 
SELECT O.*
	, CASE 
		WHEN EXISTS(SELECT 1 FROM @REPORTSETTINGS RS
			WHERE RS.FAI_NET_STAMP = 1 
			AND O.RESOURCE_ID = RS.[RESOURCE]
			) 
			AND O.OPERATION_TYPE IN ('FAI-NI', 'QP-NI', 'SFI-NI')
			THEN 'FIRST ARTICLE INSPECTION REQUIRED NET INSPECT' 
		ELSE NULL
	END AS FAI_NET_STAMP
	, CASE 
		WHEN EXISTS(SELECT 1 FROM @REPORTSETTINGS RS
			WHERE RS.FAI_STAMP = 1 
			AND O.RESOURCE_ID = RS.[RESOURCE]
			)
			AND O.OPERATION_TYPE NOT IN ('FAI-NI', 'QP-NI','SFI-NI')
			THEN 'FIRST ARTICLE INSPECTION REQUIRED' 
		ELSE NULL
	END AS FAI_STAMP
	, CASE 
		WHEN EXISTS(SELECT 1 FROM @REPORTSETTINGS RS
			WHERE RS.FAI_NET_STAMP = 1 
			AND O.RESOURCE_ID = RS.[RESOURCE]
			) 
			AND O.OPERATION_TYPE IN ('FAI-NI', 'QP-NI', 'SFI-NI')
			THEN 'FIRST ARTICLE INSPECTION REQUIRED NET INSPECT' 
		WHEN EXISTS(SELECT 1 FROM @REPORTSETTINGS RS
			WHERE RS.FAI_STAMP = 1 
			AND O.RESOURCE_ID = RS.[RESOURCE]
			)
			AND O.OPERATION_TYPE NOT IN ('FAI-NI', 'QP-NI', 'SFI-NI')
			THEN 'FIRST ARTICLE INSPECTION REQUIRED' 
		ELSE NULL
	END AS FAI_STAMP2
	, CASE 
		WHEN O.OPERATION_TYPE IN ('CMPFL-REVIEW', 'MFG-REVIEW') THEN 1 --NEW PART
		--, 'AREVIEW2' REMOVED PER SHANNEN HELLE 1/22/2020
		ELSE NULL 
	END AS NEWPART_STAMP
	, R.PIECE_NO
	, R.PART_ID AS RQ_PART_ID                              
	, RB.BITS AS RQ_BITS
	, OB.BITS AS O_BITS
	, RP.[DESCRIPTION] AS RQ_PART_DESCRIPTION
	, R.REQUIRED_DATE AS RQ_REQD_DATE
	, RP.STOCK_UM AS RQ_PART_STOCK_UM
	, R.CALC_QTY AS RQ_CALC_QTY
	, O.WORKORDER_TYPE + '~' + O.WORKORDER_BASE_ID + '~' + O.WORKORDER_SPLIT_ID + '~' + O.WORKORDER_LOT_ID 
		+ '~' + O.WORKORDER_SUB_ID + '~' + CONVERT(VARCHAR(3), O.SEQUENCE_NO) AS O_UDFJOIN
	, R.SUBORD_WO_SUB_ID
	, NULL AS MIN_HOURS
INTO #CTE_OPERATIONS                                
FROM OPERATION O
LEFT OUTER JOIN REQUIREMENT R
ON O.WORKORDER_BASE_ID = R.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = R.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = R.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = R.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = R.WORKORDER_TYPE
	AND O.SEQUENCE_NO = R.OPERATION_SEQ_NO
LEFT OUTER JOIN PART RP
	ON R.PART_ID = RP.ID
LEFT OUTER JOIN REQUIREMENT_BINARY RB
	ON R.WORKORDER_BASE_ID = RB.WORKORDER_BASE_ID
	AND R.WORKORDER_LOT_ID = RB.WORKORDER_LOT_ID
	AND R.WORKORDER_SPLIT_ID = RB.WORKORDER_SPLIT_ID
	AND R.WORKORDER_SUB_ID = RB.WORKORDER_SUB_ID
	AND R.WORKORDER_TYPE = RB.WORKORDER_TYPE
	AND R.OPERATION_SEQ_NO = RB.OPERATION_SEQ_NO
	AND R.PIECE_NO = RB.PIECE_NO
LEFT OUTER JOIN OPERATION_BINARY OB
	ON O.WORKORDER_BASE_ID = OB.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = OB.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = OB.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = OB.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = OB.WORKORDER_TYPE
	AND O.SEQUENCE_NO = OB.SEQUENCE_NO
LEFT OUTER JOIN SHOP_RESOURCE_SITE SRS
	ON O.RESOURCE_ID = SRS.RESOURCE_ID
WHERE O.WORKORDER_BASE_ID = @BASE_ID
	AND O.WORKORDER_LOT_ID = @LOT_ID
	AND O.WORKORDER_SPLIT_ID = @SPLIT_ID
	AND O.WORKORDER_TYPE = 'W'

--SELECT 'CTE_OPERATIONS' AS MSG, * FROM #CTE_OPERATIONS

/******************************************************************************************  
This section obtains the timelimit of the chemical op and all the operations up to the
first paint operation.  Special Verbiage is to print on the operation to notify the user of 
the time limits
--> temp TABLES to obtain hours between chem operation and first paint operation
*/

IF OBJECT_ID('tempdb..#CTE_CHEM_PAINT_OP') IS NOT NULL DROP TABLE #CTE_CHEM_PAINT_OP 
IF OBJECT_ID('tempdb..#CTE_FIRST_PAINT_OPS') IS NOT NULL DROP TABLE #CTE_FIRST_PAINT_OPS
IF OBJECT_ID('tempdb..#CTE_TL_SEQS') IS NOT NULL DROP TABLE #CTE_TL_SEQS
IF OBJECT_ID('tempdb..#CTE_ISLIMITBETWEEN') IS NOT NULL DROP TABLE #CTE_ISLIMITBETWEEN

-- GET HOURS
SELECT ROW_NUMBER() OVER (ORDER BY O.WORKORDER_BASE_ID, O.WORKORDER_LOT_ID, O.WORKORDER_SPLIT_ID,
	O.WORKORDER_SUB_ID, O.SEQUENCE_NO) AS ROW_NUM_HRS
	, O.WORKORDER_TYPE
	, O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, CASE 
		WHEN (SELECT CONVERT(VARCHAR(12), CONVERT(SMALLINT, NUMBER_VAL))
			FROM USER_DEF_FIELDS UDF
			WHERE UDF.PROGRAM_ID = 'VMMFGWIN_OP'
			AND UDF.ID = 'UDF-0000089'             
			AND UDF.DOCUMENT_ID = 'W~' + O.WORKORDER_BASE_ID + '~' + O.WORKORDER_SUB_ID + '~' + O.WORKORDER_LOT_ID 
				+ '~' + O.WORKORDER_SPLIT_ID + '~' + CONVERT(NVARCHAR(3), O.SEQUENCE_NO)
			) IS NOT NULL 
			AND (SELECT CONVERT(VARCHAR(12), CONVERT(SMALLINT, NUMBER_VAL))
				FROM USER_DEF_FIELDS UDF
				WHERE UDF.PROGRAM_ID = 'VMMFGWIN_OP'
				AND UDF.ID = 'UDF-0000089'             
				AND UDF.DOCUMENT_ID = 'W~' + O.WORKORDER_BASE_ID + '~' + O.WORKORDER_SUB_ID + '~' + O.WORKORDER_LOT_ID 
					+ '~' + O.WORKORDER_SPLIT_ID + '~' + CONVERT(NVARCHAR(3), O.SEQUENCE_NO)
			) <> 0
			THEN 1 
		ELSE 0 
	END AS IS_LIMIT_STARTER
	, CASE 
		WHEN (SELECT CONVERT(VARCHAR(12), CONVERT(SMALLINT, NUMBER_VAL))
			FROM USER_DEF_FIELDS UDF
			WHERE UDF.PROGRAM_ID ='VMMFGWIN_OP'
			AND UDF.ID = 'UDF-0000089'             
			AND UDF.DOCUMENT_ID = 'W~' + O.WORKORDER_BASE_ID + '~' + O.WORKORDER_SUB_ID + '~' + O.WORKORDER_LOT_ID 
				+ '~' + O.WORKORDER_SPLIT_ID + '~' + CONVERT(NVARCHAR(3), O.SEQUENCE_NO)
			) IS NOT NULL 
			AND (SELECT CONVERT(VARCHAR(12), CONVERT(SMALLINT, NUMBER_VAL))
				FROM USER_DEF_FIELDS UDF
				WHERE UDF.PROGRAM_ID = 'VMMFGWIN_OP'
				AND UDF.ID = 'UDF-0000089'             
				AND UDF.DOCUMENT_ID = 'W~' + O.WORKORDER_BASE_ID + '~' + O.WORKORDER_SUB_ID + '~' + O.WORKORDER_LOT_ID 
					+ '~' + O.WORKORDER_SPLIT_ID + '~' + CONVERT(NVARCHAR(3), O.SEQUENCE_NO)
			) <> 0
			THEN (SELECT 'TIME LIMIT ' + CONVERT(VARCHAR(12), CONVERT(SMALLINT, NUMBER_VAL))
				FROM USER_DEF_FIELDS UDF
				WHERE UDF.PROGRAM_ID = 'VMMFGWIN_OP'
				AND UDF.ID = 'UDF-0000089'             
				AND UDF.DOCUMENT_ID = 'W~' + O.WORKORDER_BASE_ID + '~' + O.WORKORDER_SUB_ID + '~' + O.WORKORDER_LOT_ID 
					+ '~' + O.WORKORDER_SPLIT_ID + '~' + CONVERT(NVARCHAR(3), O.SEQUENCE_NO)) + ' HOURS'
		ELSE NULL
	END AS MIN_HOURS
	, CASE 
		WHEN EXISTS (SELECT 1 
			FROM @REPORTSETTINGS RS
			WHERE RS.CHEM_TO_PRIME_HRS = 1 
			AND O.RESOURCE_ID = RS.[RESOURCE]
			) THEN 1 
		ELSE 0 
	END AS IS_LIMIT_ENDER
INTO #CTE_CHEM_PAINT_OP 
FROM #CTE_OPERATIONS O
WHERE O.WORKORDER_BASE_ID = @BASE_ID
	AND O.WORKORDER_LOT_ID = @LOT_ID
	AND O.WORKORDER_SPLIT_ID = @SPLIT_ID
	AND NOT EXISTS (SELECT 1 
		FROM @REPORTSETTINGS RS
		WHERE RS.CLEAN_TO_SOLGEL_HRS = 1 
		AND O.RESOURCE_ID = RS.[RESOURCE]
	)

SELECT 'CTE_CHEM_PAINT_OP' AS MSG, * FROM #CTE_CHEM_PAINT_OP
 
SELECT ROW_NUMBER() OVER (PARTITION BY O.WORKORDER_BASE_ID, O.WORKORDER_LOT_ID,
	O.WORKORDER_SPLIT_ID, O.WORKORDER_SUB_ID ORDER BY SEQUENCE_NO
	) AS ROWNUMPNT
	, O.WORKORDER_TYPE
	, O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
INTO #CTE_FIRST_PAINT_OPS
FROM #CTE_CHEM_PAINT_OP AS O
WHERE EXISTS (SELECT 1 
	FROM @REPORTSETTINGS RS
	WHERE RS.CHEM_TO_PRIME_HRS = 1 
	AND O.RESOURCE_ID = RS.[RESOURCE]
	)

SELECT 'CTE_FIRST_PAINT_OPS' AS MSG, * FROM #CTE_FIRST_PAINT_OPS

SELECT STARTROW_NUM_HRS = A.ROW_NUM_HRS
	, ENDROW_NUM_HRS = LEAD(A.ROW_NUM_HRS) OVER(PARTITION BY WORKORDER_LOT_ID, WORKORDER_SPLIT_ID, WORKORDER_SUB_ID
		ORDER BY A.ROW_NUM_HRS)
	, STARTSEQ
	, ENDSEQ = LEAD(A.ENDSEQ) OVER(PARTITION BY A.WORKORDER_LOT_ID , A.WORKORDER_SPLIT_ID, A.WORKORDER_SUB_ID
		ORDER BY ROW_NUM_HRS)
	, MIN_HOURS
	, WORKORDER_TYPE
	, WORKORDER_BASE_ID
	, WORKORDER_LOT_ID
	, WORKORDER_SPLIT_ID
	, WORKORDER_SUB_ID
INTO #CTE_TL_SEQS
FROM
	(SELECT H.ROW_NUM_HRS
		, H.IS_LIMIT_STARTER
		, H.MIN_HOURS
		, CASE 
			WHEN H.SEQUENCE_NO = O.SEQUENCE_NO THEN 1
			ELSE 0
		END AS IS_LIMIT_ENDER
		, (SELECT H.SEQUENCE_NO WHERE H.IS_LIMIT_STARTER = 1) AS STARTSEQ
		, (SELECT O.SEQUENCE_NO WHERE H.SEQUENCE_NO = O.SEQUENCE_NO) AS ENDSEQ
		, H.WORKORDER_TYPE
		, H.WORKORDER_BASE_ID
		, H.WORKORDER_LOT_ID
		, H.WORKORDER_SPLIT_ID
		, H.WORKORDER_SUB_ID
		, H.SEQUENCE_NO
		, H.RESOURCE_ID
	FROM #CTE_CHEM_PAINT_OP H
	LEFT OUTER JOIN #CTE_FIRST_PAINT_OPS O
		ON H.WORKORDER_TYPE = O.WORKORDER_TYPE
		AND H.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
		AND H.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
		AND H.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
		AND H.WORKORDER_SUB_ID = O.WORKORDER_SUB_ID
		AND H.SEQUENCE_NO = O.SEQUENCE_NO
		AND O.ROWNUMPNT = 1
	WHERE (SELECT H.SEQUENCE_NO WHERE IS_LIMIT_STARTER = 1) IS NOT NULL
		OR (SELECT O.SEQUENCE_NO WHERE H.SEQUENCE_NO = O.SEQUENCE_NO) IS NOT NULL
	) AS A

SELECT 'CTE_CHEM_PAINT_OP H' AS MSG, * FROM #CTE_CHEM_PAINT_OP H
SELECT 'CTE_FIRST_PAINT_OPS O' AS MSG, * FROM #CTE_FIRST_PAINT_OPS O
SELECT 'CTE_TL_SEQS' AS MSG, * FROM  #CTE_TL_SEQS

SELECT H.ROW_NUM_HRS
	, H.IS_LIMIT_STARTER
	, H.WORKORDER_TYPE
	, H.WORKORDER_BASE_ID
	, H.WORKORDER_LOT_ID 
	, H.WORKORDER_SPLIT_ID
	, H.WORKORDER_SUB_ID
	, H.SEQUENCE_NO 
	, H.RESOURCE_ID
	, CASE
		WHEN H.ROW_NUM_HRS >= T.STARTROW_NUM_HRS
			AND H.ROW_NUM_HRS <= T.ENDROW_NUM_HRS
		THEN T.MIN_HOURS
	END AS MIN_HOURS
	, CASE
		WHEN H.ROW_NUM_HRS >= T.STARTROW_NUM_HRS
			AND H.ROW_NUM_HRS <= T.ENDROW_NUM_HRS
		THEN 1
	END AS ISLIMITBETWEEN
INTO #CTE_ISLIMITBETWEEN
FROM #CTE_CHEM_PAINT_OP H
LEFT OUTER JOIN #CTE_TL_SEQS T
	ON H.WORKORDER_TYPE = T.WORKORDER_TYPE
	AND H.WORKORDER_BASE_ID = T.WORKORDER_BASE_ID
	AND H.WORKORDER_LOT_ID = T.WORKORDER_LOT_ID
	AND H.WORKORDER_SPLIT_ID = T.WORKORDER_SPLIT_ID
	AND H.WORKORDER_SUB_ID = T.WORKORDER_SUB_ID
WHERE CASE
	WHEN H.ROW_NUM_HRS >= T.STARTROW_NUM_HRS
		AND H.ROW_NUM_HRS <= T.ENDROW_NUM_HRS
		THEN 1
	END IS NOT NULL
GROUP BY H.ROW_NUM_HRS
	, H.MIN_HOURS
	, H.IS_LIMIT_STARTER
	, H.WORKORDER_TYPE
	, H.WORKORDER_BASE_ID
	, H.WORKORDER_LOT_ID
	, H.WORKORDER_SPLIT_ID
	, H.WORKORDER_SUB_ID
	, H.SEQUENCE_NO
	, H.RESOURCE_ID
	, CASE
		WHEN H.ROW_NUM_HRS >= T.STARTROW_NUM_HRS
			AND H.ROW_NUM_HRS <= T.ENDROW_NUM_HRS
			THEN T.MIN_HOURS
		END
	, CASE
		WHEN H.ROW_NUM_HRS >= T.STARTROW_NUM_HRS
			AND H.ROW_NUM_HRS <= T.ENDROW_NUM_HRS
			THEN 1
		END

SELECT 'CTE_ISLIMITBETWEEN' AS MSG, * FROM #CTE_ISLIMITBETWEEN

/***************************************************************************************
This section obtains the timelimit of the solgel operations and all the operations 
backward to the etch (clean) operation.  Special Verbiage is to print on the operation to 
notify the user of the time limits
--> temp TABLES to obtain hours between solgel operation and etch operation
*/
IF OBJECT_ID('tempdb..#CTE_SOLGEL_OP') IS NOT NULL DROP TABLE #CTE_SOLGEL_OP 
IF OBJECT_ID('tempdb..#CTE_FIRST_CLEAN_OPS') IS NOT NULL DROP TABLE #CTE_FIRST_CLEAN_OPS
IF OBJECT_ID('tempdb..#CTE_SOLGEL_TL_SEQS') IS NOT NULL DROP TABLE #CTE_SOLGEL_TL_SEQS
IF OBJECT_ID('tempdb..#CTE_SOLGEL_ISLIMITBETWEEN') IS NOT NULL DROP TABLE #CTE_SOLGEL_ISLIMITBETWEEN

-- GET HOURS
SELECT ROW_NUMBER() OVER(ORDER BY  O.WORKORDER_BASE_ID, O.WORKORDER_LOT_ID
		, O.WORKORDER_SPLIT_ID, O.WORKORDER_SUB_ID, O.SEQUENCE_NO ) AS ROW_NUM_HRS
	, O.WORKORDER_TYPE
	, O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, CASE 
		WHEN EXISTS (SELECT 1 FROM @REPORTSETTINGS RS 
			WHERE RS.START_OP_TO_SOLGEL = 1 AND O.RESOURCE_ID = RS.RESOURCE
			) THEN 1 
		ELSE 0 
	END AS IS_LIMIT_STARTER
	, CASE 
		WHEN (SELECT CONVERT(VARCHAR(12), CONVERT(SMALLINT,NUMBER_VAL))
			FROM USER_DEF_FIELDS UDF
			WHERE UDF.PROGRAM_ID = 'VMMFGWIN_OP'
			AND UDF.ID = 'UDF-0000089'             
			AND UDF.DOCUMENT_ID = 'W~' + O.WORKORDER_BASE_ID + '~' + O.WORKORDER_SUB_ID + '~' + O.WORKORDER_LOT_ID + '~' 
				+ O.WORKORDER_SPLIT_ID + '~' + CONVERT(NVARCHAR(3), O.SEQUENCE_NO)) IS NOT NULL 
			THEN (SELECT 'TIME LIMIT ' + CONVERT(VARCHAR(12),CONVERT(SMALLINT,NUMBER_VAL))
				FROM USER_DEF_FIELDS UDF
				WHERE UDF.PROGRAM_ID = 'VMMFGWIN_OP'
				AND UDF.ID = 'UDF-0000089'             
				AND UDF.DOCUMENT_ID = 'W~' + O.WORKORDER_BASE_ID + '~' + O.WORKORDER_SUB_ID + '~' + O.WORKORDER_LOT_ID 
					+ '~' + O.WORKORDER_SPLIT_ID + '~' + CONVERT(NVARCHAR(3), O.SEQUENCE_NO)) + ' HOURS'
		ELSE NULL 
	END AS MIN_HOURS
	, CASE 
		WHEN EXISTS (SELECT 1 FROM @REPORTSETTINGS RS
			WHERE RS.CLEAN_TO_SOLGEL_HRS = 1 AND O.RESOURCE_ID = RS.RESOURCE
			) THEN 1 
		ELSE 0 
	END AS IS_LIMIT_ENDER
INTO #CTE_SOLGEL_OP 
FROM #CTE_OPERATIONS O

SELECT ROW_NUMBER() OVER (PARTITION BY O.WORKORDER_BASE_ID, O.WORKORDER_LOT_ID
		, O.WORKORDER_SPLIT_ID, O.WORKORDER_SUB_ID ORDER BY O.SEQUENCE_NO) AS ROWNUMPNT
	, O.WORKORDER_TYPE
	, O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, O.MIN_HOURS
INTO #CTE_FIRST_CLEAN_OPS
FROM #CTE_SOLGEL_OP AS O
WHERE EXISTS(SELECT 1 FROM @REPORTSETTINGS RS WHERE RS.CLEAN_TO_SOLGEL_HRS = 1 AND O.RESOURCE_ID = RS.[RESOURCE])
--SELECT * FROM #CTE_SOLGEL_TL_SEQS

SELECT STARTROW_NUM_HRS = A.ROW_NUM_HRS
	, ENDROW_NUM_HRS = LEAD(A.ROW_NUM_HRS) OVER(PARTITION BY A.WORKORDER_LOT_ID, A.WORKORDER_SPLIT_ID, 
		A.WORKORDER_SUB_ID ORDER BY A.ROW_NUM_HRS)
	, STARTSEQ
	, ENDSEQ = LEAD(A.ENDSEQ) OVER(PARTITION BY A.WORKORDER_LOT_ID, A.WORKORDER_SPLIT_ID, 
		A.WORKORDER_SUB_ID ORDER BY A.ROW_NUM_HRS)
	, MIN_HOURS = LEAD(A.MIN_HOURS) OVER(PARTITION BY A.WORKORDER_LOT_ID, A.WORKORDER_SPLIT_ID, 
		A.WORKORDER_SUB_ID ORDER BY A.ROW_NUM_HRS)
	, A.WORKORDER_TYPE
	, A.WORKORDER_BASE_ID
	, A.WORKORDER_LOT_ID
	, A.WORKORDER_SPLIT_ID
	, A.WORKORDER_SUB_ID
INTO #CTE_SOLGEL_TL_SEQS
FROM (SELECT H.ROW_NUM_HRS
		, H.IS_LIMIT_STARTER
		, H.MIN_HOURS
		, CASE 
			WHEN H.SEQUENCE_NO = O.SEQUENCE_NO THEN 1
			ELSE 0
		END AS IS_LIMIT_ENDER
		, (SELECT H.SEQUENCE_NO WHERE H.IS_LIMIT_STARTER = 1) AS STARTSEQ
		, (SELECT O.SEQUENCE_NO WHERE H.SEQUENCE_NO = O.SEQUENCE_NO) AS ENDSEQ
		, H.WORKORDER_TYPE
		, H.WORKORDER_BASE_ID
		, H.WORKORDER_LOT_ID
		, H.WORKORDER_SPLIT_ID
		, H.WORKORDER_SUB_ID
		, H.SEQUENCE_NO
		, H.RESOURCE_ID
	FROM #CTE_SOLGEL_OP H
	LEFT OUTER JOIN #CTE_FIRST_CLEAN_OPS O
		ON H.WORKORDER_TYPE = O.WORKORDER_TYPE
		AND H.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
		AND H.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
		AND H.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
		AND H.WORKORDER_SUB_ID = O.WORKORDER_SUB_ID
		AND H.SEQUENCE_NO = O.SEQUENCE_NO
		AND O.ROWNUMPNT = 1
	WHERE (SELECT H.SEQUENCE_NO WHERE H.IS_LIMIT_STARTER = 1) IS NOT NULL
	OR (SELECT O.SEQUENCE_NO WHERE H.SEQUENCE_NO = O.SEQUENCE_NO) IS NOT NULL
	) AS A

SELECT H.ROW_NUM_HRS
	, H.IS_LIMIT_STARTER
	, H.WORKORDER_TYPE
	, H.WORKORDER_BASE_ID
	, H.WORKORDER_LOT_ID 
	, H.WORKORDER_SPLIT_ID
	, H.WORKORDER_SUB_ID
	, H.SEQUENCE_NO
	, H.RESOURCE_ID
	, CASE 
		WHEN H.ROW_NUM_HRS >= T.STARTROW_NUM_HRS
			AND H.ROW_NUM_HRS <= T.ENDROW_NUM_HRS THEN T.MIN_HOURS
	END AS MIN_HOURS
	, CASE 
		WHEN H.ROW_NUM_HRS >= T.STARTROW_NUM_HRS
			AND H.ROW_NUM_HRS <= T.ENDROW_NUM_HRS THEN 1
	END AS IS_LIMIT_BETWEEN
INTO #CTE_SOLGEL_ISLIMITBETWEEN
FROM #CTE_SOLGEL_OP H
LEFT OUTER JOIN #CTE_SOLGEL_TL_SEQS T
	ON H.WORKORDER_TYPE = T.WORKORDER_TYPE
	AND H.WORKORDER_BASE_ID = T.WORKORDER_BASE_ID
	AND H.WORKORDER_LOT_ID = T.WORKORDER_LOT_ID
	AND H.WORKORDER_SPLIT_ID = T.WORKORDER_SPLIT_ID
	AND H.WORKORDER_SUB_ID = T.WORKORDER_SUB_ID
WHERE CASE 
	WHEN H.ROW_NUM_HRS >= T.STARTROW_NUM_HRS
		AND H.ROW_NUM_HRS <= T.ENDROW_NUM_HRS THEN 1
	END IS NOT NULL
GROUP BY H.ROW_NUM_HRS
	, T.MIN_HOURS
	, H.IS_LIMIT_STARTER
	, H.WORKORDER_TYPE
	, H.WORKORDER_BASE_ID
	, H.WORKORDER_LOT_ID 
	, H.WORKORDER_SPLIT_ID
	, H.WORKORDER_SUB_ID
	, H.SEQUENCE_NO
	, H.RESOURCE_ID
	, CASE 
		WHEN H.ROW_NUM_HRS >= T.STARTROW_NUM_HRS
			AND H.ROW_NUM_HRS <= T.ENDROW_NUM_HRS THEN T.MIN_HOURS
	END
	, CASE 
		WHEN H.ROW_NUM_HRS >= T.STARTROW_NUM_HRS
			AND H.ROW_NUM_HRS <= T.ENDROW_NUM_HRS THEN 1
	END

SELECT 'CTE_SOLGEL_OP ' AS MSG, * FROM #CTE_SOLGEL_OP 
SELECT 'CTE_FIRST_CLEAN_OPS' AS MSG, * FROM #CTE_FIRST_CLEAN_OPS
SELECT 'CTE_SOLGEL_TL_SEQS' AS MSG, * FROM #CTE_SOLGEL_TL_SEQS
SELECT 'CTE_SOLGEL_ISLIMITBETWEEN' AS MSG, * FROM #CTE_SOLGEL_ISLIMITBETWEEN

--> Get documents from Master
; WITH CTE_DOCS AS
(SELECT DRW.* 
	, D.REVISION_ID
	, D.ECN_REVISION
	, U1.STRING_VAL AS ADCN
	, U2.STRING_VAL AS LOC
	, D.ID AS PART_ID
FROM DOCUMENT_REF_WO DRW
JOIN DOCUMENT D
	ON DRW.DOCUMENT_ID = D.ID
LEFT OUTER JOIN USER_DEF_FIELDS U1
	ON DRW.DOCUMENT_ID = U1.DOCUMENT_ID
	AND U1.PROGRAM_ID = N'VMDOCMNT'
	AND U1.ID = N'UDF-0000032'
	AND U1.[LABEL] IS NULL
LEFT OUTER JOIN USER_DEF_FIELDS U2
	ON DRW.DOCUMENT_ID = U2.DOCUMENT_ID
	AND U2.PROGRAM_ID = N'VMDOCMNT'
	AND U2.ID = N'UDF-0000031'
	AND U2.[LABEL] IS NULL
WHERE EXISTS (SELECT 1 FROM #CTE_WORKORDERS W
	WHERE W.PART_ID = DRW.WORKORDER_BASE_ID -- LINKS TO MASTER
	AND W.SUB_ID = N'0'  -- LINKS TO MASTER
	) 
)
--SELECT * FROM CTE_DOCS

SELECT DISTINCT DD.WORKORDER_BASE_ID
	, N'0' AS WORKORDER_SUB_ID
	, (SELECT ISNULL(D.DOCUMENT_ID, N'') + N' / REV: ' + ISNULL(D.REVISION_ID, N'') 
		+ N' / ADCN: ' + ISNULL(D.ADCN, N'') + N' / LOC: ' + ISNULL(D.LOC, N'') + CHAR(10)
		FROM CTE_DOCS D
		FOR XML PATH('')
	) AS VALS
INTO #CTE_WOLINK
FROM CTE_DOCS DD

UNION ALL 

SELECT DISTINCT DD.WORKORDER_BASE_ID
	, DD.WORKORDER_SUB_ID
	, (SELECT ISNULL(D.DOCUMENT_ID, N'') + N' / REV: ' + ISNULL(D.REVISION_ID, N'') 
		+ N' / ADCN: ' + ISNULL(D.ADCN, N'') + N' / LOC: ' + ISNULL(D.LOC, N'') + CHAR(10)
		FROM CTE_DOCS D
		WHERE (D.WORKORDER_BASE_ID= DD.WORKORDER_BASE_ID 
			AND D.WORKORDER_SUB_ID = DD.WORKORDER_SUB_ID)                                              
			FOR XML PATH('')
	) AS VALS
FROM CTE_DOCS DD
WHERE DD.WORKORDER_SUB_ID <> N'0'
GROUP BY DD.WORKORDER_BASE_ID
	, DD.WORKORDER_SUB_ID
--SELECT * FROM #CTE_WOLINK

-- Get FAI information from Masters
SELECT CASE 
		WHEN U1.BOOL_VAL = 1 THEN 'YES'
		ELSE 'NO'
	END AS FAI_COMPLETE 
	, SUBSTRING(U2.STRING_VAL, CHARINDEX('-', U2.STRING_VAL) + 1, 3) AS FAI_INITIALS
	, U3.DATE_VAL AS FAI_DATE_SIGNED
	, M.PART_ID
INTO #CTE_FAI
FROM WORK_ORDER M
LEFT OUTER JOIN USER_DEF_FIELDS U1
	ON U1.DOCUMENT_ID = 'M~' + M.BASE_ID + '~' + M.SUB_ID + '~' + M.LOT_ID + '~' + M.SPLIT_ID  
	AND U1.PROGRAM_ID = N'VMMFGWIN_WO'
	AND U1.ID = N'UDF-0000086'
	AND U1.[LABEL] IS NULL
LEFT OUTER JOIN USER_DEF_FIELDS U2
	ON U2.DOCUMENT_ID = 'M~' + M.BASE_ID + '~' + M.SUB_ID + '~' + M.LOT_ID + '~' + M.SPLIT_ID  
	AND U2.PROGRAM_ID = N'VMMFGWIN_WO'
	AND U2.ID = N'UDF-0000087'
	AND U2.[LABEL] IS NULL
LEFT OUTER JOIN USER_DEF_FIELDS U3
	ON U3.DOCUMENT_ID = 'M~' + M.BASE_ID + '~' + M.SUB_ID + '~' + M.LOT_ID + '~' + M.SPLIT_ID  
	AND U3.PROGRAM_ID = N'VMMFGWIN_WO'
	AND U3.ID = N'UDF-0000088'
	AND U3.[LABEL] IS NULL
WHERE EXISTS (SELECT 1 FROM #CTE_WORKORDERS W WHERE W.PART_ID = M.BASE_ID AND W.SUB_ID = N'0')

SELECT 'CTE_FAI' AS MSG, * FROM #CTE_FAI

-- CTE_HIDE_ETCH_BARCODE
SELECT A.*
, CASE
	WHEN RS.REPORT_SECTION IS NOT NULL
		AND RS2.REPORT_SECTION IS NOT NULL THEN 1
	ELSE 0
END AS HIDE_ETCH_BARCODE
INTO #CTE_HIDE_ETCH_BARCODE
FROM (SELECT O.WORKORDER_TYPE
		, O.WORKORDER_BASE_ID
		, O.WORKORDER_LOT_ID
		, O.WORKORDER_SPLIT_ID
		, O.WORKORDER_SUB_ID
		, O.SEQUENCE_NO
		, O.RESOURCE_ID
		, LEAD(O.SEQUENCE_NO) OVER(PARTITION BY O.WORKORDER_BASE_ID ORDER BY O.WORKORDER_BASE_ID
			, O.WORKORDER_LOT_ID, O.WORKORDER_SPLIT_ID, O.WORKORDER_SUB_ID, O.SEQUENCE_NO) AS NEXTSEQ
		, LEAD(O.RESOURCE_ID) OVER(PARTITION BY O.WORKORDER_BASE_ID ORDER BY O.WORKORDER_BASE_ID
			, O.WORKORDER_LOT_ID, O.WORKORDER_SPLIT_ID, O.WORKORDER_SUB_ID, O.SEQUENCE_NO) AS NEXTRESOURCE
	FROM OPERATION AS O
	WHERE O.WORKORDER_BASE_ID = @BASE_ID
		AND O.WORKORDER_LOT_ID = @LOT_ID
		AND O.WORKORDER_SPLIT_ID = @SPLIT_ID
	) AS A
INNER JOIN LIVESupplemental.dbo.ResourceID_ReportSettings RS
	ON A.RESOURCE_ID = RS.RESOURCE_ID
	AND RS.Report_Name = 'traveller'
INNER JOIN LIVESupplemental.dbo.ResourceID_ReportSettings RS2
	ON A.NEXTRESOURCE = RS2.RESOURCE_ID
	AND RS2.Report_Name = 'traveller'
WHERE A.WORKORDER_BASE_ID = @BASE_ID
	AND A.WORKORDER_LOT_ID = @LOT_ID
	AND A.WORKORDER_SPLIT_ID = @SPLIT_ID
	AND A.WORKORDER_TYPE = 'W'
	AND RS.Report_Section IN ('barcode_etch')
	AND RS2.Report_Section IN ('barcode_pre_etch')

--SELECT MIN_HOURS, SEQUENCE_NO FROM #CTE_OPERATIONS OP
--SELECT MIN_HOURS, SEQUENCE_NO FROM #CTE_SOLGEL_MIN_HRS A
--SELECT MIN_HOURS, SEQUENCE_NO FROM #CTE_ISLIMITBETWEEN B
--SELECT * FROM  #CTE_WORKORDERS 
--SELECT * FROM  #CTE_OPERATIONS
--SELECT * FROM  #CTE_FAI
--SELECT * FROM  #CTE_WOLINK
--SELECT * FROM  #CTE_HIDE_ETCH_BARCODE
--SELECT * FROM  #CTE_CHEM_PAINT_OP 
--SELECT * FROM  #CTE_FIRST_PAINT_OPS
--SELECT * FROM  #CTE_TL_SEQS
--SELECT * FROM  #CTE_ISLIMITBETWEEN
--SELECT * FROM  #CTE_SOLGEL_TL_SEQS
--SELECT * FROM  #CTE_SOLGEL_ISLIMITBETWEEN
--SELECT * FROM  #CTE_TIME_LIMIT

SELECT COALESCE(CONVERT(NVARCHAR(25), A.MIN_HOURS), CONVERT(NVARCHAR(25), B.MIN_HOURS)
	, CONVERT(NVARCHAR(25),OP.MIN_HOURS)) AS MIN_HOURS
	, OP.SEQUENCE_NO
	, OP.WORKORDER_TYPE
	, OP.WORKORDER_BASE_ID
	, OP.WORKORDER_LOT_ID
	, OP.WORKORDER_SPLIT_ID
	, OP.WORKORDER_SUB_ID
	, OP.RESOURCE_ID
	, OP.OPERATION_TYPE
INTO #CTE_TIME_LIMIT
FROM #CTE_OPERATIONS OP
LEFT OUTER JOIN #CTE_SOLGEL_ISLIMITBETWEEN A
	ON OP.WORKORDER_TYPE = A.WORKORDER_TYPE
	AND OP.WORKORDER_BASE_ID = A.WORKORDER_BASE_ID
	AND OP.WORKORDER_LOT_ID = A.WORKORDER_LOT_ID
	AND OP.WORKORDER_SPLIT_ID = A.WORKORDER_SPLIT_ID
	AND OP.WORKORDER_SUB_ID = A.WORKORDER_SUB_ID
	AND OP.SEQUENCE_NO = A.SEQUENCE_NO 
LEFT OUTER JOIN #CTE_ISLIMITBETWEEN B
	ON OP.WORKORDER_TYPE = B.WORKORDER_TYPE
	AND OP.WORKORDER_BASE_ID = B.WORKORDER_BASE_ID
	AND OP.WORKORDER_LOT_ID = B.WORKORDER_LOT_ID
	AND OP.WORKORDER_SPLIT_ID = B.WORKORDER_SPLIT_ID
	AND OP.WORKORDER_SUB_ID = B.WORKORDER_SUB_ID
	AND OP.SEQUENCE_NO = B.SEQUENCE_NO

SELECT 'CTE_TIME_LIMIT' AS MSG, * FROM #CTE_TIME_LIMIT

--> Added 10/22/2019 New stamp for TIME LIMIT for operation only not on footer
SELECT CASE 
		WHEN TL.MIN_HOURS = 'TIME LIMIT 0 HOURS' THEN NULL 
		ELSE TL.MIN_HOURS 
	END AS TIME_LIMIT
	, O.WORKORDER_TYPE
	, O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, SR.[DESCRIPTION] AS RESOURCE_DESC
	, O.SERVICE_ID
	, O.OPERATION_TYPE
	, OT.[DESCRIPTION] AS OP_TYPE_DESC
	, O.VENDOR_ID
	, O.VENDOR_SERVICE_ID
	, O.RQ_PART_ID 
	, O.RQ_PART_DESCRIPTION
	, O.PIECE_NO
	, O.PIECE_NO AS RQ_PIECE
	, dbo.sfnWONUMFormat(O.WORKORDER_BASE_ID, O.WORKORDER_LOT_ID, O.WORKORDER_SPLIT_ID, O.WORKORDER_SUB_ID) AS WONUM
	, dbo.sfnWONUMFormat(O.WORKORDER_BASE_ID, O.WORKORDER_LOT_ID, O.WORKORDER_SPLIT_ID, O.WORKORDER_SUB_ID) AS WONUM_ID
	, O.WORKORDER_BASE_ID + N'/' + O.WORKORDER_LOT_ID + N'/' + O.WORKORDER_SPLIT_ID AS WO_ID
	, W.PART_ID
	, W.PART_ID AS WO_PART_ID
	, ISNULL(W.DESIRED_WANT_DATE, (SELECT TOP 1 W.DESIRED_WANT_DATE FROM #CTE_WORKORDERS W)) AS DESIRED_WANT_DATE
	, ISNULL(W.DESIRED_RLS_DATE, (SELECT TOP 1 W.DESIRED_RLS_DATE FROM #CTE_WORKORDERS W)) AS DESIRED_RLS_DATE
	, (SELECT TOP 1 W.ENGINEERED_BY FROM #CTE_WORKORDERS W WHERE SUB_ID = '0') AS ENGINEERED_BY
	, O.WORKORDER_BASE_ID AS BASE_ID
	, O.WORKORDER_LOT_ID AS LOT_ID
	, O.WORKORDER_SUB_ID AS SUB_ID
	, O.WORKORDER_SPLIT_ID AS SPLIT_ID
	, CASE 
		WHEN RS.STAMP IS NOT NULL THEN 1 
		ELSE 0 
	END AS STAMP                
	, CASE 
		WHEN RS.HEIGHTCHANGE IS NOT NULL THEN 1 
		ELSE 0 
	END AS HEIGHTCHANGE
	, CASE 
		WHEN RS.SHIP_VIA IS NOT NULL THEN CO.SHIP_VIA
		ELSE NULL
	END AS SHIP_VIA 
--> CHECK HERE FOR OPTYPE
	, CASE 
		WHEN RS.BARCODE_REVIEW IS NOT NULL AND O.OPERATION_TYPE NOT IN (N'QP-REVIEW', N'QP-NI') THEN 1  
		WHEN (W.PART_ID LIKE N'TOOLING%' OR W.PART_ID LIKE N'%TOOLING') AND W.SUB_ID <> '0' THEN 1
		WHEN SR.AUTO_REPORTING = N'Y' THEN 1
		WHEN HEB.HIDE_ETCH_BARCODE = 1 THEN 1
		ELSE 0
	END AS BARCODE
	, CASE 
		WHEN O.OPERATION_TYPE IN (N'PRE-PULL', N'STAGING', N'REVIEW', N'QP-REVIEW', N'QP-NI','FAI', N'FAI-NI', N'PANEL',N'PROGM')
			THEN 1
		WHEN RS.QTY_IN IS NOT NULL THEN 0 
		ELSE 1
	END AS  HIDE_QTY_IN
	, RS.QTY_OUT
	,  CASE 
		WHEN RS.QTY_OUT IS NOT NULL THEN CAST(1 AS BIT)
		ELSE CAST(0 AS BIT)
	END AS HIDE_QTY_OUT
	, CASE 
		WHEN RS.QTY_NOSHOW IS NOT NULL THEN CAST(1 AS BIT)
		ELSE CAST(0 AS BIT)
	END AS HIDE_QTY_NOSHOW
	, CASE 
		WHEN RS.PRINTUSER IS NOT NULL THEN 1
		ELSE 0 
	END AS PRINTUSER
	--For printing Part Mark user information
	, O.USER_1 
	, N'*' + SUBSTRING(REPLACE(O.USER_1, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_1, N' ', N'')) + 1, 80) + N'*' AS OP_USER_1
	, O.USER_2
	, N'*' + SUBSTRING(REPLACE(O.USER_2, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_2 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_2
	, O.USER_3
	, N'*' + SUBSTRING(REPLACE(O.USER_3, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_3 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_3
	, O.USER_4
	, N'*' + SUBSTRING(REPLACE(O.USER_4, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_4 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_4
	, O.USER_5
	, N'*' + SUBSTRING(REPLACE(O.USER_5, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_5 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_5
	, O.USER_6
	, N'*' + SUBSTRING(REPLACE(O.USER_6, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_6 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_6
	, O.USER_7
	, N'*' + SUBSTRING(REPLACE(O.USER_7, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_7 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_7
	, O.USER_8
	, N'*' + SUBSTRING(REPLACE(O.USER_8, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_8 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_8
	, O.USER_9
	, N'*' + SUBSTRING(REPLACE(O.USER_9, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_9 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_9
	, O.USER_10
	, N'*' + SUBSTRING(REPLACE(O.USER_10, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_10 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_10 
	, CO.CUSTOMER_ID
	, CO.ID AS CUST_ORDER_ID
	, COL.CUSTOMER_PART_ID
	, C.[NAME] AS CUST_NAME
	, CA.[NAME] AS CUST_ADDRNAME
	, W.[DESCRIPTION] AS WO_PART_DESCRIPTION
	, ISNULL(W.WO_SPECS, CONVERT(NVARCHAR(MAX), CONVERT(VARBINARY(MAX), ORQ.RQ_BITS))) AS WO_LONG_DESCR
	, CONVERT(DECIMAL(14,0), W.SURFACE_AREA) AS SURFACE_AREA
	, W.MATERIAL_TYPE
	, W.ALLOY 
	, W.SA_DESCRIPTION2
	, CAST(CAST(O.O_BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS OP_LONG_DESCR 
	, O.RQ_REQD_DATE AS RQ_REQD
	, O.RQ_PART_STOCK_UM
	, O.RQ_CALC_QTY
	-- ADDED 9/5/2019 VME FAI SIGNATURE ON WORK ORDER FROM MASTER
	, F.FAI_COMPLETE
	, F.FAI_INITIALS
	, F.FAI_DATE_SIGNED
	-- ADDED 9/5/2019 VME REPLACES STAMP FOR FIRST ARTICLE INPECTION
	, O.FAI_STAMP
	, O.FAI_STAMP2
	, O.FAI_NET_STAMP 
	-- ADDED 9/5/2019 VME REPLACES STAMP FOR NEW PART
	, CASE 
		WHEN EXISTS (SELECT 1 FROM #CTE_OPERATIONS O1 WHERE NEWPART_STAMP = 1) THEN 'NEW PART' --NEW PART
		ELSE NULL
	END AS NEWPART_STAMP2
	, CASE 
		WHEN EXISTS(SELECT 1 FROM USER_DEF_FIELDS 
			WHERE DOCUMENT_ID = w.PART_ID AND PROGRAM_ID = 'VMPRTMNT' AND ID = 'UDF-0000040' AND BOOL_VAL = 1)
			THEN 'ITAR Controlled'
		WHEN W.PART_ID LIKE '737RIB-KIT-PROD%' THEN 'Tags must remain on parts throughout entire process!'
		WHEN W.PART_ID LIKE '737RIB-MAX-KIT-PROD%' THEN 'Tags must remain on parts throughout entire process!'
		ELSE ''
	END AS MESSAGE
	, CASE 
		WHEN DSL.SUPPLY_TYPE ='CP' AND COL.LINE_NO = 
			(SELECT MIN( CL1.LINE_NO)
			FROM DBO.CUST_ORDER_LINE AS CL1
			INNER JOIN DBO.DEMAND_SUPPLY_LINK AS DSL1
				ON CL1.CUST_ORDER_ID = DSL1.DEMAND_BASE_ID
				AND CL1.PART_ID = DSL1.SUPPLY_PART_ID
				AND DSL1.SUPPLY_BASE_ID = @BASE_ID  -- CHANGED 6/10/2014
				AND DSL1.SUPPLY_LOT_ID = @LOT_ID
				AND DSL1.SUPPLY_SPLIT_ID = @SPLIT_ID
				AND DSL1.SUPPLY_TYPE = 'CP' 
			) THEN 0 
	END AS CP_FIRST_PART
	, CASE 
		WHEN DSL.SUPPLY_TYPE = 'CP' THEN COL.PART_ID
		ELSE NULL
	END AS CP_PART 
	, DSL.SUPPLY_TYPE
	, COL.LINE_NO
	, SA.DESIRED_QTY AS CP_QTY 
	, SA.[DESCRIPTION] AS CP_DESCRIPTION
	, SA.SA_DESCRIPTION2 AS CP_DESCRIPTION2
	, CASE 
		WHEN ISNULL(SUPPLY_TYPE, 'WO') = 'WO' THEN COL.CUSTOMER_PART_ID
		ELSE NULL
	END AS WO_CUSTOMER_PART_ID
	, CASE 
		WHEN SUPPLY_TYPE = 'CP' THEN COL.CUSTOMER_PART_ID
		ELSE NULL
	END AS CP_CUSTOMER_PART_ID
	, SR.AUTO_REPORTING
	, OVD.LINE_NUM AS OVD_LINE_NO
	, OVD.LABEL_YN AS LABELYN
	, OVD.PROMPT AS OVD_PROMPT
	, O.SUBORD_WO_SUB_ID AS RQ_SUB_ID
	, CO.CUSTOMER_PO_REF
	, W.DESIRED_QTY
	, WL.VALS AS WO_LINK
	, CONVERT(NVARCHAR(MAX), CONVERT(VARBINARY(MAX), ORQ.RQ_BITS)) AS REQ_SPECS
	, dbo.sfnGetCustSpecsString(O.WORKORDER_TYPE + N'~' + O.WORKORDER_BASE_ID + N'~' + O.WORKORDER_SUB_ID
		+ N'~' + O.WORKORDER_LOT_ID + N'~' + O.WORKORDER_SPLIT_ID + N'~' + CAST(O.SEQUENCE_NO AS NVARCHAR(3))) AS CUSTSPECSSTRING
FROM #CTE_WORKORDERS W
INNER JOIN #CTE_OPERATIONS o
	ON W.BASE_ID = O.WORKORDER_BASE_ID
	AND W.LOT_ID = O.WORKORDER_LOT_ID
	AND W.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND W.SUB_ID = O.WORKORDER_SUB_ID
	AND W.[TYPE] = O.WORKORDER_TYPE
LEFT OUTER JOIN OPERATION_TYPE OT
	ON O.OPERATION_TYPE = OT.ID
LEFT OUTER JOIN SHOP_RESOURCE SR
	ON SR.ID = O.RESOURCE_ID
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	INNER JOIN PART P
		ON DSL.SUPPLY_PART_ID = P.ID 
	ON DSL.SUPPLY_BASE_ID = W.BASE_ID
	AND DSL.SUPPLY_LOT_ID = W.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = W.SPLIT_ID
	--AND DSL.SUPPLY_SUB_ID = W.SUB_ID
	AND DSL.SUPPLY_TYPE IN ('WO', 'CP')
LEFT OUTER JOIN CUST_ORDER_LINE COL
	ON DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
LEFT OUTER JOIN CUSTOMER AS C
	ON C.ID = CO.CUSTOMER_ID
LEFT OUTER JOIN CUST_ADDRESS AS CA
	ON CO.CUSTOMER_ID = CA.CUSTOMER_ID
	AND CO.SHIP_TO_ADDR_NO = CA.ADDR_NO
LEFT OUTER JOIN #CTE_COPRODUCTS AS SA
	ON W.BASE_ID = SA.WORKORDER_BASE_ID
	AND W.LOT_ID = SA.WORKORDER_LOT_ID
	AND W.SPLIT_ID = SA.WORKORDER_SPLIT_ID
	AND W.SUB_ID = SA.WORKORDER_SUB_ID
	AND W.[TYPE] = SA.WORKORDER_TYPE
LEFT OUTER JOIN #CTE_FAI F
	ON F.PART_ID = W.PART_ID
LEFT OUTER JOIN #CTE_HIDE_ETCH_BARCODE HEB
	ON O.WORKORDER_BASE_ID = HEB.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = HEB.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = HEB.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = HEB.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = 'W'
	AND O.SEQUENCE_NO = HEB.SEQUENCE_NO
LEFT OUTER JOIN SKILLS_PART_UDF AS PSA
	ON PSA.PART_ID = CASE WHEN SUPPLY_TYPE = 'CP' THEN COL.PART_ID ELSE NULL END
LEFT OUTER JOIN #CTE_WOLINK WL
	ON WL.WORKORDER_SUB_ID = W.SUB_ID
LEFT OUTER JOIN #CTE_OPERATIONS ORQ
	ON ORQ.WORKORDER_BASE_ID = W.BASE_ID
	AND ORQ.WORKORDER_LOT_ID = W.LOT_ID
	AND ORQ.WORKORDER_SPLIT_ID = W.SPLIT_ID
	AND ORQ.SUBORD_WO_SUB_ID = W.SUB_ID
	AND ORQ.WORKORDER_TYPE = W.[TYPE]
LEFT OUTER JOIN @REPORTSETTINGS RS
	ON SR.ID = RS.[RESOURCE]
LEFT OUTER JOIN LIVESUPPLEMENTAL.[DBO].[OPERATOR_VARIABLE_DATA] OVD
	ON O.RESOURCE_ID = OVD.RESOURCE_ID
	AND O.OPERATION_TYPE = OVD.OPERATION_TYPE_ID
LEFT OUTER JOIN #CTE_TIME_LIMIT TL
	ON O.WORKORDER_BASE_ID = TL.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = TL.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = TL.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = TL.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = TL.WORKORDER_TYPE
	AND O.SEQUENCE_NO = TL.SEQUENCE_NO
ORDER BY W.BASE_ID
	, W.LOT_ID
	, W.SPLIT_ID
	, W.SUB_ID
	, W.PART_ID
	, O.SEQUENCE_NO
	, O.PIECE_NO
	, CASE 
		WHEN W.WO_SPECS IS NULL THEN CAST(CAST(O.RQ_BITS AS VARBINARY(MAX))AS NVARCHAR(MAX))
		ELSE W.WO_SPECS
	END
	, COL.LINE_NO


/*
select * from LIVESupplemental.dbo.ResourceID_ReportSettings RS2
where RS2.Report_Name = 'traveller'
and Report_Section in ('Chem_to_Prime_hrs', 'Clean_to_Solgel_hrs', 'Start_Op_to_SOLGEL')
*/