USE LIVE
GO

/******************************************************************************************
Author :  Vivian M Elia
Create date :  1/22/2020
Description :  Work Order Traveller
Notes : 
--> tt20200728: N'MFG-REVIEW', N'BOM-REVIEW', N'COMPLEX-REVIEW' ADDED PER SHANNEN HELLE
--> tt20210225: EXPEDITE AND NEWPART STAMPS
--> tt20210309: N'FIN-REVIEW' ADDED PER SHANNEN/KEITHW
--> tt20210316: UPDATE N'STAGING', N'AREVIEW2', N'CMPFL-REVIEW', N'CM-REVIEW', N'CM-REVIEW1'
		, N'FIN-REVIEW', N'MFG-REVIEW', N'REVIEW', N'REVIEW-FAI' FOR BARCODE AND BY/DATE FIELDS
--> tt20210426: add OP_Types 'MFG-ORDER-ENTRY', 'FIN-ORDER-ENTRY'; NOTHING BUT BINARY TO DISPLAY --Ticket #506
--> mp20210611: account for requirements w/ different usage UM
--> tt20211004: removed erroneous Time Limits logic for Chem-Paint and Solgel
				pointing to ReportSettings_ResourceID instead of ResourceID_ReportSettings
				general clean up of code formatting
--> tt20211004:	Document duplication
--> tt20211021: remove Operational documents
******************************************************************************************/
DECLARE @BASE_ID NVARCHAR(30) = '1674639' --'1668108' '1584829' '1584826' 1562491
DECLARE @LOT_ID NVARCHAR(3) = '1'
DECLARE @SPLIT_ID NVARCHAR(3)= '0'
DECLARE @SUB_ID NVARCHAR(3) = '0'

DECLARE @PART_ID NVARCHAR(30) -- = '411T3484-66B'
SELECT @PART_ID = PART_ID 
FROM WORK_ORDER WO
WHERE WO.BASE_ID = @BASE_ID
    AND WO.LOT_ID = @LOT_ID
    AND WO.SUB_ID = N'0'
    AND WO.SPLIT_ID = @SPLIT_ID
    AND WO.[TYPE] = N'W'

IF OBJECT_ID('tempdb..#CTE_WORKORDERS') IS NOT NULL DROP TABLE #CTE_WORKORDERS
IF OBJECT_ID('tempdb..#CTE_COPRODUCTS') IS NOT NULL DROP TABLE #CTE_COPRODUCTS  
IF OBJECT_ID('tempdb..#CTE_OPERATIONS') IS NOT NULL DROP TABLE #CTE_OPERATIONS
IF OBJECT_ID('tempdb..#CTE_FAI') IS NOT NULL DROP TABLE #CTE_FAI
IF OBJECT_ID('tempdb..#CTE_WOLINK') IS NOT NULL DROP TABLE #CTE_WOLINK
IF OBJECT_ID('tempdb..#CTE_HIDE_ETCH_BARCODE') IS NOT NULL DROP TABLE #CTE_HIDE_ETCH_BARCODE
IF OBJECT_ID('tempdb..#CTE_TIME_LIMIT') IS NOT NULL DROP TABLE #CTE_TIME_LIMIT

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DEADLOCK_PRIORITY LOW

DECLARE @ReportSettings TABLE(
	[Resource] [nvarchar](15) NOT NULL,
	[barcode_etch] [int] NULL,
	[barcode_pre_etch] [int] NULL,
	[barcode_review] [int] NULL,
	[Chem_to_Prime_hrs] [int] NULL,
	[Clean_to_Solgel_hrs] [int] NULL,
	[FAI_NET_STAMP] [int] NULL,
	[FAI_STAMP] [int] NULL,
	[heightchange] [int] NULL,
	[printuser] [int] NULL,
	[QTY_IN] [int] NULL,
	[QTY_NOSHOW] [int] NULL,
	[QTY_OUT] [int] NULL,
	[SHIP_VIA] [int] NULL,
	[STAMP] [int] NULL,
	[Start_Op_to_SOLGEL] [int] NULL
    ) 
 
INSERT INTO @ReportSettings
SELECT [Resource]
	, [barcode_etch]
	, [barcode_pre_etch]
	, [barcode_review]
	, [Chem_to_Prime_hrs]
	, [Clean_to_Solgel_hrs]
	, [FAI_NET_STAMP]
	, [FAI_STAMP]
	, [heightchange]
	, [printuser]
	, [QTY_IN]
	, [QTY_NOSHOW]
	, [QTY_OUT]
	, [SHIP_VIA]
	, [STAMP]
	, [Start_Op_to_SOLGEL] 
FROM (SELECT [Resource]
	, CAST([Include] AS INT) AS [Include]
	, Report_Section
	FROM (SELECT [Resource_ID] AS [Resource], [Report_Name], [Report_Section], [Reasoning], [Notes], [Include]
		FROM LIVESupplemental.dbo.[ReportSettings_ResourceID] 
		WHERE Report_Name = N'Traveller'
	) A
--	WHERE A.Report_Name = N'Traveller'
	) X
PIVOT(MAX([INCLUDE])
	FOR Report_Section IN ([barcode_etch], [barcode_pre_etch], [barcode_review], [Chem_to_Prime_hrs], [Clean_to_Solgel_hrs]
		, [FAI_NET_STAMP], [FAI_STAMP], [heightchange], [printuser], [QTY_IN], [QTY_NOSHOW], [QTY_OUT], [SHIP_VIA], [STAMP]
		, [Start_Op_to_SOLGEL]
		)
)P
--SELECT * FROM @ReportSettings

SELECT WO.* 
	, CONVERT(NVARCHAR(MAX), CONVERT(VARBINARY(MAX), WB.BITS)) AS WO_SPECS
	, P.[DESCRIPTION]
	, SA.SURFACE_AREA
	, SA.Alloy
	, SA.Material_Type
	, SA.material_type + N' ' + SA.alloy + N' ' + CONVERT(VARCHAR(15), CONVERT(DECIMAL(5,2), SA.Thickness_val)) + N' x '
		+ CONVERT(VARCHAR(15), CONVERT(DECIMAL(5,2), SA.width_val)) + N' x ' + CONVERT(VARCHAR(15), CONVERT(DECIMAL(5,2), SA.length_val)) AS sa_description2
INTO #CTE_WORKORDERS
FROM WORK_ORDER WO
LEFT OUTER JOIN WORKORDER_BINARY AS WB
	ON WB.WORKORDER_TYPE = WO.[TYPE]
	AND WB.WORKORDER_BASE_ID = WO.BASE_ID
	AND WB.WORKORDER_LOT_ID = WO.LOT_ID
	AND WB.WORKORDER_SPLIT_ID = WO.SPLIT_ID
	AND WB.WORKORDER_SUB_ID = WO.SUB_ID
INNER JOIN PART P
	ON P.ID = WO.PART_ID
LEFT OUTER JOIN DBO.SKILLS_WO_INC_LEG_SURFACE_AREA AS SA
	ON WO.BASE_ID = SA.BASE_ID
	AND WO.LOT_ID = SA.LOT_ID
	AND WO.SPLIT_ID = SA.SPLIT_ID
	AND WO.PART_ID = SA.PART_ID
	--AND W.SUB_ID = SA.SUB_ID
WHERE WO.BASE_ID = @BASE_ID
	AND WO.LOT_ID = @LOT_ID
	AND WO.SPLIT_ID = @SPLIT_ID
	--AND WO.SUB_ID IN (@SUB_ID)
	AND WO.[TYPE] = N'W'

-- CO-PRODUCTS
SELECT CP.WORKORDER_TYPE
	, CP.WORKORDER_BASE_ID
	, CP.WORKORDER_LOT_ID
	, CP.WORKORDER_SPLIT_ID
	, CP.WORKORDER_SUB_ID
	, CP.PART_ID
	, CP.DESIRED_QTY
	, CP.RECEIVED_QTY
	, P.[DESCRIPTION]
	, SA.SURFACE_AREA
	, SA.Alloy
	, SA.Material_Type
	, SA.material_type + N' ' + SA.alloy + N' ' + CONVERT(VARCHAR(15),CONVERT(DECIMAL(5,2), SA.Thickness_val)) + ' x '
		+ CONVERT(VARCHAR(15), CONVERT(DECIMAL(5,2),sa.width_val)) + N' x ' + CONVERT(VARCHAR(15), CONVERT(DECIMAL(5,2), SA.length_val)) AS sa_description2 
INTO #CTE_COPRODUCTS
FROM CO_PRODUCT CP
INNER JOIN #CTE_WORKORDERS WO
	ON CP.WORKORDER_TYPE = WO.[TYPE]
	AND CP.WORKORDER_BASE_ID = WO.BASE_ID
	AND CP.WORKORDER_LOT_ID = WO.LOT_ID
	AND CP.WORKORDER_SPLIT_ID = WO.SPLIT_ID
	AND CP.WORKORDER_SUB_ID = WO.SUB_ID
INNER JOIN PART P
	ON P.ID = CP.PART_ID 
LEFT OUTER JOIN DBO.SKILLS_WO_INC_LEG_SURFACE_AREA SA
	ON CP.WORKORDER_BASE_ID = SA.BASE_ID
	AND CP.WORKORDER_LOT_ID = SA.LOT_ID
	AND CP.WORKORDER_SPLIT_ID = SA.SPLIT_ID
	AND CP.WORKORDER_SUB_ID = SA.SUB_ID
--SELECT * FROM #CTE_COPRODUCTS
--SELECT * FROM #CTE_WORKORDERS

SELECT O.*
	, CASE 
		WHEN EXISTS (SELECT 1 FROM @ReportSettings RS
			WHERE RS.FAI_NET_STAMP = 1 
				AND O.RESOURCE_ID = RS.[Resource]
			) 
			AND O.OPERATION_TYPE IN (N'FAI-NI', N'QP-NI', N'SFI-NI')
			THEN N'FIRST ARTICLE INSPECTION REQUIRED NET INSPECT' 
		ELSE NULL
	END AS FAI_NET_STAMP
	, CASE 
		WHEN EXISTS (SELECT 1 FROM @ReportSettings RS
			WHERE RS.FAI_STAMP = 1 
				AND O.RESOURCE_ID = RS.[Resource]
			)
			AND O.OPERATION_TYPE NOT IN (N'FAI-NI', N'QP-NI', N'SFI-NI')
			THEN N'FIRST ARTICLE INSPECTION REQUIRED' 
		ELSE NULL
	END AS FAI_STAMP
	, CASE 
		WHEN EXISTS (SELECT 1 FROM @ReportSettings RS
			WHERE RS.FAI_NET_STAMP = 1 
				AND O.RESOURCE_ID = RS.[Resource]
			) 
			AND O.OPERATION_TYPE IN (N'FAI-NI', N'QP-NI', N'SFI-NI')
			THEN N'FIRST ARTICLE INSPECTION REQUIRED NET INSPECT' 
		WHEN EXISTS (SELECT 1 FROM @ReportSettings RS
			WHERE RS.FAI_STAMP = 1 
				AND O.RESOURCE_ID = RS.[Resource]
			)
			AND O.OPERATION_TYPE NOT IN (N'FAI-NI', N'QP-NI', N'SFI-NI')
			THEN N'FIRST ARTICLE INSPECTION REQUIRED' 
		ELSE NULL
	END AS FAI_STAMP2
	, CASE 
--> tt20200122: 'AREVIEW2' REMOVED PER SHANNEN HELLE
--> tt20210309: N'FIN-REVIEW' ADDED PER SHANNEN HELLE
		WHEN O.OPERATION_TYPE IN (N'CMPFL-REVIEW', N'MFG-REVIEW', N'FIN-REVIEW') THEN 1 
		ELSE NULL 
	END AS NEWPART_STAMP
	, R.PIECE_NO
	, R.PART_ID AS RQ_PART_ID                              
	, RB.BITS AS RQ_BITS
	, OB.BITS AS O_BITS
	, RP.[DESCRIPTION] AS RQ_PART_DESCRIPTION
	, R.REQUIRED_DATE AS RQ_REQD_DATE
	, CASE WHEN ISNULL(RP.COMMODITY_CODE, N'.') IN (N'Standards', N'CFM-Standards') AND ISNULL(R.USAGE_UM, RP.STOCK_UM) != RP.STOCK_UM THEN R.USAGE_UM ELSE RP.STOCK_UM END AS RQ_PART_STOCK_UM
	, CASE WHEN ISNULL(RP.COMMODITY_CODE, N'.') IN (N'Standards', N'CFM-Standards') AND ISNULL(R.USAGE_UM, RP.STOCK_UM) != RP.STOCK_UM THEN ((R.QTY_PER * O.CALC_START_QTY) + R.FIXED_QTY) ELSE R.CALC_QTY END AS RQ_CALC_QTY
	, O.WORKORDER_TYPE + N'~' + O.WORKORDER_BASE_ID + N'~' + O.WORKORDER_SPLIT_ID + N'~' + O.WORKORDER_LOT_ID + N'~' + O.WORKORDER_SUB_ID + N'~' + CONVERT(VARCHAR(3), O.SEQUENCE_NO) AS O_UDFJOIN
	, R.SUBORD_WO_SUB_ID
	, NULL AS MIN_HOURS
INTO #CTE_OPERATIONS                                
FROM OPERATION O
LEFT OUTER JOIN REQUIREMENT R
	ON O.WORKORDER_BASE_ID = R.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = R.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = R.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = R.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = R.WORKORDER_TYPE
	AND O.SEQUENCE_NO = R.OPERATION_SEQ_NO
LEFT OUTER JOIN PART RP
	ON R.PART_ID = RP.ID
LEFT OUTER JOIN REQUIREMENT_BINARY RB
	ON R.WORKORDER_BASE_ID = RB.WORKORDER_BASE_ID
	AND R.WORKORDER_LOT_ID = RB.WORKORDER_LOT_ID
	AND R.WORKORDER_SPLIT_ID = RB.WORKORDER_SPLIT_ID
	AND R.WORKORDER_SUB_ID = RB.WORKORDER_SUB_ID
	AND R.WORKORDER_TYPE = RB.WORKORDER_TYPE
	AND R.OPERATION_SEQ_NO = RB.OPERATION_SEQ_NO
	AND R.PIECE_NO = RB.PIECE_NO
LEFT OUTER JOIN OPERATION_BINARY ob
	ON O.WORKORDER_BASE_ID = OB.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = OB.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = OB.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = OB.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = OB.WORKORDER_TYPE
	AND O.SEQUENCE_NO = OB.SEQUENCE_NO
LEFT OUTER JOIN SHOP_RESOURCE_SITE SRS
	ON O.RESOURCE_ID = SRS.RESOURCE_ID
WHERE O.WORKORDER_BASE_ID = @BASE_ID
	AND O.WORKORDER_LOT_ID = @LOT_ID
	AND O.WORKORDER_SPLIT_ID = @SPLIT_ID
	AND O.WORKORDER_TYPE = N'W'
--SELECT * FROM #cte_operations

/***************************************************************************************
GET DOCUMENTS FROM MASTER
***************************************************************************************/
; WITH CTE_DOCS AS
(SELECT DRW.* 
	, D.REVISION_ID
	, D.ECN_REVISION
	, U1.STRING_VAL AS ADCN
	, U2.STRING_VAL AS LOC
	, D.ID AS PART_ID
FROM DOCUMENT_REF_WO DRW
JOIN DOCUMENT D
	ON DRW.DOCUMENT_ID = D.ID
LEFT OUTER JOIN USER_DEF_FIELDS U1
	ON DRW.DOCUMENT_ID = U1.DOCUMENT_ID
	AND U1.PROGRAM_ID = N'VMDOCMNT'
	AND U1.ID = N'UDF-0000032'
	AND U1.[LABEL] IS NULL
LEFT OUTER JOIN USER_DEF_FIELDS U2
	ON DRW.DOCUMENT_ID = U2.DOCUMENT_ID
	AND U2.PROGRAM_ID = N'VMDOCMNT'
	AND U2.ID = N'UDF-0000031'
	AND U2.[LABEL] IS NULL
WHERE EXISTS (SELECT 1 FROM #CTE_WORKORDERS W
	WHERE W.PART_ID = DRW.WORKORDER_BASE_ID -- LINKS TO MASTER
	AND W.SUB_ID = N'0'  -- LINKS TO MASTER
	) 
--> tt20211021: remove Operational documents
	AND DRW.SEQUENCE_NO = '0'
)
--> SELECT * FROM #CTE_WORKORDERS
--> SELECT * FROM CTE_DOCS

SELECT DISTINCT DD.WORKORDER_BASE_ID
	, N'0' AS WORKORDER_SUB_ID
	, (SELECT ISNULL(D.DOCUMENT_ID, N'') + N' / REV: ' + ISNULL(D.REVISION_ID, N'') + N' / ADCN: ' + ISNULL(D.ADCN, N'') + N' / LOC: ' + ISNULL(D.LOC, N'') + CHAR(10)
		FROM CTE_DOCS D
--> tt20211004:	Document duplication
		GROUP BY ISNULL(D.DOCUMENT_ID, N'') + N' / REV: ' + ISNULL(D.REVISION_ID, N'') + N' / ADCN: ' + ISNULL(D.ADCN, N'') + N' / LOC: ' + ISNULL(D.LOC, N'') + CHAR(10)
		FOR XML PATH('')
	) AS VALS
INTO #CTE_WOLINK
FROM CTE_DOCS DD

UNION ALL 

SELECT DISTINCT DD.WORKORDER_BASE_ID
	, DD.WORKORDER_SUB_ID
	, (SELECT ISNULL(D.DOCUMENT_ID, N'') + N' / REV: ' + ISNULL(D.REVISION_ID, N'') + N' / ADCN: ' + ISNULL(D.ADCN, N'') + N' / LOC: ' + ISNULL(D.LOC, N'') + CHAR(10)
		FROM CTE_DOCS D
		WHERE (D.WORKORDER_BASE_ID = DD.WORKORDER_BASE_ID 
			AND D.WORKORDER_SUB_ID = DD.WORKORDER_SUB_ID)                                              
--> tt20211004:	Document duplication
		GROUP BY ISNULL(D.DOCUMENT_ID, N'') + N' / REV: ' + ISNULL(D.REVISION_ID, N'') + N' / ADCN: ' + ISNULL(D.ADCN, N'') + N' / LOC: ' + ISNULL(D.LOC, N'') + CHAR(10)
		FOR XML PATH('')
	) AS VALS
FROM CTE_DOCS DD
WHERE DD.WORKORDER_SUB_ID <> N'0'
GROUP BY DD.WORKORDER_BASE_ID
	, DD.WORKORDER_SUB_ID
-- SELECT * FROM #CTE_WOLINK

/******************************************************************************************
Get FAI information from Masters
******************************************************************************************/
SELECT CASE WHEN U1.BOOL_VAL = 1 THEN 'YES' ELSE 'NO' END AS FAI_COMPLETE 
	, SUBSTRING(U2.STRING_VAL, CHARINDEX('-', U2.STRING_VAL) + 1, 3) AS FAI_INITIALS
	, U3.DATE_VAL AS FAI_DATE_SIGNED
	, M.PART_ID
INTO #CTE_FAI
FROM WORK_ORDER M
LEFT OUTER JOIN USER_DEF_FIELDS U1
	ON U1.DOCUMENT_ID = N'M~' + M.BASE_ID + N'~' + M.SUB_ID + N'~' + M.LOT_ID + N'~' + M.SPLIT_ID  
	AND U1.PROGRAM_ID = N'VMMFGWIN_WO'
	AND U1.ID = N'UDF-0000086'
	AND U1.[LABEL] IS NULL
LEFT OUTER JOIN USER_DEF_FIELDS U2
	ON U2.DOCUMENT_ID = 'M~' + M.BASE_ID + N'~' + M.SUB_ID + N'~' + M.LOT_ID + N'~' + M.SPLIT_ID  
	AND U2.PROGRAM_ID = N'VMMFGWIN_WO'
	AND U2.ID = N'UDF-0000087'
	AND U2.[LABEL] IS NULL
LEFT OUTER JOIN USER_DEF_FIELDS U3
	ON U3.DOCUMENT_ID = 'M~' + M.BASE_ID + N'~' + M.SUB_ID + N'~' + M.LOT_ID + N'~' + M.SPLIT_ID  
	AND U3.PROGRAM_ID = N'VMMFGWIN_WO'
	AND U3.ID = N'UDF-0000088'
	AND U3.[LABEL] IS NULL
WHERE EXISTS (SELECT 1 FROM #CTE_WORKORDERS W WHERE W.PART_ID = M.BASE_ID AND W.SUB_ID = N'0')
-- SELECT * FROM #CTE_FAI

SELECT A.*
	, CASE
		WHEN RS.REPORT_SECTION IS NOT NULL AND RS2.REPORT_SECTION IS NOT NULL THEN 1
		ELSE 0
	END AS HIDE_ETCH_BARCODE
INTO #CTE_HIDE_ETCH_BARCODE
FROM (SELECT O.WORKORDER_TYPE
		, O.WORKORDER_BASE_ID
		, O.WORKORDER_LOT_ID
		, O.WORKORDER_SPLIT_ID
		, O.WORKORDER_SUB_ID
		, O.SEQUENCE_NO
		, O.RESOURCE_ID
		, LEAD(O.SEQUENCE_NO) OVER(PARTITION BY O.WORKORDER_BASE_ID ORDER BY O.WORKORDER_BASE_ID
			, O.WORKORDER_LOT_ID, O.WORKORDER_SPLIT_ID, O.WORKORDER_SUB_ID, O.SEQUENCE_NO) AS NEXTSEQ
		, LEAD(O.RESOURCE_ID) OVER(PARTITION BY O.WORKORDER_BASE_ID ORDER BY O.WORKORDER_BASE_ID
			, O.WORKORDER_LOT_ID, O.WORKORDER_SPLIT_ID, O.WORKORDER_SUB_ID, O.SEQUENCE_NO) AS NEXTRESOURCE
	FROM OPERATION AS O
	WHERE O.WORKORDER_BASE_ID = @BASE_ID
		AND O.WORKORDER_LOT_ID = @LOT_ID
		AND O.WORKORDER_SPLIT_ID = @SPLIT_ID
	) AS A
INNER JOIN LIVESupplemental.dbo.ReportSettings_ResourceID RS
	ON A.RESOURCE_ID = RS.RESOURCE_ID
	AND RS.Report_Name = N'Traveller'
INNER JOIN LIVESupplemental.dbo.ReportSettings_ResourceID RS2
	ON A.NEXTRESOURCE = RS2.RESOURCE_ID
	AND RS2.Report_Name = N'Traveller'
WHERE A.WORKORDER_BASE_ID = @BASE_ID
	AND A.WORKORDER_LOT_ID = @LOT_ID
	AND A.WORKORDER_SPLIT_ID = @SPLIT_ID
	AND A.WORKORDER_TYPE = N'W'
	AND RS.Report_Section IN (N'barcode_etch')
	AND RS2.Report_Section IN (N'barcode_pre_etch')

/******************************************************************************************
TIME LIMITS
******************************************************************************************/
SELECT ROW_NUMBER () OVER(ORDER BY O.WORKORDER_BASE_ID, O.WORKORDER_LOT_ID, O.WORKORDER_SPLIT_ID, O.WORKORDER_SUB_ID, O.SEQUENCE_NO) AS ROW_NUM_HRS
	, O.WORKORDER_TYPE
	, O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, CASE 
		WHEN (SELECT CONVERT(VARCHAR(12), CONVERT(SMALLINT, NUMBER_VAL))
			FROM USER_DEF_FIELDS UDF
			WHERE UDF.PROGRAM_ID = N'VMMFGWIN_OP'
				AND UDF.ID = N'UDF-0000089'             
				AND UDF.DOCUMENT_ID = N'W~' + O.WORKORDER_BASE_ID + N'~' + O.WORKORDER_SUB_ID + N'~' + O.WORKORDER_LOT_ID + N'~' + O.WORKORDER_SPLIT_ID + N'~' + CONVERT(NVARCHAR(3), O.SEQUENCE_NO)
			) IS NOT NULL 
			AND (SELECT CONVERT(VARCHAR(12), CONVERT(SMALLINT, NUMBER_VAL))
			FROM USER_DEF_FIELDS UDF
			WHERE UDF.PROGRAM_ID = N'VMMFGWIN_OP'
				AND UDF.ID = N'UDF-0000089'             
				AND UDF.DOCUMENT_ID = N'W~' + O.WORKORDER_BASE_ID + N'~' + O.WORKORDER_SUB_ID + N'~' + O.WORKORDER_LOT_ID + N'~' + O.WORKORDER_SPLIT_ID + N'~' + CONVERT(NVARCHAR(3), O.SEQUENCE_NO)
			) <> 0 THEN 1 
		ELSE 0 
	END AS IS_LIMIT_STARTER
	, CASE 
		WHEN (SELECT CONVERT(VARCHAR(12), CONVERT(SMALLINT, NUMBER_VAL))
			FROM USER_DEF_FIELDS UDF
			WHERE UDF.PROGRAM_ID = N'VMMFGWIN_OP' 
				AND UDF.ID = N'UDF-0000089'             
				AND UDF.DOCUMENT_ID = N'W~' + O.WORKORDER_BASE_ID + N'~' + O.WORKORDER_SUB_ID + N'~' + O.WORKORDER_LOT_ID + N'~' + O.WORKORDER_SPLIT_ID + N'~' + CONVERT(NVARCHAR(3), O.SEQUENCE_NO)
			) IS NOT NULL 
			AND (SELECT CONVERT(VARCHAR(12),CONVERT(SMALLINT, NUMBER_VAL))
			FROM USER_DEF_FIELDS UDF
			WHERE UDF.PROGRAM_ID = N'VMMFGWIN_OP' 
				AND UDF.ID = N'UDF-0000089'             
				AND UDF.DOCUMENT_ID = N'W~' + O.WORKORDER_BASE_ID + N'~' + O.WORKORDER_SUB_ID + N'~' + O.WORKORDER_LOT_ID + N'~' + O.WORKORDER_SPLIT_ID + N'~' + CONVERT(NVARCHAR(3), O.SEQUENCE_NO)
			) <> 0
			THEN (SELECT N'TIME LIMIT ' + CONVERT(VARCHAR(12), CONVERT(SMALLINT, NUMBER_VAL))
				FROM USER_DEF_FIELDS UDF
				WHERE UDF.PROGRAM_ID = N'VMMFGWIN_OP' 
					AND UDF.ID = N'UDF-0000089'             
					AND UDF.DOCUMENT_ID = N'W~' + O.WORKORDER_BASE_ID + N'~' + O.WORKORDER_SUB_ID + N'~' + O.WORKORDER_LOT_ID + N'~' + O.WORKORDER_SPLIT_ID + N'~' + CONVERT(NVARCHAR(3), O.SEQUENCE_NO)) + ' HOURS'
		ELSE NULL
	END AS MIN_HOURS
	, CASE 
		WHEN EXISTS (SELECT 1 FROM @ReportSettings RS WHERE RS.Chem_to_Prime_hrs = 1 AND O.RESOURCE_ID = RS.[Resource]) THEN 1 
		ELSE 0 
	END AS IS_LIMIT_ENDER
INTO #CTE_TIME_LIMIT
FROM #CTE_OPERATIONS O
WHERE O.WORKORDER_BASE_ID = @BASE_ID
	AND O.WORKORDER_LOT_ID = @LOT_ID
	AND O.WORKORDER_SPLIT_ID = @SPLIT_ID
--SELECT * FROM #CTE_CHEM_PAINT_OP 

/******************************************************************************************
FINAL DATASET RESULTS TO PRINT
******************************************************************************************/
SELECT CASE 
		WHEN TL.MIN_HOURS = N'TIME LIMIT 0 HOURS' THEN NULL 
		ELSE TL.MIN_HOURS 
	END AS TIME_LIMIT
	, O.WORKORDER_TYPE
	, O.WORKORDER_BASE_ID
	, O.WORKORDER_LOT_ID
	, O.WORKORDER_SPLIT_ID
	, O.WORKORDER_SUB_ID
	, O.SEQUENCE_NO
	, O.RESOURCE_ID
	, SR.[DESCRIPTION] AS RESOURCE_DESC
	, O.SERVICE_ID
	, O.OPERATION_TYPE
	, OT.[DESCRIPTION] AS OP_TYPE_DESC
	, O.VENDOR_ID
	, O.VENDOR_SERVICE_ID
	, O.RQ_PART_ID 
	, O.RQ_PART_DESCRIPTION
	, O.PIECE_NO
	, O.PIECE_NO AS RQ_PIECE
	, dbo.sfnWONUMFormat(O.WORKORDER_BASE_ID, O.WORKORDER_LOT_ID, O.WORKORDER_SPLIT_ID, O.WORKORDER_SUB_ID) AS WONUM
	, dbo.sfnWONUMFormat(O.WORKORDER_BASE_ID, O.WORKORDER_LOT_ID, O.WORKORDER_SPLIT_ID, O.WORKORDER_SUB_ID) AS WONUM_ID
	, O.WORKORDER_BASE_ID + N'/' + O.WORKORDER_LOT_ID + N'/' + O.WORKORDER_SPLIT_ID AS WO_ID
	, W.PART_ID
	, W.PART_ID AS WO_PART_ID
	, ISNULL(W.DESIRED_WANT_DATE, (SELECT TOP 1 W.DESIRED_WANT_DATE FROM #CTE_WORKORDERS W)) AS DESIRED_WANT_DATE
	, ISNULL(W.DESIRED_RLS_DATE, (SELECT TOP 1 W.DESIRED_RLS_DATE FROM #CTE_WORKORDERS W)) AS DESIRED_RLS_DATE
	, (SELECT TOP 1 W.ENGINEERED_BY FROM #CTE_WORKORDERS W WHERE SUB_ID = N'0') AS ENGINEERED_BY
	, O.WORKORDER_BASE_ID AS BASE_ID
	, O.WORKORDER_LOT_ID AS LOT_ID
	, O.WORKORDER_SUB_ID AS SUB_ID
	, O.WORKORDER_SPLIT_ID AS SPLIT_ID
	, CASE WHEN RS.STAMP IS NOT NULL THEN 1 ELSE 0 END AS STAMP                
	, CASE WHEN RS.HEIGHTCHANGE IS NOT NULL THEN 1 ELSE 0 END AS HEIGHTCHANGE
	, CASE WHEN RS.SHIP_VIA IS NOT NULL THEN CO.SHIP_VIA ELSE NULL END AS SHIP_VIA 
	, CASE    --> 1 = DISPLAY BARCODE;  0 = HIDE BARCODE
-->	tt20200728: N'BOM-REVIEW', N'COMPLEX-REVIEW', N'MFG-REVIEW' ADDED PER SHANNEN HELLE
--> tt20210309: N'FIN-REVIEW' ADDED PER SHANNEN/KEITHW
--> tt20210316: UPDATE N'STAGING', N'AREVIEW2', N'CMPFL-REVIEW', N'CM-REVIEW', N'CM-REVIEW1', N'FIN-REVIEW', N'MFG-REVIEW', N'REVIEW', N'REVIEW-FAI' FOR BARCODE AND BY/DATE FIELDS
		WHEN RS.BARCODE_REVIEW IS NOT NULL AND O.OPERATION_TYPE IN (N'STAGING', N'AREVIEW2', N'CMPFL-REVIEW', N'CM-REVIEW', N'CM-REVIEW1', N'FIN-REVIEW', N'MFG-REVIEW', N'REVIEW', N'REVIEW-FAI') THEN 0
--> TT20210426: NEW OPTYPES, NOTHING BUT BINARY TO DISPLAY
		WHEN O.OPERATION_TYPE IN (N'MFG-ORDER-ENTRY', N'FIN-ORDER-ENTRY') THEN 1
		WHEN RS.BARCODE_REVIEW IS NOT NULL AND O.OPERATION_TYPE IN (N'BOM-REVIEW', N'COMPLEX-REVIEW') THEN 0
		WHEN RS.BARCODE_REVIEW IS NOT NULL AND O.OPERATION_TYPE NOT IN (N'QP-REVIEW', N'QP-NI') THEN 1
		WHEN (W.PART_ID LIKE N'TOOLING%' OR W.PART_ID LIKE N'%TOOLING') AND W.SUB_ID <> N'0' THEN 1
		WHEN SR.AUTO_REPORTING = N'Y' THEN 1
		WHEN HEB.HIDE_ETCH_BARCODE = 1 THEN 1
		ELSE 0
	END AS BARCODE
	, CASE 
--> TT20210426: NEW OPTYPES, NOTHING BUT BINARY TO DISPLAY
		WHEN O.OPERATION_TYPE IN (N'MFG-ORDER-ENTRY', N'FIN-ORDER-ENTRY') THEN 1 
		WHEN O.OPERATION_TYPE IN (N'PRE-PULL', N'STAGING', N'REVIEW', N'QP-REVIEW', N'QP-NI','FAI', N'FAI-NI', N'PANEL', N'PROGM') THEN 1
		WHEN RS.QTY_IN IS NOT NULL THEN 0 
		ELSE 1
	END AS HIDE_QTY_IN
	, RS.QTY_OUT
	, CASE   --> 1 = DISPLAY QTY; 0 = HIDE QTY
--> tt20210316: UPDATE N'STAGING', N'AREVIEW2', N'CMPFL-REVIEW', N'CM-REVIEW', N'CM-REVIEW1', N'FIN-REVIEW', N'MFG-REVIEW', N'REVIEW', N'REVIEW-FAI' FOR BARCODE AND BY/DATE FIELDS
		WHEN O.OPERATION_TYPE IN (N'STAGING', N'AREVIEW2', N'CMPFL-REVIEW', N'CM-REVIEW', N'CM-REVIEW1', N'FIN-REVIEW', N'MFG-REVIEW', N'REVIEW', N'REVIEW-FAI') THEN CAST(0 AS BIT)
--> TT20210426: NEW OPTYPES, NOTHING BUT BINARY TO DISPLAY
		WHEN O.OPERATION_TYPE IN (N'MFG-ORDER-ENTRY', N'FIN-ORDER-ENTRY') THEN CAST(1 AS BIT) 
		WHEN RS.QTY_OUT IS NOT NULL THEN CAST(1 AS BIT)
		ELSE CAST(0 AS BIT)
	END AS HIDE_QTY_OUT
	, CASE   --> 1 = DISPLAY QTY; 0 = HIDE QTY
--> tt20210316: UPDATE N'STAGING', N'AREVIEW2', N'CMPFL-REVIEW', N'CM-REVIEW', N'CM-REVIEW1', N'FIN-REVIEW', N'MFG-REVIEW', N'REVIEW', N'REVIEW-FAI' FOR BARCODE AND BY/DATE FIELDS
		WHEN O.OPERATION_TYPE IN (N'STAGING', N'AREVIEW2', N'CMPFL-REVIEW', N'CM-REVIEW', N'CM-REVIEW1', N'FIN-REVIEW', N'MFG-REVIEW', N'REVIEW', N'REVIEW-FAI') THEN CAST(1 AS BIT)
--> TT20210426: NEW OPTYPES, NOTHING BUT BINARY TO DISPLAY
		WHEN O.OPERATION_TYPE IN (N'MFG-ORDER-ENTRY', N'FIN-ORDER-ENTRY') THEN CAST(1 AS BIT)
		WHEN RS.QTY_NOSHOW IS NOT NULL THEN CAST(1 AS BIT)
		ELSE CAST(0 AS BIT)
	END AS HIDE_QTY_NOSHOW
	, CASE WHEN RS.PRINTUSER IS NOT NULL THEN 1 ELSE 0 END AS PRINTUSER
--> For printing Part Mark user information
	, O.USER_1 
	, N'*' + SUBSTRING(REPLACE(O.USER_1, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_1, N' ', N'')) + 1, 80) + N'*' AS OP_USER_1
	, O.USER_2
	, N'*' + SUBSTRING(REPLACE(O.USER_2, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_2 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_2
	, O.USER_3
	, N'*' + SUBSTRING(REPLACE(O.USER_3, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_3 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_3
	, O.USER_4
	, N'*' + SUBSTRING(REPLACE(O.USER_4, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_4 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_4
	, O.USER_5
	, N'*' + SUBSTRING(REPLACE(O.USER_5, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_5 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_5
	, O.USER_6
	, N'*' + SUBSTRING(REPLACE(O.USER_6, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_6 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_6
	, O.USER_7
	, N'*' + SUBSTRING(REPLACE(O.USER_7, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_7 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_7
	, O.USER_8
	, N'*' + SUBSTRING(REPLACE(O.USER_8, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_8 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_8
	, O.USER_9
	, N'*' + SUBSTRING(REPLACE(O.USER_9, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_9 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_9
	, O.USER_10
	, N'*' + SUBSTRING(REPLACE(O.USER_10, N' ', N''), CHARINDEX(N':', REPLACE(O.USER_10 , N' ', N'')) + 1, 80) + N'*' AS OP_USER_10 
	, CO.CUSTOMER_ID
	, CO.ID AS CUST_ORDER_ID
	, COL.CUSTOMER_PART_ID
	, C.[NAME] AS CUST_NAME
	, CA.[NAME] AS CUST_ADDRNAME
	, W.[DESCRIPTION] AS WO_PART_DESCRIPTION
	, ISNULL(W.WO_SPECS, CONVERT(NVARCHAR(MAX), CONVERT(VARBINARY(MAX), ORQ.RQ_BITS))) AS WO_LONG_DESCR
	, CONVERT(DECIMAL(14,0), W.SURFACE_AREA) AS SURFACE_AREA
	, W.MATERIAL_TYPE
	, W.ALLOY 
	, W.SA_DESCRIPTION2
	, CAST(CAST(O.O_BITS AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS OP_LONG_DESCR 
	, O.RQ_REQD_DATE AS RQ_REQD
	, O.RQ_PART_STOCK_UM
	, O.RQ_CALC_QTY
--> ADDED 9/5/2019 VME FAI SIGNATURE ON WORK ORDER FROM MASTER
	, F.FAI_COMPLETE
	, F.FAI_INITIALS
	, F.FAI_DATE_SIGNED
--> ADDED 9/5/2019 VME REPLACES STAMP FOR FIRST ARTICLE INPECTION
	, O.FAI_STAMP
	, O.FAI_STAMP2
	, O.FAI_NET_STAMP 
--> 20210225tt: NEW PART STAMP UPDATE
	, CASE 
		WHEN O.OPERATION_TYPE IN (N'CMPFL-REVIEW', N'MFG-REVIEW', N'FIN-REVIEW') THEN N'NEW PART' -- THEN 1 --NEW PART
		WHEN EXISTS(SELECT 1 FROM USER_DEF_FIELDS UDF
			WHERE UDF.DOCUMENT_ID = W.[TYPE] + N'~'+ W.BASE_ID + N'~' + N'0' + N'~' + W.LOT_ID + N'~' + W.SPLIT_ID 
				AND UDF.PROGRAM_ID = N'VMMFGWIN_WO' 
				AND UDF.ID = N'UDF-0000061' 
				AND UDF.BOOL_VAL = 1)
			THEN N'NEW PART'
		ELSE NULL
	END AS NEWPART_STAMP2
--> 20210225tt: EXPEDITE STAMP
	, CASE 
		WHEN (SELECT TOP 1 UDF.STRING_VAL FROM USER_DEF_FIELDS UDF
			WHERE UDF.PROGRAM_ID = N'VMMFGWIN_WO' 
				AND UDF.ID = N'UDF-0000070' 
				AND ISNULL(UDF.[LABEL], N'') = N''
				AND W.[TYPE] + N'~' + W.BASE_ID + N'~' + N'0' + N'~' + W.LOT_ID + N'~' + W.SPLIT_ID = UDF.DOCUMENT_ID
			) IN (N'3_PD EXP') THEN 'EXPEDITE'
		WHEN (SELECT TOP 1 UDF.STRING_VAL FROM USER_DEF_FIELDS UDF
			WHERE UDF.PROGRAM_ID = N'VMMFGWIN_WO' 
				AND UDF.ID = N'UDF-0000070' 
				AND ISNULL(UDF.[LABEL], N'') = N''
				AND W.[TYPE] + N'~' + W.BASE_ID + N'~' + N'0' + N'~' + W.LOT_ID + N'~' + W.SPLIT_ID = UDF.DOCUMENT_ID
			) IN ('4_PD EXP/FLT') THEN 'EXPEDITE'
		WHEN EXISTS(SELECT 1 FROM USER_DEF_FIELDS UDF
			WHERE UDF.PROGRAM_ID = N'VMMFGWIN_WO' 
				AND UDF.ID = N'UDF-0000060' 
				AND UDF.BOOL_VAL = 1
				AND W.[TYPE] + N'~' + W.BASE_ID + N'~' + N'0' + N'~' + W.LOT_ID + N'~' + W.SPLIT_ID = UDF.DOCUMENT_ID
			) THEN N'EXPEDITE'
		ELSE NULL
	END AS EXPEDITE_STAMP
	, CASE 
		WHEN EXISTS (SELECT 1 FROM USER_DEF_FIELDS 
			WHERE DOCUMENT_ID = W.PART_ID 
				AND PROGRAM_ID = N'VMPRTMNT' 
				AND ID = N'UDF-0000040' 
				AND BOOL_VAL = 1
			) THEN N'ITAR Controlled'
		WHEN W.PART_ID LIKE N'737RIB-KIT-PROD%' THEN N'Tags must remain on parts throughout entire process!'
		WHEN W.PART_ID LIKE N'737RIB-MAX-KIT-PROD%' THEN N'Tags must remain on parts throughout entire process!'
		ELSE N''
	END AS MESSAGE
	, CASE 
		WHEN DSL.SUPPLY_TYPE = N'CP' AND COL.LINE_NO = (SELECT MIN(CL1.LINE_NO) FROM DBO.CUST_ORDER_LINE AS CL1
			INNER JOIN DBO.DEMAND_SUPPLY_LINK AS DSL1
				ON CL1.CUST_ORDER_ID = DSL1.DEMAND_BASE_ID
				AND CL1.PART_ID = DSL1.SUPPLY_PART_ID
				AND DSL1.SUPPLY_BASE_ID = @BASE_ID  -- CHANGED 6/10/2014
				AND DSL1.SUPPLY_LOT_ID = @LOT_ID
				AND DSL1.SUPPLY_SPLIT_ID = @SPLIT_ID
				AND DSL1.SUPPLY_TYPE = N'CP' 
			) THEN 0 
	END AS CP_FIRST_PART
	, CASE WHEN DSL.SUPPLY_TYPE = N'CP' THEN COL.PART_ID ELSE NULL END AS CP_PART 
	, DSL.SUPPLY_TYPE
	, COL.LINE_NO
	, SA.DESIRED_QTY AS CP_QTY 
	, SA.[DESCRIPTION] AS CP_DESCRIPTION
	, SA.SA_DESCRIPTION2 AS CP_DESCRIPTION2
	, CASE WHEN ISNULL(SUPPLY_TYPE, N'WO') = N'WO' THEN COL.CUSTOMER_PART_ID ELSE NULL END AS WO_CUSTOMER_PART_ID
	, CASE WHEN SUPPLY_TYPE = N'CP' THEN COL.CUSTOMER_PART_ID ELSE NULL END AS CP_CUSTOMER_PART_ID
	, SR.AUTO_REPORTING
	, OVD.LINE_NUM AS OVD_LINE_NO
	, OVD.LABEL_YN AS LABELYN
	, OVD.PROMPT AS OVD_PROMPT
	, O.SUBORD_WO_SUB_ID AS RQ_SUB_ID
	, CO.CUSTOMER_PO_REF
	, W.DESIRED_QTY
	, WL.VALS AS WO_LINK
	, CONVERT(NVARCHAR(MAX), CONVERT(VARBINARY(MAX), ORQ.RQ_BITS)) AS REQ_SPECS
	, dbo.sfnGetCustSpecsString(O.WORKORDER_TYPE + N'~' + O.WORKORDER_BASE_ID + N'~' + O.WORKORDER_SUB_ID + N'~' + O.WORKORDER_LOT_ID + N'~' + O.WORKORDER_SPLIT_ID + N'~' + CAST(O.SEQUENCE_NO AS NVARCHAR(3))) AS CUSTSPECSSTRING
FROM #CTE_WORKORDERS W
INNER JOIN #CTE_OPERATIONS o
	ON W.BASE_ID = O.WORKORDER_BASE_ID
	AND W.LOT_ID = O.WORKORDER_LOT_ID
	AND W.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND W.SUB_ID = O.WORKORDER_SUB_ID
	AND W.[TYPE] = O.WORKORDER_TYPE
LEFT OUTER JOIN OPERATION_TYPE OT
	ON O.OPERATION_TYPE = OT.ID
LEFT OUTER JOIN SHOP_RESOURCE SR
	ON SR.ID = O.RESOURCE_ID
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
	INNER JOIN PART P
		ON DSL.SUPPLY_PART_ID = P.ID 
	ON DSL.SUPPLY_BASE_ID = w.BASE_ID
	AND DSL.SUPPLY_LOT_ID = w.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = w.SPLIT_ID
	--AND DSL.SUPPLY_SUB_ID = w.SUB_ID
	AND DSL.SUPPLY_TYPE IN (N'WO', N'CP')
LEFT OUTER JOIN CUST_ORDER_LINE COL
	ON DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO  = COL.LINE_NO
LEFT OUTER JOIN CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
LEFT OUTER JOIN CUSTOMER AS C
	ON C.ID = CO.CUSTOMER_ID
LEFT OUTER JOIN CUST_ADDRESS AS CA
	ON CO.CUSTOMER_ID = CA.CUSTOMER_ID
	AND CO.SHIP_TO_ADDR_NO = CA.ADDR_NO
LEFT OUTER JOIN #CTE_COPRODUCTS AS SA
	ON W.BASE_ID = SA.WORKORDER_BASE_ID
	AND W.LOT_ID = SA.WORKORDER_LOT_ID
	AND W.SPLIT_ID = SA.WORKORDER_SPLIT_ID
	AND W.SUB_ID = SA.WORKORDER_SUB_ID
	AND W.[TYPE] = SA.WORKORDER_TYPE
LEFT OUTER JOIN #CTE_FAI F
	ON F.PART_ID = W.PART_ID
--> added 8/31/2018 VME -- needs to be optimized
LEFT OUTER JOIN #CTE_HIDE_ETCH_BARCODE HEB
	ON O.WORKORDER_BASE_ID = HEB.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = HEB.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = HEB.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = HEB.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = N'W'
	AND O.SEQUENCE_NO = HEB.SEQUENCE_NO
--> needs to be optimized  
LEFT OUTER JOIN SKILLS_PART_UDF AS PSA
	ON PSA.PART_ID = CASE WHEN SUPPLY_TYPE = N'CP' THEN COL.PART_ID ELSE NULL END
LEFT OUTER JOIN #CTE_WOLINK WL
	ON WL.WORKORDER_SUB_ID = W.SUB_ID
LEFT OUTER JOIN #CTE_OPERATIONS oRq
	ON oRq.WORKORDER_BASE_ID = W.BASE_ID
	AND oRq.WORKORDER_LOT_ID = W.LOT_ID
	AND oRq.WORKORDER_SPLIT_ID = W.SPLIT_ID
	AND oRq.SUBORD_WO_SUB_ID = W.SUB_ID
	AND oRq.WORKORDER_TYPE = W.[TYPE]
LEFT OUTER JOIN @ReportSettings RS
	ON SR.ID = RS.[Resource]
LEFT OUTER JOIN LIVESUPPLEMENTAL.[DBO].[OPERATOR_VARIABLE_DATA] OVD
	ON O.RESOURCE_ID = OVD.RESOURCE_ID
	AND O.OPERATION_TYPE = OVD.OPERATION_TYPE_ID
LEFT OUTER JOIN #CTE_TIME_LIMIT TL
	ON O.WORKORDER_BASE_ID = TL.WORKORDER_BASE_ID
	AND O.WORKORDER_LOT_ID = TL.WORKORDER_LOT_ID
	AND O.WORKORDER_SPLIT_ID = TL.WORKORDER_SPLIT_ID
	AND O.WORKORDER_SUB_ID = TL.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = TL.WORKORDER_TYPE
	AND O.SEQUENCE_NO = TL.SEQUENCE_NO
ORDER BY W.BASE_ID
	, W.LOT_ID
	, W.SPLIT_ID
	, W.SUB_ID
	, W.PART_ID
	, O.SEQUENCE_NO
	, O.PIECE_NO
	, CASE 
		WHEN W.WO_SPECS IS NULL THEN CAST(CAST(O.RQ_BITS AS VARBINARY(MAX))AS NVARCHAR(MAX))
		ELSE W.WO_SPECS
	END
	, COL.LINE_NO