
SELECT SR.ID
, SR.[DESCRIPTION]
, SR.[STATUS]
FROM LIVE.dbo.SHOP_RESOURCE SR
LEFT OUTER JOIN [LIVESupplemental].[dbo].[ResourceID_ReportSettings] R
ON R.Resource_ID = SR.ID
AND R.REPORT_NAME = 'TRAVELLER'
WHERE R.Resource_ID IS NULL
AND SR.[DESCRIPTION] NOT LIKE 'DO NOT USE%'
AND SR.ID != 'TIMEKEEPING'

SELECT *
FROM [LIVESupplemental].[dbo].[ResourceID_ReportSettings]
WHERE REPORT_NAME = 'TRAVELLER'

DECLARE @REPORTSETTINGS TABLE(
    [RESOURCE] [NVARCHAR](15) NOT NULL
    , [BARCODE_ETCH] [INT] NULL
    , [BARCODE_PRE_ETCH] [INT] NULL
    , [BARCODE_REVIEW] [INT] NULL
    , [CHEM_TO_PRIME_HRS] [INT] NULL
    , [CLEAN_TO_SOLGEL_HRS] [INT] NULL
    , [FAI_NET_STAMP] [INT] NULL
    , [FAI_STAMP] [INT] NULL
    , [HEIGHTCHANGE] [INT] NULL
    , [PRINTUSER] [INT] NULL
    , [QTY_IN] [INT] NULL
    , [QTY_NOSHOW] [INT] NULL
    , [QTY_OUT] [INT] NULL
    , [SHIP_VIA] [INT] NULL
    , [STAMP] [INT] NULL
    , [START_OP_TO_SOLGEL] [INT] NULL
    ) 
 
INSERT INTO @REPORTSETTINGS
SELECT [RESOURCE]
	, [BARCODE_ETCH]
	, [BARCODE_PRE_ETCH]
	, [BARCODE_REVIEW]
	, [CHEM_TO_PRIME_HRS]
	, [CLEAN_TO_SOLGEL_HRS]
	, [FAI_NET_STAMP]
	, [FAI_STAMP]
	, [HEIGHTCHANGE]
	, [PRINTUSER]
	, [QTY_IN]
	, [QTY_NOSHOW]
	, [QTY_OUT]
	, [SHIP_VIA]
	, [STAMP]
	, [START_OP_TO_SOLGEL] 
FROM
	(SELECT [RESOURCE]
		, CAST([INCLUDE] AS INT) AS [INCLUDE]
		, REPORT_SECTION
	FROM 
		(SELECT [RESOURCE_ID] AS [RESOURCE]
			, [REPORT_NAME]
			, [REPORT_SECTION]
			, [REASONING]
			, [NOTES]
			, [INCLUDE]
		FROM [SQL-BI-1].LIVESUPPLEMENTAL.DBO.[RESOURCEID_REPORTSETTINGS] 
		) A
	WHERE A.REPORT_NAME = 'TRAVELLER'
	) X
PIVOT
(MAX([INCLUDE])
	FOR REPORT_SECTION IN ([BARCODE_ETCH]
		, [BARCODE_PRE_ETCH]
		, [BARCODE_REVIEW]
		, [CHEM_TO_PRIME_HRS]
		, [CLEAN_TO_SOLGEL_HRS]
		, [FAI_NET_STAMP]
		, [FAI_STAMP]
		, [HEIGHTCHANGE]
		, [PRINTUSER]
		, [QTY_IN]
		, [QTY_NOSHOW]
		, [QTY_OUT]
		, [SHIP_VIA]
		, [STAMP]
		, [START_OP_TO_SOLGEL]
	)
) P 

SELECT * FROM @REPORTSETTINGS rs