USE LIVE
GO

DECLARE @LOC_ID NVARCHAR(50) = 'S5'

DROP TABLE #T1

SELECT * 
INTO #T1
FROM PART_LOCATION WHERE LOCKED = 'Y' 
--AND [STATUS] = 'A' 
--AND LOCATION_ID = @LOC_ID 

SELECT * FROM #T1

/*
BEGIN TRANSACTION;
UPDATE PART_LOCATION 
SET LOCKED = 'N'
FROM PART_LOCATION PL
INNER JOIN #T1 T
ON T.PART_ID = PL.PART_ID
AND T.LOCATION_ID = PL.LOCATION_ID 
AND T.[STATUS] = PL.[STATUS] 
--> 70 ROWS UPDATED
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/

SELECT * 
FROM PART_LOCATION WHERE LOCATION_ID = @LOC_ID AND [STATUS] = 'A' AND LOCKED = 'Y'
