SELECT PO.ID AS PO
	, PO.VENDOR_ID
	, PO.TOTAL_AMT_ORDERED
	, R.ID AS RECEIVER
	, R.RECEIVED_DATE 
FROM PURCHASE_ORDER PO
LEFT OUTER JOIN [DBO].[USER_DEF_FIELDS] PREPAIDCC (NOLOCK)
	ON PREPAIDCC.DOCUMENT_ID = PO.ID
	AND PREPAIDCC.PROGRAM_ID = 'VMPURENT'
	AND PREPAIDCC.DOCUMENT_ID IS NOT NULL
	AND PREPAIDCC.ID ='UDF-0000100'
LEFT OUTER JOIN PURC_ORDER_LINE POL
	ON POL.PURC_ORDER_ID = PO.ID
LEFT OUTER JOIN PAYABLE_LINE PL
	ON PL.PURC_ORDER_ID = POL.PURC_ORDER_ID
	AND PL.PURC_ORDER_LINE_NO = POL.LINE_NO
LEFT OUTER JOIN PAYABLE P
	ON P.VOUCHER_ID = PL.VOUCHER_ID
LEFT OUTER JOIN RECEIVER_LINE RL
	ON RL.PURC_ORDER_ID = POL.PURC_ORDER_ID
	AND RL.PURC_ORDER_LINE_NO = POL.LINE_NO
LEFT OUTER JOIN RECEIVER R
	ON R.ID = RL.RECEIVER_ID
WHERE P.VOUCHER_ID IS NULL
	AND R.ID IS NOT NULL


