USE LIVE
GO

SELECT * FROM PART WHERE ID = '737RIB-MAX-KIT-PROD-9F'
SELECT * FROM PART WHERE ID = '737RIB-MAX-KIT-PROD-9-F'
SELECT * FROM PART WHERE ID = '737RIB-MAX-KIT-PROD-9--F'

/*
BEGIN TRANSACTION;
UPDATE CUST_ORDER_LINE
SET PART_ID = '737RIB-MAX-KIT-PROD-9--F'
WHERE CUST_ORDER_ID = '477137'
AND LINE_NO = '3'

UPDATE WORK_ORDER
SET PART_ID = '737RIB-MAX-KIT-PROD-9--F'
WHERE BASE_ID = '1679603B'
AND LOT_ID = '9'
AND SPLIT_ID = '0'
AND SUB_ID = '0'
--> COMMIT TRANSACTION;
--> ROLLBACK TRANSACTION;
*/ 

SELECT * FROM WORK_ORDER
WHERE BASE_ID = '1675454'
AND LOT_ID = '9'
AND SPLIT_ID = '0'
AND SUB_ID = '0'

SELECT * FROM CUST_ORDER_LINE
WHERE CUST_ORDER_ID = '477137'
AND LINE_NO = '1'
