USE DataWarehouse
GO

SELECT EE.ID AS EMPLOYEE_ID
FROM EMPLOYEE EE
INNER JOIN LIVESupplemental.dbo.EMP_ADP ADP
ON EE.ID = ADP.Empid
WHERE EE.[USER_ID] IS NOT NULL 
AND EE.EMAIL_ADDR IS NULL
AND NOT EXISTS
	(SELECT 1
	FROM LIVESupplemental.dbo.USER_NO_EMAIL EML
	WHERE EML.EMPLOYEE_ID = EE.ID
	)

