USE [LIVE]
GO

/****** Object:  StoredProcedure [dbo].[usp_WODS_ETL02]    Script Date: 7/12/2021 10:06:21 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



/* =============================================
-- Author:		Eric Shafer 
-- Create date: 5/25/2018
-- Description:	Data set for the Work Order Daily Status report.
-- Update: tt20181111 - Added AP1_BUYER_Michele aggregate for buyer MicheleC; Changed Sunni's aggregate from AP1_BUYER_Michele to AP1_BUYER_Sunni
-- Update: tt20190424 - added shop_resources_view fields - USER_2, USER_3, Supervisor's email_addr
-- Update: tt20190723 - added LTRIM(RTRIM(sr.USER_4))
-- Update: tt20190816 - updated new salesreps
-- update: vme 20190822 - updated work order desired_rls_date for legs (added case statement)
			updated purchase order desired_recv_date to include promise_ship_date  
			updated notes field to add customer user_1 for Boeing To OSP date (when planned work order is planned to go to outside processing.)
			updated col.user_10 to col.user_1 per request from Ann
-- update: vme/wt 20190822 - removed stored procedure GetReportSettings and incoporated into this stored procedure
			created temp tables with temp indexes to optimize user_def_fields table (Part 1)
-- update: vme/wt 20190912 - updated partmaterialtype to accommodate blanks in data
-- Update: tt20190925 - Changed AP1_BUYER_Michele aggregate for buyer AP1_BUYER_Danielle 
-- Update: tt20191120 - added ShopResource User fields
-- Update: vme 20200122 - updated linked server SQL-BI-1 to SQL-LAB-2 for resourceID_reportsettings
-- Update: wnt 20200424	- updated customer id logic for unlinked (make-to-stock) cust id
-- Update: wnt 20200427 - added temp table in order to explicitly type user def fields. (bug @ time limit field)
-- Update: wnt 20200615 - left joined a second work_order set pointed at end item (sub id 0)
			Customer ID derived from _all_ or _any_ buyer id for unlinked records. 
			Drop down for cust updated.
-- Update: wnt 20200626 - Null Handling for Wait Days (was causing filter problems)
-- UpDate: wnt 20200716 - alloy now appended to material type 
-- Update: wnt 20200817 - updated code defect 8/17/2020 wt cte_laborTickets was one-to-many causing dups
-- Update: wnt Code Base 2.1.0.2 - Work Order Less Tempdb
-- update: wnt 20201007 service ops
-- Update: tt20201203 - removed facility from Danielle's salesrepid aggregate
-- Update: tt20210305 - update for BUI-derived CustomerIDs
-- Update: tt20210427 - created new version; ADD OPERATION.USER_10 AS SETUP_INFO (NEW FIELD) (Ticket #522)
-- Update: tt20210430 - updated User_8 for Skyflex
-- Update: tt20210707 - New version for IQM NCM Tag information
*/

ALTER PROCEDURE [dbo].[usp_WODS_ETL02] AS

IF OBJECT_ID('tempdb..#WODS_Output')IS NOT NULL DROP TABLE #WODS_Output

SET NOCOUNT OFF;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DEADLOCK_PRIORITY LOW

CREATE TABLE #WODS_Output(
	[BASE_ID] NVARCHAR(30) NOT NULL,
	[LOT_ID] NVARCHAR(3) NOT NULL,
	[SPLIT_ID] NVARCHAR(3) NOT NULL,
	[SUB_ID] NVARCHAR(3) NOT NULL,
	[TYPE] NCHAR(1) NOT NULL,
	[PART_ID] NVARCHAR(30) NULL,
	[WONUM] NVARCHAR(42) NULL,
	[DESIRED_QTY] DECIMAL(14,4) NULL,
	[STATUS] NCHAR(1) NOT NULL,
	[CUSTOMER_ORDER] NVARCHAR(15) NULL,
	[LINE_NO] SMALLINT NULL,
	[CUSTOMER_ID] NVARCHAR(15) NULL,
	[allocation_type] VARCHAR(8) NULL,
	[CurrentOperation] INT NULL,
	[StatusCurrOp] SMALLINT NULL,
	[PRINTED_DATE] DATETIME NULL,
	[DESIRED_RLS_DATE] DATETIME NULL,
	[CREATE_DATE] DATETIME NOT NULL,
	[remaining_operations] NVARCHAR(MAX) NOT NULL,
	[QTY_ON_HAND] DECIMAL(14,4) NOT NULL,
	[QTY_IN_DEMAND] DECIMAL(14,4) NOT NULL,
	[BUYER_USER_ID] NVARCHAR(20) NULL,
	[PLANNER_USER_ID] NVARCHAR(20) NULL,
	[COMMODITY_CODE] NVARCHAR(15) NULL,
	[DESCRIPTION] NVARCHAR(120) NULL,
	[DESIRED_WANT_DATE] DATETIME NULL,
	[EXP/FLT] NVARCHAR(254) NULL,
	[user_10] NVARCHAR(80) NULL,
	[col_user_1] NVARCHAR(80) NULL,
	[RWPart] NVARCHAR(30) NULL,
	[CUSTOMER_PO_REF] NVARCHAR(40) NULL,
	[WORK_ORDER_NOTES] NVARCHAR(MAX) NULL,
	[CUST_ORDER_NOTATION] NVARCHAR(MAX) NULL,
	[CUST_ORD_CREATEDATE] DATETIME NULL,
	[PartMaterialType] NVARCHAR(254) NOT NULL,
	[MaterialType] NVARCHAR(509) NOT NULL,
	[Alloy] NVARCHAR(254) NOT NULL,
	[CO_AMOUNT] DECIMAL(15,2) NULL,
	[UNIT_PRICE] DECIMAL(15,6) NULL,
	[TOTAL_AMT_SHIPPED] DECIMAL(15,2) NULL,
	[COL_AMOUNT] DECIMAL(15,2) NULL,
	[RESOURCE_ID_Raw] NVARCHAR(15) NULL,
	[OPERATION_TYPE] NVARCHAR(15) NULL,
	[StatusCurrOpType] NVARCHAR(15) NULL,
	[CURROPCHK] INT NULL,
	[RESOURCE_ID] NVARCHAR(15) NULL,
	[AubPriText] NVARCHAR(MAX) NULL,
	[AubTcText] NVARCHAR(MAX) NULL,
	[HasAubPri] INT NOT NULL,
	[HasAubTc] INT NOT NULL,
	[TimeLimit] INT NULL,
	[LAST_CLOCK_OUT] DATETIME NULL,
	[last_worked_seq] SMALLINT NULL,
	[last_clocked] NVARCHAR(81) NULL,
	[LATE] INT NOT NULL,
	[LATEP2] INT NOT NULL,
	[LATEP1] INT NOT NULL,
	[LATEP3] INT NOT NULL,
	[LATEBP1] INT NOT NULL,
	[WAIT_DAYS] INT NOT NULL,
	[EMPLOYEE_ID] NVARCHAR(15) NULL,
	[OPERATOR] NVARCHAR(61) NOT NULL,
	[USER_1] NVARCHAR(80) NULL,
	[LEAD_SUPERVISOR] NVARCHAR(111) NULL,
	[SupervisorName] NVARCHAR(80) NULL,
	[StatusCurrOpMsg] NVARCHAR(128) NULL,
	[tdesc] NVARCHAR(198) NOT NULL,
	[LABOR_TICKET_DESC] NVARCHAR(80) NULL,
	[BUYER] NVARCHAR(257) NOT NULL,
	[BUYERFILTER] NVARCHAR(255) NULL,
	[SALESREP_ID] NVARCHAR(255) NULL,
	[Account] NVARCHAR(5) NOT NULL,
	[Plant_ID] NVARCHAR(30) NOT NULL,
	[Tooling] INT NOT NULL,
	[IsAP1] INT NOT NULL,
	[IsAP2] INT NOT NULL,
	[IsAP3] INT NOT NULL,
	[IsBP1] INT NOT NULL,
	[IsUndetermined] INT NOT NULL,
	[IsNORGRU] INT NOT NULL,
	[IsTWMETA] INT NOT NULL,
	[IsAMTRIB] INT NOT NULL,
	[IsAUBMASK] INT NOT NULL,
	[IsAUBPrime] INT NOT NULL,
	[IsAUBSand] INT NOT NULL,
	[IsAUBsetup] INT NOT NULL,
	[IsAUBTC] INT NOT NULL,
	[IsAUBtakedown] INT NOT NULL,
	[IsAUBPartMark] INT NOT NULL,
	[IsAUBFinalInspection] INT NOT NULL,
	[IsAUBInspection] INT NOT NULL,
	[IsAUBPenetrant] INT NOT NULL,
	[IsAUBChemline] INT NOT NULL,
	[AP1_ETRAC] INT NOT NULL,
	[AP2_ETRAC] INT NOT NULL,
	[AP3_ETRAC] INT NOT NULL,
	[BP1_ETRAC] INT NOT NULL,
	[AP1_PDEXP] INT NOT NULL,
	[AP2_PDEXP] INT NOT NULL,
	[AP3_PDEXP] INT NOT NULL,
	[BP1_PDEXP] INT NOT NULL,
	[AP1_FLT] INT NOT NULL,
	[AP2_FLT] INT NOT NULL,
	[AP3_FLT] INT NOT NULL,
	[BP1_FLT] INT NOT NULL,
	[AP1_Buyer_Joe] INT NOT NULL,
	[AP1_Buyer_Rena] INT NOT NULL,
	[AP1_Buyer_Tiffany] INT NOT NULL,
	[AP1_Buyer_Sunni] INT NOT NULL,
	[AP1_Buyer_Danielle] INT NOT NULL,
	[AP1_Review] INT NOT NULL,
	[AP1_PlanningQueue] INT NOT NULL,
	[AP1_SkyFlex] INT NOT NULL,
	[ID] NVARCHAR(15) NULL,
	[DESIRED_RECV_DATE] DATETIME NULL,
	[SnapshotDate] DATETIME NOT NULL,
	[DEPARTMENT] NVARCHAR(80) NULL,
	[SUB_DEPARTMENT] NVARCHAR(80) NULL,
	[FACILITY] NVARCHAR(80) NULL,
	[REPT_DEPT] NVARCHAR(80) NULL,
	[PROCESS] NVARCHAR(80) NULL,
	[REPORT_GROUPING] NVARCHAR(80) NULL,
	[EMAIL_ADDR] NVARCHAR(80) NULL,
	[SETUP_INFO] NVARCHAR(80) NULL,
-- tt20210707: IQM NCM Tag Info
	[NCM_ID] NVARCHAR(20) NULL,
	[NCM_DATE] DATE NULL,
	[IQM_PROCESS] NVARCHAR(50) NULL,
	[IQM_SUBPROCESS] NVARCHAR(50) NULL,
	[IQM_DEFECT] NVARCHAR(50) NULL,
	[DISPOSITION_TYPE] NVARCHAR(50) NULL,
	[NCM_TYPE] NVARCHAR(50) NULL
) 

wods_query_begins:

DECLARE @ReportName NVARCHAR(255) = 'WODS'
	, @cols AS NVARCHAR(MAX)
	, @query AS NVARCHAR(MAX);

SET @cols = STUFF((SELECT DISTINCT ',' + QUOTENAME(S.Report_Section) 
	FROM [SQL-LAB-2].LIVESupplemental.dbo.ReportSettings_ResourceID S
	WHERE S.Report_Name = @ReportName
	FOR XML PATH(''), TYPE
	).value('.', 'NVARCHAR(MAX)'), 1, 1, '')
	
SET @query = 'SELECT Resource, ' + @cols + ' FROM
	(SELECT Resource
		, CAST(Include AS INT) Include
		, Report_Section
	FROM (SELECT [Resource_ID] AS Resource, [Report_Name], [Report_Section], [Reasoning], [Notes], [Include]
		FROM [SQL-LAB-2].LIVESupplemental.dbo.[ReportSettings_ResourceID] 
		) A
	WHERE A.Report_Name = ''' + @ReportName + '''
	) X
	PIVOT (MAX(Include)
	FOR Report_Section IN (' + @Cols + ')
	)P '
--PRINT @query

DECLARE @ReportSettings AS TABLE 
	(Resource NVARCHAR(30)
	, AP1_Review INT
	, HasAubPri INT
	, HasAubTc INT
	, IsAUBChemline INT
	, IsAUBFinalInspection INT
	, IsAUBInspection INT
	, IsAUBMASK INT
	, IsAUBPartMark INT
	, IsAUBPenetrant INT
	, IsAubPrime INT
	, IsAUBSand INT
	, IsAUBsetup INT
	, IsAUBtakedown INT
	, IsAUBTC INT
	, RESOURCE_ID_OpType INT
	, RESOURCE_ID_SERVICE INT
	)

INSERT INTO @ReportSettings EXECUTE(@query)

IF OBJECT_ID('tempdb..#NOTATIONBYOWNER') IS NOT NULL DROP TABLE #NOTATIONBYOWNER
--IF OBJECT_ID('tempdb..#WORK_ORDER') IS NOT NULL DROP TABLE #WORK_ORDER
--IF OBJECT_ID('tempdb..#USER_DEF_FIELDS') IS NOT NULL DROP TABLE #USER_DEF_FIELDS
IF OBJECT_ID('tempdb..#USER_DEF_FIELDS_W_48') IS NOT NULL DROP TABLE #USER_DEF_FIELDS_W_48
IF OBJECT_ID('tempdb..#CTE_WO') IS NOT NULL DROP TABLE #CTE_WO
IF OBJECT_ID('tempdb..#TEMP1') IS NOT NULL DROP TABLE #TEMP1

SELECT N.OWNER_ID
	, (SELECT CAST(CREATE_DATE AS NVARCHAR(12)) + N' - ' + CAST(CAST(NOTE AS VARBINARY(MAX)) AS NVARCHAR(MAX)) + N', ' + CHAR(10) + CHAR(13)
		FROM NOTATION N1
		WHERE N1.OWNER_ID = N.OWNER_ID
			AND N1.[TYPE] = N'CO'
		ORDER BY CREATE_DATE
		FOR XML PATH('')
	) AS NOTE
INTO #NOTATIONBYOWNER
FROM NOTATION N
WHERE N.[TYPE] = N'CO'
--AND OWNER_ID = '417967'
GROUP BY OWNER_ID

CREATE CLUSTERED INDEX CINOTATE ON #NOTATIONBYOWNER (OWNER_ID)

-- records from udf must be explicitly typed
CREATE TABLE #USER_DEF_FIELDS_W_48
	([TYPE] NCHAR(1) NOT NULL
		, [BASE_ID] NVARCHAR(30) NOT NULL
		, [LOT_ID] NVARCHAR(3) NOT NULL
		, [SPLIT_ID] NVARCHAR(3) NOT NULL
		, [SUB_ID] NVARCHAR(3) NOT NULL
		, [PROGRAM_ID] NVARCHAR(30) NOT NULL
		, [ID] NVARCHAR(30) NOT NULL
		, [LABEL] NVARCHAR(254)
		, [BOOL_VAL] INT
	)

INSERT INTO #USER_DEF_FIELDS_W_48
	([TYPE] 		
		, BASE_ID 	
		, LOT_ID 	
		, SUB_ID 	
		, SPLIT_ID 	
		, [PROGRAM_ID]  
		, [ID]  
		, [LABEL]  
		, [BOOL_VAL]  
	)
	SELECT [TYPE] = SUBSTRING(UD.DOCUMENT_ID, 0, CHARINDEX(N'~', UD.DOCUMENT_ID))
		, BASE_ID = SUBSTRING(UD.DOCUMENT_ID, CHARINDEX(N'~', UD.DOCUMENT_ID) + 1, CHARINDEX(N'~', UD.DOCUMENT_ID, CHARINDEX(N'~', UD.DOCUMENT_ID) + 1) - CHARINDEX(N'~', UD.DOCUMENT_ID) - 1) 
		, LOT_ID = SUBSTRING(UD.DOCUMENT_ID, CHARINDEX(N'~', UD.DOCUMENT_ID, CHARINDEX(N'~', UD.DOCUMENT_ID, CHARINDEX(N'~', UD.DOCUMENT_ID) + 1) + 1) + 1, 1)
		, SUB_ID = SUBSTRING(UD.DOCUMENT_ID, CHARINDEX(N'~', UD.DOCUMENT_ID, CHARINDEX(N'~', UD.DOCUMENT_ID) + 1) + 1, 1) 
		, SPLIT_ID = SUBSTRING(UD.DOCUMENT_ID, CHARINDEX(N'~', UD.DOCUMENT_ID, CHARINDEX(N'~', UD.DOCUMENT_ID, CHARINDEX(N'~', UD.DOCUMENT_ID, CHARINDEX(N'~', UD.DOCUMENT_ID) + 1) + 1) + 1) + 1, 1) 
		, UD.PROGRAM_ID
		, UD.ID
		, UD.[LABEL]
		, UD.BOOL_VAL
	FROM USER_DEF_FIELDS UD
	WHERE UD.PROGRAM_ID = N'VMMFGWIN_OP'
		AND UD.ID = N'UDF-0000048' 
		AND UD.[LABEL] IS NULL 
		AND UD.BOOL_VAL = 1

CREATE NONCLUSTERED INDEX N2CIDX_UDF_w_48 ON #USER_DEF_FIELDS_W_48 	
	(BASE_ID, LOT_ID, SUB_ID, SPLIT_ID, [TYPE])

CREATE NONCLUSTERED INDEX NCIDX_UDF_w_48 ON #USER_DEF_FIELDS_W_48 (PROGRAM_ID) 
	INCLUDE (ID, [LABEL], BOOL_VAL)

SELECT WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.[TYPE]
	, CASE 
		WHEN WO.PART_ID = N'REWORK MFG' THEN 
			(SELECT PART_ID FROM WORK_ORDER W 
			WHERE W.[TYPE] = WO.[TYPE] 
				AND W.BASE_ID = WO.BASE_ID 
				AND W.LOT_ID = WO.LOT_ID 
				AND W.SPLIT_ID = WO.SPLIT_ID 
				AND W.SUB_ID = N'0'  
				AND W.PART_ID != N'REWORK MFG'
			)
		ELSE WO.PART_ID 
	END PART_ID
	, dbo.sfnWONUMFormat(WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID) AS WONUM
	, WO.DESIRED_QTY
	, WO.[STATUS]
	, COL.CUST_ORDER_ID AS CUSTOMER_ORDER
	, COL.LINE_NO

--Customer ID calc;
--1st Customer ID for linked
--2nd Parse the Buyer ID – unlinked  **
--3rd Rework (FIN) will use the end item record (sub id 0) to cross reference and resolve.
--> tt20210305: update BUI-derived CustomerIDs for specific values
--> original code:
--	, CUSTOMER_ID2 = IIF(
--	(CASE WHEN (DSL.DEMAND_BASE_ID IS NULL AND DSL.DEMAND_SEQ_NO IS NULL AND DSL.DEMAND_TYPE IS NULL) THEN 'Unlinked' END) = 'unlinked' AND NULLIF(LTRIM(RTRIM(CO.CUSTOMER_ID)),'') IS NULL 
--		, IIF(ISNUMERIC(SUBSTRING(P.BUYER_USER_ID, 4, 1) ) = 1
--		, 'BOEPOP'
--		, SUBSTRING(P.BUYER_USER_ID, 4, 6)
--	), CO.customer_ID
--	)
	, CUSTOMER_ID2 = IIF(
		DSL.DEMAND_BASE_ID IS NULL AND DSL.DEMAND_SEQ_NO IS NULL AND DSL.DEMAND_TYPE IS NULL    --> UNLINKED
			AND NULLIF(LTRIM(RTRIM(CO.CUSTOMER_ID)), '') IS NULL  --> NO CUSTOMERID
			, CASE
				WHEN ISNUMERIC(SUBSTRING(P.BUYER_USER_ID, 4, 1)) = 1 THEN 'BOEPOP'
				WHEN SUBSTRING(P.BUYER_USER_ID, 4, 3) = 'DEF' THEN 'BOEDEF'
				WHEN SUBSTRING(P.BUYER_USER_ID, 4, 3) = 'SPI' THEN 'SPIAER'
				WHEN SUBSTRING(P.BUYER_USER_ID, 4, 4) = 'CMPF' THEN P.PLANNER_USER_ID
				ELSE SUBSTRING(P.BUYER_USER_ID, 4, 6)
			END
			, CO.CUSTOMER_ID
	)

--> ORIGINAL CODE:
--, CUSTOMER_ID = IIF(
--	(CASE WHEN (DSL.DEMAND_BASE_ID IS NULL AND DSL.DEMAND_SEQ_NO IS NULL AND DSL.DEMAND_TYPE IS NULL ) THEN 'UNLINKED' END) = 'UNLINKED' AND NULLIF(LTRIM(RTRIM(CO.CUSTOMER_ID)),'') IS NULL
--		, IIF(ISNUMERIC(SUBSTRING(EndItemPart.BUYER_USER_ID,4,1) ) = 1
--		,'BOEPOP'
--	, SUBSTRING(EndItemPart.BUYER_USER_ID, 4, 6)
--		), CO.customer_ID
--	)
	, CUSTOMER_ID = IIF(
		DSL.DEMAND_BASE_ID IS NULL AND DSL.DEMAND_SEQ_NO IS NULL AND DSL.DEMAND_TYPE IS NULL    --> UNLINKED
			AND NULLIF(LTRIM(RTRIM(CO.CUSTOMER_ID)), '') IS NULL  --> NO CUSTOMERID
			, CASE
				WHEN ISNUMERIC(SUBSTRING(EndItemPart.BUYER_USER_ID, 4, 1)) = 1 THEN 'BOEPOP'
				WHEN SUBSTRING(EndItemPart.BUYER_USER_ID, 4, 3) = 'DEF' THEN 'BOEDEF'
				WHEN SUBSTRING(EndItemPart.BUYER_USER_ID, 4, 3) = 'SPI' THEN 'SPIAER'
				WHEN SUBSTRING(EndItemPart.BUYER_USER_ID, 4, 4) = 'CMPF' THEN EndItemPart.PLANNER_USER_ID
				ELSE SUBSTRING(EndItemPart.BUYER_USER_ID, 4, 6)
			END
			, CO.CUSTOMER_ID
	)
	, EndItemPart.part_id EndItem_Part_id
	, EndItemPart.BUYER_USER_ID EndItem_BUYER_USER_ID
	, Allocation_Type = CASE WHEN (DSL.DEMAND_BASE_ID IS NULL AND DSL.DEMAND_SEQ_NO IS NULL AND DSL.DEMAND_TYPE IS NULL) THEN 'Unlinked' END
--	, SUBSTRING(P.BUYER_USER_ID, 4, 1) buyer_ptr
	, dbo.sfn_current_operation(WO.[TYPE], WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID) AS CurrentOperation
	, ISNULL(dbo.sfn_getlastopcompleted(WO.[TYPE], WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID), dbo.ufn_GetFirstOperation(WO.BASE_ID, WO.LOT_ID, WO.SUB_ID, WO.SPLIT_ID, WO.[TYPE])) AS StatusCurrOp
	, WO.PRINTED_DATE
	, CASE   
		WHEN WO.DESIRED_RLS_DATE IS NULL THEN (SELECT W.DESIRED_RLS_DATE FROM WORK_ORDER W
			WHERE W.[TYPE] = WO.[TYPE]
				AND W.BASE_ID = WO.BASE_ID
				AND W.LOT_ID = WO.LOT_ID
				AND W.SPLIT_ID = WO.SPLIT_ID
				AND W.SUB_ID = N'0'
			)
		ELSE WO.DESIRED_RLS_DATE
	END DESIRED_RLS_DATE
	, ISNULL(co.CREATE_DATE, WO.CREATE_DATE) AS CREATE_DATE
	, ISNULL(dbo.sfn_remaining_operations(WO.[TYPE], WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID), N'No Remaining Operations') remaining_operations
	, P.QTY_ON_HAND 
	, P.QTY_IN_DEMAND 
	, P.BUYER_USER_ID 
	, RTRIM(P.PLANNER_USER_ID) AS PLANNER_USER_ID
	, P.COMMODITY_CODE
	, P.[DESCRIPTION]
	, ISNULL(WO.DESIRED_WANT_DATE, (SELECT MIN(DESIRED_WANT_DATE) FROM WORK_ORDER W WHERE WO.[TYPE] = W.[TYPE] AND WO.BASE_ID = W.BASE_ID AND WO.LOT_ID = W.LOT_ID AND WO.SPLIT_ID = W.SPLIT_ID AND WO.SUB_ID != W.SUB_ID)) AS DESIRED_WANT_DATE
	, (SELECT TOP 1 STRING_VAL FROM USER_DEF_FIELDS UD
		WHERE UD.PROGRAM_ID = N'VMMFGWIN_WO'
			AND UD.ID = N'UDF-0000070' 
			AND ISNULL(UD.[LABEL], '') = ''
			AND WO.[TYPE] + N'~' + WO.BASE_ID + N'~' + N'0' + N'~' + WO.LOT_ID + N'~' + WO.SPLIT_ID = UD.DOCUMENT_ID
		) AS [EXP/FLT]
	, COL.USER_10 
	, COL.USER_1 AS COL_USER_1
	, CASE 
		WHEN WO.PART_ID = N'REWORK MFG' THEN (SELECT PART_ID FROM WORK_ORDER W
			WHERE W.[TYPE] = WO.[TYPE] 
				AND W.BASE_ID = WO.BASE_ID 
				AND W.LOT_ID = WO.LOT_ID 
				AND W.SPLIT_ID = WO.SPLIT_ID 
				AND W.SUB_ID = '0'
				AND W.PART_ID <> N'REWORK MFG'
			)
		ELSE WO.PART_ID 
	END AS RWPart
	, CO.CUSTOMER_PO_REF
	, CONVERT(NVARCHAR(MAX), CONVERT(VARBINARY(MAX), WB.BITS)) AS WORK_ORDER_NOTES
	, N.NOTE AS CUST_ORDER_NOTATION
	, CO.CREATE_DATE AS CUST_ORD_CREATEDATE
	, ISNULL(nullif(material.material, ''), '_blank') AS PartMaterialType
	, ISNULL(NULLIF(alloy.alloy, ''), '_blank') AS Alloy
	, CASE 
		WHEN Material.Material IS NULL and alloy.alloy IS NULL then'_blank'
		ELSE ISNULL(Material.Material, '') + IIF(Material.Material IS NOT NULL, IIF(alloy.alloy IS NOT NULL, ' ', ''), '') + ISNULL(alloy.Alloy, '') 
	END AS MaterialType
	, CO.TOTAL_AMT_ORDERED AS CO_AMOUNT
	, COL.UNIT_PRICE
	, COL.TOTAL_AMT_SHIPPED
	, COL.TOTAL_AMT_ORDERED AS COL_AMOUNT
INTO #CTE_WO
FROM WORK_ORDER WO2
JOIN WORK_ORDER WO
	ON WO2.[TYPE] = WO.[TYPE]
	AND WO2.[BASE_ID] = WO.[BASE_ID]
	AND WO2.[LOT_ID] = WO.[LOT_ID]
	AND WO2.[SPLIT_ID] = WO.[SPLIT_ID]
	AND WO2.[SUB_ID] = WO.[SUB_ID]
LEFT JOIN WORK_ORDER EndItem
	ON EndItem.[TYPE] = WO.[TYPE]
	AND EndItem.[BASE_ID] = WO.[BASE_ID]
	AND EndItem.[LOT_ID] = WO.[LOT_ID]
	AND EndItem.[SPLIT_ID] = WO.[SPLIT_ID]
	AND EndItem.[SUB_ID] = '0'
LEFT JOIN WORKORDER_BINARY WB
	ON WB.WORKORDER_BASE_ID = WO.BASE_ID
	AND WB.WORKORDER_LOT_ID = WO.LOT_ID
	AND WB.WORKORDER_SPLIT_ID = WO.SPLIT_ID
	AND WB.WORKORDER_SUB_ID = WO.SUB_ID
	AND WB.WORKORDER_TYPE = WO.[TYPE] 
LEFT JOIN DEMAND_SUPPLY_LINK DSL
	ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
	AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
	AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
--AND DSL.SUPPLY_SUB_ID = WO.SUB_ID  --MUST OMIT FOR LEGS AND REWORKS
LEFT JOIN CUST_ORDER_LINE COL
	ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
	AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
	AND DSL.DEMAND_TYPE = N'CO'
LEFT JOIN CUSTOMER_ORDER CO
	ON CO.ID = COL.CUST_ORDER_ID
LEFT JOIN #NOTATIONBYOWNER N
	ON N.OWNER_ID = CO.ID
JOIN PART_SITE_VIEW P
	ON P.PART_ID = WO.PART_ID
	AND P.SITE_ID = N'SK01'
LEFT JOIN PART_SITE_VIEW EndItemPart
	ON EndItemPart.PART_ID = EndItem.PART_ID
	AND EndItemPart.SITE_ID = N'SK01'
	AND EndItemPart.PART_ID != 'REWORK MFG'
			outer APPLY (SELECT top 1 pud2.DOCUMENT_ID
				, pud2.id
				, pud2.LABEL
				, NULLIF(pud2.STRING_VAL,'') AS Material
				, pud2.PROGRAM_ID
				, p.id part_id
			from USER_DEF_FIELDS pUD2
			join part p 
			on pud2.DOCUMENT_ID = p.id
			where pUD2.ID in ('UDF-0000035') -- material
			AND pUD2.PROGRAM_ID = 'VMPRTMNT'
			and pUD2.DOCUMENT_ID IS NOT NULL
			AND WO.PART_ID = pUD2.DOCUMENT_ID
			) Material

		outer APPLY (SELECT top 1 pud3.document_id
			, pud3.id
			, pud3.label
			, nullif(pud3.string_val,'') AS alloy
			, pud3.program_id
			, p3.id part_id
		from user_def_fields pud3
		join part p3 
		on pud3.document_id = p3.id
		where pUD3.ID in ('UDF-0000036')  -- prtMnt Alloy
		AND pUD3.PROGRAM_ID = 'VMPRTMNT'
		and pUD3.DOCUMENT_ID IS NOT NULL
		AND WO.PART_ID = pUD3.DOCUMENT_ID
		) alloy
LEFT JOIN LIVESupplemental.dbo.SK_CUST_SPECIFIC_PARTS CP
	ON CP.PART_ID = P.PART_ID
WHERE WO.[STATUS] IN (N'R', N'F', N'U')
	AND WO.[TYPE] = N'W'

CREATE CLUSTERED INDEX ix_tempctewo ON #CTE_WO([TYPE] ASC, BASE_ID ASC, LOT_ID ASC, SPLIT_ID ASC, SUB_ID ASC);
CREATE NONCLUSTERED INDEX ixtempctewo_CurOp ON #CTE_WO(CurrentOperation ASC);
CREATE NONCLUSTERED INDEX ixtempctewo_StatusCurOp ON #CTE_WO(StatusCurrOp ASC);

; WITH CTE_LASTCLOCKOUT AS
(SELECT A.WORKORDER_BASE_ID
	, A.WORKORDER_LOT_ID
	, A.WORKORDER_SPLIT_ID
	, A.WORKORDER_SUB_ID
	, A.WORKORDER_TYPE
	, A.LAST_CLOCK_OUT
	, MAX(OPERATION_SEQ_NO) AS LAST_OPERATION
FROM (SELECT LT.WORKORDER_BASE_ID
		, LT.WORKORDER_LOT_ID
		, LT.WORKORDER_SPLIT_ID
		, LT.WORKORDER_SUB_ID
		, LT.WORKORDER_TYPE
		, MAX(LT.CLOCK_OUT) AS LAST_CLOCK_OUT
	FROM LABOR_TICKET LT
	WHERE EXISTS (SELECT 1 FROM #CTE_WO WO
		WHERE LT.WORKORDER_BASE_ID = WO.BASE_ID
		AND LT.WORKORDER_LOT_ID = WO.LOT_ID
		AND LT.WORKORDER_SPLIT_ID = WO.SPLIT_ID
		AND LT.WORKORDER_SUB_ID = WO.SUB_ID
		AND LT.WORKORDER_TYPE = WO.[TYPE]
		)
	GROUP BY LT.WORKORDER_BASE_ID
		, LT.WORKORDER_LOT_ID
		, LT.WORKORDER_SPLIT_ID
		, LT.WORKORDER_SUB_ID
		, LT.WORKORDER_TYPE
	) A
JOIN LABOR_TICKET LT
	ON A.WORKORDER_BASE_ID = LT.WORKORDER_BASE_ID
	AND A.WORKORDER_LOT_ID = LT.WORKORDER_LOT_ID
	AND A.WORKORDER_SPLIT_ID = LT.WORKORDER_SPLIT_ID
	AND A.WORKORDER_SUB_ID = LT.WORKORDER_SUB_ID
	AND A.WORKORDER_TYPE = LT.WORKORDER_TYPE
	AND A.LAST_CLOCK_OUT = LT.CLOCK_OUT
GROUP BY A.WORKORDER_BASE_ID
	, A.WORKORDER_LOT_ID
	, A.WORKORDER_SPLIT_ID
	, A.WORKORDER_SUB_ID
	, A.WORKORDER_TYPE
	, A.LAST_CLOCK_OUT
)

, CTE_LABORTICKETS AS
(SELECT X.*
FROM (SELECT LT.* 
	, A.LAST_CLOCK_OUT
	, A.LAST_OPERATION
	, RN = ROW_NUMBER() OVER (PARTITION BY LT.WORKORDER_TYPE
		, LT.WORKORDER_BASE_ID
		, LT.WORKORDER_LOT_ID
		, LT.WORKORDER_SPLIT_ID
		, LT.WORKORDER_SUB_ID
		, LT.OPERATION_SEQ_NO
		, LT.CLOCK_OUT
		ORDER BY LT.TRANSACTION_ID DESC
		)
	FROM LABOR_TICKET LT (NOLOCK)
	JOIN CTE_LASTCLOCKOUT A 
		ON A.WORKORDER_BASE_ID = LT.WORKORDER_BASE_ID
		AND A.WORKORDER_LOT_ID = LT.WORKORDER_LOT_ID
		AND A.WORKORDER_SPLIT_ID = LT.WORKORDER_SPLIT_ID
		AND A.WORKORDER_SUB_ID = LT.WORKORDER_SUB_ID
		AND A.WORKORDER_TYPE = LT.WORKORDER_TYPE
		AND A.LAST_OPERATION = LT.OPERATION_SEQ_NO
		AND A.LAST_CLOCK_OUT = LT.CLOCK_OUT
	) X
WHERE X.RN = 1
)

, CTE_CURRENTOPERATION AS 
(SELECT W.*
	, ISNULL(O.RESOURCE_ID, O2.RESOURCE_ID) AS RESOURCE_ID_Raw
	, O.OPERATION_TYPE
	, O2.OPERATION_TYPE AS StatusCurrOpType
	, W.CurrentOperation AS CURROPCHK
	, CASE 
		WHEN EXISTS(SELECT 1 FROM @ReportSettings S
			WHERE S.[Resource] = ISNULL(O.RESOURCE_ID, O2.RESOURCE_ID)
				AND ISNULL(S.RESOURCE_ID_OpType, -1) != - 1
			) THEN ISNULL(O.OPERATION_TYPE, O2.OPERATION_TYPE) 
		WHEN EXISTS(SELECT 1 FROM @ReportSettings S
			WHERE S.[Resource] = ISNULL(O.RESOURCE_ID, O2.RESOURCE_ID)
				AND ISNULL(S.RESOURCE_ID_SERVICE, -1) != -1
			) THEN O.VENDOR_ID
		ELSE ISNULL(O.RESOURCE_ID, O2.RESOURCE_ID) 
	END AS RESOURCE_ID
	, CONVERT(NVARCHAR(MAX), CONVERT(VARBINARY(MAX), OB.BITS)) AS AubPriText
	, CONVERT(NVARCHAR(MAX), CONVERT(VARBINARY(MAX), OTB.BITS)) AS AubTcText
	, CASE 
		WHEN OB.BITS IS NOT NULL OR EXISTS(SELECT 1 FROM @ReportSettings S 
			WHERE ISNULL(O.RESOURCE_ID, O2.RESOURCE_ID) = S.[Resource] 
				AND ISNULL(S.HasAubPri, -1) != -1) THEN 1 
		ELSE 0 
	END AS HasAubPri
	, CASE 
		WHEN OTB.BITS IS NOT NULL OR EXISTS(SELECT 1 FROM @ReportSettings S 
			WHERE ISNULL(O.RESOURCE_ID, O2.RESOURCE_ID) = S.[Resource] 
				AND ISNULL(S.HasAubTc, -1) != -1) THEN 1 
		ELSE 0 
	END AS HasAubTc
-- update 4/27 for testing, udf fields must be explicitly typed
	, CASE
		WHEN EXISTS(SELECT 1 FROM #USER_DEF_FIELDS_W_48 UDF
			WHERE UDF.PROGRAM_ID = N'VMMFGWIN_OP'  
				AND UDF.ID = N'UDF-0000048' 
				AND UDF.[LABEL] IS NULL 
				AND UDF.BOOL_VAL = 1
				AND W.[TYPE] = UDF.[TYPE]  
				AND W.BASE_ID = UDF.base_id 
				AND W.LOT_ID = UDF.lot_ID 
				AND W.SUB_ID = UDF.sub_id
				AND W.SPLIT_ID = UDF.SPLIT_id
			) THEN CONVERT(INT, 1)
		ELSE CONVERT(INT, 0)
	END AS TimeLimit
--> tt20210427: new field request from Ann (Ticket #522)
	, O.USER_10 AS SETUP_INFO
FROM #CTE_WO W 
LEFT JOIN OPERATION O --LAST OP COMPLETE BASED ON STATUS C OR LTICKETS
	ON O.WORKORDER_BASE_ID = W.BASE_ID
	AND O.WORKORDER_LOT_ID = W.LOT_ID
	AND O.WORKORDER_SPLIT_ID = W.SPLIT_ID
	AND O.WORKORDER_SUB_ID = W.SUB_ID
	AND O.WORKORDER_TYPE = W.[TYPE] 
	AND O.SEQUENCE_NO = W.CurrentOperation
LEFT JOIN OPERATION O2 -- BASED ON LAST OP WITH STATUS C OR IF NONE, FIRST OP
	ON O2.WORKORDER_BASE_ID = W.BASE_ID
	AND O2.WORKORDER_LOT_ID = W.LOT_ID
	AND O2.WORKORDER_SPLIT_ID = W.SPLIT_ID
	AND O2.WORKORDER_SUB_ID = W.SUB_ID
	AND O2.WORKORDER_TYPE = W.[TYPE]
	AND O2.SEQUENCE_NO = W.StatusCurrOp
LEFT JOIN (SELECT O.WORKORDER_BASE_ID
		, O.WORKORDER_LOT_ID
		, O.WORKORDER_SPLIT_ID
		, O.WORKORDER_SUB_ID
		, O.WORKORDER_TYPE
		, O.SEQUENCE_NO
		, O.RESOURCE_ID
	FROM OPERATION O
	JOIN (SELECT O.WORKORDER_BASE_ID
			, O.WORKORDER_LOT_ID
			, O.WORKORDER_SPLIT_ID
			, O.WORKORDER_SUB_ID
			, O.WORKORDER_TYPE
			, MIN(SEQUENCE_NO) AS minAubPriSequence
		FROM OPERATION O
		WHERE EXISTS(SELECT 1 FROM #CTE_WO W
			WHERE W.BASE_ID = O.WORKORDER_BASE_ID
				AND W.LOT_ID = O.WORKORDER_LOT_ID
				AND W.SPLIT_ID = O.WORKORDER_SPLIT_ID
				AND W.SUB_ID = O.WORKORDER_SUB_ID
				AND W.[TYPE] = O.WORKORDER_TYPE
				AND O.SEQUENCE_NO >= W.CurrentOperation
				)
			AND EXISTS(SELECT 1 FROM @ReportSettings S
				WHERE O.RESOURCE_ID = S.[Resource]
					AND ISNULL(S.HasAubTc, S.HasAubPri) IS NOT NULL
					)
			GROUP BY O.WORKORDER_BASE_ID
				, O.WORKORDER_LOT_ID
				, O.WORKORDER_SPLIT_ID
				, O.WORKORDER_SUB_ID
				, O.WORKORDER_TYPE
		) A
		ON A.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
		AND A.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
		AND A.WORKORDER_SUB_ID = O.WORKORDER_SUB_ID
		AND A.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
		AND A.WORKORDER_TYPE = O.WORKORDER_TYPE
		AND A.minAubPriSequence = O.SEQUENCE_NO
	) OP
	ON OP.WORKORDER_BASE_ID = W.BASE_ID
	AND OP.WORKORDER_LOT_ID = W.LOT_ID
	AND OP.WORKORDER_SPLIT_ID = W.SPLIT_ID
	AND OP.WORKORDER_SUB_ID = W.SUB_ID
	AND OP.WORKORDER_TYPE = W.[TYPE]
LEFT JOIN OPERATION_BINARY OB
	ON OB.WORKORDER_BASE_ID = OP.WORKORDER_BASE_ID
	AND OB.WORKORDER_LOT_ID = OP.WORKORDER_LOT_ID
	AND OB.WORKORDER_SPLIT_ID = OP.WORKORDER_SPLIT_ID
	AND OB.WORKORDER_SUB_ID = OP.WORKORDER_SUB_ID
	AND OB.WORKORDER_TYPE = OP.WORKORDER_TYPE
	AND OB.SEQUENCE_NO = OP.SEQUENCE_NO
	AND EXISTS(SELECT 1 FROM @ReportSettings S
		WHERE S.[Resource] = OP.RESOURCE_ID
			AND ISNULL(S.HasAubPri, -1) != -1
		)
LEFT JOIN OPERATION_BINARY OTB
	ON OTB.WORKORDER_BASE_ID = OP.WORKORDER_BASE_ID
	AND OTB.WORKORDER_LOT_ID = OP.WORKORDER_LOT_ID
	AND OTB.WORKORDER_SPLIT_ID = OP.WORKORDER_SPLIT_ID
	AND OTB.WORKORDER_SUB_ID = OP.WORKORDER_SUB_ID
	AND OTB.WORKORDER_TYPE = OP.WORKORDER_TYPE
	AND OTB.SEQUENCE_NO = OP.SEQUENCE_NO
	AND EXISTS(SELECT 1 FROM @ReportSettings S
		WHERE OP.RESOURCE_ID = S.[Resource]
			AND ISNULL(S.HasAubTc, -1) != -1
		)
)
--SELECT * FROM cte_currentoperation

SELECT W.BASE_ID
	, W.LOT_ID
	, W.SPLIT_ID
	, W.SUB_ID
	, W.[TYPE]
	, W.PART_ID
	, W.WONUM
	, W.DESIRED_QTY
	, W.[STATUS]
	, W.CUSTOMER_ORDER
	, W.LINE_NO
	, CUSTOMER_ID = COALESCE(CUSTOMER_ID2, CUSTOMER_ID)
	, W.allocation_type
	, W.CurrentOperation
	, W.StatusCurrOp
	, W.PRINTED_DATE
	, W.DESIRED_RLS_DATE
	, W.CREATE_DATE
	, W.remaining_operations
	, W.QTY_ON_HAND
	, W.QTY_IN_DEMAND
	, W.BUYER_USER_ID
	, W.PLANNER_USER_ID
	, W.COMMODITY_CODE
	, W.[DESCRIPTION]
	, W.DESIRED_WANT_DATE
	, W.[EXP/FLT]
	, W.user_10
	, W.col_user_1
	, W.RWPart
	, W.CUSTOMER_PO_REF
	, W.WORK_ORDER_NOTES
	, W.CUST_ORDER_NOTATION
	, W.CUST_ORD_CREATEDATE
-- wt 20200716  -- the new field in rendering alloy concat material is MaterialType
	, W.PartMaterialType AS PartMaterialType  -- old used for filter by material type
-- wt 20200716  -- the old field is still used for filter by materialType
	, W.MaterialType AS MaterialType -- new 
	, W.Alloy
	, W.CO_AMOUNT
	, W.UNIT_PRICE
	, W.TOTAL_AMT_SHIPPED
	, W.COL_AMOUNT
	, W.RESOURCE_ID_Raw
	, W.OPERATION_TYPE
	, W.StatusCurrOpType
	, W.CURROPCHK
	, W.RESOURCE_ID
	, W.AubPriText
	, W.AubTcText
	, W.HasAubPri
	, W.HasAubTc
	, W.TimeLimit
	, L.LAST_CLOCK_OUT 
	, L.LAST_OPERATION AS last_worked_seq
	, CONVERT(NVARCHAR(50), COALESCE(L.LAST_CLOCK_OUT, W.PRINTED_DATE, W.DESIRED_RLS_DATE), 1) + ' ' 
		+ CONVERT(NVARCHAR,CONVERT(TIME, COALESCE(L.LAST_CLOCK_OUT, W.PRINTED_DATE, W.DESIRED_RLS_DATE)), 0) as last_clocked
	, CASE WHEN DATEDIFF(dd, W.DESIRED_WANT_DATE, GETDATE() ) > 2 THEN 1 ELSE 0 END AS LATE
	, CASE WHEN DATEDIFF(dd, W.DESIRED_WANT_DATE, GETDATE() ) > 4 AND ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP2' THEN 1 ELSE 0 END AS LATEP2
	, CASE WHEN DATEDIFF(dd, W.DESIRED_WANT_DATE, GETDATE() ) > 0 AND ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP1' THEN 1 ELSE 0 END AS LATEP1
	, CASE WHEN DATEDIFF(dd, W.DESIRED_WANT_DATE, GETDATE() ) > 2 AND ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP3' THEN 1 ELSE 0 END AS LATEP3
	, CASE WHEN DATEDIFF(dd, W.DESIRED_WANT_DATE, GETDATE() ) > 2 AND ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'BP1' THEN 1 ELSE 0 END AS LATEBP1
	, ISNULL(DATEDIFF(dd, COALESCE(L.LAST_CLOCK_OUT, W.PRINTED_DATE, W.DESIRED_RLS_DATE), GETDATE()), 0) WAIT_DAYS
	, L.EMPLOYEE_ID
	, ISNULL(E.FIRST_NAME, '') + ' ' + ISNULL(E.LAST_NAME, '') OPERATOR
	, SR.USER_1
	, ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), '') + '-' + LTRIM(RTRIM(SR.USER_4)) AS LEAD_SUPERVISOR
	, RTRIM(ISNULL(LTRIM(RTRIM(SR.USER_4)), '_blank')) AS SupervisorName
	, COALESCE(CAST(W.StatusCurrOp AS NVARCHAR(128)), CAST(W.CurrentOperation AS NVARCHAR(128)), N'NO OPERATIONS - SET TO UNRELEASED') StatusCurrOpMsg
	, ISNULL(W.col_USER_1 + ',  ','') + ISNULL(L.[DESCRIPTION] + CHAR(10) + CHAR(13), '') + ISNULL('PO '+ dslPO.ID + ' - ', '') 
		+ ISNULL(CONVERT(NVARCHAR(12), ISNULL(dslPO.PROMISE_SHIP_DATE,dslPO.DESIRED_RECV_DATE), 110), '') AS tdesc
	, L.[DESCRIPTION] AS LABOR_TICKET_DESC
	, ISNULL(CASE WHEN P.COMMODITY_CODE = 'Details' THEN COALESCE(leg.Salesperson_ID, B.Salesperson_ID, C.SALESREP_ID) + '-D' ELSE COALESCE(leg.Salesperson_ID, b.Salesperson_ID, c.SALESREP_ID) END,  '_blank')  BUYER
	, COALESCE(leg.Salesperson_ID, B.Salesperson_ID, C.SALESREP_ID, '_blank') AS BUYERFILTER
	, COALESCE(B.Salesperson_ID, C.SALESREP_ID, '_blank') AS SALESREP_ID  
	, ISNULL(B.Account_ID,'00') AS Account
	, ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') AS Plant_ID
	, CASE WHEN P.COMMODITY_CODE = 'Tools' THEN 1 ELSE 0 END AS Tooling
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP1' AND W.STATUS = 'R' THEN 1 ELSE 0 END AS IsAP1
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP2' AND W.STATUS = 'R' THEN 1 ELSE 0 END AS IsAP2
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP3' AND W.STATUS = 'R' THEN 1 ELSE 0 END AS IsAP3
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'BP1' AND W.STATUS = 'R' THEN 1 ELSE 0 END AS IsBP1
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'Undetermined' THEN 1 ELSE 0 END AS IsUndetermined
	, CASE WHEN W.CUSTOMER_ID = 'NORGRU' THEN 1 ELSE 0 END AS IsNORGRU
	, CASE WHEN W.CUSTOMER_ID = 'TWMETA' THEN 1 ELSE 0 END AS IsTWMETA
	, CASE WHEN W.CUSTOMER_ID = 'AMTRIB' THEN 1 ELSE 0 END AS IsAMTRIB
	, CASE WHEN ISNULL(RS.IsAUBMASK, -1) <> -1 THEN 1 ELSE 0 END AS IsAUBMASK
	, CASE WHEN ISNULL(RS.IsAubPrime, -1) <> -1 THEN 1 ELSE 0 END AS IsAUBPrime
	, CASE WHEN ISNULL(RS.IsAUBSand, -1) <> -1 THEN 1 ELSE 0 END AS IsAUBSand
	, CASE WHEN ISNULL(RS.IsAUBsetup, -1) <> -1 THEN 1 ELSE 0 END AS IsAUBsetup
	, CASE WHEN ISNULL(RS.IsAUBTC, -1) <> -1 THEN 1 ELSE 0 END AS IsAUBTC
	, CASE WHEN ISNULL(RS.IsAUBtakedown, -1) <> -1 THEN 1 ELSE 0 END AS IsAUBtakedown
	, CASE WHEN ISNULL(RS.IsAUBPartMark, -1) <> -1 THEN 1 ELSE 0 END AS IsAUBPartMark
	, CASE WHEN ISNULL(RS.IsAUBFinalInspection, -1) <> -1 THEN 1 ELSE 0 END AS IsAUBFinalInspection
	, CASE WHEN ISNULL(RS.IsAUBInspection, -1) <> -1 THEN 1 ELSE 0 END AS IsAUBInspection
	, CASE WHEN ISNULL(RS.IsAUBPenetrant, -1) <> -1 THEN 1 ELSE 0 END AS IsAUBPenetrant
	, CASE WHEN ISNULL(RS.IsAUBChemline, -1) <> -1 THEN 1 ELSE 0 END AS IsAUBChemline
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP1' AND W.[EXP/FLT] = '1_ETRAC' THEN 1 ELSE 0 END AS AP1_ETRAC
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP2' AND W.[EXP/FLT] = '1_ETRAC' THEN 1 ELSE 0 END AS AP2_ETRAC
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP3' AND W.[EXP/FLT] = '1_ETRAC' THEN 1 ELSE 0 END AS AP3_ETRAC
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'BP1' AND W.[EXP/FLT] = '1_ETRAC' THEN 1 ELSE 0 END AS BP1_ETRAC
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP1' AND W.[EXP/FLT] IN ('3_PD EXP', '4_PD EXP/FLT') THEN 1 ELSE 0 END AS AP1_PDEXP
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP2' AND W.[EXP/FLT] IN ('3_PD EXP', '4_PD EXP/FLT') THEN 1 ELSE 0 END AS AP2_PDEXP
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP3' AND W.[EXP/FLT] IN ('3_PD EXP', '4_PD EXP/FLT') THEN 1 ELSE 0 END AS AP3_PDEXP
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'BP1' AND W.[EXP/FLT] IN ('3_PD EXP', '4_PD EXP/FLT') THEN 1 ELSE 0 END AS BP1_PDEXP
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP1' AND W.[EXP/FLT] IN ('5_FLT', '4_PD EXP/FLT') THEN 1 ELSE 0 END AS AP1_FLT
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP2' AND W.[EXP/FLT] IN ('5_FLT', '4_PD EXP/FLT') THEN 1 ELSE 0 END AS AP2_FLT
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP3' AND W.[EXP/FLT] IN ('5_FLT', '4_PD EXP/FLT') THEN 1 ELSE 0 END AS AP3_FLT
	, CASE WHEN ISNULL(CAST(SR.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'BP1' AND W.[EXP/FLT] IN ('5_FLT', '4_PD EXP/FLT') THEN 1 ELSE 0 END AS BP1_FLT
--> tt20190816
 	, CASE WHEN COALESCE(B.Salesperson_ID, C.SALESREP_ID, '_blank') = 'Joe' AND ISNULL(CAST(sr.USER_5 AS NVARCHAR(30)), 'Undetermined') = 'AP1' THEN 1 ELSE 0 END AS AP1_Buyer_Joe
--> tt20181113
	, CASE WHEN COALESCE(B.Salesperson_ID, C.SALESREP_ID, '_blank') = 'Rena' THEN 1 ELSE 0 END AS AP1_Buyer_Rena
	, CASE WHEN COALESCE(B.Salesperson_ID, C.SALESREP_ID, '_blank') = 'Tiffany' THEN 1 ELSE 0 END AS AP1_Buyer_Tiffany
	, CASE WHEN COALESCE(B.Salesperson_ID, C.SALESREP_ID, '_blank') = 'Sunni' THEN 1 ELSE 0 END AS AP1_Buyer_Sunni
	, CASE WHEN COALESCE(B.Salesperson_ID, C.SALESREP_ID, '_blank') = 'Danielle' THEN 1 ELSE 0 END AS AP1_Buyer_Danielle
	, CASE WHEN W.[STATUS] = 'R' AND ISNULL(RS.AP1_Review, -1) <> -1 THEN 1 ELSE 0 END AS AP1_Review
	, CASE WHEN W.[STATUS] IN ('U','F') AND SR.USER_5 IN ('AP1', 'BP1') THEN 1 ELSE 0 END AS AP1_PlanningQueue
	, CASE WHEN ISNULL(SR.USER_8, '_blank') = 'CARGO' THEN 1 ELSE 0 END AS AP1_SkyFlex
	, dslPO.ID
	, ISNULL(dslPO.PROMISE_SHIP_DATE, dslPO.DESIRED_RECV_DATE) AS DESIRED_RECV_DATE
	, GETDATE() AS SnapshotDate
--> tt20190424 
	, SR.USER_2 AS DEPARTMENT
	, SR.USER_3 AS SUB_DEPARTMENT
--> tt20191120
	, SR.USER_5 AS FACILITY
	, SR.USER_6 AS REPT_DEPT
	, SR.USER_7 AS PROCESS
	, SR.USER_8 AS REPORT_GROUPING
	, CASE
		WHEN LTRIM(RTRIM(SR.USER_4)) = 'GREG HARTMAN' THEN 'GREGH@SKILLSINC.COM'
		ELSE EE.EMAIL_ADDR
	END AS EMAIL_ADDR
	, W.SETUP_INFO
	, [NCM_ID]
	, [NCM_DATE]
	, [IQM_PROCESS]
	, [IQM_SUBPROCESS]
	, [IQM_DEFECT]
	, [DISPOSITION_TYPE]
	, [NCM_TYPE]
INTO #TEMP1
FROM cte_currentoperation W
LEFT JOIN cte_labortickets L
	ON W.BASE_ID = L.WORKORDER_BASE_ID
	AND W.LOT_ID = L.WORKORDER_LOT_ID
	AND W.SPLIT_ID = L.WORKORDER_SPLIT_ID
	AND W.SUB_ID = L.WORKORDER_SUB_ID
	AND W.[TYPE] = L.WORKORDER_TYPE
LEFT JOIN EMPLOYEE E
	ON E.ID = L.EMPLOYEE_ID
LEFT JOIN SHOP_RESOURCE_SITE_VIEW SR
	ON SR.RESOURCE_ID = W.RESOURCE_ID_Raw
--> tt20190424
LEFT OUTER JOIN EMPLOYEE EE
	ON LTRIM(RTRIM(SR.USER_4)) = EE.[FIRST_NAME] + ' ' + EE.[LAST_NAME]
	AND EE.ACTIVE = 'Y'
LEFT JOIN LIVESupplemental.dbo.buyer_assn B
	ON LEFT(W.BUYER_USER_ID, 2) = B.Account_ID
LEFT JOIN CUSTOMER C
	ON C.ID = W.CUSTOMER_ID
LEFT JOIN PART_SITE_VIEW P
	ON P.PART_ID = W.PART_ID
	AND P.SITE_ID = 'SK01'
	AND W.SUB_ID <> N'0'
LEFT JOIN LIVESupplemental.dbo.buyer_assn leg
	ON leg.Account_ID = LEFT(P.BUYER_USER_ID, 2)
LEFT JOIN (SELECT PO.ID
		, dslPO.DEMAND_BASE_ID
		, DEMAND_LOT_ID
		, DEMAND_SUB_ID
		, DEMAND_SPLIT_ID
		, dslPO.DEMAND_SEQ_NO
		, PO.DESIRED_RECV_DATE
		, PO.PROMISE_SHIP_DATE 
	FROM PURCHASE_ORDER PO
	JOIN DEMAND_SUPPLY_LINK dslPO
		ON dslPO.SUPPLY_BASE_ID = PO.ID
	GROUP BY PO.ID
		, dslPO.DEMAND_BASE_ID
		, DEMAND_LOT_ID
		, DEMAND_SUB_ID
		, DEMAND_SPLIT_ID
		, dslPO.DEMAND_SEQ_NO
		, PO.DESIRED_RECV_DATE
		, PO.PROMISE_SHIP_DATE
	) dslPO
	ON dslPO.DEMAND_BASE_ID = w.BASE_ID
	AND dslPO.DEMAND_LOT_ID = w.LOT_ID
	AND dslPO.DEMAND_SUB_ID = w.SUB_ID
	AND dslPO.DEMAND_SPLIT_ID = w.SPLIT_ID
	AND dslPO.DEMAND_SEQ_NO = w.CurrentOperation
LEFT JOIN @ReportSettings rs
	ON w.RESOURCE_ID_Raw = rs.[Resource]
-- tt20210707: IQM NCM Tag Info
LEFT JOIN LIVESupplemental.dbo.WODS_NCM_TAGS NCM
	ON W.BASE_ID = NCM.WORKORDER_BASE_ID
	AND W.LOT_ID = NCM.WORKORDER_LOT_ID
	AND W.SPLIT_ID = NCM.WORKORDER_SPLIT_ID
	AND W.SUB_ID = NCM.WORKORDER_SUB_ID
	AND W.[TYPE] = 'W'

wods_query_ends:

output_data_in_test:

TRUNCATE TABLE Staging.WODS_Output02
INSERT INTO Staging.WODS_Output02
([BASE_ID]
	, [LOT_ID]
	, [SPLIT_ID]
	, [SUB_ID]
	, [TYPE]
	, [PART_ID]
	, [WONUM]
	, [DESIRED_QTY]
	, [STATUS]
	, [CUSTOMER_ORDER]
	, [LINE_NO]
	, [CUSTOMER_ID]
	, [allocation_type]
	, [CurrentOperation]
	, [StatusCurrOp]
	, [PRINTED_DATE]
	, [DESIRED_RLS_DATE]
	, [CREATE_DATE]
	, [remaining_operations]
	, [QTY_ON_HAND]
	, [QTY_IN_DEMAND]
	, [BUYER_USER_ID]
	, [PLANNER_USER_ID]
	, [COMMODITY_CODE]
	, [DESCRIPTION]
	, [DESIRED_WANT_DATE]
	, [EXP/FLT]
	, [user_10]
	, [col_user_1]
	, [RWPart]
	, [CUSTOMER_PO_REF]
	, [WORK_ORDER_NOTES]
	, [CUST_ORDER_NOTATION]
	, [CUST_ORD_CREATEDATE]
	, [PartMaterialType]
	, [MaterialType]
	, [Alloy]
	, [CO_AMOUNT]
	, [UNIT_PRICE]
	, [TOTAL_AMT_SHIPPED]
	, [COL_AMOUNT]
	, [RESOURCE_ID_Raw]
	, [OPERATION_TYPE]
	, [StatusCurrOpType]
	, [CURROPCHK]
	, [RESOURCE_ID]
	, [AubPriText]
	, [AubTcText]
	, [HasAubPri]
	, [HasAubTc]
	, [TimeLimit]
	, [LAST_CLOCK_OUT]
	, [last_worked_seq]
	, [last_clocked]
	, [LATE]
	, [LATEP2]
	, [LATEP1]
	, [LATEP3]
	, [LATEBP1]
	, [WAIT_DAYS]
	, [EMPLOYEE_ID]
	, [OPERATOR]
	, [USER_1]
	, [LEAD_SUPERVISOR]
	, [SupervisorName]
	, [StatusCurrOpMsg]
	, [tdesc]
	, [LABOR_TICKET_DESC]
	, [BUYER]
	, [BUYERFILTER]
	, [SALESREP_ID]
	, [Account]
	, [Plant_ID]
	, [Tooling]
	, [IsAP1]
	, [IsAP2]
	, [IsAP3]
	, [IsBP1]
	, [IsUndetermined]
	, [IsNORGRU]
	, [IsTWMETA]
	, [IsAMTRIB]
	, [IsAUBMASK]
	, [IsAUBPrime]
	, [IsAUBSand]
	, [IsAUBsetup]
	, [IsAUBTC]
	, [IsAUBtakedown]
	, [IsAUBPartMark]
	, [IsAUBFinalInspection]
	, [IsAUBInspection]
	, [IsAUBPenetrant]
	, [IsAUBChemline]
	, [AP1_ETRAC]
	, [AP2_ETRAC]
	, [AP3_ETRAC]
	, [BP1_ETRAC]
	, [AP1_PDEXP]
	, [AP2_PDEXP]
	, [AP3_PDEXP]
	, [BP1_PDEXP]
	, [AP1_FLT]
	, [AP2_FLT]
	, [AP3_FLT]
	, [BP1_FLT]
	, [AP1_Buyer_Joe]
	, [AP1_Buyer_Rena]
	, [AP1_Buyer_Tiffany]
	, [AP1_Buyer_Sunni]
	, [AP1_Buyer_Danielle]
	, [AP1_Review]
	, [AP1_PlanningQueue]
	, [AP1_SkyFlex]
	, [ID]
	, [DESIRED_RECV_DATE]
	, [SnapshotDate]
	, [DEPARTMENT]
	, [SUB_DEPARTMENT]
	, [FACILITY]
	, [REPT_DEPT]
	, [PROCESS]
	, [REPORT_GROUPING]
	, [EMAIL_ADDR]
	, [SETUP_INFO]
-- tt20210707: IQM NCM Tag Info
	, [NCM_ID]
	, [NCM_DATE]
	, [IQM_PROCESS]
	, [IQM_SUBPROCESS]
	, [IQM_DEFECT]
	, [DISPOSITION_TYPE]
	, [NCM_TYPE]
	)
SELECT [BASE_ID]
	, [LOT_ID]
	, [SPLIT_ID]
	, [SUB_ID]
	, [TYPE]
	, [PART_ID]
	, [WONUM]
	, [DESIRED_QTY]
	, [STATUS]
	, [CUSTOMER_ORDER]
	, [LINE_NO]
	, [CUSTOMER_ID]
	, [allocation_type]
	, [CurrentOperation]
	, [StatusCurrOp]
	, [PRINTED_DATE]
	, [DESIRED_RLS_DATE]
	, [CREATE_DATE]
	, [remaining_operations]
	, [QTY_ON_HAND]
	, [QTY_IN_DEMAND]
	, [BUYER_USER_ID]
	, [PLANNER_USER_ID]
	, [COMMODITY_CODE]
	, [DESCRIPTION]
	, [DESIRED_WANT_DATE]
	, [EXP/FLT]
	, [user_10]
	, [col_user_1]
	, [RWPart]
	, [CUSTOMER_PO_REF]
	, [WORK_ORDER_NOTES]
	, [CUST_ORDER_NOTATION]
	, [CUST_ORD_CREATEDATE]
	, [PartMaterialType]
	, [MaterialType]
	, [Alloy]
	, [CO_AMOUNT]
	, [UNIT_PRICE]
	, [TOTAL_AMT_SHIPPED]
	, [COL_AMOUNT]
	, [RESOURCE_ID_Raw]
	, [OPERATION_TYPE]
	, [StatusCurrOpType]
	, [CURROPCHK]
	, [RESOURCE_ID]
	, [AubPriText]
	, [AubTcText]
	, [HasAubPri]
	, [HasAubTc]
	, [TimeLimit]
	, [LAST_CLOCK_OUT]
	, [last_worked_seq]
	, [last_clocked]
	, [LATE]
	, [LATEP2]
	, [LATEP1]
	, [LATEP3]
	, [LATEBP1]
	, [WAIT_DAYS]
	, [EMPLOYEE_ID]
	, [OPERATOR]
	, [USER_1]
	, [LEAD_SUPERVISOR]
	, [SupervisorName]
	, [StatusCurrOpMsg]
	, [tdesc]
	, [LABOR_TICKET_DESC]
	, [BUYER]
	, [BUYERFILTER]
	, [SALESREP_ID]
	, [Account]
	, [Plant_ID]
	, [Tooling]
	, [IsAP1]
	, [IsAP2]
	, [IsAP3]
	, [IsBP1]
	, [IsUndetermined]
	, [IsNORGRU]
	, [IsTWMETA]
	, [IsAMTRIB]
	, [IsAUBMASK]
	, [IsAUBPrime]
	, [IsAUBSand]
	, [IsAUBsetup]
	, [IsAUBTC]
	, [IsAUBtakedown]
	, [IsAUBPartMark]
	, [IsAUBFinalInspection]
	, [IsAUBInspection]
	, [IsAUBPenetrant]
	, [IsAUBChemline]
	, [AP1_ETRAC]
	, [AP2_ETRAC]
	, [AP3_ETRAC]
	, [BP1_ETRAC]
	, [AP1_PDEXP]
	, [AP2_PDEXP]
	, [AP3_PDEXP]
	, [BP1_PDEXP]
	, [AP1_FLT]
	, [AP2_FLT]
	, [AP3_FLT]
	, [BP1_FLT]
	, [AP1_Buyer_Joe]
	, [AP1_Buyer_Rena]
	, [AP1_Buyer_Tiffany]
	, [AP1_Buyer_Sunni]
	, [AP1_Buyer_Danielle]
	, [AP1_Review]
	, [AP1_PlanningQueue]
	, [AP1_SkyFlex]
	, [ID]
	, [DESIRED_RECV_DATE]
	, [SnapshotDate]
	, [DEPARTMENT]
	, [SUB_DEPARTMENT]
	, [FACILITY]
	, [REPT_DEPT]
	, [PROCESS]
	, [REPORT_GROUPING]
	, [EMAIL_ADDR]
	, [SETUP_INFO]
-- tt20210707: IQM NCM Tag Info
	, [NCM_ID]
	, [NCM_DATE]
	, [IQM_PROCESS]
	, [IQM_SUBPROCESS]
	, [IQM_DEFECT]
	, [DISPOSITION_TYPE]
	, [NCM_TYPE]
FROM (SELECT [BASE_ID]
	, [LOT_ID]
	, [SPLIT_ID]
	, [SUB_ID]
	, [TYPE]
	, [PART_ID]
	, [WONUM]
	, [DESIRED_QTY]
	, [STATUS]
	, [CUSTOMER_ORDER]
	, [LINE_NO]
	, [CUSTOMER_ID]
	, [allocation_type]
	, [CurrentOperation]
	, [StatusCurrOp]
	, [PRINTED_DATE]
	, [DESIRED_RLS_DATE]
	, [CREATE_DATE]
	, [remaining_operations]
	, [QTY_ON_HAND]
	, [QTY_IN_DEMAND]
	, [BUYER_USER_ID]
	, [PLANNER_USER_ID]
	, [COMMODITY_CODE]
	, [DESCRIPTION]
	, [DESIRED_WANT_DATE]
	, [EXP/FLT]
	, [user_10]
	, [col_user_1]
	, [RWPart]
	, [CUSTOMER_PO_REF]
	, [WORK_ORDER_NOTES]
	, [CUST_ORDER_NOTATION]
	, [CUST_ORD_CREATEDATE]
	, [PartMaterialType]
	, [MaterialType]
	, [Alloy]
	, [CO_AMOUNT]
	, [UNIT_PRICE]
	, [TOTAL_AMT_SHIPPED]
	, [COL_AMOUNT]
	, [RESOURCE_ID_Raw]
	, [OPERATION_TYPE]
	, [StatusCurrOpType]
	, [CURROPCHK]
	, [RESOURCE_ID]
	, [AubPriText]
	, [AubTcText]
	, [HasAubPri]
	, [HasAubTc]
	, [TimeLimit]
	, [LAST_CLOCK_OUT]
	, [last_worked_seq]
	, [last_clocked]
	, [LATE]
	, [LATEP2]
	, [LATEP1]
	, [LATEP3]
	, [LATEBP1]
	, [WAIT_DAYS]
	, [EMPLOYEE_ID]
	, [OPERATOR]
	, [USER_1]
	, [LEAD_SUPERVISOR]
	, [SupervisorName]
	, [StatusCurrOpMsg]
	, [tdesc]
	, [LABOR_TICKET_DESC]
	, [BUYER]
	, [BUYERFILTER]
	, [SALESREP_ID]
	, [Account]
	, [Plant_ID]
	, [Tooling]
	, [IsAP1]
	, [IsAP2]
	, [IsAP3]
	, [IsBP1]
	, [IsUndetermined]
	, [IsNORGRU]
	, [IsTWMETA]
	, [IsAMTRIB]
	, [IsAUBMASK]
	, [IsAUBPrime]
	, [IsAUBSand]
	, [IsAUBsetup]
	, [IsAUBTC]
	, [IsAUBtakedown]
	, [IsAUBPartMark]
	, [IsAUBFinalInspection]
	, [IsAUBInspection]
	, [IsAUBPenetrant]
	, [IsAUBChemline]
	, [AP1_ETRAC]
	, [AP2_ETRAC]
	, [AP3_ETRAC]
	, [BP1_ETRAC]
	, [AP1_PDEXP]
	, [AP2_PDEXP]
	, [AP3_PDEXP]
	, [BP1_PDEXP]
	, [AP1_FLT]
	, [AP2_FLT]
	, [AP3_FLT]
	, [BP1_FLT]
	, [AP1_Buyer_Joe]
	, [AP1_Buyer_Rena]
	, [AP1_Buyer_Tiffany]
	, [AP1_Buyer_Sunni]
	, [AP1_Buyer_Danielle]
	, [AP1_Review]
	, [AP1_PlanningQueue]
	, [AP1_SkyFlex]
	, [ID]
	, [DESIRED_RECV_DATE]
	, [SnapshotDate]
	, [DEPARTMENT]
	, [SUB_DEPARTMENT]
	, [FACILITY]
	, [REPT_DEPT]
	, [PROCESS]
	, [REPORT_GROUPING]
	, [EMAIL_ADDR]
	, [SETUP_INFO]
-- tt20210707: IQM NCM Tag Info
	, [NCM_ID]
	, [NCM_DATE]
	, [IQM_PROCESS]
	, [IQM_SUBPROCESS]
	, [IQM_DEFECT]
	, [DISPOSITION_TYPE]
	, [NCM_TYPE]
	, RN = ROW_NUMBER() OVER (PARTITION BY wonum ORDER BY t.[LINE_NO], part_id)
FROM #temp1 t (NOLOCK)
) X
WHERE X.RN = 1

merge_data:

SET NOCOUNT OFF
--> tt20210708 - do these do anything??
DECLARE @TransactionStartDate DATETIME2(7) = SYSDATETIME()
	, @TransactionEndDate DATETIME2(7)
	, @StoredProcedureStartDate DATETIME2(7) = SYSDATETIME()
	, @DurationSeconds INT
	, @Rows INT = 0
	, @RowsPerSecond INT
	, @Error INT
	, @InsertedRows INT = 0
	, @UpdatedRows INT = 0
	, @DeletedRows INT = 0
	, @StoredProcedureName SYSNAME = 
		(SELECT @@SERVERNAME + '.' + DB_NAME() + '.' + s.name + '.' + o.name 
		FROM sys.objects o (NOLOCK) 
		JOIN sys.schemas s (NOLOCK) 
			ON o.schema_id = s.schema_id 
		WHERE o.object_id = @@PROCID)
	, @TargetServer SYSNAME = @@SERVERNAME
	, @TargetDatabase SYSNAME = 'DataWarehouse'
	, @TargetSchema SYSNAME = 'dbo'
	, @TargetTable SYSNAME = 'WODS_Output02'
	, @StepId INT = 1
	, @Step VARCHAR(4000)

DECLARE @MergeResult TABLE (ActionTaken VARCHAR(20) NOT NULL);

MERGE LiveSupplemental.dbo.WODS_Output02 Trgt
USING Staging.WODS_Output02 SRC (NOLOCK)
ON Trgt.WONUM = SRC.WONUM

WHEN MATCHED AND
	trgt.BASE_ID <> src.BASE_ID
	or trgt.LOT_ID <> src.LOT_ID
	OR trgt.SPLIT_ID <> src.SPLIT_ID
	OR trgt.SUB_ID <> src.SUB_ID
	OR trgt.TYPE <> src.TYPE
	OR ISNULL(trgt.PART_ID, '') <> ISNULL(src.PART_ID, '')
	OR ISNULL(trgt.DESIRED_QTY, -30000) <> ISNULL(src.DESIRED_QTY, -30000)
	OR trgt.STATUS <> src.STATUS
	OR ISNULL(trgt.CUSTOMER_ORDER, '') <> ISNULL(src.CUSTOMER_ORDER, '')
	OR ISNULL(trgt.LINE_NO, -30000) <> ISNULL(src.LINE_NO, -30000)
	OR ISNULL(trgt.CUSTOMER_ID, '') <> ISNULL(src.CUSTOMER_ID, '')
	OR ISNULL(trgt.allocation_type, '') <> ISNULL(src.allocation_type, '')
	OR ISNULL(trgt.CurrentOperation, -30000) <> ISNULL(src.CurrentOperation, -30000)
	OR ISNULL(trgt.StatusCurrOp, -30000) <> ISNULL(src.StatusCurrOp, -30000)
	OR ISNULL(trgt.PRINTED_DATE, '1/1/1990') <> ISNULL(src.PRINTED_DATE, '1/1/1990')
	OR ISNULL(trgt.DESIRED_RLS_DATE, '1/1/1990') <> ISNULL(src.DESIRED_RLS_DATE, '1/1/1990')
	OR trgt.CREATE_DATE <> src.CREATE_DATE
	OR trgt.remaining_operations <> src.remaining_operations
	OR trgt.QTY_ON_HAND <> src.QTY_ON_HAND
	OR trgt.QTY_IN_DEMAND <> src.QTY_IN_DEMAND
	OR ISNULL(trgt.BUYER_USER_ID, '') <> ISNULL(src.BUYER_USER_ID, '')
	OR ISNULL(trgt.PLANNER_USER_ID, '') <> ISNULL(src.PLANNER_USER_ID, '')
	OR ISNULL(trgt.COMMODITY_CODE, '') <> ISNULL(src.COMMODITY_CODE, '')
	OR ISNULL(trgt.DESCRIPTION, '') <> ISNULL(src.DESCRIPTION, '')
	OR ISNULL(trgt.DESIRED_WANT_DATE, '1/1/1990') <> ISNULL(src.DESIRED_WANT_DATE, '1/1/1990')
	OR ISNULL(trgt.[EXP/FLT], '') <> ISNULL(src.[EXP/FLT], '')
	OR ISNULL(trgt.user_10, '') <> ISNULL(src.user_10, '')
	OR ISNULL(trgt.col_user_1, '') <> ISNULL(src.col_user_1, '')
	OR ISNULL(trgt.RWPart, '') <> ISNULL(src.RWPart, '')
	OR ISNULL(trgt.CUSTOMER_PO_REF, '') <> ISNULL(src.CUSTOMER_PO_REF, '')
	OR ISNULL(trgt.WORK_ORDER_NOTES, '') <> ISNULL(src.WORK_ORDER_NOTES, '')
	OR ISNULL(trgt.CUST_ORDER_NOTATION, '') <> ISNULL(src.CUST_ORDER_NOTATION, '')
	OR ISNULL(trgt.CUST_ORD_CREATEDATE, '1/1/1990') <> ISNULL(src.CUST_ORD_CREATEDATE, '1/1/1990')
	OR trgt.PartMaterialType <> src.PartMaterialType
	OR trgt.MaterialType <> src.MaterialType
	OR trgt.Alloy <> src.Alloy
	OR ISNULL(trgt.CO_AMOUNT, -30000) <> ISNULL(src.CO_AMOUNT, -30000)
	OR ISNULL(trgt.UNIT_PRICE, -30000) <> ISNULL(src.UNIT_PRICE, -30000)
	OR ISNULL(trgt.TOTAL_AMT_SHIPPED, -30000) <> ISNULL(src.TOTAL_AMT_SHIPPED, -30000)
	OR ISNULL(trgt.COL_AMOUNT, -30000) <> ISNULL(src.COL_AMOUNT, -30000)
	OR ISNULL(trgt.RESOURCE_ID_Raw, '') <> ISNULL(src.RESOURCE_ID_Raw, '')
	OR ISNULL(trgt.OPERATION_TYPE, '') <> ISNULL(src.OPERATION_TYPE, '')
	OR ISNULL(trgt.StatusCurrOpType, '') <> ISNULL(src.StatusCurrOpType, '')
	OR ISNULL(trgt.CURROPCHK, -30000) <> ISNULL(src.CURROPCHK, -30000)
	OR ISNULL(trgt.RESOURCE_ID, '') <> ISNULL(src.RESOURCE_ID, '')
	OR ISNULL(trgt.AubPriText, '') <> ISNULL(src.AubPriText, '')
	OR ISNULL(trgt.AubTcText, '') <> ISNULL(src.AubTcText, '')
	OR trgt.HasAubPri <> src.HasAubPri
	OR trgt.HasAubTc <> src.HasAubTc
	OR ISNULL(trgt.TimeLimit, -30000) <> ISNULL(src.TimeLimit, -30000)
	OR ISNULL(trgt.LAST_CLOCK_OUT, '1/1/1990') <> ISNULL(src.LAST_CLOCK_OUT, '1/1/1990')
	OR ISNULL(trgt.last_worked_seq, -30000) <> ISNULL(src.last_worked_seq, -30000)
	OR ISNULL(trgt.last_clocked, '') <> ISNULL(src.last_clocked, '')
	OR trgt.LATE <> src.LATE
	OR trgt.LATEP2 <> src.LATEP2
	OR trgt.LATEP1 <> src.LATEP1
	OR trgt.LATEP3 <> src.LATEP3
	OR trgt.LATEBP1 <> src.LATEBP1
	OR trgt.WAIT_DAYS <> src.WAIT_DAYS
	OR ISNULL(trgt.EMPLOYEE_ID, '') <> ISNULL(src.EMPLOYEE_ID, '')
	OR trgt.OPERATOR <> src.OPERATOR
	OR ISNULL(trgt.USER_1, '') <> ISNULL(src.USER_1, '')
	OR ISNULL(trgt.LEAD_SUPERVISOR, '') <> ISNULL(src.LEAD_SUPERVISOR, '')
	OR ISNULL(trgt.SupervisorName, '') <> ISNULL(src.SupervisorName, '')
	OR ISNULL(trgt.StatusCurrOpMsg, '') <> ISNULL(src.StatusCurrOpMsg, '')
	OR trgt.tdesc <> src.tdesc
	OR ISNULL(trgt.LABOR_TICKET_DESC, '') <> ISNULL(src.LABOR_TICKET_DESC, '')
	OR trgt.BUYER <> src.BUYER
	OR ISNULL(trgt.BUYERFILTER, '') <> ISNULL(src.BUYERFILTER, '')
	OR ISNULL(trgt.SALESREP_ID, '') <> ISNULL(src.SALESREP_ID, '')
	OR trgt.Account <> src.Account
	OR trgt.Plant_ID <> src.Plant_ID
	OR trgt.Tooling <> src.Tooling
	OR trgt.IsAP1 <> src.IsAP1
	OR trgt.IsAP2 <> src.IsAP2
	OR trgt.IsAP3 <> src.IsAP3
	OR trgt.IsBP1 <> src.IsBP1
	OR trgt.IsUndetermined <> src.IsUndetermined
	OR trgt.IsNORGRU <> src.IsNORGRU
	OR trgt.IsTWMETA <> src.IsTWMETA
	OR trgt.IsAMTRIB <> src.IsAMTRIB
	OR trgt.IsAUBMASK <> src.IsAUBMASK
	OR trgt.IsAUBPrime <> src.IsAUBPrime
	OR trgt.IsAUBSand <> src.IsAUBSand
	OR trgt.IsAUBsetup <> src.IsAUBsetup
	OR trgt.IsAUBTC <> src.IsAUBTC
	OR trgt.IsAUBtakedown <> src.IsAUBtakedown
	OR trgt.IsAUBPartMark <> src.IsAUBPartMark
	OR trgt.IsAUBFinalInspection <> src.IsAUBFinalInspection
	OR trgt.IsAUBInspection <> src.IsAUBInspection
	OR trgt.IsAUBPenetrant <> src.IsAUBPenetrant
	OR trgt.IsAUBChemline <> src.IsAUBChemline
	OR trgt.AP1_ETRAC <> src.AP1_ETRAC
	OR trgt.AP2_ETRAC <> src.AP2_ETRAC
	OR trgt.AP3_ETRAC <> src.AP3_ETRAC
	OR trgt.BP1_ETRAC <> src.BP1_ETRAC
	OR trgt.AP1_PDEXP <> src.AP1_PDEXP
	OR trgt.AP2_PDEXP <> src.AP2_PDEXP
	OR trgt.AP3_PDEXP <> src.AP3_PDEXP
	OR trgt.BP1_PDEXP <> src.BP1_PDEXP
	OR trgt.AP1_FLT <> src.AP1_FLT
	OR trgt.AP2_FLT <> src.AP2_FLT
	OR trgt.AP3_FLT <> src.AP3_FLT
	OR trgt.BP1_FLT <> src.BP1_FLT
	OR trgt.AP1_Buyer_Joe <> src.AP1_Buyer_Joe
	OR trgt.AP1_Buyer_Rena <> src.AP1_Buyer_Rena
	OR trgt.AP1_Buyer_Tiffany <> src.AP1_Buyer_Tiffany
	OR trgt.AP1_Buyer_Sunni <> src.AP1_Buyer_Sunni
	OR trgt.AP1_Buyer_Danielle <> src.AP1_Buyer_Danielle
	OR trgt.AP1_Review <> src.AP1_Review
	OR trgt.AP1_PlanningQueue <> src.AP1_PlanningQueue
	OR trgt.AP1_SkyFlex <> src.AP1_SkyFlex
	OR ISNULL(trgt.ID, '') <> ISNULL(src.ID, '')
	OR ISNULL(trgt.DESIRED_RECV_DATE, '1/1/1990') <> ISNULL(src.DESIRED_RECV_DATE, '1/1/1990')
	OR trgt.SnapshotDate <> src.SnapshotDate
	OR ISNULL(trgt.DEPARTMENT, '') <> ISNULL(src.DEPARTMENT, '')
	OR ISNULL(trgt.SUB_DEPARTMENT, '') <> ISNULL(src.SUB_DEPARTMENT, '')
	OR ISNULL(trgt.FACILITY, '') <> ISNULL(src.FACILITY, '')
	OR ISNULL(trgt.REPT_DEPT, '') <> ISNULL(src.REPT_DEPT, '')
	OR ISNULL(trgt.PROCESS, '') <> ISNULL(src.PROCESS, '')
	OR ISNULL(trgt.REPORT_GROUPING, '') <> ISNULL(src.REPORT_GROUPING, '')
	OR ISNULL(trgt.EMAIL_ADDR, '') <> ISNULL(src.EMAIL_ADDR, '')
	OR ISNULL(trgt.[SETUP_INFO], '') <> ISNULL(src.[SETUP_INFO], '')
-- tt20210707: IQM NCM Tag Info
	OR ISNULL(trgt.[NCM_ID], '') <> ISNULL(src.[NCM_ID], '')
	OR ISNULL(trgt.[NCM_DATE], '') <> ISNULL(src.[NCM_DATE], '')
	OR ISNULL(trgt.[IQM_PROCESS], '') <> ISNULL(src.[IQM_PROCESS], '')
	OR ISNULL(trgt.[IQM_SUBPROCESS], '') <> ISNULL(src.[IQM_SUBPROCESS], '')
	OR ISNULL(trgt.[IQM_DEFECT], '') <> ISNULL(src.[IQM_DEFECT], '')
	OR ISNULL(trgt.[DISPOSITION_TYPE], '') <> ISNULL(src.[DISPOSITION_TYPE], '')
	OR ISNULL(trgt.[NCM_TYPE], '') <> ISNULL(src.[NCM_TYPE], '')

THEN UPDATE SET
	LOT_ID = src.LOT_ID
	, SPLIT_ID = src.SPLIT_ID
	, SUB_ID = src.SUB_ID
	, [TYPE] = src.[TYPE]
	, PART_ID = src.PART_ID
	, WONUM = src.WONUM
	, DESIRED_QTY = src.DESIRED_QTY
	, [STATUS] = src.[STATUS]
	, CUSTOMER_ORDER = src.CUSTOMER_ORDER
	, LINE_NO = src.LINE_NO
	, CUSTOMER_ID = src.CUSTOMER_ID
	, allocation_type = src.allocation_type
	, CurrentOperation = src.CurrentOperation
	, StatusCurrOp = src.StatusCurrOp
	, PRINTED_DATE = src.PRINTED_DATE
	, DESIRED_RLS_DATE = src.DESIRED_RLS_DATE
	, CREATE_DATE = src.CREATE_DATE
	, remaining_operations = src.remaining_operations
	, QTY_ON_HAND = src.QTY_ON_HAND
	, QTY_IN_DEMAND = src.QTY_IN_DEMAND
	, BUYER_USER_ID = src.BUYER_USER_ID
	, PLANNER_USER_ID = src.PLANNER_USER_ID
	, COMMODITY_CODE = src.COMMODITY_CODE
	, [DESCRIPTION] = src.[DESCRIPTION]
	, DESIRED_WANT_DATE = src.DESIRED_WANT_DATE
	, [EXP/FLT] = src.[EXP/FLT]
	, user_10 = src.user_10
	, col_user_1 = src.col_user_1
	, RWPart = src.RWPart
	, CUSTOMER_PO_REF = src.CUSTOMER_PO_REF
	, WORK_ORDER_NOTES = src.WORK_ORDER_NOTES
	, CUST_ORDER_NOTATION = src.CUST_ORDER_NOTATION
	, CUST_ORD_CREATEDATE = src.CUST_ORD_CREATEDATE
	, PartMaterialType = src.PartMaterialType
	, MaterialType = src.MaterialType
	, Alloy = src.Alloy
	, CO_AMOUNT = src.CO_AMOUNT
	, UNIT_PRICE = src.UNIT_PRICE
	, TOTAL_AMT_SHIPPED = src.TOTAL_AMT_SHIPPED
	, COL_AMOUNT = src.COL_AMOUNT
	, RESOURCE_ID_Raw = src.RESOURCE_ID_Raw
	, OPERATION_TYPE = src.OPERATION_TYPE
	, StatusCurrOpType = src.StatusCurrOpType
	, CURROPCHK = src.CURROPCHK
	, RESOURCE_ID = src.RESOURCE_ID
	, AubPriText = src.AubPriText
	, AubTcText = src.AubTcText
	, HasAubPri = src.HasAubPri
	, HasAubTc = src.HasAubTc
	, TimeLimit = src.TimeLimit
	, LAST_CLOCK_OUT = src.LAST_CLOCK_OUT
	, last_worked_seq = src.last_worked_seq
	, last_clocked = src.last_clocked
	, LATE = src.LATE
	, LATEP2 = src.LATEP2
	, LATEP1 = src.LATEP1
	, LATEP3 = src.LATEP3
	, LATEBP1 = src.LATEBP1
	, WAIT_DAYS = src.WAIT_DAYS
	, EMPLOYEE_ID = src.EMPLOYEE_ID
	, OPERATOR = src.OPERATOR
	, USER_1 = src.USER_1
	, LEAD_SUPERVISOR = src.LEAD_SUPERVISOR
	, SupervisorName = src.SupervisorName
	, StatusCurrOpMsg = src.StatusCurrOpMsg
	, tdesc = src.tdesc
	, LABOR_TICKET_DESC = src.LABOR_TICKET_DESC
	, BUYER = src.BUYER
	, BUYERFILTER = src.BUYERFILTER
	, SALESREP_ID = src.SALESREP_ID
	, Account = src.Account
	, Plant_ID = src.Plant_ID
	, Tooling = src.Tooling
	, IsAP1 = src.IsAP1
	, IsAP2 = src.IsAP2
	, IsAP3 = src.IsAP3
	, IsBP1 = src.IsBP1
	, IsUndetermined = src.IsUndetermined
	, IsNORGRU = src.IsNORGRU
	, IsTWMETA = src.IsTWMETA
	, IsAMTRIB = src.IsAMTRIB
	, IsAUBMASK = src.IsAUBMASK
	, IsAUBPrime = src.IsAUBPrime
	, IsAUBSand = src.IsAUBSand
	, IsAUBsetup = src.IsAUBsetup
	, IsAUBTC = src.IsAUBTC
	, IsAUBtakedown = src.IsAUBtakedown
	, IsAUBPartMark = src.IsAUBPartMark
	, IsAUBFinalInspection = src.IsAUBFinalInspection
	, IsAUBInspection = src.IsAUBInspection
	, IsAUBPenetrant = src.IsAUBPenetrant
	, IsAUBChemline = src.IsAUBChemline
	, AP1_ETRAC = src.AP1_ETRAC
	, AP2_ETRAC = src.AP2_ETRAC
	, AP3_ETRAC = src.AP3_ETRAC
	, BP1_ETRAC = src.BP1_ETRAC
	, AP1_PDEXP = src.AP1_PDEXP
	, AP2_PDEXP = src.AP2_PDEXP
	, AP3_PDEXP = src.AP3_PDEXP
	, BP1_PDEXP = src.BP1_PDEXP
	, AP1_FLT = src.AP1_FLT
	, AP2_FLT = src.AP2_FLT
	, AP3_FLT = src.AP3_FLT
	, BP1_FLT = src.BP1_FLT
	, AP1_Buyer_Joe = src.AP1_Buyer_Joe
	, AP1_Buyer_Rena = src.AP1_Buyer_Rena
	, AP1_Buyer_Tiffany = src.AP1_Buyer_Tiffany
	, AP1_Buyer_Sunni = src.AP1_Buyer_Sunni
	, AP1_Buyer_Danielle = src.AP1_Buyer_Danielle
	, AP1_Review = src.AP1_Review
	, AP1_PlanningQueue = src.AP1_PlanningQueue
	, AP1_SkyFlex = src.AP1_SkyFlex
	, ID = src.ID
	, DESIRED_RECV_DATE = src.DESIRED_RECV_DATE
	, SnapshotDate = src.SnapshotDate
	, DEPARTMENT = src.DEPARTMENT
	, SUB_DEPARTMENT = src.SUB_DEPARTMENT
	, FACILITY = src.FACILITY
	, REPT_DEPT = src.REPT_DEPT
	, PROCESS = src.PROCESS
	, REPORT_GROUPING = src.REPORT_GROUPING
	, EMAIL_ADDR = src.EMAIL_ADDR
	, [SETUP_INFO] = src.SETUP_INFO
-- tt20210707: IQM NCM Tag Info
	, [NCM_ID] = src.[NCM_ID]
	, [NCM_DATE] = src.[NCM_DATE]
	, [IQM_PROCESS] = src.[IQM_PROCESS]
	, [IQM_SUBPROCESS] = src.[IQM_SUBPROCESS]
	, [IQM_DEFECT] = src.[IQM_DEFECT]
	, [DISPOSITION_TYPE] = src.[DISPOSITION_TYPE]
	, [NCM_TYPE] = src.[NCM_TYPE]
WHEN NOT MATCHED BY TARGET
	THEN INSERT 
	 (BASE_ID
	, LOT_ID
	, SPLIT_ID
	, SUB_ID
	, [TYPE]
	, PART_ID
	, WONUM
	, DESIRED_QTY
	, [STATUS]
	, CUSTOMER_ORDER
	, LINE_NO
	, CUSTOMER_ID
	, allocation_type
	, CurrentOperation
	, StatusCurrOp
	, PRINTED_DATE
	, DESIRED_RLS_DATE
	, CREATE_DATE
	, remaining_operations
	, QTY_ON_HAND
	, QTY_IN_DEMAND
	, BUYER_USER_ID
	, PLANNER_USER_ID
	, COMMODITY_CODE
	, [DESCRIPTION]
	, DESIRED_WANT_DATE
	, [EXP/FLT]
	, user_10
	, col_user_1
	, RWPart
	, CUSTOMER_PO_REF
	, WORK_ORDER_NOTES
	, CUST_ORDER_NOTATION
	, CUST_ORD_CREATEDATE
	, PartMaterialType
	, MaterialType
	, Alloy
	, CO_AMOUNT
	, UNIT_PRICE
	, TOTAL_AMT_SHIPPED
	, COL_AMOUNT
	, RESOURCE_ID_Raw
	, OPERATION_TYPE
	, StatusCurrOpType
	, CURROPCHK
	, RESOURCE_ID
	, AubPriText
	, AubTcText
	, HasAubPri
	, HasAubTc
	, TimeLimit
	, LAST_CLOCK_OUT
	, last_worked_seq
	, last_clocked
	, LATE
	, LATEP2
	, LATEP1
	, LATEP3
	, LATEBP1
	, WAIT_DAYS
	, EMPLOYEE_ID
	, OPERATOR
	, USER_1
	, LEAD_SUPERVISOR
	, SupervisorName
	, StatusCurrOpMsg
	, tdesc
	, LABOR_TICKET_DESC
	, BUYER
	, BUYERFILTER
	, SALESREP_ID
	, Account
	, Plant_ID
	, Tooling
	, IsAP1
	, IsAP2
	, IsAP3
	, IsBP1
	, IsUndetermined
	, IsNORGRU
	, IsTWMETA
	, IsAMTRIB
	, IsAUBMASK
	, IsAUBPrime
	, IsAUBSand
	, IsAUBsetup
	, IsAUBTC
	, IsAUBtakedown
	, IsAUBPartMark
	, IsAUBFinalInspection
	, IsAUBInspection
	, IsAUBPenetrant
	, IsAUBChemline
	, AP1_ETRAC
	, AP2_ETRAC
	, AP3_ETRAC
	, BP1_ETRAC
	, AP1_PDEXP
	, AP2_PDEXP
	, AP3_PDEXP
	, BP1_PDEXP
	, AP1_FLT
	, AP2_FLT
	, AP3_FLT
	, BP1_FLT
	, AP1_Buyer_Joe
	, AP1_Buyer_Rena
	, AP1_Buyer_Tiffany
	, AP1_Buyer_Sunni
	, AP1_Buyer_Danielle
	, AP1_Review
	, AP1_PlanningQueue
	, AP1_SkyFlex
	, ID
	, DESIRED_RECV_DATE
	, SnapshotDate
	, DEPARTMENT
	, SUB_DEPARTMENT
	, FACILITY
	, REPT_DEPT
	, PROCESS
	, REPORT_GROUPING
	, EMAIL_ADDR 
	, [SETUP_INFO]
-- tt20210707: IQM NCM Tag Info
	, [NCM_ID]
	, [NCM_DATE]
	, [IQM_PROCESS]
	, [IQM_SUBPROCESS]
	, [IQM_DEFECT]
	, [DISPOSITION_TYPE]
	, [NCM_TYPE]
	)
VALUES (BASE_ID
	, LOT_ID
	, SPLIT_ID
	, SUB_ID
	, [TYPE]
	, PART_ID
	, WONUM
	, DESIRED_QTY
	, [STATUS]
	, CUSTOMER_ORDER
	, LINE_NO
	, CUSTOMER_ID
	, allocation_type
	, CurrentOperation
	, StatusCurrOp
	, PRINTED_DATE
	, DESIRED_RLS_DATE
	, CREATE_DATE
	, remaining_operations
	, QTY_ON_HAND
	, QTY_IN_DEMAND
	, BUYER_USER_ID
	, PLANNER_USER_ID
	, COMMODITY_CODE
	, [DESCRIPTION]
	, DESIRED_WANT_DATE
	, [EXP/FLT]
	, user_10
	, col_user_1
	, RWPart
	, CUSTOMER_PO_REF
	, WORK_ORDER_NOTES
	, CUST_ORDER_NOTATION
	, CUST_ORD_CREATEDATE
	, PartMaterialType
	, MaterialType
	, Alloy
	, CO_AMOUNT
	, UNIT_PRICE
	, TOTAL_AMT_SHIPPED
	, COL_AMOUNT
	, RESOURCE_ID_Raw
	, OPERATION_TYPE
	, StatusCurrOpType
	, CURROPCHK
	, RESOURCE_ID
	, AubPriText
	, AubTcText
	, HasAubPri
	, HasAubTc
	, TimeLimit
	, LAST_CLOCK_OUT
	, last_worked_seq
	, last_clocked
	, LATE
	, LATEP2
	, LATEP1
	, LATEP3
	, LATEBP1
	, WAIT_DAYS
	, EMPLOYEE_ID
	, OPERATOR
	, USER_1
	, LEAD_SUPERVISOR
	, SupervisorName
	, StatusCurrOpMsg
	, tdesc
	, LABOR_TICKET_DESC
	, BUYER
	, BUYERFILTER
	, SALESREP_ID
	, Account
	, Plant_ID
	, Tooling
	, IsAP1
	, IsAP2
	, IsAP3
	, IsBP1
	, IsUndetermined
	, IsNORGRU
	, IsTWMETA
	, IsAMTRIB
	, IsAUBMASK
	, IsAUBPrime
	, IsAUBSand
	, IsAUBsetup
	, IsAUBTC
	, IsAUBtakedown
	, IsAUBPartMark
	, IsAUBFinalInspection
	, IsAUBInspection
	, IsAUBPenetrant
	, IsAUBChemline
	, AP1_ETRAC
	, AP2_ETRAC
	, AP3_ETRAC
	, BP1_ETRAC
	, AP1_PDEXP
	, AP2_PDEXP
	, AP3_PDEXP
	, BP1_PDEXP
	, AP1_FLT
	, AP2_FLT
	, AP3_FLT
	, BP1_FLT
	, AP1_Buyer_Joe
	, AP1_Buyer_Rena
	, AP1_Buyer_Tiffany
	, AP1_Buyer_Sunni
	, AP1_Buyer_Danielle
	, AP1_Review
	, AP1_PlanningQueue
	, AP1_SkyFlex
	, ID
	, DESIRED_RECV_DATE
	, SnapshotDate
	, DEPARTMENT
	, SUB_DEPARTMENT
	, FACILITY
	, REPT_DEPT
	, PROCESS
	, REPORT_GROUPING
	, EMAIL_ADDR  
	, [SETUP_INFO]
-- tt20210707: IQM NCM Tag Info
	, [NCM_ID]
	, [NCM_DATE]
	, [IQM_PROCESS]
	, [IQM_SUBPROCESS]
	, [IQM_DEFECT]
	, [DISPOSITION_TYPE]
	, [NCM_TYPE]
)
WHEN NOT MATCHED BY SOURCE 
    THEN DELETE
	OUTPUT $Action INTO @MergeResult;

GO


