USE LIVE
GO

--FINDS ALL MISSING LAST_ORDER_DATE RECORDS
SELECT V.ID
, V.NAME
, V.LAST_ORDER_DATE
, (SELECT MAX(ORDER_DATE) FROM PURCHASE_ORDER P1
	WHERE V.ID = P1.VENDOR_ID) AS MAX_ORDER_DATE
FROM VENDOR V
WHERE V.ID IN (SELECT VENDOR_ID FROM PURCHASE_ORDER)
	AND V.LAST_ORDER_DATE IS NULL

--FINDS LAST_ORDER_DATE NOT EQUAL TO THE NEWEST PO ORDER DAY FOR EACH VENDOR
SELECT V.ID
, V.NAME
, V.LAST_ORDER_DATE
, (SELECT MAX(ORDER_DATE) FROM PURCHASE_ORDER P1
	WHERE V.ID = P1.VENDOR_ID) AS MAX_ORDER_DATE
FROM VENDOR V
WHERE V.ID IN (SELECT VENDOR_ID FROM PURCHASE_ORDER)
	AND V.LAST_ORDER_DATE != (SELECT MAX(ORDER_DATE) FROM PURCHASE_ORDER P1
--	AND V.LAST_ORDER_DATE < (SELECT MAX(ORDER_DATE) FROM PURCHASE_ORDER P1
		WHERE V.ID = P1.VENDOR_ID)
ORDER BY V.ID

SELECT * FROM VENDOR WHERE ID = 'SUNMET'

SELECT * FROM PURCHASE_ORDER WHERE VENDOR_ID = 'SUNMET' ORDER BY ORDER_DATE DESC

SELECT * FROM PURCHASE_ORDER WHERE ORDER_DATE = '7/8/2021'

SELECT TOP 10 * FROM PAYABLE_LINE WHERE PURC_ORDER_ID = '147618'