use DataWarehouse
go

--select co.id
--, part_id
--from CUST_ORDER_LINE col
--inner join CUSTOMER_ORDER co
--on co.id = col.CUST_ORDER_ID
--where co.customer_id = 'VERSAF'

DECLARE @START DATE = '1/1/2017'
;

WITH CTE_LINKED as 
(SELECT 'LINKED' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, SL.SHIPPED_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
	, WO.ACT_BURDEN_COST
	, WO.ACT_MATERIAL_COST
	, WO.ACT_LABOR_COST
	, WO.ACT_SERVICE_COST
FROM DATAWAREHOUSE.dbo.SHIPPER_LINE SL
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
    ON DSL.SUPPLY_TYPE = 'WO' 
    AND DSL.SUPPLY_BASE_ID = WO.BASE_ID
    AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
    AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
    AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
	AND WO.[TYPE] = 'W'
INNER JOIN DATAWAREHOUSE.dbo.RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND RL.PACKLIST_ID = SL.PACKLIST_ID
	AND RL.PACKLIST_LINE_NO = SL.LINE_NO
--	AND RL.AMOUNT != 0
INNER JOIN DATAWAREHOUSE.dbo.RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
LEFT OUTER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
WHERE RL.PACKLIST_ID IS NOT NULL
	AND S.SHIPPED_DATE >= @START
	AND COL.PART_ID IS NOT NULL
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NOT NULL
	AND CO.CUSTOMER_ID = 'VERSAF'
--	AND RL.AMOUNT != 0
)

--SELECT * FROM CTE_LINKED WHERE CUST_ORDER_ID = '429280' --AND LINE_NO = '1'
--ORDER BY CUST_ORDER_ID, LINE_NO, INVOICE_ID

, CTE_UNLINKED as
(SELECT 'UNLINKED1' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, SL.SHIPPED_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
	, WO.ACT_BURDEN_COST
	, WO.ACT_MATERIAL_COST
	, WO.ACT_LABOR_COST
	, WO.ACT_SERVICE_COST
FROM DATAWAREHOUSE.dbo.SHIPPER_LINE SL
INNER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN DATAWAREHOUSE.dbo.RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND SL.PACKLIST_ID = RL.PACKLIST_ID 
	AND SL.LINE_NO = RL.PACKLIST_LINE_NO 
	AND RL.PACKLIST_ID IS NOT NULL
--	AND RL.AMOUNT != 0
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SPLIT_ID = '0'
	AND WO.SUB_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE S.SHIPPED_DATE >= @START
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NULL
	AND CO.CUSTOMER_ID = 'VERSAF'
--	AND RL.AMOUNT != 0
----
UNION ALL
----
SELECT 'UNLINKED2' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
--	, (RL.AMOUNT / ISNULL(RL.QTY, SL.SHIPPED_QTY)) AS INV_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, SL.SHIPPED_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
	, WO.ACT_BURDEN_COST
	, WO.ACT_MATERIAL_COST
	, WO.ACT_LABOR_COST
	, WO.ACT_SERVICE_COST
FROM DATAWAREHOUSE.dbo.SHIPPER_LINE SL
INNER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN DATAWAREHOUSE.dbo.RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND SL.PACKLIST_ID = RL.PACKLIST_ID 
	AND SL.LINE_NO = RL.PACKLIST_LINE_NO 
	AND RL.PACKLIST_ID IS NOT NULL
--	AND RL.AMOUNT != 0
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID + '/' + WO.SUB_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SPLIT_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE S.SHIPPED_DATE >= @START
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NULL
	AND CO.CUSTOMER_ID = 'VERSAF'
--	AND RL.AMOUNT != 0
----
UNION ALL
----
SELECT 'UNLINKED3' AS [ORDER_TYPE]
	, T.TRACE_ID
	, SL.TRANSACTION_ID
	, RL.INVOICE_ID
	, RL.LINE_NO AS INV_LINE
	, T.QTY * -1 AS TRACE_QTY
	, RL.PACKLIST_ID
	, S.SHIPPED_DATE
	, CO.CREATE_DATE AS CO_CREATE_DATE
	, COL.CUST_ORDER_ID
	, COL.LINE_NO AS COL_LINE
	, CO.CUSTOMER_ID
	, COL.PART_ID
	, COL.LINE_STATUS AS SHIP_SHORT
	, COL.ORDER_QTY AS COL_ORDER_QTY
	, COL.TOTAL_SHIPPED_QTY
	, RL.QTY AS REC_QTY
	, COL.UNIT_PRICE AS COL_UNIT_PRICE
	, RL.AMOUNT AS REC_AMOUNT
	, SL.SHIPPED_QTY
	, WO.[STATUS] AS WO_STATUS
	, WO.CREATE_DATE AS WO_CREATE_DATE
	, WO.BASE_ID
	, WO.LOT_ID
	, WO.SPLIT_ID
	, WO.SUB_ID
	, WO.DESIRED_QTY
	, WO.ACT_BURDEN_COST
	, WO.ACT_MATERIAL_COST
	, WO.ACT_LABOR_COST
	, WO.ACT_SERVICE_COST
FROM DATAWAREHOUSE.dbo.SHIPPER_LINE SL
INNER JOIN DATAWAREHOUSE.dbo.TRACE_INV_TRANS  T
	ON SL.TRANSACTION_ID = T.TRANSACTION_ID
INNER JOIN DATAWAREHOUSE.dbo.CUST_ORDER_LINE COL
	ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND COL.PART_ID IS NOT NULL
INNER JOIN DATAWAREHOUSE.dbo.RECEIVABLE_LINE RL
	ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
	AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
	AND SL.PACKLIST_ID = RL.PACKLIST_ID 
	AND SL.LINE_NO = RL.PACKLIST_LINE_NO 
	AND RL.PACKLIST_ID IS NOT NULL
--	AND RL.AMOUNT != 0
INNER JOIN DATAWAREHOUSE.dbo.SHIPPER S
	ON SL.PACKLIST_ID = S.PACKLIST_ID 
INNER JOIN DATAWAREHOUSE.dbo.CUSTOMER_ORDER CO
	ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN DATAWAREHOUSE.dbo.RECEIVABLE R
	ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN DATAWAREHOUSE.dbo.WORK_ORDER WO
	ON (T.TRACE_ID = WO.BASE_ID + '/' + WO.LOT_ID + '.' + WO.SPLIT_ID)
	AND WO.DESIRED_QTY <> 0
	AND WO.SUB_ID = '0'
	AND WO.[TYPE] = 'W'
	AND WO.[STATUS] = 'C'
LEFT OUTER JOIN DATAWAREHOUSE.dbo.DEMAND_SUPPLY_LINK DSL
	ON DSL.DEMAND_TYPE = 'CO'
	AND DSL.DEMAND_BASE_ID = COL.CUST_ORDER_ID
	AND DSL.DEMAND_SEQ_NO = COL.LINE_NO
WHERE S.SHIPPED_DATE >= @START
	AND SL.SHIPPED_QTY <> 0
	AND DSL.SUPPLY_BASE_ID IS NULL
	AND CO.CUSTOMER_ID = 'VERSAF'
)

, CTE_COMBINED AS
(SELECT * 
FROM CTE_LINKED
UNION ALL
SELECT * 
FROM CTE_UNLINKED 
)

SELECT CUSTOMER_ID
, CO_CREATE_DATE
, CUST_ORDER_ID
, COL_LINE
, PART_ID
, COL_ORDER_QTY
, WO_STATUS
, WO_CREATE_DATE
, BASE_ID
, LOT_ID
, SPLIT_ID
, SUB_ID
, DESIRED_QTY
, (SELECT DISTINCT SR.ID
	FROM operation o
	inner join SHOP_RESOURCE sr
	on o.RESOURCE_ID = sr.ID
	WHERE CTE.BASE_ID = O.WORKORDER_BASE_ID
	AND CTE.LOT_ID = O.WORKORDER_LOT_ID
	AND CTE.SPLIT_ID = O.WORKORDER_SPLIT_ID
	AND CTE.SUB_ID = O.WORKORDER_SUB_ID
	AND O.WORKORDER_TYPE = 'W'
--	AND O.RESOURCE_ID IN ('AUB-assyPM', 'AUB-pm', 'AUB-PM-Cargo', 'BAL-pm', 'hydroform', 'P1F1-CP-PM', 'P1F1-PM', 'P1F2-PM-CMP', 'P2M1-PM', 'P3M1-PM', 'pm', 'straightening')
	AND (SR.[DESCRIPTION] LIKE'%PART MARK%' OR SR.USER_2 = 'PART MARK')
) AS [PM]
FROM CTE_COMBINED CTE

-- select * from SHOP_RESOURCE where id in ('AUB-assyPM', 'AUB-pm', 'AUB-PM-Cargo', 'BAL-pm', 'hydroform', 'P1F1-CP-PM', 'P1F1-PM', 'P1F2-PM-CMP', 'P2M1-PM', 'P3M1-PM', 'pm', 'straightening')