USE LIVE
GO

IF EXISTS
(SELECT U.[USER_ID]
	, U.PROGRAM_ID
	, U.PERMISSION
FROM [USER_PGM_AUTHORITY] U
WHERE U.PROGRAM_ID IN ('VMCHKTRG', 'VMSTEMNT', 'VMPRFMNT', 'VMCODMNT', 'VMAUDMNT', 'VMAENMNT', 'VMAPLGLB', 'VMQUERY', 'VMTRVRPT', 'VQAPLGLB', 'VQDEFINE', 'VQWOINP', 'VQTEST', 'VMEQMNT', 'VMUPMNT', 'VMEQPMM', 'VFAPLGLB', 'VCCURMNT', 'VMESTWIN', 'VMRMAENT', 'VMCSRRPT', 'VMDBRSCH', 'VMDBRMNT', 'VMDBRMGT', 'VMDBRDBD', 'VMGLBSCH', 'VMRUTRPT', 'VMDLAYRP', 'VFSCPGEN', 'VMCSTSIM', 'VMPRJWIN', 'VMPRJSUM', 'VMPRJJRN', 'VMPRJBNT', 'VMREVREC', 'VMPRBINQ', 'VMPRJMNT', 'VMRTEMNT', 'VMMAPMNT', 'VMTAXMNT', 'VMPBCENT')
AND U.[USER_ID] NOT IN ('AIP', 'AUBNOBRAKEFORM', 'BARCODE', 'BLANK', 'BRAKEM1', 'BRAKEM2', 'BRAKEM3', 'CNC', 'Config/Plan ECN', 'DOOSAN1', 'DOOSAN2', 'ECN ADMIN', 'ECN Entry', 'EXPEDITE', 'Gen Sec', 'Gen Security', 'HAAS1', 'HAAS10', 'HAAS11', 'HAAS12', 'HAAS13', 'HAAS14', 'HAAS15', 'HAAS16', 'HAAS17', 'HAAS18', 'HAAS19', 'HAAS2', 'HAAS20', 'HAAS21', 'HAAS3', 'HAAS4', 'HAAS5', 'HAAS6', 'HAAS7', 'HAAS8', 'HAAS9', 'HANSG', 'MACRO', 'MacrosGeneral', 'MENUUSER', 'OKUMA', 'PAINTER', 'PAINTERBATCH', 'PREDATOR', 'PURCHASE', 'ROMFG', 'ROUTER1', 'ROUTER2', 'ROUTER3', 'ROUTER4', 'SKILLS\barcode', 'TANKLINE', 'TANKLINEBATCH', 'testing2', 'TM1', 'TM2', 'TRAINER', 'UMC1', 'UMC2', 'TRACIT', 'ED')
AND U.PERMISSION = 'Y')
	SELECT 1 AS Result
ELSE 
	SELECT 0 AS Result

; WITH CTE_SLCT AS
(SELECT U.[USER_ID]
	, U.PROGRAM_ID
	, U.PERMISSION
FROM [USER_PGM_AUTHORITY] U
WHERE U.PROGRAM_ID IN ('VMCHKTRG', 'VMSTEMNT', 'VMPRFMNT', 'VMCODMNT', 'VMAUDMNT', 'VMAENMNT', 'VMAPLGLB', 'VMQUERY', 'VMTRVRPT', 'VQAPLGLB', 'VQDEFINE', 'VQWOINP', 'VQTEST', 'VMEQMNT', 'VMUPMNT', 'VMEQPMM', 'VFAPLGLB', 'VCCURMNT', 'VMESTWIN', 'VMRMAENT', 'VMCSRRPT', 'VMDBRSCH', 'VMDBRMNT', 'VMDBRMGT', 'VMDBRDBD', 'VMGLBSCH', 'VMRUTRPT', 'VMDLAYRP', 'VFSCPGEN', 'VMCSTSIM', 'VMPRJWIN', 'VMPRJSUM', 'VMPRJJRN', 'VMPRJBNT', 'VMREVREC', 'VMPRBINQ', 'VMPRJMNT', 'VMRTEMNT', 'VMMAPMNT', 'VMTAXMNT', 'VMPBCENT')
AND U.[USER_ID] NOT IN ('AIP', 'AUBNOBRAKEFORM', 'BARCODE', 'BLANK', 'BRAKEM1', 'BRAKEM2', 'BRAKEM3', 'CNC', 'Config/Plan ECN', 'DOOSAN1', 'DOOSAN2', 'ECN ADMIN', 'ECN Entry', 'EXPEDITE', 'Gen Sec', 'Gen Security', 'HAAS1', 'HAAS10', 'HAAS11', 'HAAS12', 'HAAS13', 'HAAS14', 'HAAS15', 'HAAS16', 'HAAS17', 'HAAS18', 'HAAS19', 'HAAS2', 'HAAS20', 'HAAS21', 'HAAS3', 'HAAS4', 'HAAS5', 'HAAS6', 'HAAS7', 'HAAS8', 'HAAS9', 'HANSG', 'MACRO', 'MacrosGeneral', 'MENUUSER', 'OKUMA', 'PAINTER', 'PAINTERBATCH', 'PREDATOR', 'PURCHASE', 'ROMFG', 'ROUTER1', 'ROUTER2', 'ROUTER3', 'ROUTER4', 'SKILLS\barcode', 'TANKLINE', 'TANKLINEBATCH', 'testing2', 'TM1', 'TM2', 'TRAINER', 'UMC1', 'UMC2', 'TRACIT', 'ED')
AND U.PERMISSION = 'Y'
)

SELECT * FROM CTE_SLCT
PIVOT(MAX(PERMISSION)
	FOR PROGRAM_ID IN (VMCHKTRG, VMSTEMNT, VMPRFMNT, VMCODMNT, VMAUDMNT, VMAENMNT, VMAPLGLB, VMQUERY, VMTRVRPT, VQAPLGLB, VQDEFINE, VQWOINP, VQTEST, VMEQMNT, VMUPMNT, VMEQPMM, VFAPLGLB, VCCURMNT, VMESTWIN, VMRMAENT, VMCSRRPT, VMDBRSCH, VMDBRMNT, VMDBRMGT, VMDBRDBD, VMGLBSCH, VMRUTRPT, VMDLAYRP, VFSCPGEN, VMCSTSIM, VMPRJWIN, VMPRJSUM, VMPRJJRN, VMPRJBNT, VMREVREC, VMPRBINQ, VMPRJMNT, VMRTEMNT, VMMAPMNT, VMTAXMNT, VMPBCENT)
) AS [PIVOTTABLE]

/*

DELETE FROM [USER_PGM_AUTHORITY] WHERE USER_ID = 'CYDENYD'

SELECT * FROM EMPLOYEE WHERE USER_ID = 'JEFFA'

The User permission only gets written to the table for a user when something other than full access (Yes) is selected because 
all users get full access by default. Once a selection is made, then that selected permission is written to the table for that 
specific user.

In other words:
In Visual Full Access is assumed unless permission is revoked or changed and the User_pgm_authority table lists only those 
changes from full. User_M_Authority table permission column values:
N = No Permission
R = Read Only permission
Y = ONLY if the user has a Profile Sting set. If Full Access is granted (default) it will not be listed in the table.

VMAUDMNT does not show in the USER_PGM_AUTHORITY table when the security setting is N
Audit Maintenance does not appear in the USER_PGM_AUTHORITY table when the permission is set to N
The default value for VMAUDMNT is N. Programs do not appear in the USER_PGM_AUTHORITY unless a value 
different than the default is selected. All other modules have a default value of Y.  Since Audit Maintenance 
is not restricted to a SYSADM only function the default value is set to N so a user other than SYSADM can have 
rights to this module without granting default permission to all users.

User information remains in the USER_PGM_AUTHORITY table after a VISUAL user has been deleted
The user information that remains in the USER_PGM_AUTHORITY table after a VISUAL user has been deleted have 
no ill-effect on the application. This only allows for the recreation of the deleted user without having to set 
their Program permissions again.

Visual has two Security Reports available under Application Global Mnt. \ File - Print Security Report (SECURITY.QRP) 
or Print Component Security Report (SECURIT2.QRP).
These reports query the USER_PGM_AUTHORITY, USER_MNU_AUTHORITY, AND APPLICATION_USER tables.


SELECT * FROM [USER_PGM_AUTHORITY] WHERE USER_ID = 'AARONE' --PROFILE_STRING IS NULL AND PERMISSION = 'Y'
USER_ID = 'TRACIT' AND 
AND PROGRAM_ID = 'VMAENMNT'
SELECT USER_ID, PROGRAM_ID, PERMISSION FROM [USER_PGM_AUTHORITY] WHERE PROGRAM_ID LIKE 'VMEMPMNT' --GROUP BY USER_ID ORDER BY USER_ID

SELECT * FROM [APPLICATION] A WHERE PROGRAM_ID IN ('VMEQMNT','VMUPMNT','VMEQPMM')
SELECT * FROM [PROGRAM_NAME] P WHERE PROGRAM_ID IN ('VMEQMNT','VMUPMNT','VMEQPMM')
SELECT * FROM [APPLICATION_FIELDS] F
SELECT * FROM [MENU_NAME] M WHERE USER_ID = 'TRACIT'
SELECT * FROM [APPLICATION_LINK] L
SELECT * FROM [APPLICATION_GROUP] G 
SELECT * FROM [APPLICATION_USER] U WHERE NAME = 'TRACIT'
SELECT * FROM [USER_FLD_AUTHORITY] FA
SELECT * FROM [USER_MNU_AUTHORITY] M

CREATE PERMISSIONS CHECK FOR:
VMCHKTRG
VMBTSLP
VMSTEMNT
VMPRFMNT
VMCODMNT
VMAUDMNT
VMAENMNT
VMAPLGLB
VMQUERY
VMTRVRPT
VQAPLGLB
VQDEFINE
VQWOINP
VQTEST
VMEQMNT
VMUPMNT
VMEQPMM
VFAPLGLB
VCCURMNT
VMESTWIN
VMRMAENT
VMCSRRPT
VMDBRSCH
VMDBRMNT
VMDBRMGT
VMDBRDBD
VMGLBSCH
VMRUTRPT
VMDLAYRP
VFSCPGEN
VMCSTSIM
VMPRJWIN
VMPRJSUM
VMPRJJRN
VMPRJBNT
VMREVREC
VMPRBINQ
VMPRJMNT
VMRTEMNT
VMMAPMNT
VMTAXMNT
VMPBCENT


*/