--SELECT TOP 5 * FROM WIP_SERVICE_DETAIL ORDER BY ROWID DESC
----> difference between various dists above should match up to below
--SELECT TOP 5 * FROM WIP_ISSUE_DIST ORDER BY ROWID DESC
----> differences can then be looked up in:
--SELECT TOP 5 * FROM SERVICE_RECEIPT ORDER BY ROWID DESC


DECLARE @PO NVARCHAR(10) = '150816'

SELECT * FROM PURCHASE_DIST WHERE PURC_ORDER_ID = @PO
--> get max dist_no

SELECT * FROM PURC_SERV_DETAIL WHERE PURC_ORDER_ID = @PO

SELECT * FROM SERVICE_RECEIPT WHERE TRANSACTION_ID = '67249'

--SELECT * FROM WIP_ISSUE_DETAIL WHERE WORKORDER_BASE_ID = '1654574'

SELECT * FROM WIP_SERVICE_DETAIL WHERE WORKORDER_BASE_ID = '1654574'

SELECT * FROM WIP_ISSUE_DIST WHERE WORKORDER_BASE_ID = '1654574'

