USE DataWarehouse
GO

SELECT RESULT.[BUSINESS_UNIT]
	, RESULT.HOURS_WORKED
	, RESULT.MONTH_YEAR AS MONTH_YEAR
	, WB.BUDGET
	-- PRECISION REQUIRED FOR DIVISION OF INTEGERS
	-- TEMPLATE USED FOR COPY PASTE
	, CAST(ROUND(IIF(RESULT.ISPRORATED = 1, 
		(CONVERT(FLOAT,RESULT.HOURS_WORKED) / RESULT.BUDREQ1) * RESULT.BUDREQ2, 
		CONVERT(FLOAT,RESULT.HOURS_WORKED)), 0) AS DECIMAL(12,0)) - CAST(WB.BUDGET AS DECIMAL(12,2)
		) AS [Ahead/(Behind)]
	, CAST(ROUND(IIF(RESULT.ISPRORATED = 1, 
		(CONVERT(FLOAT,RESULT.HOURS_WORKED) / RESULT.BUDREQ1) * RESULT.BUDREQ2, 
		CONVERT(FLOAT,RESULT.HOURS_WORKED)), 2) AS DECIMAL(12,2)
		) AS [RUNRATE]
FROM (SELECT CASE    
			--WHEN SR.USER_1 = 'B' THEN 'FINISH'
			--WHEN SR.USER_1 = 'A' THEN 'FINISH'
			WHEN SR.USER_1 = 'M' THEN 'MANUFACTURING'
			ELSE 'FINISH'
		END AS BUSINESS_UNIT
--		, SR.SKILLS_TYPE
		, SUM(LT.HOURS_WORKED) AS HOURS_WORKED
		, DATEFROMPARTS(YEAR(LT.TRANSACTION_DATE), MONTH(LT.TRANSACTION_DATE), 1) AS MONTH_YEAR
		, CAST(DATEDIFF(DAY, (EOMONTH (GETDATE(), -1)), GETDATE()) AS FLOAT) AS BUDREQ1
		, CAST(DATEDIFF(DAY, (EOMONTH (GETDATE(), -1)), EOMONTH(GETDATE(),-0)) AS FLOAT) AS BUDREQ2
		, CASE 
			WHEN EOMONTH(GETDATE(), -1) < DATEFROMPARTS(YEAR(LT.TRANSACTION_DATE), MONTH(LT.TRANSACTION_DATE), 1) THEN 1 
			ELSE 0 
		END AS ISPRORATED
	FROM Datawarehouse.dbo.LABOR_TICKET LT
	INNER JOIN Datawarehouse.dbo.SHOP_RESOURCE SR
		ON LT.RESOURCE_ID = SR.ID
	WHERE LT.TRANSACTION_DATE >= '1/1/2019'
		AND SR.USER_1 IN ('A', 'B', 'M')
	GROUP BY CASE    
		WHEN SR.USER_1 = 'M' THEN 'MANUFACTURING'
		ELSE 'FINISH'
	END
--		, SR.SKILLS_TYPE
		, DATEFROMPARTS(YEAR(LT.TRANSACTION_DATE), MONTH(LT.TRANSACTION_DATE), 1)
	) AS RESULT
LEFT OUTER JOIN Datawarehouse.dbo.[WIPBUDGET] WB
	ON RESULT.MONTH_YEAR = WB.STARTDATE  
	AND RESULT.BUSINESS_UNIT = WB.TYPEOF

