USE DataWarehouse
GO

SELECT WO.BASE_ID
, WO.LOT_ID
, WO.SPLIT_ID
, WO.SUB_ID
, O.SEQUENCE_NO
, O.RESOURCE_ID
, SR.USER_1 AS SKILLS_TYPE
, SR.USER_2 AS [PRIMARY]
, SR.USER_3 AS [SECONDARY]
, SR.USER_4 AS FL_SUPERVISOR
, SR.USER_5 AS FACILITY
, SR.USER_6 AS DEPARTMENT
, SR.USER_7 AS PROCESS
, SR.USER_8 AS REPT_GROUP
, O.OPERATION_TYPE
FROM WORK_ORDER WO
LEFT OUTER JOIN OPERATION O
ON WO.BASE_ID = O.WORKORDER_BASE_ID
AND WO.LOT_ID = O.WORKORDER_LOT_ID
AND WO.SPLIT_ID = O.WORKORDER_SPLIT_ID
AND WO.SUB_ID = O.WORKORDER_SUB_ID
AND WO.[TYPE] = O.WORKORDER_TYPE
LEFT OUTER JOIN SHOP_RESOURCE SR
ON SR.ID = O.RESOURCE_ID

WHERE (SR.STATUS IS NULL OR SR.STATUS != 'O')
AND WO.[TYPE] = 'M'
AND SR.USER_5 = 'AP1'
