; WITH OP_BINARY AS
(SELECT OB.WORKORDER_BASE_ID
	, OB.WORKORDER_LOT_ID
	, OB.WORKORDER_SPLIT_ID
	, OB.WORKORDER_SUB_ID
	, OB.WORKORDER_TYPE
	, OB.SEQUENCE_NO
	, CONVERT(NVARCHAR(MAX), CONVERT(VARBINARY(MAX), OB.BITS)) AS SPECS
FROM OPERATION_BINARY OB
WHERE OB.WORKORDER_TYPE IN (@WO_TYPE)
	AND CONVERT(NVARCHAR(MAX), CONVERT(VARBINARY(MAX), OB.BITS)) LIKE '%' + @SPECS + '%'
	AND OB.BITS IS NOT NULL
	AND EXISTS(SELECT 1 FROM WORK_ORDER W 
		WHERE W.[STATUS] IN (@WO_STATUS)
			AND W.BASE_ID = OB.WORKORDER_BASE_ID
			AND W.LOT_ID = OB.WORKORDER_LOT_ID
			AND W.SUB_ID = OB.WORKORDER_SUB_ID
			AND W.SPLIT_ID = OB.WORKORDER_SPLIT_ID
			AND W.[TYPE] = OB.WORKORDER_TYPE
			AND W.PART_ID LIKE REPLACE(ISNULL(@PART_ID, '%') + '%', '%%', '%')
			AND W.CREATE_DATE >= ISNULL(@STARTDATE, '1/1/2020')
			AND W.CREATE_DATE <= ISNULL(@ENDDATE, GETDATE())
		)
)

, WO_BINARY AS
(SELECT WB.WORKORDER_BASE_ID
	, WB.WORKORDER_LOT_ID
	, WB.WORKORDER_SPLIT_ID
	, WB.WORKORDER_SUB_ID
	, WB.WORKORDER_TYPE
	, CONVERT(NVARCHAR(MAX), CONVERT(VARBINARY(MAX), WB.BITS)) AS SPECS 
FROM WORKORDER_BINARY WB
WHERE WB.WORKORDER_TYPE IN (@WO_TYPE)
	AND CONVERT(NVARCHAR(MAX), CONVERT(VARBINARY(MAX), WB.BITS)) LIKE '%' + @SPECS + '%'
	AND EXISTS(SELECT 1 FROM WORK_ORDER W 
		WHERE W.[STATUS] IN (@WO_STATUS)
			AND W.BASE_ID = WB.WORKORDER_BASE_ID
			AND W.LOT_ID = WB.WORKORDER_LOT_ID
			AND W.SUB_ID = WB.WORKORDER_SUB_ID
			AND W.SPLIT_ID = WB.WORKORDER_SPLIT_ID
			AND W.[TYPE] = WB.WORKORDER_TYPE
			AND W.PART_ID LIKE REPLACE(ISNULL(@PART_ID, '%') + '%', '%%', '%')
			AND W.CREATE_DATE >= ISNULL(@STARTDATE, '1/1/2020')
			AND W.CREATE_DATE <= ISNULL(@ENDDATE, GETDATE())
		)
)
--SELECT * FROM OP_BINARY

SELECT *
FROM (SELECT 'WORK ORDER SPECS' AS CAMEFROM
		, W.[TYPE]
		, W.[STATUS]
		, W.BASE_ID
		, W.LOT_ID
		, W.SUB_ID
		, W.SPLIT_ID
		, W.PART_ID
		, CASE 
			WHEN P.[STATUS] = 'O' THEN 'OBSOLETE'
			ELSE 'ACTIVE'
		END AS PART_STATUS
		, '' AS SEQUENCE_NO
		, '' AS RESOURCE_ID
		, '' AS OPERATION_TYPE
		, B2.SPECS
	FROM WORK_ORDER W 
	INNER JOIN WO_BINARY B2
		ON W.[TYPE] = B2.WORKORDER_TYPE 
		AND W.BASE_ID = B2.WORKORDER_BASE_ID
		AND W.LOT_ID = B2.WORKORDER_LOT_ID
		AND W.SPLIT_ID = B2.WORKORDER_SPLIT_ID    
		AND W.SUB_ID = B2.WORKORDER_SUB_ID
	INNER JOIN PART P
		ON W.PART_ID = P.ID
	WHERE W.CREATE_DATE >= ISNULL(@STARTDATE, '1/1/2020')
		AND W.CREATE_DATE <= ISNULL(@ENDDATE, GETDATE())
	UNION
	SELECT 'WORK ORDER SPECS' AS CAMEFROM
		, W.[TYPE]
		, W.[STATUS]
		, W.BASE_ID
		, W.LOT_ID
		, W.SUB_ID
		, W.SPLIT_ID
		, CP.PART_ID AS PART_ID
		, CASE 
			WHEN P.[STATUS] = 'O' THEN 'OBSOLETE'
			ELSE 'ACTIVE'
		END AS PART_STATUS
		, '' AS SEQUENCE_NO
		, '' AS RESOURCE_ID
		, '' AS OPERATION_TYPE
		, B2.SPECS
	FROM WORK_ORDER W 
	INNER JOIN WO_BINARY B2
		ON W.[TYPE] = B2.WORKORDER_TYPE 
		AND W.BASE_ID = B2.WORKORDER_BASE_ID
		AND W.LOT_ID = B2.WORKORDER_LOT_ID
		AND W.SPLIT_ID = B2.WORKORDER_SPLIT_ID 
		AND W.SUB_ID = B2.WORKORDER_SUB_ID   
	INNER JOIN CO_PRODUCT CP
		ON W.[TYPE] = CP.WORKORDER_TYPE 
		AND W.BASE_ID = CP.WORKORDER_BASE_ID
		AND W.LOT_ID = CP.WORKORDER_LOT_ID
		AND W.SPLIT_ID = CP.WORKORDER_SPLIT_ID  
		AND W.SUB_ID = CP.WORKORDER_SUB_ID
	INNER JOIN PART P
		ON CP.PART_ID = P.ID
	WHERE W.CREATE_DATE >= ISNULL(@STARTDATE, '1/1/2020')
		AND W.CREATE_DATE <= ISNULL(@ENDDATE, GETDATE())
	UNION
	SELECT 'OPERATION SPECS' AS CAMEFROM
		, W.[TYPE]
		, W.[STATUS]
		, W.BASE_ID
		, W.LOT_ID
		, W.SUB_ID
		, W.SPLIT_ID
		, W.PART_ID
		, CASE 
			WHEN P.[STATUS] = 'O' THEN 'OBSOLETE'
			ELSE 'ACTIVE'
		END AS PART_STATUS
		, O.SEQUENCE_NO
		, O.RESOURCE_ID
		, O.OPERATION_TYPE
		, B.SPECS
	FROM WORK_ORDER W
	INNER JOIN OPERATION O
		ON W.BASE_ID = O.WORKORDER_BASE_ID
		AND W.LOT_ID = O.WORKORDER_LOT_ID
		AND W.SPLIT_ID = O.WORKORDER_SPLIT_ID
		AND W.SUB_ID  = O.WORKORDER_SUB_ID
		AND W.[TYPE] = O.WORKORDER_TYPE 
	INNER JOIN OP_BINARY B
		ON B.WORKORDER_TYPE = O.WORKORDER_TYPE 
		AND B.WORKORDER_BASE_ID = O.WORKORDER_BASE_ID
		AND B.WORKORDER_LOT_ID = O.WORKORDER_LOT_ID
		AND B.WORKORDER_SPLIT_ID = O.WORKORDER_SPLIT_ID
		AND B.WORKORDER_SUB_ID = O.WORKORDER_SUB_ID
		AND B.SEQUENCE_NO = O.SEQUENCE_NO
	INNER JOIN PART P
		ON W.PART_ID = P.ID
	WHERE W.CREATE_DATE >= ISNULL(@STARTDATE, '1/1/2020')
		AND W.CREATE_DATE <= ISNULL(@ENDDATE, GETDATE())
	) X
GROUP BY CAMEFROM
	, [TYPE]
	, [STATUS]
	, BASE_ID
	, LOT_ID
	, SUB_ID
	, SPLIT_ID
	, PART_ID
	, PART_STATUS
	, SEQUENCE_NO
	, RESOURCE_ID
	, OPERATION_TYPE
	, SPECS