USE LIVE
GO

SELECT X.*
, DIOH + DSO - DPO AS 'CASH CONVERGENCE TIME'
FROM 
(SELECT AB.ACCT_PERIOD
, AB.ACCT_YEAR
, (SUM(INVENTORY) / ((SUM(COGS) + SUM([A])) / (365/12))) AS DIOH
, SUM(AR) / ((SUM(SALES)) / (365/12)) AS DSO
, (ABS(SUM(AP)) / ((SUM(COGS) + SUM([A])) / (365/12))) AS DPO
--, (SUM(INVENTORY) / (SUM(COGS) + SUM([A]) / (365/12))) --DIOH
--	+ SUM(AR) / (SUM(SALES) / (365/12)) --+DSO
--	- ((SUM(COGS) + SUM([A])) / (ABS(SUM(AP)) / (365/12))
------    (ABS(SUM(AP)) / ((SUM(COGS) + SUM([A])) / (365/12))) -- DPO
--		) AS 'CCT'
FROM 
	(SELECT AB.*
	, CASE
		WHEN A.ID = '5' THEN AB.DEBIT_AMOUNT - AB.CREDIT_AMOUNT
		ELSE 0
	END AS COGS
	, CASE
		WHEN A.ID = '6' THEN AB.DEBIT_AMOUNT - AB.CREDIT_AMOUNT
		ELSE 0
	END AS [A]
	, CASE
		WHEN A.ID = '16' THEN AB.CURR_BALANCE
		ELSE 0
	END AS INVENTORY
	, CASE
		WHEN A.ID = '4' THEN (AB.CREDIT_AMOUNT - AB.DEBIT_AMOUNT)
		ELSE 0
	END AS SALES
	, CASE
		WHEN A.ID = '46' THEN (AB.CREDIT_AMOUNT - AB.DEBIT_AMOUNT)
		ELSE 0
	END AS [O]
	, CASE
		WHEN A.ID = '13' THEN AB.CURR_BALANCE
		ELSE 0
	END AS AR
	, CASE
		WHEN A.ID IN ('200', '201', '205', '210', '211', '212', '215', '250', '257', '280', '285') THEN CURR_BALANCE
		ELSE 0
	END AS AP
	FROM ACCOUNT A
	INNER JOIN ACCOUNT_BALANCE AB
		ON A.ID = AB.ACCOUNT_ID
	INNER JOIN ACCOUNT_PERIOD AP
		ON AP.ACCT_PERIOD = AB.ACCT_PERIOD
		AND AP.ACCT_YEAR = AB.ACCT_YEAR
	WHERE A.ID IN ('200', '201', '205', '210', '211', '212', '215', '250', '257', '280', '285', '200', '201', '205', '210', '211', '212', '215', '250', '257', '280', '285','5', '6','16', '4', '13', '46')
		AND AB.ACCT_YEAR >= YEAR(GETDATE())-1
		AND AP.END_DATE < GETDATE()
	) AB
GROUP BY AB.ACCT_PERIOD
	, AB.ACCT_YEAR
) X
ORDER BY X.ACCT_YEAR
	, X.ACCT_PERIOD