SELECT CUSTOMER_PO_REF + ' '+ BOL.SHIPTO_NAME AS NAME,
      BOL.SHIPTO_ADDR_2 AS ADDR_2,
      BOL.SHIPTO_ADDR_1 AS ADDR_1,
      BOL.SHIPTO_ADDR_3 AS ADDR_3,
      BOL.SHIPTO_CITY AS CITY,
      BOL.SHIPTO_STATE AS STATE,
      BOL.SHIPTO_ZIPCODE AS ZIPCODE,
      C.ID AS CUSTOMER_ID,
      CO.CUSTOMER_PO_REF,
      SL.SHIPPED_QTY,
      COL.PART_ID,
      [DBO].[SFNWONUMFORMAT](DSL.WO_BASE,DSL.WO_LOT,DSL.WO_SPLIT,DSL.WO_SUB) AS WONUM_ID,
      DSL.WO_BASE AS SUPPLY_BASE_ID,
      DSL.WO_LOT AS SUPPLY_LOT_ID,
      DSL.WO_SPLIT AS SUPPLY_SPLIT_ID,
      DSL.WO_SUB AS SUPPLY_SUB_ID,
      COL.MISC_REFERENCE,
      S.BOL_ID,
      S.SHIPPED_DATE,
      CO.ID,
      COL.CUST_ORDER_ID,
      S.PACKLIST_ID,
      BOL.SHIP_DATE
FROM SHIPPER_LINE AS sl  --CUSTOMER AS CUSTOMER
    JOIN CUST_ORDER_LINE AS col
        ON sl.CUST_ORDER_ID = col.CUST_ORDER_ID
            AND col.LINE_NO = sl.CUST_ORDER_LINE_NO
    JOIN SHIPPER s
        ON s.PACKLIST_ID = sl.PACKLIST_ID 
    JOIN CUSTOMER_ORDER AS co
        ON s.CUST_ORDER_ID = co.ID
    JOIN CUSTOMER c 
        ON co.CUSTOMER_ID = c.ID 

    INNER JOIN DEMAND_SUPPLY_LINK_3 AS dsl
    ON col.CUST_ORDER_ID = dsl.CUST_ORDER_ID
        AND col.LINE_NO = dsl.LINE_NO
    INNER JOIN BOL
    ON s.BOL_ID = BOL.ID

WHERE  (s.BOL_ID = @bolid)
      AND (sl.SHIPPED_QTY > 0)
union all
SELECT CUSTOMER_PO_REF + ' '+ BOL.SHIPTO_NAME AS NAME,
      BOL.SHIPTO_ADDR_2 AS ADDR_2,
      BOL.SHIPTO_ADDR_1 AS ADDR_1,
      BOL.SHIPTO_ADDR_3 AS ADDR_3,
      BOL.SHIPTO_CITY AS CITY,
      BOL.SHIPTO_STATE AS STATE,
      BOL.SHIPTO_ZIPCODE AS ZIPCODE,
      C.ID AS CUSTOMER_ID,
      CO.CUSTOMER_PO_REF,
      SL.SHIPPED_QTY,
      COL.PART_ID,
      [DBO].[SFNWONUMFORMAT](DSL.WO_BASE,DSL.WO_LOT,DSL.WO_SPLIT,DSL.WO_SUB) AS WONUM_ID,
      DSL.WO_BASE AS SUPPLY_BASE_ID,
      DSL.WO_LOT AS SUPPLY_LOT_ID,
      DSL.WO_SPLIT AS SUPPLY_SPLIT_ID,
      DSL.WO_SUB AS SUPPLY_SUB_ID,
      COL.MISC_REFERENCE,
      S.BOL_ID,
      S.SHIPPED_DATE,
      CO.ID,
      COL.CUST_ORDER_ID,
      S.PACKLIST_ID,
      BOL.SHIP_DATE
FROM LIVEARC.DBO.SHIPPER_LINE AS sl  --CUSTOMER AS CUSTOMER
    JOIN LIVEARC.DBO.CUST_ORDER_LINE AS col
        ON sl.CUST_ORDER_ID = col.CUST_ORDER_ID
            AND col.LINE_NO = sl.CUST_ORDER_LINE_NO
    JOIN LIVEARC.DBO.SHIPPER s
        ON s.PACKLIST_ID = sl.PACKLIST_ID 
    JOIN LIVEARC.DBO.CUSTOMER_ORDER AS co
        ON s.CUST_ORDER_ID = co.ID
    JOIN LIVEARC.DBO.CUSTOMER c 
        ON co.CUSTOMER_ID = c.ID 

    INNER JOIN LIVEARC.DBO.DEMAND_SUPPLY_LINK_3 AS dsl
    ON col.CUST_ORDER_ID = dsl.CUST_ORDER_ID
        AND col.LINE_NO = dsl.LINE_NO
    INNER JOIN LIVEARC.DBO.BOL
    ON s.BOL_ID = BOL.ID

WHERE  (s.BOL_ID = @bolid)
      AND (sl.SHIPPED_QTY > 0)
