SELECT CO.ID, 
      CO.CUSTOMER_ID, 
      COL.LINE_NO, 
      COL.PART_ID,
      COL.WAREHOUSE_ID,  
      COL.ORDER_QTY,
      COL.TOTAL_SHIPPED_QTY, 
      COL.DESIRED_SHIP_DATE, 
      CO.CUSTOMER_PO_REF, 
      COL.ORDER_QTY - COL.TOTAL_SHIPPED_QTY AS QTY_DIFF, 
      CASE
         WHEN COL.LINE_STATUS = 'C'
         THEN 'Yes'
         ELSE 'No'
      END AS SHIPPED_SHORT,  
      PSV.BUYER_USER_ID
FROM DBO.CUST_ORDER_LINE COL
    INNER JOIN DBO.CUSTOMER_ORDER CO
       ON COL.CUST_ORDER_ID = CO.ID
     LEFT OUTER JOIN PART_SITE_VIEW PSV
    ON COL.PART_ID = PSV.PART_ID
WHERE NOT(COL.DESIRED_SHIP_DATE >= {ts '1901-01-01 00:00:00'}
        AND COL.DESIRED_SHIP_DATE < {ts '1901-01-01 00:00:01'})
     AND NOT(CO.CUSTOMER_ID = N'AERMAN2'
            OR CO.CUSTOMER_ID = N'BOAELE'
            OR CO.CUSTOMER_ID = N'BOE609'
            OR CO.CUSTOMER_ID = N'EMEDOW'
            OR CO.CUSTOMER_ID = N'NORCOM'
            OR CO.CUSTOMER_ID = N'PROCOA'
            OR CO.CUSTOMER_ID = N'SKILLS Q.A.')
     AND NOT(CO.STATUS = N'C'
            OR CO.STATUS = N'X')
--and LINE_STATUS = 'C'
ORDER BY COL.DESIRED_SHIP_DATE;
