SELECT BASE.*
    , O.RESOURCE_ID
    , O.OPERATION_TYPE
    , CASE 
        WHEN O.RESOURCE_ID LIKE '%ASSY%' THEN 'M' 
        WHEN O.RESOURCE_ID LIKE '%ASSEMBLY%' THEN 'M' 
        WHEN O.RESOURCE_ID LIKE 'RIVET' THEN 'M' 
        WHEN O.RESOURCE_ID LIKE 'GLUE' THEN 'M' 
        WHEN O.RESOURCE_ID LIKE 'CONTRACTOR' THEN 'OS' 
        ELSE SR.SKILLS_TYPE 
    END AS SKILLS_TYPE1
    , CASE 
        WHEN O.RESOURCE_ID IN ('PM', 'BAL-PM', 'AUB-PM', 'AUB-ASSYPM') THEN 1 
        ELSE 0 
    END AS PMCOUNT
    , CASE 
        WHEN O.RESOURCE_ID = 'BAL-SHIP' AND O.OPERATION_TYPE = 'REVISION' THEN 1 
        WHEN O.RESOURCE_ID LIKE '%-SHIP' OR O.RESOURCE_ID LIKE 'RWEC' THEN 0 ELSE 1 
    END AS DIVCOUNT
INTO #T1
FROM (SELECT CUSTID
    , CASE
        WHEN BASE_ID LIKE ('%R%') THEN 'REWORK'
        WHEN PART_ID IS NOT NULL AND SHIPPEDQTY <= 0 THEN 'RETURN' 
        WHEN [DESCRIPTION] IS NULL AND BASE_ID IS NOT NULL THEN 'PARTS' 
        WHEN BASE_ID IS NOT NULL THEN 'PARTS' 
        WHEN [DESCRIPTION] LIKE 'MINIMUM%' THEN 'MIN' 
        WHEN [DESCRIPTION] LIKE ('NRE%') OR [DESCRIPTION] LIKE ('NON RECUR%') 
            OR [DESCRIPTION] LIKE ('NON_RECUR%') OR [DESCRIPTION] LIKE ('COST%') 
            THEN 'NRE'
        WHEN [DESCRIPTION] LIKE 'EXP%' THEN 'EXP' 
        WHEN ([DESCRIPTION] LIKE ('%PENE%') OR [DESCRIPTION] LIKE ('%PENA%')) AND TOTALCOST < 0 THEN 'PEN CREDIT' 
        WHEN ([DESCRIPTION] LIKE ('%CREDIT%')) AND TOTALCOST < 0 THEN 'CREDIT' 
        WHEN TOTALCOST < 0 THEN 'CREDIT' 
    END AS [TYPE]
    , CAST(CUST_ORDER_ID AS VARCHAR) AS CUST_ORDER
    , LINE_NO
    , COLINE
    , CAST(CUST_PO AS VARCHAR) AS CUST_PO
    , CASE
        WHEN CUSTID = 'BOE609' THEN 'CMP'
        ELSE 'OTHER'
    END AS CMP
    , PART_ID
    , [DESCRIPTION]
    , SHIPPEDQTY
    , BASE_ID
    , LOT_ID
    , CAST(SHIPDATE AS DATE) AS [SHIP DATE]
    , CAST(DUEDATE AS DATE) AS [DUE DATE]
    , CASE
        WHEN SHIPDATE > DUEDATE THEN 'NO'
        ELSE 'YES'
    END AS [ON TIME]
    , CASE
        WHEN DATEDIFF(D, ORDERDATE, CREATESHIPDATE) - (DATEDIFF(WK, ORDERDATE, CREATESHIPDATE) 
            + CASE 
                WHEN DATEPART(DW, ORDERDATE) = 1 THEN 1 
                ELSE 0 
            END) - (DATEDIFF(WK, ORDERDATE, CREATESHIPDATE) 
            + CASE 
                WHEN DATEPART(DW, CREATESHIPDATE)=7 THEN 1 
                ELSE 0 
            END) < 1 THEN 1
        ELSE DATEDIFF(D, ORDERDATE, CREATESHIPDATE) - (DATEDIFF(WK, ORDERDATE, CREATESHIPDATE) 
            + CASE 
                WHEN DATEPART(DW, ORDERDATE) = 1 THEN 1 
                ELSE 0 
            END) - (DATEDIFF(WK, ORDERDATE, CREATESHIPDATE) 
            + CASE 
                WHEN DATEPART(DW, CREATESHIPDATE)=7 THEN 1 
                ELSE 0 
            END)
    END AS [TURN-WKDYS]
FROM (SELECT  C.ID AS CUSTID
        , COL.CUST_ORDER_ID
        , COL.LINE_NO
        , CAST(COL.CUST_ORDER_ID AS VARCHAR) + '/' + CAST(COL.LINE_NO AS VARCHAR) AS COLINE
        , CO.CUSTOMER_PO_REF AS CUST_PO
        , ISNULL(COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) AS DUEDATE
        , COL.PART_ID
        , LTRIM(RTRIM(ISNULL(COL.MISC_REFERENCE,''))) AS [DESCRIPTION]
        , SUM(SL.SHIPPED_QTY * COL.UNIT_PRICE) AS TOTALCOST
        , MAX(CO.ORDER_DATE) AS ORDERDATE
        , MAX(S.CREATE_DATE) AS CREATESHIPDATE
        , MAX(S.SHIPPED_DATE) AS SHIPDATE
        , SUM(SL.SHIPPED_QTY) AS SHIPPEDQTY
        , ISNULL(W.BASE_ID,MAX(WO2.BASE_ID)) AS BASE_ID
        , ISNULL(W.LOT_ID,MAX(WO2.LOT_ID)) AS LOT_ID
    FROM CUSTOMER C
    INNER JOIN CUSTOMER_ORDER CO 
        ON C.ID = CO.CUSTOMER_ID
    LEFT OUTER JOIN CUST_ORDER_LINE COL 
        ON CO.ID = COL.CUST_ORDER_ID
    LEFT OUTER JOIN DEMAND_SUPPLY_LINK AS DSL 
        ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID 
        AND COL.LINE_NO = DSL.DEMAND_SEQ_NO 
        AND DSL.DEMAND_TYPE = 'CO' 
    LEFT OUTER JOIN WORK_ORDER W 
        ON DSL.SUPPLY_BASE_ID = W.BASE_ID 
        AND DSL.SUPPLY_LOT_ID = W.LOT_ID 
        AND DSL.SUPPLY_SPLIT_ID = W.SPLIT_ID 
        AND DSL.SUPPLY_SUB_ID = W.SUB_ID 
        AND DSL.SUPPLY_TYPE IN ('WO', 'CP') 
    LEFT OUTER JOIN SHIPPER_LINE SL 
        ON  COL.CUST_ORDER_ID = SL.CUST_ORDER_ID
        AND COL.LINE_NO = SL.CUST_ORDER_LINE_NO 
    LEFT OUTER JOIN SHIPPER S
        ON SL.PACKLIST_ID = S.PACKLIST_ID
    LEFT OUTER JOIN TRACE_INV_TRANS T 
        ON SL.TRANSACTION_ID = T.TRANSACTION_ID
    LEFT OUTER JOIN WORK_ORDER AS WO2 
        ON T.TRACE_ID = WO2.BASE_ID + '/' + WO2.LOT_ID + '/' + CAST(WO2.SPLIT_ID AS VARCHAR)
    WHERE COL.PART_ID NOT LIKE 'UP%' 
        AND C.USER_9 NOT LIKE 'O%' 
        AND SL.SHIPPED_QTY != 0 
        AND (S.SHIPPED_DATE >= @STARTDATE
        AND S.SHIPPED_DATE <= @ENDDATE)
    GROUP BY C.ID
        , COL.CUST_ORDER_ID
        , COL.LINE_NO
        , CAST(COL.CUST_ORDER_ID AS VARCHAR) + '/' + CAST(COL.LINE_NO AS VARCHAR)
        , CO.CUSTOMER_PO_REF
        , ISNULL(COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE)
        , COL.PART_ID
        , LTRIM(RTRIM(ISNULL(COL.MISC_REFERENCE,'')))
        , W.BASE_ID
        , W.LOT_ID
    ) A
) BASE
LEFT OUTER JOIN OPERATION O 
    ON O.WORKORDER_TYPE = 'W' 
    AND BASE.BASE_ID = O.WORKORDER_BASE_ID 
    AND BASE.LOT_ID = O.WORKORDER_LOT_ID 
    AND O.WORKORDER_SPLIT_ID = '0' 
    AND O.WORKORDER_SUB_ID = '0' 
LEFT OUTER JOIN SHOP_RESOURCE SR 
    ON O.RESOURCE_ID = SR.ID

SELECT COUNTS.*
    , CASE 
        WHEN MCOUNT >= 1 AND ACOUNT >= 4 AND BCOUNT >= 4 THEN 'MAB' 
        WHEN MCOUNT >= 1 AND ACOUNT >= 3 THEN 'MA'
        WHEN MCOUNT >= 1 AND BCOUNT >= 3 THEN 'MB'
        WHEN MCOUNT >= 1 AND ACOUNT <= 3 AND BCOUNT <= 3 THEN 'M'
        WHEN ACOUNT >= 4 AND BCOUNT >= 4 THEN 'AB'
        WHEN MCOUNT >= 1 THEN 'M'
        WHEN ACOUNT >= 1 THEN 'A'
        WHEN BCOUNT >= 1 THEN 'B'
        WHEN OCOUNT >= 1 THEN 'O' 
    END AS DIV
    , CASE 
        WHEN MCOUNT >= 1 AND ACOUNT >= 4 AND BCOUNT >= 4 THEN 'MFG & AUBURN NORTH & BALLARD' 
        WHEN MCOUNT >= 1 AND ACOUNT >= 3 THEN 'MFG & AUBURN NORTH'
        WHEN MCOUNT >= 1 AND BCOUNT >= 3 THEN 'MFG & BALLARD'
        WHEN MCOUNT >= 1 AND ACOUNT <= 3 AND BCOUNT <= 3 THEN 'MFG'
        WHEN ACOUNT >= 4 AND BCOUNT >= 4 THEN 'AUBURN NORTH & BALLARD'
        WHEN MCOUNT >= 1 THEN 'MFG'
        WHEN ACOUNT >= 1 THEN 'AUBURN NORTH'
        WHEN BCOUNT >= 1 THEN 'BALLARD'
        WHEN OCOUNT >= 1 THEN 'OUTREACH' 
    END AS DIVISION
    , CASE
        WHEN CUSTID = 'BOE609' AND PMCOUNT = 0  THEN 'W/S'
        ELSE ''
    END AS WS
FROM (SELECT CUSTID
        , [TYPE]
        , CUST_ORDER
        , LINE_NO
        , COLINE 
        , CUST_PO
        , CMP
        , PART_ID
        , [DESCRIPTION]
        , SHIPPEDQTY
        , BASE_ID
        , [SHIP DATE]
        , [DUE DATE] 
        , [ON TIME] 
        , [TURN-WKDYS]
        , (SELECT SUM(PMCOUNT) FROM #T1 PM WHERE PM.BASE_ID = T1.BASE_ID) AS PMCOUNT
        , (SELECT SUM(DIVCOUNT) FROM #T1 A  WHERE SKILLS_TYPE1 = 'A'  AND  A.BASE_ID = T1.BASE_ID) AS ACOUNT
        , (SELECT SUM(DIVCOUNT) FROM #T1 B  WHERE SKILLS_TYPE1 = 'B'  AND  B.BASE_ID = T1.BASE_ID) AS BCOUNT
        , (SELECT SUM(DIVCOUNT) FROM #T1 M  WHERE SKILLS_TYPE1 = 'M'  AND  M.BASE_ID = T1.BASE_ID) AS MCOUNT
        , (SELECT SUM(DIVCOUNT) FROM #T1 O  WHERE SKILLS_TYPE1 = 'O'  AND  O.BASE_ID = T1.BASE_ID) AS OCOUNT
        , (SELECT SUM(DIVCOUNT) FROM #T1 OS WHERE SKILLS_TYPE1 = 'OS' AND OS.BASE_ID = T1.BASE_ID) AS OSCOUNT
    FROM #T1 T1
    GROUP BY CUSTID
        , [TYPE]
        , CUST_ORDER
        , LINE_NO
        , COLINE 
        , CUST_PO
        , CMP
        , PART_ID
        , [DESCRIPTION]
        , SHIPPEDQTY
        , BASE_ID
        , [SHIP DATE]
        , [DUE DATE] 
        , [ON TIME] 
        , [TURN-WKDYS]
    ) COUNTS
WHERE ([SHIP DATE] >= @STARTDATE AND [SHIP DATE] <= @ENDDATE) 
    AND CASE 
        WHEN MCOUNT >= 1 AND ACOUNT >= 4 AND BCOUNT >= 4 THEN 'MAB' 
        WHEN MCOUNT >= 1 AND ACOUNT >= 3 THEN 'MA'
        WHEN MCOUNT >= 1 AND BCOUNT >= 3 THEN 'MB'
        WHEN MCOUNT >= 1 AND ACOUNT <= 3 AND BCOUNT <= 3 THEN 'M'
        WHEN ACOUNT >= 4 AND BCOUNT >= 4 THEN 'AB'
        WHEN MCOUNT >= 1 THEN 'M'
        WHEN ACOUNT >= 1 THEN 'A'
        WHEN BCOUNT >= 1 THEN 'B'
        WHEN OCOUNT >= 1 THEN 'O' 
    END IN (@DIV) 
    AND CUSTID IN (@CUSTID)
