SELECT ROW_NUMBER() OVER (order by TRANSACTION_ID) as 'Row', CREATE_DATE, TRANSACTION_ID, TRANSACTION_DATE, CLOCK_IN, CLOCK_OUT
    , EMPLOYEE_ID, FIRST_NAME, LAST_NAME, RESOURCE_ID, [DESCRIPTION], HOURS_WORKED
    , CASE
        WHEN CAST(CLOCK_IN AS TIME) >= '11:15:00' AND CAST(CLOCK_IN AS TIME) < '11:45:00' THEN 'CLOCK IN DURING LUNCH'
        WHEN CAST(CLOCK_OUT AS TIME) >= '11:15:00' AND CAST(CLOCK_OUT AS TIME) < '11:45:00' THEN 'CLOCK IN DURING LUNCH'
        ELSE NULL
    END AS NOTES
FROM LABOR_TICKET LT WITH (NOLOCK)
LEFT OUTER JOIN EMPLOYEE EE WITH (NOLOCK) ON EE.ID = LT.EMPLOYEE_ID
WHERE TRANSACTION_DATE > DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0) AND HOURS_WORKED < 0 and TRANSACTION_DATE >= @date 
ORDER BY TRANSACTION_DATE ASC
