Select
CO.ID
,CO.CUSTOMER_ID
,CO.CREATE_DATE
,O.WORKORDER_BASE_ID
,O.RESOURCE_ID
,O.OPERATION_TYPE

from OPERATION O
       Left Outer Join DEMAND_SUPPLY_LINK DSL
              on DSL.SUPPLY_BASE_ID = o.WORKORDER_BASE_ID
              and DSL.SUPPLY_LOT_ID = O.WORKORDER_LOT_ID
              and DSL.SUPPLY_SPLIT_ID = O.WORKORDER_SPLIT_ID
              and DSL.SUPPLY_SUB_ID = O.WORKORDER_SUB_ID
       Left Outer Join CUST_ORDER_LINE COL
              on COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
              and COl.LINE_NO = DSL.DEMAND_SEQ_NO
       left Outer Join Customer_order CO
              on CO.ID = COl.CUST_ORDER_ID

where
O.OPERATION_TYPE in ('30907-PS20722', '31408-PS20722', '8625-1C PS20722')
and O.WORKORDER_TYPE = 'W'
and CO.CREATE_DATE > Getdate()-7

Order by CO.CREATE_DATE
