	-- FROM cte_currentoperation w
	-- LEFT JOIN cte_labortickets l ON w.BASE_ID = l.WORKORDER_BASE_ID
	-- 	AND w.LOT_ID = l.WORKORDER_LOT_ID AND w.SPLIT_ID = l.WORKORDER_SPLIT_ID
	-- 	AND w.SUB_ID = l.WORKORDER_SUB_ID AND w.[TYPE] = l.WORKORDER_TYPE
	-- --> TT20210727: add last closed date
	-- LEFT JOIN CTE_LASTOPCLOSED LO ON W.BASE_ID = LO.WORKORDER_BASE_ID
	-- 	AND W.LOT_ID = LO.WORKORDER_LOT_ID AND W.SPLIT_ID = LO.WORKORDER_SPLIT_ID
	-- 	AND W.SUB_ID = LO.WORKORDER_SUB_ID AND W.[TYPE] = LO.WORKORDER_TYPE
	-- LEFT JOIN EMPLOYEE e ON e.ID = l.EMPLOYEE_ID
	-- LEFT JOIN SHOP_RESOURCE_SITE_VIEW SR ON SR.RESOURCE_ID = w.RESOURCE_ID_Raw
	-- --> tt20190424
	-- LEFT OUTER JOIN EMPLOYEE EE ON LTRIM(RTRIM(sr.USER_4)) = EE.[FIRST_NAME] + ' ' + EE.[LAST_NAME]
	-- 	AND EE.ACTIVE = 'Y'
	-- LEFT JOIN LIVESupplemental.dbo.buyer_assn b ON LEFT(w.BUYER_USER_ID,2) = b.Account_ID

  select * from 
    [LIVESupplemental].[dbo].[buyer_assn] -- table on SQL-BI-1