SELECT COUNT(*) AS COUNTS
FROM LABOR_TICKET LT
INNER JOIN SHOP_RESOURCE_SITE SRS
    ON SRS.RESOURCE_ID = LT.RESOURCE_ID
WHERE LT.TRANSACTION_DATE >= '1/27/2022'	 
    AND LT.WORKORDER_TYPE = 'W'		
    AND LT.ACT_LABOR_COST > 0		
    AND (LT.ACT_BURDEN_COST - CAST((LT.HOURLY_COST * LT.HOURS_WORKED * 
	  (CASE
		 WHEN LT.[TYPE] = 'S' THEN SRS.BUR_PERCENT_SETUP
		 WHEN LT.[TYPE] = 'R' THEN SRS.BUR_PERCENT_RUN
	  END) / 100) AS DECIMAL (10,2)) > 0.01
	OR LT.ACT_BURDEN_COST - CAST((LT.HOURLY_COST * LT.HOURS_WORKED * 
	  (CASE
		 WHEN LT.[TYPE] = 'S' THEN SRS.BUR_PERCENT_SETUP
		 WHEN LT.[TYPE] = 'R' THEN SRS.BUR_PERCENT_RUN
	  END) / 100) AS DECIMAL (10,2)) < -(0.01)
	 )
