-- VISUAL ENTERPRISE > SHIPPING REPORTS > FGA Ship List
SELECT CASE WHEN CL.ORDER_QTY - CL.TOTAL_SHIPPED_QTY <= ISNULL(
            (SELECT SUM(QTY)AS SHIP_QTY FROM PART_LOCATION pl WITH (NOLOCK) WHERE pl.PART_ID = P.PART_ID AND STATUS = 'A'),0) THEN 1 
        ELSE 2 
    END AS SORT
    --> checking to see if qty on hand is available to fulfill the order
    , CASE 
        WHEN CA.ADDR_2 LIKE '%HOLD%'  THEN 6
        WHEN CA.CITY LIKE '%HOLD%' THEN 6
        WHEN CA.CITY LIKE '%RENTON%' AND CASE WHEN CL.DESIRED_SHIP_DATE < GETDATE() THEN DATEDIFF(DAY,GETDATE(), CL.DESIRED_SHIP_DATE)
            ELSE DATEDIFF(DAY,GETDATE(), CL.DESIRED_SHIP_DATE)
            END >= 5 THEN 5
        WHEN CA.CITY LIKE '%EVERETT%' AND CASE 
            WHEN CL.DESIRED_SHIP_DATE < GETDATE() THEN DATEDIFF(DAY,GETDATE(), CL.DESIRED_SHIP_DATE)
            ELSE DATEDIFF(DAY,GETDATE(), CL.DESIRED_SHIP_DATE)
            END >= 7 THEN 4
        WHEN CO.CUSTOMER_ID NOT LIKE 'BOE%' AND CASE 
            WHEN CL.DESIRED_SHIP_DATE < GETDATE() THEN DATEDIFF(DAY,GETDATE(), CL.DESIRED_SHIP_DATE)
            ELSE DATEDIFF(DAY,GETDATE(), CL.DESIRED_SHIP_DATE)
            END >= 7 
                THEN 3
        WHEN CA.STATE NOT LIKE 'WA%' AND 
            CASE 
                WHEN CL.DESIRED_SHIP_DATE < GETDATE() THEN DATEDIFF(DAY,GETDATE(), CL.DESIRED_SHIP_DATE)
                ELSE DATEDIFF(DAY,GETDATE(), CL.DESIRED_SHIP_DATE)
                END >= 5 
                    THEN 2
        WHEN TOTAL_SHIPPED_QTY + P.QTY_ON_HAND >= ORDER_QTY THEN 0
        ELSE 1
    END AS SORT2
    --> 0 => qty on hand is enouch to fulfill order
    --> 1 => fall thru, none of other criteria apply
    --> 2 => not in WA, shipdate >= 5 days 
    --> 3 => not BOE, shipdate >= 7 days
    --> 4 => shipping to Everett, 7 days
    --> 5 => shipping to Renton, 5 days
    --> 6 => addr is "HOLD"
    , CO.ID + '/' + CONVERT(VARCHAR(3), CL.LINE_NO) AS 'CUSTIDLINE', CO.CUSTOMER_ID
    , CASE 
        WHEN CA.ADDR_2 LIKE '%HOLD%' THEN 'HOLD'
        WHEN CA.CITY LIKE '%HOLD%' THEN 'HOLD' 
        WHEN CA.STATE IS NULL  AND CA.COUNTRY <> 'USA'  THEN CA.COUNTRY
        ELSE CA.CITY +', ' + CA.STATE              
    END AS CO_OR_STATE
    , CL.PART_ID, CL.USER_6, CL.ORDER_QTY
    , CASE 
        WHEN CL.DESIRED_SHIP_DATE < GETDATE() THEN DATEDIFF(DAY, GETDATE(), CL.DESIRED_SHIP_DATE)
        ELSE DATEDIFF(DAY,GETDATE(), CL.DESIRED_SHIP_DATE)
    END AS DAYS
    , CL.DESIRED_SHIP_DATE, CL.TOTAL_SHIPPED_QTY, CO.[STATUS], P.PLANNER_USER_ID
    , V.LOCATIONS AS PART_LOC, P.QTY_ON_ORDER AS QTY, CL.ORDER_QTY - CL.TOTAL_SHIPPED_QTY AS 'QTY_DUE'
    , ISNULL((SELECT SUM(QTY) AS SHIP_QTY FROM PART_LOCATION pl WITH (NOLOCK) WHERE pl.PART_ID = P.PART_ID AND STATUS = 'A'),0) AS 'SHIP_QTY'
    , CL.LINE_STATUS, CO.CUSTOMER_PO_REF, 'N' AS IBT--, V.LOC_NO
FROM CUST_ORDER_LINE CL WITH (NOLOCK)
INNER JOIN CUSTOMER_ORDER AS CO WITH (NOLOCK)
    ON CL.CUST_ORDER_ID = CO.ID
    AND CO.STATUS = 'R'
LEFT OUTER JOIN CUST_ADDRESS CA
    ON CA.CUSTOMER_ID = CO.CUSTOMER_ID
    AND CA.ADDR_NO = CO.SHIP_TO_ADDR_NO
INNER JOIN PART_SITE_VIEW P WITH (NOLOCK) ON CL.PART_ID=P.PART_ID
    AND EXISTS
        (SELECT 1
        FROM LIVESupplemental.dbo.PLANNER_USER_ID_ReportSettings EX WITH (NOLOCK)
        WHERE P.PLANNER_USER_ID = EX.PLANNER_USER_ID
            AND REPORT_NAME = 'FGA Ship List'
        )
LEFT OUTER JOIN SKILLS_PART_LOC_LIST2 V WITH (NOLOCK) ON P.PART_ID = V.ID
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL WITH (NOLOCK) ON CL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
    AND CL.LINE_NO = DSL.DEMAND_SEQ_NO
LEFT OUTER JOIN [SQL-LAB-2].LIVE.dbo.WAREHOUSE WHS (nolock) ON CL.WAREHOUSE_ID = WHS.ID 

WHERE P.SITE_ID = 'SK01' AND CL.ORDER_QTY > CL.TOTAL_SHIPPED_QTY
    AND CO.CUSTOMER_ID NOT IN ('BOE609', 'BOE614')
    AND CL.LINE_STATUS NOT IN ('C') AND CL.PART_ID NOT LIKE 'K12%'
    AND CL.PART_ID NOT LIKE '%FAI'
    AND CASE 
        WHEN CL.DESIRED_SHIP_DATE < GETDATE() THEN DATEDIFF(DAY,GETDATE(), CL.DESIRED_SHIP_DATE)
        ELSE DATEDIFF(DAY,GETDATE(), CL.DESIRED_SHIP_DATE)
    END  <= @DAYS
    AND DSL.SUPPLY_BASE_ID IS NULL
    AND ((CL.USER_6 NOT LIKE ('CBO%') AND CL.USER_6 NOT LIKE ('VOI%') 
        AND CL.USER_6 NOT LIKE ('KIT%')) OR CL.USER_6 IS NULL)
    --AND V.LOCATIONS IS NOT NULL
UNION ALL 
SELECT CASE 
        WHEN IL.ORDER_QTY - IL.SHIPPED_QTY <= ISNULL(
            (SELECT SUM(QTY)AS SHIP_QTY FROM PART_LOCATION pl WITH (NOLOCK) WHERE pl.PART_ID = P.PART_ID AND STATUS = 'A'),0) THEN 1 
        ELSE 2 
    END AS SORT
    --> checking to see if qty on hand is available to fulfill the order
    , CASE 
        WHEN IL.SHIPPED_QTY + P.QTY_ON_HAND >= IL.ORDER_QTY THEN 0
        ELSE 1
    END AS SORT2
    , I.ID + '/' + CONVERT(VARCHAR(3), IL.LINE_NO) AS IBTLINE, WHS.CUSTOMER_ID
    , WHS.CITY +', ' + WHS.STATE, IL.PART_ID, 'M/M' AS USER_6, IL.ORDER_QTY
    , CASE 
        WHEN I.DESIRED_SHIP_DATE < GETDATE() THEN DATEDIFF(DAY, GETDATE(), I.DESIRED_SHIP_DATE)
        ELSE DATEDIFF(DAY,GETDATE(), I.DESIRED_SHIP_DATE)
    END AS DAYS
    , I.DESIRED_SHIP_DATE, IL.SHIPPED_QTY, I.[STATUS], P.PLANNER_USER_ID
    , V.LOCATIONS AS PART_LOC, P.QTY_ON_ORDER AS QTY, IL.ORDER_QTY - IL.SHIPPED_QTY AS QTY_DUE
    , ISNULL((SELECT SUM(QTY) AS SHIP_QTY FROM PART_LOCATION pl WITH (NOLOCK) WHERE pl.PART_ID = P.PART_ID AND STATUS = 'A'),0) AS SHIP_QTY
    , IL.LINE_STATUS
    , ISNULL(CO.CUSTOMER_PO_REF,'Consignment') AS CUSTOMER_PO_REF
    , 'Y' AS IBT--, V.LOC_NO

FROM [SQL-LAB-2].LIVE.dbo.IBT_LINE IL (NOLOCK) JOIN [SQL-LAB-2].LIVE.dbo.IBT I (NOLOCK) ON IL.IBT_ID = I.ID
INNER JOIN PART_SITE_VIEW P  WITH (NOLOCK) ON IL.PART_ID = P.PART_ID
    AND EXISTS
        (SELECT 1 FROM LIVESupplemental.dbo.PLANNER_USER_ID_ReportSettings EX WITH (NOLOCK)
            WHERE P.PLANNER_USER_ID = EX.PLANNER_USER_ID AND REPORT_NAME = 'FGA Ship List'
        )
LEFT OUTER JOIN SKILLS_PART_LOC_LIST2 V WITH (NOLOCK) ON P.PART_ID = V.ID
JOIN [SQL-LAB-2].LIVE.dbo.WAREHOUSE WHS WITH (NOLOCK) ON I.TO_WHSE_ID = WHS.ID AND WHS.CONSIGNED_TYPE = 'C'
LEFT OUTER JOIN CUSTOMER_ORDER CO WITH (NOLOCK) ON ISNULL(IL.TO_CUST_ORDER_ID,IL.FROM_CUST_ORDER_ID) = CO.ID 
WHERE IL.ORDER_QTY > IL.SHIPPED_QTY --AND V.LOCATIONS IS NOT NULL
