--Visual Enterprise Reports/Purchasing Reports/Open Purchase Orders Past Due
--DECLARE @BUYER AS NVARCHAR (20)
--SET @BUYER = 'JEREMYS'

SELECT PO.ID, 
        PO.VENDOR_ID, 
        PO.ORDER_DATE, 
       ISNULL(PL.DESIRED_RECV_DATE, PO.DESIRED_RECV_DATE) AS DUEDATE,
       ISNULL(PL.PROMISE_SHIP_DATE, PO.PROMISE_SHIP_DATE) AS RECOMMITTEDDATE,
       DATEDIFF(DAY, ISNULL(PL.DESIRED_RECV_DATE, PO.DESIRED_RECV_DATE), ISNULL(PL.PROMISE_SHIP_DATE, PO.PROMISE_SHIP_DATE)) AS DAYSDIFF, 
        --CASE WHEN PL.DESIRED_RECV_DATE IS NULL
        --     THEN PO.DESIRED_RECV_DATE
        --     ELSE PL.DESIRED_RECV_DATE END AS DUEDATE,
        PO.DESIRED_RECV_DATE, 
        PL.LINE_NO, 
        PL.PART_ID, 
        PL.VENDOR_PART_ID,
        PO.STATUS, 
        PL.LINE_STATUS, 
        PL.ORDER_QTY,
        PL.USER_ORDER_QTY, 
        PL.TOTAL_RECEIVED_QTY,
        PL.USER_ORDER_QTY-PL.TOTAL_USR_RECD_QTY   AS QTYDUE,
        PL.UNIT_PRICE,
       (PL.USER_ORDER_QTY-PL.TOTAL_USR_RECD_QTY)* PL.UNIT_PRICE AS LINETOTAL,
        CASE WHEN PL.VENDOR_PART_ID IS NOT NULL THEN 
             CASE WHEN PL.USER_1 IS NULL THEN PL.VENDOR_PART_ID
             ELSE PL.VENDOR_PART_ID  + ': ' + PL.USER_1 
              END END AS DESCRIPTION,
        PO.BUYER
   FROM LIVE.dbo.PURC_ORDER_LINE pl 
  INNER JOIN LIVE.dbo.PURCHASE_ORDER PO 
     ON PL.PURC_ORDER_ID=PO.ID
  LEFT OUTER JOIN LIVE.DBO.PART P
     ON PL.PART_ID = P.ID
   left outer join dbo.PART_UNITS_CONV u
    on pL.PART_id = u.PART_ID 
   AND PL.PURCHASE_UM = FROM_UM
  WHERE PL.LINE_STATUS='A' 
    AND ISNULL(PL.DESIRED_RECV_DATE, PO.DESIRED_RECV_DATE) <= GETDATE()-1 
   AND NOT (PO.STATUS='C' OR PO.STATUS='X')
   AND PL.ORDER_QTY-PL.TOTAL_RECEIVED_QTY > 0
  and po.buyer in (@buyer)
ORDER BY PO.BUYER,
         PO.VENDOR_ID,  
         PO.ID,  
         PL.LINE_NO
