--declare @PO varchar(24) = '163772'
; WITH CTEBASE AS 
(SELECT PL.PURC_ORDER_ID AS POID
    , PL.LINE_NO AS POLN
    , PL.PART_ID AS PARTID
    , PL.SERVICE_ID AS SERVICEID
    , COALESCE(P.DESCRIPTION,PL.USER_1) AS DESCRIPTION
    , S.DESCRIPTION AS SERV_DESC
    , CAST(CAST(CAST(PLB.BITS AS VARBINARY(4000)) AS NVARCHAR(4000)) AS VARCHAR(4000)) AS EXTDESCRIPTION
    , PL.VENDOR_PART_ID AS VENDORPN
    , PL.MFG_NAME AS MFGNAME
    , PL.MFG_PART_ID AS MFGPARTID
    , WO.BASE_ID + '/' + WO.LOT_ID + CASE WHEN WO.SPLIT_ID = '0' THEN '' ELSE '.' + CAST(WO.SPLIT_ID AS VARCHAR) END AS JOBID
    , WO.DESIRED_WANT_DATE AS JOBWANTDATE
    , DSL.DEMAND_SEQ_NO AS OPNO
    , DSL.DEMAND_SUB_ID AS OPSUB
    , (SELECT TOP 1 SO.COMPLETED_QTY FROM OPERATION SO (NOLOCK) JOIN SHOP_RESOURCE SR (NOLOCK) ON SO.RESOURCE_ID = SR.ID AND CHARINDEX('RECEIVING',SR.DESCRIPTION) = 0 
        WHERE SO.WORKORDER_TYPE = WO.TYPE AND SO.WORKORDER_BASE_ID = DSL.DEMAND_BASE_ID 
        AND SO.WORKORDER_LOT_ID = DSL.DEMAND_LOT_ID AND SO.WORKORDER_SPLIT_ID = DSL.DEMAND_SPLIT_ID AND SO.WORKORDER_SUB_ID = DSL.DEMAND_SUB_ID 
        AND SO.SEQUENCE_NO > DSL.DEMAND_SEQ_NO ORDER BY SO.SEQUENCE_NO) 
    AS NEXTOPQTY
    , (SELECT TOP 1 SO.STATUS FROM OPERATION SO (NOLOCK) JOIN SHOP_RESOURCE SR (NOLOCK) ON SO.RESOURCE_ID = SR.ID AND CHARINDEX('RECEIVING',SR.DESCRIPTION) = 0 
        WHERE SO.WORKORDER_TYPE = WO.TYPE AND SO.WORKORDER_BASE_ID = DSL.DEMAND_BASE_ID 
        AND SO.WORKORDER_LOT_ID = DSL.DEMAND_LOT_ID AND SO.WORKORDER_SPLIT_ID = DSL.DEMAND_SPLIT_ID AND SO.WORKORDER_SUB_ID = DSL.DEMAND_SUB_ID 
        AND SO.SEQUENCE_NO > DSL.DEMAND_SEQ_NO ORDER BY SO.SEQUENCE_NO) 
    AS NEXTOPSTATUS
    , (SELECT TOP 1 SR.DESCRIPTION FROM OPERATION SO (NOLOCK) JOIN SHOP_RESOURCE SR (NOLOCK) ON SO.RESOURCE_ID = SR.ID AND CHARINDEX('RECEIVING',SR.DESCRIPTION) = 0 
        WHERE SO.WORKORDER_TYPE = WO.TYPE AND SO.WORKORDER_BASE_ID = DSL.DEMAND_BASE_ID 
        AND SO.WORKORDER_LOT_ID = DSL.DEMAND_LOT_ID AND SO.WORKORDER_SPLIT_ID = DSL.DEMAND_SPLIT_ID AND SO.WORKORDER_SUB_ID = DSL.DEMAND_SUB_ID 
        AND SO.SEQUENCE_NO > DSL.DEMAND_SEQ_NO ORDER BY SO.SEQUENCE_NO) 
    AS NEXTOPRESDESC
    , CASE WHEN DSL.DEMAND_NO = 0 THEN NULL ELSE DEMAND_NO END AS PCNO
    , R.RECEIVED_DATE AS RECVRDATE
    , RL.RECEIVER_ID AS RECVRID
    , RL.LINE_NO AS RECVRLINE
    , RL.USER_RECEIVED_QTY 
    , PL.GL_EXPENSE_ACCT_ID + ' (' + A.DESCRIPTION + ')' AS GL_EXPENSE_ACCT_ID
    , RL.INSPECT_QTY
    , (RL.UNIT_PRICE * RL.USER_RECEIVED_QTY) + RL.FIXED_CHARGE AS RECVAMOUNT
    , CASE WHEN (PL.UNIT_PRICE * RL.USER_RECEIVED_QTY) + PL.FIXED_CHARGE < PL.MINIMUM_CHARGE
           THEN PL.MINIMUM_CHARGE
           ELSE (PL.UNIT_PRICE * RL.USER_RECEIVED_QTY) + PL.FIXED_CHARGE
    END AS PORCVAMOUNT
    , PO.VENDOR_ID AS VENDORID
    , V.NAME AS VENDORNAME
    , APL.VOUCHER_ID AS VOUCHERID
    , AP.INVOICE_ID AS INVOICEID
    , AP.INVOICE_DATE AS INVOICEDATE 
    , CD.CHECK_NO AS CHECKNO
    , CD.CHECK_DATE AS CHECKDATE
    , CDL.AMOUNT AS VOUCHERPAIDAMT
    , CD.AMOUNT AS CHECKAMOUNT
    --, CASE WHEN ISNULL(PR.STATUS,'-') IN ('O','V') THEN 'Y' ELSE 'N' END AS RFQAPPROVED
    , PR.ID PURCREQID
FROM PURC_ORDER_LINE PL (NOLOCK)
JOIN PURCHASE_ORDER PO (NOLOCK) 
    ON PL.PURC_ORDER_ID = PO.ID 
JOIN VENDOR V (NOLOCK) 
    ON PO.VENDOR_ID = V.ID 
LEFT JOIN PART P (NOLOCK) 
    ON PL.PART_ID = P.ID 
LEFT JOIN SERVICE S (NOLOCK) 
    ON PL.SERVICE_ID = S.ID 
LEFT JOIN PURC_LINE_BINARY PLB (NOLOCK) 
    ON PL.PURC_ORDER_ID = PLB.PURC_ORDER_ID 
    AND PL.LINE_NO = PLB.PURC_ORDER_LINE_NO 
LEFT JOIN DEMAND_SUPPLY_LINK (NOLOCK) DSL 
    ON PL.PURC_ORDER_ID = DSL.SUPPLY_BASE_ID 
    AND PL.LINE_NO = DSL.SUPPLY_SEQ_NO 
    AND DSL.SUPPLY_TYPE = 'PO' 
    AND DSL.DEMAND_TYPE IN ('OP','RQ')
LEFT JOIN WORK_ORDER (NOLOCK) WO 
    ON DSL.DEMAND_BASE_ID = WO.BASE_ID 
    AND DSL.DEMAND_LOT_ID = WO.LOT_ID 
    AND DSL.DEMAND_SPLIT_ID = WO.SPLIT_ID 
    AND WO.SUB_ID = 0 
    AND WO.TYPE = 'W'
LEFT JOIN RECEIVER_LINE RL (NOLOCK) 
    ON PL.PURC_ORDER_ID = RL.PURC_ORDER_ID 
    AND PL.LINE_NO = RL.PURC_ORDER_LINE_NO
LEFT JOIN INVENTORY_TRANS IT (NOLOCK) 
    ON RL.TRANSACTION_ID = IT.TRANSACTION_ID 
LEFT JOIN SERVICE_RECEIPT SR (NOLOCK) 
    ON RL.SERV_TRANS_ID = SR.TRANSACTION_ID 
LEFT JOIN RECEIVER R (NOLOCK) 
    ON RL.RECEIVER_ID = R.ID
LEFT JOIN ACCOUNT A (NOLOCK) 
    ON PL.GL_EXPENSE_ACCT_ID = A.ID 
LEFT JOIN PAYABLE_LINE APL (NOLOCK) 
    ON RL.RECEIVER_ID = APL.RECEIVER_ID 
    AND RL.LINE_NO = APL.RECEIVER_LINE_NO        
LEFT JOIN PAYABLE AP (NOLOCK) 
    ON APL.VOUCHER_ID = AP.VOUCHER_ID 
LEFT JOIN CASH_DISBURSE_LINE CDL (NOLOCK) 
    ON APL.VOUCHER_ID = CDL.VOUCHER_ID 
LEFT JOIN CASH_DISBURSEMENT CD (NOLOCK) 
    ON CDL.BANK_ACCOUNT_ID = CD.BANK_ACCOUNT_ID 
    AND CDL.CONTROL_NO = CD.CONTROL_NO 
LEFT JOIN PURC_ORDER_REQ PRL (NOLOCK) 
    ON PL.PURC_ORDER_ID = PRL.PURC_ORD_ID 
    AND PL.LINE_NO = PRL.PURC_ORD_LINE_NO 
LEFT JOIN PURC_REQUISITION PR (NOLOCK) 
    ON PRL.PURC_REQ_ID = PR.ID 
WHERE PL.PURC_ORDER_ID = @PO 
)

, CTETASK AS 
(SELECT T.EC_ID
    , @PO AS PURC_ORD_ID 
    , CASE WHEN T.SUB_TYPE = 'A2' THEN 1 ELSE 0 END AS APPV
    , CASE WHEN T.SUB_TYPE = 'A2' AND T.COMPLETED_DATE IS NOT NULL THEN 1 ELSE 0 END AS APPVCOMP
    , CASE WHEN T.SUB_TYPE = 'A3' THEN 1 ELSE 0 END AS APPVEL1 
    , CASE WHEN T.SUB_TYPE = 'A3' AND T.COMPLETED_DATE IS NOT NULL THEN 1 ELSE 0 END AS APPVEL1COMP
    , CASE WHEN T.SUB_TYPE = 'A4' THEN 1 ELSE 0 END AS APPVEL2
    , CASE WHEN T.SUB_TYPE = 'A4' AND T.COMPLETED_DATE IS NOT NULL THEN 1 ELSE 0 END AS APPVEL2COMP
FROM TASK T 
JOIN (SELECT DISTINCT PURC_REQ_ID FROM PURC_ORDER_REQ WHERE PURC_ORD_ID = @PO) L ON T.EC_ID = L.PURC_REQ_ID
WHERE T.TYPE = 'REQ' 
    AND T.SUB_TYPE NOT IN ('A1','H','AT') 
)

, CTETASKSUMM AS 
(SELECT EC_ID
    , PURC_ORD_ID 
    , SUM(APPV) AS APPV
    , SUM(APPVCOMP) AS APPVCOM
    , SUM(APPVEL1) AS APPVEL1
    , SUM(APPVEL1COMP) AS APPVEL1COMP
    , SUM(APPVEL2) AS APPVEL2
    , SUM(APPVEL2COMP) AS APPVEL2COMP
FROM CTETASK 
GROUP BY EC_ID, PURC_ORD_ID 
)

SELECT B.*
    , CASE WHEN ISNULL(INSPECT_QTY, 0) > 0 THEN 'YES'
           WHEN RECVRDATE IS NOT NULL AND SERVICEID IS NOT NULL 
                AND (CHARINDEX('RECEIV', NEXTOPRESDESC) > 0) 
                AND NEXTOPSTATUS IN ('F', 'R') THEN 'YES' 
           WHEN RECVRDATE IS NOT NULL AND SERVICEID IS NOT NULL 
                AND (CHARINDEX('INSP', NEXTOPRESDESC) > 0) 
                AND NEXTOPSTATUS IN ('F', 'R') THEN 'YES' 
                /*--> TT20210524: ADDED CODE FOR WHEN OP.COMPLETED_QTY DOESN'T MATCH RECEIVED_QTY*/
                -- WHEN RECVRDATE IS NOT NULL AND SERVICEID IS NOT NULL 
                --AND (CHARINDEX('INSP', NEXTOPRESDESC) = 0 OR CHARINDEX('RECEIV', NEXTOPRESDESC) = 0) 
                --AND NEXTOPSTATUS IN ('C') 
                --AND NEXTOPQTY < USER_RECEIVED_QTY
                --THEN 'YES' 
           ELSE '' END AS INSPECT
    , CASE WHEN S.APPVEL2 > 0 AND APPVEL2COMP > 0 THEN 'Y'
           WHEN S.APPVEL2 > 0 AND APPVEL2COMP = 0 THEN 'N'
           WHEN S.APPVEL1 > 0 AND APPVEL1COMP > 0 THEN 'Y'
           WHEN S.APPVEL1 > 0 AND APPVEL1COMP = 0 THEN 'N'
           WHEN S.APPVCOM > 0 AND APPVEL2 = 0 AND APPVEL1COMP = 0 THEN 'Y'
           ELSE 'N' END AS RFQAPPROVED
FROM CTEBASE B 
--> TT20210209: UPDATED FOR NOT REQ POS
LEFT OUTER JOIN CTETASKSUMM S 
    ON B.POID = S.PURC_ORD_ID
