-- Visual Enterprise Reports > Purchasing Reports > Open POs by Vendor
SELECT CONVERT(NVARCHAR(15), PO.ID) + '/' + CONVERT(NVARCHAR(3), POL.LINE_NO) AS PO_POLINE
    , [dbo].[sfnWONUMFormat](DSL.DEMAND_BASE_ID, DSL.DEMAND_LOT_ID, DSL.DEMAND_SPLIT_ID, DSL.DEMAND_SUB_ID) AS WONUM
    , PO.VENDOR_ID, CONVERT(DATE, PO.ORDER_DATE) AS ORDER_DATE, CONVERT(DATE, POL.DESIRED_RECV_DATE) AS RECV_DATE
    , PO.BUYER, PO.SHIPTO_ID, ISNULL(POL.PART_ID, POL.VENDOR_PART_ID) AS PART_ID, P.[DESCRIPTION] AS PART_DESC
    , POL.USER_ORDER_QTY, POL.TOTAL_USR_RECD_QTY, PO.[STATUS], CONVERT(DATE, POL.PROMISE_DATE) PROMISE_DATE
    , V.SUPPLIER_TYPE AS 'SUPPLIER_TYPE'
    , V.PRODUCT_TYPE AS 'PRODUCT_TYPE'
    , ROW_NUMBER() OVER (order by PO.ID) as  'row'
    , POL.TOTAL_AMT_ORDERED as 'Extension'
        , PO.SALES_ORDER_ID
FROM PURCHASE_ORDER PO WITH (NOLOCK)
INNER JOIN PURC_ORDER_LINE POL WITH (NOLOCK) ON POL.PURC_ORDER_ID = PO.ID
LEFT OUTER JOIN DBO.DEMAND_SUPPLY_LINK AS DSL WITH (NOLOCK) ON POL.PURC_ORDER_ID = DSL.SUPPLY_BASE_ID
    AND POL.LINE_NO = DSL.SUPPLY_SEQ_NO AND DSL.DEMAND_TYPE = 'OP' AND DSL.SUPPLY_TYPE = 'PO'
LEFT OUTER JOIN PART P WITH (NOLOCK) ON POL.PART_ID = P.ID
LEFT OUTER JOIN (SELECT ID, iif(USER_6 is null, 'Without Registration', USER_6) AS 'SUPPLIER_TYPE',
    iif(USER_7 is null, 'Without Registration', USER_7) AS 'PRODUCT_TYPE' FROM  VENDOR WITH (NOLOCK) ) V  ON PO.VENDOR_ID = V.ID

WHERE VENDOR_ID IN (@VENDOR) AND PO.[STATUS] IN (@STATUS)
AND PO.BUYER IN (@BUYER) AND V.SUPPLIER_TYPE IN (@SUPPLIER_TYPE) AND V.PRODUCT_TYPE IN (@PRODUCT_TYPE)
AND PO.ORDER_DATE >= @Date_Start AND PO.ORDER_DATE <= @Date_End
