--USE [Datamart]  -- ** IMPORTANT **
--GO

--/****** Object:  StoredProcedure [dbo].[usp_BOE_BILLING_EME_V2]    Script Date: 8/29/2025 12:28:11 PM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

-- =============================================
-- Author:        traci treffert
-- Create date: 9/22/2020
-- Description:    Boeing Billing for BOEEME
--        converted from original code in Crystal Reports to be used as SSRS report
--        take the logic/process out of hardcoded CR report and put in SQL for ease of maintenance
--        logic to also be included in Gross Margin processing
--
--  ISSUES WITH BILLING BASED UPON PART_IDS;  SEE COMPARISON
-- =============================================
---- CREATE PROCEDURE [dbo].[usp_BOE_BILLING_EME_V2] (@STARTDATE DATE, @ENDDATE DATE) AS

--DECLARE @STARTDATE DATE = '2025-08-01';
--DECLARE @ENDDATE DATE = '2025-08-31';

SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DEADLOCK_PRIORITY LOW

DECLARE @CHARGE FLOAT = (SELECT CHARGE FROM [sql-bi-1].LIVESupplemental.dbo.[BOE_Billing_Charges] WHERE [REPORT] = 'usp_BOE_BILLING_EME')

;

SELECT SPROC 
    , [COST ITEM]
    , POS
    , [PART NUMBER]
    , RAMAC
    , CASE
        WHEN SERVICE_CHARGE_ID = 'EX' THEN 1
        ELSE [BILLED QTY]
    END AS [BILLED QTY]
    , CASE
        WHEN SERVICE_CHARGE_ID = 'EX' THEN 0
        WHEN [EP_PART_ID] IS NOT NULL AND [EP_AMOUNT] <= 250 THEN 250 / [BILLED QTY] 
        WHEN [EP_PART_ID] IS NOT NULL AND [EP_AMOUNT] > 250 THEN [EP_AMOUNT] / [BILLED QTY]
        WHEN ((SUM(SORT_SETUP) + SUM(SORT_RUN)) * isnull(PRATE.bill_rate,@CHARGE)) < 250 THEN 250 / [BILLED QTY]
        ELSE ((SUM(SORT_SETUP) + SUM(SORT_RUN)) * isnull(PRATE.bill_rate,@CHARGE)) / [BILLED QTY] 
    END AS [UNIT PRICE]
    , CASE
        WHEN SERVICE_CHARGE_ID = 'EX' THEN 0
        WHEN [EP_PART_ID] IS NOT NULL AND [EP_AMOUNT] <= 250 THEN 250 
        WHEN [EP_PART_ID] IS NOT NULL AND [EP_AMOUNT] > 250 THEN [EP_AMOUNT]
        WHEN ((SUM(SORT_SETUP) + SUM(SORT_RUN)) * isnull(PRATE.bill_rate,@CHARGE)) < 250 THEN 250 
        ELSE ((SUM(SORT_SETUP) + SUM(SORT_RUN)) * isnull(PRATE.bill_rate,@CHARGE))  
    END AS [EXTENDED DOLLARS]
    , [EXPEDITE DOLLARS]
    , [SPECIAL FEES]
    , 0 AS [SERVICE_FEES]
    , CASE
        WHEN SERVICE_CHARGE_ID = 'EX' THEN 0
        ELSE SUM(SORT_SETUP) 
    END AS [SETUP HOURS]
    , CASE
        WHEN SERVICE_CHARGE_ID = 'EX' THEN 0
        ELSE SUM(SORT_RUN) 
    END AS [RUN HOURS]
    , [EXPEDITE HOURS]
    , [PACK SLIPS / DATE]
    , STUFF(REPLACE('/' + CONVERT(NVARCHAR(15), INVOICED_DATE, 101), '/0', '/'), 1, 1, '') + CASE
        WHEN SERVICE_CHARGE_ID = 'EX' THEN ',EXPEDITE'
        WHEN [EP_PART_ID] IS NOT NULL AND [EP_AMOUNT] <= 250 THEN ',MIN LOT'
        WHEN ((SUM(SORT_SETUP) + SUM(SORT_RUN)) * @CHARGE) < 250 THEN ',MIN LOT'
        ELSE ',WRAP' 
    END AS COMMENTS
    , [INVOICE ID]
    , [COID]
    , [COLINE]
    , '' AS SORTATION
FROM 
    (SELECT CASE
            WHEN CA.CITY IN ('HELENA', 'TUKWILA') THEN CA.CITY
            WHEN CO.CUSTOMER_ID IN ('BOE602') THEN CO.CUSTOMER_ID
            ELSE 'OTHER'
        END AS SPROC 
        , CASE
            WHEN COL.SERVICE_CHARGE_ID = 'EX' THEN 150
            ELSE 0 
        END AS [COST ITEM]
        , CASE
            WHEN COL.SERVICE_CHARGE_ID = 'EX' THEN 900
            ELSE 2 
        END AS POS
        , CASE
            WHEN RIGHT(CO.ID, 1) = 'A' AND LEN(REPLACE(CO.ID, 'A', '')) < 7 THEN CO.CUSTOMER_PO_REF + N'A'
            WHEN LEN(REPLACE(CO.ID, 'A', '')) < 7 THEN CO.CUSTOMER_PO_REF 
            ELSE CO.ID
        END AS RAMAC
        , CASE
            WHEN LEN(REPLACE(CO.ID, 'A', '')) < 7 THEN CO.ID
            ELSE CO.CUSTOMER_PO_REF 
        END AS COID
--        , 0 AS [EXPEDITE DOLLARS]
        , CASE
            WHEN COL.SERVICE_CHARGE_ID = 'EX' THEN COL.UNIT_PRICE
--            WHEN CO.CUSTOMER_ID IN ('BOE602') AND RIGHT(CO.CUSTOMER_PO_REF, 2) = 'SB' THEN 250
            ELSE 0 
        END AS [EXPEDITE DOLLARS]
        , 0 AS [SPECIAL FEES]
        , 0 AS [EXPEDITE HOURS]
        , LT.WORKORDER_BASE_ID
        , LT.HOURS_WORKED
        , EP.PART_ID AS [EP_PART_ID]
        , COL.LINE_NO AS [COLINE]
        , COL.SERVICE_CHARGE_ID
        , COL.UNIT_PRICE * COL.USER_ORDER_QTY AS [EP_AMOUNT]
        , CASE
            WHEN COL.SERVICE_CHARGE_ID = 'EX' THEN COL2.PART_ID 
            ELSE COL.PART_ID 
        END AS [PART NUMBER]
        , COL.TOTAL_SHIPPED_QTY AS [BILLED QTY]
        , LT.[TYPE]
        , LT.TRANSACTION_ID
        , CO.CUSTOMER_ID
        , SR.USER_1
        , SL.SHIPPED_QTY
        , S.INVOICE_ID AS [INVOICE ID]
        , S.INVOICED_DATE
        , S.PACKLIST_ID AS [PACK SLIPS / DATE]
        , SR.RESOURCE_ID
        , CASE
            WHEN LT.[TYPE] = 'S' THEN LT.HOURS_WORKED
            ELSE 0
        END AS SORT_SETUP
        , CASE
            WHEN LT.[TYPE] = 'R' THEN LT.HOURS_WORKED
            ELSE 0
        END AS SORT_RUN
    FROM dbo.SHIPPER S
    INNER JOIN dbo.SHIPPER_LINE SL
        ON S.PACKLIST_ID = SL.PACKLIST_ID
    INNER JOIN dbo.CUST_ORDER_LINE COL
        ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
        AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
    INNER JOIN dbo.CUSTOMER_ORDER CO
        ON COL.CUST_ORDER_ID = CO.ID
    INNER JOIN dbo.CUST_ORDER_LINE COL2
        ON SL.CUST_ORDER_ID = COL2.CUST_ORDER_ID
--        AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
        AND COL2.SERVICE_CHARGE_ID IS NULL
    LEFT OUTER JOIN dbo.DEMAND_SUPPLY_LINK DSL
        ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
        AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
    LEFT OUTER JOIN dbo.WORK_ORDER WO
        ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
        AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
        AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
    LEFT OUTER JOIN dbo.LABOR_TICKET LT
        ON WO.BASE_ID = LT.WORKORDER_BASE_ID
        AND WO.LOT_ID = LT.WORKORDER_LOT_ID
        AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
        AND WO.SUB_ID = LT.WORKORDER_SUB_ID
        AND WO.[TYPE] = LT.WORKORDER_TYPE
    LEFT OUTER JOIN dbo.SHOP_RESOURCE_SITE SR
        ON LT.RESOURCE_ID = SR.RESOURCE_ID
        --AND ISNULL(SR.USER_9, '') != 'BOE BILLING EXCLUDE'   -- Change
    LEFT OUTER JOIN CUST_ADDRESS CA
        ON CO.CUSTOMER_ID = CA.CUSTOMER_ID
        AND S.SHIP_TO_ADDR_NO = CA.ADDR_NO
    LEFT OUTER JOIN [sql-bi-1].LIVESupplemental.dbo.EME_Billing_Parts EP
        ON EP.PART_ID = COL.PART_ID
    WHERE SL.SHIPPED_QTY > 0
        AND ISNULL(WO.BASE_ID, '') NOT LIKE N'%R%'
        AND ISNULL(WO.PART_ID, '') NOT LIKE N'%REWORK%'
--> TT20211202: ADDED 602; REMOVED FROM 605
-->        AND CO.CUSTOMER_ID = N'BOEEME'
        AND CO.CUSTOMER_ID IN (N'BOEEME', N'BOE602')
        AND (S.INVOICED_DATE >= @STARTDATE AND S.INVOICED_DATE <= @ENDDATE)

--    AND CO.ID = '471811'
    ) A LEFT JOIN [sql-bi-1].datamart.dbo.BOE_Billing_Charges_RATE PRATE 
    ON PRATE.PART_ID=A.EP_PART_ID
GROUP BY SPROC 
    , [COST ITEM]
    , POS
    , [PART NUMBER]
    , SERVICE_CHARGE_ID 
    , RAMAC
    , [BILLED QTY]
    , [INVOICE ID]
    , INVOICED_DATE
    , [PACK SLIPS / DATE]
    , [EXPEDITE DOLLARS]
    , [SPECIAL FEES]
    , [EXPEDITE HOURS]
    , [EP_PART_ID]
    , [EP_AMOUNT]
    , [COID]
    , [COLINE]
    ,PRATE.bill_rate

UNION ALL
--> FOR 602SB EXPEDITES
SELECT SPROC 
    , [COST ITEM]
    , POS
    , [PART NUMBER]
    , RAMAC
    , 1 AS [BILLED QTY]
    , 0 AS [UNIT PRICE]
    , 0 AS [EXTENDED DOLLARS]
    , [EXPEDITE DOLLARS]
    , [SPECIAL FEES]
    , 0 AS [SERVICE_FEES]
    , 0 AS [SETUP HOURS]
    , 0 AS [RUN HOURS]
    , [EXPEDITE HOURS]
    , [PACK SLIPS / DATE]
    , STUFF(REPLACE('/' + CONVERT(NVARCHAR(15), INVOICED_DATE, 101), '/0', '/'), 1, 1, '') + ',EXPEDITE' AS COMMENTS
    , [INVOICE ID]
    , [COID]
    , [COLINE]
    , '' AS SORTATION
FROM 
    (SELECT CASE
            WHEN CA.CITY IN ('HELENA', 'TUKWILA') THEN CA.CITY
            WHEN CO.CUSTOMER_ID IN ('BOE602') THEN CO.CUSTOMER_ID
            ELSE 'OTHER'
        END AS SPROC 
        , 150 AS [COST ITEM]
        , 900 AS POS
        , CASE
            WHEN RIGHT(CO.ID, 1) = 'A' AND LEN(REPLACE(CO.ID, 'A', '')) < 7 THEN CO.CUSTOMER_PO_REF + N'A'
            WHEN LEN(REPLACE(CO.ID, 'A', '')) < 7 THEN CO.CUSTOMER_PO_REF 
            ELSE CO.ID
        END AS RAMAC
        , CASE
            WHEN LEN(REPLACE(CO.ID, 'A', '')) < 7 THEN CO.ID
            ELSE CO.CUSTOMER_PO_REF 
        END AS COID
        , CASE
            WHEN CO.CUSTOMER_ID IN ('BOE602') AND RIGHT(CO.CUSTOMER_PO_REF, 2) = 'SB' THEN 250
            ELSE 0 
        END AS [EXPEDITE DOLLARS]
        , 0 AS [SPECIAL FEES]
        , 0 AS [EXPEDITE HOURS]
        , 2 AS [COLINE]
        , COL.SERVICE_CHARGE_ID
        , COL.UNIT_PRICE * COL.USER_ORDER_QTY AS [EP_AMOUNT]
        , CASE
            WHEN COL.SERVICE_CHARGE_ID = 'EX' THEN COL2.PART_ID 
            ELSE COL.PART_ID 
        END AS [PART NUMBER]
        , COL.TOTAL_SHIPPED_QTY AS [BILLED QTY]
        , CO.CUSTOMER_ID
        , SL.SHIPPED_QTY
        , S.INVOICE_ID AS [INVOICE ID]
        , S.INVOICED_DATE
        , S.PACKLIST_ID AS [PACK SLIPS / DATE]
    FROM dbo.SHIPPER S
    INNER JOIN dbo.SHIPPER_LINE SL
        ON S.PACKLIST_ID = SL.PACKLIST_ID
    INNER JOIN dbo.CUST_ORDER_LINE COL
        ON SL.CUST_ORDER_ID = COL.CUST_ORDER_ID
        AND SL.CUST_ORDER_LINE_NO = COL.LINE_NO
    INNER JOIN dbo.CUSTOMER_ORDER CO
        ON COL.CUST_ORDER_ID = CO.ID
    INNER JOIN dbo.CUST_ORDER_LINE COL2
        ON SL.CUST_ORDER_ID = COL2.CUST_ORDER_ID
        AND COL2.SERVICE_CHARGE_ID IS NULL
    LEFT OUTER JOIN CUST_ADDRESS CA
        ON CO.CUSTOMER_ID = CA.CUSTOMER_ID
        AND S.SHIP_TO_ADDR_NO = CA.ADDR_NO
    WHERE SL.SHIPPED_QTY > 0
        AND CO.CUSTOMER_ID IN (N'BOEEME', N'BOE602')
        AND (S.INVOICED_DATE >= @STARTDATE AND S.INVOICED_DATE <= @ENDDATE)
        AND RIGHT(CO.CUSTOMER_PO_REF, 2) = 'SB'
--    AND CO.ID = '471811'
    ) A
GROUP BY SPROC 
    , [COST ITEM]
    , POS
    , [PART NUMBER]
    , SERVICE_CHARGE_ID 
    , RAMAC
    , [BILLED QTY]
    , [INVOICE ID]
    , INVOICED_DATE
    , [PACK SLIPS / DATE]
    , [EXPEDITE DOLLARS]
    , [SPECIAL FEES]
    , [EXPEDITE HOURS]
    , [EP_AMOUNT]
    , [COID]
    , [COLINE]
ORDER BY [RAMAC]
    , [COID]
    , [COLINE]



    
--GO


