--USE [Datamart]
--GO

--/****** Object:  StoredProcedure [dbo].[usp_BOE_BILLING_BOLTBOARDS]    Script Date: 8/26/2025 8:09:05 AM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO



-- =============================================
-- Author:        traci treffert
-- Create date: 9/13/2019
-- Description:    Boeing Billing for BOE614 Boltboards
--        converted from original code in Crystal Reports to be used as SSRS report
--        take the logic/process out of hardcoded CR report and put in SQL for ease of maintenance
--        logic to also be included in Gross Margin processing
-- =============================================

--DECLARE @STARTDATE DATE = '2025-08-18';
--DECLARE @ENDDATE DATE = '2025-08-24';

--CREATE PROCEDURE [dbo].[usp_BOE_BILLING_BOLTBOARDS] (@STARTDATE DATE, @ENDDATE DATE)
--AS

SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DEADLOCK_PRIORITY LOW
;

SELECT 'BOLTBOARDS' AS SPROC 
    , 0 AS [COST ITEM]
    , CASE
        WHEN DSL.DEMAND_BASE_ID LIKE '%R%' THEN 'RWK'
        ELSE '1'
    END AS POS
    , COL.PART_ID AS [PART NUMBER]
    , CO.ID AS RAMAC
    , RL.QTY AS [BILLED QTY]
    --, COL.UNIT_PRICE AS [UNIT PRICE]
    --, RL.AMOUNT AS [EXTENDED DOLLARS]
    , CASE WHEN R.INVOICE_DATE < '2024-01-01' THEN COL.UNIT_PRICE ELSE '5.62' END AS [UNIT PRICE]
    , CASE WHEN R.INVOICE_DATE < '2024-01-01' THEN RL.AMOUNT ELSE 5.62 * RL.QTY END AS [EXTENDED DOLLARS]
    , CASE
        WHEN COL.TOTAL_SHIPPED_QTY < 1 THEN 0 --  'PROBLEM'
        ELSE 0
    END AS [EXPEDITE DOLLARS]
    , 0 AS [SPECIAL FEES]
    , 0 AS [SERVICE_FEES]
    , CASE
        WHEN COL.TOTAL_SHIPPED_QTY < 1 THEN 0 -- 'PROBLEM'
        ELSE 0
    END AS [SETUP HOURS]
    , CASE
        WHEN COL.TOTAL_SHIPPED_QTY < 1 THEN 0 --'PROBLEM'
        ELSE 0
    END AS [RUN HOURS]
    , CASE
        WHEN COL.TOTAL_SHIPPED_QTY < 1 THEN 0 --'PROBLEM'
        ELSE 0
    END AS [EXPEDITE HOURS]
    , RL.PACKLIST_ID AS [PACK SLIPS / DATE]
    , CASE
        WHEN R.INVOICE_ID LIKE '%A%' THEN LEFT(R.INVOICE_ID,6)
        ELSE R.INVOICE_ID
    END AS [INVOICE ID]
    , STUFF(REPLACE('/' + CONVERT(NVARCHAR(15), R.INVOICE_DATE, 101), '/0', '/'), 1, 1, '')
     + ', BOLTBOARDS' AS COMMENTS
    , 1 AS SORTATION
FROM dbo.RECEIVABLE_LINE RL
INNER JOIN dbo.CUST_ORDER_LINE COL
    ON RL.CUST_ORDER_ID = COL.CUST_ORDER_ID
    AND RL.CUST_ORDER_LINE_NO = COL.LINE_NO
INNER JOIN dbo.RECEIVABLE R
    ON RL.INVOICE_ID = R.INVOICE_ID
INNER JOIN dbo.CUSTOMER_ORDER CO
    ON COL.CUST_ORDER_ID = CO.ID
INNER JOIN dbo.DEMAND_SUPPLY_LINK DSL
    ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
    AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
WHERE RL.QTY > 0
    AND CO.CUSTOMER_ID = N'BOE614'
    --AND (R.INVOICE_DATE >= '2024-01-01' AND R.INVOICE_DATE <= '2024-01-31')
    AND (R.INVOICE_DATE >= @STARTDATE AND R.INVOICE_DATE <= @ENDDATE)

--GO


