--> Home > Visual Enterprise Reports > Part Reports > Part Families Touched Within Timeframe
SELECT CO.CUSTOMER_ID
    , CO.ID
    , COL.LINE_NO
    , COL.PART_ID
    , WO.BASE_ID
    , WO.LOT_ID
    , WO.DESIRED_QTY
FROM LIVE.dbo.CUSTOMER_ORDER AS CO
INNER JOIN LIVE.dbo.CUST_ORDER_LINE AS COL
    ON CO.ID = COL.CUST_ORDER_ID 
INNER JOIN LIVE.dbo.DEMAND_SUPPLY_LINK AS DSL
    ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID
    AND COL.LINE_NO = DSL.DEMAND_SEQ_NO 
INNER JOIN LIVE.dbo.WORK_ORDER AS WO
    ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
    AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
    AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID 
WHERE COL.PART_ID LIKE @PARTID
    AND CO.CUSTOMER_ID IN (@CUSTOMERID)
    AND EXISTS (SELECT 1
        FROM LIVE.dbo.LABOR_TICKET AS LT
        WHERE WO.BASE_ID = LT.WORKORDER_BASE_ID
            AND WO.LOT_ID = LT.WORKORDER_LOT_ID
            AND WO.SPLIT_ID = LT.WORKORDER_SPLIT_ID
            AND WO.SUB_ID = LT.WORKORDER_SUB_ID
            AND WO.[TYPE] = LT.WORKORDER_TYPE
            AND LT.TRANSACTION_DATE >= @STARTDATE
            AND LT.TRANSACTION_DATE <= @ENDDATE
        )

