SELECT * FROM vw_PART_DATA
WHERE (PART_ID LIKE --'%' + @PART + '%')
    CASE
        WHEN @PART = 'ALL' THEN '%'
        ELSE '%' + @PART + '%'
    END )
    AND ISNULL([STATUS], 'A') IN (@STATUS)
    AND ISNULL([COMMODITY_CODE], '_Blank') IN (@COMMCODE)
    AND ISNULL([FABRICATED], 'N') IN (@FABRICATED)
    AND ISNULL([PURCHASED], 'N') IN (@PURCHASED)
    AND ISNULL([STOCKED], 'N') IN (@STOCKED)
    AND ISNULL([TOOL_OR_FIXTURE], 'N') IN (@TOOL)
    AND ISNULL([PLANNER_USER_ID], '_Blank') IN (@PLANNER)
    AND ISNULL([BUYER_USER_ID], '_Blank') IN (@BUYER)
    AND ISNULL(CONSUMABLE, 'N') IN (@CONSUMABLE)
