--> Home > Visual Enterprise Reports > Part Reports > Parts in Receiving Inspection 
SELECT V.[NAME] AS VENDOR_NAME
    , P.ID AS PART_ID
    , P.[DESCRIPTION]
    , P.STOCK_UM
    , P.COMMODITY_CODE
    , CONVERT(VARCHAR(7), POL.PURC_ORDER_ID) + '/' + CONVERT(VARCHAR(2), POL.LINE_NO) AS PO_ID_LINE_NO
    , R.RECEIVED_DATE
    , DATEDIFF(DAY, R.RECEIVED_DATE, GETDATE()) AS DAYS_IN_INSPECTION
    , CONVERT(VARCHAR(7), RL.RECEIVER_ID) + '/' + CONVERT(VARCHAR(2), RL.LINE_NO) AS RECEIVER_ID_LINE_NO
    , RL.RECEIVED_QTY
    , RL.INSP_REASON_CD
    , RL.INSPECT_QTY
FROM PURC_ORDER_LINE POL
INNER JOIN dbo.PURCHASE_ORDER PO
    ON PO.ID = POL.PURC_ORDER_ID
INNER JOIN dbo.VENDOR V
    ON V.ID = PO.VENDOR_ID
INNER JOIN dbo.PART P
    ON P.ID = POL.PART_ID
INNER JOIN dbo.RECEIVER_LINE RL
    ON POL.PURC_ORDER_ID = RL.PURC_ORDER_ID
    AND POL.LINE_NO = RL.PURC_ORDER_LINE_NO
INNER JOIN dbo.RECEIVER R
    ON R.ID = RL.RECEIVER_ID
WHERE RL.INSPECT_QTY > 0
    AND R.RECEIVED_DATE >= @STARTDATE
    AND R.RECEIVED_DATE <= @ENDDATE
ORDER BY R.RECEIVED_DATE
    , V.[NAME]
