SELECT        
P.DESCRIPTION 
, wo.PART_ID 
, wo.BASE_ID
, CAST(CAST(wob.BITS AS varbinary(max)) AS nvarchar(max)) AS SPECS
FROM PART AS P
INNER JOIN WORK_ORDER wo
    ON P.ID = wo.PART_ID 
INNER JOIN WORKORDER_BINARY wob
    ON wo.TYPE = wob.WORKORDER_TYPE 
    AND wo.BASE_ID = wob.WORKORDER_BASE_ID 
    AND wo.LOT_ID = wob.WORKORDER_LOT_ID 
    AND wo.SPLIT_ID = wob.WORKORDER_SPLIT_ID 
    AND wo.SUB_ID = wob.WORKORDER_SUB_ID
WHERE wo.PART_ID LIKE @PART
