SELECT L.PART_ID,P.FABRICATED,P.DESCRIPTION, P.PURCHASED,P.STATUS,P.COMMODITY_CODE,P.CONSUMABLE,P.INSPECTION_REQD, L.PURC_ORDER_ID, L.LINE_NO,P.QTY_IN_DEMAND,P.QTY_ON_HAND,(L.USER_ORDER_QTY-L.TOTAL_USR_RECD_QTY) AS QTY_ORDER, 
SUM((L.USER_ORDER_QTY-L.TOTAL_USR_RECD_QTY)) OVER (PARTITION BY L.PART_ID) AS TOTAL_QTY_Order
FROM PURC_ORDER_LINE L
INNER JOIN PURCHASE_ORDER O ON O.ID=L.PURC_ORDER_ID
INNER JOIN PART P ON P.ID=L.PART_ID
WHERE L.PART_ID NOT IN (SELECT PART_ID FROM REQUIREMENT WHERE WORKORDER_TYPE ='W' AND STATUS IN ('R','F')) 
AND L.PART_ID NOT IN  (SELECT distinct REQUIRED_PART_ID FROM PLANNED_MATL_REQ WHERE REQUIRED_PART_ID = L.PART_ID)
AND O.STATUS IN ('R','F') AND P.CONSUMABLE ='N' AND P.PURCHASED = 'Y' 
ORDER BY L.PART_ID
