--REVIEW ALL PARTS 
-- To ensure PRIMARY BUSINESS_UNIT, BUYER_USER_ID, COMMODITY_CODE are accurate.
-- Skills fields sizes that are used for calculating the surface area, Material, 
-- and Alloy for all end items are completed. With the intent to not have any Null 
-- values in these fields
-- Also to ensure that required fields such as FABRICATED, PURCHASED, Detail_only, 
-- and TOOL_OR_FIXTURE are accurate
-- To obsolete parts that are outdated
-- End Items for shipped dates
-- Purchased parts for Purchase Orders
-- This report will need to create daily reports to ensure maintenance of parts
-- Parameter created to separate volume of parts and send to responsible personnel at each plant
-- 02/26/2020 Vivian Elia changed buyer_user_id code 

--DECLARE @part_plant_review as varchar(10) = 'P1-review'
--DECLARE @max_ship_years as int = 0
--DECLARE @max_purc_years as int = 0
--DECLARE @start_date AS DATE = '1/1/2019'
--DECLARE @end_date AS DATE =  getdate()-- '12/25/2018'
--DECLARE @purchased as varchar(1) = ('N')
--DECLARE @commodity_code varchar(15) = ('_blank')
--DECLARE @buyer_name  varchar(15) = 'Michele'
--DECLARE @all_checks as nvarchar(300)
;
IF OBJECT_ID ('tempdb..#TMP_PART') IS NOT NULL
DROP TABLE #TMP_PART;
;

SELECT P.[STATUS]
    , P.CREATE_DATE
    , CASE 
        WHEN P.PLANNER_USER_ID NOT IN('FIN','FIN-HOURLY','MFG','MFG-HOURLY','MFG-PLAN','MFG-MRP','MFG-HOURLY-PLAN','PURCHASED','TOOLING','BUSSOL')
            OR P.PLANNER_USER_ID IS NULL THEN 'FIX PLANNER'
        ELSE 'OKAY'
    END AS PLANNER_CHECK
            ,CASE WHEN P.BUYER_USER_ID IS NULL
              THEN  'FIX BUYER'
             WHEN LEFT(P.BUYER_USER_ID,2) <> ISNULL(B.ACCOUNT_ID,'')
             THEN 'FIX BUYER'
             ELSE 'OKAY'
         END AS BUYER_CHECK
    , CASE 
        WHEN P.COMMODITY_CODE NOT IN ('Abrasives', 'Adhesives', 'CFM-Details', 'CFM-Raw Matl', 'CFM-Standards', 'Chemicals', 
            'Details', 'End Item', 'General', 'Lab Tests', 'Non-Fly Away', 'Paint-Primer', 'Paint-TopCoat', 'Raw Material',
            'Standards','Tools') OR COMMODITY_CODE IS NULL THEN 'FIX COMMODITY_CODE'
        ELSE 'OKAY'
    END AS COMMODITY_CODE_CHECK
    , CASE 
        WHEN P.[DESCRIPTION] IS NULL THEN 'FIX DESCRIPTION'
        ELSE 'OKAY'
    END AS DESCRIPTION_CHECK
    , P.PART_ID
    , P.[DESCRIPTION]
    , P.PLANNER_USER_ID
    , ISNULL(P.BUYER_USER_ID,'_blank') AS BUYER_USER_ID
    , ISNULL(B.Salesperson_ID,'_blank') AS Salesperson_ID
    , ISNULL(P.COMMODITY_CODE,'_blank') AS COMMODITY_CODE
    , P.PRODUCT_CODE
    , P.ENGINEERING_MSTR
    , P.FABRICATED
    , P.PURCHASED
    , P.STOCKED
    , P.DETAIL_ONLY
    , P.TOOL_OR_FIXTURE
    --INVENTORY INFORMATION
    , CASE 
        WHEN P.QTY_ON_HAND <> 0 THEN 'HAS INVENTORY'
        ELSE 'NO INVENTORY'
    END AS HASINVENTORY
    , P.QTY_ON_HAND
    , P.QTY_IN_DEMAND
    -- MFG NEEDED INFORMATION
    , P.USER_6 AS CBO_MIN_MAX
    , P.USER_7 AS AIRPLANE_MODEL
    , P.USER_8 AS AWARD_INFO
    , P.USER_9 AS PART_FAMILY
    , P.USER_10 AS CUSTOMER_ROLT
    --SKILLS DATA NEEDED
    , CASE 
        WHEN COMMODITY_CODE IN ('CFM-Standards', 'CFM-Raw Matl') THEN 'OKAY'
        ELSE CASE 
            WHEN TOOL_OR_FIXTURE = 'N' AND PURCHASED = 'N' 
-- TT20190722 - ADDED PER ANNW --> TICKET 2370
                AND COMMODITY_CODE IN ('End Item', 'Details', 'Non-Fly Away')
                    THEN CASE 
                WHEN PSA.MATERIAL_TYPE IS NULL OR PSA.ALLOY IS NULL
                    OR PSA.THICKNESS_VAL IS NULL OR PSA.WIDTH_VAL IS NULL
                    OR PSA.LENGTH_VAL IS NULL THEN 'FIX SKILLS DATA'
                ELSE 'OKAY' 
                END
            ELSE 'OKAY'
            END 
    END AS SKILLS_DATA_CHECK
    , PSA.MATERIAL_TYPE
    , PSA.ALLOY
    , PSA.THICKNESS_VAL
    , PSA.WIDTH_VAL
    , PSA.LENGTH_VAL
    , PSA.SURFACE_AREA
    -- CHECK FOR TRACE PROFILE
    , CASE 
        WHEN TP.PART_ID IS NULL THEN 'N'
        ELSE 'Y'
    END AS HAS_PROFILE
INTO #TMP_PART
FROM PART_SITE_VIEW P
LEFT OUTER JOIN SKILLS_PART_SURFACE_AREA PSA
    ON P.PART_ID = PSA.PART_ID
LEFT OUTER JOIN TRACE_PROFILE TP
    ON P.PART_ID = TP.PART_ID
LEFT OUTER JOIN LIVESupplemental.DBO.BUYER_ASSN B
    ON LEFT(P.BUYER_USER_ID,2) = B.Account_ID
WHERE (P.[STATUS] <> 'O' OR P.[STATUS] IS NULL)
GROUP BY P.[STATUS]
    , P.CREATE_DATE
    , P.PART_ID
    , P.[DESCRIPTION]
    , P.PLANNER_USER_ID
    , P.PRODUCT_CODE
    , P.BUYER_USER_ID
                   , B.ACCOUNT_ID
    , B.Salesperson_ID
    , P.COMMODITY_CODE
    , P.ENGINEERING_MSTR
    , P.FABRICATED
    , P.PURCHASED
    , P.STOCKED
    , P.DETAIL_ONLY
    , P.TOOL_OR_FIXTURE
    , CASE
        WHEN P.QTY_ON_HAND <> 0 THEN 'HAS INVENTORY'
        ELSE 'NO INVENTORY'
    END
    , P.QTY_ON_HAND
    , P.QTY_IN_DEMAND
    , P.USER_6
    , P.USER_7
    , P.USER_8
    , P.USER_9
    , P.USER_10
    , PSA.MATERIAL_TYPE
    , PSA.ALLOY
    , PSA.THICKNESS_VAL
    , PSA.WIDTH_VAL
    , PSA.LENGTH_VAL
    , PSA.SURFACE_AREA
    , CASE 
        WHEN TP.PART_ID IS NULL THEN 'N'
        ELSE 'Y'
    END
--select * from #tmp_part

;

WITH CTE_PART_CHECK AS
(SELECT PART_ID
    , REPLACE(REPLACE(REPLACE(PLANNER_CHECK,'OKAY','') + ', '
        + REPLACE(BUYER_CHECK, 'OKAY', '') + ', ' + REPLACE(COMMODITY_CODE_CHECK, 'OKAY', '') + ', '
        + REPLACE(SKILLS_DATA_CHECK, 'OKAY', '') + ', ' + REPLACE(DESCRIPTION_CHECK, 'OKAY', ''), ', ', ''), 'FIX', ',FIX')
    AS ALL_CHECKS
    , CASE 
        WHEN PLANNER_CHECK <> 'OKAY' THEN 1
        ELSE 0
    END AS CNT_PLANNER_CHECK
    , CASE 
        WHEN BUYER_CHECK <> 'OKAY' THEN 1
        ELSE 0
    END AS CNT_BUYER_CHECK
    , CASE 
        WHEN COMMODITY_CODE_CHECK <> 'OKAY' THEN 1
        ELSE 0
    END AS CNT_COMMODITY_CODE_CHECK
    , CASE 
        WHEN SKILLS_DATA_CHECK <> 'OKAY' THEN 1
        ELSE 0
    END AS CNT_SKILLS_DATA_CHECK
    , CASE 
        WHEN HAS_PROFILE = 'N' AND LEFT(PLANNER_USER_ID,3) = 'MFG' THEN 1
        WHEN HAS_PROFILE = 'N' AND COMMODITY_CODE = 'ABRASIVES' THEN 1
        ELSE 0
    END AS CNT_PROFILE_CHECK
FROM #TMP_PART 
)
--select * from CTE_PART_CHECK

, CTE_ERROR_COUNTS AS
(SELECT PART_ID
    , ALL_CHECKS
    , CNT_PLANNER_CHECK + CNT_BUYER_CHECK + CNT_COMMODITY_CODE_CHECK 
        + CNT_SKILLS_DATA_CHECK AS ERROR_COUNT
FROM CTE_PART_CHECK
 )

, CTE_CUSTOMER_SHIPPER AS 
(SELECT COL.PART_ID
    , CO.CUSTOMER_ID
    , UDF.STRING_VAL AS BUSINESS_UNIT
    , MAX(S.SHIPPED_DATE) AS MAX_SHIP_DATE
FROM CUSTOMER_ORDER CO
INNER JOIN USER_DEF_FIELDS UDF
    ON UDF.DOCUMENT_ID = CO.CUSTOMER_ID
    AND UDF.ID = 'UDF-0000072'
INNER JOIN CUST_ORDER_LINE COL
    ON COL.CUST_ORDER_ID = CO.ID
LEFT OUTER JOIN SHIPPER_LINE SL
    ON COL.CUST_ORDER_ID = SL.CUST_ORDER_ID
LEFT OUTER JOIN SHIPPER S
    ON COL.CUST_ORDER_ID = S.CUST_ORDER_ID
    AND COL.LINE_NO = SL.CUST_ORDER_LINE_NO
WHERE  EXISTS (SELECT 1
    FROM PART_SITE_VIEW P
    WHERE P.PART_ID = COL.PART_ID
        AND (P.[STATUS] <> 'O' OR P.[STATUS] IS NULL)
        AND (P.PLANNER_USER_ID NOT IN('FIN','FIN-HOURLY','MFG','MFG-HOURLY','MFG-PLAN','MFG-MRP','MFG-HOURLY-PLAN','PURCHASED','TOOLING','BUSSOL')
            OR P.PLANNER_USER_ID IS NULL)
        OR (P.BUYER_USER_ID IS NULL
            OR LEFT(P.BUYER_USER_ID,2) <>
                (SELECT LEFT(ACCOUNT_ID,2)
                FROM LIVESUPPLEMENTAL.DBO.BUYER_ASSN
                )
        )
    OR (P.COMMODITY_CODE NOT IN ('Abrasives', 'Adhesives', 'CFM-Details', 'CFM-Raw Matl', 'CFM-Standards', 'Chemicals', 
        'Details', 'End Item', 'General', 'Lab Tests', 'Non-Fly Away', 'Paint-Primer', 'Paint-TopCoat', 'Raw Material', 'Standards','Tools')
        OR COMMODITY_CODE IS NULL
        )
)
GROUP BY CO.CUSTOMER_ID
    , UDF.STRING_VAL
    , COL.PART_ID
) 
--OPERATIONS FIRST OP FOR BUSINESS UNIT

, CTE_FIRST_OP AS 
(SELECT [TYPE]
    , BASE_ID
    , LOT_ID
    , SPLIT_ID
    , SUB_ID
    , CASE
        WHEN SKILLS_TYPE = 'A' THEN 'FIN'
        WHEN SKILLS_TYPE = 'M' THEN 'MFG'
        WHEN SKILLS_TYPE = 'B' THEN 'FIN'
        ELSE 'OTHER'
    END AS FIRST_OP_BU
    , SKILLS_TYPE
    , FIRSTLOC
FROM   SKILLS_MASTER_OPS
WHERE  FIRSTLOC IS NOT NULL
)  --33466

, CTE_PURCHASE_ORDERS AS 
(SELECT POL.PART_ID
    , MAX(POL.LAST_RECEIVED_DATE) AS LAST_DATE_PUR
FROM PURC_ORDER_LINE POL
INNER JOIN PURCHASE_ORDER PO
    ON POL.PURC_ORDER_ID = PO.ID
WHERE  PO.[STATUS] <> 'X'
    AND EXISTS (SELECT 1
        FROM PART_SITE_VIEW PSV
        WHERE PSV.PART_ID = POL.PART_ID
    )
GROUP BY POL.PART_ID
)

SELECT P.[STATUS]
    , P.CREATE_DATE
    , CASE 
        WHEN P.CREATE_DATE < '12/25/2017' THEN 'CLEAN UP OLD PARTS'
        ELSE 'CLEAN UP NEW PARTS'
    END AS CLEANUP
    , EC.ALL_CHECKS
    , EC.ERROR_COUNT
    , P.PART_ID
    , P.[DESCRIPTION]
    , CASE 
        WHEN LEFT(PLANNER_USER_ID,3) = 'FIN' THEN 'P1-REVIEW'
        ELSE 'P2-REVIEW'
    END AS FILTER_PARAM
    , P.PLANNER_USER_ID
    , P.BUYER_USER_ID
    , P.Salesperson_ID
    , P.COMMODITY_CODE
    , P.PRODUCT_CODE
    , P.ENGINEERING_MSTR
    , P.FABRICATED
    , P.PURCHASED
    , P.STOCKED
    , P.DETAIL_ONLY
    , P.TOOL_OR_FIXTURE
    , P.HASINVENTORY
    , P.QTY_ON_HAND
    , P.QTY_IN_DEMAND
    , P.CBO_MIN_MAX
    , P.AIRPLANE_MODEL
    , P.AWARD_INFO
    , P.PART_FAMILY
    , P.CUSTOMER_ROLT
    , P.MATERIAL_TYPE
    , P.ALLOY
    , P.THICKNESS_VAL
    , P.WIDTH_VAL
    , P.LENGTH_VAL
    , P.SURFACE_AREA
    , P.HAS_PROFILE
    , FO.FIRST_OP_BU
    , FO.SKILLS_TYPE AS FO_SKILLS_TYPE
    , FO.FIRSTLOC AS FO_FIRSTLOC
    , CS.BUSINESS_UNIT AS CS_BUSINESS_UNIT
    , CS.CUSTOMER_ID
    , CS.MAX_SHIP_DATE
    , PU.LAST_DATE_PUR
FROM #TMP_PART P
LEFT OUTER JOIN CTE_FIRST_OP FO
    ON P.PART_ID = FO.BASE_ID
LEFT OUTER JOIN CTE_CUSTOMER_SHIPPER CS
    ON P.PART_ID = CS.PART_ID -- 134827 
LEFT OUTER JOIN CTE_PURCHASE_ORDERS PU
    ON P.PART_ID = PU.PART_ID
LEFT OUTER JOIN CTE_ERROR_COUNTS EC
    ON P.PART_ID = EC.PART_ID
WHERE EC.ERROR_COUNT <> 0
    AND CASE 
        WHEN LEFT(PLANNER_USER_ID,3) = 'FIN' THEN 'P1-REVIEW'
        ELSE 'P2-REVIEW'
    END in (@part_plant_review)
    AND (YEAR(CS.MAX_SHIP_DATE) < YEAR(GETDATE()) - @max_ship_years
        OR CS.MAX_SHIP_DATE IS NULL)
    AND (YEAR(PU.LAST_DATE_PUR) < YEAR(GETDATE()) - @max_purc_years
        OR PU.LAST_DATE_PUR IS NULL)
    AND (P.CREATE_DATE >= @start_date
    AND P.CREATE_DATE <= @end_date)
    AND P.PURCHASED In (@purchased)
    AND P.Salesperson_ID IN (@buyer_name)
    AND P.COMMODITY_CODE IN (@commodity_code)
