SELECT TRACE_INV_TRANS.TRANSACTION_ID, TRACE_INV_TRANS.PART_ID, TRACE_INV_TRANS.TRACE_ID, TRACE_INV_TRANS.QTY, INVENTORY_TRANS.WAREHOUSE_ID, INVENTORY_TRANS.LOCATION_ID
FROM TRACE_INV_TRANS INNER JOIN INVENTORY_TRANS ON TRACE_INV_TRANS.TRANSACTION_ID = INVENTORY_TRANS.TRANSACTION_ID
WHERE TRACE_INV_TRANS.TRANSACTION_ID =@Transaction_ID
