SELECT WO.PART_ID,
     dbo.sfnWONUMFormat(WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID) AS WORKORDER,
        
       BASE_ID,
       LOT_ID, 
       SPLIT_ID, 
       SUB_ID, 
       DESIRED_WANT_DATE, 
       DESIRED_QTY 
  FROM WORK_ORDER AS WO 
 WHERE BASE_ID = @BASE_ID
    AND LOT_ID = @LOT_ID
    AND SPLIT_ID = @SPLIT_ID
    AND TYPE = 'W'
