SELECT     INVENTORY_TRANS.TRANSACTION_ID, INVENTORY_TRANS.PART_ID, INVENTORY_TRANS.WORKORDER_BASE_ID, INVENTORY_TRANS.WORKORDER_LOT_ID, 
                      INVENTORY_TRANS.QTY, INVENTORY_TRANS.WAREHOUSE_ID, INVENTORY_TRANS.LOCATION_ID, PART.DESCRIPTION
FROM         LIVE.DBO.INVENTORY_TRANS INNER JOIN
                      LIVE.DBO.PART ON INVENTORY_TRANS.PART_ID = PART.ID
WHERE     (INVENTORY_TRANS.TRANSACTION_ID =
                          (SELECT     MAX(TRANSACTION_ID) 
                            FROM          LIVE.DBO.INVENTORY_TRANS
                            WHERE      (INVENTORY_TRANS.PART_ID = @PART_ID)))
