SELECT PART_ID,
        BASE_ID +'-'+SUB_ID +'/'+LOT_ID AS WORKORDER, 
       BASE_ID,
       LOT_ID, 
       SPLIT_ID, 
       SUB_ID, 
       DESIRED_WANT_DATE, 
       DESIRED_QTY 
  FROM WORK_ORDER 
 WHERE BASE_ID = @BASE_ID
    AND LOT_ID = @LOT_ID
    AND SPLIT_ID = @SPLIT_ID
