--declare @PURCHASE_ORDER varchar(24) = '175717', @HEAT varchar(24) = '29288197'

SELECT Distinct RL.PURC_ORDER_ID, RL.PURC_ORDER_LINE_NO, PL.PART_ID
    , CASE WHEN PS.PRIMARY_WHS_ID IS NULL THEN 'ALTERNATE' ELSE 'PRIMARY' 
    END + ' > ' + PL.WAREHOUSE_ID + '/' + PL.LOCATION_ID AS [PART_LOCATION]
    , PL.WAREHOUSE_ID + '/' + PL.LOCATION_ID AS LOCATION_ID
    , ISNULL(UDF.STRING_VAL, DBO.SPLIT(P.[DESCRIPTION], 2, ' ')) AS MATL_TYPE
    , T.APROPERTY_2,SUBSTRING(T.ID,CHARINDEX('/',T.ID)+1,1) RECIVER
FROM RECEIVER_LINE RL WITH (NOLOCK) 
INNER JOIN PURC_ORDER_LINE POL WITH (NOLOCK) ON POL.PURC_ORDER_ID = RL.PURC_ORDER_ID
    AND POL.LINE_NO = RL.PURC_ORDER_LINE_NO
LEFT OUTER JOIN PART P WITH (NOLOCK) ON P.ID = POL.PART_ID
LEFT OUTER JOIN PART_LOCATION PL WITH (NOLOCK) ON POL.PART_ID = PL.PART_ID
LEFT OUTER JOIN PART_SITE PS WITH (NOLOCK)  ON PS.PART_ID = POL.PART_ID
    AND PL.WAREHOUSE_ID = PS.PRIMARY_WHS_ID AND PL.LOCATION_ID = PS.PRIMARY_LOC_ID
LEFT OUTER JOIN USER_DEF_FIELDS UDF WITH (NOLOCK) ON UDF.PROGRAM_ID = 'VMPRTMNT'
    AND UDF.ID = 'UDF-0000035' AND UDF.DOCUMENT_ID = POL.PART_ID
LEFT OUTER JOIN TRACE_INV_TRANS TI WITH (NOLOCK)  ON TI.TRANSACTION_ID = RL.TRANSACTION_ID
LEFT OUTER JOIN TRACE T WITH (NOLOCK)  ON TI.TRACE_ID = T.ID
WHERE RL.PURC_ORDER_ID = @PURCHASE_ORDER AND T.APROPERTY_2=@HEAT AND PL.PART_ID = @part

/**********************************************************************/
/********************       UNION LIVEARC      ************************/
/**********************************************************************/
UNION

SELECT Distinct RL.PURC_ORDER_ID, RL.PURC_ORDER_LINE_NO, PL.PART_ID
    , CASE WHEN PS.PRIMARY_WHS_ID IS NULL THEN 'ALTERNATE' ELSE 'PRIMARY' 
    END + ' > ' + PL.WAREHOUSE_ID + '/' + PL.LOCATION_ID AS [PART_LOCATION]
    , PL.WAREHOUSE_ID + '/' + PL.LOCATION_ID AS LOCATION_ID
    , ISNULL(UDF.STRING_VAL, DBO.SPLIT(P.[DESCRIPTION], 2, ' ')) AS MATL_TYPE
    , T.APROPERTY_2,SUBSTRING(T.ID,CHARINDEX('/',T.ID)+1,1) RECIVER
FROM [SQL-Lab-2].LIVEARC.dbo.RECEIVER_LINE RL WITH (NOLOCK) 
INNER JOIN [SQL-Lab-2].LIVEARC.dbo.PURC_ORDER_LINE POL WITH (NOLOCK) ON POL.PURC_ORDER_ID = RL.PURC_ORDER_ID
    AND POL.LINE_NO = RL.PURC_ORDER_LINE_NO
LEFT OUTER JOIN [SQL-Lab-2].LIVEARC.dbo.PART P WITH (NOLOCK) ON P.ID = POL.PART_ID
LEFT OUTER JOIN [SQL-Lab-2].LIVEARC.dbo.PART_LOCATION PL WITH (NOLOCK) ON POL.PART_ID = PL.PART_ID
LEFT OUTER JOIN [SQL-Lab-2].LIVEARC.dbo.PART_SITE PS WITH (NOLOCK)  ON PS.PART_ID = POL.PART_ID
    AND PL.WAREHOUSE_ID = PS.PRIMARY_WHS_ID AND PL.LOCATION_ID = PS.PRIMARY_LOC_ID
LEFT OUTER JOIN [SQL-Lab-2].LIVEARC.dbo.USER_DEF_FIELDS UDF WITH (NOLOCK) ON UDF.PROGRAM_ID = 'VMPRTMNT'
    AND UDF.ID = 'UDF-0000035' AND UDF.DOCUMENT_ID = POL.PART_ID
LEFT OUTER JOIN [SQL-Lab-2].LIVEARC.dbo.TRACE_INV_TRANS TI WITH (NOLOCK)  ON TI.TRANSACTION_ID = RL.TRANSACTION_ID
LEFT OUTER JOIN [SQL-Lab-2].LIVEARC.dbo.TRACE T WITH (NOLOCK)  ON TI.TRACE_ID = T.ID
WHERE RL.PURC_ORDER_ID = @PURCHASE_ORDER AND T.APROPERTY_2=@HEAT AND PL.PART_ID = @part
