SELECT DSL.SUPPLY_BASE_ID AS BASE_ID
    , DSL.SUPPLY_LOT_ID AS LOT_ID
    , DSL.SUPPLY_SUB_ID AS SUB_ID
    , DSL.SUPPLY_SPLIT_ID AS SPLIT_ID
    , CO.CUSTOMER_ID
    , CO.ID
    , CO.CUSTOMER_PO_REF
    , COL.PART_ID
    , COL.CUSTOMER_PART_ID
    , COL.ORDER_QTY
    , dbo.sfnWONUMFormat(DSL.SUPPLY_BASE_ID, DSL.SUPPLY_LOT_ID, DSL.SUPPLY_SPLIT_ID, DSL.SUPPLY_SUB_ID) AS WONUM_ID
FROM CUST_ORDER_LINE COL
INNER JOIN CUSTOMER_ORDER CO
    ON COL.CUST_ORDER_ID = CO.ID 
INNER JOIN DEMAND_SUPPLY_LINK DSL
    ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID 
    AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
WHERE (CO.ID = @ORDER_ID)
