SELECT WO.BASE_ID
    , WO.LOT_ID
    , WO.SUB_ID
    , WO.SPLIT_ID
    , CO.CUSTOMER_ID
    , CO.ID
    , CO.CUSTOMER_PO_REF
    , ISNULL(COL.PART_ID, WO.PART_ID) AS PART_ID
    , COL.CUSTOMER_PART_ID
    , ISNULL(COL.ORDER_QTY, WO.DESIRED_QTY) AS ORDER_QTY
    , ISNULL(dbo.sfnWONUMFormat(DSL.SUPPLY_BASE_ID, DSL.SUPPLY_LOT_ID, DSL.SUPPLY_SPLIT_ID, DSL.SUPPLY_SUB_ID)
         , dbo.sfnWONUMFormat(WO.BASE_ID, WO.LOT_ID, WO.SPLIT_ID, WO.SUB_ID)) AS WONUM_ID
FROM WORK_ORDER WO
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
    ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
    AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
    AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
    AND DSL.SUPPLY_SUB_ID = WO.SUB_ID
LEFT OUTER JOIN CUST_ORDER_LINE COL
    ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID 
    AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
LEFT OUTER JOIN CUSTOMER_ORDER CO
    ON COL.CUST_ORDER_ID = CO.ID 
WHERE (WO.[TYPE] = @TYPE
    AND WO.BASE_ID = @BASE_ID
    AND WO.LOT_ID = @LOT_ID
    AND WO.SPLIT_ID = @SPLIT_ID
    AND WO.SUB_ID = @SUB_ID
    )
