SELECT IIF(WORKORDER_TYPE = 'W', 'WO', 'EM') AS 'TYPE', STATUS, WORKORDER_BASE_ID AS 'WO', WORKORDER_LOT_ID AS 'LOT_ID', 
    WORKORDER_SPLIT_ID AS 'SPLIT_ID', RESOURCE_ID, CALC_START_QTY, COMPLETED_QTY
FROM OPERATION  WHERE STATUS in ('F', 'R', 'U') AND
RESOURCE_ID IN ('P3M1-REC', 'P3M1-SHIP', 'P3M1-IN-DIM', 'P3M1-DB-DBR', 'P3M1-FM-BLST-AU', 'P3M1-FM-CF', 
'P3M1-FM-HF-SM', 'P3M1-BS-REVIEW', 'P3M1-BS-IN')
order by WORKORDER_BASE_ID
