SELECT IIF(POL.ORDER_QTY = RL.RECEIVED_QTY, 'NO','YES') AS [QTY ISSUE]
    , CASE
        WHEN (POL.UNIT_PRICE * RL.RECEIVED_QTY) = P.TOTAL_AMOUNT THEN 'NO'
        ELSE 'YES'
    END AS [PRICE ISSUE]
    , CASE 
        WHEN POR.PURC_REQ_ID IS NULL AND EDP.pNo IS NULL THEN 'NEEDS APPROVAL'
        ELSE ''
    END AS APPROVALCHECK
    , EDP.pNo
    , EDF.[section] 
    , EDF.[CompanyID] 
    , P.INVOICE_ID 
    , PO.CREATE_DATE
    , PO.ID AS PO_ID
    , POL.LINE_NO AS 'PO_LINE_NO'
    , PRL.PURC_REQ_ID AS PR_ID
    , PRL.LINE_NO AS PR_LINE
    , PL.VOUCHER_ID
    , PL.LINE_NO AS VOUCHER_LINE
    , RL.RECEIVER_ID AS 'RECEIVER_ID'
    , RL.LINE_NO AS RCVR_LINE    
    , R.RECEIVED_DATE
    , PO.VENDOR_ID
    , POL.ORDER_QTY AS POL_ORDERQTY
    , RL.RECEIVED_QTY AS RL_RECEIVEDQTY
    , POL.UNIT_PRICE AS POL_UNITPRICE
    , P.TOTAL_AMOUNT AS PAY_TOTALAMT
    , POL.TOTAL_AMT_ORDERED AS 'PO_AMOUNT'
    , POL.TOTAL_AMT_RECVD AS 'RECEIVED_AMOUNT'
    , PL.AMOUNT AS 'INVOICE_AMOUNT'
    , PO.BUYER
    , P.PAY_STATUS
FROM PAYABLE P
LEFT OUTER JOIN PAYABLE_LINE PL
    ON PL.VOUCHER_ID = P.VOUCHER_ID
LEFT OUTER JOIN PURC_ORDER_LINE POL
    ON POL.PURC_ORDER_ID = PL.PURC_ORDER_ID
    AND POL.LINE_NO = PL.PURC_ORDER_LINE_NO
LEFT OUTER JOIN RECEIVER_LINE RL
    ON RL.PURC_ORDER_ID = POL.PURC_ORDER_ID
    AND RL.PURC_ORDER_LINE_NO = POL.LINE_NO
    AND PL.RECEIVER_ID = RL.RECEIVER_ID
    AND PL.RECEIVER_LINE_NO = RL.LINE_NO
LEFT OUTER JOIN PURC_ORDER_REQ POR
    ON POL.PURC_ORDER_ID = POR.PURC_ORD_ID
    AND POL.LINE_NO = POR.PURC_ORD_LINE_NO
LEFT OUTER JOIN PURC_REQ_LINE PRL
    ON POR.PURC_REQ_ID = PRL.PURC_REQ_ID
    AND POR.PURC_REQ_LINE_NO = PRL.LINE_NO
LEFT OUTER JOIN PURCHASE_ORDER PO
    ON PO.ID = POL.PURC_ORDER_ID
LEFT OUTER JOIN RECEIVER R
    ON R.ID = RL.RECEIVER_ID
LEFT OUTER JOIN [SQL-LAB-1].dbRMS.dbo.tblPO EDP
    ON CONVERT(NVARCHAR(15), EDP.pNo) = PO.ID
LEFT OUTER JOIN [SQL-LAB-1].dbRMS.dbo.tblFiles EDF
    ON EDP.fileID = EDF.id
    AND EDF.CompanyID = PO.VENDOR_ID
    AND EDF.[section] = 'Purchase Requisition'
LEFT OUTER JOIN [SQL-LAB-1].dbRMS.dbo.tblInvoice EDI
    ON EDF.id = EDI.fileID
WHERE (PO.CREATE_DATE >= '1/1/2019'
    AND P.PAY_STATUS IN (@STATUS)
    AND IIF(POL.ORDER_QTY = RL.RECEIVED_QTY, 'NO','YES') IN (@QTYISSUE)
    AND CASE
        WHEN (POL.UNIT_PRICE * RL.RECEIVED_QTY) = P.TOTAL_AMOUNT THEN 'NO'
        ELSE 'YES'
    END IN (@PRICEISSUES)
    AND CASE 
        WHEN POR.PURC_REQ_ID IS NULL AND EDP.pNo IS NULL THEN 'NEEDS APPROVAL'
        ELSE 'APPROVAL MET'
    END IN (@APPROVAL)
    AND (@POID) = '_Blank'
    )
    OR PO.ID IN (@POID)
