SELECT A.*
       , CASE
              WHEN COL.CUST_ORDER_ID IS NOT NULL THEN 'EXPEDITE'
              ELSE ''
       END AS EXPEDITE
       , DATEDIFF(D, A.ORDER_DATE, MAX(A.[DESIRED_SHIP_DATE])) AS [TRUETURNTIME]
FROM
    (SELECT CO.CUSTOMER_ID
           , CUST_ORDER_ID
           , [ORDER_DATE]
           , CO.[DESIRED_SHIP_DATE]
    FROM CUSTOMER_ORDER CO
    LEFT OUTER JOIN CUST_ORDER_LINE COL
           ON CO.ID = COL.CUST_ORDER_ID
    WHERE COL.PART_ID IS NOT NULL
        AND CO.ORDER_DATE >= '1/1/2018'
    ) AS A
    LEFT OUTER JOIN CUST_ORDER_LINE COL
           ON  A.CUST_ORDER_ID = COL.CUST_ORDER_ID
           AND COL.MISC_REFERENCE LIKE 'EXPED%'
GROUP BY 
       CUSTOMER_ID
       , A.CUST_ORDER_ID
       , [ORDER_DATE]
       , A.[DESIRED_SHIP_DATE]
       , CASE
              WHEN COL.CUST_ORDER_ID IS NOT NULL THEN 'EXPEDITE'
              ELSE ''
       END
