exec('
SELECT X.*, OPEN_TTL - IB_TTL_AMT AS DELTA, TX.USER_ID, 
CASE WHEN TX.WORKORDER_BASE_ID IS NOT NULL THEN ''WO: '' + TX.WORKORDER_BASE_ID + ''/'' + TX.WORKORDER_LOT_ID
     WHEN TX.CUST_ORDER_ID IS NOT NULL THEN ''CO: '' + TX.CUST_ORDER_ID + ''/'' + CAST(TX.CUST_ORDER_LINE_NO AS VARCHAR)
     WHEN TX.PURC_ORDER_ID IS NOT NULL THEN ''PO: '' + TX.PURC_ORDER_ID + ''/'' + CAST(TX.PURC_ORDER_LINE_NO AS VARCHAR)
     WHEN TX.CLASS = ''A'' THEN TX.DESCRIPTION
     ELSE NULL END AS DOCUMENT
FROM (
    SELECT ''VAL_BAL'' AS RPT_TYPE, TRANSACTION_DATE, (SELECT TRANSACTION_ID FROM ' + @DB + '.dbo.INVENTORY_BALANCE WHERE POSTING_DATE = ''' + @POSTING_DATE + ''' AND TRANSACTION_ID = Q.TRANSACTION_ID) AS CROSS_REF_TX, 
    PART_ID, TRANSACTION_ID AS TX_ID, OPEN_QTY, 
    (SELECT SUM(QTY) FROM ' + @DB + '.dbo.INVENTORY_BALANCE WHERE TRANSACTION_ID = Q.TRANSACTION_ID AND POSTING_DATE = ''' + @POSTING_DATE + ''') AS IB_QTY, 
    CLASS, TYPE, 
    OPEN_MATL, ISNULL((SELECT SUM(MATERIAL_AMOUNT) FROM ' + @DB + '.dbo.INVENTORY_BALANCE WHERE TRANSACTION_ID = Q.TRANSACTION_ID AND POSTING_DATE = ''' + @POSTING_DATE + '''),0) AS IB_MATL,
    OPEN_LABR, ISNULL((SELECT SUM(LABOR_AMOUNT) FROM ' + @DB + '.dbo.INVENTORY_BALANCE WHERE TRANSACTION_ID = Q.TRANSACTION_ID AND POSTING_DATE = ''' + @POSTING_DATE + '''),0) AS IB_LABR,
    OPEN_BURD, ISNULL((SELECT SUM(BURDEN_AMOUNT) FROM ' + @DB + '.dbo.INVENTORY_BALANCE WHERE TRANSACTION_ID = Q.TRANSACTION_ID AND POSTING_DATE = ''' + @POSTING_DATE + '''),0) AS IB_BURD,
    OPEN_SERV, ISNULL((SELECT SUM(SERVICE_AMOUNT) FROM ' + @DB + '.dbo.INVENTORY_BALANCE WHERE TRANSACTION_ID = Q.TRANSACTION_ID AND POSTING_DATE = ''' + @POSTING_DATE + '''),0) AS IB_SERV,
    CAST((OPEN_MATL+OPEN_LABR+OPEN_BURD+OPEN_SERV) AS DECIMAL(14,2)) AS OPEN_TTL, 
    ISNULL((SELECT SUM(MATERIAL_AMOUNT+LABOR_AMOUNT+BURDEN_AMOUNT+SERVICE_AMOUNT) 
            FROM ' + @DB + '.dbo.INVENTORY_BALANCE WHERE TRANSACTION_ID = Q.TRANSACTION_ID AND POSTING_DATE = ''' + @POSTING_DATE + '''),0) AS IB_TTL_AMT

    FROM (
    SELECT IT.PART_ID, IT.TRANSACTION_ID, IT.TRANSACTION_DATE, 
        (IT.QTY-IT.COSTED_QTY)*(CASE WHEN TYPE = ''I'' THEN 1 ELSE -1 END) AS OPEN_QTY, CLASS, TYPE, 
        CASE WHEN IT.TYPE = ''I''
             THEN IT.ACT_MATERIAL_COST / (CASE WHEN IT.QTY = 0 THEN 1 ELSE IT.QTY END) * (IT.QTY - IT.COSTED_QTY) 
             ELSE (IT.ACT_MATERIAL_COST -
                ISNULL((SELECT SUM(ACT_MATERIAL_COST) FROM ' + @DB + '.dbo.INV_TRANS_DIST (NOLOCK) WHERE OUT_TRANS_ID = IT.TRANSACTION_ID),0))*-1
             END AS OPEN_MATL, 
        CASE WHEN IT.TYPE = ''I''
             THEN IT.ACT_LABOR_COST / (CASE WHEN IT.QTY = 0 THEN 1 ELSE IT.QTY END) * (IT.QTY - IT.COSTED_QTY) 
             ELSE (IT.ACT_LABOR_COST - 
                ISNULL((SELECT SUM(ACT_LABOR_COST) FROM ' + @DB + '.dbo.INV_TRANS_DIST (NOLOCK) WHERE OUT_TRANS_ID = IT.TRANSACTION_ID),0))*-1
             END AS OPEN_LABR, 
        CASE WHEN IT.TYPE = ''I''
             THEN IT.ACT_BURDEN_COST / (CASE WHEN IT.QTY = 0 THEN 1 ELSE IT.QTY END) * (IT.QTY - IT.COSTED_QTY) 
             ELSE (IT.ACT_BURDEN_COST -
                ISNULL((SELECT SUM(ACT_BURDEN_COST) FROM ' + @DB + '.dbo.INV_TRANS_DIST (NOLOCK) WHERE OUT_TRANS_ID = IT.TRANSACTION_ID),0))*-1
             END AS OPEN_BURD, 
        CASE WHEN IT.TYPE = ''I''
             THEN IT.ACT_SERVICE_COST / (CASE WHEN IT.QTY = 0 THEN 1 ELSE IT.QTY END) * (IT.QTY - IT.COSTED_QTY) 
             ELSE (IT.ACT_SERVICE_COST - 
                ISNULL((SELECT SUM(ACT_SERVICE_COST) FROM ' + @DB + '.dbo.INV_TRANS_DIST (NOLOCK) WHERE OUT_TRANS_ID = IT.TRANSACTION_ID),0))*-1
             END AS OPEN_SERV
        FROM ' + @DB + '.dbo.INVENTORY_TRANS IT (NOLOCK) JOIN ' + @DB + '.dbo.PART P (NOLOCK) ON IT.PART_ID = P.ID 
        AND IT.QTY > IT.COSTED_QTY
    )Q 
UNION ALL
    SELECT ''BAL_VAL'' AS RPT_TYPE, IT.TRANSACTION_DATE, (SELECT TRANSACTION_ID FROM ' + @DB + '.dbo.INVENTORY_TRANS WHERE COSTED_QTY < QTY AND TRANSACTION_ID = IB.TRANSACTION_ID) AS CROSS_REF_TX, 
    IB.PART_ID, IB.TRANSACTION_ID, 
    CASE WHEN IT.TYPE = ''I'' 
         THEN CASE WHEN IT.QTY = IT.COSTED_QTY THEN NULL ELSE IT.QTY-IT.COSTED_QTY END 
         ELSE (IT.QTY-IT.COSTED_QTY)*-1 END AS QTY, 
    IB.QTY AS IB_QTY, IT.CLASS, IT.TYPE, 
    CASE WHEN IT.TYPE = ''I''
            THEN IT.ACT_MATERIAL_COST / (CASE WHEN IT.QTY = 0 THEN 1 ELSE IT.QTY END) * (IT.QTY - IT.COSTED_QTY) 
            ELSE (IT.ACT_MATERIAL_COST -
            ISNULL((SELECT SUM(ACT_MATERIAL_COST) FROM ' + @DB + '.dbo.INV_TRANS_DIST (NOLOCK) WHERE OUT_TRANS_ID = IT.TRANSACTION_ID),0))*-1
            END AS OPEN_MATL,
    IB.MATERIAL_AMOUNT AS IB_MATL, 
    CASE WHEN IT.TYPE = ''I''
            THEN IT.ACT_LABOR_COST / (CASE WHEN IT.QTY = 0 THEN 1 ELSE IT.QTY END) * (IT.QTY - IT.COSTED_QTY) 
            ELSE (IT.ACT_LABOR_COST - 
            ISNULL((SELECT SUM(ACT_LABOR_COST) FROM ' + @DB + '.dbo.INV_TRANS_DIST (NOLOCK) WHERE OUT_TRANS_ID = IT.TRANSACTION_ID),0))*-1
            END AS OPEN_LABR, 
    IB.LABOR_AMOUNT AS IB_LABR, 
    CASE WHEN IT.TYPE = ''I''
            THEN IT.ACT_BURDEN_COST / (CASE WHEN IT.QTY = 0 THEN 1 ELSE IT.QTY END) * (IT.QTY - IT.COSTED_QTY) 
            ELSE (IT.ACT_BURDEN_COST -
            ISNULL((SELECT SUM(ACT_BURDEN_COST) FROM ' + @DB + '.dbo.INV_TRANS_DIST (NOLOCK) WHERE OUT_TRANS_ID = IT.TRANSACTION_ID),0))*-1
            END AS OPEN_BURD, 
    IB.BURDEN_AMOUNT AS IB_BURD,
    CASE WHEN IT.TYPE = ''I''
            THEN IT.ACT_SERVICE_COST / (CASE WHEN IT.QTY = 0 THEN 1 ELSE IT.QTY END) * (IT.QTY - IT.COSTED_QTY) 
            ELSE (IT.ACT_SERVICE_COST - 
            ISNULL((SELECT SUM(ACT_SERVICE_COST) FROM ' + @DB + '.dbo.INV_TRANS_DIST (NOLOCK) WHERE OUT_TRANS_ID = IT.TRANSACTION_ID),0))*-1
            END AS OPEN_SERV,
    IB.SERVICE_AMOUNT AS IB_SERV, 
    CASE WHEN IT.TYPE = ''I''
            THEN (IT.ACT_MATERIAL_COST+IT.ACT_LABOR_COST+IT.ACT_BURDEN_COST+IT.ACT_SERVICE_COST) 
                / (CASE WHEN IT.QTY = 0 THEN 1 ELSE IT.QTY END) * (IT.QTY - IT.COSTED_QTY) 
            ELSE ((IT.ACT_MATERIAL_COST+IT.ACT_LABOR_COST+IT.ACT_BURDEN_COST+IT.ACT_SERVICE_COST) - 
                    ISNULL((SELECT SUM(ACT_MATERIAL_COST+ACT_LABOR_COST+ACT_BURDEN_COST+ACT_SERVICE_COST) 
                    FROM ' + @DB + '.dbo.INV_TRANS_DIST (NOLOCK) WHERE OUT_TRANS_ID = IT.TRANSACTION_ID),0))*-1
            END AS OPEN_TTL,
    (IB.MATERIAL_AMOUNT+IB.LABOR_AMOUNT+IB.BURDEN_AMOUNT+IB.SERVICE_AMOUNT) AS IB_TTL_AMT
    FROM ' + @DB + '.dbo.INVENTORY_BALANCE IB LEFT JOIN ' + @DB + '.dbo.INVENTORY_TRANS IT ON IB.TRANSACTION_ID = IT.TRANSACTION_ID
    WHERE IB.POSTING_DATE = ''' + @POSTING_DATE + '''
)X JOIN ' + @DB + '.dbo.INVENTORY_TRANS TX ON X.TX_ID = TX.TRANSACTION_ID
WHERE ABS(ISNULL(OPEN_TTL,0)-ISNULL(IB_TTL_AMT,0)) > ' + @THRESHOLD + ' OR ISNULL(OPEN_QTY,0) <> ISNULL(IB_QTY,0)
ORDER BY X.PART_ID')
