SELECT R.INVOICE_ID
    , R.INVOICE_DATE
    , R.CUSTOMER_ID
    , RL.CUST_ORDER_ID AS INV_CO
    , SL.CUST_ORDER_ID AS SL_CO
    , RL.PACKLIST_ID
    , RL.PACKLIST_LINE_NO
FROM RECEIVABLE_LINE RL
INNER JOIN RECEIVABLE R
    ON R.INVOICE_ID = RL.INVOICE_ID
INNER JOIN SHIPPER_LINE SL
    ON RL.PACKLIST_ID = SL.PACKLIST_ID
    AND RL.PACKLIST_LINE_NO = SL.LINE_NO
WHERE CUSTOMER_ID = @CUSTOMER
    AND R.INVOICE_DATE >= @STARTDATE
    AND R.INVOICE_DATE <= @ENDDATE

