SELECT A.ID
, A.[DESCRIPTION]
, MONTH(POL.LAST_RECEIVED_DATE) AS [MONTH]
, YEAR(POL.LAST_RECEIVED_DATE) AS [YEAR]
, CASE
    WHEN YEAR(POL.LAST_RECEIVED_DATE) = '2020' THEN B.[2020_BUDGET]
    WHEN YEAR(POL.LAST_RECEIVED_DATE) = '2019' THEN B.[2019_BUDGET]
    ELSE '0'
END AS BUDGET
, SUM(POL.TOTAL_AMT_ORDERED) AS [CURRENT SPEND]
, CASE
    WHEN YEAR(POL.LAST_RECEIVED_DATE) = '2020' THEN B.[2020_BUDGET]
    WHEN YEAR(POL.LAST_RECEIVED_DATE) = '2019' THEN B.[2019_BUDGET]
    ELSE '0'
END - SUM(POL.TOTAL_AMT_ORDERED) AS [DELTA]
FROM PURC_ORDER_LINE POL
INNER JOIN PURCHASE_ORDER PO
    ON POL.PURC_ORDER_ID = PO.ID
LEFT OUTER JOIN LIVESUPPLEMENTAL.DBO.ACCTG_BUDGET B
    ON B.GL_ACCT = POL.GL_EXPENSE_ACCT_ID
    AND MONTH(POL.LAST_RECEIVED_DATE) = B.[MONTH]
LEFT OUTER JOIN ACCOUNT A
    ON A.ID = POL.GL_EXPENSE_ACCT_ID
LEFT OUTER JOIN ACCOUNT_BALANCE AB
    ON AB.ACCOUNT_ID = A.ID
    AND AB.ACCT_YEAR = MONTH(POL.LAST_RECEIVED_DATE)
    AND AB.ACCT_PERIOD = YEAR(POL.LAST_RECEIVED_DATE)
WHERE POL.LAST_RECEIVED_DATE >= '1/1/2019'
    AND POL.LAST_RECEIVED_DATE IS NOT NULL
    AND POL.GL_EXPENSE_ACCT_ID IS NOT NULL
    AND B.[2020_BUDGET] IS NOT NULL
    AND POL.LAST_RECEIVED_DATE <= '2/1/2040'
    AND YEAR(POL.LAST_RECEIVED_DATE) = @YEAR
    AND MONTH(POL.LAST_RECEIVED_DATE) = @MONTH
GROUP BY A.ID
    , A.[DESCRIPTION]
    , MONTH(POL.LAST_RECEIVED_DATE) 
    , YEAR(POL.LAST_RECEIVED_DATE)
    , B.[2020_BUDGET]
    , B.[2019_BUDGET]

