--> Home > Visual Enterprise Financial Reports > Receivable Reconciliations
SELECT CO.CUSTOMER_ID
    , UDF.STRING_VAL AS [BUS_STREAM]
    , COL.USER_5 AS COL_VERIFICATION
    , COL.CUST_ORDER_ID
    , COL.LINE_NO AS CO_LINE
    , COL.UNIT_PRICE
    , COL.ORDER_QTY AS TOTAL_ORDER_QTY
    , SL.SHIPPED_QTY 
    , ISNULL(R.INVOICE_ID, 'NO INVOICE') AS INVOICE_ID
    , RL.LINE_NO AS INV_LINE
    , R.PRINTED_DATE
    , R.CREATE_DATE
    , RL.QTY AS INV_QTY
    , COL.ORDER_QTY - COL.TOTAL_SHIPPED_QTY AS MISSING_QTY
--    , (SL.SHIPPED_QTY * RL.AMOUNT) AS 'TOTAL_AMT'
    , RL.AMOUNT AS INV_AMOUNT
    , COL.TOTAL_AMT_SHIPPED AS COL_SHIP_AMT
    , RL.AMOUNT - COL.TOTAL_AMT_SHIPPED AS AMOUNT_DELTA
    , (RL.AMOUNT - (SL.SHIPPED_QTY * COL.UNIT_PRICE)) AS SHIP_AMT_DELTA
    , CO.TOTAL_AMT_ORDERED
    , R.TOTAL_AMOUNT AS INV_TOTAL_AMOUNT
    , CO.TOTAL_AMT_ORDERED - R.TOTAL_AMOUNT AS TOTAL_AMOUNT_DELTA
    , CASE
        WHEN CO.CUSTOMER_ID = 'BOE609' THEN NULL
        WHEN CO.TOTAL_AMT_ORDERED < 175 THEN 'CHECK'
        ELSE NULL
    END AS [MIN_ORDER_CHECK]
    , S.SHIPPED_DATE
    , IIF(COL.PART_ID IS null, COL.SERVICE_CHARGE_ID, COL.PART_ID) as 'PART_ID'
FROM SHIPPER S
INNER JOIN SHIPPER_LINE SL
    ON S.PACKLIST_ID = SL.PACKLIST_ID
INNER JOIN CUST_ORDER_LINE COL
    ON COL.CUST_ORDER_ID = SL.CUST_ORDER_ID
    AND COL.LINE_NO = SL.CUST_ORDER_LINE_NO
INNER JOIN CUSTOMER_ORDER CO
    ON CO.ID = COL.CUST_ORDER_ID
LEFT OUTER JOIN USER_DEF_FIELDS UDF
    ON UDF.DOCUMENT_ID = CO.CUSTOMER_ID
    AND PROGRAM_ID = 'VMCUSMNT'
    AND UDF.ID = 'UDF-0000072'
LEFT OUTER JOIN RECEIVABLE_LINE RL
    ON RL.PACKLIST_ID = SL.PACKLIST_ID
    AND RL.PACKLIST_LINE_NO = SL.LINE_NO
LEFT OUTER JOIN RECEIVABLE R
    ON R.INVOICE_ID = RL.INVOICE_ID
WHERE S.SHIPPED_DATE >= @STARTDATE
    AND ISNULL(R.INVOICE_DATE, GETDATE()) >= @INVDATE
    AND (
            (@CHECK = 'Y'
            AND CASE
                WHEN CO.CUSTOMER_ID = 'BOE609' THEN NULL
                WHEN CO.TOTAL_AMT_ORDERED < 175 THEN 'CHECK'
                ELSE NULL
            END = 'CHECK'
            )
            OR 
            (@CHECK = 'ALL')
            )
    AND (
            (@INVOICE = 'N' AND R.INVOICE_ID IS NULL)
            OR 
            (@INVOICE = 'Y' AND R.INVOICE_ID IS NOT NULL)
            OR 
            (@INVOICE = 'ALL')
        )
    AND (
            (@VERIFIED = 'Y' AND ISNULL(COL.USER_5, 'N') = 'Y')
            OR 
            (@VERIFIED = 'N' AND ISNULL(COL.USER_5, 'N') = 'N')
            OR 
            (@VERIFIED = 'ALL')
        )
    AND (
            (@BOEING = 'Y')
            OR 
            (@BOEING = 'N' AND ISNULL(CO.CUSTOMER_ID, '_Blank') NOT LIKE 'BOE%')
        )
