


-- Invoice header → lines:
SELECT P.VOUCHER_ID, P.INVOICE_ID, PL.LINE_NO, PL.AMOUNT
FROM Live.dbo.PAYABLE P
JOIN Live.dbo.PAYABLE_LINE PL ON PL.VOUCHER_ID = P.VOUCHER_ID
WHERE P.VENDOR_ID = @VendorID;


-- Voucher → payments applied:
SELECT P.VOUCHER_ID, P.INVOICE_ID, CDL.AMOUNT AS AppliedAmt, CD.CHECK_DATE
FROM Live.dbo.PAYABLE P
LEFT JOIN Live.dbo.CASH_DISBURSE_LINE CDL ON CDL.VOUCHER_ID = P.VOUCHER_ID
LEFT JOIN Live.dbo.CASH_DISBURSEMENT CD
  ON CD.BANK_ACCOUNT_ID = CDL.BANK_ACCOUNT_ID AND CD.CONTROL_NO = CDL.CONTROL_NO
WHERE 
-- AND P.VOUCHER_ID = @VoucherId;

-- Voucher → GL distributions (posting lines):
SELECT P.VOUCHER_ID, PD.DIST_NO, PD.GL_ACCOUNT_ID, PD.AMOUNT
FROM Live.dbo.PAYABLE P
JOIN Live.dbo.PAYABLE_DIST PD ON PD.VOUCHER_ID = P.VOUCHER_ID
WHERE P.POSTING_DATE BETWEEN @Start AND @End;

-- Vendor lookup:
SELECT P.VOUCHER_ID, P.INVOICE_ID, V.ID, V.NAME
FROM Live.dbo.PAYABLE P
LEFT JOIN Live.dbo.VENDOR V ON P.VENDOR_ID = V.ID;