--VISUAL ENTERPRISE REPORTS/CUSTOMER SERVICE REPORTS/STATUS REPORTS/MFG CUSTOMER ORDERS
SELECT CO.CUSTOMER_ID
    , COL.PART_ID
    , CASE 
        WHEN COL.PART_ID IS NOT NULL THEN COL.PART_ID 
        WHEN COL.MISC_REFERENCE LIKE ('NR%')
            OR COL.MISC_REFERENCE LIKE ('%NON%')
            OR COL.MISC_REFERENCE LIKE ('TOOL%')
            OR COL.MISC_REFERENCE LIKE ('PROGRAM%')
            OR COL.MISC_REFERENCE LIKE ('SET%')
            OR COL.MISC_REFERENCE LIKE ('COST%')
            THEN 'NRE'
        WHEN COL.MISC_REFERENCE LIKE 'EXP%' THEN 'EXPEDITE' 
        ELSE 'UNKNOWN'
    END AS PART_ID2
    , COL.MISC_REFERENCE
    , CO.[STATUS]
    , COL.ORDER_QTY
    , CASE 
        WHEN COL.DESIRED_SHIP_DATE IS NOT NULL THEN COL.DESIRED_SHIP_DATE 
        ELSE CO.DESIRED_SHIP_DATE 
    END AS DUE_DATE
    , ISNULL(COL.DESIRED_SHIP_DATE, CO.DESIRED_SHIP_DATE) AS DESIRED_SHIP_DATE
    , COL.ORDER_QTY - COL.TOTAL_SHIPPED_QTY AS OPEN_QTY
    , COL.TOTAL_SHIPPED_QTY
    , COL.LINE_STATUS
    , CO.DESIRED_SHIP_DATE CO_DESIRED_SHIP_DATE
    , COL.CUST_ORDER_ID
    , P.BUYER_USER_ID
    , ISNULL(Salesperson_ID, '_BLANK') AS BUYER
    --, CASE 
    --WHEN ACCOUNT_HOLDER IS NULL THEN '_BLANK' 
    --ELSE ACCOUNT_HOLDER
    --END AS BUYER
    , COL.USER_10
    , CO.ORDER_DATE
    , CO.CUSTOMER_PO_REF
    , CA.CITY + ', ' + CA.STATE AS CITY_STATE
    , CA.COUNTRY
    , CASE 
        WHEN ADDR_2 LIKE '%HOLD%' THEN 'HOLD'
        WHEN CITY LIKE '%HOLD%' THEN 'HOLD' 
        WHEN CA.STATE IS NULL 
            AND CA.COUNTRY <> 'USA' 
            THEN CA.COUNTRY
        ELSE CA.STATE             
    END AS SHIP_TO
    , COL.CUST_ORDER_ID + '/' + CONVERT(VARCHAR(3),COL.LINE_NO) AS CO_LINE
    , CASE 
        WHEN COL.USER_2 IS NOT NULL THEN RIGHT(COL.USER_2,3)  
    END AS LINE_UDF2
    , CO.CUSTOMER_PO_REF + '_' + CASE 
        WHEN COL.USER_2 IS NOT NULL THEN COL.USER_2
    END AS PO_LINE
    , COL.USER_2
    , P.PLANNER_USER_ID
    , COL.PROMISE_DATE
FROM CUSTOMER_ORDER CO
LEFT OUTER JOIN CUST_ORDER_LINE COL
    ON CO.ID = COL.CUST_ORDER_ID
LEFT OUTER JOIN CUST_ADDRESS CA
    ON CO.CUSTOMER_ID = CA.CUSTOMER_ID
    AND CO.SHIP_TO_ADDR_NO = CA.ADDR_NO
--LEFT OUTER JOIN PART P
--    ON COL.PART_ID = P.ID
LEFT OUTER JOIN PART_SITE_VIEW P
                  ON COL.PART_ID = P.PART_ID
--LEFT OUTER JOIN LIVESUPPLEMENTAL.DBO.BUYER_ASSIGNMENTS BA
--    ON ACCOUNT = LEFT(P.BUYER_USER_ID, 2)
LEFT OUTER JOIN LIVESupplemental.dbo.buyer_assn BA
    ON Account_ID = LEFT(P.BUYER_USER_ID,2)
WHERE COL.LINE_STATUS <> 'C'
    AND COL.DESIRED_SHIP_DATE IS NOT NULL
    AND CO.STATUS IN ('R', 'H')
    AND COL.ORDER_QTY - COL.TOTAL_SHIPPED_QTY >0
--    AND P.PLANNER_USER_ID IN ('619M','MRP','NEW','PLAN','TTO')
    AND EXISTS
        (SELECT 1
        FROM LIVESupplemental.dbo.PLANNER_USER_ID_ReportSettings EX
        WHERE P.PLANNER_USER_ID = EX.PLANNER_USER_ID
        AND REPORT_NAME = 'MFG Customer Orders'
        )
    AND CASE 
        WHEN Salesperson_ID IS NULL THEN '_BLANK' 
        ELSE Salesperson_ID
    END IN (@buyer)
