-- DDL template: LIVE.dbo.CUST_ORDER_LINE
CREATE TABLE dbo.CUST_ORDER_LINE (
    CUST_ORDER_ID    VARCHAR(50) NOT NULL,
    LINE_NO          INT NOT NULL,
    PART_ID          VARCHAR(100) NULL,
    PRIMARY KEY (CUST_ORDER_ID, LINE_NO)
);
