-- DDL template: LIVE.dbo.INV_TRANS_DIST
CREATE TABLE dbo.INV_TRANS_DIST (
    DIST_ID      INT IDENTITY(1,1) PRIMARY KEY,
    OUT_TRANS_ID VARCHAR(50) NULL,
    IN_TRANS_ID  VARCHAR(50) NULL,
    DEMAND_SUPPLY_ID VARCHAR(50) NULL
);
