-- DDL template: LIVE.dbo.INVENTORY_TRANS
CREATE TABLE dbo.INVENTORY_TRANS (
    TRANSACTION_ID   VARCHAR(50) NOT NULL PRIMARY KEY,
    TRANSACTION_DATE DATETIME NULL,
    [CLASS]          NVARCHAR(10) NULL,
    [TYPE]           NVARCHAR(10) NULL,
    CUST_ORDER_ID    VARCHAR(50) NULL,
    CUST_ORDER_LINE_NO INT NULL,
    WORKORDER_TYPE   VARCHAR(50) NULL,
    WORKORDER_BASE_ID VARCHAR(50) NULL,
    WORKORDER_LOT_ID VARCHAR(50) NULL,
    WORKORDER_SPLIT_ID VARCHAR(50) NULL
);
