-- DDL template: LIVE.dbo.RECEIVABLE_LINE
CREATE TABLE dbo.RECEIVABLE_LINE (
    RECEIVABLE_LINE_ID INT IDENTITY(1,1) PRIMARY KEY,
    INVOICE_ID         VARCHAR(50) NOT NULL,
    PACKLIST_ID        VARCHAR(100) NULL,
    CUST_ORDER_ID      VARCHAR(50) NULL,
    CUST_ORDER_LINE_NO INT NULL,
    AMOUNT             DECIMAL(18,2) NULL,
    REFERENCE          VARCHAR(255) NULL,
    -- add other columns as required
    CONSTRAINT FK_RECEIVABLE_LINE_RECEIVABLE FOREIGN KEY (INVOICE_ID) REFERENCES dbo.RECEIVABLE(INVOICE_ID)
);
