-- DDL template: SHIPPER_LINE
CREATE TABLE dbo.SHIPPER_LINE (
    SHIPPER_LINE_ID INT IDENTITY(1,1) PRIMARY KEY,
    PACKLIST_ID     VARCHAR(100) NULL,
    TRANSACTION_ID  VARCHAR(50) NULL,
    LINE_NO         INT NULL
);
