SELECT CO.CUSTOMER_ID
    , CO.CREATE_DATE
    , CO.ID
    , CO.[STATUS] AS CO_STATUS
    , CAST(CAST(N.[NOTE] AS VARBINARY(MAX)) AS NVARCHAR(MAX)) AS NOTES
    , WO.BASE_ID
    , WO.LOT_ID
    , WO.SPLIT_ID
    , WO.SUB_ID
    , WO.[STATUS] AS WO_STATUS
FROM CUSTOMER_ORDER CO
LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL
    ON DSL.DEMAND_TYPE = 'CO' 
    AND DSL.DEMAND_BASE_ID = CO.ID
LEFT OUTER JOIN WORK_ORDER WO
    ON DSL.SUPPLY_BASE_ID = WO.BASE_ID
    AND DSL.SUPPLY_LOT_ID = WO.LOT_ID
    AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID
    AND DSL.SUPPLY_SUB_ID = WO.SUB_ID 
LEFT OUTER JOIN NOTATION N
    ON N.[TYPE] = 'CO'
    AND N.[OWNER_ID] = CO.ID
WHERE CO.[STATUS] = 'X'
    AND CO.CREATE_DATE >= @SINCEDATE
    AND CO.CUSTOMER_ID IN (@CUSTID)

