SELECT SALESREP_ID
    , ACTIVE_FLAG
    , ID
    , [NAME]
    , ADDR_1
    , ADDR_2
    , CITY
    , [STATE]
    , COUNTRY
    , CONTACT_PHONE
FROM CUSTOMER
WHERE ACTIVE_FLAG = @FLAG
AND SALESREP_ID IN (@SALESREP_ID)
