SELECT E.EQUIPMENT_ID
    , E.[NAME] AS EQUIP_NAME
    , E.BUSINESS_UNIT_ID
    , ET.[NAME] AS EQUIP_TYPE
    , E.MAJOR_LOCATION
    , E.MINOR_LOCATION
    , MIL.[DESCRIPTION] AS MINOR_DESC
    , E.COMMENTS
    , E.[STATUS]
    , E.MANUFACTURER_NAME
    , E.MODEL_NUMBER
    , E.SERIAL_NUMBER
FROM [dbo].[VQ_EQUIPMENT] E
LEFT OUTER JOIN [dbo].[VQ_MAJOR_LOCATION] MAJ
    ON E.MAJOR_LOCATION = MAJ.MAJOR_LOCATION
LEFT OUTER JOIN [dbo].[VQ_MINOR_LOCATION] MIL
    ON E.MINOR_LOCATION = MIL.MINOR_LOCATION
LEFT OUTER JOIN [dbo].[VQ_EQUIPMENT_TYPE] ET
    ON ET.[RECORD_ID] = E.[EQUIPMENT_TYPE_REC_ID]
