SELECT        P.PREVENTIVE, P.ERP_ID2, P.COMPONENT_NUMBER, EC.NAME AS PM_ACT_TYPE, 
                         CASE WHEN P.RESULT = 'F' THEN 'Failed' WHEN P.RESULT = 'PA' THEN 'Passed' WHEN P.RESULT = 'PE' THEN 'Pending' WHEN P.RESULT = 'S' THEN 'Status' ELSE 'ISSUES' END AS RESULT, P.DUE_DATE, 
                         E.EQUIPMENT_ID, E.NAME AS EQUIP_NAME, E.MAJOR_LOCATION, MAJ.DESCRIPTION AS MAJOR_DESC, E.MINOR_LOCATION, MIL.DESCRIPTION AS MINOR_DESC, E.BUSINESS_UNIT_ID, E.COMMENTS, 
                         ISNULL(C.INSTRUCTIONS, EC.INSTRUCTIONS) AS INSTRUCTIONS, 
                         CASE WHEN P.[MAINTAINED_BY] = 'I' THEN 'INTERNAL' WHEN P.[MAINTAINED_BY] = 'C' THEN 'CUSTOMER' WHEN P.[MAINTAINED_BY] = 'S' THEN 'SUPPLIER' ELSE NULL END AS MAINTAINED_BY, P.EMPLOYEE_REC_ID, 
                         EE.FIRST_NAME + ' ' + EE.LAST_NAME AS EMPLOYEE, P.CUSTOMER_REC_ID, CUST.NAME AS CUSTOMER, P.SUPPLIER_REC_ID, S.NAME AS SUPPLIER, P.USER_DEFINED_3, C.NEXT_DATE
FROM            VQ_PREVENTIVE AS P LEFT OUTER JOIN
                         VQ_EQUIPMENT AS E ON P.EQUIPMENT_REC_ID = E.RECORD_ID LEFT OUTER JOIN
                         VQ_EQUP_TYPE_COMP AS EC ON E.EQUIPMENT_TYPE_REC_ID = EC.EQUIPMENT_TYPE_REC_ID AND P.COMPONENT_NUMBER = EC.COMPONENT_NUMBER LEFT OUTER JOIN
                         VQ_COMPONENTS AS C ON P.EQUIPMENT_REC_ID = C.EQUIPMENT_REC_ID AND P.COMPONENT_NUMBER = C.COMPONENT_NUMBER LEFT OUTER JOIN
                         VQ_MAJOR_LOCATION AS MAJ ON E.MAJOR_LOCATION = MAJ.MAJOR_LOCATION LEFT OUTER JOIN
                         VQ_MINOR_LOCATION AS MIL ON E.MINOR_LOCATION = MIL.MINOR_LOCATION LEFT OUTER JOIN
                         VQ_EMPLOYEE AS EE ON EE.RECORD_ID = P.EMPLOYEE_REC_ID LEFT OUTER JOIN
                         VQ_CUSTOMER AS CUST ON CUST.RECORD_ID = P.CUSTOMER_REC_ID LEFT OUTER JOIN
                         VQ_SUPPLIER AS S ON S.RECORD_ID = P.SUPPLIER_REC_ID
WHERE        (CASE WHEN P.RESULT = 'F' THEN 'Failed' WHEN P.RESULT = 'PA' THEN 'Passed' WHEN P.RESULT = 'PE' THEN 'Pending' WHEN P.RESULT = 'S' THEN 'Status' ELSE 'ISSUES' END IN (@RESULT)) AND (ISNULL(E.NAME, 
                         N'_BLANK') IN (@EQUIPNAME)) AND (ISNULL(E.MAJOR_LOCATION, N'_BLANK') IN (@MAJOR)) AND (ISNULL(E.MINOR_LOCATION + '-' + MIL.DESCRIPTION, N'_BLANK') IN (@MINOR)) AND (ISNULL(E.BUSINESS_UNIT_ID, 
                         N'_BLANK') IN (@BUSUNIT)) AND (CASE WHEN P.[MAINTAINED_BY] = 'I' THEN 'INTERNAL' WHEN P.[MAINTAINED_BY] = 'C' THEN 'CUSTOMER' WHEN P.[MAINTAINED_BY] = 'S' THEN 'SUPPLIER' END IN (@MAINTAINBY)) AND 
                         (ISNULL(EE.LAST_NAME + ', ' + EE.FIRST_NAME, N'_BLANK') IN (@EE)) AND (ISNULL(CUST.NAME, N'_BLANK') IN (@CUSTOMER)) AND (ISNULL(S.NAME, N'_BLANK') IN (@SUPPLIER)) AND (ISNULL(P.USER_DEFINED_3, 
                         N'_BLANK') IN (@USERDEFINED3))
