--HOME > INFORMATION SYSTEMS REPORTS > DATAWAREHOUSE SYNC INFO

SELECT J.[NAME]
    , J.[DESCRIPTION]
    , S.STEP_NAME
    , CAST(CAST(S.LAST_RUN_DATE AS CHAR(8)) + ' ' 
        + REVERSE(STUFF(STUFF(REVERSE(S.LAST_RUN_TIME), 3, 0, ':'), 6, 0, ':')) AS DATETIME) AS LASTRUN
    , A.NEXTRUN
    , S.LAST_RUN_OUTCOME
    , S.STEP_ID
FROM SYSJOBS_VIEW J
JOIN SYSJOBSTEPS S
    ON S.JOB_ID = J.JOB_ID
JOIN 
    (SELECT JOB_ID, MAX(NEXT_SCHEDULED_RUN_DATE) NEXTRUN
    FROM SYSJOBACTIVITY
    GROUP BY JOB_ID
    ) A
    ON A.JOB_ID = J.JOB_ID
WHERE NAME LIKE 'DWH%'
AND NAME <> 'DWH – Tester'
