SELECT PL.PART_ID
    , PL.LOCATION_ID
    , PL.QTY
    , PL.WAREHOUSE_ID
    , CCP.LAST_COUNT_DATE
    , PS.UNIT_MATERIAL_COST
    , PS.UNIT_LABOR_COST
    , PS.BURDEN_PER_UNIT
    , PS.UNIT_SERVICE_COST
FROM PART_SITE PS
INNER JOIN PART_LOCATION PL 
    ON PS.PART_ID=PL.PART_ID
LEFT OUTER JOIN CYCLE_COUNT_PART CCP
    ON PL.WAREHOUSE_ID = CCP.WAREHOUSE_ID
    AND PL.PART_ID = CCP.PART_ID
WHERE  PL.QTY <> 0
